### ISSUE TITLE
Stop song at the end, disable automatic jump to the next song

### ISSUE THREAD

**Issue by balazskiss** [spotify/ios-sdk#10]
I'd like to start one song and stop music playback when that one song ends. Is there a way to do this? Spotify automatically jumps to the next one, but I don't want that.

**Comment by jackfreeman** [comment]
This is currently not an available feature. You might be able to detect when the track changes and pause the music however.

**Comment by kbirch** [comment]
My feature request here would be to have more detail inside of SPTAppRemotePlayerState that the delegate receives on a state change - playback started, playback ended, playback failed, etc.  I see that it fires a number of times when songs are changing (3 or 4) so I assume those represent some player lifecycle changes behind the scenes?  Great if we can get detail on what has happened to cause a state change notification, and yes detecting track changes is at least partially helpful as an interim workaround.
