### ISSUE TITLE
Google cast support

### ISSUE THREAD

**Issue by parth0072** [spotify/ios-sdk#106]
Is this Spotify SDK support the google cast?

actually, we are building the app which supports the cast feature with using the Spotify SDK.
but seems like Spotify SDK is not providing the casting support.

**Comment by kkarayannis** [comment]
While the main Spotify app does support Google Cast, the SDK does not. We take it into consideration for future features.

**Comment by parth0072** [comment]
No actually, spotify app does support google cast.
If you go into device list you will able to find the google home device in the list and you can play song on that device also
