### ISSUE TITLE
Hi @Anders27 @arirawr , Thank you for your suggestion.

### ISSUE THREAD

**Issue by AnandPGautam** [spotify/ios-sdk#107]
Hi @Anders27 , Thank you for your suggestion. 

Currently I am using SpotifyAudioPlayback, SpotifyAuthentication and SpotifyMetadata framework in my App. Now I have downloaded Spotify iOS Streaming SDK Beta 27 (SpotifyiOS framework). But when I am comparing the Header classes then it's not similar. Like we don't have SPTYourMusic.h/SPTPlaylistList.h/SPTPlaylistTracks.h header classes in the newer SDK. 

How to do merge now? Please suggest..

_Originally posted by @AnandPGautam in https://github.com/spotify/ios-sdk/issues/12#issuecomment-470435094_

**Comment by Anders27** [comment]
I think you are doing something wrong.
SpotifyMetadata framework Beta 27 contains SPTYourMusic.h/SPTPlaylistList.h/SPTPlaylistTracks.h etc as it always did.

**Comment by AnandPGautam** [comment]
There was mistake on Downloading the framework. Sorry to disturb you :(

**Comment by arirawr** [comment]
Glad to hear you got this resolved :)
