### ISSUE TITLE
User's music

### ISSUE THREAD

**Issue by DiegoResnik** [spotify/ios-sdk#11]
Is there a way to get the user's playlists / favorites / recommendations so he can choose what to play?

**Comment by jackfreeman** [comment]
@DiegoResnik please see [fetchRecommendedContentItemsForType: on SPTAppRemoteContentAPI](https://spotify.github.io/ios-sdk/html/Protocols/SPTAppRemoteContentAPI.html#//api/name/fetchRecommendedContentItemsForType:callback:)

You can also see how to use this api by looking at the [NowPlayingView sample project](https://github.com/spotify/ios-sdk/tree/master/DemoProjects), and more specificially [ContentCollectionViewController.swift](https://github.com/spotify/ios-sdk/blob/master/DemoProjects/NowPlayingView/NowPlayingView/ContentCollectionViewController.swift)

If you would prefer to use the [Web API](https://developer.spotify.com/documentation/web-api/reference/library/) for this there are also several end points there as well.

**Comment by tiagomendesEye** [comment]
Hey @DiegoResnik check if this help you

after you have a valid session you can do this:

```
        ...
        NSString *token = auth.session.accessToken;
        NSString *tokenType = auth.session.tokenType;
        
        NSString *header = [NSString stringWithFormat:@"%@ %@", tokenType, token];
        NSMutableURLRequest *request = [[NSMutableURLRequest alloc] init];
        NSURL *url = [NSURL URLWithString:@"https://api.spotify.com/v1/me/tracks"];

        [request setValue:header forHTTPHeaderField:@"Authorization"];
        [request setURL:url];
        
        NSURLSession *session = [NSURLSession sessionWithConfiguration:[NSURLSessionConfiguration defaultSessionConfiguration]];
        [[session dataTaskWithRequest:request completionHandler:^(NSData * _Nullable data, NSURLResponse * _Nullable response, NSError * _Nullable error) {
            if (!error) {
                NSDictionary *json = [NSJSONSerialization JSONObjectWithData:data options:0 error:nil];
                NSLog(@"%@",json);
            }
        }] resume];
```

P.S : The auth.session.tokenType was done using the old SDK

**Comment by jackfreeman** [comment]
@DiegoResnik unfortunately the only sample app that uses this API is in Swift at the moment, but the objective-c implementation should be almost the same except for syntax.
