### ISSUE TITLE
shuffle issue

### ISSUE THREAD

**Issue by shavik** [spotify/ios-sdk#110]
I tried playerApi.setShuffle but it does not shuffle within the Playlist I am playing, the shuffle gives me songs which are not present in the playlist.

**Comment by arirawr** [comment]
Hi @shavik , are you using a free or premium account to test?

**Comment by shavik** [comment]
I am using the free version of Spotify.

**Comment by arirawr** [comment]
Could you check the account's permissions using [this function](https://spotify.github.io/ios-sdk/html/Protocols/SPTAppRemotePlaybackRestrictions.html)? It is possible that you are unable to shuffle due to playback restrictions on free accounts.

**Comment by shavik** [comment]
Yes i have all the permissions, the issue is I things playlist has more than 500 track and the tracks I am fetching from playlist/{id}/tracks API only 100 due to max limit. can you suggest something more robust, instead of fetching all the 500+ tracks.
