### ISSUE TITLE
 10 second forward or backward in Spotify player

### ISSUE THREAD

**Issue by dhimansham** [spotify/ios-sdk#111]
I am trying to add(move forward) 10 second song duration or minus(move backward) 10 second in Spotify player but i am really confused how to add or minus.

When i m trying to use this code the song is not changed duration. and player hanged, they didn't any response

    @IBAction func moveFrdBtnAction(_ sender: Any) {
      SpotifyManager.shared.audioStreaming(SpotifyManager.shared.player, didSeekToPosition: TimeInterval(10))
    }

    func audioStreaming(_ audioStreaming: SPTAudioStreamingController!, didSeekToPosition position: TimeInterval) {
        player?.seek(to: position, callback: { (error) in
            let songDuration = audioStreaming.metadata.currentTrack?.duration as Any as! Double
            self.delegate?.getSongTime(timeCount: Int(songDuration)+1)
        })
    }

Can someone please explain to me how to solve this , i've tried to solve this  but no results yet.

Any help would be greatly appreciated.

Thanks in advance.

**Comment by dhimansham** [comment]
Hello Spotify team please reply as soon as possible
Thank you

**Comment by kkarayannis** [comment]
Does this question refer to the [Streaming SDK](https://github.com/spotify/ios-streaming-sdk) instead of this one? 
Please note that the Streaming SDK is deprecated and no longer supported.
