### ISSUE TITLE
How to play chosen track in playlist and rest all the track played sequentially

### ISSUE THREAD

**Issue by shavik** [spotify/ios-sdk#113]
I am getting the playlist and playing it, and simultaneously showing all the tracks in a collection view. I want user can select any track and play it. After the track ends, the next song should start playing which happens in Spotify APP, but no API exposed to make an app work like that using SPotify SDK.

To select a song I am enqueuing the selected track, and after getting the callback result calling 
 playerAPI.skip(toNext:), this start playing the selected song but it's not the correct solution, as song ends it does not go to next song after that track.

**Comment by nicoletapop** [comment]
Hi @shavik I got the same problem. If I select a track from the playlist, I basically create another queue in which that track is the only element. The solution I was thinking is to enqueue the rest of the tracks in the current one but that means if I play the 5th track in the playlist, the first 4 tracks will be enqueued after the 5th and that is bad user experience. Unfortunately, it doesn't exist any method to get the current queue nor to try to sort it taking into account that it is saved locally on the device. Have you managed to find a proper solution?

**Comment by nicoletapop** [comment]
@arirawr @jackfreeman @j-hit what is the difference between playerAPI play and playerAPI playItem? Is the latter creating a queue with only one track too? Can you please give us an explanation regarding this issue?

**Comment by nicoletapop** [comment]
Hi @shavik, thank you very much for your quick response. I will try it and let you know. Happy coding :)

**Comment by nicoletapop** [comment]
It worked! Thank you very much again and have a nice day! 💃

**Comment by Farrukh-Salman** [comment]
Hi, @shavik , Can you please tell me how you are doing that. I have all the playlist info,URI but when give URI to above "enqueueTrackUri" method it doesn't play my song instead it plays any other song. Can you explain briefly how you are doing that.

**Comment by kkarayannis** [comment]
Please check `playItem:skipToTrackIndex:callback:` in `SPTAppRemotePlayerAPI` as it should do what you need. This is a new method added in the latest SDK release, v.1.0.2.

Please find more details [here](https://github.com/spotify/ios-sdk/blob/master/SpotifyiOS.framework/Versions/A/Headers/SPTAppRemotePlayerAPI.h#L74).

**Comment by shavik** [comment]
The code I suggested above works when you are already playing a playlist, want to switch to any song in that playlist.

**Comment by hspinks** [comment]
@kkarayannis thank you, this is helpful! Do you have any advice on how to use this with a specific Spotify URI? The method expects the first param to be an `id<SPTAppRemoteContentItem>`, and while I see that there are [some methods](https://spotify.github.io/ios-sdk/html/Protocols/SPTAppRemoteContentAPI.html) from SPTAppRemoteContentAPI for getting content items by type, I don't see a good way to get a content item from a Spotify URI... I suppose I could try to construct an object that conforms to the content item protocol by querying the web API for the Spotify URI, but that would defeat the purpose of using this SDK for offline modes...

Specifically, my use case would be that I already know the Spotify URI of the playlist that I want to play, and I want to start playback at a specific index in that playlist. I would appreciate anyone's advice on how to get this to work!

**Comment by CoderAFI** [comment]
how to get the index?
