### ISSUE TITLE
AppRemote Connect Fail

### ISSUE THREAD

**Issue by aroe01** [spotify/ios-sdk#114]
Hi Spotify,

I'm having an issue with AppRemote.connect().  Sometimes after a successful SessionManager didInitiate I try to set the appremote.accesstoken and then appremote.connect but after redirecting to the Spotify and back to my app I receive this:

Spotify didFailConnectionAttemptWithError Optional(Error Domain=com.spotify.app-remote Code=-1000 "Connection attempt failed." UserInfo={NSLocalizedDescription=Connection attempt failed., NSUnderlyingError=0x282a1c0f0 {Error Domain=com.spotify.app-remote.transport Code=-2000 "Stream error." UserInfo={NSLocalizedDescription=Stream error., NSUnderlyingError=0x282a1c090 {Error Domain=NSPOSIXErrorDomain Code=61 "Connection refused" UserInfo={_kCFStreamErrorCodeKey=61, _kCFStreamErrorDomainKey=1}}, NSLocalizedRecoverySuggestion=Reconnect the transport to the Spotify app., NSLocalizedFailureReason=A stream error has occured in the transport.}}, NSLocalizedRecoverySuggestion=Ensure the Spotify app is installed, and try to reconnect., NSLocalizedFailureReason=Could not connect to the Spotify app.})

Even though I am currently listening to music in the Spotify App.  I have set the configuration.playURI to "" and I have the requested scope to be:
.appRemoteControl, .playlistReadPrivate.  I'm testing with Xcode 10.2 and an iPhone X with 12.1.4

If I restart Spotify I am able connect again, and this only seems to happen once a day or so.

Any suggestions for further debugging or solutions would be greatly appreciated.

Thank you!

**Comment by oliverleopold** [comment]
I'm also having this problem.

**Comment by j-hit** [comment]
I also regularly get this error. At first I thought I was doing something wrong in my app.

But now as I got this error in my app, I downloaded the "NowPlayingView" sample app from this repo and launched it. **I also get the exact same error in the sample app!**

As @aroe01 mentioned, after killing the Spotify app, the sample app can connect again, as well as my own app.

Who else sees this issue from time to time? How can we work around it? Don't want to have to tell users to kill the Spotify app 😅

**Comment by haikusw** [comment]
Similar issue (macOS 10.14.6, Xcode 11.0 GM, and also macOS 10.14.6, Xcode 12.3):

> NowPlayingView: AppRemote: Connecting...
> NowPlayingView: [] nw_socket_handle_socket_event [C1.1:1] Socket SO_ERROR [61: Connection refused]
> NowPlayingView: AppRemote: Established a connection to the Spotify app.

And status is pulsing orange.

Sometimes I get:


> NowPlayingView: AppRemote: Connecting...
> NowPlayingView: [] nw_socket_handle_socket_event [C1.1:1] Socket SO_ERROR [61: Connection refused]
> NowPlayingView: [] nw_socket_handle_socket_event [C1.2:1] Socket SO_ERROR [61: Connection refused]
> NowPlayingView: [] nw_connection_get_connected_socket [C1] Client called nw_connection_get_connected_socket on unconnected nw_connection
> NowPlayingView: TCP Conn 0x283121740 Failed : error 0:61 [61]
> NowPlayingView: AppRemote: Failed connection attempt with error: Error Domain=com.spotify.app-remote.transport Code=-2000 "Stream error." UserInfo={NSLocalizedDescription=Stream error., NSUnderlyingError=0x280a70d50 {Error Domain=NSPOSIXErrorDomain Code=61 "Connection refused" UserInfo={_kCFStreamErrorCodeKey=61, _kCFStreamErrorDomainKey=1}}, NSLocalizedRecoverySuggestion=Reconnect the transport to the Spotify app., NSLocalizedFailureReason=A stream error has occured in the transport.}
didFailConnectionAttemptWithError

**Comment by WickedChicken42** [comment]
Hey there, I'm the author of #149 and experiencing the same issue however the suggested shutdown of the Spotify app is not having any impact on my being able to reconnect.

**Comment by haikusw** [comment]
@WickedChicken42 
> Update: However shutting down Spotify, starting it back up AND playing a track will allow my app to connect.
Is this with your app still running while you do this or are you killing your app, doing this, and relaunching your app?  TIA.

**Comment by rugoso** [comment]
HELP!, with the Spotify app version 8.5.22 can't connect with the spotify app no matter what I do ... I used to connect, then did the update, then could not connect any more. I know it was the update cuz I first noticed this on my phone, that had the latest update ... then tried on my ipad with the previous version and it connected, then did the update there, and now I can't connect  ... haven't got into the code yet ... just trying to see if anyone has this problem with Spotify app version 8.5.22 ...? also can't seem to connect with NowPlayingView app, no matter what

**Comment by rugoso** [comment]
Can any of you confirm that you are connecting with the Spotify app version 8.5.22 (or newer) ...?

**Comment by haikusw** [comment]
I got the app to say it connected at one point, but it didn't seem to call the callback in the NowPlaying sample to update the UI so I don't know if it really connected or not.  You might notice in the console log I posted above that it _says_ it connected but there's an error and it didn't really connect as far as I can tell.  I haven't gone through and tried to debug their demo app yet, but things don't look good.  The lack of replies or any updates to this sdk in 5 months makes it seem like they really don't care about this SDK much at all. ¯\_(ツ)_/¯

**Comment by rugoso** [comment]
I just got to connect with version 8.5.22 ONCE but not anymore, and I don't know why yet ... will keep trying ... they just replied to issue #146 a few days ago so maybe they are still kinda working on this ...??

**Comment by haikusw** [comment]
That issue doesn't seem directly related to me.  Does make it sound like they might care a little, which would be good.

**Comment by WickedChicken42** [comment]
I can only get it to connect if I have shutdown my app and Spotify.  Once connected I seem to be OK as my app will reconnect from time to time (When an Apple Music track has played).  If I start my app (and then my app starts Spotify), if it doesn't connect bouncing over to the Spotify app to play a track does not make things happy.  I have to start from a position where both my app and Spotify are shutdown.

**Comment by rugoso** [comment]
Just opened a new issue (#150) trying to explain this new issue.

**Comment by kkarayannis** [comment]
Hi! I've posted about the recent issues connecting App Remote to Spotify over at #150.

**Comment by kkarayannis** [comment]
Version 8.5.25 should fix most people's issue. I'm not sure what the original poster's issue from April was but until there are some new details or confirmation that the issue still exists I'm closing this issue.

**Comment by bryanhpchiang** [comment]
Getting the same issue. I downloaded the sample application, and it works perfectly -- not sure what I could be doing wrong on my end?

**Comment by nguyen-tam** [comment]
same issue happens with Spotify 8.5.51.877.

**Comment by intonarumori** [comment]
+1

**Comment by avdgriendt** [comment]
I'm also having this problem can someone from Spotify please fix this?

**Comment by hsmith825** [comment]
Same issue

**Comment by zallanx** [comment]
Same issue

**Comment by yingtao-futurewonder** [comment]
The same issue happens with Spotify 8.5.74

**Comment by jkichline** [comment]
Why are Spotify's SDK so frustratingly ridiculous? Are they planning to fix this or should I just remove Spotify integration? It is so unstable to be laughable.

**Comment by hsmith825** [comment]
Same issue with Spotify 8.5.86.739

**Comment by farad4y** [comment]
Same Issue

**Comment by roz0n** [comment]
Any fix?

**Comment by mcm-gr** [comment]
?

**Comment by somparkash** [comment]
Still waiting for fix...

**Comment by dagnorland** [comment]
I am experiencing same issues... it seems useless on ios. android is working nice

**Comment by ingaintent** [comment]
Same Issue :(

**Comment by zallanx** [comment]
Same issue. And this issue should not be closed. It still persists to this date.

**Comment by zallanx** [comment]
After a lot of testing. a potential workaround (tested on iOS) is:

- suppose you need to play tracks `track1`, track2` and `track3` 
- you want to maximize the chance that the AppRemote isn't disconnected so you can successfully enqueue `track2` and `track3`

What I have works is to call `self.appRemote.authorizeAndPlayURI("track_1_uri")` first (the function `authorizeAndPlayURI` always works because it is needed to "wake up" Spotify)

Then, wait 8 seconds or so (tbh, 8 seconds may be overkill on newer devices, but seems to hit the sweet spot for waking up Spotify when it comes to older devices)

Then, call your `appRemote` functions like enqueue, etc. 

AppRemote at this point will almost always be connected, and you will be able to perform the needed functions.

Hope this helps.

**Comment by ViktorKirjanov** [comment]
Still not fixed?

**Comment by haashem** [comment]
And it's not gonna fix for next 5 years! 

I have the same issue! the connection drops after pausing the music for 10 seconds!

**Comment by kamanov** [comment]
started working after
`config.playURI = ""`

**Comment by Eugenezamora** [comment]
I have the same problem! Connection lost after pausing music for a few seconds!
