### ISSUE TITLE
Spotify iOS SDK play specific track from playlist.

### ISSUE THREAD

**Issue by Farrukh-Salman** [spotify/ios-sdk#118]
I have been building a music app which integrates Spotify SDK in iOS. every thing is working fine but the problem is  when I have to play a specific song from a playlist by clicking on that song I am unable to do that and song doesn't play, even I can retrieve information about that specific song but unable to play.
I am using the Spotify iOS SDK version 1.0.2

**Comment by kkarayannis** [comment]
Hi @Farrukh-Salman have you tried calling `playItem:skipToTrackIndex:callback:` in `SPTAppRemotePlayerAPI`?

Please find more details [here](https://github.com/spotify/ios-sdk/blob/master/SpotifyiOS.framework/Versions/A/Headers/SPTAppRemotePlayerAPI.h#L74).

**Comment by Farrukh-Salman** [comment]
> Hi @Farrukh-Salman have you tried calling `playItem:skipToTrackIndex:callback:` in `SPTAppRemotePlayerAPI`?
> 
> Please find more details [here](https://github.com/spotify/ios-sdk/blob/master/SpotifyiOS.framework/Versions/A/Headers/SPTAppRemotePlayerAPI.h#L74).

Thanks @kkarayannis . I have tried this solution but the index that I passed, it didn't play that song but played different song  from same playlist. When checked the selected index and title it was same which I selected. I am using basic account its not premium.

**Comment by kkarayannis** [comment]
> I am using basic account its not premium.

Ah then that's the reason why. Like in the main Spotify app, free users can't play any track on demand and instead have Shuffle turned on.

**Comment by Farrukh-Salman** [comment]
> > I am using basic account its not premium.
> 
> Ah then that's the reason why. Like in the main Spotify app, free users can't play any track on demand and instead have Shuffle turned on.

Thanks @kkarayannis . I have got the premium account now, and now its working fine on Albums, Artist, Songs but If I select a playlist then, it doesn't play that song instead always starts with first one. So is there any difference between playlist and Album?

**Comment by kkarayannis** [comment]
There shouldn't be any difference. If you send me the link of a playlist with this problem I'll take a look.

**Comment by Farrukh-Salman** [comment]
@kkarayannis Here is the link :

**Comment by Farrukh-Salman** [comment]
Hi, @kkarayannis did you get a chance to look into it?, so for I didn't get success in it.

**Comment by kkarayannis** [comment]
Hi @Farrukh-Salman, sorry for the delayed reply but I found some time to look into this today. I didn't find any problems when I tried with your playlist. Could you share how you call `playItem:skipToTrackIndex:callback:`?

**Comment by Farrukh-Salman** [comment]
> Hi @Farrukh-Salman, sorry for the delayed reply but I found some time to look into this today. I didn't find any problems when I tried with your playlist. Could you share how you call `playItem:skipToTrackIndex:callback:`?

Hi @kkarayannis no worries. Thanks for the response. It's working fine. :)

**Comment by kkarayannis** [comment]
Awesome! Closing this issue for now then. Let me know if issues come up in the future.

**Comment by Farrukh-Salman** [comment]
> Awesome! Closing this issue for now then. Let me know if issues come up in the future.

Sure. Thanks @kkarayannis
