### ISSUE TITLE
Using Spotify ios-sdk with React Native

### ISSUE THREAD

**Issue by JakeMotta** [spotify/ios-sdk#119]
Does anyone have any examples or reference material for using this sdk with React Native? I've got everything setup up in my project (to the best of my knowledge), but I still am having trouble with bridging between RN and this sdk. 

Any help or advice is appreciated. :)

**Comment by hspinks** [comment]
check out https://github.com/cjam/react-native-spotify-remote - I'd been looking for the same, and came across that repo. Just getting things set up, but been pretty easy to work with so far!
