### ISSUE TITLE
Existing iOS SDK – Playlist Access is Broken (401 error – Invalid Playlist URI)

### ISSUE THREAD

**Issue by zackfletch00** [spotify/ios-sdk#12]
Issue Type:  Bug
Spotify iOS SDK Version:  Beta 25
**User Impact:  Severe**
Reproducibility:  100% (first observed 9/11/2018 8:00am CDT)

When passing in a playlist URI given by a `SPTPartialPlaylist` object to a request for promotion to a `PlaylistSnapshot` object, a 401 error is returned and users cannot view their playlist tracks, play songs from their playlists, or add and remove tracks.   Along with the 401, an error reason of "Invalid Playlist URI" is given.

Example of URI provided by `SPTPartialPlaylist`:  "spotify:playlist:0tLwSYR5m7BxP9uxKHfhK1"
Broken SDK method call:  `[SPTPlaylistSnapshot playlistWithURI: accessToken: market: callback: ]`

Error output obtained in the callback block:  `Error Domain=com.spotify.ios-sdk Code=401 "Invalid Playlist URI" UserInfo={NSLocalizedDescription=Invalid Playlist URI}`

Judging by the changes to this GitHub project, I can tell that no work continues on the 2014-2018 'iOS SDK'.  However, this is still where [developer.spotify.com points developers to](https://developer.spotify.com/documentation/ios-sdk/#issues) to report issues with the existing iOS SDK (as well as the new Remote SDK).  Any help resolving this would be appreciated– **hundreds of active Premium users in production are potentially affected by this issue today.**

Thanks in advance!

**Comment by Anders27** [comment]
I see the same problem with my app.
My inbox is flooded with complaints from users.
Please fix this bug as fast as possible.

**Comment by markd2** [comment]
Same here.

**Comment by jackfreeman** [comment]
For clarification this issue is related to the streaming SDK which has moved to https://github.com/spotify/ios-streaming-sdk

**Comment by markd2** [comment]
@arirawr Hi!  I noticed you labeled this is a bug.  Do we need to put this issue over on ios-streaming-sdk, or is it ok living here?

**Comment by markd2** [comment]
@jackfreeman I see that this is a new SDK today (totes congrats on shipping!).  If we're wanting to play music in our apps is this new SDK the one to use, or continue using the ios-streaming-sdk?   

Specifically I am wanting to take an arbitrary set of `spotify:` urls and play them sequentially, along with visualization inside my app.  For Premium members.

**Comment by jackfreeman** [comment]
@markd2 this would be the recommended SDK to use moving forward, but as a heads up it works a bit differently than the streaming SDK. 

The main differences are: 
- Playback happens through the Spotify app, this means the Spotify app must be installed to stream music. Additionally, since the Spotify app controls the audio, you will be more limited in working with the audio signal at a low level.
- This SDK works for both Premium and Free users (the streaming one is only for Premium)
- There are no wrapped Web-API endpoints, meaning you will have to construct and parse requests yourself if you wish to communicate with the Web-API (Metadata and other info can still be obtained from built-in methods that communicate with the Spotify app however).

**Comment by zackfletch00** [comment]
Update:  As of roughly 6-7pm CDT and later, the issue appears to have resolved, and a pause of customer feedback emails confirms this elsewhere as well.  A huge thank-you to anyone out there who helped raise attention for this issue or helped resolve compatibility on the API side.

This issue can be considered closed unless/until the issue appears again.

**Comment by arirawr** [comment]
Hey all - thank you for this report.

We reported the issue and found it was related to changes to our playlist URIs, [announced in June of this year](https://developer.spotify.com/community/news/2018/06/12/changes-to-playlist-uris/). The change has been rolled back for now, and we will communicate a new date and path forward for affected applications.

Thank you for your patience!

**Comment by markd2** [comment]
This is happening again about five months after the firs occurence.

**Comment by zackfletch00** [comment]
This is due to (perhaps overzealous) input validation code inside of SPTPlaylistSnapshot. [SPTPlaylistSnapshot createRequestForPlaylistWithURI: accessToken: market: error:] contains the following code, which aborts the playlist request due to a suspected bad URI:

```
    + (NSURLRequest *)createRequestForPlaylistWithURI:(NSURL *)uri
									  accessToken:(NSString *)accessToken
										   market:(NSString *)market
											error:(NSError **)error {
	NSArray *uriComponents = [[uri absoluteString] componentsSeparatedByString:@":"];
	
	if (uriComponents.count < 4 ||
		uriComponents.count > 5) {
		[SPTRequest setErrorCode:401 withDescription:@"Invalid Playlist URI" toError:error];
		return nil;
	}
	
	if (![[uriComponents objectAtIndex:0] isEqualToString:@"spotify"] ||
		![[uriComponents objectAtIndex:1] isEqualToString:@"user"]) {
		[SPTRequest setErrorCode:401 withDescription:@"Invalid Playlist URI" toError:error];
		return nil;
	}
        ...
    }
```
**This code is likely still included in many apps on the market using the streaming SDK**, unless the developers had been closely monitoring [the Web API news announcements](https://developer.spotify.com/community/news/2019/01/15/update-changes-to-playlist-uris/) and had a painless path to release an update to the App Store by this time.  In my case, I am still blocked by Apple from updating my application, and this issue is affecting several hundred users in production today, unless the change can be rolled back, or a hotfix can be made to return old URIs to iOS Streaming SDK users due to the broken code above.

Here is a link to the code affected:  [broken client code in Metadata framework](https://github.com/erdtman/spotify-ios-metadata/blob/fd546230a870b6d23e5f74b2afacacdc4ff1e25a/Spotify%20Metadata/src/SPTPlaylistSnapshot.m#L111)

I will try to get the wheels moving with Apple over the next week or two to try to restore my ability to push out a client update with the broken code removed, but until then, is there any way we could get this hotfixed on the server side (for iOS Streaming SDK clients) or rolled back temporarily to restore functionality to current users?  @arirawr – is there any chance of this happening?  Thanks!

**Comment by dlo** [comment]
Hi all. Our app depends on the streaming sdk and this change has broken our existing app. Is there any way this URI change could be reverted or a hotfix could be published to this SDK? Thank you so much!

**Comment by Spriter** [comment]
Hi all. Our existing app is broken too. A hotfix would be very nice 🙏

**Comment by J3y-S** [comment]
We have the same problem, is there any workaround to fix it?

**Comment by AnandPGautam** [comment]
Hi All, I am also facing this issue, previously I can able to display Track list of Spotify's playlist using SPTPlaylistSnapshot createRequestForPlaylist method. But now I am getting error from this method. 

Please anyone advise me. Thank you!

**Comment by Anders27** [comment]
Why not download and use Spotify iOS Streaming SDK Beta 27?

from the "CHANGELOG.md" file:
Updates to SPTPlaylistSnapshot to support V2 playlist URI's. For for information see https://developer.spotify.com/community/news/2018/06/12/changes-to-playlist-uris/

It fixes this problem.

But sooner or later this SDK will break if Spotify decides to change something else in their infrastructure. So please, tell us that you will continue to maintain this SDK. The newer SDK is NOT a good replacement since it's not possible to access the raw audio samples. This "ios-streaming-sdk" is something no other music streaming company offers. I'm quite sure our apps that uses this SDK generates many new paying Spotify subscribers, so maintaining this SDK will pay off in the long run.
It's already a very mature and stable SDK and the very few bugs it contains should be easy to fix.

**Comment by AnandPGautam** [comment]
Hi @Anders27 , Thank you for your suggestion. 

Currently I am using SpotifyAudioPlayback, SpotifyAuthentication and SpotifyMetadata framework in my App. Now I have downloaded Spotify iOS Streaming SDK Beta 27 (SpotifyiOS framework). But when I am comparing the Header classes then it's not similar. Like we don't have SPTYourMusic.h/SPTPlaylistList.h/SPTPlaylistTracks in the newer SDK. 

How to do merge now? Please suggest..

**Comment by AnandPGautam** [comment]
Please anyone advise me. Thanks in Advance!

**Comment by arirawr** [comment]
Hey again all!

We have fully rolled out the changes to our playlist URIs, announced in June 2018. We released beta-27, which patches the URI issue, and you will need to upgrade to that version to resolve these errors.
