### ISSUE TITLE
Shuffle isn't quite shuffle

### ISSUE THREAD

**Issue by svenooo** [spotify/ios-sdk#121]
Hello,

Since the recent updates of Spotify the shuffle function is absolutely terrible. It used to work perfectly before the updates but now it's just awful. On my Mac, when I turn on shuffle and pick a song to start on, the list of following songs isn't random at all. I have my playlist sorted on the artists name. When for example I pick a song to start with of an artist who's name begins with an "A", shuffle will stay within "A". The following list of songs will only exist of all other artist who's name begins with "A". I'm sure that when you have sorted your playlist on other aspects like the time at which you added a song to the playlist or by the name of the song, it will also keep picking songs you added in the certain period of time at which you added the song you began with or again songs which's tittle begins with the same alphabetic letter.
Especially when sorted alphabetically, this causes some extremely annoying song queues too little and too much variation at the same time. It makes patterns with the same artist returning all the time in the same order often even with two songs of the same artist after one-another. And also it causes queues with artist that do not at all fit in the mood or style of the what you wanted. You'll often start with again for example Anouk -It Wasn't Me which is a pretty lexaing song mainly consisting of acoustic guitar and vocals, and right after that when you're nice and relaxed you'll get your ears blown of by AC/DC blasting away on their distorted guitars right after it.
Here's an example of a queue:

<img width="1440" alt="Schermafbeelding 2019-05-01 om 10 48 54" src="https://user-images.githubusercontent.com/50166848/57011429-de308680-6c01-11e9-898c-ce56e6fe95e8.png">
<img width="1440" alt="Schermafbeelding 2019-05-01 om 10 49 05" src="https://user-images.githubusercontent.com/50166848/57011431-e12b7700-6c01-11e9-9952-9b89baf38de6.png">
<img width="1440" alt="Schermafbeelding 2019-05-01 om 10 49 10" src="https://user-images.githubusercontent.com/50166848/57011434-e688c180-6c01-11e9-8742-afd89a2bce8a.png">
<img width="1440" alt="Schermafbeelding 2019-05-01 om 10 49 14" src="https://user-images.githubusercontent.com/50166848/57011439-eab4df00-6c01-11e9-9d25-2d740e4e9b50.png">
<img width="1440" alt="Schermafbeelding 2019-05-01 om 10 49 25" src="https://user-images.githubusercontent.com/50166848/57011442-edafcf80-6c01-11e9-8fed-c6547dee772b.png">
<img width="1440" alt="Schermafbeelding 2019-05-01 om 10 49 29" src="https://user-images.githubusercontent.com/50166848/57011448-f30d1a00-6c01-11e9-96d6-d3fdf3ad0ca3.png">

Another problem I encountered when streaming to my streaming DAC (Bluesound Node 2) is that when you start on a song, whether you have shuffle turned on or off, it will always return and start with the first song of the playlist instead of playing the songs after the one you started on or a random song. It will only continue playing though the list when you skip a song.

**Comment by kkarayannis** [comment]
Thanks for reporting this. We will look into it.

**Comment by kkarayannis** [comment]
There have been some improvements to Shuffle lately. Please check it out in the newest version of Spotify.
In the future, if you want to report issues with the Spotify app, you can find information about how to contact us at https://support.spotify.com/us/article/how-can-i-contact-spotify
