### ISSUE TITLE
Violation of App Store Terms of Service

### ISSUE THREAD

**Issue by EvanKaminsky** [spotify/ios-sdk#122]
I just spoke with an App Store representative and he confirmed that any app built on top of the Spotify App Remote SDK violates the App Store Terms of Service. Specifically, it breaks "Guideline 4.2.3 - Design - Minimum Functionality" which states that an app cannot require another app to be downloaded. Do the App Remote developers plan on removing the SDK's reliance on the main Spotify app or will this repo simply remain a toy project for non-commercial applications?

**Comment by kkarayannis** [comment]
Hi @EvanKaminsky,
The App Remote SDK's purpose is to provide the ability to control Spotify as an additional feature to standalone apps. It’s not built to enable apps to be built on top of it, whose only purpose is to control Spotify. For example, Google Maps uses App Remote to allow for playback control and picking from a small set of recommended playlists while the user is navigating.
I hope that answers your question.

**Comment by EvanKaminsky** [comment]
That's what I figured - thanks for the info.
