### ISSUE TITLE
Error Domain=com.spotify.sdk.login Code=1 "(null)" only appear in physical device when Spotify is installed

### ISSUE THREAD

**Issue by el-fuche** [spotify/ios-sdk#123]
Hello 

Everything works very well without Spotify installed on a physical device(login & fetching datas work well,but if Spotify is installed I got the error `fail Error Domain=com.spotify.sdk.login Code=1 "(null)` when I try to log me.

Can u help me to find a solution ?

Regards,

Marvin

**Comment by kkarayannis** [comment]
Hi @el-fuche 
Is the Spotify app updated to the latest version from the App Store?

**Comment by el-fuche** [comment]
Hi @kkarayannis 
I tried just now, with the latest version, and I got the same error.

**Comment by el-fuche** [comment]
I found the solution ! And it was dumb...
I didn't put the method `func application(_ app: UIApplication, open url: URL, options: [UIApplicationOpenURLOptionsKey : Any] = [:]) -> Bool`. It works on the simulator because the Spotify App is not installed on it so the method is never called.
