### ISSUE TITLE
Song start with 0.5 second

### ISSUE THREAD

**Issue by MehulOpenxcell** [spotify/ios-sdk#126]
I'm using Spotify iOS SDK to play songs from Spotify track ID and it is working fine for me but when I play another song, it starts with 0.5 seconds always.

When the player loads the first song it works fine but this issue happens after the second song and so on.

I'm using the following method to get track duration.

`func audioStreaming(_ audioStreaming: SPTAudioStreamingController, didChangePosition position: TimeInterval) {} `

Any help is appreciated. 👍

**Comment by kkarayannis** [comment]
This refers to our [older SDK](https://github.com/spotify/ios-streaming-sdk) which is no longer supported.
