### ISSUE TITLE
Login with Spotify - Can't go past accept permissions - iOS SDK

### ISSUE THREAD

**Issue by AlanShortz** [spotify/ios-sdk#127]
Hello friends at Spotify -

I used this package https://github.com/lufinkey/react-native-spotify to enable login with Spotify in my react-native application and while it looks like the Spotify SDK works well for login, after login with email/password I am unable to get past the following screen where we ask user to agree to the permissions after clicking "Agree". See attached image. 

After I click the agree button below, nothing happens

![SpotifyIssue](https://user-images.githubusercontent.com/34199846/57643441-99481080-756e-11e9-8f52-17650f440842.png)

Any help would be much appreciated. Thanks!

**Comment by kkarayannis** [comment]
Hi @AlanShortz! Have you tried asking in that project's repo? Seems like it's an issue with this library rather than the Spotify SDK.
