### ISSUE TITLE
Background support possibilities

### ISSUE THREAD

**Issue by frangulyan** [spotify/ios-sdk#128]
I would like to understand if the new "remote approach" of the SDK somehow supports background execution of my app, seems to me that there is no way to do that. In normal flow my app needs to run in background and play music based on what my backend suggests. As a result, I'm actively connected to my backend to figure out what should be played next (it might change quite often). The standard iOS audio playback background execution mode helps me to keep the app alive. The idea of delegating the playback to Spotify app itself is quite interesting, however, that means that my app will completely lose the possibility to work in background, which is unacceptable to me.
I wonder if there are any ideas on how this can be solved. I have a feeling that the old streaming SDK will be dropped at some point in near future, also heard about widgets but never tried, not sure how can I achieve what I need. Thanks!

**Comment by kseniya-hydric** [comment]
I would like to know a solution to this also.

**Comment by Anders27** [comment]
Please do not drop the old streaming SDK, it's far superior to the new SDK. The old streaming SDK is working very very good and gives Spotify an advantage over all other music streaming service such as "Apple Music" etc. 
The streaming SDK might be more difficult to use, but hey, audio programming is inherently difficult. Making an SDK simpler to use also makes it impossible to do a lot of good stuff.
Why not support both the new and old SDK?
With 100.000.000 of paying users there must be enough money to have someone taking care of that.

**Comment by kkarayannis** [comment]
Hi,
You are right that the this SDK cannot keep your app active in the background since it's not the one that's playing music, the Spotify app is. Given the current APIs available in iOS there doesn't seem to be a way to do what you need. 
The previous streaming SDK is no longer supported, and we don't recommend use it at this time.

**Comment by frangulyan** [comment]
@kkarayannis thanks for the clarification! Hopefully there will be a solution from you guys or even from Apple. The idea of controlling Spotify app is actually quite good, at least it removes some legal problems away from developers. I will close this issue, but I would also appreciate a really short comment from you if the Android SDK is free of this problem before my "deep-dive" into it, even though this is not the correct place to ask. Android should be much more relaxed when it comes to background execution.
