### ISSUE TITLE
Example Get current user saved tracks

### ISSUE THREAD

**Issue by tiagomendesEye** [spotify/ios-sdk#13]
Hey! I notice that you update your SDK that's great.

I am having some difficulty to find how I can make a request using the SDK to see all the user saved tracks, can someone provide an example? 

Endpoint: https://api.spotify.com/v1/me/tracks

Link with more details:
https://developer.spotify.com/console/get-current-user-saved-tracks/?market=&limit=&offset=

**Comment by jackfreeman** [comment]
Closing as a duplicate of https://github.com/spotify/ios-sdk/issues/11
