### ISSUE TITLE
Incorporating Spotify into a new mobile app

### ISSUE THREAD

**Issue by cma4** [spotify/ios-sdk#130]

**Comment by cma4** [comment]
Hello,
I am a new developer interested in incorporating Spotify into my new app. Any ideas how I should get started or who I could contact?

**Comment by WickedChicken42** [comment]
I'd start with developer.spotify.com, pull down the SDK from the code tab and dive deep into the sample project.

**Comment by GearoidMullins** [comment]
I have an idea for using Spotify within my app, but the sort of library access I require to do it does not seem to be yet available on the SDK. How can I discuss this further with the Spotify developers to see if this can be implemented, please?

**Comment by leeibbo78** [comment]
O

**Comment by kkarayannis** [comment]
@GearoidMullins You can open a new issue and we'll answer your question.

**Comment by GearoidMullins** [comment]
@kkarayannis Thanks
I have opened a new issue regarding this and can be viewed here: https://github.com/spotify/ios-sdk/issues/142 
Thank you for your help
