### ISSUE TITLE
Feature Request: Core Audio support

### ISSUE THREAD

**Issue by JacksonWrath** [spotify/ios-sdk#133]
I know others have talked about this, but my request is a bit different. Please hear me out.

First and foremost, thanks for all the work put into this SDK!

I agree that maintaining a full secondary "player" in the SDK is a lot of additional overhead for a feature that's not used very much, especially for something that I effectively get to implement for free. So I'm not asking for that.

Make me do the heavy lifting of working with Core Audio. Give me an object that handles the proprietary bits (whatever that's deemed to be) with an exposed AudioUnit for getting the data, and I'll do the rest. If the proprietary parts are minimal, I'd even be willing to manage having to request the data from Spotify as needed, the cacheing mechanisms, encryption...whatever is required of me and you're wiling to give me access to. I just need the means.

The core of my app, its entire reason for existence, isn't possible without being able to work with the low level audio data. I don't want feature parity; I want to reach a compromise that works for both of us, before the old streaming SDK eventually stops working.

Thanks for hearing me out. I would really appreciate a response one way or the other; help me achieve my dreams, or crush them here and now so I can move on. 🙂

**Comment by kkarayannis** [comment]
Hi @JacksonWrath! Thank you for your enthusiasm for Spotify and your suggestions. Unfortunately this is not a direction we are looking to take with the SDK at the moment. Hopefully you can find another use for the SDK. In any case, best of luck in your future endeavors.
