### ISSUE TITLE
Wrong URI

### ISSUE THREAD

**Issue by alextrikoz** [spotify/ios-sdk#134]
Hi
I use the iOS sdk. I have two buttons to play songs
One for a Katy Perry's track
`appRemote.playerAPI?.play("spotify:track:4lCv7b86sLynZbXhfScfm2") { (restult, error) in }`
Second for a Robbie Williams's track Angles
`appRemote.playerAPI?.play("spotify:track:1M2nd8jNUkkwrc1dgBPTJz") { (restult, error) in }`
I switch between them and it works correctly. But if, for example, Robbie Williams's song ends than new song plays, Snoop Dog's song for example. I switch to Katy, listen her song to the end, and new song starts, a Metallica track for example. Now when I am trying to switch between Katy and Robbie I switch between Metallica and Snoop Dog.
What have I done wrong?

**Comment by josianebezerra** [comment]
Hi, @alextrikoz. Are you testing with a free Spotify user? Free users have some restrictions on playing specific content. Have you checked if App Remote returns any error?

**Comment by alextrikoz** [comment]
Hi, @josianebezerra. Yes I am using a free Spotify account. There are no error from App Remote. Is it possible to play the requested track with a free account not a queue started from the requested.

**Comment by kkarayannis** [comment]
Free accounts are not allowed to stream tracks on demand in most cases. This limitation applies when using the SDK as well.
There might be cases where you're allowed to stream a specific track, which is why it worked the first time you tried it, but you shouldn't depend on it. There will not be an error about it either. It is the expected behavior.

**Comment by NathanWalker** [comment]
@kkarayannis do you happen to know percentage wise how often a free account would stream the desired track? Seems sometime works, sometimes not but curious if known percentage of when this occurs, little odd it seems purely random or is that by design?
