### ISSUE TITLE
Authentication no longer working on apps built for iOS 13

### ISSUE THREAD

**Issue by squaredx** [spotify/ios-sdk#138]
URL Callbacks are now handled in the SceneDelegate.swift file for apps built using Xcode 11 and iOS13 using the function "func scene(_ scene: UIScene, openURLContexts URLContexts: Set<UIOpenURLContext>)". The Spotify callback function requires the following function signature "application:(UIApplication *)application openURL:(NSURL *)URL options:(NSDictionary<UIApplicationOpenURLOptionsKey,id> *"

Note the difference between:
-UIScene vs. UIApplication
-Set of UIScene.UIOpenURLContext vs NSURL and UIApplication.OpenURLOptionsKey

The current Spotify iOS-SDK is able to launch the Spotify app for authentication, but the return callback to my application is unable to handle the retuned information. My application is using SwiftUI so there is no way (that I know of atleast) to not use UIScene.

**Comment by kkarayannis** [comment]
You can get the URL from `URLContexts.first!.url` when `func scene(_ scene: UIScene, openURLContexts URLContexts: Set<UIOpenURLContext>)` is called in your UISceneDelegate. From thereafter there is no difference from before.

**Comment by Kingamattack** [comment]
Hi guys, I just started working with this SDK on Xcode11/iOS13 and even with the samples I'm not able to make the SDK works.
I implemented my AppDelegate following that sample https://github.com/spotify/ios-sdk/blob/master/DemoProjects/NowPlayingView/NowPlayingView/AppDelegate.swift but my code never pass in the ``func application(_ app: UIApplication, open url: URL, options: [UIApplication.OpenURLOptionsKey: Any] = [:]) -> Bool`` 

I'm using the Firebase SDK so I also need the ``func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool``

Is there a problem with the SDK or is it me? Can't I have ``open url`` and ``didFinishLaunchingWithOptions`` at same time?

Thanks.

**Comment by kkarayannis** [comment]
Hi @Kingamattack,

If you have a SceneDelegate in your app, you can have this method in there:
```
func scene(_ scene: UIScene, openURLContexts URLContexts: Set<UIOpenURLContext>) {
        guard let url = URLContexts.first?.url else {
            return
        }

        let parameters = appRemote.authorizationParameters(from: url);

        if let access_token = parameters?[SPTAppRemoteAccessTokenKey] {
            appRemote.connectionParameters.accessToken = access_token
            self.accessToken = access_token
        } else if let error_description = parameters?[SPTAppRemoteErrorDescriptionKey] {
            // Show the error
        }

    }
```

You can then remove the one from your AppDelegate. We'll update the documentation soon.
