### ISSUE TITLE
Spotify iOS Streaming SDK - what will happen?

### ISSUE THREAD

**Issue by Anders27** [spotify/ios-sdk#14]
This new SDK is a real showstopper for certain types of apps.

Since playback is now handled by the regular Spotify app, working with the audio signal at a low level is not possible.

Me and many other developers will have to continue to use the older "Spotify iOS Streaming SDK".
It has worked very very well despite a couple of annoying bugs that never has been fixed.
It broke completely when the new changes to the playlist URIs was added on September 11.
The change has been rolled back for now and everything is back working as normal. But what will happen in the future?

The affected methods in the old SDK is the following:
+(void)playlistWithURI:(NSURL *)uri accessToken:(NSString *)accessToken callback:(SPTRequestCallback)block;
+(void)playlistsWithURIs:(NSArray *)uris accessToken:(NSString *)accessToken callback:(SPTRequestCallback)block;

Will you update the older SDK so it continues to work? The changes to the playlist uri is minimal as explained here:
https://developer.spotify.com/community/news/2018/06/12/changes-to-playlist-uris/
so it seems as a simple fix to the SDK.

The old "Spotify iOS Streaming SDK" is a beautifully designed SDK making it possible to access to raw audio samples.
This is big big advantage for Spotify when comparing to say "Apple Music". 
I have many customers that has changed from "Apple Music" to Spotify only because of the feature my app offers,
and this is only possible because of the older "Spotify iOS Streaming SDK" and its support for low level audio.

So please come up with a solution so that our apps does not break again as they the did on September 11.

**Comment by arirawr** [comment]
Hi @Anders27 - thanks for raising your concerns.

I'll communicate here and on the developer blog when we have more detail about our plans.

The iOS Streaming SDK is in beta and we do not guarantee functionality, however, we understand that broken SDKs means a poor experience for users and will try to find a way forward for applications that are affected.

**Comment by Anders27** [comment]
I found out how to fix it myself:

Since the "SpotifyMetadata.framework" is open source, it's easy to make it support both the older playlist uri:
spotify:user:spotify:playlist:37i9dQZF1DZ06evO3OC4Te
and the newer
spotify:playlist:37i9dQZF1DZ06evO3OC4Te

This must mean that if I update my app now with support for both uri's,
whenever you change to the new uri type, this will not affect my users, right?

Can you confirm this?

**Comment by arirawr** [comment]
Hey again - yes, it may be possible to patch. If you end up making a patch, please let me know and make a pull request to the source repo :)

**Comment by jackfreeman** [comment]
The old streaming sdk has now been updated to support v2 uri's.
