### ISSUE TITLE
One of the streams has reached the end

### ISSUE THREAD

**Issue by dataexcess** [spotify/ios-sdk#140]
I implemented the authentication and remote connection of the new SDK.
Every 5 minutes after successfully authenticating and connecting to the Remote, I have to reauthenticate because of the following error:

Code=-1002:"connection terminated" / "End of stream" / "One of the streams has reached the end" / "try to reconnect" / reason:"the spotify app might have been suspended". 

Why is this happening and how can I prevent it. 
Thnx

**Comment by kkarayannis** [comment]
When playback stops, the audio session has ended so iOS will suspend the Spotify app. The Spotify app then has to shut down the app remote connection.

The way to avoid this is to always have something playing, so prefer playlists and albums vs single tracks. On a related note, the "Autoplay" option in the Playback settings in Spotify is on by default so most users should not experience the above even with single tracks.

Unfortunately though, this can't be avoided when the music is manually paused. Trying to resume when the audio has been paused for a while will require re-authentication.

**Comment by dataexcess** [comment]
@kkarayannis is this a new requirement of the new SDK? This wasn't the case in the old one right?

**Comment by kkarayannis** [comment]
The new SDK doesn't stream directly to itself and the app it is in. It just tells the Spotify app to start playback, so all the standard iOS limitations for inter-app communication and background execution apply.

**Comment by dataexcess** [comment]
Ok. That's a pitty. 
Thnx for the info!

**Comment by dataexcess** [comment]
@kkarayannis one last question: would it be able to reauthenticate the user 'behind the scenes' everytime this happens using a token-refresh action?

It would be nice to have more documentation on token-refresh and how it is/should be implemented.

Thnx
