### ISSUE TITLE
In order to implement Spotify into my app, I would need certain Spotify library access that is currently not available to developers. Is there a way of applying for such access so that I can integrate Spotify with my app?  

### ISSUE THREAD

**Issue by GearoidMullins** [spotify/ios-sdk#142]
Hi,
As the title suggests, I am looking to get certain access to Spotify music libraries approved in order to integrate with my own app, however, the access I require is not currently available with the Spotify SDK (for either iOS or Android).

I have a fitness app on the market called 'Music Momentum', which uses a persons GPS location to calculate their speed at a given stage. If they are not walking, jogging or running above a personal target speed (set by the user), the app will slow down the playing speed of their music. In order to get their music back at its normal playing speed again, they will need to accelerate their pace, whereupon their music will resume playing as normal once they have reached their target speed. 

Some more information about this app can be found here: 
https://apps.apple.com/ie/app/music-momentum/id1445113107
and here:
https://play.google.com/store/apps/details?id=app.musicmomentum.com

A lot of customers have given me very positive feedback about the app, but have also expressed that they would love if the app could sync with their personal Spotify account. I agree that having such access would be very beneficial and as a result, make the app more appealing to other potential customers. 

However, in order for the app to slow down the playing speed of any Spotify music, Music Momentum would need access to the music files that the person is currently using. It needs a physical .wav, .mp3 or .aiff audio file to be able to process the song and slow it down. 

After consulting with other developers, we have realised that this sort of access is not currently available to developers through the current SDK and therefore not a viable option. However, if there was a method of getting such access and permissions with Spotify directly in order to integrate the app with Music Momentum, this could be a viable option.

Can you please advise who I can direct this query to or if it's possible for me to set up a meeting with the Spotify developers? I would really like to investigate this further with the view to executing it into the Music Momentum fitness app. Thank you 

Kind regards,
Gearóid

**Comment by kkarayannis** [comment]
Hi @GearoidMullins! While this is a great idea and the kind of innovation that we hope to see from people using our SDKs, we cannot provide access to the audio files due to licensing restrictions.
Best of luck with your app!

**Comment by GearoidMullins** [comment]
Hi @kkarayannis 
Thanks for your feedback. Can you please elaborate and provide more information on the licensing restrictions that you mention? 

Also, do you know if there are any Spotify music licensing packages available for developers to purchase in order to access such music files within their app?
For example, to pay per year to access a certain amount of artists or something like that?

**Comment by kkarayannis** [comment]
Those restrictions refer to the licensing terms that Spotify has with the music copyright holders.
Spotify can't provide access to the music files.
