### ISSUE TITLE
SKStoreProductViewController may not be subclassed - Exception on iOS 13

### ISSUE THREAD

**Issue by jeffrey-beauchamp** [spotify/ios-sdk#143]
SPTStoreViewController subclasses SKStoreProductViewController:
https://github.com/spotify/ios-streaming-sdk/blob/master/SpotifyAuthentication.framework/Headers/SPTStoreViewController.h

As of iOS 13 beta 6 this throws an exception: SKStoreProductViewController may not be subclassed.

**Comment by kkarayannis** [comment]
This refers to the Streaming SDK instead of this one.
Please note that the [Streaming SDK](https://github.com/spotify/ios-streaming-sdk) is deprecated and no longer supported.

I've just tested the current SDK and it doesn't have this problem.
