### ISSUE TITLE
Error when using logout of SPTAudioStreamingController

### ISSUE THREAD

**Issue by schansge** [spotify/ios-sdk#143]
Hi Guys,

i've got a problem with the logout functionality of the SPTAudioStreamingController class. When i log out a streaming controller, which was previously logged in successfully, I have the problem, that I am no longer able to log that instance of the class in again. I get the following error message:

Error Domain=com.spotify.ios-sdk.playback Code=6 "A playback function was invoked before playback was initalized properly." UserInfo=0x7fd604201c60 {NSLocalizedDescription=A playback function was invoked before playback was initalized properly.}

So I am not quite sure, if i have to create a new instance of that class or if it is a bug.

Greetings, Patrik

**Comment by possan** [comment]
Closing this since it's so old, it seems like this is no longer the problem with the recent versions.
