### ISSUE TITLE
UIWebView Deprecation In Old SDK

### ISSUE THREAD

**Issue by markearbuds** [spotify/ios-sdk#145]
Hello There,
Posting here because issues are closed on old Spotify SDK at the moment.

We are still heavily using the old Spotify SDK (https://github.com/spotify/ios-streaming-sdk)

Apple is now issuing warnings that it will reject all applications that use UIWebView

The older SDK contains UIWebView calls (even though we aren't using them) and Apple is giving us this warning.

Would it be possible for the old SDK to be updated to have UIWebView removed?  We cannot rewrite our entire application just yet to support thew new Spotify SDK.

Any guidance would be appreciated.

Thanks!
Mark

**Comment by kkarayannis** [comment]
Unfortunately the streaming SDK is unsupported and there will be no more updates to it.
