### ISSUE TITLE
initiateSession(with:, options:) now starts playing songs with in-app authentication?

### ISSUE THREAD

**Issue by vikasnair** [spotify/ios-sdk#146]
The ```initateSession``` method previously would only open the app (or web view) to prompt authentication. Now, it also starts playing songs (the last-played song?). 

I did not make any changes to any of the code touching this API. Just seemed to start happening. Did something change with the handler for the session auth flow within the Spotify app / API?

This so far has been observed on iOS 12.4 and 13.0.

**Comment by kkarayannis** [comment]
Hi @vikasnair, this is a regression in the Spotify app will be fixed in an upcoming update.

**Comment by sanchezlol** [comment]
Hi, @kkarayannis! Spotify app update came today, but bug has not fixed yet. It will be in the next update? Thanks!

**Comment by kkarayannis** [comment]
Hi @sanchezlol! Yes, I expect it to be in v8.5.24.

**Comment by kkarayannis** [comment]
The update with the fix is now live. Please update the Spotify app to the newest version (8.5.25) and try again.
