### ISSUE TITLE
Inconsistently receiving callback to appRemoteDidEstablishConnection

### ISSUE THREAD

**Issue by WickedChicken42** [spotify/ios-sdk#149]
After updating to the Spotify app v8.5.22 I am receiving inconsistent behavior in receiving the callback to appRemoteDidEstablishConnection.  The behavior has been changing over the last hour as I normally today have not gotten the callback but sometimes I do.  Sometimes I can not connect to Spotify at all.  I have not changed my code.  The Spotify app seems to work on its own.  FYI: I am also not getting any calls to didDisconnectWithError or didFailConnectionAttemptWithError
iOS: 12.4.1  SDK: 1.0.2

Update: I stand corrected, I did just receive a callback to didFailConnectionAttemptWithError with the error being : Connection refused. I'm not sure why, my internet connection is good and the Spotify app itself seems to be OK. This callback is not always called when I run the app so still inconsistent behavior, guessing Spotify is having server troubles of some kind.

Also, connecting over home WiFi or Cellular makes no difference in the behavior I'm seeing.

**Comment by WickedChicken42** [comment]
I stand corrected, I did just receive a callback to didFailConnectionAttemptWithError with the error being : Connection refused

**Comment by haikusw** [comment]
Wonder if this is related to https://github.com/spotify/ios-sdk/issues/114 ?

**Comment by WickedChicken42** [comment]
Hmm, sure seems extremely similar.  Thanks for the heads up.  Initially I didn't think it was a failure to connect but as you can see in my notes I have come to realize it may be the same thing.  Too bad there is no resolution yet :(

**Comment by WickedChicken42** [comment]
Sadly, shutting down the Spotify app nor removing and reinstalling it has had any impact.

**Comment by WickedChicken42** [comment]
Shutting down the Spotify App, starting it back up AND playing a track will allow my app to connect again.  Marking this thread as a dupe to #114 and continuing the discussion over there.
