### ISSUE TITLE
After downloading demo works only one time

### ISSUE THREAD

**Issue by Gurmeetkaur5949** [spotify/ios-sdk#153]
I have downloaded this demo and was working fine from last days. Now It stopped working pause and next song functionality . I have dowloaded the demo again ,  it is  also not working for me.Any solution regarding this issue?

**Comment by kkarayannis** [comment]
Please update the Spotify app to the latest version (8.5.25) and try again. There was an issue that prevented the SDK from connecting to Spotify before this update.
