### ISSUE TITLE
Download Spotify Song Through Spotify api Swift

### ISSUE THREAD

**Issue by shamdass** [spotify/ios-sdk#154]
I am developing an iPhone application with integrating Spotify SDK. Is there any way I can download the Spotify song through any Spotify Api or any other way because I developing a music application which change the song bpm (Beats Per Minutes). But I can’t change Spotify song bpm because Spotify song play online through Spotify methods with the Spotify premium account. So any way to download Spotify song.

**Comment by kkarayannis** [comment]
Hi,
We don't provide access to the audio files.

**Comment by shamdass** [comment]
Hello @kkarayannis thank you for your reply, but I am confused because some application are changing the bpm of Spotify song.

**Comment by kkarayannis** [comment]
I understand your confusion. Those apps are using an older SDK that is no longer supported or maintained.

**Comment by shamdass** [comment]
okay which SDK Version provide this type of functionality?

**Comment by shamdass** [comment]
Thank you so much @kkarayannis
