### ISSUE TITLE
Swift

### ISSUE THREAD

**Issue by thegreatmichael** [spotify/ios-sdk#156]
idk the easiest way to offer swift code as an alternative to https://developer.spotify.com/technologies/spotify-ios-sdk/tutorial/#creating-the-application-code. find it here (at least this JUST worked for me):

we need a bridging header to allow us to import the spotify.h file (see details here: https://developer.apple.com/library/ios/documentation/swift/conceptual/buildingcocoaapps/MixandMatch.html#//apple_ref/doc/uid/TP40014216-CH10-XID_80 ***especially about "Objective-C Bridging Header"***):

    #ifndef MyApp_Bridging_Header_h
    #define MyApp_Bridging_Header_h

    #import <Spotify/Spotify.h>

    #endif

then, rather than deleting the contents of AppDelegate.swift, add the following to the class definition (outside of other functions)

    let kClientId = "YOURCLIENTID"
    let kCallbackURL = "your-protocol://your-callback-url"
    let kTokenSwapURL = "http://localhost:1234/swap"
    
    var session:SPTSession?
    
    var player:SPTAudioStreamingController?
    
    func delay(delay:Double, closure:()->()) {
        dispatch_after(
            dispatch_time(
                DISPATCH_TIME_NOW,
                Int64(delay * Double(NSEC_PER_SEC))
            ),
            dispatch_get_main_queue(), closure)
    }

this should be the contents of `func application(application: UIApplication, didFinishLaunchingWithOptions launchOptions: [NSObject: AnyObject]?) -> Bool {`

    var auth = SPTAuth.defaultInstance()
    var loginURL = auth.loginURLForClientId(kClientId, declaredRedirectURL: NSURL(string: kCallbackURL), scopes: [SPTAuthStreamingScope])
    
    // Opening a URL in Safari close to application launch may trigger
    // an iOS bug, so we wait a bit before doing so.
    delay(0.1) {
        application.openURL(loginURL)
        return
    }
    
    return true

finally, add the following two functions:

    func application(application: UIApplication, openURL url: NSURL, sourceApplication: String?, annotation: AnyObject?) -> Bool {
        // Ask SPTAuth if the URL given is a Spotify authentication callback
        if (SPTAuth.defaultInstance().canHandleURL(url, withDeclaredRedirectURL: NSURL(string:kCallbackURL))) {
            SPTAuth.defaultInstance().handleAuthCallbackWithTriggeredAuthURL(url, tokenSwapServiceEndpointAtURL: NSURL(string: kTokenSwapURL), callback: { (error, session) -> Void in
                if (error != nil) {
                    println("*** Auth error: \(error)")
                    return
                }
                
                self.playUsingSession(session)
            })
            
            return true
        }
        
        return false
    }
    
    func playUsingSession(session:SPTSession) {
        // Create a new player if needed
        if (self.player == nil) {
            self.player = SPTAudioStreamingController()
        }
        self.player?.loginWithSession(session, callback: { (error) -> Void in
            if (error != nil) {
                println("*** Enabling playback got error: \(error)")
                return
            } else {
            
                SPTRequest.requestItemAtURI(NSURL(string: "spotify:album:3vGtqTr5he9uQfusQWJ0oC"), withSession: session, callback: { (error, album) -> Void in
                    if (error != nil) {
                        println("*** Album lookup got error \(error)")
                        return
                    }
                    self.player?.playTrackProvider(album as SPTAlbum, callback: nil)

                })
            }
        })

    }

**Comment by pwcremin** [comment]
Dude! Thanks so much for an example.  I almost had it but you brought me the rest of the way.  Thanks man

**Comment by jamiegalbreath** [comment]
I don't seem to be able to get this working. It would be great to see this as a working project...

**Comment by j-wilkin** [comment]
I started making a swift project a while ago. It's very much a WIP but you might find it useful as an example https://github.com/j-wilkin/SpotifyDJ

**Comment by Dinkins** [comment]
This version does work with the latest release of the sdk, but in `playUsingSession`: 
```
self.player = SPTAudioStreamingController() 
```
is now 
```
self.player = SPTAudioStreamingController(clientId: kClientId)
```

**Comment by jamiegalbreath** [comment]
Amazing this fixed things, Thanks dude

**Comment by thomtheman** [comment]
Has anyone figured out how to get the album artwork image URL, cannot get it to work...
           
            var songArtMeta:NSURL = self.player?.currentTrackMetadata["SPTAudioStreamingMetadataAlbumURI"] as NSURL
            var songArtUrl: NSURL = songArtMeta.largestCover.imageURL

**Comment by iKenndac** [comment]
Your `songArtMeta` variable is an `NSURL`, which doesn't have a `largestCover` property. You need to use `SPTRequest` to turn that url into a proper `SPTAlbum` object. Please see the SDK documentation and example code for instructions on how to do this - this isn't a Swift-specific problem.

**Comment by uknowmeright** [comment]
SPTAlbum does not have a member named largestCover anymore.  Is this depricated now again? Jeez

**Comment by uknowmeright** [comment]
IKenndacs suggestion will no longer work as STPAlbum currently does not have an images property. Please let us know if there is an alternate method we can use to get album artwork. thanks!

**Comment by johndbritton** [comment]
I had some trouble getting this to work, but I found another solution via Google cache: http://webcache.googleusercontent.com/search?q=cache:u7EGvefidr8J:pachulski.me/2015/spotifyframework-with-swift/+&cd=2&hl=en&ct=clnk&gl=us

**Comment by ahallora** [comment]
provided by @Sethmr, see this regarding Spotify iOS-SDK Swift 3: https://github.com/Sethmr/SpotifyInSwift 😄
