### ISSUE TITLE
Suggestions: Play a track from a specific starting position

### ISSUE THREAD

**Issue by anscash** [spotify/ios-sdk#157]
Hi guys

My team and I would love to start a playback from a specific starting position; like in the WEB API
Our Android Colleagues also mentioned this feature here:
https://github.com/spotify/android-sdk/issues/121

Greetings

**Comment by kkarayannis** [comment]
Hi @anscash 
Thanks for the suggestion. This is something we might add in the future. In the meantime you can always start playing a track and seek forward to the position you want.

**Comment by auro-krishna** [comment]
@kkarayannis Can you please tell how to do seek in IOS swift?
