### ISSUE TITLE
Update Readme for iOS 13 and Xcode 11

### ISSUE THREAD

**Issue by Vuong-Dao** [spotify/ios-sdk#159]
Hi All
Since iOS 13 and XCode 11. We couldn't receive the call back on `application(_ app: UIApplication, open url: URL, options: [UIApplication.OpenURLOptionsKey : Any] = [:]) -> Bool` anymore. 
It moved to a new method and a new class called `SceneDelegate` and `scene(_ scene: UIScene, openURLContexts URLContexts: Set<UIOpenURLContext>)` 

I've tried with it and received the token in there.
I'm suggesting that we should change the Readme so that all developers can see it and no more pain on debugging something wrong with SDK 👯‍♂ ( I lose 1 day to find out it)

Ref: https://forums.developer.apple.com/thread/121990 and https://medium.com/@ZkHaider/apples-new-uiscene-api-a-programmatic-approach-52d05e382cf2 and https://stackoverflow.com/questions/56508764/app-delegate-methods-arent-being-called-in-ios-13

**Comment by cstuart08** [comment]
Hi Vuong-Dao. I am having some trouble here and was wondering if you might be able to assist. Do you recommend I move:
`func application(_ app: UIApplication, open url: URL, options: [UIApplication.OpenURLOptionsKey : Any] = [:]) -> Bool {
        self.sessionManager.application(app, open: url, options: options)
        
        return true
    }`

to the scene delegate?

**Comment by kkarayannis** [comment]
Here's what you need to add to your SceneDelegate:
```
func scene(_ scene: UIScene, openURLContexts URLContexts: Set<UIOpenURLContext>) {
        guard let url = URLContexts.first?.url else {
            return
        }

        let parameters = appRemote.authorizationParameters(from: url);

        if let access_token = parameters?[SPTAppRemoteAccessTokenKey] {
            appRemote.connectionParameters.accessToken = access_token
            self.accessToken = access_token
        } else if let error_description = parameters?[SPTAppRemoteErrorDescriptionKey] {
            // Show the error
        }

    }
```

We'll update the documentation and the sample project to reflect this soon.

**Comment by kkarayannis** [comment]
Now updated.
