### ISSUE TITLE
Bundle ID issue

### ISSUE THREAD

**Issue by DiegoResnik** [spotify/ios-sdk#16]
**Description**
I registered to try the iOS App Remote, add it to my app - iCarMode.
I followed: https://developer.spotify.com/documentation/ios-app-remote/quick-start/
My app opened spotify but on callback I got this error:
error=invalid_app_identifier&error_description=The app identifier is not valid with the client ID provided
In "My dashboard" I registered my app bundle id as "iCarMode.com" although my app bundle id is "iCarMode"...but trying to fill "iCarMode" as my bundle id gets a validation error: "Not a valid Bundle ID".
Changing a bundle id on the appstore is not possible after the app exists there...
It's actually IS a valid bundleid...is there a way to fix this or bypass this?

**Versions**
iOS SDK version - Remote beta
Spotify app version (if native SSO flow is involved) - 8.4.69.787

**Severity**
Major

**Steps to Reproduce**
go to developer dashboard: https://developer.spotify.com/dashboard
try to fill a single word under the "Bundle Id", it will flash an error: "Not a valid Bundle ID"

**Actual behaviour**
error: "Not a valid Bundle ID"

**Expected behaviour**
"iCarMode" is the actual BundleID of my app on the AppStore...it should be valid to register it.

**Logs**
I've attached a picture of the error on the dashboard, and the bundleid on the AppStore.
![45317289-441cb080-b542-11e8-9c74-810b9427ceb7](https://user-images.githubusercontent.com/19625881/45429554-397e2a80-b6ac-11e8-8d40-ee802ed46a24.png)

**Comment by tiagomendesEye** [comment]
@DiegoResnik  that not valid Bundle ID
 
For example in this print screen, the bundle ID is "com.spotify.sdk.SPTLoginSampleApp"

![screen shot 2018-09-12 at 15 54 30](https://user-images.githubusercontent.com/34243918/45433556-57479180-b6a4-11e8-98fc-ef87b0d31cc6.png)

**Comment by DiegoResnik** [comment]
@tiagomendesEye, what do you mean it is not a valid bundleid? It is my bundleid in the AppStore...I even attached a screenshot from the AppStore...and it can not be changed...

**Comment by DiegoResnik** [comment]
> honestly thought it was not possible to make bundle ID with just one word...my mistake

@tiagomendesEye ,Thanks for trying, really appreciated....do you have any idea how to fix or bypass this issue?

**Comment by arirawr** [comment]
Hey @DiegoResnik - this is something that will need to be changed on our end. Our Dashboard expects bundle IDs to follow the Apple guidelines and doesn't take these kind of bundle IDs into account. We'll look into getting it updated and I'll post here when it's fixed.

**Comment by DiegoResnik** [comment]
@arirawr  thank you for the update, looking forward for this fix ! I'm really anxious to add Spotify integration to my app. any estimation ?

**Comment by arirawr** [comment]
Hey @DiegoResnik this should be fixed. Let me know if you're able to add the bundle ID in now!

**Comment by champrocks3190** [comment]
After 3 hours i found that , Its case sensitive for Android packages .  need to put SHA1 IN CAPITAL AS IT IS .
