### ISSUE TITLE
Change BPM value of Spotify Song Swift

### ISSUE THREAD

**Issue by shamdass** [spotify/ios-sdk#160]
I am trying to build an application that plays Spotify songs. I am really confused about how to change BPM(Beats Per Minute,) value of Spotify songs.

**First Step:** Login through Spotify.

**Second Step:** Get Current user all album.

**Third Step:** get album track.

**Last Step:** play track.

I have done All step with Spotify Delegates. but I want to change the BPM value of the track.

Can someone please explain to me how to change the BPM value?

**Comment by shamdass** [comment]
Update Question Title

**Comment by kkarayannis** [comment]
Hi @shamdass
That functionality is not available.

**Comment by shamdass** [comment]
Hello @kkarayannis  Thank you for you reply. but some application are changing the bpm of Spotify song. 
**Example : **  The Amazing Slow Downer Application provide this feature on paid version.

**Comment by shamdass** [comment]
Okay but Some application's change the bpm of Spotify song. so is there any special feature provided by Spotify or any third party doing this?

**Comment by kkarayannis** [comment]
That was a feature of an older SDK that is no longer supported. Those applications that do it might stop working in the future as well.

**Comment by shamdass** [comment]
Okay, @kkarayannis, Thank you for your response,
Is it possible if i pay extra amount to Spotify to provide this feature to download or any alternative way to change BPM of song (Playback Speed of song)?.  Because my client want's this feature. Could you please suggest a way or solution ASAP.

**Comment by kkarayannis** [comment]
I'm sorry, due to our license deals with the labels, we just can't offer access to the audio files.

**Comment by shamdass** [comment]
okay thank you so much .
