### ISSUE TITLE
Custom AV AudioPlayer to play Spotify songs

### ISSUE THREAD

**Issue by azeemohd786** [spotify/ios-sdk#164]
I want to use my own customised  audio player in my iOS project instead of SPTAudioPlayer. I could get preview url played in my audio player for 30 seconds. But I need to use full song in my player?. Any suggestions?..

**Comment by kkarayannis** [comment]
Hi @azeemohd786,
There is no ability to play audio with your own player or your own app. All audio plays from the Spotify app.

**Comment by azeemohd786** [comment]
@kkarayannis , Thank you for response.

Wondering before 6 months when I was trying to play Spotify song using Spotify URI, it was working., 
```
SPTAudioStreamingController.sharedInstance().playSpotifyURI("spotify:track:4aDLPXlzHZm26GppvRwms8", startingWith: 0, startingWithPosition: 10) { error in
                    if error != nil {
                        print("*** failed to play: \(error)")
                        return
                    }
                }
```


nowadays, when I try its not. So from native iOS app we cannot play songs using Spotify player

**Comment by kkarayannis** [comment]
The streaming SDK is an old SDK that is no longer supported.
