### ISSUE TITLE
SPTPlaylistSnapshot does not contain images for certain playlists.

### ISSUE THREAD

**Issue by LandonRover** [spotify/ios-sdk#164]
After retrieving an `SPTPlaylistSnapshot` from a partial playlist, all playlists that are not Spotify created (uri begins with `spotify:user:spotify`) do not contain images. I am assuming this was intentional, but it's a bit of a letdown. Likely, because the images are dynamically created from the playlist, the API expects that the developer will parse the playlist for cover art and pull those URLs to load a mixed image. It would be a nice enhancement if the API would perform that magic and return the images in the `SPTPlaylistSnapshot.images` array that already exists...

What are others doing to mitigate this issue?

**Comment by possan** [comment]
Closing this since it's so old, it seems like this is no longer the problem with the recent versions.
