### ISSUE TITLE
How to differentiate between free and premium accounts (SDK)

### ISSUE THREAD

**Issue by cggapps** [spotify/ios-sdk#165]
Hello.

I'm using the SDK (iOS and Android) and the AppRemote class to link my App with Spotify App (without using the Web API) to listen Spotify music within my App.

I have to know **how can I differentiate between the Free and Premium user account** when my App is linking with Spotify App (In the moment of vinculation).
Is there any way (iOS and Android)?

Thanks in advance.

**Comment by mdelolmo** [comment]
Hi,

In Android, you can use the [UserApi class](https://spotify.github.io/android-sdk/app-remote-lib/docs/com/spotify/android/appremote/api/UserApi.html). If you call [getCapabilities](https://spotify.github.io/android-sdk/app-remote-lib/docs/com/spotify/android/appremote/api/UserApi.html#getCapabilities--), you will get an object that determines whether the user "can play on demand".
Currently, that value is mapped to the product state (premium/free), so it will work for your purposes.

I will investigate a little bit to see how you can do the same on iOS.

**Comment by mdelolmo** [comment]
I learned that you can use the same API in iOS and it should work like in Android.

**Comment by zallanx** [comment]
For those wondering, the method is `canPlayOnDemand` from `SPTAppRemoteUserCapabilities`. Documentation is [here](https://spotify.github.io/ios-sdk/html/Protocols/SPTAppRemoteUserCapabilities.html#//api/name/canPlayOnDemand).
