### ISSUE TITLE
How to know the playbackPosition (SDK)

### ISSUE THREAD

**Issue by cggapps** [spotify/ios-sdk#166]
Hello.

I'm using the SDK (iOS and Android) and the App Remote class to link my App with Spotify App (without using the Web API) to listen Spotify music within my App.

Is there a way to know the "**playbackPosition**" every time my App wants (**iOS and Android**)?

In iOS App, the playerStateDidChange (SPTAppRemotePlayerStateDelegate) method is called sometimes, and in this method I can get the playbackPosition, but I don't know how to obtain it using a Timer to get the playbackPosition when my App wants.

Thanks in advance.

**Comment by mdelolmo** [comment]
Hi,

In both platforms there are methods to retrieve the player state without subscribing to it.
## Android
https://spotify.github.io/android-sdk/app-remote-lib/docs/com/spotify/android/appremote/api/PlayerApi.html#getPlayerState--
Then the `[playbackPosition](https://spotify.github.io/android-sdk/app-remote-lib/docs/com/spotify/protocol/types/PlayerState.html#playbackPosition)` field.
## iOS
https://spotify.github.io/ios-sdk/html/Protocols/SPTAppRemotePlayerAPI.html#//api/name/getPlayerState:
Within PlayerState, inspect the `[playbackPosition](https://spotify.github.io/ios-sdk/html/Protocols/SPTAppRemotePlayerState.html#//api/name/playbackPosition)` field.

Now, both calls are asynchronous, so if you are going to use a Timer, it's possible that synchronize the timer job and the callbacks will be challenging. That is, if you need to use the `playbackPosition` value exactly at a given time, and the call you are making will have a delayed response, that might not work for you.

What do you need the playback position for? Is it to update the UI? In that case, a workaround is to run your own timer for the UI component and override the value with the subscription to `playbackPosition`.

**Comment by louisk2** [comment]
Hi,

Are there any methods to retrieve the current playback position with a higher level of granularity? The application I am developing is a musical training app and needs to show visual feedback cues that match up exactly with the beats in the music. I intend on matching the current playback position with audio analysis api data to determine the current beat. It doesn't appear that the getPlayerState or playerStateDidChange will provide the necessary frequency needed, it would need to be 50ms or lower. Are my assumptions correct and/or is there an alternative solution?

Thank you!

**Comment by ThatcherDev** [comment]
Hey @mdelolmo could you expand on your idea about the asynchronous calls? I am trying to get the playback position every 5 seconds, however sometimes the returned position is delayed and does not represent the actual position. How could I remove this delay and make the position more accurate?
