### ISSUE TITLE
Spotify Play URI - not working in latest iOS SDK

### ISSUE THREAD

**Issue by azeemohd786** [spotify/ios-sdk#169]
6 months before, when I was trying to play Spotify song using Spotify URI, it was working fine in Xcode 10.1 | swift4 .Nowadays, it's not working.From native iOS app -not able play songs using Spotify player in Xcode 11 with swift5.  Also Is there any possibility to add AutoPan method in Spotify player?

Trying for a solution havn't got yet.

    
```
SPTAudioStreamingController.sharedInstance().playSpotifyURI("spotify:track:4aDLPXlzHZm26GppvRwms8", startingWith: 0, startingWithPosition: 10) { error in
                        if error != nil {
                            print("*** failed to play: \(error)")
                            return
                        }
                    }
```

When I tried with some break point ,error showing --

    `error: Error Domain=com.spotify.ios-sdk.playback Code=1 "The operation failed due to an unspecified issue." UserInfo={NSLocalizedDescription=The operation failed due to an unspecified issue.} `

Is there any written License or agreement to use Spotify Web API and player in native iOS App?...

**Comment by Amanpreet20** [comment]
Hi
Can you please confirm to play song is it required to navigate to Spotify app then authorise the token and back to my own application where I have integrated the Spotify SDK?

**Comment by azeemohd786** [comment]
@Amanpreet20 , YES, it will navigate to Spotify main app and return to your native app.

**Comment by Amanpreet20** [comment]
Thanks for the quick reply.
Is there any solution for this as we checked the Android SDK, it working smooth as per user experience. Because its not looking good to go to spotify when there is need to play song and return back again.

**Comment by azeemohd786** [comment]
@Amanpreet20 Last year onwards, Spotify have changed their SDK, there are lot of limits in present sdk and its access. It will navigate to Spotify main app and return to your native app.

**Comment by Amanpreet20** [comment]
Thanks for the information!!
