### ISSUE TITLE
Deleted Beta Releases

### ISSUE THREAD

**Issue by lprhodes** [spotify/ios-sdk#17]
Hey,

I'm glad you've continued work and created a 1.0.0 release but removing the betas is really frustrating. Our builds now fail and we're forced to spend time updating to 1.0 at a critical point in the project.

**Comment by jackfreeman** [comment]
@lprhodes If you are looking for the old streaming SDK it can be found here https://github.com/spotify/ios-streaming-sdk

If you are referring to the App Remote beta it can be found here https://github.com/spotify/ios-sdk/releases/tag/AppRemote_Beta_v1.0.0 (its API is compatible with the new SDK version so I would encourage to switch to the new SDK if this is the beta you are referencing)

**Comment by lprhodes** [comment]
I just found App Remote-Public-Beta. Not the best thing to wake up to though. Is there a migration guide?
