### ISSUE TITLE
refresh tokens not encrypted in beta 6 renewSession:withServiceEndpointAtURL

### ISSUE THREAD

**Issue by sbauch** [spotify/ios-sdk#175]
I have some general confusion about changes to auth with beta 6, but looking through the demo apps I think there may be something off. Here's how I handle auth:

1. open auth window in safari using `loginURLForClientId:declaredRedirectURL:scopes:withResponseType:` with `'code'` as the responseType

2. exchange code for access_token via token swap service on callback from safari 

3. store session data locally

4. On subsequent app opens, use `initWithUserName:accessToken:encryptedRefreshToken:expirationDate:` to initialize an SPTSession instance using the stored session data

5. immediately call isValid on the session. returns false if > 1 hour has passed

6. when false, call `renewSession:withServiceEndpointAtURL`

On my server, I initially copied over the ruby from the demo Sinatra app into my rails api. 

However, when I try to decrypt the refresh token, I got the error: `OpenSSL::Cipher::CipherError (wrong final block length)`. So instead I post the raw parameter for refresh_token to the refresh endpoint on the Spotify API, and everything works fine.

Also of note is that when I check the encryptedRefreshToken property on the session, it matches the value that is posted by the SDK in the refresh method.

So am I doing something wrong here? The examples make it seem like the refresh token would be encrypted coming from the SDK to my server endpoint, but they appear not to be.

I don't think I want to use the 'token' response type - that would exclude refresh tokens altogether.

I partially expected that `initWithUserName:accessToken:encryptedRefreshToken:expirationDate:` would take care of refreshing the access token if it was expired, and thusly isValid would always return true, but that appears to not be the case either.

**Comment by possan** [comment]
Have you found any solution to this?

**Comment by sbauch** [comment]
Not particularly. My app is live in the app store, and I haven't made any changes to my server side refresh token code, and refreshing auth tokens is working fine. So it's not really affecting me, but I do think it's still an issue, that the token posted by the SDK (version 6) isn't encrypted.

**Comment by possan** [comment]
The idea is that your backend should encrypt the refresh token in some way so that a third party will not be able to steal it and continue to be signed in as one of your users, the SDK has no knowledge of what this encrypted blob is, it just passes it back and forth when refreshing tokens.

So, if the server doesn't encrypt it, that's a bug in the example server that we should fix.

**Comment by possan** [comment]
Closing this, since running the bundled ruby examples requires the encrypted_strings.
