### ISSUE TITLE
Multiple Equalizers

### ISSUE THREAD

**Issue by m0rdice** [spotify/ios-sdk#175]
Hi guys,

could you establish different equalizers?
My car needs a different one, as my Hi-Fi systems or ear pod...

Kind regards,
 Patrick

**Comment by kkarayannis** [comment]
Is this about the Spotify app? This iOS SDK repo is for developers that want their application to interact with the Spotify app. If you want to report issues with the Spotify app, you can find information about how to contact us at https://support.spotify.com/us/article/how-can-i-contact-spotify
