### ISSUE TITLE
Question: authorizeAndPlayURI when in background.

### ISSUE THREAD

**Issue by cpizzaia** [spotify/ios-sdk#177]
Currently in our app we use the older streaming SDK for Spotify and we're looking to transition over to this SDK. Our app for long period of time can sit in the background and users can listen to voice audio from it and at certain moments begin to play music (through Spotify) under the voice audio. i.e. like a podcast with music playing at certain intervals.

I'm noticing that with this new SDK is that if the Spotify app suspends (due to lack of activity) and our app is in the background we won't be able to establish a connection again through authorizeAndPlayURI. Is there a work around for this or a way to make sure the Spotify app never suspends when not playing audio?

**Comment by kkarayannis** [comment]
Hi! Yes you are right, iOS 13 is especially aggressive in suspending apps, as it suspends them after only 30 seconds. Previously it was only a few minutes.
There is no way around this I'm afraid 😞
