### ISSUE TITLE
RemoteSDK Connection gets killed after pause Playback

### ISSUE THREAD

**Issue by anscash** [spotify/ios-sdk#181]
Hi guys.

I have this issue: If i pause a playback inside my app connected to the remoteSDK, the connection gets killed. Is there a way to prevent the spotify app from being killed after apprx. 1-3 seconds?

And if not, is there a way to reconnect the app with not jumping to the spotify app and jump back to my app? This would be very bad UX for me and there will be some moments my app does not play any tracks :-D
If i pause a track, the spotify app itself is alive, but the connection to my app is killed...

With kind regards
anscash

**Comment by kkarayannis** [comment]
> Is there a way to prevent the spotify app from being killed after apprx. 1-3 seconds?

There isn't, the system suspends Spotify if it's not playing music. However 1-3 seconds doesn't sound right. It should be 30 seconds in iOS 13, and it was significantly more (3-4 minutes) before iOS 13.

> is there a way to reconnect the app with not jumping to the spotify app and jump back to my app?

There isn't. An app needs to be in the foreground in order for it to start an audio session.
