### ISSUE TITLE
Crash when performing too frequent play requests

### ISSUE THREAD

**Issue by fotiDim** [spotify/ios-sdk#182]
If a user is a bit fast with his interactions and triggers play calls too often this crashes the SDK with:
```
2019-12-05 21:34:18.157143+0100 TunedeckSpotify[1261:258778] AppRemote: Sending request: <SPTAppRemoteCallRequest: 0x2839d5e30; id: 26, method: com.spotify.play_uri>
2019-12-05 21:34:18.159952+0100 TunedeckSpotify[1261:258575] *** Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[NSConcreteMutableData replaceBytesInRange:withBytes:length:]: range {0, 89} exceeds data length 0'
*** First throw call stack:
(0x1c0bc180c 0x1c08e9fa4 0x1c0eef318 0x1000dc578 0x1000e13bc 0x1000e16c8 0x1c0b57b1c 0x1c0b5711c 0x1c0b3f7c4 0x1c0b3f71c 0x1c0b3eeb4 0x1c0b3a000 0x1c0b398a0 0x1caa91328 0x1c4c2a740 0x100093220 0x1c09c4360)
libc++abi.dylib: terminating with uncaught exception of type NSException
```

The issue can be reproduced easily with this code:
```
while (true){
    self?.appRemote.playerAPI?.play(uri, asRadio: true, callback: { (result, error) in
        print("Player result: \(result)")
        print("Player error: \(error)")
    })
    usleep(500000)
}
```

**Comment by kkarayannis** [comment]
Hmm I can't reproduce it in the demo app, either manually or with the above code.
We use the `replaceBytesInRange:withBytes:length:` method in the stream writer class, which is the one that sends data to the Spotify app. It may be specific to the uri you are using. Can you share a uri that causes a crash?

**Comment by fotiDim** [comment]
@kkarayannis you are right about the example I provided above. It seems the crash happens when I call the above code within an NSURLSession dataTask callback. So you have to add a little bit more context to reproduce it. That should do the trick:

```
func crashSpotifySDK() {
            let task = URLSession.shared.dataTask(with: URL(string: "https://google.com")!, completionHandler: {[weak appRemote] data, response, error in
                while (true) {
                    appRemote?.playerAPI?.play("spotify:track:39ukbGu3UVWs74ba83T68c", asRadio: true, callback: { (result, error) in
                        print("all done")
                    })
                    usleep(500000)
                }
            })
            task.resume()
        }
```

**Comment by fotiDim** [comment]
It seems it is a threading issue.

**Running on main thread works fine**
```
URLSession.shared.dataTask(with: URL(string: "https://google.com")!, completionHandler: {[weak appRemote] data, response, error in
    while (true) {
        DispatchQueue.main.async {
            appRemote?.playerAPI?.play("spotify:track:39ukbGu3UVWs74ba83T68c", asRadio: true, callback: { (result, error) in
                print("all done")
            })
        }
        usleep(500000)
    }
}).resume()
```

**Running on background (default) thread makes it crash**
```
func selectedGenre() {
    URLSession.shared.dataTask(with: URL(string: "https://google.com")!, completionHandler: {[weak appRemote] data, response, error in
        while (true) {
            appRemote?.playerAPI?.play("spotify:track:39ukbGu3UVWs74ba83T68c", asRadio: true, callback: { (result, error) in
                print("all done")
            })
            usleep(500000)
        }
    }).resume()
}
```

In the readme you state: `No, the framework currently expects to be called from the main thread. It will offload most of its work to a background thread internally but callbacks to your code will also occur on the main thread.`

URLSession by default uses background threads for callbacks. I tried the same experiment with Alamofire and I was wondering how Alamofire was not crashing for me. Turns out Alamofire uses the main thread by default.

One possible take-away from this would be to add a thread check in the SDK and at least print a warning in the console if a reckless developer is calling it not using the main thread.

**Comment by kkarayannis** [comment]
> One possible take-away from this would be to add a thread check in the SDK and at least print a warning in the console if a reckless developer is calling it not using the main thread.

That's a good idea. Thanks for the suggestion, Foti!
