### ISSUE TITLE
more doc (esp. about playback)

### ISSUE THREAD

**Issue by thegreatmichael** [spotify/ios-sdk#188]
what does queueURI do? if i queueURI while nothing is playing, will it start playing automatically? if i queueURI while something is playing, will this queued thing be the very next track, or is it at the end of the queue? I think this is why the clearQueue option is there?

if i, playURI, then while it's playing, queueURI, will it continue on, or does playURI just mean to play this one track then stop?

is the best thing to do queueURI (firstOne), queueURI(secondOne), setIsPlaying(true)?

or should it be ok to playURI(firstOne), queueURI(secondOne)? 

I'm having trouble especially when the app goes into the background. That is, if i playURI(firstOne), queueURI(secondOne), then while firstOne is playing, change to another app, it will continue playing, but does not continue to secondOne. (I do have `App plays audio or streams audio/video using AirPlay` in my required background modes)

**Comment by possan** [comment]
Yes, this needs more documentation, and it's also subject to change.

Currently, the sdk internally operates in two different modes, you either queue stuff using `queueURI`, or you play single items (tracks, albums or playlists) using `playURI` - if you play stuff and then queue stuff, it will not switch from one of the modes to the other automatically. (ie. the queue doesn't work as it does in the Spotify applications)

I would recommend you to queue up a bunch of songs with `queueURI`, then do a `queuePlay` to start playing back that queue.

**Comment by thegreatmichael** [comment]
@possan Happy New Year! thanks for that info! MOST helpful.

**Comment by ahallora** [comment]
I've added songs to the queue using queueURI - but I can't seem to find the right method for starting playback of the queue. There's no queuePlay method in the documentation either:
https://developer.spotify.com/ios-sdk-docs/Documents/Classes/SPTAudioStreamingController.html

**Comment by thegreatmichael** [comment]
@ahallora https://developer.spotify.com/ios-sdk-docs/Documents/Classes/SPTAudioStreamingController.html#//api/name/queuePlay: (in the table of contents of the class, the functions are not in alphabetical order)
