### ISSUE TITLE
Questions about using Spotify SDK

### ISSUE THREAD

**Issue by Demkovskyi** [spotify/ios-sdk#189]
Hello,

  Our IOS application uses your Spotify SDK for audio streaming, but we have been warned that it will stop working soon. Could you please help us with the following questions:

Can we use your new Spotify SDK without installing a Spotify application?

Do you have any private / paid SDKs that we could use to increase the functionality of our application?

Your backend uses DRM encoding technology when streaming audio.  In order to use a different player (not from SDK) or can we do without it?

Is it possible to play your stream with another player?  If so, which one?

Is it possible to formally redirect your stream through our backend? 

Please apologize if this is not the correct address (please tell us email address with this issue)

**Comment by kkarayannis** [comment]
> Can we use your new Spotify SDK without installing a Spotify application?
No. All playback happens in the Spotify app.

> Do you have any private / paid SDKs that we could use to increase the functionality of our application?
No. This is only supported mobile SDK.

> Your backend uses DRM encoding technology when streaming audio. In order to use a different player (not from SDK) or can we do without it?
The Spotify app handles playback, so DRM is also handled.

> Is it possible to play your stream with another player? If so, which one?
No. Only the Spotify app is supported as a player.

> Is it possible to formally redirect your stream through our backend?
No.

**Comment by Demkovskyi** [comment]
Thanks for the answer
