### ISSUE TITLE
Auth error: 1002 "unsupported URL"

### ISSUE THREAD

**Issue by pandaxbacon** [spotify/ios-sdk#189]
I set up all the things I need on the Spotify developer portal, and edit the URL schema in my Xcode project.

![screen shot 2014-12-17 at 03 10 54](https://cloud.githubusercontent.com/assets/7383285/5460014/5ba5376c-859a-11e4-8450-ff3f4c16259e.png)

static NSString * const kCallbackURL = @"nerfire-hk-project-m://callback";

-(BOOL)application:(UIApplication *)application
           openURL:(NSURL *)url
 sourceApplication:(NSString *)sourceApplication
        annotation:(id)annotation {

        // Ask SPTAuth if the URL given is a Spotify authentication callback

    NSLog(@"callBack url >> %@", url);

    if ([[SPTAuth defaultInstance] canHandleURL:url withDeclaredRedirectURL:[NSURL URLWithString:kCallbackURL]]) {

        [[SPTAuth defaultInstance] handleAuthCallbackWithTriggeredAuthURL:url callback:^(NSError *error, SPTSession *session) {

            if (error != nil) {
                NSLog(@"*** Auth error: %@", error);
                return;
            }

        }];
......

And when I run the code.

Here is the callBackURL I have NSLogged:
callBack url >> nerfire-hk-project-m://callback?code=AQA4Q5uz-jKoSGPb80APGJMx6jofLbPpMY15nCBjSXmjBwca78NKDwwVzJ5S6E4TLQHgpoMvsUkPyPdyiUamWvDN1JsAmCDiqdwQoIxe33m60TB1N2PFE2yQDZuFf4-Z2iR_ugyGlkUPviPQX1GqhPb0SHR5_BqSRYpxC1cVuzFJRIUVmMBA7duE0CQb4GI8G9aFfIfpo7XBMtnmyQJ_LRXBW2bGWTYRHFy70ue48OH54RFvBY6F_jvPHwpDFVlshzSip8WtwDBlXDWDKqxDeVlMLRhuA-GzaaeQgeoWH4cQFOH_xJgnCMWyeIUemOlcsjjlnoB1ZfEjKSqmGcv98-t5SK70wM2qMPEXHxxcvAKPYXyaZqiWaGWtFLbw-Yo1h0qyxkY38IJMqDW-HSVslzjzHiA

And also the Auth error:
 *** Auth error: Error Domain=NSURLErrorDomain Code=-1002 "unsupported URL" UserInfo=0x1658aa00 {NSUnderlyingError=0x16593cb0 "unsupported URL", NSLocalizedDescription=unsupported URL}

I think I did everything right? and the callback url seems appropriate in format, any idea whats going on? thanks

**Comment by possan** [comment]
Could you try to change your callback to be without dashes, for example nerfirehkprojectm://callback and see if that solves the issue?

**Comment by JohnGoodstadt** [comment]
I am also getting this error. Did you fix it? If so how?

**Comment by possan** [comment]
Did it work by removing the dashes?

**Comment by possan** [comment]
I'm closing this, re-open if this is still an issue.

**Comment by plougy** [comment]
There is still the error on this issue.

```objective-c
NSURL *loginURL = [SPTAuth loginURLForClientId:[SPTAuth defaultInstance].clientID
                               withRedirectURL:[SPTAuth defaultInstance].redirectURL
                                        scopes:[SPTAuth defaultInstance].requestedScopes
                                  responseType:@"code"];
```

However when I use `loginURL` provided by the instance this works.
```objective-c
NSURL *loginURL = [SPTAuth defaultInstance].loginURL;
```
