### ISSUE TITLE
seek no longer works?

### ISSUE THREAD

**Issue by thegreatmichael** [spotify/ios-sdk#190]
The following code has started producing this error: 

    Seek Error: Error Domain=com.spotify.ios-sdk.playback Code=1 "The operation failed due to an unspecified issue." UserInfo=0x17007e040 {NSLocalizedDescription=The operation failed due to an unspecified issue.}

The snippet:

    println("about to seek to pos: \(pos)")
    self.player!.seekToOffset(pos, callback: {(seekError)->Void in
        if seekError != nil {
            println("Seek Error: \(seekError)")
        }
    })

Please advise.

**Comment by possan** [comment]
The delay hack is a workaround that will work for now, the problem is that the 0.1 constant might need to be longer :/

We'll probably add additional functions for starting playback from a certain position in the next release since this still seems to be a problem.

**Comment by thegreatmichael** [comment]
@possan if you do this, would it be possible that it is included for both playURI and queuePlay (where it'd start the first song at the given position)? (due to #188 )

**Comment by possan** [comment]
Yes, that's the plan.

**Comment by thegreatmichael** [comment]
awesome!

**Comment by RocketCity** [comment]
But `queuePlay` is deprecated, isn't it?  Yet it will be updated in next release? 

Wondering because I've been sitting here clicking on everything under `SPTAudioStreamingController` looking for any non-deprecated way just to play a song, and the only ones seem to be `playURI(s)`

**Comment by cjwhitsitt** [comment]
I am still getting the same error when seeking too early. Was this actually fixed?

**Comment by brki** [comment]
I'm still on Beta 14, and am seeing something perhaps related.

If I pause playback in the last 1 or 2 seconds of the track, I am no longer able to seek, trying to do so gives an error like:
```
Error while trying to seek to offset: 16.9658412722647: Error Domain=com.spotify.ios-sdk.playback Code=1 "The operation failed due to an unspecified issue." UserInfo={NSLocalizedDescription=The operation failed due to an unspecified issue.}
```

If I see this on the latest Beta, I'll open a new ticket for it.
