### ISSUE TITLE
Crash in audio streaming when deallocing

### ISSUE THREAD

**Issue by kennylovrin** [spotify/ios-sdk#191]
I just wanted to verify if this is expected behavior or not as I think I have read somewhere that it is supported to deallocate and allocate new audio controllers, given they are not alive at the same time?

I have a crash (same problem in two projects) where it seems to crash in a notify callback within SPTAudioStreamingController, and it seems to happen when I deallocate the audio controller.

I haven't been able to work around it other than keeping a singleton alive. I am however in a situation where I have a very customized core audio controller in one case, and in another case I just need the default behavior. It would great if I could deallocate my custom one and allocate a standard one when I need it, but I can't get it to work.

Just to clarify, the default one crashes like this wether I have allocated my own before or not, so it happens even without any "custom" code ever being allocated if you know what I mean.

I can't work out much from the error other than this so far in terms of where it crashes (I get a feeling it could perhaps be a delegate thing or something from the c lib that is trying to access something that has been deallocated as it is a bad access crash I think):
`cb_playback_on_notify at SPTAudioStreamingController.m:996

So the question is, IS it supported to deallocate and reallocate an SPTAudioStreamingController, and if so, is there a special way I have to deallocate it?

**Comment by possan** [comment]
It's not really optimal (and quite untested from our side) to have more than one instance of the player running in your app, the best way would be to initialize your player upon start up and keep using that the whole time.

**Comment by possan** [comment]
I'm closing this since it's quite old, the test app in the latest beta does deallocation and reallocation of the player and it seems to work fine.
