### ISSUE TITLE
currentPlaybackPosition stuck at end after seeking right before song finishes

### ISSUE THREAD

**Issue by GabeJacobs** [spotify/ios-sdk#194]
I'm playing a song that has a duration (SPTAudioStreamingMetadataTrackDuration) of 275.933014.

While the song plays, seeking to times between 0 - 275.933014 works fine and currentPlaybackPosition updates normally. However, for some odd reason when the currentPlaybackPosition gets past ~272, and then I try to seek to a earlier time, the currentPlaybackPosition does not update, but instead keeps getting bigger until it is just constantly 275.933014. When I seek, the song does in fact seek, but the currentPlaybackPosition does not update.

I can provide my code, but I think that explains it well. Any clue?

**Comment by possan** [comment]
I thought we fixed this bug in the last release :/, but there seems to be one case where the position could exceed the end of track

Probably related to when you're playing the same track on repeat for example and when it's not actually switching track

**Comment by possan** [comment]
Closing this, this should be fixed now in the latest release.

**Comment by GabeJacobs** [comment]
@possan perfect timing. You're the best :)
