### ISSUE TITLE
Token refresh/swap on own web site, how?

### ISSUE THREAD

**Issue by Anders27** [spotify/ios-sdk#197]
I’m primarily an audio developer and now have all Spotify audio stuff running perfect.

However the token refresh/swap thing is a big mystery to me and during development I have lived with having to login every now and then.
But this scenario is not OK when releasing the app to customers.

I have my own company web site:
http://www.mycompany.com 
hosted at a commercial web hosting company.

I know enough to be able to edit my html pages and upload them using FTP, but there it ends.

So I assume I could host the needed refresh/swap server(?) somewhere at my website?

My web hosting company allows me to install lots of different “Site applications” such as:
Ruby 1.9.3, Java JRE 1.6, Frontpage extensions and what not.

Could someone with a better knowledge, explain how to configure this stuff when we have our own web site.
Maybe using the “spotify_token_swap.rb” file changed in some way?

Someone (https://github.com/spotify/ios-sdk/issues/193) wrote:
“I've rewritten the spotify token exchange from the demo (in ruby) to node.js:”
Would this be a better or simpler approach?

https://github.com/spotify/ios-sdk/issues/139
and
https://github.com/spotify/ios-sdk/issues/159
also discusses this subject but is of no help to me.

This is probably not that difficult for people with experience in web development but I’m sure it would be a big big help for us “regular” audio developers.

Thanks for any help!

**Comment by ahallora** [comment]
If your shared web host supports Ruby you can just use the token exchange server provided in the examples by Spotify:
https://github.com/spotify/ios-sdk/blob/master/Demo%20Projects/spotify_token_swap.rb

I have experience with ruby but if you follow the instructions in the code example above you should get it working. :)

**Comment by Anders27** [comment]
Thanks for you reply!
Sometimes any answer is better than no answer at all.

Your reply made me give it a try and here are my results so far (hopefully useful for other people).

I installed ruby on my site using the web host company site application.
That installed Ruby ver. 1.9.3 (on my Mac running 10.9 it’s ver. 2.0.0)
I then installed “Sinatra” and “encrypted_strings”.

From the terminal i log into my website using SSH:
ssh username@mysite.com

Then entering the password when prompted.

I’m now located in:
/usr/home/username

I upload the “spotify_token_swap.rb” file edited with my CLIENT_ID, CLIENT_SECRET, and CLIENT_CALLBACK_URL into
/usr/local/


From the terminal using SSH I do:
ruby spotify_token_swap.rb

It runs but with some error:
[2015-01-06 01:57:23] ERROR NoMethodError: undefined method `join' for #<String:0xa2b6538>

Some Google search stated it could be a problem with “rack-1.6.0” so I installed “rack-1.5.2”
and added
gem 'rack', '1.5.2'
as the first line in the “spotify_token_swap.rb” file and gave it a new try.

The server starts!! Yippee!!

[2015-01-06 06:21:51] INFO  WEBrick 1.3.1
[2015-01-06 06:21:51] INFO  ruby 1.9.3 (2012-02-16) [i686-linux]
== Sinatra/1.4.5 has taken the stage on 1234 for development with backup from WEBrick
[2015-01-06 06:21:51] INFO  WEBrick::HTTPServer#start: pid=26641 port=1234

I run my app on my iPhone, the app is able to login to my server (here is log from the terminal):

OpenSSL::SSL::SSLError - SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed:
	/usr/local/ruby-1.9.3/lib/ruby/1.9.1/net/http.rb:799:in `connect'
	/usr/local/ruby-1.9.3/lib/ruby/1.9.1/net/http.rb:799:in `block in connect'
	/usr/local/ruby-1.9.3/lib/ruby/1.9.1/timeout.rb:54:in `timeout'
	/usr/local/ruby-1.9.3/lib/ruby/1.9.1/timeout.rb:99:in `timeout'
	/usr/local/ruby-1.9.3/lib/ruby/1.9.1/net/http.rb:799:in `connect'
	/usr/local/ruby-1.9.3/lib/ruby/1.9.1/net/http.rb:755:in `do_start'
	/usr/local/ruby-1.9.3/lib/ruby/1.9.1/net/http.rb:744:in `start'
	/usr/local/ruby-1.9.3/lib/ruby/1.9.1/net/http.rb:1284:in `request'
	spotify_token_swap.rb:81:in `block in <main>'
	/usr/local/ruby-1.9.3/lib/ruby/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:1603:in `call'
	/usr/local/ruby-1.9.3/lib/ruby/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:1603:in `block in compile!'
	/usr/local/ruby-1.9.3/lib/ruby/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:966:in `[]'
	/usr/local/ruby-1.9.3/lib/ruby/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:966:in `block (3 levels) in route!'
	/usr/local/ruby-1.9.3/lib/ruby/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:985:in `route_eval'
	/usr/local/ruby-1.9.3/lib/ruby/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:966:in `block (2 levels) in route!'
	/usr/local/ruby-1.9.3/lib/ruby/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:1006:in `block in process_route'
	/usr/local/ruby-1.9.3/lib/ruby/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:1004:in `catch'
	/usr/local/ruby-1.9.3/lib/ruby/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:1004:in `process_route'
	/usr/local/ruby-1.9.3/lib/ruby/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:964:in `block in route!'
	/usr/local/ruby-1.9.3/lib/ruby/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:963:in `each'
	/usr/local/ruby-1.9.3/lib/ruby/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:963:in `route!'
	/usr/local/ruby-1.9.3/lib/ruby/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:1076:in `block in dispatch!'
	/usr/local/ruby-1.9.3/lib/ruby/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `block in invoke'
	/usr/local/ruby-1.9.3/lib/ruby/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `catch'
	/usr/local/ruby-1.9.3/lib/ruby/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `invoke'
	/usr/local/ruby-1.9.3/lib/ruby/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:1073:in `dispatch!'
	/usr/local/ruby-1.9.3/lib/ruby/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:898:in `block in call!'
	/usr/local/ruby-1.9.3/lib/ruby/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `block in invoke'
	/usr/local/ruby-1.9.3/lib/ruby/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `catch'
	/usr/local/ruby-1.9.3/lib/ruby/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `invoke'
	/usr/local/ruby-1.9.3/lib/ruby/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:898:in `call!'
	/usr/local/ruby-1.9.3/lib/ruby/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:886:in `call'
	/usr/local/ruby-1.9.3/lib/ruby/gems/1.9.1/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'
	/usr/local/ruby-1.9.3/lib/ruby/gems/1.9.1/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'
	/usr/local/ruby-1.9.3/lib/ruby/gems/1.9.1/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'
	/usr/local/ruby-1.9.3/lib/ruby/gems/1.9.1/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
	/usr/local/ruby-1.9.3/lib/ruby/gems/1.9.1/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
	/usr/local/ruby-1.9.3/lib/ruby/gems/1.9.1/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'
	/usr/local/ruby-1.9.3/lib/ruby/gems/1.9.1/gems/rack-1.5.2/lib/rack/logger.rb:15:in `call'
	/usr/local/ruby-1.9.3/lib/ruby/gems/1.9.1/gems/rack-1.5.2/lib/rack/commonlogger.rb:33:in `call'
	/usr/local/ruby-1.9.3/lib/ruby/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:217:in `call'
	/usr/local/ruby-1.9.3/lib/ruby/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:210:in `call'
	/usr/local/ruby-1.9.3/lib/ruby/gems/1.9.1/gems/rack-1.5.2/lib/rack/head.rb:11:in `call'
	/usr/local/ruby-1.9.3/lib/ruby/gems/1.9.1/gems/rack-1.5.2/lib/rack/methodoverride.rb:21:in `call'
	/usr/local/ruby-1.9.3/lib/ruby/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/show_exceptions.rb:21:in `call'
	/usr/local/ruby-1.9.3/lib/ruby/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:180:in `call'
	/usr/local/ruby-1.9.3/lib/ruby/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:2014:in `call'
	/usr/local/ruby-1.9.3/lib/ruby/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:1478:in `block in call'
	/usr/local/ruby-1.9.3/lib/ruby/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:1788:in `synchronize'
	/usr/local/ruby-1.9.3/lib/ruby/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:1478:in `call'
	/usr/local/ruby-1.9.3/lib/ruby/gems/1.9.1/gems/rack-1.5.2/lib/rack/handler/webrick.rb:60:in `service'
	/usr/local/ruby-1.9.3/lib/ruby/1.9.1/webrick/httpserver.rb:138:in `service'
	/usr/local/ruby-1.9.3/lib/ruby/1.9.1/webrick/httpserver.rb:94:in `run'
	/usr/local/ruby-1.9.3/lib/ruby/1.9.1/webrick/server.rb:191:in `block in start_thread'
12-345-678-127-no28.tbcn.telia.com - - [06/Jan/2015:06:23:00 MST] "POST /swap HTTP/1.1" 500 154506
- -> /swap

Then it fails here:

      // Ask SPTAuth if the URL given is a Spotify authentication callback
      if ([[SPTAuth defaultInstance] canHandleURL:url withDeclaredRedirectURL:[NSURL URLWithString:kCallbackURL]])
        {
        // Call the token swap service to get a logged in session
        [[SPTAuth defaultInstance]
            handleAuthCallbackWithTriggeredAuthURL:url
            tokenSwapServiceEndpointAtURL:[NSURL URLWithString:kTokenSwapURL]
              callback:^(NSError *error, SPTSession *session)
          {
          if (error != nil)
            {
            DLog(@"*** Auth error: %@", error);
            return;
            }

          NSLog(@"*** Auth OK session: %@", session);
          }];

        return YES;

        }

with the following error:

*** Auth error: Error Domain=NSCocoaErrorDomain Code=3840 "The operation couldn’t be completed. (Cocoa error 3840.)" (JSON text did not start with array or object and option to allow fragments not set.) UserInfo=0x171665380 {NSDebugDescription=JSON text did not start with array or object and option to allow fragments not set.}	


Can anyone explain what this error means and how to resolve it?

"POST /swap HTTP/1.1" 500 154506

does this mean “500 Internal Server Error”?

Thanks for any help!

**Comment by possan** [comment]
Looking at the openssl errors it looks like you're trying to do https://domain/swap instead of http.

**Comment by possan** [comment]
What happens if you run `curl "https://api.spotify.com/v1/tracks/2Eea4LBy0ZJ2IH1IH2zThv"` on your server, do you see a openssl error for that request too?

**Comment by Anders27** [comment]
I get the following error:
curl: (35) error:0D0890A1:asn1 encoding routines:ASN1_verify:unknown message digest algorithm

**Comment by Anders27** [comment]
Must my web site have OpenSSL installed?
Could that be the problem?
I have an option to install Open SSL 0.9.6, should I do that?

**Comment by possan** [comment]
Did you solve this issue?

**Comment by possan** [comment]
I'm closing this, re-open if this is still an issue.
