### ISSUE TITLE
Apple rejects apps with Spotify iOS SDK

### ISSUE THREAD

**Issue by Zwaaan** [spotify/ios-sdk#198]
My app just got rejected by Apple for using your solution with the Spotify SDK.

Reason:
"10.6: Apple and our customers place a high value on simple, refined, creative, well thought through interfaces. They take more work but are worth it. Apple sets a high bar. If your user interface is complex or less than very good, it may be rejected"

And explanation:
"We found users are taken out to a web browser to login with Spotify, then returned to the app, which is not in compliance with the App Store Review Guidelines. The user should be able to log in within the app, such as in a web view as an example."

I really hope you will take this seriously and look over your solution, since apps will get rejected if they use the one you are using now.

**Comment by ahallora** [comment]
You can circumvent it by modifying the openLoginPage() function in the AppDelegate from opening the url in safari to opening in a web view inside your app. I've got it working but am struggling with handling the callback from within the webview. The authorization does work nonetheless within the web view. However, this workaround is in violation with the Spotify ToS.

See spotify framework -> Headers -> sptauth.h:
 @warning You must open this URL with the system handler to have the auth process
 happen in Safari. Displaying this inside your application is against the Spotify ToS.

So, I assume Spotify will change their ToS to allow in-app authorization as Apple will have the last word in this matter. :)

**Comment by GabeJacobs** [comment]
Any idea on the time table for the next release?

**Comment by pabloblancog** [comment]
I got my app accepted last week, using Spotify iOS SDK beta 6. 
Maybe an exception... I don't know how hard Apple is reviewing the apps, because mine was approved to release in less than half an hour...

**Comment by loretoparisi** [comment]
@pabloblancog that's a good news, we have found that Apple is not accepting apps that do SSO with FAS between the app and Safari mobile, like this with G+:

```
We found the following issue with the user interface of your app:

The app opens a web page in mobile Safari for creating an account or logging in for Google+ account, then returns the user to the app. The user should be able to create an account or log in without opening Safari first.﻿
```

So I guess in your case it was an exception or the reviewer did not look at it.
As for Apple recommendation, the best solution is the WebView as the Spotify team @possan (thank you)  is going to do for the next release.

**Comment by loretoparisi** [comment]
Waiting for a solution by Spotify team,
my temporary solution to support the Embedded WebView was

1) Do a server-side Spotfy oAuth on our servers (same flow of the SDK endpoints)
2) Intercept the access_token, refresk_token, expires_in fields

```
        NSString *accessToken = [response objectForKey:@"access_token"];
        NSString *refreshToken = [response objectForKey:@"refresh_token"];
        NSTimeInterval expiresIn = [[response objectForKey:@"expires_in"] integerValue];
        [[MXMSpotifyManager sharedInstance] loginWithAccessToken:accessToken refreshToken:refreshToken expirationTimeInterval:expiresIn completion:^(NSError *error) {
                [[MXMLogger sharedLogger] debug:@"Spotify logged with error:%@", error?error:@""];
            }];
```

where

3) Use the User Profile REST API to get the Username like:

```
- (void)fetchUserProfileWithAccessToken:(NSString*)accessToken completion:(void (^)(id results, NSError* error))completion {
    
    NSString *apiUrl = [NSString stringWithFormat:@"https://api.spotify.com/v1/me/?access_token=%@", accessToken];
    NSURL *url = [NSURL URLWithString:apiUrl];
    
    NSMutableURLRequest *urlRequest = [NSMutableURLRequest requestWithURL:url];
    NSOperationQueue *queue = [[NSOperationQueue alloc] init];
    [NSURLConnection sendAsynchronousRequest:urlRequest queue:queue completionHandler:^(NSURLResponse *response, NSData *data, NSError *error) {
        if (error) {
            completion(nil,error);
        }
        else {
            NSLog(@"%@", [[NSString alloc] initWithData:data encoding:NSASCIIStringEncoding]);
            
            NSError *err=nil;
            NSDictionary *jsonResult = [NSJSONSerialization JSONObjectWithData:data options:NSJSONReadingAllowFragments error:&err];
            if(!err) {
                completion(jsonResult,nil);
            } else {
                completion(nil,err);
            }
        }
        
    }];
}
```

4) Create a new SPTSession object with resulting info then:

```
-(void)loginWithAccessToken:(NSString *)accessToken refreshToken:(NSString*)refreshToken expirationTimeInterval:(NSTimeInterval)timeInterval completion:(void (^)(NSError* error))completion {
    
    MXMSpotifyManager *weakSelf = self;
    [self fetchUserProfileWithAccessToken:accessToken completion:^(id result, NSError *error) {
        if(!error && result) {
            [[MXMLogger sharedLogger] debug:@"User profile\n%@", result];
            if( [result objectForKey:@"id"] ) {
                NSString *userName =  [result objectForKey:@"id"];
                SPTSession *_session = [[SPTSession alloc] initWithUserName:userName accessToken:accessToken expirationTimeInterval:timeInterval];
                [weakSelf setSession:_session]; // <---- here we set the SPTSession object
                [weakSelf silentLoginSpotify:^(NSError *error) {
                    if(completion) completion(error);
                }];
            } else {
                NSError *error = [[NSError alloc] initWithDomain:kMXMSpotifyDefaultException code:kMXMSpotifyErrorUserLogin userInfo:nil];
                if(completion) completion(error);
            }
            
        }
        if(completion) completion(error);
    }];
}
```


4) Silently login to the Spotify SDK
Done through the SDK and you SDK implementation.

Hope this helps!

**Comment by loretoparisi** [comment]
It turns out that logging in with Spotify through a Facebook account, the XHR call gives out an error:

Status Code:
400 Bad Request error

https://accounts.spotify.com/us/authorize/accept POST

This happens in a Embedded WebView and a normal browser as well.

In the case of the Embedded Web View the page just get stuck since the XHR calls are not intercepted by the UIWebView delegates.

**Comment by SpiderKenny** [comment]
Is there any update on this issue?
Some news from Spotify would be very welcome!

**Comment by GabeJacobs** [comment]
Sounds like we just gotta wait for their next release. But it would be really great for it to come sooner rather than later!

Also it would be great if it logged the user in if they have logged in through the spotify app on their phone. Just like for Facebook. Makes the whole process a lot faster

**Comment by jarrodrobins** [comment]
+1 for sooner rather than later. Can we have an (even vague) indication of when it'll be available? Days? Weeks? Next month? Even if it's a bit buggy it's better than nothing.

We can't really use CocoalibSpotify due to that big 64-bit issue and this library isn't useable until this problem is sorted.

**Comment by loretoparisi** [comment]
If you use the solution depicted above it works in the same way. There's no really need to have it in the SDK actually. You just need your server (and if you do oauth you should have already), and a UIWebView to handle the incoming and outgoing requests.

**Comment by GabeJacobs** [comment]
If anything, I would love an update that solves this issue and only this issue. No need to bundle it together with potentially other buggy code. I feel like this is important enough for a standalone update

**Comment by s** [comment]
My application wasn't rejected and it uses external login through safari. I don't understand that reason. And my application was approved at the end of January. https://itunes.apple.com/tr/app/5artists/id950420999?mt=8 
Also you can see source code here:
https://github.com/s/5Artists

**Comment by dtrenz** [comment]
+1 My app was also just rejected by Apple for this reason.

I believe I have seen apps auth using the Spotify iOS app, if the user has it installed. Is this a supported - but possibly undocumented - auth option?

**Comment by CVertex** [comment]
@s Our app was accepted the first time and rejected subsequently

**Comment by gbrickley** [comment]
It seems like the consensus is that you must embed the login in a UIWebView, which I have done, but does anyone have any tips on how to get the authDelegate block to get called?  When I opened the login in an external page I was able to put the authCallback block inside the  application:openURL:sourceApplication:annotation: method and it worked great.  Now that I'm using a UIWebView I can't get the authCallback to run no matter where I put it.

This is part of my code for opening the UIWebView:

  [[SPTAuth defaultInstance] handleAuthCallbackWithTriggeredAuthURL:loginURL tokenSwapServiceEndpointAtURL:[NSURL URLWithString:kTokenSwapServiceURL] callback:authCallback];
[self.webView loadRequest:[NSURLRequest requestWithURL:loginURL]];


I'm getting an error, basically saying that my authCallback block is nil no matter where I put it.

**Comment by loretoparisi** [comment]
Hey @gbrickley look at the solution I show up here. You should be able to do this with few changes in your Spotify Manager class.

You have to do the following steps:

1) Retrieve the access token. You do that within the UIWebView as showed above in the webViewDidFinishLoad method that is a good place since the oauth process makes several calls and redirect before getting the final url with the access token,

```
- (void)webViewDidFinishLoad:(UIWebView *)_webView {
```

2) If you have set up your callback in the UIWebView, you can do this in a async way as soon as the previous method is getting called, you can fire that callback:

```
 if( [API_HOST rangeOfString:host].location!=NSNotFound ) { // our host
            if( [path rangeOfString:@"callback"].location!=NSNotFound) { // callback
                if( [navigatorUrl rangeOfString:@"?"].location!=NSNotFound) { // params
                    NSString *qs = [navigatorUrl substringFromIndex:[navigatorUrl rangeOfString:@"?"].location+1];
                    NSDictionary *params = [self dictionaryFromQueryString:qs];
                    if(self.callback) {
                        self.callback(params,nil);
                    }
                }
            }
        }
```

3) At this point you need to fetch the user profile, since to login you need the user:

```
- (void)fetchUserProfileWithAccessToken:(NSString*)accessToken completion:(void (^)(id results, NSError* error))completion {
```

4) Now you have everything to login the SPTSession:

```
-(void)loginWithAccessToken:(NSString *)accessToken refreshToken:(NSString*)refreshToken expirationTimeInterval:(NSTimeInterval)timeInterval completion:(void (^)(NSError* error))completion {
```

Note that you get a SPTSession object here:

```
SPTSession *_session = [[SPTSession alloc] initWithUserName:userName accessToken:accessToken expirationTimeInterval:timeInterval];
                [weakSelf setSession:_session]; // <---- here we set the SPTSession object
 ```             

This is the complete workflow.

Now, supposed that you have your  ```LoginWebViewController ``` to handle this, check out this method that I didn't show before:

  ```
/**
 * Login Spotfiy Client With A Embedded WebView Controller
 */
-(void)loginWithViewController:(UIViewController*)viewController completion:(void (^)(NSError *error))completion {
    
    MXMSpotifyManager *weakSelf = self;
    LoginWebViewController *loginWebViewController = [[LoginWebViewController alloc] initWithNibName:@"LoginWebViewController" bundle:nil];
    [loginWebViewController removeCookies];
    [viewController presentViewController:loginWebViewController animated:YES completion:^{
       [loginWebViewController doSpotifyLogin:^(id result, NSError *error) {
       
           NSString *accessToken = [result objectForKey:@"access_token"];
           NSString *refreshToken = [result objectForKey:@"encrypted_refresh_token"];
           NSTimeInterval expiresIn = [[result objectForKey:@"expires_in"] integerValue];
           
           [weakSelf loginWithAccessToken:accessToken refreshToken:refreshToken expirationTimeInterval:expiresIn completion:^(NSError *error) {
               [[MXMLogger sharedLogger] debug:@"Spotify logged with error:%@", error?error:@""];
               [loginWebViewController dismissViewControllerAnimated:YES completion:^{
                   
               }];
           }];
           
       }];
    }];
    
}

  ```

I prefer to reset cookies here in the UIWebView for testing purposes:

  ```
-(void) removeCookies {

    NSHTTPCookieStorage *storage = [NSHTTPCookieStorage sharedHTTPCookieStorage];
    for (NSHTTPCookie *cookie in [storage cookies]) {
        [storage deleteCookie:cookie];
    }
    [[NSUserDefaults standardUserDefaults] synchronize];

}
  ```

The    ```LoginWebViewController ``` is a standard class that handles the UIWebViewDelegate and something else:

  ```
#import <UIKit/UIKit.h>
#import "NJKWebViewProgress.h"

typedef void(^MXMLoginCallback)(id result, NSError *error);

@interface LoginWebViewController : UIViewController<UIWebViewDelegate, UIScrollViewDelegate, NJKWebViewProgressDelegate> {
    UIWebView *webView;
}

@property(nonatomic,strong) IBOutlet UIWebView *webView;
@property(nonatomic,strong) IBOutlet UINavigationBar *navBar;

-(void) doGooglePlusLogin:(void (^)(id result, NSError* error))completion;
-(void) doFacebookLogin:(void (^)(id result, NSError* error))completion;
-(void) doMusixmatchLogin:(void (^)(id result, NSError* error))completion;
-(void) doSpotifyLogin:(void (^)(id result, NSError* error))completion;
-(void) openURL:(NSURL*)url completion:(void (^)(id result, NSError* error))completion;
-(void) removeCookies;
-(IBAction)dismiss:(id)sender;
@end

  ```

Maybe you wish to get back all the UIWebView url parameters in a dictionary in a fashion way:

  ```
- (NSDictionary *)dictionaryFromQueryString:(NSString*)queryString {
    
    NSMutableDictionary *queryComponents = [NSMutableDictionary dictionary];
    for(NSString *keyValuePairString in [queryString componentsSeparatedByString:@"&"])
    {
        NSArray *keyValuePairArray = [keyValuePairString componentsSeparatedByString:@"="];
        if ([keyValuePairArray count] < 2) continue;
        NSString *key = [self stringByEncodingURLFormat:[keyValuePairArray objectAtIndex:0]];
        NSString *value = [self stringByEncodingURLFormat:[keyValuePairArray objectAtIndex:1]];
        [queryComponents setObject:value forKey:key];
    }
    return queryComponents;
}
  ```

There is no need to call the ```handleAuthCallbackWithTriggeredAuthURL  ``` since you are going to create a SPTSession back from the access token and username after the embedded webview oAuth process.

Infact as you can see in the method above

  ```
-(void)loginWithViewController:(UIViewController*)viewController completion:(void (^)(NSError *error))completion 
  ```

you have:

  ```
[viewController presentViewController:loginWebViewController animated:YES completion:^{
       [loginWebViewController doSpotifyLogin:^(id result, NSError *error) {
       
           NSString *accessToken = [result objectForKey:@"access_token"];
           NSString *refreshToken = [result objectForKey:@"encrypted_refresh_token"];
           NSTimeInterval expiresIn = [[result objectForKey:@"expires_in"] integerValue];
           
           [weakSelf loginWithAccessToken:accessToken refreshToken:refreshToken expirationTimeInterval:expiresIn completion:^(NSError *error) {
               [[MXMLogger sharedLogger] debug:@"Spotify logged with error:%@", error?error:@""];
               [loginWebViewController dismissViewControllerAnimated:YES completion:^{
                   
               }];
           }];
           
       }];
  ```

that does the trick.

NOTE. I suppose that your nodejs / other backend is handling in the right way the oauth 2.0 refresh/callback/token urls.

**Comment by chrishale** [comment]
I think I've found a simpler way to do this, this seems to work fine for me:

````
import UIKit

class SpotifyLoginController: UIViewController, UIWebViewDelegate {
    
    let webView: UIWebView = UIWebView(frame: CGRectZero)
    
    var completion: (session: SPTSession)->Void = { (session: SPTSession) in }
    
    override func loadView() {
        super.loadView()
        self.webView.frame = self.view.bounds
        self.webView.userInteractionEnabled = true
        self.view = self.webView
    }
    
    override func viewDidLoad() {
        super.viewDidLoad()
        self.webView.delegate = self
    }
    
    func login(completion: ((session: SPTSession)->Void)) {
        self.completion = completion
        var loginURL: NSURL = SPTAuth.defaultInstance().loginURLForClientId(kClientId,
            declaredRedirectURL: NSURL(string: kCallbackURL),
            scopes: [SPTAuthStreamingScope, SPTAuthPlaylistReadPrivateScope, SPTAuthUserReadPrivateScope])
        let request: NSURLRequest = NSURLRequest(URL: loginURL, cachePolicy: NSURLRequestCachePolicy.ReloadIgnoringLocalCacheData, timeoutInterval: 10)
        self.webView.loadRequest(request)
    }
    
    func webView(webView: UIWebView, shouldStartLoadWithRequest request: NSURLRequest, navigationType: UIWebViewNavigationType) -> Bool {
        let url: NSURL = request.URL
        if (SPTAuth.defaultInstance().canHandleURL(url, withDeclaredRedirectURL: NSURL(string:kCallbackURL))) {
            SPTAuth.defaultInstance().handleAuthCallbackWithTriggeredAuthURL(url, tokenSwapServiceEndpointAtURL: NSURL(string: kTokenSwapServiceURL)) { (error, session) -> Void in
                if (error != nil) {
                    println("Auth error: \(error.localizedDescription)")
                    return
                }
                self.dismissViewControllerAnimated(true) {
                    self.completion(session: session)
                }
            }
        }
        return true
    }

}
````

**Comment by possan** [comment]
Sorry for this taking so long, but we're on this and we're trying to get a solution out this week that will use UIWebViews initially, but eventually will support SSO when we get that support in...

**Comment by GabeJacobs** [comment]
Ok awesome. Keep us updated!

**Comment by loretoparisi** [comment]
That's a good news @possan. My embedded web view solution works fine, but it does not handle facebook account for some reason i.e. there's no response from Spotify oAuth since when trying to login with Facebook I get javascript errors:

(Safari Console Web Inspector)
Failed to load resource: the server responded with a status of 400 (Bad Request)
URI: https://accounts.spotify.com/it/authorize/accept

This happens tapping the button "OK" on the Confirm page at the end of the process (after Facebook login)

![screen_shot_2015-03-04_at_12_42_13](https://cloud.githubusercontent.com/assets/163333/6483062/fffa3254-c26c-11e4-8fc9-5eb82e140bd5.png)

**Comment by possan** [comment]
We just sent out a new version, which should fix this issue, it would be great if you could confirm that it's fixed.

**Comment by possan** [comment]
(No SSO yet though, that will take some time)

**Comment by loretoparisi** [comment]
great we will check it out!

**Comment by GabeJacobs** [comment]
Awesome! Thank you! Will this automatically update if we do pod update?

**Comment by GabeJacobs** [comment]
woops, forgot you weren't a pod...

**Comment by loretoparisi** [comment]
So after updating SPAuth methods and setters we get a crash here:

```
if ( [[SPTAuth defaultInstance] canHandleURL:url]  ) {
        [[SPTAuth defaultInstance] handleAuthCallbackWithTriggeredAuthURL:url callback:authCallback];
        return YES;
    }
```

where the url was

```
DEBUG: URL:testapp://oauth/sp/callback?code=xxxxx application:com.apple.mobilesafari
libc++abi.dylib: terminate_handler unexpectedly threw an exception
```

If I don't check the url it works fine (playlists and playback).

**Comment by GabeJacobs** [comment]
Awesome. Got it to work, great job. However, it would be super awesome if logging into facebook would just work if they have the facebook app installed and have already logged in. Is that possible?

**Comment by abrock17** [comment]
I was in the midst of getting authentication to work when this new version was released.  It looks *much* simpler than what was in version 6 - kudos for that.  From what I can tell, the "Simple Track Playback" example project has been updated to use the new SPTAuthViewController, but now it looks like a lot of the code in that example is no longer needed.  Is this the case?  And if so, can you please update the example and your docs for developers who are new to the SDK?  Many thanks.

**Comment by possan** [comment]
I'm closing this, re-open if this is still an issue.

**Comment by intrepidmatt** [comment]
My app was just rejected for a different reason than above:

From Apple
11.13 - Apps that link to external mechanisms for purchases or subscriptions to be used in the App, such as a "buy" button that goes to a web site to purchase a digital book, will be rejected

11.13 Details:
Your app includes an account registration feature, which is considered an access to external mechanisms for purchases or subscriptions to be used in the app. Specifically, your app links out to the Sportify website for account registration. This feature does not comply with the App Store Review Guidelines.

**Comment by shto** [comment]
Sportify lol

**Comment by pabloblancog** [comment]
My app has been updated without problems a few minutes ago :)

**Comment by GabeJacobs** [comment]
@intrepidmatt did you include any extra sign up process in your app? Or just the normal login.

**Comment by intrepidmatt** [comment]
I appealed the rejection and Apple changed their mind.

**Comment by GabeJacobs** [comment]
@intrepidmatt we just got rejected too. How did you appeal?

They said this:

"2.25 Details

The Spotify feature in your app displays or promotes third-party apps, which violates the App Store Review Guidelines. "

**Comment by uknowmeright** [comment]
I noticed the sign up option is not appearing anymore in the Webview. Is that in response to this issue? Also has anyone tried submitting yet with this update?

**Comment by GabeJacobs** [comment]
We just got accepted. I think it was the sign up button that did the trick

**Comment by GabeJacobs** [comment]
@possan thanks for being quick with that. You da best

**Comment by ungureanuli** [comment]
The new authentication way works great on iOS 8.x , but not on iOS 7.1.x .
After creating an instance of SPTAuthViewController, when I try display it using presentViewController:animated:completion: I get the errors:
*** WebKit discarded an uncaught exception in the webView:decidePolicyForNavigationAction:request:frame:decisionListener: delegate: <NSInvalidArgumentException> -[__NSCFString containsString:]: unrecognized selector sent to instance 0x7a0e17a0
The web view is not displayed anymore (just a blank view), the user can only dismiss it.

Also, when calling the clearCookies methos I get a crash:
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFString containsString:]: unrecognized selector sent to instance 0x7bef4810'


So I guess you should not use the containsString method as it is only available from iOS8 (http://stackoverflow.com/questions/26410420/nsstring-containsstring-crashes).
