### ISSUE TITLE
Spotify Developer Terms of Service

### ISSUE THREAD

**Issue by DiegoResnik** [spotify/ios-sdk#20]
I saw in the "Spotify Developer Terms of Service" that I need spotify approval for use of spotify ios-sdk in a commercial app.
1. Does remote sdk also under the same restriction?
2. How can I get this approval?

**Comment by jackfreeman** [comment]
@DiegoResnik Yes you will need approval. When you create a new client-id at https://developer.spotify.com/dashboard/applications you will be asked if it's for a commercial app. If you click `YES` you will be taken to a form to apply for approval.

**Comment by DiegoResnik** [comment]
Ok, thank you, @jackfreeman , for the quick response. 
where can I see the status of my application? or how much time it should take to get an answer?

**Comment by arirawr** [comment]
Hi @DiegoResnik - we do not have any status tracking for the applications. The partnerships team will reach out directly to you via the contact details you provided if you application is approved. We do not have an estimated time frame, but the process can take several months. In the meantime, you can use the SDK for non-commercial/non-production purposes.

Let me know if you have any further questions.

**Comment by DiegoResnik** [comment]
Hi @arirawr,
I've sent an application to my app a few months ago, still didn't receive any answer.
I'm almost ready with a beta version which includes Spotify remote api implementation, so I can add screenshots or more information to the application if needed (only I don't know if & where I should do this).
