### ISSUE TITLE
Spotify iOS SDK and iOS 5

### ISSUE THREAD

**Issue by Anders27** [spotify/ios-sdk#203]
I still have an old iPad 1 running iOS 5.1.1

Since adding support for Spotify my (which still supports iOS 5) quits with the following error: 

objc[6081]: Object 0x545f80 of class __NSCFString autoreleased with no pool in place - just leaking - break on objc_autoreleaseNoPool() to debug
2015-01-04 11:46:20.486 myApp[6081:707] -[__NSCFDictionary setObject:forKeyedSubscript:]: unrecognized selector sent to instance 0x5463e0
2015-01-04 11:46:20.493 myApp[6081:707] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFDictionary setObject:forKeyedSubscript:]: unrecognized selector sent to instance 0x5463e0'
*** First throw call stack:
(0x357f688f 0x3341a259 0x357f9a9b 0x357f8915 0x35753650 0x33414ae9 0x334148db 0x2fe227d1 0x2fe2b85b 0x2fe2c82d 0x2fe23a41 0x2fe27c1d 0x2fe222cf 0x2fe22060)
terminate called throwing an exception(lldb) 

This happens when the Spotify framework is loaded, before
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions	
and even before main().

So even if one doesn’t intend to support Spotify, the app doesn’t even start. 

The Spotify SDK uses

@interface NSMutableDictionary (NSExtendedMutableDictionary)
- (void)setObject:(id)obj forKeyedSubscript:(id <NSCopying>)key NS_AVAILABLE(10_8, 6_0);
@end

which requires iOS 6 or better.

I fixed that by adding

@implementation NSObject (MyNSObjectCategory)

- (void)setObject:(id)obj forKeyedSubscript:(id <NSCopying>)key
{
  [(NSMutableDictionary *)self setObject:obj forKey:key];
}

@end

which makes my app run on iOS 5.1.1 again, This is obviously a big hack so it would be better if the Spotify SDK in the loading phase did a check with respondsToSelector:@selector(forKeyedSubscript::)…

**Comment by iKenndac** [comment]
The SDK's minimum supported target is iOS 7. We'll make this more clear in the next release.
