### ISSUE TITLE
Spotify SDK and iOS 6

### ISSUE THREAD

**Issue by Anders27** [spotify/ios-sdk#204]
When running my old iPhone 3GS with iOS 6.1.6 and setting it up using

mPlayer = [[SPTAudioStreamingController alloc] initWithClientId:cliendID audioController:myAudioController];

the app crashes:

dyld: lazy symbol binding failed: Symbol not found: ___sincos_stret
  Referenced from: /var/mobile/Applications/F85892F6-25B4-41E1-96E9-DA4ECE744C62/myApp.app/myApp
  Expected in: /usr/lib/libSystem.B.dylib

If this is the only problem to make it work on iOS 6, then it would be good to have that fixed for the next beta of the SDK.

Maybe I have missed if it's stated somewhere that the Spotify SDK needs iOS 7 or better?

**Comment by iKenndac** [comment]
The SDK does indeed require iOS 7. We'll get a ticket to have the documentation updated.
