### ISSUE TITLE
Swapservice return format issues

### ISSUE THREAD

**Issue by paasan** [spotify/ios-sdk#205]
Hi guys!

So i just want you to know that the return format required from the swap service is really hard to find, and will not be flagged as an error by handleAuthCallbackWithTriggeredAuthURL if wrong.

Originally I used 
[[SPTAuth defaultInstance] loginURLForClientId:@kClientId
                         declaredRedirectURL:[NSURL URLWithString:@kCallbackURL]
                                      scopes:@[SPTAuthStreamingScope]];
[[SPTAuth defaultInstance] handleAuthCallbackWithTriggeredAuthURL:url
                                                tokenSwapServiceEndpointAtURL:[NSURL URLWithString:swapUrl]
                                                                     callback:authCallback];
and
[auth renewSession:session withServiceEndpointAtURL:[NSURL URLWithString:@kTokenRefreshServiceURL] callback:^(NSError *error, SPTSession *session){}]

The problem was that I got sessions back with no accessToken or encryptedRefreshTokens, the fields were blank. error was also nil in both cases, but because of the missing fields, the session was not valid.

What I ended up with doing was catching the callback url myself, call my swap service myself, and the init the session myself. Works great!

What would be much better was if handleAuthCallbackWithTriggeredAuthURL... and renewSession... triggered an error if the input format was wrong. Also a description somewhere on what exactly they expect would be great.

I user parse.com to hos the swap service as a cloud function, and they might have some headers or something that makes it harder, the body of my swap-service return was exactly like the example ruby service, and the service was called correctly.

**Comment by possan** [comment]
Yes, we need to document this more clearly.

`handleAuthCallbackWithTriggeredAuthURL` will send a `POST` request to the `/swap` endpoint with a post body of the type `application/x-www-form-urlencoded` with the field `code` containing the authorization code retrieved by the initial login call.

It expects the endpoint to return a JSON object containing a `access_token`, `refresh_token` and an `expires_in` field.

`renewSession` will send a `POST` request to the `/refresh` endpoint with a post body of the type `application/x-www-form-urlencoded` with the field `refresh_token` containing the (encrypted) refresh token returned by the `handleAuthCallbackWithTriggeredAuthURL` call.

It expects the endpoint to return a JSON object containing a `access_token` and an `expires_in` field.

For more information on the fields returned, see: https://developer.spotify.com/web-api/authorization-guide/

**Comment by paasan** [comment]
Well that is exactly what i get from my swapservice when i call it directly. I just parse the body string as Jon and get exactly those fields. Belive me, i have double checked :-)

There has to be something else, i could send you the URL to my service :-)

**Comment by possan** [comment]
Did you solve this?
