### ISSUE TITLE
User 'null' likes 'One Direction'

### ISSUE THREAD

**Issue by paasan** [spotify/ios-sdk#206]
If i create an STSession with a valid access token, encrypted refresh token, and a correct expiry date, BUT with nil as username, i get a lot of 'One direction'-stuff when i ask for my playlists :-) If i instead use the nameless session to ask for my user info, and then recreate the session with the username i get, it works and i get my own playlists.

What am I supposed to get first? The username to create a working session, or a session to get my username :-) A strange little issue.

Also it is a problem that i sudenly get someone elses playlists :-)

**Comment by iKenndac** [comment]
You need a valid username for most of the SDK to work. If you use `SPTAuth`'s `-handleAuthCallbackWithTriggeredAuthURL:…` method to deal with auth (which you should), it'll perform a request to get user info for you and create a proper, fully-formed session for you.

`nil` is transformed to `@"(null)"` by the runtime, and you're looking at the user `(null)`'s playlists. We should probably add a runtime check to make sure people are making valid sessions.

**Comment by paasan** [comment]
Yes, I currently have issues (#205) with 'handleAuthCallbackWithTriggeredAuthURL', but I hope eventually to use that instead :-)

**Comment by possan** [comment]
I'm closing this, re-open if this is still an issue.
