### ISSUE TITLE
SPTTrack availableTerritories Issue

### ISSUE THREAD

**Issue by martinobonfiglioli** [spotify/ios-sdk#209]
As guideline says, some tracks aren't playable in some countries and `AudioStreaming` delegate calls this method
```objectivec
-(void)audioStreaming:(SPTAudioStreamingController *)audioStreaming didFailToPlayTrack:(NSURL *)trackUri
```
So before playing a `SPTTrack` i want to know if that track is playable in user's country but `availableTerritories` seems doesn't work properly. Here some examples (testing from IT country):

**spotify:track:6x9fFNDkIAzRHQPWcU8g2H** has available territories “ES” and works
**spotify:track:2Vu3PpbpaBB5nAThPQstKL** has available territories “IT” and works
**spotify:track:0rFke7eNFHbGuGJUdRgjB2** has available territories “CA, US” and doesn’t work
**spotify:track:0lRS4GFAJVuIgXOgBxW5ik** has available territories empty and works

How can I know if a `SPTTrack` is playable?

**Comment by martinobonfiglioli** [comment]
Guys what's up?
Please answer me too.

**Comment by iKenndac** [comment]
At the moment, the only way to tell if a track is playable is to try to play it. When a track isn't available, the playback stack will try to find a similar version of the track that is available in the user's area. There's currently no way of invoking this lookup without actually trying to play.

**Comment by martinobonfiglioli** [comment]
Will you consider this as a bug?

**Comment by iKenndac** [comment]
Well, it's in the bug tracker and we didn't close it, so… yes. :)

**Comment by possan** [comment]
In the latest beta you can specify a market to the various functions for getting tracks, that will replace any unavailable track with an available equivalent (if it exists)

I'm closing this, re-open if this is still an issue.
