### ISSUE TITLE
Problem initiating a session 

### ISSUE THREAD

**Issue by truemetal** [spotify/ios-sdk#21]
Hey

I have this problem initiating a session, basically call to `SPTSessionManager.initiateSession` lands at `func sessionManager(manager: SPTSessionManager, didFailWith error: Error)` of `SPTSessionManagerDelegate`

This is the error I'm getting:

    Error Domain=com.spotify.sdk.login Code=1 "invalid_request" UserInfo={NSLocalizedDescription=invalid_request}

And this is the URL that's coming back from Spotify ios app at `func application(_ app: UIApplication, open url: URL, options: [UIApplicationOpenURLOptionsKey : Any] = [:]) -> Bool`:

    spotify-playground://spotify-login-callback/?code=AQAgOd0MvT01I_9Zu0a1xLimvZKZRN63d8NXugRRkbxfmFQnGaYvS7V0kUAnWU9-0Aqe0HhJeSYa1P01by1DBEnZS9drE7Dc7UrniGxBmCstiYlZvKqdwRn4c6RKj92wY2ZTv8cm9sk-AibLM8RcYidMkoFosNPEptpKNGARJdyAYTHQqOLaSFn-5V2OSKFrARCqmYy3qSgPItad1mIMRPKv1pIUTxDONGkw6-KQQgvHKknrxioaWoG9w29ifHRT7Q3Ne25tkG9AP18DdqZ0iXl_vHo325A0i6K8vx10ScFG

Any ideas?
Cheers

**Comment by jackfreeman** [comment]
@truemetal You will have to exchange that code with your own backend servers that contain your client-secret. Then your servers will make an exchange with the Spotify servers before returning an OAuth token to your app. You can find more info from the [Token Swap & Refresh Guide](https://developer.spotify.com/documentation/ios/guides/token-swap-and-refresh/) as well as a detailed overview in the [Authorization Guide](https://developer.spotify.com/documentation/general/guides/authorization-guide/)

Be sure to set [these two properties](https://github.com/spotify/ios-sdk/blob/master/DemoProjects/SPTLoginSampleApp/SPTLoginSampleApp/ViewController.m#L24-L25) on `SPTConfiguration` to your own server. There's an example ruby script provided with the demo projects as well as [instructions](https://github.com/spotify/ios-sdk/tree/master/DemoProjects#how-to-use-the-provided-ruby-script) on how to use it for testing too.

**Comment by truemetal** [comment]
Right, for some reason I've assumed token swapping is an optional step (at least for development).
Works with both local ruby script and Heroku apps you've provided. 

Thanks
