### ISSUE TITLE
Crash in [SPTPlaylistSnapshot playlistWithURI: session: callback: ]

### ISSUE THREAD

**Issue by martinobonfiglioli** [spotify/ios-sdk#210]
**Internal method that causes this crash:**

-[SPTPlaylistSnapshot initWithDecodedJSONObject:error:] at /Users/spotify-buildagent/buildAgent/work/f0512cb09316daec/src/SPTPlaylistSnapshot.m:146

**Console Log:**

-[NSNull longValue]: unrecognized selector sent to instance

**Comment by possan** [comment]
I can't reproduce it, do you have the uri to the playlist that you're trying to load?

**Comment by martinobonfiglioli** [comment]
Nope, it happened one time during loading all my playlists.
BTW hope my detailed debug description can help.

**Comment by possan** [comment]
We just sent out a new version, which should fix this issue, it would be great if you could confirm that it's fixed.

**Comment by possan** [comment]
I'm closing this, re-open if this is still an issue.
