### ISSUE TITLE
Spotify not Authorizing Users in my app anymore

### ISSUE THREAD

**Issue by ehinerdeer** [spotify/ios-sdk#213]
I have an app I was testing out to see if I can get recently played songs from a user and their profile information. For about two weeks this was working wonderfully and my app was updating with all the songs the users I was testing it out on. I have been getting working access tokens and using the refresh tokens as the docs have stated. This morning I went to use my app on my own account and it keeps saying "401 Unauthorized". I tried to manually re-authenticate my token and that is also coming up "401 Unauthorized". It is almost like Spotify has blocked my id from getting access tokens? I haven't changed any of my code for the process and, as stated, it was working on Friday and now this morning not working at all. Could this be a rate limit thing for a personal app? Or a bug in the auth process? I am really lost and any help would be greatly appreciated. I am using IOS sdk for authorizing and Java Spring for the recently played calls. Thanks.

**Comment by deepam1212** [comment]
any update on this, i am getting this error, as my app is working fine till last week and now the app is not getting authorized to spotify

**Comment by deepam1212** [comment]
it resolved, i havenot changes my bundle id on Spotify on Store

**Comment by ehinerdeer** [comment]
Thanks for the update. Mine was resolved when I realized Someone changed our refresh token process and it was no longer refreshing old tokens correctly.
