### ISSUE TITLE
Shuffle doesn't work

### ISSUE THREAD

**Issue by pconno** [spotify/ios-sdk#213]
Shuffle doesn't appear to consistently work. It appears to sometimes work for my own playlist but to never work for curated playlists. 

            [self.player setShuffle:YES];
            [self.player playTrackProvider:self.track
                                      callback:^(NSError *error3) {
                                          [self.playerDelegate songStarted];
                                          [self updateCurrentlyPlayingSong];
                                      }];

If I set a breakpoint in the callback, I can see that shuffle is true for the player but it doesn't actually shuffle.

**Comment by possan** [comment]
Yes, there seems to be an issue with the shuffle, a workaround that seems to work is this; setting shuffle and restarting playback within the callback:

```
[self.player playTrackProvider:trackprovider callback:^(NSError *error) {
  self.player.shuffle = YES;
  [self.player setIsPlaying:YES callback:nil];
}];
```

**Comment by stocknell2000** [comment]
It also always has the same first song, with or without shuffle. Is this how it's meant to be?

**Comment by pconno** [comment]
This seems to fix part of the bug. The function works to enable shuffle. If I then start a new playback and try to disable shuffle then it continues to shuffle. When I put in a breakpoint then the playlist does not shuffle. Additionally if I then call in this function a third time, the player does not shuffle (as expected).

**Comment by possan** [comment]
Closing this since it's so old, it seems like this is no longer the problem with the recent versions.
