### ISSUE TITLE
supportsApplicationAuthentication is always returning NO

### ISSUE THREAD

**Issue by seankellycs** [spotify/ios-sdk#215]
I had a question about how supportsApplicationAuthentication. 

I only want to be able to authenticate users if they have the Spotify application installed on the device and can do the 'flip-flop' style of user authentication between apps. I have been successfully authenticating by jumping out to Safari, however the SPTAuth method 'supportsApplicationAuthentication' is always returning NO, indicating that 'flip-flop' type of authentication is not possible. The Spotify application on the device is the most updated version. Any ideas on how to get this to work with the beta 6 SDK?

**Comment by iKenndac** [comment]
This is correct behaviour at the moment - the client doesn't support flip-flop auth just yet. When it does, as long as you're using `SPTAuth` it'll just start working - you don't need to do anything special for it.

**Comment by iKenndac** [comment]
I really with they'd put the "Close and comment" button somewhere else. Closed by mistake.

**Comment by seankellycs** [comment]
I see, thanks for the info. Looking forward to having application authentication supported.
