### ISSUE TITLE
Login via Facebook is redirecting to a spotify logout page instead of my app

### ISSUE THREAD

**Issue by pkotesh-systango** [spotify/ios-sdk#216]
Hi, 

I am facing this issue from past 4 hours. When I login through Facebook, the login screen is redirected to a page on safari which says "You are logged in as Username" and gives me a logout button, instead of redirecting it to my application. Can you please look into it? Thank you

**Comment by mhabegger** [comment]
Same here. Started happening this morning around 9 CET. Until then it was working properly.

**Comment by billgert** [comment]
Same problem here

**Comment by whittlbc** [comment]
Same

**Comment by kennylovrin** [comment]
Is it possible to get some info on wether this will require a SDK update, or if it is just a temporary bug in the login flow?

**Comment by iKenndac** [comment]
> Is it possible to get some info on whether this will require a SDK update, or if it is just a temporary bug in the login flow?

I would suggest that if it broke without an SDK update, it will be fixed without one too.

**Comment by possan** [comment]
Is this still valid?

**Comment by pkotesh-systango** [comment]
Yes. The logout screen appears once in a while. Not only with Facebook Login but with spotify login as well.

**Comment by possan** [comment]
We had some intermittent Facebook login issues recently, this should now be fixed.

**Comment by pkotesh-systango** [comment]
Yep. Didn't see it in the recent past.

**Comment by possan** [comment]
Great, i'll close this.
