### ISSUE TITLE
IOS SDK6, playback feature bugs ?

### ISSUE THREAD

**Issue by captain-tarace** [spotify/ios-sdk#217]
Hi, I've developped an app using Spotify SDK beta6.
I'm using iOS SDK6 and iOS8, iPhone6, 6+.

I've successfully did those 3 things.

1: Login and Renewing Session
2: Receive some URIs from Spotify server
3: playing music with SPTAudioStreamingController.playURIs or queueURIs

However, we have some problem with following issues:

1: SPTAudioStreamingController.skipNext works, but skipPrevious never works and never returns error.
2: queueURIs's clear flag, never clear current queued URIs, and we can't remove data that is added to queue once.

Are there any known issue or are they unimplemented feature yet?

Thanks!

**Comment by jackcook** [comment]
I'm having the same issue with skipPrevious, if someone could look into this that would be great :)

**Comment by captain-tarace** [comment]
Yop folks, I have the answer...

The queue is modeling the queue in the Spotify application itself. If you add things to your queue in the mobile client, you can't skip backwards; adding things to the queue that way is ephemeral. In order for skipping backwards to work, you need to have a play context.

So I would describe the behavior seeing as expected. The confusion comes from the definition of the word "queue". It isn't what you think it is.

In order to get the behavior they want, you should probably be using the playURIs function,

https://developer.spotify.com/ios-sdk-docs/Documents/Classes/SPTAudioStreamingController.html#//api/name/playURIs:fromIndex:callback:

It's my understanding that this function creates a new context, which you can then skip forward and backward within. My call to this function (in Swift) looks like this,

self.player.playURIs(toPlay, fromIndex: 0, callback: nil)

...where toPlay is an array of NSURL objects.

I can then call skipPrevious(nil) and skipNext(nil) on the player, and I think they'll have the behavior they want.

**Comment by thegreatmichael** [comment]
@captain-tarace or @iKenndac or others, if i do as suggested above (playURI on a list of NSURLs), what if i later want to add one into the middle? would i call playURIs again with the same list, with whatever insertion i need, and then make the fromIndex some value to do the right thing?

**Comment by iKenndac** [comment]
In this case, at the moment it's probably best to maintain the queue yourself, and only ever play one track at a time. When the track finishes, figure out the next track in your own code and play it.

**Comment by thegreatmichael** [comment]
sorry @iKenndac, thanks for the clarification, if I do as you say, would i just never call skipPrevious, and instead handle it in my own code?

**Comment by iKenndac** [comment]
Good point. I mean, with your original suggestion of repeating `playURIs` calls when your queue changes you'll smash into the current playback, so you'll need to time it so it only happens when a track finishes playing. 

If you do only one track at a time you will indeed lose all playback controls except volume, seeking and play/pause. If you need a fully-fledged mutable queue system that allows skip back, you will indeed need to manage it yourself at the moment.

**Comment by thegreatmichael** [comment]
ok, thanks again, i think that for my purposes, if i am modifying the queue, it would be in response to a user ixn where they would expect the track to change anyway, so for my case i might be able to get away with it, but i'll keep the second option in mind as well (and really, to do the first one, i anyway have to keep the queue myself, so the only reason to do the first, is if there's some performance benefit to using playuri with skipnext and prev vs my own skip functions...)

**Comment by possan** [comment]
I'm closing this, please re-open if this is still an issue.

**Comment by Navideck-fotis** [comment]
Now that queue is deprecated, we need a way to append URIs at the playURIs call.
