### ISSUE TITLE
Wronk format for SPTUser displayName

### ISSUE THREAD

**Issue by Kry256** [spotify/ios-sdk#218]
I try to retrieve current **SPTUser** infos using
``+(void)userInformationForUserInSession:(SPTSession *)session callback:(SPTRequestCallback)block``
I noticed that the display name of the returned **SPTUser** object is empty and that may be obviously correct.
The issue is that, instead to be a ***nil*** value or an ***empty string***, the value is **< null>**. As to say a string that contains the characters **< null >** .
Is this to be considered as a bug, or I must consider these cases and eventually use __canonicalUserName__ for UI display pourposes?

**Comment by loretoparisi** [comment]
I have found that for those users, the WebAPI response returns this <null> value:

```
{
  "country" : "IT",
  "display_name" : null,
  "email" : "xxxx@xxxx.com",
  "external_urls" : {
    "spotify" : "https://open.spotify.com/userxxxx"
  },
  "followers" : {
    "href" : null,
    "total" : 0
  },
  "href" : "https://api.spotify.com/v1/users/xxxxx",
  "id" : "streamtestmxm",
  "images" : [ ],
  "product" : "premium",
  "type" : "user",
  "uri" : "spotify:user:xxxxxx"
}
```

**Comment by iKenndac** [comment]
It's a bug. Also, make sure you're using the `SPTAuthUserReadPrivateScope` scope to get the full name of the logged-in user.
