### ISSUE TITLE
SPTPlaylistSnapshot playlistWithURI crashes with certain playlists

### ISSUE THREAD

**Issue by Anders27** [spotify/ios-sdk#219]
This is exactly the same problem as:

https://github.com/spotify/ios-sdk/issues/132

[SPTPlaylistSnapshot playlistWithURI:partial.uri session:self.session callback:^(NSError *error, id object)

crashes with the following playlist:
spotify:user:b271478:playlist:6p14MY8c5bsIzoIAaPQzGD

it's a public playlist so it should be easy to check the problem

Actually it also crashes the sample app:

#if 1
NSString *uri = @"spotify:user:b271478:playlist:6p14MY8c5bsIzoIAaPQzGD";
#else
NSString *uri = @"spotify:album:4L1HDyfdGIkACuygktO7T7";
![screen shot 2015-01-22 at 13 51 12](https://cloud.githubusercontent.com/assets/10338608/5855999/1e2c54f8-a23f-11e4-8a60-7c68503d350b.png)

#endif
      [SPTRequest requestItemAtURI:[NSURL URLWithString:uri]
                         withSession:session
                            callback:^(NSError *error, id object)

**Comment by Anders27** [comment]
Here is the crash log, thread 16 crashes, thread 17 is  a thread that doesn't crash.

Thread 16 name:  Dispatch queue: com.apple.root.default-qos
Thread 16 Crashed:
0   libsystem_kernel.dylib        0x00000001946cb270 __pthread_kill + 8
1   libsystem_pthread.dylib       0x0000000194769224 pthread_kill + 108
2   libsystem_c.dylib             0x0000000194642b14 abort + 108
3   libc++abi.dylib               0x0000000193715414 abort_message + 112
4   libc++abi.dylib               0x0000000193734b88 default_terminate_handler() + 300
5   libobjc.A.dylib               0x0000000193f443bc _objc_terminate() + 124
6   libc++abi.dylib               0x0000000193731bb0 std::__terminate(void (*)()) + 12
7   libc++abi.dylib               0x0000000193731474 __cxa_throw + 132
8   libobjc.A.dylib               0x0000000193f44200 objc_exception_throw + 344
9   CoreFoundation                0x00000001837f5660 -[NSObject(NSObject) doesNotRecognizeSelector:] + 216
10  CoreFoundation                0x00000001837f2414 ___forwarding___ + 924
11  CoreFoundation                0x00000001836f6b68 _CF_forwarding_prep_0 + 88
12  app                           0x0000000100199d20 -[SPTPartialTrack initWithDecodedJSONObject:error:] (SPTPartialTrack.m:67)
13  app                           0x0000000100197d94 -[SPTTrack initWithDecodedJSONObject:error:] (SPTTrack.m:76)
14  app                           0x000000010019616c -[SPTPlaylistTrack initWithDecodedJSONObject:error:] (SPTPlaylistTrack.m:44)
15  app                           0x00000001001b36e4 +[SPTJSONDecoding SPObjectFromDecodedJSON:collection:error:] (SPTJSONDecoding.m:96)
16  app                           0x00000001001a2980 -[SPTListPage initWithDecodedJSONObject:expectingPartialChildren:rootObjectKey:] (SPTListPage.m:84)
17  app                           0x000000010019c490 -[SPTPlaylistSnapshot initWithDecodedJSONObject:error:] (SPTPlaylistSnapshot.m:133)
18  app                           0x00000001001b36e4 +[SPTJSONDecoding SPObjectFromDecodedJSON:collection:error:] (SPTJSONDecoding.m:96)
19  app                           0x00000001001ad510 __56+[SPTRequest requestPlaylistAtURI:withSession:callback:]_block_invoke (SPTRequest.m:613)
20  libdispatch.dylib             0x00000001945893a8 _dispatch_call_block_and_release + 20
21  libdispatch.dylib             0x0000000194589368 _dispatch_client_callout + 12
22  libdispatch.dylib             0x0000000194595408 _dispatch_root_queue_drain + 1148
23  libdispatch.dylib             0x0000000194596758 _dispatch_worker_thread3 + 104
24  libsystem_pthread.dylib       0x00000001947652e0 _pthread_wqthread + 812
25  libsystem_pthread.dylib       0x0000000194764fa4 start_wqthread + 0

Thread 17 name:  Dispatch queue: com.apple.root.default-qos
Thread 17:
0   libsystem_kernel.dylib        0x00000001946cb0c0 __psynch_mutexwait + 8
1   libsystem_pthread.dylib       0x0000000194765548 _pthread_mutex_lock + 416
2   libicucore.A.dylib            0x0000000193961598 0x1938dc000 + 546200
3   libicucore.A.dylib            0x000000019395f7b8 0x1938dc000 + 538552
4   libicucore.A.dylib            0x000000019396078c ures_getByKeyWithFallback + 464
5   libicucore.A.dylib            0x00000001939e25c0 0x1938dc000 + 1074624
6   libicucore.A.dylib            0x00000001939cc978 icu::DateFormatSymbols::initializeData(icu::Locale const&, char const*, UErrorCode&, signed char) + 5252
7   libicucore.A.dylib            0x00000001939cd2e4 icu::DateFormatSymbols::DateFormatSymbols(icu::Locale const&, char const*, UErrorCode&) + 100
8   libicucore.A.dylib            0x0000000193a30a3c icu::SimpleDateFormat::initializeSymbols(icu::Locale const&, icu::Calendar*, UErrorCode&) + 132
9   libicucore.A.dylib            0x0000000193a303e0 icu::SimpleDateFormat::construct(icu::DateFormat::EStyle, icu::DateFormat::EStyle, icu::Locale const&, UErrorCode&) + 276
10  libicucore.A.dylib            0x0000000193a317ec icu::SimpleDateFormat::SimpleDateFormat(icu::DateFormat::EStyle, icu::DateFormat::EStyle, icu::Locale const&, UErrorCode&) + 176
11  libicucore.A.dylib            0x00000001939b1b70 icu::DateFormat::create(icu::DateFormat::EStyle, icu::DateFormat::EStyle, icu::Locale const&) + 152
12  libicucore.A.dylib            0x0000000193a5d850 udat_open + 304
13  CoreFoundation                0x00000001837d9914 __cficu_udat_open + 64
14  CoreFoundation                0x00000001837878fc __ResetUDateFormat + 416
15  CoreFoundation                0x000000018372fcc8 CFDateFormatterCreate + 296
16  Foundation                    0x0000000184617520 -[NSDateFormatter _regenerateFormatter] + 292
17  Foundation                    0x000000018472e8a8 getObjectValue + 148
18  Foundation                    0x000000018472e7d4 -[NSDateFormatter getObjectValue:forString:errorDescription:] + 196
19  Foundation                    0x000000018472eb60 -[NSDateFormatter dateFromString:] + 48
20  app                           0x0000000100196288 -[SPTPlaylistTrack initWithDecodedJSONObject:error:] (SPTPlaylistTrack.m:51)
21  app                           0x00000001001b36e4 +[SPTJSONDecoding SPObjectFromDecodedJSON:collection:error:] (SPTJSONDecoding.m:96)
22  app                           0x00000001001a2980 -[SPTListPage initWithDecodedJSONObject:expectingPartialChildren:rootObjectKey:] (SPTListPage.m:84)
23  app                           0x000000010019c490 -[SPTPlaylistSnapshot initWithDecodedJSONObject:error:] (SPTPlaylistSnapshot.m:133)
24  app                           0x00000001001b36e4 +[SPTJSONDecoding SPObjectFromDecodedJSON:collection:error:] (SPTJSONDecoding.m:96)
25  app                           0x00000001001ad510 __56+[SPTRequest requestPlaylistAtURI:withSession:callback:]_block_invoke (SPTRequest.m:613)
26  libdispatch.dylib             0x00000001945893a8 _dispatch_call_block_and_release + 20
27  libdispatch.dylib             0x0000000194589368 _dispatch_client_callout + 12
28  libdispatch.dylib             0x0000000194595408 _dispatch_root_queue_drain + 1148
29  libdispatch.dylib             0x0000000194596758 _dispatch_worker_thread3 + 104
30  libsystem_pthread.dylib       0x00000001947652e0 _pthread_wqthread + 812
31  libsystem_pthread.dylib       0x0000000194764fa4 start_wqthread + 0

**Comment by possan** [comment]
Closing this, this should be fixed now in the latest release.
