### ISSUE TITLE
No API for following other users playlists

### ISSUE THREAD

**Issue by ericlewis** [spotify/ios-sdk#22]
Doesn't seem to be a way to follow another users playlist- you have to pull the tracks and create a new one.

**Comment by possan** [comment]
Closing this, this is now supported in the latest release.

**Comment by ronakvora** [comment]
This seems to not work.

NSURLRequest *followReq =
      [SPTPlaylistSnapshot createRequestForPlaylistWithURI:[NSURL URLWithString:<playlist_uri_string>]
                                               accessToken:session.accessToken
                                                     error:nil];
      
      [[SPTRequest sharedHandler] performRequest:followReq callback:^(NSError *error, NSURLResponse *response, NSData *data) {
        if (error) {
          NSLog(@"Notify user of failure: %@", error);
        }
        else {
          NSLog(@"Notify user of success");
        }
      }];


I get the callback with the error as nil, but when I look on my Spotify account, the playlist hasn't been followed.
