### ISSUE TITLE
Is there an SDK for macOS?

### ISSUE THREAD

**Issue by Peter-Schorn** [spotify/ios-sdk#221]
I'm sure this isn't the right place to post this, but I don't know where the right place is. I would like to build a **macOS** notification center widget to control playback. **Is there an SDK for macOS?**
Would I have to use the web API? The one issue with this is that I would like to be able to detect when a user has skipped to a new song without running an infinite loop that perpetually retrieves the currently playing song.

**Comment by eedvardsson** [comment]
There's no macOS SDK, the web API is the way to go.

**Comment by marcinwlodarczyk** [comment]
@eedvardsson are there any plans to support Catalyst?

**Comment by jholowesko** [comment]
@eedvardsson I'd also love to implement this on a Catalyst app ^

**Comment by kkarayannis** [comment]
Hi!
Like I mentioned in #231, there are no plans to support Mac Catalyst at this time.

**Comment by Peter-Schorn** [comment]
@kkarayannis But is there a way to detect if the user has changed songs using the web API without running an infinite loop?

**Comment by technomorph** [comment]
Spotify Desktop broadcasts DistributedNotifications....   you just need to register as an observer of these notifications and then then use the userInfo Dict to get info you need.   Or if you you need to “reask” the app for info you can use AppleScript.
