### ISSUE TITLE
Enhancement - File API

### ISSUE THREAD

**Issue by Anders27** [spotify/ios-sdk#221]
For certain apps it would be very useful with a file API similar to Mac/iOS “Extended Audio File”.

The most needed stuff would be (I’m using ExtAudioFile names for simplicity):

SPTAudioFileLogin();
SPTAudioFileLogout();

SPTAudioFileOpenURL();
SPTAudioFileClose();

SPTAudioFileSetProperty(kExtAudioFileProperty_ClientDataFormat_ONLY_PCM_Nedded);

SPTAudioFileGetProperty(kExtAudioFileProperty_FileLengthFrames);

SPTAudioFileSeek(seekPosistion);
SPTAudioFileRead(framesToRead);

That’s about all needed.

Regular file APIs are synchronous and as closely to that would be preferable, possibly with some kind of “time out” value but asynchronous with a completion block would be better than nothing.

**Comment by iKenndac** [comment]
This would be a wrapper for API consumers such as yourself to write. `SPTAudioStreaming` is a public exposure of a pattern that goes through the entire stack, and uses a push-based way of giving you audio. `SPTCoreAudioController` then wraps this and implements a Core Audio AUGraph, using circular buffers to convert the streaming's push-based approach to Core Audio's required pull-based approach.

You could easily subclass `SPTCoreAudioController`, override `-attemptToDeliverAudioFrames:ofCount:streamDescription:audioDescription` to get the raw data then implement whatever API pattern you like on top of it.
