### ISSUE TITLE
Audio playback stuttering

### ISSUE THREAD

**Issue by johra** [spotify/ios-sdk#223]
Every 10 second or so there is a small pop in playback, regardless of which track

* Does not make a difference if SPTBitrate is set to low or high.
* Have tried on different connections with very low latency.
* Same track with the regular Spotify client works fine.

Edit: This occurs on an iPad 2 but NOT on an iPhone 5

**Comment by possan** [comment]
I suspect this is related to some cpu usage spikes in the disk cache, have you enabled that?

**Comment by burkaygur** [comment]
I have exactly the same issue. I get spikes in the CPU every 10 seconds. What is the solution?

**Comment by burkaygur** [comment]
I have resolved this issue by deleting my app and reinstalling it. I have then set the maximum disk cache size to 5MB. Hopefully I won't have the same issue again. 

What is a good size to set the max cache to? And would that be a permanent solution?

**Comment by possan** [comment]
Closing this since it's so old, it seems like this is no longer the problem with the recent versions.
