### ISSUE TITLE
Can't check if track is starred without loading entire starred playlist.

### ISSUE THREAD

**Issue by mhuusko5** [spotify/ios-sdk#226]
It's extremely common to need to show whether a user has starred a track, but with the current API the only way to do that is pull down their entire starred playlist (potentially thousands of tracks) and check if it contains the track.

It would be extremely valuable to have a call which accepts a track or set of tracks and a valid session, and returns whether the current user has starred them.

**Comment by possan** [comment]
Starred is not officially supported so adding such functionality will not happen.
