### ISSUE TITLE
Can't search for multiple resource types in one request (can with Web API).

### ISSUE THREAD

**Issue by mhuusko5** [spotify/ios-sdk#228]
Just want to make sure that the ability to search for multiple resource types (album, tracks, artists, playlist) simultaneously will make it's way from the Web API to the iOS SDK in a subsequent version.

**Comment by Navideck-fotis** [comment]
+1

**Comment by mhuusko5** [comment]
Bump. This seems like high priority given the level of utility, and that its already in the web api.

I guess would be good to know if there's at least a plan to integrate this, or if I need to create a more permanent work around?

**Comment by erdtman** [comment]
We are deprecating the iOS-Metadata library.

The source code of the iOS-Metadata library has been released and can be found [here](https://github.com/erdtman/spotify-ios-metadata/). Spotify will not continue to maintain the released source code.

Either you can select to use the web-api directly or use the new open source iOS-Metadata library.

I will close this issue now.

We are sorry for the inconvenience that this creates, but looking back we think this is the best path forward.
