### ISSUE TITLE
Playing previews without Spotify account?

### ISSUE THREAD

**Issue by ralfr** [spotify/ios-sdk#230]
The Web API offers to play 30s previews without any need for the user to log into Spotify ([Example](http://artistexplorer.spotify.com)).

Is this support from the iOS SDK, too?

If not, does the lower level C-SDK support this? Or is there no way of doing this natively / on a mobile? (The Web API's playback does not work on Mobile Safari.)

**Comment by iKenndac** [comment]
Yes, it does. Please see the `previewURL` property on `SPTrack` and `SPTPartialTrack`.

**Comment by ralfr** [comment]
Thanks for your speedy response, @iKenndac.

I'm still struggling. Assume I've got the following reduced code from one of the great samples you provide:

```
    // Create a new player if needed
    if (self.player == nil) {
        self.player = [[SPTAudioStreamingController alloc] initWithClientId:kClientId];
    }
    
    
    [SPTRequest requestItemAtURI:[NSURL URLWithString:@"spotify:album:4L1HDyfdGIkACuygktO7T7"]
                withSession:nil
                callback:^(NSError *error, SPTAlbum *album) {
                                
                if (error != nil) {
                    NSLog(@"*** Album lookup got error %@", error);
                    return;
                }
                [self.player playTrackProvider:album callback:nil];
    }];
```
If all I want is to play the 30s preview of a specific song right away, how would I have to change the code? Having a problem to understand how I create an `STPPartialTrack` and hand it over to the player.

**Comment by ralfr** [comment]
One more remark: If playback-able objects have to be created via `SPTRequest` it would be a problem for my use case, as `STPRequest` seems to always require a session and hence the user to be logged in.

**Comment by iKenndac** [comment]
You don't use the `SPTAudioStreaming` class to play previews, since `SPTAudioStreaming` requires a logged-in Premium user. As documented, `previewURL` is a HTTP link to an MP3, so you can use `AVAudioPlayer` or similar to play it. 

`SPTRequest` can take a `nil` session for requests that don't require a logged-in user. This is also in the documentation.

**Comment by ralfr** [comment]
Thanks again. That makes it clear. All that's left is how do we get the preview URL? It's still somewhat unclear how we get the `SPTPartialTrack` Object in order to read the read-only `previewURL` property and the address to ship the thank-you chocolate to.

**Comment by ralfr** [comment]
Found it. It's as simple as a GET request to 'https://developer.spotify.com/web-api/get-track/'.

**Comment by iKenndac** [comment]
`[SPTRequest requestItemAtURI:<uri> withSession:nil callback:^(NSError *error, SPTTrack *track) {
    /// Now you have a track
];`

*Please* read the documentation. Everything is there.

**Comment by gmaijoe** [comment]
we can download the preview and use it in any way right? obviously i'll give spotify credit as such.

**Comment by iKenndac** [comment]
@gmaijoe No, you can't. Use of the Spotify SDK is bound by the [Terms of Use](https://developer.spotify.com/developer-terms-of-use/), which contains several restrictions on the use of Audio Preview Clips.

**Comment by andresmontelpare** [comment]
is still possible to get a song preview without having to log in?
In documentation, the token parameter is defined as optional, but i am getting: 
"Error Domain=kCFErrorDomainCFNetwork Code=-1012 "(null)" UserInfo={_kCFURLErrorAuthFailedResponseKey"

Thanks in advance,
Andrés

**Comment by alexmorel** [comment]
Hi everyone, I'm struggling too with this.
The advices in this issue are no longer possible as requestItemAtURI has been deleted in the newest SDK version

Without being logged, 
`SPTTrack .track(withURI: URL(string:"spotify:track:58s6EuEYJdlb0kO7awm3Vp"), accessToken: nil, market: nil) { (error, track) in {`

fails with a error with  "The operation failed due to an unspecified issue."

Is there any way to get the preview url without being logged ?

**Comment by alexmorel** [comment]
FYI doing a basic GET request to https://api.spotify.com/v1/tracks/<TRAKC_ID> returns a no token provided error

`  "error" : {
    "status" : 401,
    "message" : "No token provided"
  }`

`var request: URLRequest = try! SPTRequest.createRequest(for: URL(string:"https://api.spotify.com/v1/tracks/58s6EuEYJdlb0kO7awm3Vp"), withAccessToken: nil, httpMethod: "GET", values: nil, valueBodyIsJSON: true, sendDataAsQueryString: true);

NSURLConnection.sendAsynchronousRequest(request, queue: OperationQueue(),
                                                
                                                completionHandler:{ (response:URLResponse!, data: Data!, error: Error!) -> Void in
                                                    NSLog(data.toString());
        }
        );
`

**Comment by hughrawlinson** [comment]
Hey @alexmorel - the API has changed since this issue - we now no longer support unauthenticated requests to the API. This was [announced in January 2017](https://developer.spotify.com/news-stories/2017/01/27/removing-unauthenticated-calls-to-the-web-api/).

**Comment by alexmorel** [comment]
Thanks for your reply ! Wow this is a bummer, I would have loved to use your SDK :(
Maybe for another app ;)
Congrats for your work and BTW I'm fond of Spotify and use it everyday
