### ISSUE TITLE
Renew access token in background

### ISSUE THREAD

**Issue by ahallora** [spotify/ios-sdk#232]
Hi fellow iOS developers,

I'm having trouble renewing the spotify token while the app is playing as a background task (the phone screen is off and the music is playing). When the token needs to be renewed the music stops and I have to unlock the phone and bring up the app before the token is renewed and playback resumes. There must be another way...

How do you guys go about this? :)

(I'm unsure if this is the right place for this question; since the ios sdk is still in beta I deemed github more fit than stackoverflow... I apologize if I'm wrong in my assesment.) :smile:

**Comment by ahallora** [comment]
Somehow I got it working... by not actually changing the code. Don't know what I did, but it works now. :) Closing the issue. :+1:

**Comment by gbrickley** [comment]
@ahallora care to share how you were able to get this to work?

**Comment by ahallora** [comment]
I'm still very new to coding in objective-C, so I hack away until all syntax errors are gone and then prey to God that it's working... 
![Image of no-idea-dog](http://www.spacegamejunkie.com/wp-content/uploads/2014/07/i-have-no-idea-what-im-doing-dog.jpg)

I think perhaps it was working out of the box, but my noob-code somehow managed to mess it up. I use the example provided by Spotify:
https://github.com/spotify/ios-sdk/tree/master/Demo%20Projects/Simple%20Track%20Playback/Simple%20Track%20Playback

Good luck... :)

**Comment by kennylovrin** [comment]
A simple way that works could be to just check how many seconds until the token expires whenever it makes sense (like after logging in, when app becomes active etc) and start a timer with that delay to run a refresh call. Subtract a bit on the expiry for some margin, like 30 secs or so.

**Comment by gbrickley** [comment]
@kennylovrin I was thinking the same thing.  Can you renew an access token before it expires?  Do you know of any easy way to simulate a token expiring other than waiting a day to test your code?  Can you set the expirationDate property manually?

**Comment by kennylovrin** [comment]
You can refresh it whenever you want, but I don't know if you can fake expiry (other than refreshing after any delay).

**Comment by cjwhitsitt** [comment]
For anyone seeing this, you can fake an early expiration with a proxy or by modifying the response from your token swap or refresh endpoint. The endpoint sends back `expires_in` which is life time in seconds. Modifying that value will cause `session.isValid` to return `NO` after the given amount of seconds has passed.

I use https://www.charlesproxy.com/ as a proxy to do this.
