### ISSUE TITLE
Authentication Error

### ISSUE THREAD

**Issue by swifferina** [spotify/ios-sdk#233]
Hi, after callback after the authentication I received the following error:

*** Auth error: Error Domain=NSCocoaErrorDomain Code=3840 "The operation couldn’t be completed. (Cocoa error 3840.)" (JSON text did not start with array or object and option to allow fragments not set.) UserInfo=0x1708651c0 {NSDebugDescription=JSON text did not start with array or object and option to allow fragments not set.}

I 'm running the token swap at https://whispering-beyond-6523.herokuapp.com

**Comment by oroom** [comment]
I have the same problem with SDK

**Comment by possan** [comment]
Did you solve this issue? is sounds like an issue with the response body from the token swap service...

**Comment by swifferina** [comment]
no....I haven't solved it......do you know how can I avoid it?

**Comment by steve-whitney** [comment]
same here.  Just started happening today to a stable dev-app that's been working for weeks.


error=Error Domain=NSCocoaErrorDomain Code=3840 "The operation couldn’t be completed. (Cocoa error 3840.)" (JSON text did not start with array or object and option to allow fragments not set.) UserInfo=0x7fdcbb8c4530 {NSDebugDescription=JSON text did not start with array or object and option to allow fragments not set.}

**Comment by steve-whitney** [comment]
My mistake -- my token-swap server was hosed, all ok now.
