### ISSUE TITLE
SPTPartialArtist playableUri is nil

### ISSUE THREAD

**Issue by Navideck-fotis** [spotify/ios-sdk#234]
I am calling
[SPTRequest performSearchWithQuery:[searchBar text] queryType:SPTQueryTypeArtist session:_session callback:^(NSError *error, SPTListPage *listPage)

and the playableUri is nil for every artist

**Comment by hannesjung** [comment]
I'm experiencing the same issue with
    [SPTRequest performSearchWithQuery:searchText queryType:SPTQueryTypeArtist session:playback.spotifySession callback:^(NSError *error, id object)

I also tried requesting the full album but without success. Please help!

**Comment by iKenndac** [comment]
This is expected - passing the object to `SPTAudioStreamingController`'s `playTrackProvider:` methods will still work. We'll update the documentation to state that it's fine and expected for this to be `nil` in some situations.

**Comment by iKenndac** [comment]
This is also discussed here: #200
