### ISSUE TITLE
REopen: Collaborative playlists bug #180?

### ISSUE THREAD

**Issue by thegreatmichael** [spotify/ios-sdk#235]
Would it be possible to leave the issue about getting collaborative playlists open until there is a resolution? I mean, is it a wontfix? Or is it just that it's not a priority or not sure what to do yet? To not return the collab lists in a search, weould be acceptable for me, but for an authenticated user not to be able to see their collab lists is pretty bad for my use case. Even if my app did not have permission to modify a collab playlist, this would be a major improvement. Thanks for any further discussion.

**Comment by possan** [comment]
The problem currently is that all collaborative playlist is editable by anyone, there's no ACL controlling whom has access to it, as long as you have the URI to it you can do anything, exposing them in search or the playlist listing of another user would be a very bad thing, eventually we'd like to have greater control over the access to playlists but that's currently not the case..

**Comment by thegreatmichael** [comment]
@possan sorry for my confusion, but one last question: is it even a problem to list the playlist for the user themselves? `SPTRequest.playlistsForUserInSession` ?

**Comment by NathanWalker** [comment]
Curious on this as well. Any updates? Can you fetch a list of `collaborative` playlists?

**Comment by martinobonfiglioli** [comment]
Check this out #484

**Comment by erdtman** [comment]
We are deprecating the iOS-Metadata library.

The source code of the iOS-Metadata library has been released and can be found [here](https://github.com/erdtman/spotify-ios-metadata/). Spotify will not continue to maintain the released source code.

Either you can select to use the web-api directly or use the new open source iOS-Metadata library.

I will close this issue now.

We are sorry for the inconvenience that this creates, but looking back we think this is the best path forward.
