### ISSUE TITLE
playTrackProvider does not play track

### ISSUE THREAD

**Issue by brianadvent** [spotify/ios-sdk#236]
I experienced that sometimes the callback is called and sometimes its not. Also in many cases the player does not start playing although it is provided with a SPTTrack. 

I am using a SPTTrack as TrackProvider. I made sure that the SPTTrack is never nil so I assume that there could be something wrong with the playTrackProvider method in the SDK.

This is what I do:
```swift
 SPTRequest.requestItemAtURI(NSURL(string: "\(id)"), withSession: nil, callback: { (error:NSError!, spotifyTrack:AnyObject!) -> Void in
                if error != nil {
                    println("*** Album lookup got error \(error)")
                    return
                }
            
                if let track = spotifyTrack as SPTTrack!{
                    println(track) // Track is always available but does not get played
                    self.player.playTrackProvider(track, callback: { (error:NSError!) -> Void in
                        if error == nil{
                            self.updateCoverArt()

                        }else{
                            println("error playing track")
                        }
                    })

                }

 })
```

**Comment by brianadvent** [comment]
I have also discovered that many tracks just won't play. I wrote a function that enables me to search for the spotify item URIs. The following code searches for a specific track. If I run this 100 times it won't play. Another track id like spotify:track:4t5lrf5rFX6JWAUPKCDlKk works just fine.

```swift
SPTRequest.requestItemAtURI(NSURL(string: "spotify:track:4bZvA6Uk1QnIfOx0AmfLac"), withSession: nil, callback: { (error:NSError!, tr:AnyObject!) -> Void in
                let track = tr as SPTTrack

                self.player?.playTrackProvider(track, callback: { (error:NSError!) -> Void in

                    if error != nil {
                        println(error)
                    }
                })
            })
```
The used URI contains the spotify track id. So perhaps someone could tell me if there is any way to tell if a track is playable or if that is an error in the sdk that will be fixed in the future.

**Comment by possan** [comment]
We just added track linking support to the API so we'll add support for that in the SDK really soon

**Comment by possan** [comment]
This should be fixed in the latest betas, just pass market when looking up the item to play.
