### ISSUE TITLE
Advance auth using SceneDelegate and iOS13

### ISSUE THREAD

**Issue by Antonio-Melo** [spotify/ios-sdk#237]
Let me start just saying that I'm **not an experienced** iOS Developer and I have tried a lot to make this work, but with no luck so far. I have done the same for Android and was much easier.

I started following the [quick start guide](https://developer.spotify.com/documentation/ios/quick-start/) and it says: "If you need to authorize for more scopes than just controlling Spotify with App Remote please take a look at [advanced auth](https://developer.spotify.com/documentation/ios/guides/advanced-auth.md)"

I created a new project in Xcode (11.4) and configured everything to add the framework correctly.

**SceneDelegate:**
```
import UIKit

class SceneDelegate: UIResponder, UIWindowSceneDelegate, SPTSessionManagerDelegate {

    var window: UIWindow?
    var spotifyClient : SpotifyClient = SpotifyClient()
    
    lazy var sessionManager: SPTSessionManager = {
        let manager = SPTSessionManager(configuration: spotifyClient.getConfiguration(), delegate: self)
        return manager
    }()

 
    func scene(_ scene: UIScene, willConnectTo session: UISceneSession, options connectionOptions: UIScene.ConnectionOptions) {
        guard let _ = (scene as? UIWindowScene) else { return }
    }

    func sceneDidBecomeActive(_ scene: UIScene) {
        let requestedScopes: SPTScope = [.appRemoteControl]
        self.sessionManager.initiateSession(with: requestedScopes, options: .default)
    }
    
    // MARK - SPTSessionManagerDelegate
    
    func sessionManager(manager: SPTSessionManager, didInitiate session: SPTSession) {
        print("success", session)
    }
    
    func sessionManager(manager: SPTSessionManager, didFailWith error: Error) {
        print("failed", error)
    }
    
    func sessionManager(manager: SPTSessionManager, didRenew session: SPTSession) {
        print("renewed", session)
    }
}
```

My SpotifyClient has the SPTConfiguration configurated.
In the advance-auth.md it says:

Once a user successfully returns to your application, we'll need to notify `sessionManager` about it by implementing the following method:

```swift
func application(_ app: UIApplication, open url: URL, options: [UIApplicationOpenURLOptionsKey : Any] = [:]) -> Bool {
  self.sessionManager.application(app, open: url, options: options)
  return true
}
```

Where can I put this if I'm not using the ApplicationDelegate?

If someone was able to make it work and could share code with me I would deeply appreciate it.

**Comment by harmankang** [comment]
I ran into the same issue (see #229).

Try this:

```swift
func scene(_ scene: UIScene, openURLContexts URLContexts: Set<UIOpenURLContext>) {
  guard let url = URLContexts.first?.url else {
    return
  }
  self.sessionManager.application(UIApplication.shared, open: url, options: [:])
}
```

**Comment by GabeJacobs** [comment]
@harmankang  @Antonio-Melo 

Let me just say, I also ran into issues using the documentation. Spotify doesn't prioritize the sdk. They need to do a complete overhaul and totally re-do the documentation and implementation of the SDK.  Everything is overly complicated and most of their guides are outdated and wrong. It's so sad how many people struggle with trying to do something as simple as authentication. Look at any other popular service such as google/facebook/apple and see how simple it all is.

**Comment by Antonio-Melo** [comment]
Hi @harmankang, thank you so much for the tip, it worked perfectly. I own you one !!
@GabeJacobs I totally agree with you, I found it extremely difficult compared with other popular services.
