### ISSUE TITLE
Can't add tracks to starred playlist?

### ISSUE THREAD

**Issue by paasan** [spotify/ios-sdk#239]
SPTPlaylistSnapshot:
-(void)addTracksToPlaylist:(NSArray *)tracks withSession:(SPTSession *)session callback:(SPTErrorableOperationCallback)block;

Fails when adding a track to "spotify:user:paasan:starred" while logged inn as 'paasan'. Can view tracks, so I got the full/correct object. Error = NSError domain: @"com.spotify.ios-sdk" - code: 404 "not found"

Works fine with my other playlists, for the exact same track under the exact same conditions.

These are my scopes:
SPTAuthStreamingScope, SPTAuthUserLibraryReadScope, SPTAuthPlaylistReadPrivateScope, SPTAuthUserLibraryModifyScope, SPTAuthPlaylistModifyPrivateScope, SPTAuthPlaylistModifyPublicScope

**Comment by tbass134** [comment]
Having the same issue.
Here's what i am doing 

     [SPTRequest starredListForUserInSession:[PlayerManager sharedInstance].session callback:^(NSError *error, id object) {
        SPTPlaylistSnapshot *playlistSnapshot = (SPTPlaylistSnapshot *)object; 

        SPTPartialTrack *track =self.tracks[self.current_track_index]; //this is a track i want to star

        [playlistSnapshot addTracksToPlaylist:@[track] withSession:[PlayerManager sharedInstance].session callback:^(NSError *error) {
            
      
        }];
        
    }];

**Comment by possan** [comment]
We're not officially supporting starred tracks any more, i'd suggest adding tracks to "Your Music" instead.

**Comment by tbass134** [comment]
Thanks @possan for the update

**Comment by ronakvora** [comment]
What's the reason for not supporting this?
