### ISSUE TITLE
Searching tracks by metadata

### ISSUE THREAD

**Issue by truemetal** [spotify/ios-sdk#24]
Hey there! 

There're nice APIs that return track metadata: `v1/audio-features/{id}` and `/v1/audio-analysis/{id}` 
I wonder, is it possible to search tracks with `/v1/search` using the metadata to filter tracks e.g. by danceability, energy, tempo eg? 

If that's not possible right now, are there any plans for supporting this in the nearest future? 

Thanks

**Comment by jackfreeman** [comment]
@truemetal You can't search directly on the analyses, but this might be close to what you're looking for: https://developer.spotify.com/documentation/web-api/reference/browse/get-recommendations/
