### ISSUE TITLE
Wifi to cell network pauses music

### ISSUE THREAD

**Issue by pconno** [spotify/ios-sdk#240]
I'm running into an issue when my phone loses wifi and moves onto a cell network. This occurs roughly 50% of the time. When this happens the music stops. It doesn't appear that any of the SPTAudioStreamingDelegate methods are called to notify my app that the music has stopped. The only method that is called is comes from SPTAudioStreamingPlaybackDelegate

`
-(void)audioStreaming:(SPTAudioStreamingController *)audioStreaming didStopPlayingTrack:(NSURL *)trackUri
`

I would expect one of the following methods to be called.

`-(void)audioStreaming:(SPTAudioStreamingController *)audioStreaming didEncounterError:(NSError *)error`

`-(void)audioStreamingDidEncounterTemporaryConnectionError:(SPTAudioStreamingController *)audioStreaming`

**Comment by possan** [comment]
It is supposed to call `audioStreamingDidEncounterTemporaryConnectionError` when an intermittent error is detected, Is this still an issue with the latest beta?

**Comment by possan** [comment]
Closing this, this should be fixed now in the latest release.
