### ISSUE TITLE
Play music from particular playlist

### ISSUE THREAD

**Issue by auro-krishna** [spotify/ios-sdk#242]
I would like to achieve the following items, Can anyone help me out for doing this

1. I want to play music from a particular playlist which I have created and also need to reorder the playlist items.
2. Need to switch the tracks between items and seek to some particular location without buffering. Is there any way where I can preload next track?

**Comment by kkarayannis** [comment]
You can use the playlist's URI to start playback. 
You can't reorder the playlist order from this SDK.
You can't preload the next track but there shouldn't be any buffering if the user has previously downloaded the tracks for offline use in the Spotify app.

**Comment by auro-krishna** [comment]
Thanks for the update
