### ISSUE TITLE
SDK support for free subscribers to play in shuffle mode?

### ISSUE THREAD

**Issue by akoi** [spotify/ios-sdk#243]
With the recent addition to the Spotify iOS app allowing users on free subscriptions to play music in shuffle mode, I was wondering if there are plans to include this functionality for 3rd party apps using the iOS SDK?

**Comment by possan** [comment]
Not planned right now, but of course, eventually we wish to do so, there's a few other things we need to add  support for then like ads and playback order changes.

**Comment by akoi** [comment]
Ok, many thanks for the feedback. Be great to get an update when you have more of an idea when this will be available. Look forward to having this functionality!
