### ISSUE TITLE
permittedBackgroundDuration expires - app gets killed

### ISSUE THREAD

**Issue by Anders27** [spotify/ios-sdk#245]
I’m using SPTCoreAudioController

I do:

[mPlayer setIsPlaying:NO callback:^(NSError *error)
[mPlayer stop:^(NSError *error)

If I then just leave my app running, but moving into background (home button), the app will resign active.
So far so good, this is normal behaviour.

But when I “wake up” my app after say five minutes, it will be restarted since the system has killed it.

Here is snippet from a crash log:

Exception Type:  00000020
Exception Codes: 0x000000008badf00d
Highlighted Thread:  8

Application Specific Information:
<BKNewProcess: 0x127d2fc30; com.mycompany.myapp; pid: 795; hostpid: -1> has active assertions beyond permitted time: 
{(
    <BKProcessAssertion: 0x127e16aa0> id: 795-75421E9A-29EE-464B-B8D2-E9F02DEA57D1 name:
    Called by myapp, from -[SPTCoreAudioController startAudioQueue]
    process: <BKNewProcess: 0x127d2fc30; com.mycompany.myapp; pid: 795; hostpid: -1>
    permittedBackgroundDuration: 180.000000 reason: finishTask owner pid:795 preventSuspend  preventIdleSleep  preventSuspendOnSleep 
)}

Thread 8 name:  com.spotify.AudioStreaming
Thread 8:
0   libsystem_kernel.dylib        	0x0000000198833498 __select + 8
1   myapp                           	0x00000001002297c0 0x10008c000 + 1693632
2   myapp                           	0x00000001002170ec 0x10008c000 + 1618156
3   myapp                           	0x000000010021ec7c 0x10008c000 + 1649788
4   myapp                           	0x000000010021c2c8 0x10008c000 + 1639112
5   myapp                           	0x00000001001e86d8 0x10008c000 + 1427160
6   CoreFoundation                	0x00000001879128d4 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 24
7   CoreFoundation                	0x0000000187912584 __CFRunLoopDoTimer + 884
8   CoreFoundation                	0x000000018790ffd0 __CFRunLoopRun + 1368
9   CoreFoundation                	0x000000018783d0a0 CFRunLoopRunSpecific + 392
10  CoreFoundation                	0x000000018788f1f8 CFRunLoopRun + 108
11  myapp                           	0x00000001001e8c80 0x10008c000 + 1428608
12  Foundation                    	0x000000018882dba8 __NSThread__main__ + 1068
13  libsystem_pthread.dylib       	0x00000001988cfe7c _pthread_body + 160
14  libsystem_pthread.dylib       	0x00000001988cfdd8 _pthread_start + 156
15  libsystem_pthread.dylib       	0x00000001988ccfac thread_start + 0

I assume the Spotify SDK calls beginBackgroundTaskWithExpirationHandler for some reason and when the 180 seconds has expired, the app gets killed by the system.

How can I prevent this happening?

**Comment by iKenndac** [comment]
If you're not actively playing music, you can't. This is a built-in behaviour of iOS. 

Also, the SDK doesn't manage background tasks for you - if you want to stay alive in the background, you'll need to manage that yourself. Since this is outside the scope of the SDK (and isn't a bug to start with), I'll close the issue.
