### ISSUE TITLE
OpenGLES linker error on OS X

### ISSUE THREAD

**Issue by kennylovrin** [spotify/ios-sdk#247]
I realize that this might be super low prio as it is advertised as an iOS SDK, but since there are switches in the headers for OS X I gave it a go, and got a linker error for OpenGLES.

I mainly ask to figure out if this is in fact an issue in the SDK or if I have messed up something else..

**Comment by iKenndac** [comment]
The SDK is compiled against the iOS ABI, so although there are i386 and x86_64 slices in there, the SDK will *not* work in Mac OS X.

**Comment by kennylovrin** [comment]
Thanks for the reply, that is fine.

May I ask though, if I wanted to do an app for OS X, I could potentially just wrap the web API myself. But, there is no way of logging in the user in libspotify with a token from the web API right?

So, is there any other way to get playback on OS X while still using only an OAuth login flow? I could ask for two logins of course, one specific for audio playback, but I'd rather not. :)

**Comment by iKenndac** [comment]
No, not right now. If you want to Make a Mac application, use CocoaLibSpotify - it provides a full SDK including metadata and playback.
