### ISSUE TITLE
Often getting 502 Bad Gateway when authenticating

### ISSUE THREAD

**Issue by jayceecam** [spotify/ios-sdk#248]
It's intermittent, but we're fairly often seeing a 502 when authenticating. Sometimes this alleviates itself fairly quickly, and other times it takes > 10 mins to resolve.

Here an an example of the URL providing the 502. I omitted our Client ID and App ID in the redirect_url below.

https://accounts.spotify.com/authorize?client_id={CLIENT_ID}&scope=streaming%20playlist-read-private%20playlist-modify-private%20user-library-read%20user-library-modify&redirect_uri={APP_ID}%3A%2F%2Fspotify-callback&response_type=code

**Comment by GabeJacobs** [comment]
Yep, getting it too

**Comment by GabeJacobs** [comment]
Back up!

**Comment by bangerang** [comment]
Same here
