### ISSUE TITLE
Wrong tracks order on starred playlist

### ISSUE THREAD

**Issue by martinobonfiglioli** [spotify/ios-sdk#253]
This method returned me uresr's starred playlist but tracks are in 'shuffle' order.

```objectivec
+(void)starredListForUserInSession:(SPTSession *)session callback:(SPTRequestCallback)block
```

**Comment by iKenndac** [comment]
This is actually known behaviour for starred, and is consistent with all our other SDKs including CocoaLibSpotify. To get the correct order, get the whole playlist and sort by the `addedAt` property.
