### ISSUE TITLE
No album artwork url for SPTrack in SPTListPage.items for performSearchWithQuery?

### ISSUE THREAD

**Issue by tnahvu** [spotify/ios-sdk#254]
Is it not possible to get album artwork for SPTTrack that are returned from doing searches?  Sorry, if I'm missing something...I want to display the search results on a tableview cell with their respective album.  I've managed to get the album artwork for other fetches but not the performSearch. 

Thanks!

**Comment by kevin--** [comment]
I am promoting the results to a full SPTTrack object, then you can get the album art.

**Comment by tnahvu** [comment]
Ah! Cool, thanks!

**Comment by kevin--** [comment]
Search results typically return ```SPTPartialTrack``` (https://developer.spotify.com/ios-sdk-docs/Documents/Classes/SPTPartialTrack.html) objects to save time/data. These do not have an album field. When you have a Partial object, you can promote it to a full object (```SPTTrack``` in this case) with the ```SPTRequest requestItemFromPartialObject:withSession:callback:``` method (https://developer.spotify.com/ios-sdk-docs/Documents/Classes/SPTRequest.html#//api/name/requestItemFromPartialObject:withSession:callback:)

Then you can get the SPTPartialAlbum and its art.

**Comment by tnahvu** [comment]
Ah, I see.  Thanks, Kevin!
