### ISSUE TITLE
audioStreamingDidEncounterTemporaryConnectionError forever?

### ISSUE THREAD

**Issue by kevin--** [spotify/ios-sdk#255]
On Friday (02/20/2015) left work with a nice build of our app working well. Came in this morning, and everyone who has the app within our QA and Software teams cannot play any tracks. Library and Album Art all loads successfully, but when you start to play a track, we see the audioStreamingDidEncounterTemporaryConnectionError: method being called repeatedly, I guess about every 30 seconds.

Did anything change over the weekend? Would our clientId have been revoked? What can I check?

**Comment by tnahvu** [comment]
Problem here, as well. Played well last night at midnight, but this morning not playing with a sptsession, expiration date of tonight, and a player object.  Though, I'm not getting any errors.

**Comment by CVertex** [comment]
I'm seeing the same playback issues. Everything was working last night, but this morning playback doesn't start. No errors are returned through audioStreamingDidEncounterTemporaryConnectionError or anything else.

**Comment by megeek** [comment]
+1 for me...did anyone get a resolve on this?

**Comment by CVertex** [comment]
Still broken for me.

I tried djay 2 (another app that integrates with Spotify), and it works fine. Not sure what Spotify SDK/API they're using though.

**Comment by pkotesh-systango** [comment]
Same here. I was able to play a track in the morning. But not working again.

**Comment by CVertex** [comment]
@iKenndac pointed me to https://twitter.com/SpotifyPlatform/ 
Which says 
"The playback issue in the mobile SDKs has now been resolved. Thank you for your patience!"

https://twitter.com/SpotifyPlatform/status/569890325076033537

**Comment by megeek** [comment]
mine just recently started working again...it's still a bit delayed, but working...

**Comment by tnahvu** [comment]
Same here with slight delay.

**Comment by CVertex** [comment]
Still broken here :cry:

**Comment by pkotesh-systango** [comment]
It is random to me. Working sometimes with delay but not always.

**Comment by possan** [comment]
Is this still an issue?

**Comment by pkotesh-systango** [comment]
When I play a track, sometimes It hits the audioStreamingDidEncounterTemporaryConnectionError and then starts Playing.

**Comment by possan** [comment]
we had an short outage about a week ago that probably was the cause of this issue at least

**Comment by kevin--** [comment]
My app has resumed normal functionality, and yes, I opened this bug regarding the outage.
