### ISSUE TITLE
cb_error_event (SPTAudioStreamingController.m:911)

### ISSUE THREAD

**Issue by dtrenz** [spotify/ios-sdk#257]
```
EXC_BAD_ACCESS KERN_INVALID_ADDRESS at 0x00000001a87ebec8
cb_error_event (SPTAudioStreamingController.m:911)
```

I'm seeing this crash a lot from SPTAudioStreamingController. Any idea what could be causing it?

**Comment by possan** [comment]
Closing this, this should be fixed now in the latest release.
