### ISSUE TITLE
[Request] Add Support For Starting Songs With Offsets Or Playing Time Ranges

### ISSUE THREAD

**Issue by awojnowski** [spotify/ios-sdk#258]
I'm looking for the functionality to be able to start a song with an offset (such as starting the songs 45 seconds in) and even play the song during a select time range.

So far, I've tried:

1. Appending `#0:45` (or any starting offset time) to the song URI as described here: http://stackoverflow.com/questions/9444482/spotify-api-playing-a-specific-part-of-a-song
2. Pausing the song after it initially starts loading, seeking, and unpausing, in a `dispatch_after` block like so (this seems to work 50% of the time on a good connection, and not at all on a low network connection, presumably due to dispatch offset being too small):

        CGFloat const offset = 30.0;
        SPTAudioStreamingController __weak *audioStreamingControllerW = audioStreamingController;
        [audioStreamingController playURI:[self URI] callback:^(NSError *error) {
        
            dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(0.1 * NSEC_PER_SEC)), dispatch_get_main_queue(), ^{
            
                [audioStreamingControllerW setIsPlaying:NO callback:^(NSError *error) {
                    [audioStreamingControllerW seekToOffset:offset callback:^(NSError *error) {

                        NSLog(@"Seeked to offset %f with error: %@",offset,error);
                        [audioStreamingControllerW setIsPlaying:YES callback:^(NSError *error) {
                            // finished
                        }];

                    }];
                }];
            
            });
        
        }];

It would be nice to be able to offset the song starting time, or even set a time range for the song (such as play only the first 45 seconds, or play 45 seconds to 2 minutes) without having to manually monitor that time range.

**Comment by possan** [comment]
This is actually solved in the new beta that we released like 10 minutes after you posted that issue :)

**Comment by awojnowski** [comment]
Excellent stuff! Looks to be working great :)
