### ISSUE TITLE
appRemoteDidEstablishConnection not being called

### ISSUE THREAD

**Issue by vikasnair** [spotify/ios-sdk#26]
Currently trying to migrate to this SDK from the prev. streaming one. Having a lot of trouble figuring out a particular issue re: `appRemote` delegate. I followed the Quick Start guide, have verified that the session successfully inits, and also see these logs...

> AppRemote: Connecting...
> AppRemote: Established a connection to the Spotify app.

...however none of the appRemote delegate methods are being called. I have set `appRemote.delegate = self` within my main AppDelegate, and have implemented all the req. delegate methods. 

```
    func appRemoteDidEstablishConnection(_ appRemote: SPTAppRemote) {
        print("connected!", playerRemote != nil, playerRemote?.playerAPI != nil) // DOES NOT PRINT
        playerRemote?.playerAPI?.subscribe(toPlayerState: { (success, error) in
            print(success, error)
        })
    }
    
    func appRemote(_ appRemote: SPTAppRemote, didDisconnectWithError error: Error?) {
        print("disconnected!", error) // DOES NOT PRINT
        sptSessionManager?.renewSession()
    }
    
    func appRemote(_ appRemote: SPTAppRemote, didFailConnectionAttemptWithError error: Error?) {
        print("failed!", error.debugDescription) // DOES NOT PRINT
    }
```

For reference, here is the rest of the setup:

```

    // MARK: Application Delegate

    func initializeSpotify() {
        sptConfiguration = SPTConfiguration(clientID: "###", redirectURL: URL(string: "###")!)
        sptConfiguration!.tokenRefreshURL = URL(string: "###")!
        sptConfiguration!.tokenSwapURL = URL(string: "###")!
        sptConfiguration!.playURI = ""
        sptSessionManager = SPTSessionManager(configuration: sptConfiguration!, delegate: self)
        playerRemote = SPTAppRemote(configuration: sptConfiguration!, logLevel: .debug)
        **playerRemote!.delegate = self**
        
        let requestedScopes: SPTScope =  [.appRemoteControl] // .streaming?
        
        if #available(iOS 11.0, *) {
            sptSessionManager!.initiateSession(with: requestedScopes, options: .default)
        } else {
//            sptSessionManager!.initiateSession(with: requestedScopes, options: .default, presenting: <#T##UIViewController#>)
        }
    }

    func applicationDidBecomeActive(_ application: UIApplication) {
        if let _ = playerRemote?.connectionParameters.accessToken {
            // successfully reaches here and connects, resetting delegate to be extra sure (doesn't work either way)
            playerRemote!.delegate = self
            playerRemote?.connect()
        }
    }
    // MARK: SPTSessionManager Delegate
    
    func sessionManager(manager: SPTSessionManager, didInitiate session: SPTSession) {
        print("successfully init spt session", playerRemote != nil) // prints true
        playerRemote!.connectionParameters.accessToken = session.accessToken
    }
    
    func sessionManager(manager: SPTSessionManager, didFailWith error: Error) {
        print("failed to init spt session", error) // DOES NOT PRINT
        sptSessionManager?.renewSession()
    }
    
    func sessionManager(manager: SPTSessionManager, didRenew session: SPTSession) {
        print("renewed spt session", session) // DOES NOT PRINT
    }
```

My thoughts were maybe it had something to do with the way I was initializing the var globally? I am running this on Xcode 10.1 Beta on a physical iPhone X running iOS 12 with Spotify installed. Could this be an issue?

**Comment by AlexVedushev** [comment]
Maybe this is help:
DispatchQueue.main.async {[weak self] in
            appRemote.connect()
        }

**Comment by vikasnair** [comment]
@AlexVedushev doesn't seem to do anything. playerRemote is defined globally. However when I 'connect()' after dispatch on main after 2 seconds or so, OR if I 'connect()' in a ViewController instantiated after returning to the app from Spotify auth, then the delegate works and prints:

> failed! failed! Optional(Error Domain=com.spotify.app-remote Code=-1000 "Connection attempt failed." UserInfo={NSLocalizedDescription=Connection attempt failed., NSUnderlyingError=0x280b2ad00 {Error Domain=com.spotify.app-remote.transport Code=-2000 "Stream error." UserInfo={NSLocalizedDescription=Stream error., NSUnderlyingError=0x280b2adc0 {Error Domain=NSPOSIXErrorDomain Code=61 "Connection refused" UserInfo={_kCFStreamErrorCodeKey=61, _kCFStreamErrorDomainKey=1}}, NSLocalizedRecoverySuggestion=Reconnect the transport to the Spotify app., NSLocalizedFailureReason=A stream error has occured in the transport.}}, NSLocalizedRecoverySuggestion=Ensure the Spotify app is installed, and try to reconnect., NSLocalizedFailureReason=Could not connect to the Spotify app.})

**Comment by vikasnair** [comment]
The main problem here that I am trying to fix is that the `playerAPI` property of `appRemote` is always `nil`. Even though property `isConnected` reads true. Any thoughts on why this might be @devs?

**Comment by vikasnair** [comment]
Ok, I've fixed the above issue by putting back the `playURI = ""` in config. But is there a way to do init `playerAPI` **without** forcing playback?

**Comment by jackfreeman** [comment]
@vikasnair to connect App Remote audio must be playing so the Spotify app can be running in the background on the user's device. 

As for the delegate methods, are you sure you are setting the correct instance as the delegate? Where are you initializing `SPTAppRemote` and where are you setting it's delegate in the `AppDelegate` specifically?

**Comment by vikasnair** [comment]
Right, for some reason it wasn't working before when I had that `playURI` set, but I must have been doing something else wrong! 

Re: delegate methods, I was do `init` and `connect` within the `AppDelegate`. Specifically, `init` on `didFinishLaunchingWithOptions` and `connect` on `didBecomeActive` under the condition that its `accessToken` has been set (which it was).

```
    func applicationDidBecomeActive(_ application: UIApplication) {
        if let _ = playerRemote?.connectionParameters.accessToken {
            print("goes here") // DOES print
            playerRemote?.delegate = self
            playerRemote?.connect()
        }
    }
```

Now I have figured that in the main app I can instantiate `playerAPI` by making a call to `authorizeAndPlay` if the `playerAPI` property is `null`, else `play`. This works for my purposes, so I'm satisfied with that. Do I need to set the delegate after I have instantiated `playerAPI` for the `appRemote.delegate` to work (not `appRemote.playerAPI.delegate`)?

**Comment by jackfreeman** [comment]
@vikasnair the `SPTAppRemote` delegate methods should be firing regardless of dealing with the `playerAPI`. Can you provide a sample project that has the issue of the delegate not being called?

**Comment by cjam** [comment]
Was having the exact same issue, thanks to @AlexVedushev with the suggestion of dispatching on the main queue. I wish I found this thread earlier in my travels.  Is there any indication in the docs anywhere that a method needs to be run on the main queue?

**Comment by jackfreeman** [comment]
@cjam we will update the readme to clarify that the SDK is not currently thread safe and depends on the calls originating from main thread.

**Comment by appsird** [comment]
Jack, I have a number of fixes for you. Would like to do a pull request, but uncertain how to process. Would appreciate if you guid me through the process. want to save others from the hours I had to put into making this demo project work..

**Comment by Goos** [comment]
@appsird Hey Brian! Thanks for wanting to share your learnings – please open a pull request with your proposed changes and we can take it from there.

**Comment by cjam** [comment]
@appsird You'll want to create a fork of this repo and create your branch (and work) within your fork.  Then when you're happy with it, GitHub should allow you to issue a PR back to the original repo (i.e. this one).  If you just cloned this repo, you won't have permissions to push new branches or commits as it will be locked down to contributors.

**Comment by appsird** [comment]
Colter,

I created a pull request with two minor changes. More changes later.
