### ISSUE TITLE
SPTRequest::userInformationForUserInSession:callback always returns SPTProductUnknown for SPTUser.product

### ISSUE THREAD

**Issue by dtrenz** [spotify/ios-sdk#260]
I'm trying to determine if a user has a free or premium account, but the SPTUser object returned from SPTRequest::userInformationForUserInSession:callback always returns SPTProductUnkown for both free & premium accounts.

**Comment by iKenndac** [comment]
Did you include the `SPTAuthUserReadPrivateScope` scope when authenticating?

**Comment by rodgutierrez** [comment]
I had the same problem. Originally I had an Unlimited subscription, and it wasn't until I canceled my account and resubscribed as a Premium user that the `SPTProduct` property on `SPTUser` started to return a valid value.

**Comment by possan** [comment]
This has been fixed in the latest beta, also this api will probably change to a capabilities-type api to make it simpler, think `canStreamAudio` or similar...

**Comment by kevosauce** [comment]
this is happening for me using both `requestCurrentUserWithAccessToken` and `requestUser:(NSString *)username withAccessToken` . I am requesting the `SPTAuthUserReadPrivateScope`. Any advice?

**Comment by sajsanghvi** [comment]
+1 same

**Comment by bowenbowensun** [comment]
This is happening to me too. I'm using swift and requestCurrentUserWithAccessToken
