### ISSUE TITLE
How to check for available markets?

### ISSUE THREAD

**Issue by ahallora** [spotify/ios-sdk#261]
I want to validate that any given spotify track is playable by the player, so I've implemented a check to see if a tracks availableTerritories is within the users "market", in this case Denmark (DK). (sptTrack is a valid SPTPartialTrack object)

```objective-c
NSMutableArray *songMarkets = [NSMutableArray arrayWithArray:sptTrack.availableTerritories];
NSString *userMarket = @"DK";
if([songMarkets containsObject:userMarket]) {
   // song is playable
}
```

This song (https://play.spotify.com/track/6izhPbUU3CeMYvTT74YHnb) is playable with the Spotify Web Player, but when I look at the availableTerritories of said track (6izhPbUU3CeMYvTT74YHnb) with the Spotify API Console (https://developer.spotify.com/web-api/console/get-track/) it returns:
```json
"available_markets" : [ "CA", "MX", "US" ]
```
Which in case makes my script above useless. 

How can I do a proper check if the song is actually playable by the user? AvailableTerritories is obviously not adequate for the job... :smiley: 

Thanks in advance.

**Comment by iKenndac** [comment]
Beta 7, released a couple of days ago, fixes this so you don't have to do checks like this.

Instead, pass in `SPTMarketFromToken` to the market parameter when making requests in `SPTRequest` and the SDK will endeavour to give playable tracks in the user's region.
