### ISSUE TITLE
SPTAuthViewController.hidesSignup doesn't show signup button

### ISSUE THREAD

**Issue by kennylovrin** [spotify/ios-sdk#262]
My understanding is that setting this property to false will show a signup button in the login screen, but it seems it doesn't. I still get only one button - "sign in"

`authController.hideSignup = false`

**Comment by iKenndac** [comment]
Signup is one of the things that got SDK apps rejected from the App Store, so that functionality has been removed for now.

**Comment by possan** [comment]
Indeed, we're waiting for changes to happen elsewhere in the org before we can enable it again...

**Comment by kennylovrin** [comment]
No worries, that's fine. Just needed to know. :)

**Comment by GabeJacobs** [comment]
hiding signup isn't doing anything in beta 8

**Comment by DmytroAnkudinov** [comment]
The hide signup has been removed in Beta25 and the whole SPTAuthViewController class has been deprecated in Beta25 and would be removed later.
