### ISSUE TITLE
SPTAuthViewController: Can't tap Login With Facebook

### ISSUE THREAD

**Issue by GabeJacobs** [spotify/ios-sdk#263]
In SPTAuthViewController, when the popup open, I can't immediately tap Login With Facebook. I can't scroll the popover either. Only if I tap a field first can I do either of those things.

**Comment by elmateo487** [comment]
Also in the simulator you cannot click on Login with Facebook, it does nothing.

**Comment by possan** [comment]
I'm not able to see this issue in my simulator builds at all, is this still an issue?

**Comment by possan** [comment]
I'm closing this, re-open if this is still an issue.
