### ISSUE TITLE
Beta 7 Xcode warnings

### ISSUE THREAD

**Issue by Anders27** [spotify/ios-sdk#264]
My project doesn't use ARC and starting with Beta 7 I get the following warnings:

Spotify.framework/Headers/SPTDiskCaching.h:65:1: No 'assign', 'retain', or 'copy' attribute is specified - 'assign' is assumed
Spotify.framework/Headers/SPTDiskCaching.h:65:1: Default property attribute 'assign' not appropriate for non-GC object

In "SPTDiskCaching.h"
@property (nonatomic) NSURL *URI;

@property (nonatomic, assign) NSURL *URI;
would probably silence the warnings?

Other than that Beta 7 works fine!

**Comment by iKenndac** [comment]
Assign will likely cause problems - you want `strong` instead. We'll fix the header in a later release.

**Comment by possan** [comment]
Closing this, this should be fixed now in the latest release.
