### ISSUE TITLE
SPTRequest starredListForUserInSession deprecated, why?

### ISSUE THREAD

**Issue by Anders27** [spotify/ios-sdk#265]
+(void)starredListForUserInSession:(SPTSession *)session callback:(SPTRequestCallback)block DEPRECATED_ATTRIBUTE;

Will this go away?
I think it's important to keep it.
Or does it just mean it will be replaced with something similar in the future?

**Comment by jbharrell92** [comment]
IIRC, starred songs are being replaced in favor of 'Your Music' in the Spotify platform.

**Comment by iKenndac** [comment]
Yes, @jbharrell92 is correct. Starred is being demoted to a regular playlist for users who already have it, and the "Your Music" functionality is replacing it as the canonical "the user's favourite music" place.

**Comment by jarrodrobins** [comment]
Since Starred is being demoted to a regular playlist, is the plan that it'll be sent down with the `playlistsForUserInSession` method response at some point? Currently that's not the case, and would be quite useful so we don't have to use a deprecated method to access its songs.
