### ISSUE TITLE
currentTrackMetadata deprecated - what to replace it?

### ISSUE THREAD

**Issue by ahallora** [spotify/ios-sdk#266]
First and foremost thank you for a nice beta release 7. I'm particularly pleased with the new simplified login form and auth singleton. :+1:

However, with beta 7 you've marked [currentTrackMetadata as deprecated](https://github.com/spotify/ios-sdk/blob/master/Spotify.framework/Versions/A/Headers/SPTAudioStreamingController.h#L428):
```objective-c
@property (nonatomic, readonly, copy) NSDictionary *currentTrackMetadata DEPRECATED_ATTRIBUTE;
```

But [according to the API](https://developer.spotify.com/ios-sdk-docs/Documents/Classes/SPTAudioStreamingController.html#//api/name/currentTrackMetadata) currentTrackMetadata should still be a valid way to retrieve current metadata for the currently playing track. Furthermore are you actually using it in  your demo project [Simple Track Playback](https://github.com/spotify/ios-sdk/blob/master/Demo%20Projects/Simple%20Track%20Playback/Simple%20Track%20Playback/ViewController.m#L100). 

What do you suggest as an alternative to currentTrackMetadata? :smile:

**Comment by elmateo487** [comment]
I had to actually just remove the deprecated part of their sdk......... to be able to use the app.

**Comment by ahallora** [comment]
@elmateo487 , how did you then retrieve the metadata of the currently playing track? :smile:

**Comment by elmateo487** [comment]
Lol. Once you delete the deprecated tag you can then just use getCurrentTrackMetadata again. Ghetto. But works.

**Comment by iKenndac** [comment]
You want `currentTrackURI`. Pass that to `SPTRequest` to get whatever metadata you need.
