### ISSUE TITLE
How to modify the SPTAuthViewController?

### ISSUE THREAD

**Issue by ahallora** [spotify/ios-sdk#267]
I have some issues with the SPTAuthViewController showing up but the webView doesn't show any webpage; so it's just a white modal. How can I see the code behind the AuthViewController so I can analyse the execution of the code and where it all goes wrong...? 

I use the following code, taken from the new demo project:
```objective-c
- (void)openLoginPage {
    self.authViewController = [SPTAuthViewController authenticationViewController];
    self.authViewController.delegate = self;
    self.authViewController.modalPresentationStyle = UIModalPresentationOverCurrentContext;
    self.authViewController.modalTransitionStyle = UIModalTransitionStyleCrossDissolve;

    self.modalPresentationStyle = UIModalPresentationCurrentContext;
    self.definesPresentationContext = YES;

    [self presentViewController:self.authViewController animated:NO completion:nil];
}
```

Also, how can I modify the close-image of the modal? E.g. the depth (z-index), image-src and action associated with it? Is there a xib or storyboard somewhere or how (and where) is it configured? :smile:

**Comment by possan** [comment]
This is probably related to the bug with ios7 (#271)

**Comment by possan** [comment]
Closing this, this should be fixed now in the latest release.
