### ISSUE TITLE
-(void)playURI:(NSURL *)uri callback:(SPTErrorableOperationCallback)block is deprecated

### ISSUE THREAD

**Issue by bangerang** [spotify/ios-sdk#270]
May I ask why this is deprecated? Can't really see why. 
This forces me to restructure a lot of my code to use ```playURIs``` instead...

**Comment by iKenndac** [comment]
Because it'll be going away soon, it the simplest answer. Our internal playback stack changed quite a lot recently, so we're having to follow (which is why the library is still marked as a beta).

**Comment by elmateo487** [comment]
@bangerang everywhere you had playURI just replace it with playURIs and pass in an array of 1 uri. Until you are ready to update your code.
