### ISSUE TITLE
SPTAuthViewController won't load on iOS 7

### ISSUE THREAD

**Issue by GabeJacobs** [spotify/ios-sdk#271]
![img_3503](https://cloud.githubusercontent.com/assets/953195/6581139/64dc061c-c72b-11e4-9855-e3625b46a5b8.png)

on iOS7, it won't load. I've tried on multiple devices. This is a serious problem for us, any idea!?

**Comment by pabloblancog** [comment]
Are you creating the SPTAuthViewController with the right constructor?
SPTAuthViewController *authvc = [SPTAuthViewController authenticationViewController];

**Comment by markdintrepid** [comment]
I'm seeing this as well. Attempting to present `[SPTAuthViewController authenticationViewController]` results in the following exception, so it looks like an iOS 8-only API is being used somewhere.

```
-[__NSCFString containsString:]: unrecognized selector sent to instance 0x7fd99bea9f20
*** WebKit discarded an uncaught exception in the webView:decidePolicyForNavigationAction:request:frame:decisionListener: delegate: <NSInvalidArgumentException> -[__NSCFString containsString:]: unrecognized selector sent to instance 0x7fd99bea9f20
```

**Comment by loretoparisi** [comment]
@markdintrepid that's correct. Infact 

```
- webView:decidePolicyForNavigationAction:decisionHandler:
```

is a method of the new Web View class the ```WKWebView```

```
https://developer.apple.com/library/prerelease/ios/documentation/WebKit/Reference/WKNavigationDelegate_Ref/index.html#//apple_ref/occ/intfm/WKNavigationDelegate/webView:decidePolicyForNavigationAction:decisionHandler:
```

**Comment by gbrickley** [comment]
I'm having the same issue.  The following code works on iOS 8 but 7 just shows a blank screen.  Also, it would be nice to have an activity indicator show in the SPTAuthViewController while it loads.  Even on iOS 8 it's just a white screen for a while before anything loads.  

    SPTAuthViewController *authvc = [SPTAuthViewController authenticationViewController];
    authvc.delegate = self;
    authvc.modalPresentationStyle = UIModalPresentationOverCurrentContext;
    authvc.modalTransitionStyle = UIModalTransitionStyleCrossDissolve;
    self.modalPresentationStyle = UIModalPresentationCurrentContext;
    self.definesPresentationContext = YES;
    
    // Clear the cookies before showing the login view
    [authvc clearCookies:^() {
        [self presentViewController:authvc animated:NO completion:nil];     
    }];

**Comment by billgert** [comment]
Having this problem here as well.

**Comment by GabeJacobs** [comment]
An activity indicator would be really great. In spotty service you just see a white screen for 5-8 seconds before the page loads

**Comment by Zwaaan** [comment]
I can also confirm that this is a bug, I received several users reporting problems and all have iOS7, when I test myself I can crash on [NSString containsString] which was introduced in iOS 8, perhaps check new code with older versions then iOS8 before release? Hoping for a quick fix! :)

+1

**Comment by GabeJacobs** [comment]
Is there anyway to do this remotely? We just released our app and are getting a lot of complaints :(

**Comment by GabeJacobs** [comment]
@possan do you have any thoughts on this problem? It would be really nice to fix this one since we've noticed 1/5th of our users are still on iOS 7

**Comment by GabeJacobs** [comment]
You could replace the containsString with the rangeOfString method which is supported on iOS 7 as well: http://stackoverflow.com/questions/2753956/how-do-i-check-if-a-string-contains-another-string-in-objective-c

**Comment by possan** [comment]
Closing this, this should be fixed now in the latest release.
