### ISSUE TITLE
-(void)playURIs:(NSArray *)uris fromIndex:(int)index callback:(SPTErrorableOperationCallback)block; doesnt work with UIEventSubtypeRemoteControlNextTrack 

### ISSUE THREAD

**Issue by bangerang** [spotify/ios-sdk#272]
When i try to change to next track with ```UIEventSubtypeRemoteControlNextTrack``` nothing happens, it works if the app is active though.
This all works just fine with the deprecated method ```-(void)playURI:(NSURL *)uri fromIndex:(int)index callback:(SPTErrorableOperationCallback)block```.
Some example code:
```
//AppDelegate
-(void)remoteControlReceivedWithEvent:(UIEvent *)event
{
    if (event.subtype == UIEventSubtypeRemoteControlNextTrack){
         [[AudioPlayer mainPlayer] testNext];
    }
    
}

//AudioPlayer
-(void)testNext
{
    
    NSArray *array = @[[NSURL URLWithString:@"spotify:track:3X7XBPN4EU6unqGTsxWafS"], [NSURL URLWithString:@"spotify:track:4SGaUTZcnagDqQNh7aq7Wv"], [NSURL URLWithString:@"spotify:track:0Y8QUKJTss7tG9s4j9mYiR"]];
 
    [self.audioStreamingController playURIs:array fromIndex:testIndex callback:^(NSError *error) {
        //called without an error   
        testIndex++;
        if (testIndex == [array count]) testIndex = 0;
        
    }];
}
```

**Comment by elmateo487** [comment]
It works. This in swift

    override func canBecomeFirstResponder() -> Bool {
        return true
    }
    
    override func viewDidAppear(animated: Bool) {
        super.viewDidAppear(animated)
        self.becomeFirstResponder()
        UIApplication.sharedApplication().beginReceivingRemoteControlEvents()
    }
    
    override func remoteControlReceivedWithEvent(event: UIEvent) {
        let rc = event.subtype
        println("received remote control \(rc.rawValue)") // 101 = pause, 100 = play
        switch rc {
        case .RemoteControlTogglePlayPause:
        case .RemoteControlPlay:
        case .RemoteControlPause:
        case .RemoteControlNextTrack:
        case .RemoteControlPreviousTrack:
        default:break
        }
        
    }

**Comment by bangerang** [comment]
Why is this closed? This is still a issue in the latest beta.

**Comment by bangerang** [comment]
Maybe this is a issue when you're using ```NSURL``` objects. I implemented the ```UIEventSubtypeRemoteControlNextTrack``` event in the demo project Simple Track Playback and it seems to work. I noticed that you're using ```SPTPlaylistTrack```and I'm using ```NSURL```objects.
