### ISSUE TITLE
Partial and Full Playlists desynchronisation (cache problem?)

### ISSUE THREAD

**Issue by bezigon** [spotify/ios-sdk#275]
Initially was a playlist called "test". I renamed them, removed/added some of tracks.
As a result:

```
2015-03-17 17-58-37.158 > INFO: PARTIAL OBJECT: <SPTPartialPlaylist: 0x17ead140>: test playlist [21 tracks] (spotify:user:bezigon:playlist:5LQv0DIVVWgwFCZynbac5p)
2015-03-17 17-58-37.355 > INFO: FULL OBJECT: <SPTPlaylistSnapshot: 0x17eec960>: cool playlist [14 tracks] (spotify:user:bezigon:playlist:5LQv0DIVVWgwFCZynbac5p)
```

I noticed on mess with a partial playlist.

PARTIAL OBJECT – old playlist, which returns from `[SPTRequest playlistsForUserInSession: callback: ];` as SPTListPage, comprising SPTPartialPlaylist.
FULL OBJECT –  playlist which received from the partial playlist through `[SPTRequest requestItemFromPartialObject: withSession: callback: ];` and it is the actual information on the playlist.

I restarted application and nothing was changed. Is there any mess with cache?

**Comment by possan** [comment]
There shouldn't be any caching happening, but there's also no synchronization happening, so if you request one playlist, update the name, you need to re-request it to get a playlist with that name set,

The SDK is only a wrapper on top of the Web API.
