### ISSUE TITLE
Warning: treating Unicode character as whitespace

### ISSUE THREAD

**Issue by kevin--** [spotify/ios-sdk#276]
Trivial bug, just a warning, but the SPTRequest.h header has a unicode character after the DEPRECATED_ATTRIBUTE macro apparently.

Spotify iOS SDK/Spotify.framework/Headers/SPTRequest.h:110:113: warning: treating Unicode character as whitespace [-Wunicode-whitespace]
+(void)starredListForUserInSession:(SPTSession *)session callback:(SPTRequestCallback)block DEPRECATED_ATTRIBUTE ;

**Comment by possan** [comment]
Closing this, this should be fixed now in the latest release.
