### ISSUE TITLE
Artist's "Appears On" returns same data as Albums

### ISSUE THREAD

**Issue by kevin--** [spotify/ios-sdk#277]
In SDK Beta 6 and 7, passing the "Appears On" enumeration value returns the same list of Albums. Anyone else experience this? SPTAlbumTypeSingle works correctly.

    [artist requestAlbumsOfType:SPTAlbumTypeAppearsOn withSession:session availableInTerritory:territory callback:^(NSError *error, id object)

**Comment by possan** [comment]
Closing this, this should be fixed now in the latest release.
