### ISSUE TITLE
Subscribing to a playlist?

### ISSUE THREAD

**Issue by fluidpixel** [spotify/ios-sdk#278]
Is it possible to subscribe to a (public) playlist? I can't see any mention of it in the library.

**Comment by psephos** [comment]
there is no method to interact with that endpoint in the sdk yet but you can call the web api directly to follow a playlist. See here: https://developer.spotify.com/web-api/console/put-playlist-followers/

**Comment by possan** [comment]
Closing this, this is now supported in the latest release.
