### ISSUE TITLE
tracksWithURIs causing unrecognised selector in SPTRequest internalRequestMultipleTracks

### ISSUE THREAD

**Issue by fluidpixel** [spotify/ios-sdk#280]
Trying to get the SPTTracks within a playlist from the tracks spotify uris using tracksWithURIs but getting an internal error:

2015-03-19 09:44:42.913[4022:1128455] -[__NSCFString absoluteString]: unrecognized selector sent to instance 0x163c6360
2015-03-19 09:44:47.920[4022:1128455] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFString absoluteString]: unrecognized selector sent to instance 0x163c6360’

from here:#12	0x0021479c in __65+[SPTRequest internalRequestMultipleTracks:withSession:callback:]_block_invoke at /Users/spotify-buildagent/buildAgent/work/f0512cb09316daec/src/SPTRequest.m:269

Here’s my uri array if that helps?
<__NSArrayM 0x163cd2a0>(
spotify:track:60U5CqVUhItO9GqvHJdRo5,
spotify:track:6nF4Jorqzz1mWdhMfIKjJC,
spotify:track:5y7PX6C3Ip0XYWLecLoXJX,
spotify:track:5LFrKp3MLJZYSNZ3sXarQE,
spotify:track:3EfkjtCBWI5NvnVr3Z6Z6i,
spotify:track:5mas3ZpaFic7C1539BR5Jc,
spotify:track:3lqGdZynVJY8DEfy8BM3Po,
spotify:track:2LdalId0Kzql1gGdfWaMuZ,
spotify:track:1x1mnLRtBm2sdxvZ4jd3Oi,
spotify:track:23QFrOIyd6jV4hTIhpYBUg,
spotify:track:6NmmNODhIunEGvGvoeyzCw,
spotify:track:2GNevYtLQ0R9ioyi6qu32R,
spotify:track:4lxunSFYkcTdsbxwg2Vpzx,
spotify:track:7MhAeb3LfzpeJ9PuxwzTP5,
spotify:track:3woFJVw7kvDXozgAvqE2Km,
spotify:track:55ctqy5NuRuna7nm7OZRZn,
spotify:track:2n7qMCUkmdhnhj91kBEeFs,
spotify:track:41SOLgNAkxzFc9w163uSBI,
spotify:track:7paBisHTti7mSXJ30s4e98,
spotify:track:3t2ZHBoLUYvvaMpOvXfdML,
spotify:track:3GeWplBM2xohYo3rr6Ix5L,
spotify:track:5aiqPKCzYfdG8Ax15R8i2o,
spotify:track:62wfOkPbflGG2qMX1GwFQK,
spotify:track:4DGoangzSwbEpjXAdhAs68,
spotify:track:1OMAFXeXtPQUp6dnkxu2GS,
spotify:track:67q0MHGrff19GYsPxd59Ij,
spotify:track:5OzQhp82bwBWHPvJXsyu5X,
spotify:track:21qIhtW714ASJy3cSd3KU7,
spotify:track:5UmI6dBAUAOLzwN71y413P,
spotify:track:0DcaRT6WRwhLSkJzgcFdr5,
spotify:track:2IrEAajhb9Uy1gD7wkdOxj,
spotify:track:2mCLc4lZjbpcpXgNBrC5lY,
spotify:track:3hY57ozXkune3iiy52O6kJ,
spotify:track:6dxFkdo1QNxM3Bpu2WqaXH,
spotify:track:0rypbrM6HuzbuqvCzfxH3O,
spotify:track:0LnGmMMWW6lOKljOUatPeB,
spotify:track:6zr4j7bKQn23RWHmFkm3vp,
spotify:track:0mqm2Qs5dvzpYXc5YvZHe4,
spotify:track:4IWqC9tZ2u9r8u9FiaxKm5
)

**Comment by possan** [comment]
Closing this, this should be fixed now in the latest release.
