### ISSUE TITLE
Shuffle bool state not updating

### ISSUE THREAD

**Issue by elmateo487** [spotify/ios-sdk#283]
When you playURIs and set the player to shuffled (a bool of true), then play a new set of URIs, the bool in player.shuffle is set to true, but the player is actually not playing the set of URIs shuffled. So you have to set the player shuffle to true again, and it will shuffle again. It seems that if playing a new set of URIs is going to reset the shuffle state, it should also reset that boolean.

**Comment by possan** [comment]
This should be fixed in the latest beta.
