### ISSUE TITLE
playlistsForUserInSession fails for username with special characters

### ISSUE THREAD

**Issue by johra** [spotify/ios-sdk#284]
From what I can tell, users with username containing åäö seems unable to retrieve playlists using playlistsForUserInSession.

*** Playlist lookup got error Error Domain=NSURLErrorDomain Code=-1002 "unsupported URL" UserInfo=0x14ed2d80 {NSUnderlyingError=0x14ed4b20 "unsupported URL", NSLocalizedDescription=unsupported URL}

playlistsForUser works fine though.

**Comment by Anders27** [comment]
This explains why some of my Swedish users couldn't get Spotify to work.
Creating a new Spotify account without "åäö" in the username solved the problem.
So yes, this must be a bug.

**Comment by possan** [comment]
Closing this, this should be fixed now in the latest release.
