### ISSUE TITLE
SDK sound levels different to Spotify player

### ISSUE THREAD

**Issue by johra** [spotify/ios-sdk#285]
I have a feeling the sound levels are much different when playing with SDK to from inside Spotify. Is there some magic sound normalisation being done there? Is there some way we can get this in SDK as well? Volume info per track to set the volume ourselves?

**Comment by possan** [comment]
The real Spotify client might use a different replay gain than the SDK does, that is probably what you are hearing.

This is not a planned feature right now but we'll add it to our backlog.
