### ISSUE TITLE
'SPTAuth' does not have a member named 'loginURLForClientId'

### ISSUE THREAD

**Issue by jamesavaughn** [spotify/ios-sdk#286]
I'm working on the basic tutorial and having trouble authenticating my app.  I'm working in Swift and have my environment all set up. 

code...
 let loginURL = auth.loginURLForClientId(kClientID, declaredRedirectURL: NSURL(string: kCallbackURL), scopes: [SPTAuthStreamingScope])
       
I'm getting this error:
error...
'SPTAuth' does not have a member named 'loginURLForClientId'

**Comment by jarrodrobins** [comment]
Yeah, I noticed that with the latest beta too - the API's been changed. Check out the demo projects in this Git repo for the updated usage. SimpleTrackPlayback looks the clearest to me.

**Comment by emmanuelcu** [comment]
The same is happening to me. I opened the library "loginURL" and the variables are declared but the method is not active.

/**
 Returns a URL that, when opened, will begin the Spotify authentication process.

 @warning You must open this URL with the system handler to have the auth process
 happen in Safari. Displaying this inside your application is against the Spotify ToS.

 @param clientId Your client ID as declared in the Spotify Developer Centre.
 @param redirectURL Your callback URL as declared in the Spotify Developer Centre.
 @param scopes The custom scopes to request from the auth API.
 @param responseType Authentication response code type, defaults to "code", use "token" if you want to bounce directly to the app without refresh tokens.
 @return The URL to pass to `UIApplication`'s `-openURL:` method.
 */
+(NSURL *)loginURLForClientId:(NSString *)clientId withRedirectURL:(NSURL *)redirectURL scopes:(NSArray *)scopes responseType:(NSString *)responseType;
