### ISSUE TITLE
Crash on SPTPlaylistSnapshot initWithDecodedJSONObject

### ISSUE THREAD

**Issue by Kry256** [spotify/ios-sdk#288]
I've experienced crashes that for certain playlists after the call of
**+(void)playlistWithURI:(NSURL *)uri session:(SPTSession *)session callback:(SPTRequestCallback)block;**
method.
This no happens for particular playlists, but it seems happens quite randomly.
Here is the crashlog

**Fatal Exception: NSInvalidArgumentException
-[NSNull longValue]: unrecognized selector sent to instance 0x382c3690**

*SPTPlaylistSnapshot.m line 147
-[SPTPlaylistSnapshot initWithDecodedJSONObject:error:]
SPTJSONDecoding.m line 91
+[SPTJSONDecoding SPObjectFromDecodedJSON:collection:error:]
SPTJSONDecoding.m line 50
+[SPTJSONDecoding SPObjectFromDecodedJSON:error:]
SPTRequest.m line 653
__56+[SPTRequest requestPlaylistAtURI:withSession:callback:]_block_invoke*

**Comment by whittlbc** [comment]
Me as well. Having same problem that comes and goes by the day. Exactly the same crashlog, too.

**Comment by fishkingsin** [comment]
same here +1

**Comment by piotrbernad** [comment]
+1

**Comment by Snppls** [comment]
+1
One playlist where this occurs every time for me is this one: spotify:user:spotify:playlist:06CemleTteSalaVGVMbgFy

**Comment by Muesly** [comment]
Me too +1

**Comment by eparis-bit** [comment]
In the beta6 the crash happens at:

SPTPlaylistSnapshot.m line 146
-[SPTPlaylistSnapshot initWithDecodedJSONObject:error:]
SPTJSONDecoding.m line 96
+[SPTJSONDecoding SPObjectFromDecodedJSON:collection:error:]
SPTJSONDecoding.m line 55
+[SPTJSONDecoding SPObjectFromDecodedJSON:error:]
SPTRequest.m line 613
__56+[SPTRequest requestPlaylistAtURI:withSession:callback:]_block_invoke

**Comment by Snppls** [comment]
Unfortunately I couldn't wait for the next beta to fix this so I (temporarily) avoided the issue by creating a category on NSNull to add the conversion methods (stringValue, integerValue, floatValue, longValue, boolValue, ...), that the Spotify SDK is calling while parsing JSON.
Not a clean solution by any means but at this point it's better than putting a randomly crashing application in the app store. I hope this issue is fixed soon.

**Comment by fishkingsin** [comment]
@Snppls could you share your code with us?
thanks

**Comment by piotrbernad** [comment]
I did the same thing as @Snppls. I confirm that it works, but this is ugly solution, and spotify should fix it asap.

**Comment by Snppls** [comment]
@fishkingsin sure
I wouldn't recommend using this any longer than you have to though.

http://pastebin.com/HLDCsPwU

**Comment by fishkingsin** [comment]
thanks @Snppls 
surely remark as temporary fix until spotify fix it

**Comment by possan** [comment]
Closing this, this should be fixed now in the latest release.

**Comment by matijse** [comment]
I am seeing this bug again at: 

```
[SPTPlaylistSnapshot playlistWithURI:uri session:auth.session callback:^(NSError *error, id object) {

}];
```

But only on the playlist "Today's Top Hits" from the `toplists` category. (`uri` = `spotify:user:spotify:playlist:5FJXhjdILmRA2z5bvz4nzf`)

Stack trace:

```
#4	0x0026eb9c in -[SPTPlaylistSnapshot initWithDecodedJSONObject:error:] at /Users/ceciliahumlelu/ios-sdk/src/SPTPlaylistSnapshot.m:78
#5	0x0026ecb2 in +[SPTPlaylistSnapshot playlistSnapshotFromDecodedJSON:error:] at /Users/ceciliahumlelu/ios-sdk/src/SPTPlaylistSnapshot.m:102
#6	0x0026ec46 in +[SPTPlaylistSnapshot playlistSnapshotFromData:withResponse:error:] at /Users/ceciliahumlelu/ios-sdk/src/SPTPlaylistSnapshot.m:96
#7	0x0026f31a in __60+[SPTPlaylistSnapshot playlistWithURI:accessToken:callback:]_block_invoke93 at /Users/ceciliahumlelu/ios-sdk/src/SPTPlaylistSnapshot.m:166
```

Error:
 `-[NSNull longValue]: unrecognized selector sent to instance 0x3958ca70`
