### ISSUE TITLE
Modify the SPTAuthViewController

### ISSUE THREAD

**Issue by ahallora** [spotify/ios-sdk#290]
How can I modify the appearance of the authentication box - e.g.
- change/move the big black closing-button
- resize the window
- enable/disable facebook login
  ?

**Comment by 909kishore** [comment]
+1 

A) Users don't realize they have to scroll down (the most prominent call-to-action is exit)
B) The login and cancel buttons don't look right.

![onboarding spotify 1](https://cloud.githubusercontent.com/assets/6827699/7840432/50585282-0465-11e5-99db-3c8a11ec84c6.png)
![onboarding spotify 2](https://cloud.githubusercontent.com/assets/6827699/7840439/54bc50a8-0465-11e5-9888-acbc352072d2.png)

**Comment by msgilligan** [comment]
+1 We're having the same problem.

**Comment by chrismazzeo** [comment]
Same here

**Comment by skiddle** [comment]
+1

**Comment by skiddle** [comment]
In our testing we've noticed  a large percentage of users don't proceed past login, presumably because the "Okay" button is hidden and you have to scroll down (with no indication that you need to do this)

**Comment by erdtman** [comment]
There has been an update to the approval dialog to be more compact, please have a look to see if it solves some of the inconvenience.

**Comment by bensebborn** [comment]
On the permissions page, it's more compact now - and the Okay button shows

It seems the page has been scrolled down to view the button, rather than everything fitting on (as the logo at the top is cut off) so as long as that's deliberate behaviour and won't revert back to needing to scroll then it's an OK workaround

**Comment by DmytroAnkudinov** [comment]
SPTAuthViewController has been deprecated in Beta25 and should not be used anymore, as it will be removed in the subsequent releases. Please use SFSafariViewController instead.
