### ISSUE TITLE
Cannot fetch playlists for usernames with ä or ö

### ISSUE THREAD

**Issue by kevin--** [spotify/ios-sdk#292]
Authentication, Search, Playback and fetching the saved tracks for these users all work, but when doing SPTRequest playlistsForUserInSession:, the error returned to the callback is

Error Domain=NSURLErrorDomain Code=-1000 "bad URL" UserInfo=0x15ed8940 {NSUnderlyingError=0x15e79530 "bad URL", NSLocalizedDescription=bad URL}

Seems other special characters may trigger this behavior as well (åäö). The user first reporting this to us was in Swedish locale

**Comment by possan** [comment]
Closing this, this should be fixed now in the latest release.
