### ISSUE TITLE
App crashes due to EXC_BAD_ACCESS (SIGSEGV), when a track is playing and user press back button.

### ISSUE THREAD

**Issue by rajaarun** [spotify/ios-sdk#293]
Exception Type:  EXC_BAD_ACCESS (SIGSEGV)
Exception Subtype: KERN_INVALID_ADDRESS at 0x00000010
Triggered by Thread:  10

Thread 0 name:  Main thread  Dispatch queue: com.apple.main-thread
Thread 0:
0   libsystem_kernel.dylib        	0x34ecab2c __psynch_cvwait + 24
1   libsystem_pthread.dylib       	0x34f473be _pthread_cond_wait + 574
2   libsystem_pthread.dylib       	0x34f47178 pthread_cond_timedwait_relative_np + 12
3   Foundation                    	0x2761836a -[NSCondition waitUntilDate:] + 282
4   Foundation                    	0x2761588c -[NSConditionLock lockWhenCondition:beforeDate:] + 204
5   APPNAME                    	0x003c1e0a +[SPTAudioStreamingController dispatchToAudioThread:waitUntilDone:] (SPTAudioStreamingController.m:1247)
6   APPNAME                    	0x003bc842 -[SPTAudioStreamingController initWithClientId:audioController:] (SPTAudioStreamingController.m:193)
7   APPNAME                    	0x001b72fc -[MyViewController initPlayer] (MyViewController.m:51)
8   APPNAME                    	0x001b714c -[MyViewController viewDidLoad] (MyViewController.m:33)
9   UIKit                         	0x29ebb2fe -[UIViewController loadViewIfRequired] + 598
10  UIKit                         	0x29ebb06c -[UIViewController view] + 20
11  UIKit                         	0x2a044440 -[UINavigationController _startCustomTransition:] + 624
12  UIKit                         	0x29f64022 -[UINavigationController _startDeferredTransitionIfNeeded:] + 418
13  UIKit                         	0x29f63e28 -[UINavigationController __viewWillLayoutSubviews] + 40
14  UIKit                         	0x29f63dbc -[UILayoutContainerView layoutSubviews] + 180
15  UIKit                         	0x29eb87fa -[UIView(CALayerDelegate) layoutSublayersOfLayer:] + 510
16  QuartzCore                    	0x298de830 -[CALayer layoutSublayers] + 132
17  QuartzCore                    	0x298da208 CA::Layer::layout_if_needed(CA::Transaction*) + 356
18  QuartzCore                    	0x298da090 CA::Layer::layout_and_display_if_needed(CA::Transaction*) + 12
19  QuartzCore                    	0x298d9a6c CA::Context::commit_transaction(CA::Transaction*) + 220
20  QuartzCore                    	0x298d9870 CA::Transaction::commit() + 320
21  QuartzCore                    	0x298d3748 CA::Transaction::observer_callback(__CFRunLoopObserver*, unsigned long, void*) + 52
22  CoreFoundation                	0x26964ffa __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 18
23  CoreFoundation                	0x269626b6 __CFRunLoopDoObservers + 274
24  CoreFoundation                	0x26962abe __CFRunLoopRun + 910
25  CoreFoundation                	0x268b03ac CFRunLoopRunSpecific + 472
26  CoreFoundation                	0x268b01be CFRunLoopRunInMode + 102
27  GraphicsServices              	0x2dedd1fc GSEventRunModal + 132
28  UIKit                         	0x29f1a438 UIApplicationMain + 1436
29  APPNAME                    	0x0003b3ec main (main.m:16)
30  libdyld.dylib                 	0x34e00aac start + 0

**Comment by possan** [comment]
Did you find a solution to this?

**Comment by rajaarun** [comment]
Yes, My application was crashing because it receives the callback by SPTAudioStreamingController, so I have created the object of SPTAudioStreamingController in AppDelegate.
