### ISSUE TITLE
Connection refused after trying to reconnect when app becomes active again

### ISSUE THREAD

**Issue by datinc** [spotify/ios-sdk#293]
Steps to reproduce
* Connect to Spotify as described in the quick start guide
* Minimize app
* Disconnect from Spotify (`appRemote.disconnect()`) when app minimizes (`applicationWillResignActive`)
* Wait some time
* Reopen application
* Reconect to Spotify (`appRemote.connect()`) when app becomes active (`applicationDidBecomeActive `)

Expected Result
* Application reconnects to Spotify

Actual Result
* Recive call back on `func appRemote(_ appRemote: SPTAppRemote, didDisconnectWithError error: Error?)` with error 

```
Error Domain=com.spotify.app-remote Code=-1002 "Connection terminated." UserInfo={NSLocalizedDescription=Connection terminated., NSUnderlyingError=0x2801d4e70 {Error Domain=com.spotify.app-remote.transport Code=-2000 "Stream error." UserInfo={NSLocalizedDescription=Stream error., NSUnderlyingError=0x2801d5c80 {Error Domain=NSPOSIXErrorDomain Code=57 "Socket is not connected" UserInfo={_kCFStreamErrorCodeKey=57, _kCFStreamErrorDomainKey=1}}, NSLocalizedRecoverySuggestion=Reconnect the transport to the Spotify app., NSLocalizedFailureReason=A stream error has occured in the transport.}}, NSLocalizedRecoverySuggestion=Try to reconnect., NSLocalizedFailureReason=The Spotify app might have been suspended.}
```

**Comment by datinc** [comment]
Deleting as this is intended. We need to implement the refresh token as described here
https://developer.spotify.com/documentation/ios/guides/token-swap-and-refresh/

**Comment by hethcox** [comment]
Hi @datinc. Are you saying that you did a token refresh and then used that to reconnect to the Spotify app?  

I'm getting the -1002 error (which is fine) but I can't reconnect to Spotify after that.
