### ISSUE TITLE
STPListPage.items in nil

### ISSUE THREAD

**Issue by aivanov93** [spotify/ios-sdk#294]
Hi I'm trying to extract the artists from the the user starred songs. I understand that starredListForUserInSession returns a PlaylistSnapshot. That has a firstTrackPage attribute that's a SPTListPage.

In my test when printing out the SPTListPage, it says the list has 8 items. When I try to get the items in the ListPage with ListPage.items it returning nil. I'm not sure what's wrong. Am I calling the wrong property?

```
func retrieveStarred() -> Void {
    SPTRequest.starredListForUserInSession(self.session, callback: { (error:NSError!, starred: AnyObject!) -> Void in
        if error != nil {
            println("error retrieving starred playlist")
        } else {
            self.starred = starred as SPTPlaylistSnapshot
            self.scrapePlaylist(self.starred)
        }
    })
}
func scrapePlaylist(playlist: SPTPlaylistSnapshot) -> Void {
    println(playlist);
    var firstTracks = playlist.firstTrackPage
    println(firstTracks)
    println(firstTracks.hasNextPage)
    var songs = firstTracks as SPTListPage
    println(songs.items)
    for song in songs.items {
        var track = song as SPTPartialTrack
        for artist in track.artists {
            updateSongsCount(artist as SPTPartialArtist)
        }
    }
}
```
The same problem holds for any playlist

**Comment by timsk159** [comment]
I'm having the same problem.

NSLog(@"%@", _playlistPager);
Prints:
<SPTPlaylistSnapshot: 0x17f35450>: Jay Z – Watch The Throne [16 tracks] 

NSLog(@"%@", [_playlistPager.firstTrackPage.items objectAtIndex:0]);
prints:
(null)


I even tried:
    [SPTPlaylistSnapshot playlistWithURI:pager.uri session: [SPTAuth defaultInstance].session callback:^(NSError *error, id object)
    {
        SPTPlaylistSnapshot *snapshot = (SPTPlaylistSnapshot*)object;
        NSLog(@"First track from page: %@", [snapshot.firstTrackPage.items objectAtIndex:0]);
    }];

But it still prints null!

Are we doing something wrong? Or is there an issue in the SDK?

**Comment by timsk159** [comment]
Right, I managed to solve this. After spending nearly all day on it.

This seems to be fixed by adding the -ObjC linker flag as described [here](https://developer.apple.com/library/mac/qa/qa1490/_index.html)

It would really be nice to get some sort of error with this... it was just failing silently and filling our objects (mostly) with nil.

Btw, be sure to check the "Troubleshooting" bit of the page I linked. I had to add the flag to both my target AND my project before it would work.

**Comment by aivanov93** [comment]
oh nice! will try that, thanks

**Comment by possan** [comment]
It's also noted in the tutorial and the github readme, i'm closing this.

**Comment by djaygit** [comment]
It doesn't work If I use few other SDKs along with Spotify?
