### ISSUE TITLE
Unplayable tracks

### ISSUE THREAD

**Issue by sgoodwin** [spotify/ios-sdk#295]
In our app, we try to use a user's spotify playlists. The SPTPlaylistSnapshot objects the SDK gives report a track count of over 100 for many of our test accounts. However, due to licensing in countries or whatever reason, most of those tracks are not playable by the API (they do not have a playableUri).

Could you make each playlist's track count represent the number of playable tracks instead of the raw number of tracks? It makes for a terrible experience when a user picks a playlist and we are unable to play a song because the tracks are unplayable. Currently, there is no way to discover this without requesting the SPTPlaylistSnapshot from each SPTPartialPlaylist individually. When a user has 100 playlists, that's a bad way for us to go.

**Comment by possan** [comment]
Currently there is no other way then to do the filtering of unavailable tracks in the app itself, the underlying api will not filter based on availability, but if you pass the users' market along with the playlist request the backend will try to replace unavailable tracks with available ones.

**Comment by sgoodwin** [comment]
Oh ok, how do I do that?

**Comment by possan** [comment]
You can use `+(void)requestItemAtURI:(NSURL *)uri withSession:(SPTSession *)session market:(NSString *)market callback:(SPTRequestCallback)block;` in `SPTRequest` to pass market with your request.

**Comment by sgoodwin** [comment]
Tried using this method, feeding different things in for market, all still give me a playlist with 100 unplayable items on it. including using SPTMarketFromToken. Am I doing something wrong?

**Comment by jacksonh** [comment]
I'm using Runscope with my app to inspect request/responses, and it looks like ```+(void)requestItemAtURI:(NSURL *)uri withSession:(SPTSession *)session market:(NSString *)market callback:(SPTRequestCallback)block;``` is not respecting the ```market``` argument. Here is an invocation and the request URI:

    [SPTRequest requestItemAtURI:spotifyID withSession:[SPTAuth defaultInstance].session market:SPTMarketFromToken callback:^(NSError *error, id object)
yields:

    /v1/tracks/0utGheyKNmigz7gMgJRDzm?uri=spotify%3Atrack%3A0utGheyKNmigz7gMgJRDzm

and same thing if I hard code @"US" as the market:

    GET /v1/tracks/0870QNicMawQH2cnzBVZ3P?uri=spotify%3Atrack%3A0870QNicMawQH2cnzBVZ3P

**Comment by sgoodwin** [comment]
That would explain why I'm still getting unplayable tracks!

**Comment by possan** [comment]
Closing this, this should be fixed now in the latest release.
