### ISSUE TITLE
Crash in SPTPartialTrack initWithDecodedJSONObject:error:

### ISSUE THREAD

**Issue by eparis-bit** [spotify/ios-sdk#296]
With the beta6, Crashlytics reports me a couple hundred of crashes like this:

Fatal Exception: NSInvalidArgumentException
-[NSNull objectForKeyedSubscript:]: unrecognized selector sent to instance 0x195afbba0

Call stack:

SPTPartialTrack.m line 67
-[SPTPartialTrack initWithDecodedJSONObject:error:]
SPTTrack.m line 76
-[SPTTrack initWithDecodedJSONObject:error:]
SPTSavedTrack.m line 43
-[SPTSavedTrack initWithDecodedJSONObject:error:]
SPTJSONDecoding.m line 96
+[SPTJSONDecoding SPObjectFromDecodedJSON:collection:error:]
SPTListPage.m line 86
-[SPTListPage initWithDecodedJSONObject:expectingPartialChildren:rootObjectKey:]
SPTListPage.m line 177
__49-[SPTListPage requestPageAtURL:session:callback:]_block_invoke

**Comment by possan** [comment]
Closing this, this should be fixed now in the latest release.
