### ISSUE TITLE
Cannot delete playlists

### ISSUE THREAD

**Issue by mhuusko5** [spotify/ios-sdk#299]
Would like to be able to delete playlists (that the current user owns) as well as create them.

**Comment by possan** [comment]
We have currently not exposed that functionality in our web api, and until that is in place we can't add that functionality in the sdk either.

**Comment by erdtman** [comment]
We are deprecating the iOS-Metadata library.

The source code of the iOS-Metadata library has been released and can be found [here](https://github.com/erdtman/spotify-ios-metadata/). Spotify will not continue to maintain the released source code.

Either you can select to use the web-api directly or use the new open source iOS-Metadata library.

I will close this issue now.

We are sorry for the inconvenience that this creates, but looking back we think this is the best path forward.
