### ISSUE TITLE
Possible to auth without backend token swap?

### ISSUE THREAD

**Issue by jscalo** [spotify/ios-sdk#30]
This first iteration of my app is just a prototype and I'm hoping I don't need to bring up server infrastructure to support it at this stage. Is it possible to authenticate with `SPTSessionManager` _without_ setting `tokenSwapURL` and `tokenRefreshURL`? I tried but it fails with "invalid_request".

If it matters I was previously able to auth with the older "streaming" framework.

**Comment by jscalo** [comment]
Following up… by all indications the app _should_ be able to authenticate without the `tokenSwapURL` and `tokenRefreshURL` endpoints and get an access token that expires in an hour. And it seems like it almost works— if I break in `application(_, open url, options)` and peek at the incoming URL, it appears to have a valid access code:

```
myapp-spt://?code=AQCjw-6KFlBA532RvD1XrBbTwcgoZSQjCF0bSi2_ihDQuHBLAHBLAH
```

The problem is that afterward the call to `sessionManager.application(app, open: url, options: options)` for some reason is generating a `sessionManager(didFailWith)` error on the delegate. I've triple checked that my app's callback URI on the dashboard matches what's in the app and Info.plist (and they were working with the older framework).

The exact same thing happens in the Obj-C sample app if I comment out the lines that set the `tokenSwapURL` and `tokenRefreshURL`.

**Comment by weswes** [comment]
You should use "the built-in app-remote-control Authorization flow" to avoid using tokenSwapURL and tokenRefreshURL and get an one hour access token.
Do not use STPSessionManager. Just STPAppRemote:
```
SPTConfiguration *configuration =
    [[SPTConfiguration alloc] initWithClientID:@"your_client_id" redirectURL:[NSURL urlWithString:@"your_redirect_uri"]];
self.appRemote = 
    [[SPTAppRemote alloc] initWithConfiguration:configuration logLevel:SPTAppRemoteLogLevelDebug];
BOOL spotifyInstalled = [self.appRemote authorizeAndPlayURI:@""]; // blank URI plays the last user song
```
Configure your AppDelegate to parse out the accessToken in application:openURL:options: and set it on the SPTAppRemote connectionParameters.
```
- (BOOL)application:(UIApplication *)app openURL:(NSURL *)url options:(NSDictionary<UIApplicationOpenURLOptionsKey,id> *)options
{
    NSDictionary *params = [self.appRemote authorizationParametersFromURL:url];
    NSString *token = params[SPTAppRemoteAccessTokenKey];
    if (token) {
        self.appRemote.connectionParameters.accessToken = token;
    } else if (params[SPTAppRemoteErrorDescriptionKey]) {
        NSLog(@"%@", params[SPTAppRemoteErrorDescriptionKey]);
    }
    return YES;
}
```

**Comment by jackfreeman** [comment]
@jscalo, @weswes is correct. You do not need a backend server if you using the `the built-in app-remote-control Authorization flow` on `SPTAppRemote`. 

If you need any additional scopes you will need to set up a backend server to perform the token swap.

**Comment by jscalo** [comment]
Thanks @jackfreeman and @weswes, I'll give it a shot. Mind pointing me to where this is documented? I don't see it in any of the [iOS guides](url
https://developer.spotify.com/documentation/ios/guides/) or the [Authorization guide](https://developer.spotify.com/documentation/general/guides/authorization-guide/).

**Comment by jackfreeman** [comment]
https://github.com/spotify/ios-sdk#using-the-built-in-app-remote-control-authorization-flow-recommended

**Comment by jscalo** [comment]
Thanks @jackfreeman. One last question— the server flow can take a configuration with a nil playURI so that no audio plays after authentication. However in this flow the only way to start the auth process is with `authorizeAndPlayURI` which takes a non-nil URI, so that audio *always* plays after authenticating. Is there any way to prevent that?

**Comment by jackfreeman** [comment]
@jscalo Unfortunately the only way to auth without playing music is by using `SPTSessionManager` and setting up your own backend to handle the token swap.

**Comment by jscalo** [comment]
Weird. OK. Sending a bogus URI won't have the same effect?

**Comment by nicoletapop** [comment]
When the given access token through appDelegate openURL method by the built-in authorization expires, what can we do? Do we receive a new access token when calling appRemote.connect()? Or only when we call authorizeAndPlayURI?
