### ISSUE TITLE
support for folders

### ISSUE THREAD

**Issue by ericlewis** [spotify/ios-sdk#30]
not sure if intended, but would be interested to know.

**Comment by timidri** [comment]
Is there news about supporting folders? If folders are not intended to be supported, does this mean the Spotify client itself will not use this SDK but use CocoaLibSpotify or something proprietary instead?

**Comment by iGranDav** [comment]
I am interested about folder support also.

**Comment by erdtman** [comment]
We are deprecating the iOS-Metadata library.

The source code of the iOS-Metadata library has been released and can be found [here](https://github.com/erdtman/spotify-ios-metadata/). Spotify will not continue to maintain the released source code.

Either you can select to use the web-api directly or use the new open source iOS-Metadata library.

I will close this issue now.

We are sorry for the inconvenience that this creates, but looking back we think this is the best path forward.
