### ISSUE TITLE
Allow access to users' followers and add follow/unfollow functionality

### ISSUE THREAD

**Issue by 14lox** [spotify/ios-sdk#300]
Any plans to add the endpoints to `/v1/me/following` and `/v1/me/following/contains` ?

**Comment by jasperblues** [comment]
+1 This would certainly provide some more interesting possibilities.

**Comment by erdtman** [comment]
We are deprecating the iOS-Metadata library.

The source code of the iOS-Metadata library has been released and can be found [here](https://github.com/erdtman/spotify-ios-metadata/). Spotify will not continue to maintain the released source code.

Either you can select to use the web-api directly or use the new open source iOS-Metadata library.

I will close this issue now.

We are sorry for the inconvenience that this creates, but looking back we think this is the best path forward.
