### ISSUE TITLE
SPTAudioStreamingController.playTrackProvider is unavailable

### ISSUE THREAD

**Issue by HombreDeGatos** [spotify/ios-sdk#301]
I have been using SDK 7 and been modeling the Simple Track Playback Demo project to implement track playing in my own swift app.

However, when I try and get the SPTAudioStreamingController to play a song by using playTrackProvider, XCode says it is unavailable.

        func handleNewSession() {
        let auth = SPTAuth.defaultInstance()
        
        if (self.player == nil) {
            self.player = SPTAudioStreamingController(clientId: auth.clientID)
            self.player!.playbackDelegate = self;
            self.player!.diskCache = SPTDiskCache(capacity: 1024 * 1024 * 64)
        }
        
        self.player?.loginWithSession(auth.session, callback: { (error : NSError?) -> () in
            if (error != nil) {
                NSLog("*** Enabaling playback got error: \(error)")
                return
            }
            
            self.updateUI()
            
            SPTRequest.requestItemAtURI(NSURL(string: "spotify:album:4L1HDyfdGIkACuygktO7T7"), withSession: auth.session, callback: { (error : NSError!, albumObject : AnyObject!) -> Void in
                if (error != nil) {
                    NSLog("Album Lookup got error \(error)")
                    return
                }
                let album = albumObject as SPTAlbum
                
                self.player?.playTrackProvider(album, callback: nil)
                
            })
        })
    }

Since many SPTAudioStreamingControllers methods are deprecated, what is the correct way to go about playing tracks now?

**Comment by possan** [comment]
The recommended way is to only play lists of track uri's using `playURIs` and then maintaining that list using `replaceURIs`, but the example you provided should work in beta 7.
