### ISSUE TITLE
Causes Apple Silicon Simulator builds to fail

### ISSUE THREAD

**Issue by mredig** [spotify/ios-sdk#302]
When linking against the framework in Xcode on an Apple Silicon Mac, there's a build error because the framework only includes x86 simulator binaries.

```
ld: in /Users/.../SpotifyiOS.framework/SpotifyiOS(MPMessagePackReader.o), building for iOS Simulator, but linking in object file built for iOS, file '/Users/.../SpotifyiOS.framework/SpotifyiOS' for architecture arm64
```

**Comment by bogo** [comment]
I came across the same issue recently. Turns out that with enough elbow grease, you can make it work despite the missing Simulator slice. Explanation of the process here: https://bogo.wtf/arm64-to-sim.html.

**Comment by danielgronlund** [comment]
Closing this issue as we now have an official XCFramework build available. https://github.com/spotify/ios-sdk/tree/master/SpotifyiOS.xcframework

**Comment by danyf90** [comment]
Is there any reason why there isn't an official release (e.g. a tag) with that change?
Would be much easier to reference on which version of the SDK we depend on, especially if paired with [SPM support](https://github.com/spotify/ios-sdk/pull/344)
