### ISSUE TITLE
SPTAuthViewController needs work

### ISSUE THREAD

**Issue by ahallora** [spotify/ios-sdk#302]
I'm having some issues with the SPTAuthViewController.

When connecting to Spotify with the SPTAuthViewController the login prompt comes up; I enter my spotify credentials and on the next screen I need to confirm that my app will get access to read public information and bla bla bla... It's all good. But now, if I press "Cancel", to go back and e.g. log in with another spotify account, I can't and the screen freezes until the timeout is handled with the error:

> *** Failed to log in: Error Domain=com.spotify.auth Code=0 "access_denied" UserInfo=0x14ebd440 {NSLocalizedDescription=access_denied}

I'm actually starting to prefer my own UIWebView workaround before the SPTAuthViewController was introduced...

**Comment by possan** [comment]
Closing this, this should be fixed now in the latest release.
