### ISSUE TITLE
Can't handle Spotify Family subscriptions

### ISSUE THREAD

**Issue by ahallora** [spotify/ios-sdk#303]
When logging in with a Spotify Family subscription (which is a Premium subscription with 50% off https://www.spotify.com/family - but still a premium user) the SPTUser product is not matched with the SPTProductPremium enum:
```objective-c
[SPTRequest userInformationForUserInSession:auth.session callback:^(NSError *error, SPTUser *user) {
    if(user.product != SPTProductPremium) {
        NSLog(@"User does not have premium spotify subscription");
    }
}];
```

When ignoring the validation of the users subscription and try forcing playback the log shows:
> *** Enabling playback got error: Error Domain=com.spotify.ios-sdk.playback Code=9 "The operation requires a Spotify Premium account." UserInfo=0x1561fb20 {NSLocalizedDescription=The operation requires a Spotify Premium account.}

The documentation on SPTUser regarding product is sparse too: 
https://developer.spotify.com/ios-sdk-docs/Documents/Classes/SPTUser.html#//api/name/product

**Comment by possan** [comment]
Interesting, it IS supposed to return premium, do you have a username i can use to test this?

**Comment by ahallora** [comment]
![image](https://cloud.githubusercontent.com/assets/5302751/7064437/f17451d4-deae-11e4-87b3-c34eb2c73fed.png)

**Comment by possan** [comment]
Weird, did you specify the user-read-private scope when creating the session? otherwise it won't give you the product value.

**Comment by ahallora** [comment]
My code which actually do serve the product value with a "normal" spotify Premium account but fails with Spotify Family Premium account:
```objective-c
SPTAuth *auth = [SPTAuth defaultInstance];
auth.clientID = config_kClientId;
auth.requestedScopes = @[SPTAuthStreamingScope, SPTAuthPlaylistReadPrivateScope, SPTAuthPlaylistModifyPrivateScope];
```

By adding `SPTAuthUserReadPrivateScope` to the scope the problem goes away. Thanks for clearing that out for me. :smiley: Cheers.

**Comment by jaronheard** [comment]
This issue still impacts Spotify family users, but only the "master" account. At least in my instance. Here are the two usernames: 12101371561 (master), t9portland.

**Comment by zakmandhro** [comment]
@jaronheard, I see the issue is closed but did you resolve this potential issue of SPTProductUnkown on family account?
