### ISSUE TITLE
SPTTrack.album is null when performing a search.

### ISSUE THREAD

**Issue by timsk159** [spotify/ios-sdk#304]
When performing a search using:

`[SPTRequest performSearchWithQuery:search queryType:(SPTQueryTypeTrack) session:auth.session callback:^(NSError *error, SPTListPage* object)]`

and trying to access an items album, we are returned null.

It's very annoying to have to have to pull in the SPTTracks for the search, then request them all again just to get the album name.

**Comment by timsk159** [comment]
It appears I was mislead by the documentation

SPTQueryTypeTrack
Specifies that all search results will be of type SPTTrack.

It actually returns a SPTPartialTrack... which annoyingly seems to contain everything except the album.

So because you are trying to save sending one string, I now have to make two full requests to your API.

The Android SDK is much simpler, these "Partial" objects are a PITA.

**Comment by possan** [comment]
Yes, search only returns partial albums, and functionality for having the possibility to 'upgrade' the partial search result to a list of full tracks is indeed missing, we'll add it to our backlog of things to fix.

**Comment by timsk159** [comment]
Rather than just fixing this, I'd like to suggest you fix your actual API flow here.

At the moment, we say to you API "Can I have these tracks please" and it replies with "Here is *some* of the data for the tracks that we guess you probably need".

We should be able to say "Can I have these tracks please, and here's the data I will need on them".

That way, we only request the minimum that we need.

At the moment, I'm receiving lots of data I don't need, and having to receive even more data I don't need, just to get one specific bit I *do* need.
