### ISSUE TITLE
Metadata attribute names are deprecated with no recommended replacements (beta 7)

### ISSUE THREAD

**Issue by timburks** [spotify/ios-sdk#305]
I find these declarations in SPTAudioStreamingController.h

FOUNDATION_EXPORT NSString * const SPTAudioStreamingMetadataTrackName DEPRECATED_ATTRIBUTE;
FOUNDATION_EXPORT NSString * const SPTAudioStreamingMetadataTrackURI;
FOUNDATION_EXPORT NSString * const SPTAudioStreamingMetadataArtistName DEPRECATED_ATTRIBUTE;
FOUNDATION_EXPORT NSString * const SPTAudioStreamingMetadataArtistURI DEPRECATED_ATTRIBUTE;
FOUNDATION_EXPORT NSString * const SPTAudioStreamingMetadataAlbumName DEPRECATED_ATTRIBUTE;
FOUNDATION_EXPORT NSString * const SPTAudioStreamingMetadataAlbumURI DEPRECATED_ATTRIBUTE;
FOUNDATION_EXPORT NSString * const SPTAudioStreamingMetadataTrackDuration DEPRECATED_ATTRIBUTE;

All but one of these attribute names are marked "DEPRECATED" with no further explanation. 

What should we use instead of these? Each corresponds to a string with the same value as the symbol name. Will these key names be preserved in future updates?

**Comment by possan** [comment]
The recommended replacement is to look them up using the track URI.

**Comment by uknowmeright** [comment]
Can you give a quick example of what method we use to accomplish this. I have been trying to figure this out for the last couple of days. Thanks!

**Comment by uknowmeright** [comment]
Just a quick example of what I have already tried that still returns nil:

    SPTRequest.requestItemAtURI(spotifySongToplay.uri, withSession: auth.session) { (error, returnedObject) -> Void in
        println("TrackURI")
        println(returnedObject)
        println(returnedObject.album)
        //println(spotifySongToplay.uri)
        //println(returnedObject.imageURL)
        
        SPTRequest.requestItemFromPartialObject(returnedObject as SPTPartialObject, withSession: auth.session) { (error, finalObject)  -> Void in
            
            println("Did get Final object")
            println(finalObject)
            println(finalObject.album)
            println(finalObject.imageURL)
            println("Artist")
            println(finalObject.artist)
        }
    }

Artist, Album, and image URL all come up nil

**Comment by timburks** [comment]
Per-Olov, 

It seems that the only non-deprecated way that I can get metadata for a track now is to to rely on this delegate method:

-(void)audioStreaming:(SPTAudioStreamingController *)audioStreaming didChangeToTrack:(NSDictionary *)trackMetadata;

because all of these are deprecated:

-(void)getRelativeTrackMetadata:(int)index callback:(void (^)(NSDictionary *))block DEPRECATED_ATTRIBUTE;
-(void)getAbsoluteTrackMetadata:(int)index callback:(void (^)(NSDictionary *))block DEPRECATED_ATTRIBUTE;
@property (nonatomic, readonly, copy) NSDictionary *currentTrackMetadata DEPRECATED_ATTRIBUTE;

That's fine.

But once I have this metadata, the only non-deprecated way to access properties in the metadata dictionary is to use the key names (as strings). This code compiles without warnings with the beta 7 SDK:

            metadata.title = trackMetadata[@"SPTAudioStreamingMetadataTrackName"];
            metadata.trackIdentifier = trackMetadata[SPTAudioStreamingMetadataTrackURI];
            metadata.album = trackMetadata[@"SPTAudioStreamingMetadataAlbumName"];
            metadata.artist = trackMetadata[@"SPTAudioStreamingMetadataArtistName"];
            metadata.trackDuration = [trackMetadata[@"SPTAudioStreamingMetadataTrackDuration"] doubleValue];

It seems weird to me that SPTAudioStreamingMetadataTrackURI is not deprecated and all the other keys are.  

The corresponding values are all still returned in the metadata dictionary:

(lldb) po trackMetadata
{
    SPTAudioStreamingMetadataAlbumName = "An Orchestrated Rise to Fall";
    SPTAudioStreamingMetadataAlbumURI = "spotify:album:7IoLXKqgoZSlX3PgwaL8WC";
    SPTAudioStreamingMetadataArtistName = "The Album Leaf";
    SPTAudioStreamingMetadataArtistURI = "spotify:artist:02uPe16VFxPaiueQsPEDkE";
    SPTAudioStreamingMetadataTrackDuration = "353.045";
    SPTAudioStreamingMetadataTrackName = Wander;
    SPTAudioStreamingMetadataTrackURI = "spotify:track:7iXiX53lhIcmYygpzwHlL6";
}

**Comment by uknowmeright** [comment]
Thanks! this helped me get it working.

**Comment by zakmandhro** [comment]
Please note that based on feedback on a more recent issue (https://github.com/spotify/ios-sdk/issues/320), the above proposed solution will also be deprecated "very soon".

**Comment by mattgabor** [comment]
I'm having trouble working with one of these functions in Swift. Is there any documentation online that discusses alternatives? Not sure what it means by "use full metadata object instead". Here is what I'm trying to accomplish:

    func tableView(tableView: UITableView, didSelectRowAtIndexPath indexPath: NSIndexPath) {
        let playListVC = UIStoryboard(name: "Main", bundle: nil).instantiateViewControllerWithIdentifier("playlistView") as! PlaylistDetailController
        
        let partial = self.partialPlaylists[indexPath.row] as! SPTPartialPlaylist
        SPTRequest.requestItemFromPartialObject(partial, withSession: self.session) { (error: NSError!, metadata: AnyObject!) -> Void in
            playListVC.snapshot = partial as! SPTPlaylistSnapshot
            playListVC.currentPage = playListVC.snapshot.firstTrackPage
            playListVC.partialPlaylist = partial
            playListVC.session = self.session
            self.navigationController?.pushViewController(playListVC, animated: true)
        }   
    }

Can anyone think of a way to do this without using requestItemFromPartialObject

**Comment by DmytroAnkudinov** [comment]
Playback track metadata in Spotify Audio Playback module is available in SPTPlaybackTrack class.
This class has been introduced in beta20.
