### ISSUE TITLE
Cocoa error 3840 

### ISSUE THREAD

**Issue by uknowmeright** [spotify/ios-sdk#306]
The operation couldn’t be completed. (Cocoa error 3840.)
This error pops up when I launched my app this morning. I looked it up and apparently it is related to JSON being improperly delivered. It was working fine yesterday. I guess they are working on the server? Any time frame on how long this may take to be resolved?

**Comment by possan** [comment]
Is this error still occurring?

**Comment by uknowmeright** [comment]
No, sorry for the late update, it went away by itself.

**Comment by docterd** [comment]
Since yesterday I'm getting the same problem.

**Comment by dcristolovean** [comment]
it comes and goes, I just got it in beta 9, i cant login now and I'm stuck.
