### ISSUE TITLE
removeTracksWithPositionsFromPlaylist - bad request

### ISSUE THREAD

**Issue by johra** [spotify/ios-sdk#307]
When trying to delete (or re-order) tracks in a playlist, I get error code 400 "bad request".

These are my parameters:
[track: <SPTPlaylistTrack: 0x155f86d0>: She's Not You (spotify:track:6o0S0i0NoKvrbDOJ2nRNvf), positions: (
    6
)]

Response:
*** Track delete got error Error Domain=com.spotify.ios-sdk Code=400 "bad request" UserInfo=0x1681a5f0 {NSLocalizedDescription=bad request}

This worked fine some time ago and seems to have broken recently?

**Comment by DmytroAnkudinov** [comment]
Issue is not reproducible as of beta24.
