### ISSUE TITLE
Cannot play non-streamed music

### ISSUE THREAD

**Issue by eldaniel7** [spotify/ios-sdk#308]
I went trough all the available documentation and I have not found any way to play the music the user has downloaded, i.e. non-streaming content.

According to the Spotify Developer Terms of Use, Section III (Licenses and Permissions), Article 2 (Commercial Use Restrictions), Point b: "Unless you receive Spotify's written approval, the following are the only commercial uses of **NON-Streaming SDAs** permitted under these Developer Terms(...)"

(Non-Streaming SDA: "A 'Non-Streaming SDA' is an SDA that does not provide any Streaming functionality.", Sec.II, Article 10)

The only class that I can see in the API Reference that produces sound is *SPTAudioStreamingController*, which as its name says is a Streaming controller which does not uses locally-available songs.

**Comment by possan** [comment]
There is no way to stream local content using the SDK's today, the local content is just that, local to the app where you added it, and it's not synchronized across devices etc, and the path to the actual file is only available in the app that added it.

**Comment by eldaniel7** [comment]
Thank you for your answer. From it I infer that the functionality I mention won't be supported. Then my question is, how are we developers to implement a NON-Straming SDA? 

Kind regards
Daniel

**Comment by possan** [comment]
Non Streaming SDA refers to applications using the SDK for let's say manipulating a users' playlists, but not actually playing any music.

Streaming SDA is the opposite, anything playing audio from Spotify.
