### ISSUE TITLE
There is no sound when play the preview url in iPad

### ISSUE THREAD

**Issue by alanchen1988** [spotify/ios-sdk#310]
We team use the iOS SDK to get the track preview url. Then play the 30s song, but, there is no sound. However, the progress is moving.

Issue found on April 14th 2015.

Steps to reproduce: 
***** We use the API to get the preview url from the track.
[SPTRequest requestItemAtURI:[NSURL URLWithString:@"spotify:track:0CKxrnF9KplS21LTjkkqsW" withSession:nil callback:^(NSError error, SPTTrack *track) {
/// Now you have a track
if (error != nil) {
NSLog(@"** Album lookup got error %@", error);
return;
}
NSLog(@"previewURL=%@", track.previewURL);
}];

***** Then play the preview url (https://p.scdn.co/mp3-preview/1f74e8c41c7e1d1823382ab78aece316c24f3bad), there is no sound.

Expected behaviour: The progress is moving, but can not hear the sound.

Actual behaviour: The progress is moving and can hear the sound.

**Comment by possan** [comment]
Did you solve this? If not, how do you actually play the 30s preview mp3?

**Comment by alanchen1988** [comment]
We can play the preview mp3 in the simulator and can hear the sound. We also can play it in the device, but there is no sound.

**Comment by possan** [comment]
I'm closing this since i'm not sure how this is related to our sdk, if audio works in the simulator and not on the device, using the system mp3 player i guess, this must be related to the actual playback code, or state of the device.
