### ISSUE TITLE
Issues with track count after adding track to playlist

### ISSUE THREAD

**Issue by righthandman** [spotify/ios-sdk#311]
Hi, I think that there is an internal issue in the SDK. 

Every time I add a track to a playlist I expect the track count for this playlist to be updated when I retrieve all users playlists. 

+(void)playlistsForUserInSession:(SPTSession *)session callback:(SPTRequestCallback)block;

The expected behavior occurs when I either create a new playlist though my app or remove some other playlist using the web player.

I think the SDK is missing something internally that recalculates track counts when the new track is added. Please look into it, thanks!

**Comment by possan** [comment]
There is no recalculation happening in the SDK, it's just a wrapper on top of the Web API, if you add a track and then request a users playlist again, the counts should be updated.

**Comment by righthandman** [comment]
That's exactly what I do request the tracks using 
[SPTRequest playlistsForUserInSession:appDelegate.spotifySession callback:^(NSError *error, id object)];

I do not have the correct count I only get the correct count after I add another track.

**Comment by possan** [comment]
Hmm, thats very weird..

**Comment by DmytroAnkudinov** [comment]
Issue is not reproducible as of beta24.
