### ISSUE TITLE
`Simple Track Playback` relogin crash

### ISSUE THREAD

**Issue by bezigon** [spotify/ios-sdk#313]
Tested in iOS 7, 8 on sample project `Simple Track Playback` with enabled swap, renew token feature

Steps to reproduce:
1. Login
2. Logout
3. Login
... *CRASH!*

![screen shot 2015-04-24 at 11 49 27](https://cloud.githubusercontent.com/assets/771853/7315710/b421401e-ea78-11e4-811b-6d82656b1aca.png)

**Comment by possan** [comment]
This has been fixed in the new beta.

**Comment by bezigon** [comment]
I repeated this issue, seems not fixed by now...

![screen shot 2015-05-11 at 10 49 44](https://cloud.githubusercontent.com/assets/771853/7560408/8e07c0aa-f7cb-11e4-9ad1-b84068b57bda.png)
