### ISSUE TITLE
`In for a penny, in for a pound` my dear friends...

### ISSUE THREAD

**Issue by bezigon** [spotify/ios-sdk#314]
### beta-8 on *TBA* (52 days and *counts...*)
beta-7 on Mar 4 (***achtung!!*** 104 days)
beta-6 on Nov 21, 2014 (79 days)
beta-5 on Sep 4, 2014 (21 days)
beta-4 on Aug 15, 2014 (59 days)
beta-3 on Jun 18, 2014 (76 days)
beta-2 on Apr 4, 2014 (30 days)
beta-1 on Mar 6, 2014 
## We need a *working* bug-*free* SDK!
Where developers who worked on the old but proven library `Libspotify SDK`?

**Comment by possan** [comment]
Let's just say that the team working on this isn't that big and we also have other priorities...
