### ISSUE TITLE
App rejected due to authentication screen

### ISSUE THREAD

**Issue by GabeJacobs** [spotify/ios-sdk#316]
"From Apple
2.25 Details

The Spotify feature in your app displays or promotes third-party apps, which violates the App Store Review Guidelines. We’ve attached screenshot(s) for your reference.

Please see the attached screenshot for more information.

Next Steps

Please remove the promotion of Spotify feature from your app."

There was a thread about this before, but I wanted to re-open one since that one was closed. Are people getting this? What are they doing about it?

**Comment by possan** [comment]
What does the screenshot show? is it the in-app authentication dialog?

**Comment by GabeJacobs** [comment]
@possan this screen http://imgur.com/8xi2ac2

**Comment by possan** [comment]
Hmm, they haven't been this aggressive before and others have been approved lately as i understand it...

**Comment by GabeJacobs** [comment]
I appealed showing other apps that have the same functionality. But I think they are sticking with their answer. Maybe it's because there is a sign up option?

**Comment by possan** [comment]
Hm, we'll have to look in to this, if there's a way to hide it, but that means that no one can use the app without an existing account...

**Comment by GabeJacobs** [comment]
For me that's totally fine. Not sure about others though.

**Comment by Anders27** [comment]
In my opinion it's not important that the signup link is displayed. Spotify users only need to be able login and none Spotify users don't care anyway.

So far Apple has approved all my updates but I have a new update that Apple still hasn't approved.
When Apple release their own streaming audio service (WWDC June?) there will be a (big?) possibility that they will reject every app that has a signup option for a competing service.

**Comment by GabeJacobs** [comment]
@Anders27 What do you suggest doing for the time being?

**Comment by Anders27** [comment]
Spotify support is not the main thing in my app, it has other ways to playback audio. Maybe that’s why Apple approve it?

But I keep my fingers crossed each time I upload an update so I think it would be good if the signup button is removed.

**Comment by bezigon** [comment]
From App Store Review Guidelines
"17.5 Apps that include account registration or access a user’s existing account must include a privacy policy or they will be rejected"

Maybe there is no link in login/signup UIWebView?

**Comment by possan** [comment]
We've hidden the signup link on our login page for calls from the last beta release now, please re-submit and report if there's any additional issues ...

**Comment by possan** [comment]
Update: We're talking to Apple about this and will enable the signup link back soon again, let us now if this keeps causing rejections.

**Comment by GabeJacobs** [comment]
@possan should we resubmit with the sign up removed? We have an appeal going right now, but should we just forget about it an resubmit?

**Comment by GabeJacobs** [comment]
@possan also how do we update the SDK to get the hide signup feature working?

**Comment by possan** [comment]
You don't need to change anything, it's affecting all builds with the current sdk

**Comment by GabeJacobs** [comment]
@possan, just noticed that. Thanks. Fingers crossed! Apple said they are okay with this now?

**Comment by possan** [comment]
I don't know if we heard back yet, that could probably take some time, so we'll see what happens...

**Comment by GabeJacobs** [comment]
We're accepted. @possan thanks a lot for the quick response
