### ISSUE TITLE
Try to play a track which is not available

### ISSUE THREAD

**Issue by Zwaaan** [spotify/ios-sdk#317]
Hi!

When I try to play a track with self.streamingPlayer playURIs: and load it with a track which is not available (spotify:track:47fsBEXAmXzJILc1B9dqIb) nothing happens, I don't get an error or a callback.

How can I determine if the track is playable or avoid this error?

**Comment by possan** [comment]
It should fire the `[SPTAudioStreamingControllerDelegate audioStreaming:didFailToPlayTrack:]`event. if not, this is a bug.

**Comment by uknowmeright** [comment]
Can confirm. This crashes my app now and only throws "unexpectadly found nil while unwrapping an Optional value" im guessing on the spotifyPlayer? have tried including a callback but will not execute it when it fails.

**Comment by possan** [comment]
Closing this, this should be fixed now in the latest release.
