### ISSUE TITLE
didStartPlayingTrack invoked twice?

### ISSUE THREAD

**Issue by jacksonh** [spotify/ios-sdk#318]
I'm getting two invocations of ```- (void)audioStreaming:(SPTAudioStreamingController *)audioStreaming didStartPlayingTrack:(NSURL *)trackURI``` each time I change tracks using ```-(void)playURIs:(NSArray *)uris withOptions:(SPTPlayOptions *)options callback:(SPTErrorableOperationCallback)block;```

**Comment by possan** [comment]
Could this be related to the first track being unplayable? or is it refering to the same track?

**Comment by uknowmeright** [comment]
can confirm,
 i get two of the same song URL printed. I am redirecting from another Viewcontroller to my "mainView" and call a function through NSNotificationcenter. My setupspotify() function is called twice and thus runs the following function twice:

println([spotifySongToplay.uri])

I don't think its an NSnotificationcenter bug as I use it in other parts of my app and it runs fine. I believe this is a bug in the sdk. Hope this helps!

**Comment by jacksonh** [comment]
I actually think this issue was just in my code. I've been trying to build a standalone test and can't replicate the issue. I need to dig into my code more, but most likely ```didStartPlayingTrack``` is causing an extra invocation.

**Comment by guindows** [comment]
Hi @jacksonh 
I'm having same trouble...the method playURIs is calling twice the delegate didStartPlayingTrack. And I've re-cheked my code, and I'm sure I'm calling play just once.
Any suggestions? Have you solved you problem? Tk's!!!

**Comment by elmateo487** [comment]
This is still an issue, when I call .skipNext() didStartPlayingTrack is called twice. skipNext is only called once
