### ISSUE TITLE
Change Spotify's audio stream volume

### ISSUE THREAD

**Issue by JCardenete** [spotify/ios-sdk#32]
In the previous SDK we had fine control over Spotify's volume with [SPTAudioStreamingController](https://spotify.github.io/ios-streaming-sdk/Classes/SPTAudioStreamingController.html). I'm not sure if this is possible with the new Remote SDK?

**Comment by jackfreeman** [comment]
@JCardenete this is not currently possible with the new SDK, but your suggestion has been noted. 

There is a beta web-api endpoint here that might work for you: https://developer.spotify.com/documentation/web-api/reference/player/set-volume-for-users-playback/

**Comment by JCardenete** [comment]
Thanks @jackfreeman.

Do you recommend using the web-api over the previous iOS SDK if we want to haver finer control?

**Comment by JCardenete** [comment]
A few weeks ago I tried using the web-api endpoint for the volume and it worked via the Spotify web console, however now I'm getting this response:

{
  "error": {
    "status": 403,
    "message": "Player command failed: Cannot control device volume",
    "reason": "VOLUME_CONTROL_DISALLOW"
  }
}

Any ideas on why?

**Comment by onurhazar** [comment]
@JCardenete Hi, did you able to find a workaround for this? I got the same error when using the web api.

**Comment by onurhazar** [comment]
@JCardenete I think for iOS devices, it's not possible to change the volume of the Spotify mobile app itself because there is no in app sound setting inside of the app (btw changing web player's volume is working). I also tried their sample (https://developer.spotify.com/console/put-volume/?volume_percent=&device_id=) It gave me the same error. @jackfreeman Is this going to be implemented in the future releases? Sorry for asking this here because I couldn't find any technical support email to contact.

**Comment by afox381** [comment]
Such a shame the volume control isn't in. I guess it'll be back to the old SDK for the time being, ugly and intrusive authorisation page and all. :( 

Any sign of it in the near future?

**Comment by dataexcess** [comment]
Does this mean we can also not mute the track?
Right now a track is playing when authenticating... Any chance we can mute the player when this is going on and then unmute when successfully connected?

**Comment by SelcouthGuy** [comment]
Any news here?
Same problem looks like not resolved for a year

**Comment by kkarayannis** [comment]
There are no plans to implement volume controls in the mobile SDK.

**Comment by EvanKaminsky** [comment]
Well that's pathetic lol. Just get rid of the mobile SDK if you're not serious about it.

**Comment by vapor-pawelw** [comment]
Why make such a breaking change and remove a feature many apps relied on? I could understand this if you wanted to disallow changing volume via any API at all, but if you allow it via new web API I can not understand why you wouldn't implement this feature in the SDK.
