### ISSUE TITLE
Deprecation clarification: Is audioStreaming:didChangeToTrack:trackMetadata OK?

### ISSUE THREAD

**Issue by zakmandhro** [spotify/ios-sdk#320]
I see that `[play currentTrackMetadata]` and most of the metadata constants (e.g. `SPTAudioStreamingMetadataTrackName`) have been deprecated. However, `audioStreaming:didChangeToTrack:trackMetadata` still returns the metadata dictionary and *is not* deprecated.

Is it safe to assume that the below delegate call is not being deprecated?

    - (void)audioStreaming:(SPTAudioStreamingController *)audioStreaming didChangeToTrack:(NSDictionary *)trackMetadata {
      NSString *trackName = trackMetadata[@"SPTAudioStreamingMetadataTrackName"];
    }

**Comment by possan** [comment]
The thing is that we can't provide track metadata such as album and artist at this point, but we can provide the track URI, that's why the structure is deprecated at the moment, those additional fields will probably go away very soon, but track URI and possibly track duration will still be in there

**Comment by zakmandhro** [comment]
Two follow-ups:

(1) Does "go away" mean that the API server will stop returning values? In other words, will live apps break?

(2) Is this the recommended solution as follows?

    [SPTTrack trackWithURI:[NSURL URLWithString:[self.player.currentTrackMetadata valueForKey:SPTAudioStreamingMetadataTrackURI]]
                   session:auth.session
                  callback:^(NSError *error, SPTTrack *track) {

                      self.titleLabel.text = track.name;
                      self.albumLabel.text = track.album.name;
    ....

**Comment by uknowmeright** [comment]
I am also interested in this issue. I currently have this method implemented for pulling track name, URI, album, artist, TrackDuration, and AlbumURI for the album art. It all currently works great until a song ends and it crashes saying there is a nil value for those values. Will this not be able to pull info in the future?

**Comment by possan** [comment]
It will go away from the SDK, in the last betas there's a few new fields named `currentTrackURI`, `currentTrackDuration` and `currentTrackIndex` - i'd recommend using those instead.

The reason for this is that we don't know the album name and track name at this point in the playback, and we don't want to do extra lookups for those fields if they aren't necessary, and they're not necessary for doing the actual playback.

**Comment by jeffb6688** [comment]
You say that the track name is unknown when the delegate method audioStreaming:didChangeToTrack: is called. You say that you don't want to do extra lookups for the track name since they are not necessary for playback. Its true they are not necessary for playback. However, if we want to tell the user what track is playing, we need the track name. What methods and/or methodology can we use to do the "extra lookups" to get the track name?

**Comment by jeffb6688** [comment]
@zakmandhro did you ever find a solution for this? In my case, the track name is needed when the delegate method audioStreaming:didChangeToTrack: is called so that the user can be informed.
