### ISSUE TITLE
Latest update has broken the ability to connect to the app via Spotify iOS SDK

### ISSUE THREAD

**Issue by addy239** [spotify/ios-sdk#320]
With the most recent update to Spotify’s iOS App, the ability for 3rd party apps to read Spotify’s now playing information using the iOS SDK has broken and the app no longer allows connecting as reliably as before.
 
This also affects demo app so let me explain what’s going on:

If the demo app is opened quickly after Spotify, it’s able to connect fine as Spotify app is still not backgrounded, but if Spotify gets backgrounded, no further connections are allowed. So basically that’s the bug. 

Same thing happens with our app too, but since we have added a delay on connection, our app doesn’t fire connection request before Spotify gets backgrounded. The delay was really added due to another bug that users were facing and adding the delay used to connect more reliably.

Previously, as long as Spotify app was playing music in the background, it was possible to connect to the app using the iOS SDK.

It’s affecting many of our users and probably many other apps. I hope it gets fixed soon.

Spotify App Version that introduced this issue: 8.6.20

**Comment by rugoso** [comment]
Also experiencing this error with my app, also tried running the demo project (NowPlayingView, with the SDK 1.2.2 ) and it does not connect to the Spotify app, no matter if the Spotify app is already running or not, playing or not. Does anybody know if the SDK developers have confirmed that they are aware of this issue?

**Comment by addy239** [comment]
This has been fixed in the latest update to Spotify app, 8.6.22. Thanks, Spotify.
