### ISSUE TITLE
playlist.firstTrackPage.items get from playlistWithURI SPTPlaylistSnapshot return nil with WatchKit Extension

### ISSUE THREAD

**Issue by TristanNeret** [spotify/ios-sdk#321]
Hi,

I use the following code to get track from user playlist, it works well on iPhone but playlist.firstTrackPage.items return nil on WatchKit Extension.

[SPTPlaylistSnapshot playlistWithURI:partial_playlist.uri session:auth.session callback:^(NSError *error, SPTPlaylistSnapshot* playlist) {
        
            tab_track = playlist.firstTrackPage.items;
        
    }];

I also use SPTRequest to get the user's playlist and it works well on the WatchKit extension so I don't understand why playlistWithURI does not work on the Watch.

Are there any reason ?

**Comment by Voxar** [comment]
Hi Tristan. This issues almost has its anniversary. Sorry about that.

I sure hope this was resolved for you by now. Please let us know otherwise!
