### ISSUE TITLE
Cannot search for users

### ISSUE THREAD

**Issue by mhuusko5** [spotify/ios-sdk#322]
Cannot currently search for spotify users, like in the desktop app.

**Comment by possan** [comment]
Our open api does currently not support this feature, i'll keep this around as a future enhancement.

**Comment by erdtman** [comment]
We are deprecating the iOS-Metadata library.

The source code of the iOS-Metadata library has been released and can be found [here](https://github.com/erdtman/spotify-ios-metadata/). Spotify will not continue to maintain the released source code.

Either you can select to use the web-api directly or use the new open source iOS-Metadata library.

I will close this issue now.

We are sorry for the inconvenience that this creates, but looking back we think this is the best path forward.
