### ISSUE TITLE
Cannot avoid active playback device error

### ISSUE THREAD

**Issue by GabeJacobs** [spotify/ios-sdk#324]
@possan With beta 8, I now cannot avoid this error when I try to play a song:

Error Domain=com.spotify.ios-sdk.playback Code=14 "The operation is not supported if the device is not the active playback device." UserInfo=0x17147a200 {NSLocalizedDescription=The operation is not supported if the device is not the active playback device.}

I only upgraded the framework. What is wrong?

**Comment by possan** [comment]
When do you get that error? when calling `playURIs`?

**Comment by GabeJacobs** [comment]
Forget

**Comment by Navideck-fotis** [comment]
How did you solve it?
