### ISSUE TITLE
Spotify song pauses automatically.

### ISSUE THREAD

**Issue by rajaarun** [spotify/ios-sdk#325]
Many times the song has been paused randomly and below method is called.

``` 
-(void)audioStreaming:(SPTAudioStreamingController *)audioStreaming didChangePlaybackStatus:(BOOL)isPlaying{
   
}

 ```

Then it need to set the player to play the song again. After calling this code the song resumes from where it was paused previously.

**[[MyViewController player] setIsPlaying:YES callback:nil];**

**Comment by possan** [comment]
I haven't seen this in my test at all, to me it sounds like someone else is trying to play using your account somewhere else.

**Comment by rajaarun** [comment]
Yes, i am using the same Spotify account to play song in multiple iOS devices for testing purpose.

**Comment by possan** [comment]
If you start playing a song on another device the old device will get a notification and stop playing.

**Comment by rajaarun** [comment]
Yes that's the reason it was stopping the song, i tested it again. 
Thanks for the help.
