### ISSUE TITLE
SPTAudioStreamingController login callback not getting called.

### ISSUE THREAD

**Issue by ASCrookes** [spotify/ios-sdk#326]
@possan, updated to beta 8 and now the SPTAudioStreamingController login function (loginWithSession:callback:) never calls the callback.
Any ideas how to fix this?

**Comment by possan** [comment]
Could you try the included example app and check if it is called in that? i haven't seen this issue.

**Comment by ASCrookes** [comment]
Ah yeah, actually do not need to call loginWithSession:callback: anymore for premium playback.
Thanks!
