### ISSUE TITLE
Playback stopped in headset when i lock the screen

### ISSUE THREAD

**Issue by MDkil** [spotify/ios-sdk#327]
Playback is being stopped in headphones when i lock the screen: Only in Headphones.
PS: I'm using Audio Playback mode in capabilities .

**Comment by JMPerez** [comment]
@MDkil Does your issue refer to the Spotify iOS SDK or to the Spotify iOS application?

**Comment by MDkil** [comment]
@JMPerez : Spotify iOS SDK ofc.
I don't have this issue with CocoaLibSpotify.
