### ISSUE TITLE
createPlaylistWithName has become a class method

### ISSUE THREAD

**Issue by mhuusko5** [spotify/ios-sdk#328]
createPlaylistWithName has become a class method despite needing to act on a SPTPlaylistList instance and being documented as "Create a new playlist and add it to the *this* playlist list."

**Comment by mhuusko5** [comment]
Just tested and it seems the method does work as expected though. So I guess this is more a semantics/documentation issue.

**Comment by possan** [comment]
Yes, it operates your "list of playlists" but not on an instance of that list, that's why it's a class/static method now.
