### ISSUE TITLE
performSearch methods have been marked deprecated without replacements

### ISSUE THREAD

**Issue by mhuusko5** [spotify/ios-sdk#329]
^ title says it :)

**Comment by possan** [comment]
I was going to reply, "See `SPTSearch`" but then i noticed that's missing from the headers :/

**Comment by dnosk** [comment]
any timeline on this?

**Comment by EsbenRud** [comment]
It works when you comment out the DEPRECATED_ATTRIBUTE in the SPTRequest.h file.

**Comment by lgfaria** [comment]
Thanks for that, commenting out "DEPRECATED_ATTRIBUTE" in the header file worked.. any news on this issue?

**Comment by DmytroAnkudinov** [comment]
SPTSearch class introduced in beta9. All search methods are there now.
