### ISSUE TITLE
Inconsistency of methods taking session object or accesstoken string

### ISSUE THREAD

**Issue by mhuusko5** [spotify/ios-sdk#330]
With beta 8 most methods now have sister methods that take an accesstoken instead of the session object. But some methods have actually lost their original one taking the session, and can only take an accesstoken. Just seems inconsistent.

Example:

```obj-c
-(void)addTracksToPlaylist:(NSArray *)tracks
			   withSession:(SPTSession *)session
				  callback:(SPTErrorableOperationCallback)block;  // There

-(void)addTracksToPlaylist:(NSArray *)tracks
		   withAccessToken:(NSString *)accessToken
				  callback:(SPTErrorableOperationCallback)block; // There

-(void)removeTracksFromPlaylist:(NSArray *)tracks
				 withSession:(SPTSession *)session
					   callback:(SPTErrorableOperationCallback)block; // MISSING

-(void)removeTracksFromPlaylist:(NSArray *)tracks
				withAccessToken:(NSString *)accessToken
					   callback:(SPTErrorableOperationCallback)block; // There
```

**Comment by possan** [comment]
We're moving away from passing the SPTSession everywhere because we want to separate the authentication and the api wrapper parts of the SDK into separate frameworks, i thought i got all of them down but i probably missed a few of them.

**Comment by DmytroAnkudinov** [comment]
Separation implemented in beta22. Only methods accepting accessToken remain.
