### ISSUE TITLE
Unable to Authenticate

### ISSUE THREAD

**Issue by Brad-Jackson** [spotify/ios-sdk#332]
My login code is as follows

>static NSString * const gSpotifyCallbackURL = @"managemynightlife://callback";

>- (void)showLogin:(UIApplication *)aApplication
>{
>    // Create SPTAuth instance; create login URL and open it
>    NSURL *url = [NSURL URLWithString:gSpotifyCallbackURL];
>    NSURL *loginURL = [SPTAuth loginURLForClientId:gSpotifyClientId withRedirectURL:url scopes:@[SPTAuthStreamingScope] responseType:@"code"];
>    
>    // Opening a URL in Safari close to application launch may trigger
>    // an iOS bug, so we wait a bit before doing so.
>    [aApplication performSelector:@selector(openURL:) withObject:loginURL afterDelay:0.1];
>}

I have commented out the canHandleURL function as it asserts. The URL that I get back from the server is.

managemynightlife://callback/?code=AQD7kgqf78gndGmk7BOyqvL5n6FcBeFGGDNJySZ9w_-Wy7WKbVNFchgEIwuQGdeKCKDwD4LfN-8WLcitXdUvHniRq9wbBvrDKPpm0pwBB0EHo9k9qEYx97igVceN-kJ6NDwnBLe2rrrk5Is7_WkpEjBdeLnK68BaYyPx3RX6oGhSrpykdTND0_iZGhnB09DR4q6HdPfHHXYuaAXdYA

>- (bool)openURL:(NSURL *)aURL
>{
>   // Ask SPTAuth if the URL given is a Spotify authentication callback
>    NSLog(@"%@", aURL);
>    
>//    if ([[SPTAuth defaultInstance] canHandleURL:aURL])
>    {
>        // Call the token swap service to get a logged in session
>        [[SPTAuth defaultInstance] handleAuthCallbackWithTriggeredAuthURL:aURL callback:^(NSError *error, SPTSession *session)
>         {
>             if (error)
>             {
>                 NSLog(@"*** Auth error: %@", error);
>                 return;
>             }
>             
>             [self onLoggedIn:session];
>         }];
>        
>        return true;
>    }
>    
>    return false;
>}

The handleAuthCallbackWithTriggeredAuthURL errors with the following code.

Error Domain=NSURLErrorDomain Code=-1002 "unsupported URL" UserInfo=0x145c6650 {NSUnderlyingError=0x146533d0 "unsupported URL", NSLocalizedDescription=unsupported URL}

I am stuck as to what is the problem. I am running on a device not the simulator.
I just recently updated from beta-6 to the beta-8; the login code worked fine on the old version.

**Comment by possan** [comment]
What is your token swap url and how do you set it?

**Comment by Brad-Jackson** [comment]
So I have changed the login to look like this.

>    static NSString * const gSpotifyCallbackURL = @"managemynightlife://callback";
>    static NSString * const gSpotifyTokenSwapURL = @"http://hdms-live.nightlife.com.au/papi/spotify/swap/manageMyNightlife";
>    static NSString * const gSpotifyTokenRefreshURL = @"http://hdms-live.nightlife.com.au/papi/spotify/refresh/manageMyNightlife";

>    [[SPTAuth defaultInstance] setClientID:gSpotifyClientId];
>    [[SPTAuth defaultInstance] setRedirectURL:[NSURL URLWithString:gSpotifyCallbackURL]];
>    [[SPTAuth defaultInstance] setTokenSwapURL:[NSURL URLWithString:gSpotifyTokenSwapURL]];
>    [[SPTAuth defaultInstance] setTokenRefreshURL:[NSURL URLWithString:gSpotifyTokenRefreshURL]];
    
>    [[SPTAuth defaultInstance] setRequestedScopes:@[SPTAuthStreamingScope]];
>    NSURL *loginURL = [[SPTAuth defaultInstance] loginURL];
>    [aApplication performSelector:@selector(openURL:) withObject:loginURL afterDelay:0.1];

The error has now changed to. You might want to update the web page tutorial as it doesn't set the swap URL anywhere. I did find it set in the demo projects.

Domain=com.spotify.auth Code=400 "Invalid redirect URI" UserInfo=0x16d0d560 {NSLocalizedDescription=Invalid redirect URI}

**Comment by Brad-Jackson** [comment]
Still need help I can't figure out what the problem is.

**Comment by possan** [comment]
What is your client id? (so that i can look up your configuration and verify some things)

**Comment by Brad-Jackson** [comment]
static NSString * const gSpotifyClientId = @"50803e5feb4840a28c7006e34a59618f";

**Comment by possan** [comment]
i did some debugging, and it's your server is returning the message "invalid redirect uri", if you're just passing the response from our backend call back out to the client, that means you aren't passing the correct parameters to that endpoint.

See https://developer.spotify.com/web-api/authorization-guide/ - Step 4 and onward

**Comment by Brad-Jackson** [comment]
Thanks for that, turns out my url should have been manageMyNightlife://callback

**Comment by parthpatel1105** [comment]
@possan I am getting error: 

Error Domain=com.spotify.auth Code=400 "No refresh token available in the session!" UserInfo={NSLocalizedDescription=No refresh token available in the session!}

Is there any specific solution which could help me to renew session of Spotify in my app?

Thank you.
