### ISSUE TITLE
New Spotify version (8.6.58) broke the authorization flow

### ISSUE THREAD

**Issue by aronpammer** [spotify/ios-sdk#332]
The initiateSession's callback url's format has changed, and users of my app are no longer able to log in.

Version 8.6.58 returns an access_token:
`<app-name>://spotify-login-callback/?spotify_version=8.6.58.1030#access_token=<token>&token_type=Bearer&expires_in=3600`

Version 8.6.40 returns code:
`<app-name>://spotify-login-callback/?code=<code>&spotify_version=8.6.40.1248`

This means that the following does not work anymore:
`sessionManager?.application(UIApplication.shared, open: url, options: [:])`, because this function does not recognize this new callback url.

**Comment by josianebezerra** [comment]
@aronpammer thanks for reporting. This issue should be fixed now. Can you try again?

**Comment by aronpammer** [comment]
@josianebezerra Thanks for the quick response. I just checked and now it works, thank you!
