### ISSUE TITLE
How to get inboxPlaylist?

### ISSUE THREAD

**Issue by hsin919** [spotify/ios-sdk#333]
As the property under

https://github.com/spotify/cocoalibspotify/blob/master/common/SPSession.m

```
@property (nonatomic, readwrite, strong) SPPlaylist *inboxPlaylist;
```

Currently I am using the following function getting `starredPlaylist` & `userPlaylists`

```
+(void)playlistsForUserInSession:(SPTSession *)session callback:(SPTRequestCallback)block;
+(void)starredListForUserInSession:(SPTSession *)session callback:(SPTRequestCallback)block DEPRECATED_ATTRIBUTE ;
```

How to get inboxPlaylist in this iOS-sdk?
Thanks for your help !

**Comment by possan** [comment]
This is not something that we support in the Web API's so we can't wrap those API's in the SDK.

**Comment by hsin919** [comment]
Thanks for your reply.
Just curious about how `cocoalibspotify` get inbox playlist by using
```
                                        SPPlaylist *playlist = [self playlistForPlaylistStruct:pl];
					dispatch_async(dispatch_get_main_queue(), ^() {
						// We don't want to overwrite our old instances
						if (self.inboxPlaylist == nil)
							self.inboxPlaylist = playlist;
					});
```

**Comment by erdtman** [comment]
We are deprecating the iOS-Metadata library.

The source code of the iOS-Metadata library has been released and can be found [here](https://github.com/erdtman/spotify-ios-metadata/). Spotify will not continue to maintain the released source code.

Either you can select to use the web-api directly or use the new open source iOS-Metadata library.

I will close this issue now.

We are sorry for the inconvenience that this creates, but looking back we think this is the best path forward.
