### ISSUE TITLE
Beta 8 - SPTDiskCaching warnings

### ISSUE THREAD

**Issue by Anders27** [spotify/ios-sdk#334]
My project doesn't use ARC and with beta 8 I get the following warnings:

/Volumes/HD_devoted_to_programming/iOS/spotify-ios-sdk/Spotify.framework/Headers/SPTDiskCaching.h:32:1: No 'assign', 'retain', or 'copy' attribute is specified - 'assign' is assumed
/Volumes/HD_devoted_to_programming/iOS/spotify-ios-sdk/Spotify.framework/Headers/SPTDiskCaching.h:32:1: Default property attribute 'assign' not appropriate for non-GC object
/Volumes/HD_devoted_to_programming/iOS/spotify-ios-sdk/Spotify.framework/Headers/SPTDiskCaching.h:37:1: No 'assign', 'retain', or 'copy' attribute is specified - 'assign' is assumed
/Volumes/HD_devoted_to_programming/iOS/spotify-ios-sdk/Spotify.framework/Headers/SPTDiskCaching.h:37:1: Default property attribute 'assign' not appropriate for non-GC object
/Volumes/HD_devoted_to_programming/iOS/spotify-ios-sdk/Spotify.framework/Headers/SPTDiskCaching.h:48:1: No 'assign', 'retain', or 'copy' attribute is specified - 'assign' is assumed
/Volumes/HD_devoted_to_programming/iOS/spotify-ios-sdk/Spotify.framework/Headers/SPTDiskCaching.h:48:1: Default property attribute 'assign' not appropriate for non-GC object

I reported the same warnings when beta 7 was released, issue #264

**Comment by DmytroAnkudinov** [comment]
Issue fixed in Beta9.
SPTDiskCaching was refactored and associate interface 'SPTCacheData' that possessed all attributes mentioned in the bug was removed in Beta22.
