### ISSUE TITLE
The new authentication way using SPTAuthViewController on iOS 7.1.x 

### ISSUE THREAD

**Issue by ungureanuli** [spotify/ios-sdk#336]
The new authentication way works great on iOS 8.x , but not on iOS 7.1.x .
After creating an instance of SPTAuthViewController, when I try display it using presentViewController:animated:completion: I get the error:
*** WebKit discarded an uncaught exception in the webView:decidePolicyForNavigationAction:request:frame:decisionListener: delegate: -[__NSCFString containsString:]: unrecognized selector sent to instance 0x7a0e17a0
The web view is not displayed anymore (just a blank view), the user can only dismiss it.

Also, when calling the clearCookies method I get the crash:
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFString containsString:]: unrecognized selector sent to instance 0x7bef4810'

So I guess you should not use the containsString: method as it is only available from iOS8 (http://stackoverflow.com/questions/26410420/nsstring-containsstring-crashes).

Can you please tell me if you want to support iOS 7.1.x? And if so, could you please release another version with this fix?

**Comment by zakmandhro** [comment]
+1

Currently unable to support iOS 7 users due to this issue. Can you please fix or propose a workaround?

**Comment by Snppls** [comment]
[myString containsString:anotherString] does the same thing as [myString rangeOfString:anotherString].location != NSNotFound
You can implement containsString in a category to execute rangeOfString instead, like this guy did.
http://petersteinberger.com/blog/2014/retrofitting-containsstring-on-ios-7/

But this should obviously be fixed.

**Comment by ungureanuli** [comment]
In the bta 9 SDK this issue was fixed.
