### ISSUE TITLE
playURIs question

### ISSUE THREAD

**Issue by bangerang** [spotify/ios-sdk#337]
Just out of curiosity.
Will this method:
 ```-(void)playURIs:(NSArray *)uris fromIndex:(int)index callback:(SPTErrorableOperationCallback)block;``` pre fetch the tracks in any way?

My play logic is built up on the deprecated method:
``` -(void)playURI:(NSURL *)uri fromIndex:(int)index callback:(SPTErrorableOperationCallback)block ```
So for now I solved this by calling each new track with an array with 1 item:
```[self.audioStreamingController playURIs:@[URI] fromIndex:0 callback:(SPTErrorableOperationCallback)block];```

Is there any drawbacks by using the method like this?

**Comment by possan** [comment]
The idea is that we would prefetch the next track, we don't currently though.

That's the reason why we provide playURIs to initiate playback and replaceURIs (for changing the future tracks, or your position within your future list of tracks)

**Comment by bangerang** [comment]
All right, good to know, thanks for the reply.
