### ISSUE TITLE
app is crashing 'com.spotify.AudioStreaming (46): EXC_BAD_ACCESS (code=1, address=0x10)'

### ISSUE THREAD

**Issue by anupamwcities** [spotify/ios-sdk#338]
Hi , I am using beta 8 in my application ,  some times my app causing crashed while loading the next track. error message --- 'com.spotify.AudioStreaming (46): EXC_BAD_ACCESS (code=1, address=0x10)' 
As I  know generally  these type of error occurred  if object is removed from memory & we want to use that object .  I looked in my code din't get any point where I am using unassigned object . Please help me why this error causing .

**Comment by DmytroAnkudinov** [comment]
Issue is not reproducible as of beta24.
