### ISSUE TITLE
Provide more API source code.

### ISSUE THREAD

**Issue by msgilligan** [spotify/ios-sdk#339]
It would be great if (as much as possible) of the source code for this library could be published. In particular it would be nice to have the source for the code that wraps the web API calls.  This would help with documentation and debugging and, who knows, maybe you might even get a pull request or two.

**Comment by possan** [comment]
This is our goal, separating the sdk into an authentication framework, a metadata framework and a playback framework.

We are waiting for the playback part to be open sourceable (or at least in binary form releasable)

**Comment by flovilmart** [comment]
Any Progress on that?

**Comment by loretoparisi** [comment]
@msgilligan absolutely agree, also exposing more api to developers, with speed up the development process as well for bug fixing and improvements via PR!

**Comment by erdtman** [comment]
We are deprecating the iOS-Metadata library.

The source code of the iOS-Metadata library has been released and can be found [here](https://github.com/erdtman/spotify-ios-metadata/). Spotify will not continue to maintain the released source code.

Either you can select to use the web-api directly or use the new open source iOS-Metadata library.

I will close this issue now.

We are sorry for the inconvenience that this creates, but looking back we think this is the best path forward.
