### ISSUE TITLE
[SPTPlaylistSnapshot addTracksToPlaylist:withSession:callback:] adds track to playlist twice in iOS SDK Beta 8 (+ crash)

### ISSUE THREAD

**Issue by trufflin** [spotify/ios-sdk#341]
(UPDATE: Confirmed that the new method, addTracksToPlaylist:withAccessToken:callback behaves correctly. Perhaps addTracksToPlaylist:withSession:callback should be deprecated / removed.)

Hello, in testing my code after upgrading from Beta 7 to Beta 8, the "addTracksToPlaylist:withSession:callback" call is now adding the track to the playlist twice. I have confirmed I am only making one call to this method. The new track is listed twice in the playlist in the official Spotify client for Mac, and the callback: block in [SPTPlaylistSnapshot addTracksToPlaylist:] will be executed twice as well, often followed by a crash with callstack shown below: 

2015-05-16 14:40:21.902 ****[10956:2076788] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'data parameter is nil'
*** First throw call stack:
(
	0   CoreFoundation                      0x02d6e746 __exceptionPreprocess + 182
	1   libobjc.A.dylib                     0x029f7a97 objc_exception_throw + 44
	2   CoreFoundation                      0x02d6e66d +[NSException raise:format:] + 141
	3   Foundation                          0x02700156 +[NSJSONSerialization JSONObjectWithData:options:error:] + 67
	4   ****                                0x00171058 __59+[SPTRequest requestItemAtURI:withSession:market:callback:]_block_invoke + 71
	5   ****                                0x0017b350 __52-[SPTDefaultRequestHandler performRequest:callback:]_block_invoke_2 + 41

This would appear to be a bug introduced in Beta 8.

**Comment by possan** [comment]
Yep, confirmed.

**Comment by steve-whitney** [comment]
beta 8: I'm getting duplicated additions, too (but no crash).
beta 7 and below: didn't try.

**Comment by kevin--** [comment]
We are seeing this in SDK 8, not in SDK 7. Seems to happen more often when network connection is flaky or the request fails

**Comment by michalumni** [comment]
I am seeing it on ios 9.3 with the most recent version of the sdk.

**Comment by DmytroAnkudinov** [comment]
Issue is not reproducible as of Beta24.
