### ISSUE TITLE
SPTTrack trackWithURI issue

### ISSUE THREAD

**Issue by Kry256** [spotify/ios-sdk#343]
Before last SDK update, I was using 

```
[SPTRequest requestItemAtURI:[NSURL URLWithString:trackUri]
		                withSession:self.session
			              callback:^(NSError *error, id object) {
                             // Some stuff
					}];
```

to retrieve a complete ___SPTTrack___ object inside the ___SPTAudioStreamingController___ callback
```
-(void)audioStreaming:(SPTAudioStreamingController *)audioStreaming didChangeToTrack:(NSDictionary *)trackMetadata {__
          // Do the request
}
```

After the update to the _beta 8_ version, I noticed that the method in ___SPTRequest___ class was deprecated, so, as specified in your documentation, I start using the "equivalent" method inside ___SPTTarck___ class.

```
[SPTTrack trackWithURI:[self getSpotifyURIFromSpotifyID:trackUri]
                  accessToken:self.session.accessToken
		            market:[self getUserMarketPlace]
			  callback:^(NSError *error, id object) {
                     // Some other stuff
}];
```

Unfortunately, this method is not so "equivalent", because the _SPTTrack_ object returned inside the callback of  __[SPTTrack trackWithURI....__ has many less informations than the one returned inside the callback of the deprecated __[SPTRequest requestItemAtURI...__.
In particular the _'album'_ property is always ___nil__ and is very annoying for me.
I've tried some workaround, and I found that for me the solution is 
1 - create a request for an ___SPTTrack___ object
2 - perform it with ___SPTRequest___ object
3 - wait for the response, and eventually create a track _from data_ (here the complete code)

```
NSURLRequest *request = [SPTTrack createRequestForTrack:[NSURL URLWithString:trackUri]
											withAccessToken:self.session.accessToken
													 market:[self getUserMarketPlace]
													  error:nil];
[[SPTRequest sharedHandler] performRequest:request
				                               callback:^(NSError *error, NSURLResponse *response, NSData *data) {
										  if (!error) {
											  NSError *parsingError = nil;
											  SPTTrack *t = [SPTTrack trackFromData:data
																	   withResponse:response
																			  error:&parsingError];
										  }
									  }];
```

I found this solution a little too tricky, especially since there are ___trackWithURI...___ or ___tracksWithURIs...___ inside ___SPTTrack___ class and since the official documentation inside ___SPTRequest__ section says

_ [...] This method is deprecated, use the helpers in each individual object class instead. [...]
   For example: SPTTrack trackWithURI:session:callback: or `SPTPlaylistSnapshot playlistWithURI:session:callback [...]_

**Comment by ghear** [comment]
Hey, the new methods don't work for me.
```objective-c
    [SPTTrack trackWithURI:[NSURL URLWithString:@"spotify:track:5JlqbEj7Bbh2RdZgcO5kJE"] accessToken:loginVC.session.accessToken market:nil callback:^(NSError *error, id object) {
        if (!error) {
            NSLog(@"Returned object is %@", object);
        } else {
            NSLog(@"Error %@", error);
        }
    }];
```
This results in the error 
```
Error Error Domain=com.spotify.ios-sdk Code=102 "No registered class for type 'artist'" UserInfo=0x7f92e370a5b0 {NSLocalizedDescription=No registered class for type 'artist'}
```
I also tried your solution:
```objective-c
    NSURLRequest *trackReq = [SPTTrack createRequestForTrack:[NSURL URLWithString:self.song.trackURI]
                                             withAccessToken:loginVC.session.accessToken market:nil error:nil];

    
    [[SPTRequest sharedHandler] performRequest:trackReq callback:^(NSError *error, NSURLResponse *response, NSData *data) {
        if (!error) {
            NSDictionary *json = [NSJSONSerialization JSONObjectWithData:data options:NSJSONReadingAllowFragments error:nil];
            //SPTTrack *track = [SPTTrack trackFromData:data withResponse:response error:nil];
            SPTTrack *track =[SPTTrack trackFromDecodedJSON:json error:nil];
            NSLog(@"track is %@", track);

        } else {
            NSLog(@"There was an error, %@", error);
        }
    }];
```
And while this request succeeds, the returned track is null. Any help? The value for self.song.trackURI is the same uri as in my first code block. Also, this does not work using the session.accessToken returned from [SPTAuth defaultInstance]. I tried that and get the same results. Will you try and see if it works for you?

**Comment by Kry256** [comment]
As I wrote above, try create the track like this
```
NSError *parsingError = nil;
SPTTrack *t = [SPTTrack trackFromData:data
                         withResponse:response
                                error:&parsingError];
```
You can use the same __NSData__ and __NSURLResponse__ objects returned inside the callback, this works for me.
In addition I also noticed that passing ___nil___ to _market_ parameter, often cause the request return a non valid object (it seems to be another SDK bug).
Try passing ___currentUser.territory___ where _currentUser_ in an __SPTUser__ object or simply  __[[NSLocale currentLocale] objectForKey:NSLocaleCountryCode]__

**Comment by ghear** [comment]
Ok. Something was wrong with my project. I created a new project and am now able to fetch the track. Thanks! However, can you try playing this track with an SPTAudioStreamingController player object? I am facing errors. 
First I tried passing an array of SPTTracks to the player, and this failed.
```objective-c
        NSString *trackURI = @"spotify:track:5JlqbEj7Bbh2RdZgcO5kJE";
        NSString *market = [[NSLocale currentLocale] objectForKey:NSLocaleCountryCode];
        [SPTTrack trackWithURI:[NSURL URLWithString:trackURI] accessToken:auth.session.accessToken market:market callback:^(NSError *error, id object) {
            if (!error) {
                SPTTrack *t = object;
                NSArray *tracks = [NSArray arrayWithObject:t];
                [self.player playURIs:tracks fromIndex:0 callback:^(NSError *error) {
                    if (!error) {
                        
                    } else {
                        NSLog(@"*** Failed to play track : %@", error);
                    }
                }];
            } else {
                NSLog(@"Error %@", error);
            }
        }];
```
```
2015-05-22 19:29:11.109 SS[26643:974992] -[SPTTrack absoluteString]: unrecognized selector sent to instance 0x7f9408e9fa70
2015-05-22 19:29:11.111 SS[26643:974992] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[SPTTrack absoluteString]: unrecognized selector sent to instance 0x7f9408e9fa70'
```
I read that the player only needs the spotify uri, so I tried that too.
```objective-c
        NSString *trackURI = @"spotify:track:5JlqbEj7Bbh2RdZgcO5kJE";
        [self.player playURIs:[NSArray arrayWithObject:trackURI] fromIndex:0 callback:^(NSError *error) {
            if (!error) {
                
            } else {
                NSLog(@"NO: %@", error);
            }
        }];
```
```
2015-05-22 19:27:01.511 SS[26617:973733] NO: Error Domain=com.spotify.ios-sdk.playback Code=5 "An unexpected argument value was passed to a function." UserInfo=0x7f86ad071580 {NSLocalizedDescription=An unexpected argument value was passed to a function.}
2015-05-22 19:27:01.511 SS[26617:973902] -[__NSCFConstantString absoluteString]: unrecognized selector sent to instance 0x101d10580
2015-05-22 19:27:01.514 SS[26617:973902] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFConstantString absoluteString]: unrecognized selector sent to instance 0x101d10580'
```

Do you see these same errors? The goal is to play a single track using the player. Will you try this?
I also found this may be somewhat relevant: https://github.com/spotify/ios-sdk/issues/280

**Comment by Kry256** [comment]
Any news with the status of this bug after Beta 9?

**Comment by ram2386** [comment]
I am also face the same problem as @ghear. 

Could anyone find any solution then please share with us.

Thanks in advance.

**Comment by Kry256** [comment]
I've posted it above. it's the only one that I've found and that works for me.

**Comment by ram2386** [comment]
@Kry256 : Thanks for your reply and I had used your suggestion but it get crash. For more information please find the below code.

        self.player = [[SPTAudioStreamingController alloc] initWithClientId:auth.clientID];
        self.player.playbackDelegate = self;
        self.player.diskCache = [[SPTDiskCache alloc] initWithCapacity:1024 * 1024 * 64];

    NSString *market = [[NSLocale currentLocale] objectForKey:NSLocaleCountryCode];
    NSURLRequest *request = [SPTTrack createRequestForTrack:[NSURL URLWithString:@"spotify:track:1zHlj4dQ8ZAtrayhuDDmkY"]
                                            withAccessToken:auth.session.accessToken
                                                     market:market
                                                      error:nil];
    [[SPTRequest sharedHandler] performRequest:request
                                      callback:^(NSError *error, NSURLResponse *response, NSData *data) {
                                          if (!error) {
                                              NSError *parsingError = nil;
                                              SPTTrack *track = [SPTTrack trackFromData:data
                                                                       withResponse:response
                                                                              error:&parsingError];
                                              
                                              [self.arrURIs addObject:track];
                                              [self.player playURIs:self.arrURIs fromIndex:0 callback:nil];
                                              
                                          }
                                      }];

Please let me know if anything is missing from the code.

**Comment by Kry256** [comment]
It seems ok. i run it with your same parameters for market and spotify url and it works for me.
Which crash are you experiencing?

**Comment by ram2386** [comment]
Simple Track Playback[783:96977] -[SPTTrack absoluteString]: unrecognized selector sent to instance 0x175cb7e0

**Comment by ram2386** [comment]
@Kry256 : Please let me know which version of spotify_ios_sdk you are using as I have "ios-sdk-beta-9" which cause the issue.

**Comment by Kry256** [comment]
Me too. Probably the issue is in the lines  
```self.arrURIs = @[track];```
```[self.player playURIs:self.arrURIs fromIndex:0 callback:nil];```
You are passing to **playURIs:** function an array of **SPTTrack**.
May be this cause the issue.
Try this
```self.arrURIs = @[track.playableUri];```

**Comment by ram2386** [comment]
Thank you so much @Kry256 for your help it works.

**Comment by erdtman** [comment]
Sorry for not getting back earlier. In an attempt to get a better overview of the issues we are cleaning out some of the older issues. If this issue is still a problem in the latest SDK please reopen this issue or open a new one.
