### ISSUE TITLE
How to get most relevant search of artist .

### ISSUE THREAD

**Issue by anupamwcities** [spotify/ios-sdk#344]
Hi, I am searching artist to get there Id , for this if i am looking on web API console from here - https://developer.spotify.com/web-api/console/get-search-item/?q=tania+bowra&type=artist#complete , for the artist named 'Beck' , getting the artist named "Christophe Beck"  first , then "Beck" on second position. Same result i am getting in IOS SDK beta 8 . Please tell me how to get most relevant search result in shorted order of artist name .

**Comment by possan** [comment]
There's unfortunately no good way to do this right now. you're stuck with doing a search, then iterating the results and picking either the most popular one, or the one with an exact matching of the artist name.

**Comment by erdtman** [comment]
This is a question to web-api, if this is still a problem report it to them.
