### ISSUE TITLE
Searching for a specific artist's track

### ISSUE THREAD

**Issue by mph070770** [spotify/ios-sdk#345]
Hello all,

I'm very new to this iOS SDK and to iOS programming in general. I have the demo player built and working and have made some of my own modifications. I'd now like to add a search that will find a specific track by a specific artist - such as "Mamma Mia" by "ABBA". I've been trying to use:

```
SPTRequest performSearchWithQuery:@"ABBA" queryType:SPTQueryTypeArtist session:nil callback:^(NSError *error, SPTListPage *object
```
but this only searches for the artist, how do I add a track name? Also, I've been getting partial results when performing track searches. I assume I need to allow time for the search to complete - so need to implement callbacks? Can anyone give me some sample code that does what I need? I'd be very very grateful!

Thanks
Martin

**Comment by anupamwcities** [comment]
Hi Martin , for Track do something like this -

     [SPTRequest performSearchWithQuery:@"Mamma Mia" queryType:SPTQueryTypeTrack 
    session:session callback:^(NSError *error, id object)
    {       
        if (error != nil  || [(SPTListPage*)object items].count <= 0)
        {
            NSLog(@"*** Auth error: %@", error);
            errorBlock(error);
            return;
        }        
          NSArray *results = [(SPTListPage*)object items];
    }];

then get artist of track OR for Artist - 

     [SPTRequest performSearchWithQuery:@"ABBA" queryType:SPTQueryTypeArtist 
     session:session callback:^(NSError *error, id object)
     {       
     if (error != nil  || [(SPTListPage*)object items].count <= 0)
    {
        NSLog(@"*** Auth error: %@", error);
        errorBlock(error);
        return;
    }        
      NSArray *results = [(SPTListPage*)object items];
    }];
then get track of particular artist . Hope will help you.

**Comment by mph070770** [comment]
Thanks anupamwcities.

One more question, is there an efficient way to navigate the returns array of results? It looks like I want to search through "results" and find the relevant index that is "ABBA" and then grab the URI for that index?

Thanks
Martin

**Comment by mph070770** [comment]
I think I'm now more confused than ever. In trying to get this working, my results for the search are no longer in object. Previously I could examine _items and see example tracks, and dump them to the console with NSLog. I'm now getting no results. Is this the partialartist issue I mentioned in my first post? If so, how do I provide enough time for the search results to complete?

Thanks again anyone who can provide an insight into this.

![image](https://cloud.githubusercontent.com/assets/508539/7752063/62352212-ffd5-11e4-8a6b-8ffd97ffc639.png)

Thanks
Martin

**Comment by mph070770** [comment]
For anyone interested in this thread, this is what I did to get it working i.e. get partialresults into full results. I'd be keen on comments if you think there's a better way but this works. (Thanks again anupamwcities for pointing me in the right direction):

```
-(void) SpotifySearchTrack: (NSString*)searchArtist searchTrack:(NSString*)searchTrack {
    [self searchSPTracks:self.session searchQuery:searchTrack completionHandler:^(SPTListPage *trackList, NSString *error) {
        NSArray* tempArray = trackList.items;
        self.spotifySearchResults = [tempArray mutableCopy];
        [self.tableView reloadData];
    }];
}

-(void)searchSPTracks: (SPTSession*)session searchQuery: (NSString*)searchQuery completionHandler:(void(^)(SPTListPage* trackList, NSString *error)) completionHandler; {
    [SPTRequest performSearchWithQuery:searchQuery queryType:SPTQueryTypeTrack session:session callback:^(NSError *error, SPTListPage* trackResults) {
        if (error != nil) {
            NSLog(@"%@", error);
            return;
        }
        completionHandler(trackResults, nil);
    }];
}

```
