### ISSUE TITLE
Init Error: 5 with SPTAudioStreamingController

### ISSUE THREAD

**Issue by SKumarSpace** [spotify/ios-sdk#346]
if (!self.player) {
        NSLog(@"initPlayer");
        self.player = [[SPTAudioStreamingController alloc] initWithClientId:[SPTAuth defaultInstance].clientID];
    }
On this piece of code. Any Ideas?

**Comment by possan** [comment]
Are you sure you're setting the clientID correctly, and that it's the correct value?

Error 5 points to an invalid argument

**Comment by SKumarSpace** [comment]
Yup, because it works fine sometimes

**Comment by SKumarSpace** [comment]
Hmm... Could it be anything else?

**Comment by erdtman** [comment]
Sorry for not getting back earlier. In an attempt to get a better overview of the issues we are cleaning out some of the older issues. If this issue is still a problem in the latest SDK please reopen this issue or open a new one.
