### ISSUE TITLE
encryptedRefreshToken is being displayed as NULL

### ISSUE THREAD

**Issue by triplej86** [spotify/ios-sdk#347]
Hello, 

The iOS app I am working on will be simply requesting the authorization access from the users and most of the sptfy functions will happen on the backend. 

Right now I am able to correctly get the access token via:

[[SPTAuth defaultInstance] session] accessToken]

I need to pass the access token along with the encryptedRefreshToken to the backend so the server can always refresh the access token when it expires. The following is always being displayed as NULL:

[[SPTAuth defaultInstance] session] encryptedRefreshToken]

Can you please tell me what I am doing wrong? 

Thanks

**Comment by possan** [comment]
If you're not getting a refresh token, that either means that you're using the "implicit grant"-flow, in that case you won't get any refresh token at all, or if you're using "authorization code"-flow your backend doesn't respond with a refresh token correctly.

**Comment by triplej86** [comment]
Thanks possan. 

I want to be using the authorization code flow. However I am not sure how to do so as the documentation on the iOS for this is very lacking. 

All I have done so far is followed the tutorial listed and I am able to get an access token. The confusing section is that there is barely any mention of the swap service. 

It only mentions this:

"In the method we ask SPTAuth to check if the URL given is a Spotify authentication callback and, if so, we call your token swap service (see the Readme in the download package for more information on this) to get an access token. "

So I have setup the swap server and refresh service url on the backend. What shall I do with them and how can I tie them in to the authentication process. 

Thanks

**Comment by nicolaka** [comment]
@possan thanks for you help , myself and @triplej86  set up the backend service using (https://github.com/plamere/spotify_token_swap/blob/master/spotify_token_swap.py) . It is set up on public server( with /swap and /refresh endpoints). In the spotify_token_swap.py, I supplied the following

k_client_id = <my spotify app id>
k_client_secret = < my spotify app secret>
k_client_callback_url = < my ios app callback uri that we set up in xcode>

Then @triplej86 , is using the following in ios app
     NSURL *swapServiceURL = 
        [NSURL # urlWithString:@"<public_ip_where_swap_service_runs>/swap"];
    
        -[SPAuth handleAuthCallbackWithTriggeredAuthURL:url
               tokenSwapServiceEndpointAtURL:swapServiceURL callback:callback];

I'm receiveing POST /swap HTTP/1.1" 401 27 "" " CFNetwork/711.1.12 Darwin/14.1.0"
with a 401
{"error": "invalid_client"}

Not sure what we're missing here? Also, is there any other method to do this process without a separate swap service? with Facebook and other services, I am sending the access token that I'm getting on the iOS to my backend and then I'm storing it and refreshing it with server-to-server requests. Is there another way to get the authorization code or refresh token on ios then pass them to server side for them to refresh them?

Thanks!

**Comment by triplej86** [comment]
Hey guys... any update on this please? 

Thanks

**Comment by freespirit83xyz** [comment]
Same issue
*** Failed to log in: Error Domain=com.spotify.auth Code=200 "invalid_client" UserInfo=0x14ec9810 {NSLocalizedDescription=invalid_client}

**Comment by erdtman** [comment]
We are relying on standard OAuth so you can always implement the flows without the help of our SDK (https://developer.spotify.com/web-api/authorization-guide/). then you get the refresh token and can store it server side on your user accounts.

If you use the SSO flow make sure that you have the correct bundle id registerd on your app in the developer portal.
