### ISSUE TITLE
SPTAudioStreamingController  loginWithSession callback not called the second time

### ISSUE THREAD

**Issue by hauran** [spotify/ios-sdk#348]
Running the Simple Track Playback example app works fine.

But if for example, you want to change playlists, and call SPTAudioStreamingController  loginWithSession a second time, the callback is never executed.

**Comment by possan** [comment]
You shouldn't have to log in and log out for every play action, just call playURIs again.

**Comment by hauran** [comment]
got it. is there a preferred way to check if SPTAudioStreamingController is logged in?

**Comment by SKumarSpace** [comment]
Yeah, SPTAudioStreamingController has a BOOL property named loggedIn.

**Comment by hauran** [comment]
perfect thanks.

**Comment by mhuusko5** [comment]
So.. you shouldn't have to login/logout.. but this doesn't change the fact that logging in works, logging out works, but logging in a second time fails. This seems like a pretty serious bug.

**Comment by ahallora** [comment]
+1
