### ISSUE TITLE
App Remote connection fails - Error 1000 - 

### ISSUE THREAD

**Issue by jacobconley** [spotify/ios-sdk#35]
I have created a project that follows the Quick Start pretty closely - Upon attempting to connect the app remote, I get the below error: 

```
[SPT/APP][!] Connection failure: %@ Optional(Error Domain=com.spotify.app-remote 
Code=-1000 "Connection attempt failed." UserInfo={NSLocalizedDescription=Connection attempt failed., 
NSUnderlyingError=0x1c0657940 {Error Domain=com.spotify.app-remote.transport Code=-2000 "Stream error." UserInfo={NSLocalizedDescription=Stream error., NSUnderlyingError=0x1c4842010 {Error Domain=NSPOSIXErrorDomain Code=61 "Connection refused" UserInfo={_kCFStreamErrorCodeKey=61, _kCFStreamErrorDomainKey=1}}, NSLocalizedRecoverySuggestion=Reconnect the transport to the Spotify app., NSLocalizedFailureReason=A stream error has occured in the transport.}}, NSLocalizedRecoverySuggestion=Ensure the Spotify app is installed, and try to reconnect., NSLocalizedFailureReason=Could not connect to the Spotify app.})
```

Noting the codes for the main error and the UnderlyingError and  checking the docs for `SPTAppRemoteErrorCode` I see -1000 meaning a Background Wakeup Error caused by a -2000 meaning an invalid arguments error, but I am setting the access token for the `AppRemote.connectionParameters`, and I know that this access token is valid because it is used in a successful web API request.  I am out of ideas to debug this.

Any help would be greatly appreciated

**Comment by jackfreeman** [comment]
@jacobconley is Music playing when you attempt to connect? 

Note that the Spotify app must be playing music when in the background  and attempting to connect to ensure it is awake and not in a suspended state. You can ensure it's playing music with either `SPTAppRemote`'s `authorizeAndPlayURI` call  or if using `SPTSessionManager` by setting `playURI` to a blank string on `SPTConfiguration` as seen in the demo app [here](https://github.com/spotify/ios-sdk/blob/master/DemoProjects/SPTLoginSampleAppSwift/SPTLoginSampleAppSwift/ViewController.swift#L12)

**Comment by jacobconley** [comment]
@jackfreeman I did not realize that the app had to be playing music - this has solved my issue.  Thanks for your quick response on a Friday evening, I appreciate that a lot

**Comment by shavik** [comment]
The issue at my end I am facing is that whenever I fresh install of the app appRemote does not connect but the app can play a song, but on subsequent launches, appRemote connects.
Something is weird.

**Comment by jacobconley** [comment]
@shavik I struggled with similar issues for a while.  I wound up just giving it a small delay before connecting the app remote - terrible solution, but it worked for me.  I forget why I put it on the main queue, I think I remember getting some strange errors when trying a different thread

Here's an edited piece of my current implementation.  (The `after` dispatch method is a simple convenience method in an extension, implemented using `asyncAfter`)


    func appConnect(uri) {
        AppRemote.authorizeAndPlayURI(uri)
      
        DispatchQueue.main.after(1.5) {
            AppRemote.connectionParameters.accessToken = SessionManager.session?.accessToken
            AppRemote.connect()
        }
    }
