### ISSUE TITLE
Spotify paused playing the current track while loading the next tracks of other artists

### ISSUE THREAD

**Issue by anupamwcities** [spotify/ios-sdk#350]
I am using **ios-sdk beta 8** in my application. I have more than 50 artists , I wants to get top 10 tracks of each artist & display it in a tableview . I am getting the top 10 tracks of each artists which is proper, as i am getting top 10 track of a single artist I wanted to play it while loading the tracks of remaining artists but **SPTAudioStreamingController** won't allow me to do show , it stopped playing the tracks until it get the tracks of all the artists.
My question is -

   - Is it possible to play already loaded tracks while loading the next tracks of other artists.
   - If it is restriction from Spotify then how can I meet my requirement . any idea . please help. Thanks

**Comment by erdtman** [comment]
Sorry for not getting back earlier. In an attempt to get a better overview of the issues we are cleaning out some of the older issues. If this issue is still a problem in the latest SDK please reopen this issue or open a new one.
