### ISSUE TITLE
Beta 8 - tracksWithURIs:session:callback: number limited in array

### ISSUE THREAD

**Issue by plougy** [spotify/ios-sdk#352]
Hi,

I found a strange comportment on the **Beta 8**. When I use `SPTTrack tracksWithURIs:session:callback:` with an array of more **50** items. In the callback, the _error_ and the 
_object_ (NSArray) are both set on `nil`.

Do you have any solution?

**Comment by possan** [comment]
This is a limitation in the Web API, but yes, that should probably result in a better error message.

**Comment by RocketCity** [comment]
Same for `SPTAlbum.albumsWithURIs`.  The limit seems to be 20.  When requesting more than 20 the callback error and object are both nil -- should respond with an error.

**Comment by erdtman** [comment]
We are deprecating the iOS-Metadata library.

The source code of the iOS-Metadata library has been released and can be found [here](https://github.com/erdtman/spotify-ios-metadata/). Spotify will not continue to maintain the released source code.

Either you can select to use the web-api directly or use the new open source iOS-Metadata library.

I will close this issue now.

We are sorry for the inconvenience that this creates, but looking back we think this is the best path forward.
