### ISSUE TITLE
Combination of webapi with SDK, and authentication

### ISSUE THREAD

**Issue by mph070770** [spotify/ios-sdk#353]
Hi. I'm trying to use some of the features of the web API along with the SDK (specifically to see if I can get more flexible track searching). I've achieved searching without a problem as it doesn't use authentication. However, trying to add a track to a playlist fails. I'm using the auth token that the SDK gives me, and I have privileges to read/write my playlists. I'm constructing the command as follows:

```
requestFields = [requestFields stringByAppendingFormat:@"https://api.spotify.com/v1/users/my_name/playlists/0VpD39qOaV3AgYhaJsZCsm/tracks?uris=spotify:track:4iV5W9uYEdYUVa79Axb7Rh,spotify:track:1301WleyT98MSxVHPZCA6M -H ""Authorization: Bearer %@", auth.session.accessToken]; 
```
which results in this:
```
https://api.spotify.com/v1/users/my_name/playlists/0VpD39qOaV3AgYhaJsZCsm/tracks?uris=spotify:track:4iV5W9uYEdYUVa79Axb7Rh,spotify:track:1301WleyT98MSxVHPZCA6M%20-H%20Authorization:%20Bearer%20BQChUSzhHcb1qOwLYDr9jtYm3XU33VMi822Or8k4FgjDZ8L-qXWDQZB4o2sW9hEaSentuyTfT-cNR3oCLAV6rQqPuwP_SNCd9wy08tw9oTN7LisVTJ04VzJuxsaQWNl-uY23HTigbp9FS2fp6s2SRZy_sZRbCqS2vx7P_Uy6aqXOcxkkhPEoMk8XLeQWaY1cXuqp9VmGcLziAY6DImr5mp7jEvM8M7FWUiw0zMinGRcD7ExPLwe_zVMfM7pD
```
but it doesn't work and when I try the URL in a browser I get the following:

```
{
  "error": {
    "status": 401,
    "message": "This request requires authentication."
  }
}
```

am I forming the URL incorrectly? I can curl the URL successfully like this:

Thanks

**Comment by ronakvora** [comment]
What was the issue?

**Comment by nighthawk** [comment]
This should be working as long as you send the token as a header, rather than appending it to the URL.
