### ISSUE TITLE
When setIsPlaying:No is called from background, app crashes

### ISSUE THREAD

**Issue by jeffb6688** [spotify/ios-sdk#354]
When the iPod controls are used from lock screen to pause the Spotify music player, the pause indication is received by remoteControlReceivedWithEvent and I attempt to pause the player with setIsPlaying:No. This results in the app crashing. The code looks like the following:

    remoteControlReceivedWithEvent: (UIEvent*) event {
        ...
        [spotifyPlayer setIsPlaying: NO callback:nil];
    }

If I use the iPod controls from lock screen to fast forward or rewind using 

    [spotifyPlayer skipNext:nil]; 

or 

    [spotifyPlayer skipPrevious:nil];, 

all is well. These functions work as expected in the background.

Note that when the pause button is pressed, I also receive a call to the delegate method:

    -(void)audioStreaming:(SPTAudioStreamingController *)audioStreaming didChangePlaybackStatus:(BOOL)isPlaying {
   }

where isPlaying is false. Does this sound like a bug with setIsPlaying:NO ? Am I doing something incorrectly?

**Comment by kevin--** [comment]
Not happening to me. Try passing a callback -- perhaps they don't like a nil callback for that one? If you are getting the delegate method called, then it should be working fine. What's the callstack look like on the crash?

**Comment by jeffb6688** [comment]
I am already passing a callback (I just put nil in the description above to abbreviate the code). However, I am not getting a callstack. Now I see that it is not actually crashing. It just has the illusion of crashing because the iPod controls disappear, thus exposing just the lock screen. If I comment out the line

    [spotifyPlayer setIsPlaying: NO callback:nil];

then the iPod controls remain visible (although the music continues to play as you would expect). Can you think of any reason why the iPod controls would disappear (and only for the pause button)?

**Comment by kevin--** [comment]
Yes. Spotify SDK controls the state of the AVAudioSession "active" property. Pausing probably sets the session inactive, relinquishing the remote control

I have filed an enhancement for the behavior since it interferes with my own app
https://github.com/spotify/ios-sdk/issues/238

**Comment by jeffb6688** [comment]
Ok. Thanks. After further investigation, I have found that if include the following code when my app enters the background and when the remote control events are received, the iPod controls do not disappear.

    
        
        // Set up info center to display album artwork within ipod controls (needed for spotify)
        MPMediaItemArtwork *ipodControlArtwork = [[MPMediaItemArtwork alloc]initWithImage:artworkImage];
        [MPNowPlayingInfoCenter defaultCenter].nowPlayingInfo = [NSDictionary dictionaryWithObjectsAndKeys:nowPlayingTitle, MPMediaItemPropertyTitle,
                                                                 nowPlayingArtist, MPMediaItemPropertyArtist, ipodControlArtwork, MPMediaItemPropertyArtwork,  0.0, MPNowPlayingInfoPropertyPlaybackRate, nil];

**Comment by erdtman** [comment]
Sorry for not getting back earlier. In an attempt to get a better overview of the issues we are cleaning out some of the older issues. If this issue is still a problem in the latest SDK please reopen this issue or open a new one.
