### ISSUE TITLE
Auth redirect to Spotify App results in INVALID_REQUEST: Invalid app Identifier

### ISSUE THREAD

**Issue by LandonRover** [spotify/ios-sdk#357]
Today the auth workflow randomly started acting differently, and instead of a web view, it's redirecting to the user installed Spotify app. This results in an error message "INVALID_REQUEST: Invalid app Identifier".

I am authenticating via the SPTAuthViewController currently:
```swift
SpotifyHelper.sharedInstance.authenticate { (authenticated, authViewController) -> () in
      if !authenticated {
        if let authViewController = authViewController {
          self.presentViewController(authViewController, animated: false, completion: nil)
        }
      }
    }
```
![screen shot 2015-06-04 at 2 26 56 pm](https://cloud.githubusercontent.com/assets/9013138/7991390/d46be104-0ac5-11e5-9a2a-6bf054e4cdaf.png)

**Comment by Snppls** [comment]
+1

**Comment by rubenvdb** [comment]
+1

**Comment by seanmcdonald** [comment]
+1

**Comment by ak1394** [comment]
+1

**Comment by Navideck-fotis** [comment]
+1

**Comment by thomasvsundert** [comment]
+1

**Comment by mph070770** [comment]
+1

**Comment by Zwaaan** [comment]
+1

**Comment by xeppex** [comment]
+1

**Comment by JenssRey** [comment]
+1

**Comment by timsk159** [comment]
+1

**Comment by possan** [comment]
I'll try to get a fix for this out today, this is something that was introduced with the latest spotify client..

**Comment by possan** [comment]
There's now a beta 9 with this breaking issue fixed.

**Comment by thomasvsundert** [comment]
Hi Possan,
we actually have a couple of apps live that now no longer work.
Isn't there a solution that fixes things for apps using the current version?

**Comment by jdecoster** [comment]
@possan +1

**Comment by mph070770** [comment]
beta 9 seems to just have this fix? I've built my app with it and all other functionality is ok and the authentication problem is fixed. Thanks Possan.

**Comment by Snppls** [comment]
@possan beta 9 does seem to fix this issue but it's no solution for the apps that are currently live in the store.

This couldn't have come at a worse time for us. We added Spotify playback to one of our apps, an app for a music event that takes place in a couple days. There's not enough time to submit an update.

Isn't it possible for you guys to get rid of the redirect to spotify:// in whatever link the web view of the SPTAuthViewController uses. Right now in beta 9 it doesn't redirect to the Spotify iOS app either so I don't see why that shouldn't be possible. 
I can't be the only one who's app in the store is broken by the bug.

**Comment by billgert** [comment]
@Snppls +1 We have the same issue, our app is live and we have had around 200 new users/day in the last week. Today we had three... :/

**Comment by Zwaaan** [comment]
@possan How can you release an server update like this which causes all previous apps not to work anymore? How about you give us a chance to update the app before you release something like this.

Since you updated your part which caused the bug, you should be able to revert it without the need for an app update...

Very bad customer service, very bad practice...

**Comment by Zwaaan** [comment]
@Snppls +1 Can't understand how Spotify can treat our users like this...

**Comment by GabeJacobs** [comment]
There has to be a server fix for this. Can you change the web code so the client does not hijack it?

**Comment by ASCrookes** [comment]
+1 to everything above

**Comment by GabeJacobs** [comment]
@possan do you foresee Spotify fixing this any time soon? Or do you suggest we upgrade the beta and resubmit to apple (which takes a week+ for them to review and accept)? Obviously we would rather the first option, but it would be good to know if Spotify has any plans to work on this problem.

**Comment by jeroenjoosen** [comment]
+1

**Comment by possan** [comment]
We're looking into how we could support you guys with existing apps out there, we'll keep you updated as soon as we know more

**Comment by possan** [comment]
We have a solution for your existing apps!

If you just send an email to sdk-support@spotify.com with your client id and the bundle id of your ios app, we'll make sure your existing apps will start working with the changed login flow. If you want, include a link to the app so we can verify that it works too.

**Comment by LandonRover** [comment]
@possan, can we start using the new login flow with the new beta? Should we email sdks-support as well. I'll hold off until you let us know. Thanks for supporting the other guys :+1:

**Comment by possan** [comment]
The idea is that you should set this bundle id (and package name on android) in the application settings page on the developer website but since that's not currently possible, and since this feature was rolled out a bit too fast :hankey: hit the fan.

If you use beta 9 - don't worry yet, we'll make the ui changes soon, if you have existing stuff on beta 8 out now, please send us an email.

**Comment by possan** [comment]
This will only work if the app handles a new session being passed through the callback of [SPTAuth handleAuthCallbackWithTriggeredAuthURL] (it will unfortunately not fire the success callback in SPTAuthViewController)

**Comment by GabeJacobs** [comment]
@possan So this was not a solution? For us the auth popover just is blank after logging into Spotify now. What do you suggest we do? Is it not possible to fix this on the server? Do the Spotify iOS people know about this? Maybe they can provide a workaround on their server which will call the success callback. Or should we rush a fix to Apple right now and hope they approve it soon?

**Comment by possan** [comment]
There's unfortunately no server side fix we can do for this, and an updated app would still be a few weeks away before it could get out, and then you are still relying on them updating their apps.

**Comment by GabeJacobs** [comment]
@possan Okay. Do you suggest we update to beta 9 and just forget this whole new auth process. Or should we implement handleAuthCallbackWithTriggeredAuthURL ad stick with beta 8. We want to do whatever will be safe from here on out so this does not happen again.

**Comment by possan** [comment]
I'd suggest doing both, beta 9 was a quick fix just to disable the actual jump TO the spotify app, but will not add support for coming back from it. adding the handleAuthCallbackWithTriggeredAuthURL (like the example and tutorial does) will support coming back from the Spotify app too.

We're aware this is of course not a great solution, but unfortunately the only possible one right now.

**Comment by GabeJacobs** [comment]
Ok. So we'll use beta 9 which won't go to the Spotify app, but implement handleAuthCallbackWithTriggeredAuthURL so that in future betas it will work.

**Comment by possan** [comment]
Yes, that's the best bet right now

**Comment by kevin--** [comment]
Does this issue affect SDK 7?

**Comment by possan** [comment]
It should not affect beta 7

**Comment by GabeJacobs** [comment]
Just to give an update. We still have beta 8 on our platform, but integrated the new login flow with handleAuthCallbackWithTriggeredAuthURL. We requested an expedited review from apple and got it approved. So all set now. But can we confirm this process will not break in future iOS Spotify updates?

**Comment by nathanandersen** [comment]
+1

**Comment by bassntweeter** [comment]
@nathanandersen You have to register your app bundle id on your area on developer.spotify.com, see the guide: [https://developer.spotify.com/technologies/spotify-ios-sdk/](url)
