### ISSUE TITLE
SPTBrowse.requestNewReleasesForCountry returns SPTListPage with 0 items

### ISSUE THREAD

**Issue by uknowmeright** [spotify/ios-sdk#358]
Is anyone else experiencing issues with the new Browse callbacks?

I have tried multiple parameters but when I print out the resulting SPTListPage it prints the following: 

    <SPTListPage: 0x1744874e0>: 0-18446744073709551615 of 0 items

My callback method looks like this:

    SPTBrowse.requestNewReleasesForCountry("US", limit: 50, offset: 0, accessToken: session.accessToken) { (error, ReturnedList) -> Void in
            if (error != nil) {
                println(error)
                return
            }

    .......

    }

**Comment by ak1394** [comment]
Yes, I had the same problem. Worked around by using SPTBrowse.createRequestForNewReleasesInCountry() instead.

**Comment by uknowmeright** [comment]
Does this return the list on its own or do I have to somehow "execute" this request via a different method?

**Comment by ak1394** [comment]
I do following:

let request = SPTBrowse.createRequestForNewReleasesInCountry("US", limit: 50, offset: 0, accessToken: accessToken, error: nil)
    
    NSURLConnection.sendAsynchronousRequest(request, queue: NSOperationQueue.mainQueue()) {(response, data, error) in
        let page = SPTBrowse.newReleasesFromData(data, withResponse: response, error: nil)
        if page.totalListLength > 0 {
           // got data
        }
    }

**Comment by uknowmeright** [comment]
Thank you for your quick response. Could you also show your SPTBrowse.createRequestForNewReleasesInCountry() method? I cannot seem to get it to work.

**Comment by uknowmeright** [comment]
Thanks for the quick reply. I am able to return a list of songs but they don't seem to be playable. When I try to play one via my streaming controller i get:

     Error Domain=com.spotify.ios-sdk.playback Code=4 "An unexpected NULL pointer was passed as an argument to a function." UserInfo=0x174665f80 {NSLocalizedDescription=An unexpected NULL pointer was passed as an argument to a function.}

**Comment by uknowmeright** [comment]
Nevermind I solved it. I Didn't realize it was returning Albums.

**Comment by ak1394** [comment]
Did the SPTBrowse.requestNewReleasesForCountry worked for you or you've used SPTBrowse.createRequestForNewReleasesInCountry?

I think the createRequestForNewReleasesInCountry is broken, so it might be a good idea to keep the ticket open.

**Comment by uknowmeright** [comment]
No, I used your workaround. Yeah probably a good idea to keep it open.

**Comment by erdtman** [comment]
Sorry for not getting back earlier. In an attempt to get a better overview of the issues we are cleaning out some of the older issues. If this issue is still a problem in the latest SDK please reopen this issue or open a new one.
