### ISSUE TITLE
How to use Spotify Connect with SPTAudioStreamingController

### ISSUE THREAD

**Issue by EsbenRud** [spotify/ios-sdk#359]
Hi, is it possible to connect to Spotify Connect from your SPTAudioStreamingController or another controller. Without being able to use Spotify Connect from your API then third-party apps only can work the local audio device and that seems poor to me.

**Comment by possan** [comment]
This is currently not possible, this is of course a feature we want to add at some point.

**Comment by zakmandhro** [comment]
**+1**

Any decisions on including this in the SDK?

This is the # 1 request for our users and I'd like to give the users a sense of timeline.

**Comment by loretoparisi** [comment]
+1
We are getting a lot of  users asking for the Spotify Connect as well!

**Comment by kemuri** [comment]
+1. Would be nice to write Spotify connect clients.

**Comment by chrishale** [comment]
+1

**Comment by erdtman** [comment]
there is no current plans to add connect support to the iOS-SDK
