### ISSUE TITLE
Controlling the AppRemote while the app is in background

### ISSUE THREAD

**Issue by jacobconley** [spotify/ios-sdk#36]
I've noticed that calls to the AppRemote fail while my app is in the background.  Are there any plans to support this in the future?  Or perhaps is this just a limit of iOS?

**Comment by jackfreeman** [comment]
iOS has some limitations in regards to opening apps from other apps while backgrounded. If your app is not in a suspended state and App Remote is connected you might be able to send commands while both apps are backgrounded.
