### ISSUE TITLE
queueURIs:clearQueue:callback Deprecated or not?

### ISSUE THREAD

**Issue by fotiDim** [spotify/ios-sdk#360]
I can see in SDK 9 that the method is not marked as "DEPRECATED_ATTRIBUTE" but in the description it says that " This function is deprecated and will be removed in the next version."

Is there any queue alternative of I need to implement it myself?

**Comment by plougy** [comment]
I asked myself the same question there is few days. It's confusing.

You can use `playURIs:withOptions:callback:` or you must to implement by yourself if you need to have a queue.

**Comment by CVertex** [comment]
Did anyone find out any official way to do this? 

How do you implement the queue yourself? My first guess would be wait for the current song to finish and then call playURIs again. I've tried this and there's a noticeable pause before next song begins streaming. I preferred the queuing API as there wasn't the same pause.

**Comment by chrishale** [comment]
:+1: I'd also like this. I can't find the correct delegate methods to use for when I should be calling `playURIs:withOptions:callback:`. I thought `audioStreaming:didStopPlayingTrack` could work, but I'm getting a recursive loop, that blasts though all the songs haha.

**Comment by erdtman** [comment]
queueURIs and clearQueue has been removed
