### ISSUE TITLE
ios sdk streaming thread stays after login.

### ISSUE THREAD

**Issue by egouletlang** [spotify/ios-sdk#361]
I am using the ios spotify sdk in my app for track playback.  I can play songs just fine, but im facing a battery issue.  After i log into the player, my cpu stays at a constant 1%, even before trying to stream a song.  This continues to be a problem after I play and stop a song.  

The thread that remains active is:  com.spotify.AudioStreaming.

I guess I could log into the player whenever the user wants to stream a song, then log back out when he or she is done... but im trying to avoid that.

Here's how i setup my player

//SWIFT Code
session = SPTSession(userName: username, accessToken: accessToken, expirationDate: nil)
player = SPTAudioStreamingController(clientId: clientId)
        
player.loginWithSession(session) { (error) -> Void in
      ... check for reauth ....
}

any thoughts? anyone facing a similar issue?

**Comment by possan** [comment]
What happens if you call logout on the streaming controller? then it shouldn't remain active.

**Comment by egouletlang** [comment]
I am experiencing this problem even when i don't call loginWithSession(...).  For me (iphone 6+, ios 8.3, XCode 6.3.1), adding: 

        session = SPTSession(userName: nil, accessToken: accessToken, expirationDate: nil)
        player = SPTAudioStreamingController(clientId: clientId)

to a project keeps the CPU at a constant 1%.  When i remove those two lines, the CPU stays at 0%.

Do you think logging in and out would help?  Can you reproduce this?  Ive tried using spotify sdk 6, 8.  I see theres a new sdk on the website, maybe the problem is fixed in this release.

**Comment by egouletlang** [comment]
any news? are you able to reproduce this issue?

**Comment by EgaSetya** [comment]
did you solved this issue?

**Comment by egouletlang** [comment]
No this is a still a problem, and it's preventing me from integrating the sdk into my product.

As it stands, even just instantiating the class without logging in keeps the cpu level at 1% according to Xcode.

**Comment by virenenskully** [comment]
I'm seeing "com.streaming" threading consuming lot of CPU as well. I have not even logged in, nor streaming anything (of course) and still the thread steals away a great many CPU cycles. I'm sorry to say this but why is spotify SDK so buggy? Something as big as Spotify could do lot better. Just saying!

**Comment by erdtman** [comment]
Sorry for not getting back earlier. In an attempt to get a better overview of the issues we are cleaning out some of the older issues. If this issue is still a problem in the latest SDK please reopen this issue or open a new one.
