### ISSUE TITLE
removeTracksFromPlaylist:withAccessToken:callback: not working

### ISSUE THREAD

**Issue by fotiDim** [spotify/ios-sdk#364]
The callback returns without error but the track is not removed from my custom playlist.

**Comment by marianolatorre** [comment]
I had similar issue: http://stackoverflow.com/questions/30607200/removetracksfromplaylist-not-removing-tracks-with-ios-spotify-sdk#

**Comment by marianolatorre** [comment]
I solved my issue by reseting simulator + adding SPTAuthPlaylistModifyPublicScope (which I fogot to do...)
auth.requestedScopes = @[SPTAuthStreamingScope, SPTAuthPlaylistModifyPublicScope];

**Comment by Navideck-fotis** [comment]
@marianolatorre I am already using that scope. I can add tracks to playlist fine. Problem is I cannot remove them.

**Comment by marianolatorre** [comment]
are you doing anything similar to this:

                SPTAuth *auth = [SPTAuth defaultInstance];
                [self.currentPlaylistSnapshot removeTracksFromPlaylist:@[self.player.currentTrackURI]
                                            withAccessToken:auth.session.accessToken
                                            callback:^(NSError *error) {
                                                if (error != nil) {
                                                    NSLog(@"*** Failed to remove track : %@", self.titleLabel.text);
                                                    return;
                                                }
                                            }];

**Comment by Navideck-fotis** [comment]
Actually I was passing a partial track instead of the URI but both seem to be valid (just tested yours). However the problem still remains. Someone from Spotify has to look into it I am afraid. Thanks for the help!

**Comment by Navideck-fotis** [comment]
Just for the record the playlist I am tampering with is a public playlist created from my app. The scopes I am asking for are "SPTAuthStreamingScope, SPTAuthUserReadPrivateScope, SPTAuthUserReadEmailScope, SPTAuthPlaylistModifyPublicScope"

**Comment by fotiDim** [comment]
This is still an issue for me. Can somebody from Spotify please look into this?

**Comment by erdtman** [comment]
Have you verified if this is and issue when using the web-api directly without the iOS-SDK wrappers? i.e. https://developer.spotify.com/web-api/remove-tracks-playlist/

**Comment by erdtman** [comment]
Since there has not been any followup comments I will close this issue for now. If the issue persists please reopen this issue.
