### ISSUE TITLE
SPTAudioStreamingController playURI:fromIndex:callback: deprecated

### ISSUE THREAD

**Issue by jeffb6688** [spotify/ios-sdk#365]
I see that the latest spotify ios-sdk has deprecated many of the previous interfaces for playing URIs. If I continue to use Beta 6 sdk, will these previous interfaces that I am using within my iOS app (e.g. playURI:fromIndex:callback:) stop working at some point in time? If so, how long do I have to get my app updated before it breaks?

**Comment by possan** [comment]
the playURI has just been replaced with playURI(s) which takes a list of track URI's instead of a single track uri. so just switch to that one.

**Comment by jeffb6688** [comment]
Ok, to do this it appears that I have to replace my Beta7 Spotify.framework with Beta9 Spotify.framework because SPTPlayOptions is undefined. When I do that, certain methods and interfaces are marked as deprecated even though the documentation does not indicate that they are deprecated. For example, playURI:callback, albumWithUri:session:callback, currentTrackMetadata (and associated keys), performSearchWithQuery:queryType:offset:session:callback:, and many others are marked as deprecated even though the documentation does not indicate this. In addition, some methods are marked as undefined (e.g. loginURLForClientId:withRedirectURL:scopes:responseType:). The documentation I am referring to is at https://developer.spotify.com/ios-sdk-docs/Documents/Classes/SPTAudioStreamingController.html#//api/name/currentTrackMetadata.

Is Beta9 the wrong sdks to use? If not, have I incorrectly replaced beta7 by trashing it and dragging beta9 into Xcode?

**Comment by jeffb6688** [comment]
Please let me know what the deprecation status is for the methods mentioned above. Please let me know correctness of the documentation such as: https://developer.spotify.com/ios-sdk-docs/Documents/Classes/SPTAudioStreamingController.html#//api/name/playURI:callback since it does not seem to match the Xcode warnings I am receiving for these methods.

**Comment by jeffb6688** [comment]
I am closing this in favor of identifying specific documentation problems.
