### ISSUE TITLE
[SPTAudioStreamingController loginWithSession:callback:] is failing to call the callback [beta-8, beta-9]

### ISSUE THREAD

**Issue by timburks** [spotify/ios-sdk#368]
Are there any known circumstances under which [SPTAudioStreamingController loginWithSession:callback:] would not call the provided callback?

Since the callback takes an NSError * argument, I would expect it to always be called, but we've observed that in beta 8 and beta 9, there seem to be situations in which the callback isn't called. As a result, we have not yet upgraded from beta 7, but hope to do so soon.

Also, would this be considered a bug in the SDK? It seems to violate the "contract" of this method.

**Comment by possan** [comment]
Could this be that you have called login once before? i think that's the only known case when it doesn't fire the callback properly

**Comment by timburks** [comment]
Yes, that's the case here. We can restructure our calls to avoid that, and I've found that those changes seem to eliminate the problem. This behavior appeared in beta 8, so although we had some structural problems that exposed it, I hope that we can generally avoid silent failures from the SDK. Also, since you mentioned that this was a "known case", is there some external documentation of this that we missed? Thank you!

**Comment by mhuusko5** [comment]
I don't understand why these bugs are being closed. It should be possible to log back into a streaming controller after logging out, but it just isn't as of Beta 8.
