### ISSUE TITLE
App Rejected - Spotify Login

### ISSUE THREAD

**Issue by piotrbernad** [spotify/ios-sdk#369]
From Apple Review:

```
10.6 Details
Upon further review, we noticed an issue in your app that contributes to a lower quality user experience than Apple users expect. Specifically, your app did not integrate with iOS features. Your app prompts users to link out to Safari for the Spotify login.
```

and then:
```
 It would be appropriate to implement login to Spotify within the app. 
```

Is there any possibility to implement Spotify authrozation without using Safari and web view?

**Comment by possan** [comment]
You can do the same login flow in a UIWebView inside your app, using the latest betas you can use the SPTAuthViewController to handle that for you.

**Comment by bassntweeter** [comment]
Soon we will provide a version of the SDK where you can do the login flow via the Spotify app. Thus rendering that claim from Apple void.
