### ISSUE TITLE
"Save" an album to "Your Music"?

### ISSUE THREAD

**Issue by mhuusko5** [spotify/ios-sdk#37]
The recent Spotify clients (Web, Mac, and iOS at least) feature the ability to "Save" an album to one's "Your Music" section (versus simply adding the contents of that album to a playlist).

Does the Beta iOS SDK implement this API (for that matter, does CocoaLibSpotify or libSpotify even)?

Thanks!

**Comment by erdtman** [comment]
We are deprecating the iOS-Metadata library.

The source code of the iOS-Metadata library has been released and can be found [here](https://github.com/erdtman/spotify-ios-metadata/). Spotify will not continue to maintain the released source code.

Either you can select to use the web-api directly or use the new open source iOS-Metadata library.

I will close this issue now.

We are sorry for the inconvenience that this creates, but looking back we think this is the best path forward.
