### ISSUE TITLE
performSearchWithQuery ignores offset parameter

### ISSUE THREAD

**Issue by oskob** [spotify/ios-sdk#370]
No matter what offset I give to this method, the callback gives me the same results in SPTListPage: <SPTListPage: 0x17428af50>: 0-19 of 3245940 items

    + (void)performSearchWithQuery:(NSString *)searchQuery
    					 queryType:(SPTSearchQueryType)searchQueryType
    						offset:(NSInteger)offset
    				   accessToken:(NSString *)accessToken
    					  callback:(SPTRequestCallback)block;

**Comment by dcristolovean** [comment]
same here, ended up using the deprecated [SPTRequest performSearchWithQuery...].  That one works.

**Comment by erdtman** [comment]
Sorry for not getting back earlier. In an attempt to get a better overview of the issues we are cleaning out some of the older issues. If this issue is still a problem in the latest SDK please reopen this issue or open a new one.
