### ISSUE TITLE
SPTAuth canHandleURL is crashing with NSInvalidArgumentException

### ISSUE THREAD

**Issue by jeffb6688** [spotify/ios-sdk#372]
I have upgraded Spotify from Beta6 to Beta9. One of the necessary changes to support the upgrade is to the canHandleURL method signature. The Beta6 signature was:

    canHandleURL: withDeclaredRedirectURL:

The new signature removes withDeclaredRedirectURL. However, when I try to execute the method with the new signature from my appDelegate in the following manner: 

    -(BOOL)application:(UIApplication *)application
                    openURL:(NSURL *)url
       sourceApplication:(NSString *)sourceApplication
                   annotation:(id)annotation {

        if ([[SPTAuth defaultInstance] canHandleURL:url]) {
        
            [[SPTAuth defaultInstance]
             handleAuthCallbackWithTriggeredAuthURL:url callback:^(NSError *error, SPTSession *session) {
             
                 if (error != nil) {
                     ...
                     return;
                 }
             
                 // Save the session info
                 ...
             }];
            return YES;
        }
        ...
        return NO;
    }

The error is as follows:

    *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '- [__NSCFString hasPrefix:]: nil argument'
    *** First throw call stack:
    (
	0   CoreFoundation                      0x0000000112eeec65 __exceptionPreprocess + 165
	1   libobjc.A.dylib                     0x0000000112b87bb7 objc_exception_throw + 45
	2   CoreFoundation                      0x0000000112eeeb9d +[NSException raise:format:] + 205
	3   CoreFoundation                      0x0000000112e0ee00 -[__NSCFString hasPrefix:] + 96
	4   MyAPP                        0x000000010fa64c0a -[SPTAuth _canHandleURL:withDeclaredRedirectURL:] + 143
	5   MyAPP                        0x000000010fa64c7e -[SPTAuth canHandleURL:] + 82
	6   MyAPP                        0x000000010f9e8c09 -[myAppDelegate application:openURL:sourceApplication:annotation:] + 73
	7   UIKit                               0x0000000111159cd0 __45-[UIApplication _applicationOpenURL:payload:]_block_invoke + 144
	8   UIKit                               0x0000000111159c31 -[UIApplication _applicationOpenURL:payload:] + 333
	9   UIKit                               0x0000000111162328 -[UIApplication _handleNonLaunchSpecificActions:forScene:withTransitionContext:] + 2350
	10  UIKit                               0x0000000111165e71 __88-[UIApplication _handleApplicationLifecycleEventWithScene:transitionContext:completion:]_block_invoke + 196
	11  UIKit                               0x0000000111165d9e -[UIApplication _handleApplicationLifecycleEventWithScene:transitionContext:completion:] + 349
	12  UIKit                               0x00000001111507fa -[UIApplication scene:didUpdateWithDiff:transitionContext:completion:] + 486
	13  FrontBoardServices                  0x00000001175605e5 __31-[FBSSerialQueue performAsync:]_block_invoke_2 + 21
	14  CoreFoundation                      0x0000000112e2241c __CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK__ + 12
	15  CoreFoundation                      0x0000000112e18165 __CFRunLoopDoBlocks + 341
	16  CoreFoundation                      0x0000000112e17f25 __CFRunLoopRun + 2389
	17  CoreFoundation                      0x0000000112e17366 CFRunLoopRunSpecific + 470
	18  GraphicsServices                    0x00000001138f6a3e GSEventRunModal + 161
	19  UIKit                               0x0000000111152900 UIApplicationMain + 1282
	20  MyAPP                        0x000000010f9925b1 main + 97
	21  libdyld.dylib                       0x0000000113420145 start + 1
	22  ???                                 0x0000000000000001 0x0 + 1
    )
    libc++abi.dylib: terminating with uncaught exception of type NSException

This code appears to follow the SDK tutorial, so I am not sure why this is crashing. When I updated the Spotify.framework, I deleted the old one (moved to trash) and I deleted the Derived Data to clear out the cache in the compiler. Then I dragged the new Spotify.framework into Xcode. Can you see if I have made some mistake? Please help.

**Comment by jeffb6688** [comment]
PLEASE provide me with some feedback. The url that I am passing to canHandleURL is:

    "MyApp-login://callback/#access_token=BQDJjk-5er-GeVh6KmQctI_H-OJCec2V0aAREOpvrvBWfuSPPyy4Kzf7RDiolDZjsihxryzI53Plf7Zcd2wiL5l1Rddy9DEnr0SIBbOLYLPNKAKOy26Be0iKbUFXgqS7MrW65JVKO-5igtIBU6ASDaYCOTn3QWY7A3YRzEQSI5xvKrBlcOf3DM-hZ3Dnf6FQ7yfoqCrGFq9_p5rDwj8bexQxtncD73DGyU8uwvIqo4nSN6hsza_n8pAw&token_type=Bearer&expires_in=3600"

Is there something about this url that causes a [__NSCFString hasPrefix:]: nil argument exception?

**Comment by jeffb6688** [comment]
I give up. The method canHandleURL does not seem to work. If I pass either a Facebook url or a Spotify url to it, it crashes. Unless I am using it incorrectly, I don't understand why no one else is complaining. But without your feedback, its pretty hard to tell. 

In order to move forward, I am forced to just sort between callbacks based on the sourceApplication string.

**Comment by ruslan120101** [comment]
+1, also experiencing this crash

**Comment by retendo** [comment]
+1

**Comment by bughana** [comment]
+1

**Comment by chrisjhill** [comment]
+1, Also experiencing this crash, in a live application.

**Comment by loretoparisi** [comment]
I'm not having this issue in my codebase. Since it's due to the

```shell
3   CoreFoundation                      0x0000000112e0ee00 -[__NSCFString hasPrefix:] + 96
```

we need to check all your string formatting like the one by @jeffb6688 

```shell
"MyApp-login://callback/#access_token=XXXXTOKENXXXX&token_type=Bearer&expires_in=3600"
```

Anyways my code that is not crashing is this

```Objective-c
if(session==nil) { // no active session
        if(allowUI) {
            NSURL *loginURL = [SPTAuth loginURLForClientId:kSpotifyClientId withRedirectURL:[NSURL URLWithString:kSpotifyCallbackURL]
                                  scopes:[self getAccessTokenScopes]
                                responseType:@"code"];
            double delayInSeconds = 0.1;
            dispatch_time_t popTime = dispatch_time(DISPATCH_TIME_NOW, (int64_t)(delayInSeconds * NSEC_PER_SEC));
            dispatch_after(popTime, dispatch_get_main_queue(), ^(void){
                [[UIApplication sharedApplication] openURL:loginURL];
            });
            if(completion) {
                completion(nil);
            }
        }
    }
```

**Comment by JMSerruya** [comment]
Hello!. This issue has been fixed and the fix will be included in our next release. 

Thank you for the reports and patience.

**Comment by ruslan120101** [comment]
:']

**Comment by JMSerruya** [comment]
This issue has been addressed in Beta-13

https://github.com/spotify/ios-sdk/releases/tag/beta-13

**Comment by timtime4** [comment]
I seem to getting this issue with Beta-14

My error code is as follows:

`2016-04-05 14:41:33.757 Ear of the Party[6638:1707377] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFString hasPrefix:]: nil argument'
*** First throw call stack:
(
	0   CoreFoundation                      0x00000001097ecf65 __exceptionPreprocess + 165
	1   libobjc.A.dylib                     0x000000010b955deb objc_exception_throw + 48
	2   CoreFoundation                      0x00000001097ece9d +[NSException raise:format:] + 205
	3   CoreFoundation                      0x0000000109705ae0 -[__NSCFString hasPrefix:] + 96
	4   Ear of the Party                    0x00000001086229c1 -[SPTAuth _canHandleURL:withDeclaredRedirectURL:] + 143
	5   Ear of the Party                    0x0000000108622a35 -[SPTAuth canHandleURL:] + 82
	6   Ear of the Party                    0x00000001085f98ac _TFC16Ear_of_the_Party11AppDelegate11applicationfS0_FTCSo13UIApplication7openURLCSo5NSURL17sourceApplicationGSqSS_10annotationPSs9AnyObject__Sb + 1148
	7   Ear of the Party                    0x00000001085f9fd6 _TToFC16Ear_of_the_Party11AppDelegate11applicationfS0_FTCSo13UIApplication7openURLCSo5NSURL17sourceApplicationGSqSS_10annotationPSs9AnyObject__Sb + 262
	8   UIKit                               0x000000010a4e8a82 __45-[UIApplication _applicationOpenURL:payload:]_block_invoke + 1018
	9   UIKit                               0x000000010a4e8437 -[UIApplication _applicationOpenURL:payload:] + 729
	10  UIKit                               0x000000010a4f593d -[UIApplication _handleNonLaunchSpecificActions:forScene:withTransitionContext:completion:] + 2777
	11  UIKit                               0x000000010a4fc413 -[UIApplication _handleApplicationActivationWithScene:transitionContext:completion:] + 2535
	12  UIKit                               0x000000010a4fb782 -[UIApplication _handleApplicationLifecycleEventWithScene:transitionContext:completion:] + 508
	13  UIKit                               0x000000010a4dc181 __70-[UIApplication scene:didUpdateWithDiff:transitionContext:completion:]_block_invoke + 159
	14  UIKit                               0x000000010a4dbe06 -[UIApplication scene:didUpdateWithDiff:transitionContext:completion:] + 833
	15  FrontBoardServices                  0x000000010e0d27ac -[FBSSerialQueue _performNext] + 192
	16  FrontBoardServices                  0x000000010e0d2b1a -[FBSSerialQueue _performNextFromRunLoopSource] + 45
	17  CoreFoundation                      0x00000001097190a1 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	18  CoreFoundation                      0x000000010970efcc __CFRunLoopDoSources0 + 556
	19  CoreFoundation                      0x000000010970e483 __CFRunLoopRun + 867
	20  CoreFoundation                      0x000000010970de98 CFRunLoopRunSpecific + 488
	21  GraphicsServices                    0x000000010d6c0ad2 GSEventRunModal + 161
	22  UIKit                               0x000000010a4de676 UIApplicationMain + 171
	23  Ear of the Party                    0x00000001085fb2ed main + 109
	24  libdyld.dylib                       0x000000010dc5a92d start + 1
	25  ???                                 0x0000000000000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException`

And my App Delegate Code is as follows:

`   func application(application: UIApplication, openURL url: NSURL, sourceApplication: String?, annotation: AnyObject) -> Bool {
        print("In app del function")
        print( NSURL(string: kCallbackURL)!)
        print(url)
        
        if SPTAuth.defaultInstance().canHandleURL( url ) {
            print("Past first if")
            
            SPTAuth.defaultInstance().handleAuthCallbackWithTriggeredAuthURL(url, callback: {
                (error:NSError!, session: SPTSession! ) -> Void in
                if error != nil {
                    print("Authentication Error")
                    return
                }
                
                print("Successful Authentication")
                
                let userDefaults = NSUserDefaults.standardUserDefaults()
                let sessionData = NSKeyedArchiver.archivedDataWithRootObject(session)
                
                userDefaults.setObject(sessionData, forKey: "SpotifySession")
                userDefaults.synchronize()
            })
        } else {
            print("error")
    }
    
        return false
    }`
