### ISSUE TITLE
unsupported URL in swift 

### ISSUE THREAD

**Issue by codinglearning** [spotify/ios-sdk#373]
trying to login with Spotiy in my swift project but it always says unsupported URL.

    func application(application: UIApplication, openURL url: NSURL, sourceApplication: String?, annotation: AnyObject?) -> Bool {
        
        if SPTAuth.defaultInstance().canHandleURL(url, withDeclaredRedirectURL: NSURL(string: kCallbackURL)) {
            SPTAuth.defaultInstance().handleAuthCallbackWithTriggeredAuthURL(url, callback: { (error, session) -> Void in
                if error != nil {
                    println(error.localizedDescription)
                    return
                }
 
                
                NSNotificationCenter.defaultCenter().postNotificationName("loginSuccessfull", object: nil)
            })
        }
        
        return false
    }

**Comment by jaronheard** [comment]
I has a similar issue. Try removing the withDeclaredRedirectURL argument to
the canHandleURL function. Also, I can't see what URL you are checking but
check to make sure that your callback URL conforms to the standards
outlined in the documentation (i.e. lowercase).

**Comment by codinglearning** [comment]
yes its working, can you answer this http://stackoverflow.com/questions/31010708/sptplaylistsnapshot-tracksforplayback-returns-function-swift ?

**Comment by jaronheard** [comment]
@codinglearning I took a stab at answering your question. Let me know if that doesn't work,

**Comment by codinglearning** [comment]
@jaronheard hey thanks for replying :+1:

**Comment by codinglearning** [comment]
hey @jaronheard can you reply now, I'm  still shaking my head lol

**Comment by jaronheard** [comment]
@codinglearning I'll try to take a look this evening.

**Comment by codinglearning** [comment]
@jaronheard  thanks :)

**Comment by codinglearning** [comment]
hey @jaronheard  moved this to https://github.com/spotify/ios-sdk/issues/377

**Comment by erdtman** [comment]
Moved to #377, does that mean we can close this issue?
