### ISSUE TITLE
Crash on SPTPlaylistList playlistListFromData:withResponse:error:

### ISSUE THREAD

**Issue by Kry256** [spotify/ios-sdk#374]
I'm experiencing crashes when parsing certain playlists.
Just after download the playlists for my user, in the debugger I can see the stack trace as follow

```[SPTDefaultRequestHandler performRequest:callback:]_block_invoke at /Users/spotify-buildagent/buildAgent/work/f0512cb09316daec/src/SPTRequest.m:1117```
```[SPTPlaylistList playlistsForUser:withAccessToken:callback:]_block_invoke78 at /Users/spotify-buildagent/buildAgent/work/f0512cb09316daec/src/SPTPlaylistList.m:136```
```[SPTPlaylistList playlistListFromData:withResponse:error:] at /Users/spotify-buildagent/buildAgent/work/f0512cb09316daec/src/SPTPlaylistList.m:157```
```[NSJSONSerialization JSONObjectWithData:options:error:] --> crash!```

Here are the poor informations that I can retrieve from the logs

***Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'data parameter is nil'
First throw call stack:
(0x183fa42d8 0x1957c80e4 0x183fa4218 0x184e306f0 0x100a58df0 0x100a58a18 0x101ad8fd4 0x101ad8f94 0x101addc28 0x183f5b7f8 0x183f598a0 0x183e852d4 0x18d69b6fc 0x188a4afac 0x1000e7344 0x195e46a08)
libc++abi.dylib: terminating with uncaught exception of type NSException***

Unfortunately it seems that this bug/crash doesn't happens for a specific playlist, contrariwise it appear to be quite random

**Comment by TokyoBirdy** [comment]
Try out with latest beta-10 release. Let me know if there are more problems ^^ Cheers  https://github.com/spotify/ios-sdk/releases

**Comment by erdtman** [comment]
Sorry for not getting back earlier. In an attempt to get a better overview of the issues we are cleaning out some of the older issues. If this issue is still a problem in the latest SDK please reopen this issue or open a new one.
