### ISSUE TITLE
Login with Facebook or user/password

### ISSUE THREAD

**Issue by chrismazzeo** [spotify/ios-sdk#375]
Hi all, i am dealing with the login, is it posible to login to spotify without entering the user and password, just opening the Facebook app, like all other apps do? The second i want to ask is how older apps loging into spotify using user and password? Is there another way to login without the SPTAuthViewController ? Thk

**Comment by erdtman** [comment]
You need an OAuth access token, but you don´t need to use the SDK to get it i.e. you are not forced to use SPTAuthViewController.

See the https://developer.spotify.com/web-api/authorization-guide/ for details on how to get an access token.

I will close this issue now, if you need more information please feel free to reopen it.
