### ISSUE TITLE
[iOS 9 Beta 2] Spotify with CarPlay doesn't work anymore

### ISSUE THREAD

**Issue by AndrexOfficial** [spotify/ios-sdk#376]
2 Days ago I've installed iOS 9 Beta 2 but when I connect my iPhone 6 to my Car Stereo (Pioneer) with CarPlay the App of Spotify launches but it doesn't show music controls and music library, If I start playing music from the iPhone the sound is played throught my car speakers.
In iOS 9 Beta 1 the CarPlay function with Spotify was ok.

**Comment by erdtman** [comment]
I cannot see how this is related to the ios-sdk so I will close this issue. If I´m wrong please reopen the issue.
