### ISSUE TITLE
Playlist.firstTrackPage.tracksForPlayback() returns nil (Swift)

### ISSUE THREAD

**Issue by codinglearning** [spotify/ios-sdk#377]
This is my code
<pre>
SPTPlaylistList.playlistsForUserWithSession(session, callback: { (error, object) -> Void in
            if error == nil {
                var playlists = object as! SPTListPage
                println(playlists)
                SPTPlaylistSnapshot.playlistWithURI(playlists.items[0].uri, accessToken: session.accessToken, callback: { (error:NSError!, obj) -> Void in
                    var playl = obj as! SPTPlaylistSnapshot
                    println(playl.firstTrackPage.tracksForPlayback()) // nil
                })
            }
        })
</pre>
This works fine in the demo objective C code but not sure whats wrong with my swift code.

Here is the sample project you can download https://www.dropbox.com/s/48y27ijft3ytsja/TestSpotifyNew.zip?dl=0

**Comment by LandonRover** [comment]
Here's a version of your code that I can confirm works. If it doesn't for you, there's something else wrong in your setup, not the code.

```swift
SPTPlaylistList.playlistsForUserWithSession(session) { (error, playlistList) -> Void in
      if let playlistList = playlistList as? SPTPlaylistList, partialPlaylist = playlistList.items.first as? SPTPartialPlaylist {
        SPTPlaylistSnapshot.playlistWithURI(partialPlaylist.uri, accessToken: session.accessToken) { (error, playlistSnapshot) -> Void in
          if let playlistSnapshot = playlistSnapshot as? SPTPlaylistSnapshot {
            println(playlistSnapshot.firstTrackPage.tracksForPlayback())
          } else if let error = error {
            println(error.localizedDescription)
          }
        }
      }
    }
```

**Comment by codinglearning** [comment]
it doesn't work, 50 tracks and still returns nil. Can you please check the sample project I created, if you have some spare time.

**Comment by LandonRover** [comment]
Where are you seeing the 50 tracks?

**Comment by codinglearning** [comment]
I have 50 tracks in my paylist. I added this line  pritnln(playlistList.items.first) . It prints the playlist id,user id and number of tracks.

**Comment by MusicSplitterGit** [comment]
Did you ever solve this issue? I am having the same problem with both solutions offered above^

**Comment by agtd** [comment]
Same issue for me. Copied the code from above and still no success. Did anyone get this resolved??

**Comment by agtd** [comment]
Ok - Got it fixed

To complete the set up of your build environment, switch from the Info tab to the Build Settings tab and find the Other Linker Flags build setting (you can search for it using the search field at the top of the settings list). If you don’t see it you might need click on ‘All’ to show all build settings.

Add the value -ObjC to this setting.

**Comment by Sethmr** [comment]
https://github.com/Sethmr/SpotifyInSwift has your Swift answers
