### ISSUE TITLE
Spotify not working on my Window 8.1 phone.

### ISSUE THREAD

**Issue by God5on** [spotify/ios-sdk#378]
My spotify will not play on my new Window 8.1 phone. Keep saying loading plus I'm a Premium user. I need to get this issue fixed asap before I cancel my subscription.

**Comment by LandonRover** [comment]
Definitely the wrong place to post this.

https://support.spotify.com/us/

**Comment by loretoparisi** [comment]
uhm, we could ask a Windows Phone SDK instead :dancers:

**Comment by God5on** [comment]
Ok. Please let me know what's the out come. Thanks so much.

"GODSON"

-----Original Message-----

**Comment by JMPerez** [comment]
I'm going to close this issue since it is not related with the Spotify iOS SDK. We have taken note of your request for a Windows Phone SDK.

**Comment by loretoparisi** [comment]
@JMPerez thank you very much, a Windows Phone SDK would be awesome, and I would be glad to test it.

**Comment by God5on** [comment]
What does the initial SDK stands for and what do you mean by test it?

"GODSON"

-----Original Message-----
