### ISSUE TITLE
Get total track count of an album/disc

### ISSUE THREAD

**Issue by adambolcsfoldi** [spotify/ios-sdk#379]
It seems that every _SPTTrack_/_SPTParialTrack_ has a _discNumber_, but there's not way of getting the total number of tracks on an album or disc. Is this right?

**Comment by LandonRover** [comment]
The workflow is a bit odd, but you can get the total number of tracks for an album. Since SPTAlbum / `SPTAlbum.firstTrackPage` is an `SPTListPage`, and has a property called `totalListLength`.

```swift
let numberOfTracks = album.firstTrackPage?.totalListLength
```

I would extend SPTAlbum to include a `trackCount` function.

```swift
extension SPTAlbum {
  func trackCount() -> Int {
    return firstTrackPage?.totalListLength ?? 0
  }
}
```

**Comment by WormBuffet** [comment]
That's quite good. I hadn't noticed the `SPTAlbum.firstTrackPage`. 

Unfortunately it still doesn't get me track counts per disc, which I guess would involve iterating over the tracks and counting them using the `SPTTrack.discNumber`.

**Comment by erdtman** [comment]
We are deprecating the iOS-Metadata library.

The source code of the iOS-Metadata library has been released and can be found [here](https://github.com/erdtman/spotify-ios-metadata/). Spotify will not continue to maintain the released source code.

Either you can select to use the web-api directly or use the new open source iOS-Metadata library.

I will close this issue now.

We are sorry for the inconvenience that this creates, but looking back we think this is the best path forward.
