### ISSUE TITLE
Unit testing initiateSessionWithScope on Xcode + Simulator

### ISSUE THREAD

**Issue by amahanti** [spotify/ios-sdk#38]
The SPTSessionManager initiateSession call presents a UIAlert and then a modal web controller on the iOS Simulator within an XCTest. 

Is there a way to auto-advance or override so that scope and accessToken is granted without required user interaction?

We would like to use the accessToken to test other Spotify endpoints but don't have a reliable way to unit test.

**Comment by jackfreeman** [comment]
@amahanti You could manually grant access and then use the `refreshToken` to renew the session silently for your tests.
