### ISSUE TITLE
Crash in SPTPlaylistList playlistListFromData:withResponse:error:

### ISSUE THREAD

**Issue by steve-whitney** [spotify/ios-sdk#380]
SDK version: beta-9

In our app, this is readily reproducible when trying to get user's playlist when in airplane mode.  If I were to write a proof-of-issue app, it would be a single-view app:
`   click HERE to login`
`   Now turn on airplane mode...`
`   click HERE to retrieve playlists`

Our app:
 * works fine when retrieving playlists in good data-networking env
 * never used SPTReachability (?)

Partial crash report:

`Incident Identifier: 4140FE62-3106-4ECD-871E-EB4FE5989573`
`CrashReporter Key:   89230fdb27635c9d34a301a99f4db842f0071a8c`
`Hardware Model:      iPhone6,1`
`Process:             REDACTED [756]`
`Path:                /private/var/mobile/Containers/Bundle/Application/1161852D-CD5F-4CBE-A6B4-7ADE5E483ABB/REDACTED.app/REDACTED`
`Identifier:          REDACTED`
`Version:             87 (1.0)`
`Code Type:           ARM-64 (Native)`
`Parent Process:      launchd [1]`

`Date/Time:           2015-07-02 13:38:44.936 -0500`
`Launch Time:         2015-07-02 13:38:44.027 -0500`
`OS Version:          iOS 8.3 (12F70)`
`Report Version:      105`

`Exception Type:  EXC_CRASH (SIGABRT)`
`Exception Codes: 0x0000000000000000, 0x0000000000000000`
`Triggered by Thread:  5`

`Last Exception Backtrace:`
`0   CoreFoundation                 0x185a382d8 __exceptionPreprocess + 132`
`1   libobjc.A.dylib                0x1972040e4 objc_exception_throw + 60`
`2   CoreFoundation                 0x185a38218 +[NSException raise:format:] + 128`
`3   Foundation                     0x1868c46f0 +[NSJSONSerialization JSONObjectWithData:options:error:] + 80`
`4   REDACTED                       0x1003a735c +[SPTPlaylistList playlistListFromData:withResponse:error:] (SPTPlaylistList.m:157)`
`5   REDACTED                       0x1003a6f84 __61+[SPTPlaylistList playlistsForUser:withAccessToken:callback:]_block_invoke78 (SPTPlaylistList.m:136)`
`6   libdispatch.dylib              0x197855994 _dispatch_call_block_and_release + 24`
`7   libdispatch.dylib              0x197855954 _dispatch_client_callout + 16`
`8   libdispatch.dylib              0x19785a20c _dispatch_main_queue_callback_4CF + 1608`
`9   CoreFoundation                 0x1859ef7f8 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 12`
`10  CoreFoundation                 0x1859ed8a0 __CFRunLoopRun + 1492`
`11  CoreFoundation                 0x1859192d4 CFRunLoopRunSpecific + 396`
`12  GraphicsServices               0x18f1376fc GSEventRunModal + 168`
`13  UIKit                          0x18a4defac UIApplicationMain + 1488`
`14  REDACTED                       0x10017ef34 main (AppDelegate.swift:15)`
`15  libdyld.dylib                  0x197882a08 start + 4`

`Thread 0 name:  Dispatch queue: com.apple.main-thread`
`Thread 0:`
`0   libsystem_kernel.dylib         0x000000019799b594 __semwait_signal_nocancel + 8`
`1   libsystem_c.dylib              0x00000001978cb1a0 nanosleep$NOCANCEL + 200`
`2   libsystem_c.dylib              0x00000001978f02b8 usleep$NOCANCEL + 64`
`3   libsystem_c.dylib              0x0000000197912b1c abort + 116`
`4   REDACTED                       0x00000001003632d8 uncaught_exception_handler + 32`
`5   CoreFoundation                 0x0000000185a38694 __handleUncaughtException + 688`
`6   libobjc.A.dylib                0x00000001972043b0 _objc_terminate() + 112`
`7   libc++abi.dylib                0x0000000196a01bb0 std::__terminate(void (*)()) + 12`
`8   libc++abi.dylib                0x0000000196a01474 __cxa_throw + 132`
`9   libobjc.A.dylib                0x0000000197204200 objc_exception_throw + 344`
`10  CoreFoundation                 0x0000000185a38214 +[NSException raise:format:] + 124`
`11  Foundation                     0x00000001868c46ec +[NSJSONSerialization JSONObjectWithData:options:error:] + 76`
`12  REDACTED                       0x00000001003a7358 +[SPTPlaylistList playlistListFromData:withResponse:error:] (SPTPlaylistList.m:157)`
`13  REDACTED                       0x00000001003a6f80 __61+[SPTPlaylistList playlistsForUser:withAccessToken:callback:]_block_invoke78 (SPTPlaylistList.m:136)`
`14  libdispatch.dylib              0x0000000197855990 _dispatch_call_block_and_release + 20`
`15  libdispatch.dylib              0x0000000197855950 _dispatch_client_callout + 12`
`16  libdispatch.dylib              0x000000019785a208 _dispatch_main_queue_callback_4CF + 1604`
`17  CoreFoundation                 0x00000001859ef7f4 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 8`
`18  CoreFoundation                 0x00000001859ed89c __CFRunLoopRun + 1488`
`19  CoreFoundation                 0x00000001859192d0 CFRunLoopRunSpecific + 392`
`20  GraphicsServices               0x000000018f1376f8 GSEventRunModal + 164`
`21  UIKit                          0x000000018a4defa8 UIApplicationMain + 1484`
`22  REDACTED                       0x000000010017ef30 main (AppDelegate.swift:15)`
`23  libdyld.dylib                  0x0000000197882a04 start + 0`

`Thread 1 name:  Dispatch queue: com.apple.libdispatch-manager`
`Thread 1:`
`0   libsystem_kernel.dylib         0x0000000197980c24 kevent64 + 8`
`1   libdispatch.dylib              0x0000000197865e6c _dispatch_mgr_invoke + 272`
`2   libdispatch.dylib              0x0000000197857998 _dispatch_mgr_thread + 48`

~~~ snip ~~~

**Comment by steve-whitney** [comment]
proof-of-issue app:  https://github.com/steve-whitney/spt-ios-sdk-issue380

**Comment by steve-whitney** [comment]
possibly related: https://github.com/spotify/ios-sdk/issues/374

**Comment by steve-whitney** [comment]
possibly related: #380

**Comment by steve-whitney** [comment]
possibly related: #331

**Comment by steve-whitney** [comment]
I rolled back from spotify sdk tip (beta 9) to beta 8, and re-tested my proof-of-issue app:  it still crashes.

**Comment by matijse** [comment]
+1

**Comment by TokyoBirdy** [comment]
Try out with latest beta-10 release. Let me know if there are more problems ^^ Cheers  https://github.com/spotify/ios-sdk/releases

**Comment by matijse** [comment]
Seems to be fixed. Thanks

**Comment by steve-whitney** [comment]
I see the same problem as @matijse 

New issue: #394

**Comment by steve-whitney** [comment]
Closing this because 2nd beta-10 release (commit ea137b23e4f7dafbae52fe47523104b8516fd49c) fixed both this issue and #394 .

**Comment by bass4aj** [comment]
I am seeing this issue on beta 14
