### ISSUE TITLE
What is the token swap method in Beta 9?

### ISSUE THREAD

**Issue by hamzahashmi** [spotify/ios-sdk#381]
In spotify_token_swap.rb it explains that you pass your token swap URL to the token swap method, however there doesn't seem to be any information on that method in the API documentation. Do we now just have to set the tokenSwapURL property? 

I have played around with the api while running spotify_token_swap.rb(I set the client_id, secret, and callback url appropriately), but it does not seem to be getting pinged, even in the Basic Auth example that was provided in the SDK when run through the iOS simulator. How exactly do we do the exchange for the access token?

**Comment by EgaSetya** [comment]
I have the same problem too, how to deal with this problem.
Did you find any workaround?

**Comment by hamzahashmi** [comment]
Hi, sorry for the late response. I decided to use the SPTAuthViewController which is what I think Spotify wants us to use, and that calls spotify_token_swap.rb

**Comment by erdtman** [comment]
Seems like you have solved your problem. Can I close this issue?

**Comment by hamzahashmi** [comment]
Yes!

Hamza
