### ISSUE TITLE
SPTSearch performSearchWithQuery crashes when there is no internet connection

### ISSUE THREAD

**Issue by fotiDim** [spotify/ios-sdk#384]
SPTSearch performSearchWithQuery crashes when there is no internet connection with: 'NSInvalidArgumentException', reason: 'data parameter is nil'

**Comment by bass4aj** [comment]
#635 +1

**Comment by DmytroAnkudinov** [comment]
See #766

**Comment by DmytroAnkudinov** [comment]
Fixed in Beta25.
