### ISSUE TITLE
Why no 'market' parameter for playlist or listPage requests?

### ISSUE THREAD

**Issue by LandonRover** [spotify/ios-sdk#385]
Playlists very often contain unplayable tracks, and the playlist requests do not have `market` to easily mark those tracks with `isPlayable = false`.

```swift
// why no market
SPTPlaylistSnapshot.playlistWithURI(uri, accessToken: accessToken, callback: callback) 
// .. has market, marks track unplayable
SPTTrack.trackWithURI(uri, accessToken: accessToken, market: market, callback: callback)
```

Since playlists are `listPage` based, I pull the tracks with:
```swift
listPage.requestNextPageWithAccessToken(accessToken) { (error, nextPage) -> Void in
        if let nextPage = nextPage as? SPTListPage, tracks = nextPage.tracksForPlayback() as? [SPTTrack] {
          // do something with the tracks
        }
      }

```
which also doesn't allow for market. It would make me sad if I have to parse the uris from tracksForPlayback and request them all with `SPTTrack.trackWithURI` to get `isPlayable`.

I have also noticed that lots of tracks that return `isPlayable = false` are playable in the Spotify app, is there more to unplayable tracks than market?

**Comment by iGranDav** [comment]
Hi, did you found any solution on this? I'm experiencing the exact same issue with playlist loading without market infos.

**Comment by iGranDav** [comment]
It appears #528 does the trick 😊 several duplicated issues about this BTW.

**Comment by erdtman** [comment]
Sorry for not getting back earlier. In an attempt to get a better overview of the issues we are cleaning out some of the older issues. If this issue is still a problem in the latest SDK please reopen this issue or open a new one.
