### ISSUE TITLE
Audio Skipping

### ISSUE THREAD

**Issue by sgoodwin** [spotify/ios-sdk#386]
Hi folks,

In our app, when I add some music to the queue, music plays.
When I clear the queue, music stops.
When I add different music to the queue, I hear a tiny bit of the original music before it begins playing the new music.

Problems like this are making our app sound bad by randomly skipping during use.

**Comment by erdtman** [comment]
Sorry for not getting back earlier. In an attempt to get a better overview of the issues we are cleaning out some of the older issues. If this issue is still a problem in the latest SDK please reopen this issue or open a new one.
