### ISSUE TITLE
requestNewReleasesForCountry returns nil items

### ISSUE THREAD

**Issue by jeffb6688** [spotify/ios-sdk#387]
After upgrading from Beta6 to Beta9, I see that requestNewReleasesForCountry returns nil items. To get around the problem, I had to fall back to the Beta6 deprecated version. Below is example code:

    
        // Get the featured playlists for the local country and language
        NSLocale *locale = [NSLocale currentLocale];
        NSString *countryCode = [locale objectForKey: NSLocaleCountryCode];
    #ifdef SPOTIFY_BETA6
        [SPTRequest requestNewReleasesForCountry:countryCode limit: 50 offset: 0 session:session callback:^(NSError *error, SPTListPage *newReleases) {
    #else
        [SPTBrowse requestNewReleasesForCountry:countryCode limit: 50 offset: 0 accessToken:[session accessToken] callback:^(NSError *error, SPTListPage *newReleases) {
    #endif

                NSArray *temp = [newReleases items];
        }];

The beta6 line of code returns a non-zero number of newReleases, but the beta9 line of code returns nil.

**Comment by Voxar** [comment]
Fixed for next release
