### ISSUE TITLE
playURIs:withOptions does not allow a specific track to be selected in shuffle mode

### ISSUE THREAD

**Issue by jeffb6688** [spotify/ios-sdk#388]
The SPTAudioStreamingController method playURIs:withOptions:callback does not allow me to specify a track within a playlist to begin play when I am using shuffle mode. It seems that the track index is ignored and a random track plays.

While the simple work around is to turn off shuffle mode, it seems that a user should be able to choose a specific song to play even in shuffle mode. For example, if you present a list of songs in a table view to the user while in shuffle mode, the user should be able to select a particular song to play.

**Comment by erdtman** [comment]
Sorry for not getting back earlier. In an attempt to get a better overview of the issues we are cleaning out some of the older issues. If this issue is still a problem in the latest SDK please reopen this issue or open a new one.
