### ISSUE TITLE
currentTrackMetadata (and associated keys)

### ISSUE THREAD

**Issue by jeffb6688** [spotify/ios-sdk#389]
The SPTAudioStreamingController property currentTrackMetadata (and associated keys) are marked as deprecated in beta9. 

The keys returned in a trackMetadata dictionary in the SPTAudioStreamingPlaybackDelegate Protocol method audioStreaming:didChangeToTrack: are marked deprecated in beta9 (i.e. if you try to determine what track and artist is currently playing, keys such as SPTAudioStreamingMetadataTrackName and SPTAudioStreamingMetadataArtistName are marked deprecated.

What is the replacement for the currentTrackMetadata (and associated keys) in beta9? Is there some other way to determine the track name and artist of the currently playing track?

**Comment by Voxar** [comment]
This has been reworked since.
