### ISSUE TITLE
Unable to connect to Spotify app after acquiring access token

### ISSUE THREAD

**Issue by clt** [spotify/ios-sdk#39]
I'm following the steps outlined in the tutorial using the `SPTSessionManager` authorization flow and I'm getting the following error when attempting to connect to the spotify app:

`AppRemote: Failed connection attempt with error: Error Domain=com.spotify.app-remote.transport Code=-2000 "Stream error." UserInfo={NSLocalizedDescription=Stream error., NSUnderlyingError=0x282461e60 {Error Domain=NSPOSIXErrorDomain Code=61 "Connection refused" UserInfo={_kCFStreamErrorCodeKey=61, _kCFStreamErrorDomainKey=1}}, NSLocalizedRecoverySuggestion=Reconnect the transport to the Spotify app., NSLocalizedFailureReason=A stream error has occured in the transport.}`

I've verified that I get back a valid session with an access token that I hand off to my instance of `SPTAppRemote`. Here's the code that I'm using:

```
- (void)configure
{
    SPTConfiguration *theConfig = [[SPTConfiguration alloc] initWithClientID:kXDSpotifyClientID redirectURL:[NSURL URLWithString:kXDSpotifyCallbackURL]];
    theConfig.tokenSwapURL = [NSURL URLWithString:kXDSpotifyTokenSwapServiceURL];
    theConfig.tokenRefreshURL = [NSURL URLWithString:kXDSpotifyTokenRefreshServiceURL];
    self.sessionManager = [[SPTSessionManager alloc] initWithConfiguration:theConfig delegate:self];
    self.appRemote = [[SPTAppRemote alloc] initWithConfiguration:theConfig logLevel:SPTAppRemoteLogLevelDebug];
}

-(void)initiateSession
{
    SPTScope theScopes = SPTPlaylistReadPrivateScope | SPTPlaylistModifyPublicScope | SPTPlaylistModifyPrivateScope |SPTUserFollowReadScope | SPTUserFollowModifyScope | SPTUserLibraryReadScope | SPTUserLibraryModifyScope | SPTUserTopReadScope | SPTAppRemoteControlScope;
    [self.sessionManager initiateSessionWithScope:theScopes options:SPTDefaultAuthorizationOption];
}


// called from AppDelegate
-(BOOL)application:(UIApplication *)app openURL:(NSURL *)url options:(NSDictionary<NSString *,id> *)options
{
    return [self.sessionManager application:app openURL:url options:options];
}

#pragma mark - SPTSessionManagerDelegate
- (void)sessionManager:(SPTSessionManager *)manager didInitiateSession:(SPTSession *)session
{
    self.appRemote.connectionParameters.accessToken = session.accessToken;
    self.appRemote.delegate = self;
    [self.appRemote connect];
}

- (void)sessionManager:(SPTSessionManager *)manager didFailWithError:(NSError *)error
{
    NSLog(@"Error getting session token: %@", error);
}

#pragma mark - SPTAppRemoteDelegate
- (void)appRemoteDidEstablishConnection:(SPTAppRemote *)appRemote
{
    self.appRemote.playerAPI.delegate = self;
    [self.appRemote.playerAPI subscribeToPlayerState:^(id  _Nullable result, NSError * _Nullable error) {
        NSLog(@"%@",error);
    }];
    
    self.appRemote.userAPI.delegate = self;
    [self.appRemote.userAPI subscribeToCapabilityChanges:^(id  _Nullable result, NSError * _Nullable error) {
        NSLog(@"%@",error);
    }];
}

- (void)appRemote:(SPTAppRemote *)appRemote didFailConnectionAttemptWithError:(nullable NSError *)error
{
    NSLog(@"Error connecting to Spotify app %@",error);
}
```

**Comment by jackfreeman** [comment]
@clt Looks like you need to set a `playURI` on `SPTConfiguration`. Music must be playing the first time you connect with App Remote so that Spotify is not in a suspended state in the background.

**Comment by clt** [comment]
@jackfreeman thanks, that worked. It seems like a playURI is required in both the built-in App Remote auth flow and the session manager auth flow. Would it be possible to relax the playURI requirement for the session manager auth flow? Calling `initiateSessionWithScope:options:` on the session manager causes the Spotify app to launch and/or rotate into the foreground which should satisfy the condition of having Spotify up and running in order to subsequently connect with App Remote.

**Comment by jackfreeman** [comment]
@clt Please see this [comment](https://github.com/spotify/ios-sdk/issues/22#issuecomment-423938453) for tips on how to auth without playing music and using the web-api to surface content. 

Spotify cannot stay alive indefinitely in the background without playing music due to iOS restrictions.

**Comment by clt** [comment]
Ok thanks @jackfreeman
