### ISSUE TITLE
SPTSearch class not documented in Beta9 - need to performSearchWithQuery:

### ISSUE THREAD

**Issue by jeffb6688** [spotify/ios-sdk#390]
After upgrading to Beta9 from Beta6, I see that the SPTRequest method 

    performSearchWithQuery:queryType:session:callback

is deprecated. The documentation says that "This method is moved to the SPTSearch class." But there is no link to the SPTSearch class. 

What does the Beta9 interface look like? Please provide a replacement example for the following:

    [SPTRequest performSearchWithQuery: searchString queryType:SPTQueryTypeArtist session:session callback:^(NSError *error, SPTListPage *searchResults) {

        // do something with the searchResults
    }];

**Comment by TokyoBirdy** [comment]
@jeffb6688  you can check it here https://developer.spotify.com/ios-sdk-docs/Documents/Classes/SPTSearch.html

**Comment by erdtman** [comment]
Sorry for not getting back earlier. In an attempt to get a better overview of the issues we are cleaning out some of the older issues. If this issue is still a problem in the latest SDK please reopen this issue or open a new one.
