### ISSUE TITLE
Search functionality is lacking.

### ISSUE THREAD

**Issue by LandonRover** [spotify/ios-sdk#391]
In the web api and this sdk, it seems like the search functionality is somewhat odd when including multiple terms. For example, searching for artists "selena" results in lots of results, with Selena Gomez at the top. However, add the first letter of her last name "Selena G", and we get 0 results (https://developer.spotify.com/web-api/console/get-search-item/?q=selena+g&type=artist&market=US). The same thing happens for nearly every search, until you spell out the full last name you don't get any results.

The Spotify apps all return appropriate results when using multiple terms, can we have that search in the APIs? Are there any additional strategies for searching that we can use to get a better result?

Also, adding "Top Result" to the API would be amazing.

**Comment by ahallora** [comment]
+1

**Comment by samuelerdtman** [comment]
Sorry for the long delay.
When I click the link I get results so this might have been resolved, if I´m somehow mistaken please report the issus to web-api (https://github.com/spotify/web-api)

**Comment by LandonRover** [comment]
Looks like this is indeed fixed, thanks!
