### ISSUE TITLE
To use this code I need to give up a license for our IP?

### ISSUE THREAD

**Issue by ketz** [spotify/ios-sdk#393]
We just did a kids health app for a client, that allows parents to play tracks through their premium Spotify account, while the screen animates.

We were about to launch the app, but our lawyers had a look at the Spotify Terms of Use, and raised some alarming points. This is how it reads:
 
1.       “You” essentially means the entity entering into the terms of use and all of its related legal entities (e.g, our company and its entities) and those it’s purportedly binding (which you tell Spotify you have authority) and thus could include the client if you try to just try to sublicense to them and get them to agree to be bound by the OSS terms as the master licensor
 
2.       In exchange for the free license, you give up a license to “your” IP (i.e. all our legal entities and all legal entities you purport to bind (i.e., our client)) – including patents
 
3.       Your Spotify license does not give you the right to license the Spotify terms of use as your company's and then “assign” or even “sublicense” to your client.  As a result, as a technical matter, this would be better achieved by NOT including the Spotify code and instead requiring the client to take their own license and build for itself, but if you require the client to take on this obligation they will likely reject it.

Reference: https://developer.spotify.com/developer-terms-of-use/

With the above in mind, I was just hoping for some clarification. By allowing users to use their Spotify account, am I giving our IP to Spotify? If so, where do we draw the line? Is it the IP for the app, or for everything we do and patents we hold (which would make no sense)?

Would appreciate any help from the Spotify team on this matter.

**Comment by erdtman** [comment]
I would suggest that you fill out this form 
https://docs.google.com/a/erdtman.se/forms/d/1TGm4bLQRnnPGGev8OorLZQ4M6yKXJ7Etd1awN234Q54/viewform?c=0&w=1
to get in contact with the Spotify legal/licensing

I will close this issue for now. If you ave further questions feel free to reopen it
