### ISSUE TITLE
App terminates when searching for a song with bad/no internet connection

### ISSUE THREAD

**Issue by AntonMeier** [spotify/ios-sdk#395]
When using "performSearchWithQuery:queryType:accessToken:callback:" I get:

*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'data parameter is nil'

**Comment by TokyoBirdy** [comment]
@AntonMeier  Thank you ! I have also created an issue in our sprint to go through ios-sdk when no/bad network happens.

**Comment by matijse** [comment]
Also on 

SPTListPage *listPage = ...
[listPage requestNextPageWithSession:session callback:^(NSError *error, id object) {

}];

**Comment by LandonRover** [comment]
+1 Lots of calls result in 'data parameter is nil' with connectivity issues, not just these two.

**Comment by steve-whitney** [comment]
+1

**Comment by Jackc415** [comment]
Is there a fix for this? My app is still crashing from this.

**Comment by bass4aj** [comment]
I just made an issue for this as well

**Comment by DmytroAnkudinov** [comment]
See #766

**Comment by DmytroAnkudinov** [comment]
Fixed in Beta25.
