### ISSUE TITLE
SPTPlaylistTrack decodedJSONObject is nil

### ISSUE THREAD

**Issue by fishkingsin** [spotify/ios-sdk#396]
as title 
in 0.9
<img width="689" alt="screen shot 2015-07-16 at 12 22 51 am" src="https://cloud.githubusercontent.com/assets/481343/8703645/f1e017b8-2b50-11e5-9835-3bb0f5230a0a.png">

**Comment by fishkingsin** [comment]
but SPTJSONObjectBase contain non nil decodedJSONObject 
<img width="684" alt="screen shot 2015-07-16 at 12 24 28 am" src="https://cloud.githubusercontent.com/assets/481343/8703681/1e919296-2b51-11e5-9730-38ffe50e703d.png">

**Comment by Voxar** [comment]
Fixed for next release
