### ISSUE TITLE
Starred list contains zero song

### ISSUE THREAD

**Issue by ramunasjurgilas** [spotify/ios-sdk#398]
After executing request starred list I am getting zero tracks count when in reality it contains 26 tracks (image attached). Why it returns zero tracks?

```
    SPTAuth *auth = [SPTAuth defaultInstance];
    [SPTPlaylistSnapshot requestStarredListForUserWithSession:auth.session callback:^(NSError *error, SPTPlaylistSnapshot *object) {
            NSLog(@"Starred :%@ tracks:%d",object.name, object.trackCount);
    }];
```
Output: <b>Starred :(null) tracks:0</b>

![img_9702](https://cloud.githubusercontent.com/assets/255732/8773697/e1f0cb54-2ede-11e5-8496-3e48d85868da.PNG)

**Comment by matijse** [comment]
Maybe the token is requested with the wrong scope?

**Comment by ramunasjurgilas** [comment]
Here is scope which I am using. Is it correct?
```
    SPTAuth *auth = [SPTAuth defaultInstance];
    [auth setRequestedScopes:@[SPTAuthUserReadPrivateScope, SPTAuthUserReadEmailScope]];
```

**Comment by matijse** [comment]
I guess you need the `SPTAuthPlaylistReadPrivateScope` scope. Starred songs is probably a private playlist.

See documentation on this GitHub page:

`SPTAuthPlaylistReadScope` and `SPTAuthPlaylistReadPrivateScope` allows access to a user's public and private playlists, respectively.

**Comment by ramunasjurgilas** [comment]
Thanks! It did work!
I know it was my mistake, but recommendation to iOS SDK would be if wrong scope is used that particular error will be generate. :)

**Comment by ramunasjurgilas** [comment]
On more thing to same question. Is this (request starred list) method not deprecated? Or planning to make it as deprecated?
```
+ (void)requestStarredListForUserWithSession:(SPTSession *)session
									callback:(SPTRequestCallback)block;
```

**Comment by DmytroAnkudinov** [comment]
For Beta22 all methods concerning Metadata functionality have been updated to avoid usage of objects from Authentication functionality, so the method you mentioned has been removed.

Use the following method for obtaining starred list
`
 + (void)requestStarredListForUser:(NSString *)username
  			      withAccessToken:(NSString *)accessToken
				              callback:(SPTRequestCallback)block;
`
