### ISSUE TITLE
Stopped playback when iPhone locked!

### ISSUE THREAD

**Issue by adamzairia** [spotify/ios-sdk#399]
My code is 

@property (nonatomic, strong) SPTAudioStreamingController *player;
.....
[self.player playURIs:self.arraySPTTracks fromIndex:i callback:nil];

Songs are playing when i'm on the app. when the screen is locked, play is stopped.  How can I play on fourground/background modes? 

Thanks,

**Comment by mustafaozdemir** [comment]
Add "Required backgroud modes" property to you Info.plist

Required background modes (Array)

Item 0 = App plays audio or streams audio/video using AirPlay
Item 1 = App downloads content from the network

**Comment by adamzairia** [comment]
Thank you. It works well. I have another question. How can I add UIProgressBar to track SPTAudioStreaming? So I want to get the following values in real time. 

length of current playing song,
current seek offset (how many played from start point),

is this possible? 

Many Thanks,

**Comment by RudyB** [comment]
@mustafaozdemir I have those background modes set in my Info.plist however it still stops playing with the device is locked. Do you have any other resources to take a look at to troubleshoot this?
