### ISSUE TITLE
respondsToSelector send messages to deallocated instances

### ISSUE THREAD

**Issue by kleids** [spotify/ios-sdk#4]
Seeing a lot of these errors:

```*** -[SPTAppRemoteSocketTransport respondsToSelector:]: message sent to deallocated instance```

**Comment by jackfreeman** [comment]
@kleids can you provide more info on your implementation? Maybe a sample app where you are seeing this occur? 

It sounds like your `SPTAppRemote` instance might not be properly retained.

**Comment by arirawr** [comment]
Hi @kleids - are you still seeing this issue?

**Comment by kleids** [comment]
I was, I gave up on the issue for now, and reverted to using the web API player to remote to the device. 

This was in Swift, when the device was in background modes, I was trying to wake up, connect, execute the command, and disconnect within the time allowed in background. It worked great 90% of the time with erratic crashes posted above. 

Thanks anyways!

**Comment by jackfreeman** [comment]
@kleids  I was able to reproduce this issue. It has now been resolved in the latest release of the SDK.
