### ISSUE TITLE
PlayURIs: crashes when playing a single track playlist

### ISSUE THREAD

**Issue by RDSpinz** [spotify/ios-sdk#400]
This concerns the methods
-(void)playURIs:(NSArray *)uris fromIndex:(int)index callback:(SPTErrorableOperationCallback)block;
-(void)playURIs:(NSArray *)uris withOptions:(SPTPlayOptions *)options callback:(SPTErrorableOperationCallback)block;

I am able to play the uris when there are 2 or more in the array, however when there is only 1 the program crashes with the message NSException unrecognized selector sent to instance [SPTPlaylistTrack absoluteString]

What's even stranger is that if I turn the single track playlist into a playlist with 2 of the same track, the playlist works as it should: playing a playlist of only 1 track.

Additionally, loading a playlist with 2 of the same track also works as it should by playing a playlist with 2 of the same track.

That's all the information I have so far on this bug. there is no callback

**Comment by thebradbain** [comment]
+1

I'm experiencing the exact same issue, though it only very recently started occurring - did something get changed in the backend perchance?

**Comment by djonik** [comment]
Any more info on this issue? Just started testing my app with a playlist with only one track and I'm seeing the same crash.

**Comment by erdtman** [comment]
playURIs has been removed
