### ISSUE TITLE
[SPTTrack trackWithURI] for local songs returns isPlayable = YES with uri = null

### ISSUE THREAD

**Issue by matijse** [spotify/ios-sdk#402]
When I try to find out if a track is playable in a certain market, I use the `[SPTTrack trackWithURI]` method to request the track information, and look for `track.isPlayable` and maybe a changed `track.uri`. (See [Track Relinking Guide](https://developer.spotify.com/web-api/track-relinking-guide/))

Today I noticed this doesn't work as expected for local songs (`spotify:local:....` uri's). I am getting those URI's from a playlist I am following, so the local songs aren't in my account. The desktop player is able to play these songs however.

I use the following code to get a playable URI and to see if the URI is playable at all:

```
[SPTTrack trackWithURI:[NSURL URLWithString:trackUrl] accessToken:token market:market callback:^(NSError *error, id object) {
            
            if(error != nil) {
                NSLog(@"getPlayableTrack error: %@", error.debugDescription);
            }
            else {
                SPTTrack *track = (SPTTrack *)object;
                NSLog(@"hasPlayable: %i", track.hasPlayable);
                NSLog(@"isPlayable: %i", track.isPlayable);
                NSLog(@"uri: %@", track.uri);
                NSLog(@"playableUri: %@", track.playableUri);
            }
            
        }];
```

For normal `spotify:track:...` URI's this works as expected: `isPlayble` is either `YES` or `NO`, and if `YES`, the track works.

For local `spotify:local:....` URI's however, `isPlayable` returns `YES`, while `uri` and `playableUri` both are `nil`. 

So when checking the track object, I noticed the `hasPlayable` property. Which is `NO` for these local songs. Does this mean we first/also need to check if `hasPlayable` is `YES`? 

Or is there maybe still a bug, because the Spotify desktop player is able to link the local song to a playable track and play it. (The local song is not on my computer, it is in a playlist I am following).

**Comment by loretoparisi** [comment]
@matijse @possan 
We are experiencing the same issue.
As for my understanding the flag ```isPlayable``` is ```TRUE``` by defaults:

```
/** Returns `YES` if the track is flagged as playable, otherwise `NO`, if no market is passed to the api call, this will default to `YES`. */
@property (nonatomic, readonly) BOOL isPlayable;
```

And so this happens for local tracks as well.

I have also found that the ```hasPlayable``` flag can be ```TRUE``` of ```FALSE```, based on the availability of an array of playable tracks that was given by an array of ```playableTracks``` (I cannot see anymore this property in the last Beta12 anyways.

Question is, which is the expression to use when checking this like:

```
trackIsPlayable = track.isPlayable && track.playableUri && track.hasPlayable;
```

Does this solution will work in any case? Is it formally correct. In our checks, not. Since, having the market setup, I can see that track.isPlayable takes the default value ```YES``` not following the availability of the playable tracks array and/or the ```playableUri```.

**Comment by erdtman** [comment]
Sorry for not getting back earlier. In an attempt to get a better overview of the issues we are cleaning out some of the older issues. If this issue is still a problem in the latest SDK please reopen this issue or open a new one.
