### ISSUE TITLE
Device to play on selection

### ISSUE THREAD

**Issue by lenkaiser** [spotify/ios-sdk#403]
Is it possible to select a device to play audio on with iOS SDK beta 10 or Libspotify SDK just like in the iOS and OSX application?
![screen shot 2015-07-27 at 23 28 09](https://cloud.githubusercontent.com/assets/1133235/8918321/acf7a344-34b7-11e5-95fc-da0448a303e2.png)

**Comment by lawrencek7** [comment]
This is not possible at this time in any of our SDKs. We have noted your request for this feature and also think that it would be a great future addition.

**Comment by lenkaiser** [comment]
Have you thought about a certain timeframe that this feature will be available? Or can I as an developer work on this?

Regards
