### ISSUE TITLE
SPTTrack trackWithURI call intermittently crashes with array out of bounds exception

### ISSUE THREAD

**Issue by yourei** [spotify/ios-sdk#404]
I basically have a call to the spotify player within the SPTTrack trackWithURI call like shown below:

```objective-c
[self.spotifyTrackPlayer loginWithSession:session callback:^(NSError *error) {
....
   [SPTTrack trackWithURI:[NSURL URLWithString:self.selectedSong.refId] session:session    callback:^(NSError *error, id object) {
   ....
      [self.spotifyTrackPlayer playURIs:@[track.uri] withOptions:sptPlayOptions  callback:^(NSError *error)   {
....
```
Intermittently, I have been getting a crash in the SPTTrack trackWithURI call with *** Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[__NSArrayI objectAtIndex:]: index 2 beyond bounds [0 .. 0]'

I have attached a screenshot of the crash/trace - 
<img width="1424" alt="spttrack crash" src="https://cloud.githubusercontent.com/assets/13399219/8920242/bf47422a-347b-11e5-9ff4-932634828cb9.png">

Please let me know if there is a work around or if this indeed an issue that will be fixed in the future release or am I doing something incorrectly? In the meantime, I will just handle the exception on my end and figure out a way to ignore it. 

Thanks!

**Comment by erdtman** [comment]
Sorry for not getting back earlier. In an attempt to get a better overview of the issues we are cleaning out some of the older issues. If this issue is still a problem in the latest SDK please reopen this issue or open a new one.
