### ISSUE TITLE
Crash on SPTPlaylistSnapshot from certain playlists

### ISSUE THREAD

**Issue by matijse** [spotify/ios-sdk#405]
Looks like the same bug as #288 

When retrieving the full SPTPlaylistSnapshot, I get a crash only at a specific playlist:  "Today's Top Hits" from the `toplists` category. (`uri` = `spotify:user:spotify:playlist:5FJXhjdILmRA2z5bvz4nzf`). Using this code:

```
[SPTPlaylistSnapshot playlistWithURI:uri session:auth.session callback:^(NSError *error, id object) {

}];
```

Stack trace:

```
#4	0x0026eb9c in -[SPTPlaylistSnapshot initWithDecodedJSONObject:error:] at /Users/ceciliahumlelu/ios-sdk/src/SPTPlaylistSnapshot.m:78
#5	0x0026ecb2 in +[SPTPlaylistSnapshot playlistSnapshotFromDecodedJSON:error:] at /Users/ceciliahumlelu/ios-sdk/src/SPTPlaylistSnapshot.m:102
#6	0x0026ec46 in +[SPTPlaylistSnapshot playlistSnapshotFromData:withResponse:error:] at /Users/ceciliahumlelu/ios-sdk/src/SPTPlaylistSnapshot.m:96
#7	0x0026f31a in __60+[SPTPlaylistSnapshot playlistWithURI:accessToken:callback:]_block_invoke93 at /Users/ceciliahumlelu/ios-sdk/src/SPTPlaylistSnapshot.m:166
```

Error:
 `-[NSNull longValue]: unrecognized selector sent to instance 0x3958ca70`

**Comment by matijse** [comment]
I guess it depends on the songs in the playlist? Today the bug is gone, so I think it is because today there is a new "Today's Top Hits" playlist.

(Error was there on 28th of July, market: NL)

**Comment by simonpang** [comment]
I can confirm that this bug still exist.

**Comment by simonpang** [comment]
The app crashed at address 0x10010f0e4. Look like it crashes when followerCount is NSNull.

 0x10010f08c <+788>: adr    x2, #472108               ; @"followers"
    0x10010f090 <+792>: nop    
    0x10010f094 <+796>: mov    x0, x19
    0x10010f098 <+800>: mov    x1, x21
    0x10010f09c <+804>: bl     0x100155a1c               ; symbol stub for: objc_msgSend
    0x10010f0a0 <+808>: mov    x29, x29
    0x10010f0a4 <+812>: bl     0x100155a64               ; symbol stub for: objc_retainAutoreleasedReturnValue
    0x10010f0a8 <+816>: mov    x22, x0
    0x10010f0ac <+820>: adr    x2, #472108               ; @"total"
    0x10010f0b0 <+824>: nop    
    0x10010f0b4 <+828>: mov    x1, x21
    0x10010f0b8 <+832>: bl     0x100155a1c               ; symbol stub for: objc_msgSend
    0x10010f0bc <+836>: mov    x29, x29
    0x10010f0c0 <+840>: bl     0x100155a64               ; symbol stub for: objc_retainAutoreleasedReturnValue
    0x10010f0c4 <+844>: mov    x21, x0
    0x10010f0c8 <+848>: mov    x0, x22
    0x10010f0cc <+852>: bl     0x100155a34               ; symbol stub for: objc_release
    0x10010f0d0 <+856>: nop    
    0x10010f0d4 <+860>: nop    
    0x10010f0d8 <+864>: ldr    x1, #589848               ; "longValue"
    0x10010f0dc <+868>: mov    x0, x21
    0x10010f0e0 <+872>: bl     0x100155a1c               ; symbol stub for: objc_msgSend
    0x10010f0e4 <+876>: mov    x2, x0
    0x10010f0e8 <+880>: nop    
    0x10010f0ec <+884>: nop    
    0x10010f0f0 <+888>: ldr    x1, #589832               ; "setFollowerCount:"
    0x10010f0f4 <+892>: mov    x0, x20
    0x10010f0f8 <+896>: bl     0x100155a1c               ; symbol stub for: objc_msgSend
    0x10010f0fc <+900>: mov    x0, x21
    0x10010f100 <+904>: bl     0x100155a

**Comment by erdtman** [comment]
Sorry for not getting back earlier. In an attempt to get a better overview of the issues we are cleaning out some of the older issues. If this issue is still a problem in the latest SDK please reopen this issue or open a new one.
