### ISSUE TITLE
Authentication error

### ISSUE THREAD

**Issue by swifferina** [spotify/ios-sdk#406]
I followed the steps to configure the service on Heroku and is running, I've also created the app on Spotify account, but when my iOS app start I get this error :

Auth error: Error Domain=NSCocoaErrorDomain Code=3840 "The operation couldn’t be completed. (Cocoa error 3840.)" (JSON text did not start with array or object and option to allow fragments not set.) UserInfo=0x16d4abb0 {NSDebugDescription=JSON text did not start with array or object and option to allow fragments not set.}

my TokenSwapURL is https://limitless-fjord-6752.herokuapp.com

please could you help me?

**Comment by erdtman** [comment]
Sorry for not getting back earlier. In an attempt to get a better overview of the issues we are cleaning out some of the older issues. If this issue is still a problem in the latest SDK please reopen this issue or open a new one.
