### ISSUE TITLE
No name property on SPTArtist

### ISSUE THREAD

**Issue by finngaida** [spotify/ios-sdk#407]
I forked the latest beta of the Spotify SDK, but when I look at my headers for `SPTArtist`, there is no `.name` property whatsoever, so I have to fetch them via a GET request to the web API. 
I'd like to not do that, will the name property be added some time in the future?
![header](https://cloud.githubusercontent.com/assets/2173831/8959833/415102be-360d-11e5-83dc-9979c9d18485.png)
![method](https://cloud.githubusercontent.com/assets/2173831/8959834/417624c2-360d-11e5-83d0-2d10b427db69.png)

**Comment by lenkaiser** [comment]
You can do this by using the SPTTrack class.

```
SPTTrack.trackWithURI(player.currentTrackURI, session: auth.session, callback: { (error, track) -> Void in
    //Song name
    self.lblSong?.text = track.name
    
    //Artist name
    if let artist:SPTPartialArtist = (track.artists as NSArray).objectAtIndex(0) as? SPTPartialArtist {
        self.lblArtist?.text = artist.name
    } else {
        self.lblArtist?.text = "Unkown"
    }
})
```

**Comment by finngaida** [comment]
OH, wonderful, thanks!
There should be a comment in the `SPTPartialArtist.h` header stating that this can be done.

**Comment by lenkaiser** [comment]
Yes I bumped into a couple of changes too today due to the fact that the documentation isn't updated yet. But I hope they'll update it soon to the beta 10 version.
