### ISSUE TITLE
Skipping From Lock Screen & Control Center

### ISSUE THREAD

**Issue by 909kishore** [spotify/ios-sdk#408]
When my app is in the foreground, skipping works great.
When my app is in the background and I hit skip once from control center or the lock screen, nothing happens.  Then I open the app 10 seconds later and it finally skips the song.

If I hit skip twice from control center or lock screen, it often works.  It just doesn't work the first time.

Issue happens with skip to next song or skip to previous song with beta 10.  This issue did not happen with earlier betas.

**Comment by ronakvora** [comment]
How did you get the skip to even show up in the control center?

**Comment by 909kishore** [comment]
It only shows up with spotify premium accounts. I don't think we did
anything that special for skip. It's pretty standard for apps set to
control audio on iOS. One you set the right category, it should work:
https://developer.apple.com/library/ios/documentation/Audio/Conceptual/AudioSessionProgrammingGuide/AudioSessionBasics/AudioSessionBasics.html

We did have to search for how to get the progress bar to show up in control
center and to get the album name to show up on Bluetooth systems.

Hope that helps!

**Comment by ronakvora** [comment]
Ah yeah I figured it out after a while! Thank you for the response, nonetheless :). I appreciate it.

**Comment by lehn0058** [comment]
I am having trouble getting Spotify pause/play, next and previous controls to work in the latest beta, even with an appropriate category set. Was their any other audio setup you needed to do to get this to work?

**Comment by incipio-srinu** [comment]
I am using the Spotify SDK for iOS. But when I am playing song from my app I am unable to see the song info in the Control Center.Please let me know what change I have to made?
