### ISSUE TITLE
Cannot submit app for iTunes Review

### ISSUE THREAD

**Issue by adamzairia** [spotify/ios-sdk#410]
I'm getting URL Scheme format error when I try to submit app in Xcode. 

my spotify app call back url is myspotifyerapp123456789://

how can I resolve this issue in xcode? 

Thanks,

**Comment by loretoparisi** [comment]
You should have no errors, if you just add a new scheme like:

myspotifyerapp123456789

Which error are you getting from the XCode Submit tool?

**Comment by lawrencek7** [comment]
Closing. Please re-open if you still have issues.
