### ISSUE TITLE
Occasional AURemoteIO@0xXXXX: IOThread exiting with error. AUIOClient_StartIO failed 

### ISSUE THREAD

**Issue by yourei** [spotify/ios-sdk#411]
When I try to stop the Spotify player and then start it back on after handling certain events, I get this error:

AURemoteIO@0xXXXX: IOThread exiting with error. 
AUIOClient_StartIO failed 

I am wondering if any of you have seen this error? This is definitely not consistent and I only get this error occasionally. I am curious as to what would scenario would cause this?

Any help is greatly appreciated. Thanks!

**Comment by erdtman** [comment]
Sorry for not getting back earlier. In an attempt to get a better overview of the issues we are cleaning out some of the older issues. If this issue is still a problem in the latest SDK please reopen this issue or open a new one.
