### ISSUE TITLE
Acoustic Fingerprinting

### ISSUE THREAD

**Issue by tamez** [spotify/ios-sdk#412]
Hello Spotify,

I'm looking for a way to add acoustic fingerprinting to an iOS product. Like, the old EchoNest or Shazam.

Does the Spotify iOS SDK allow for this in anyway? Any recommendations on the best approach? 

dt

**Comment by hughrawlinson** [comment]
Hey @tamez - sorry for such a long delay! Spotify doesn't provide any functionality like this. I don't know of an API that does, unfortunately.
