### ISSUE TITLE
Playlist search broken in beta 10

### ISSUE THREAD

**Issue by sgoodwin** [spotify/ios-sdk#416]
Hi folks!

So I create a playlist programmatically with the SDK, call it "Tracks From This Cool App". When I try to search to find the same playlist later, I get 0 results even if I search exactly for "Tracks From This Cool App". This seems like an error.

This is how I am searching
```objc
[SPTSearch performSearchWithQuery:@"Tracks%20From%20This%20Cool%20App" queryType:SPTQueryTypePlaylist accessToken:[session accessToken] callback:^(NSError *error, id object) {
}];
```

**Comment by sgoodwin** [comment]
Upon further investigation it turns out the documentation is not clear and it does in fact work.

Surely the Spotify SDK could do things like string escaping and not expect the user of the library to do that? The point of using the SDK is that it constructs the requests and handles the results *for* us. Yes?

**Comment by Voxar** [comment]
The SDK should escape strings if necessary. For example in your example the percent signs should be escaped by the SDK before hitting the web api. 

The correct usage should be `[SPTSearch performSearchWithQuery:@"Tracks From This Cool App" ...];`

**Comment by sgoodwin** [comment]
Good that it is fixed now. Odd that it took more than a year to get a response about this. =/
