### ISSUE TITLE
iOS 9 Beta 5 - login fails

### ISSUE THREAD

**Issue by Anders27** [spotify/ios-sdk#417]
Since iOS 9 beta 5 my app (also the “Simple Track Playback” sample app) fails to login to Spotify with the following error:

2015-08-10 12:05:39.526 Simple Track Playback[428:209398] NSURLSession/NSURLConnection HTTP load failed (kCFStreamErrorDomainSSL, -9802)

Any solution to this problem?

**Comment by alexissan** [comment]
The problem is that apple introduced ATS (App Transport Security) in iOS 9 
https://developer.apple.com/library/prerelease/ios/technotes/App-Transport-Security-Technote/
You can set read this tutorial to fix it (http://code.tutsplus.com/articles/apple-tightens-security-with-app-transport-security--cms-24420).

I tried the option that allows all load and the spotify API worked.
...
    <key>NSAppTransportSecurity</key>
    <dict>
        <key>NSAllowsArbitraryLoads</key>
        <true/>
    </dict>
    ...

I would like to know the domain where the spotify API requests are going to use the NSExceptionDomains and set the spotify domaind there.

**Comment by ablinov** [comment]
I would second knowing the list of domains that the SDK is talking to.

**Comment by CVertex** [comment]
Me too for iOS 9 security

**Comment by lisbakke** [comment]
Ping.

Any update?

**Comment by doguhanokumus** [comment]
+1

**Comment by dbuddah** [comment]
+1 for knowing which domains to except. 
Allowing arbitrary loads across the entire app is not a good solution for app devs. 

Or better yet, update the spotify servers to use modern SSL

**Comment by abrock17** [comment]
Bump.

Any word on this?  I'd prefer not to submit my app with the "NSAllowsArbitraryLoads" property.

**Comment by lawrencek7** [comment]
If you would like to handle the specific domain, please add the following to your info.plist:
```
    <key>NSAppTransportSecurity</key>
    <dict>
        <key>NSExceptionDomains</key>
        <dict>
            <key>cloudfront.net</key>
            <dict>
                <key>NSIncludesSubdomains</key>
                <true/>
                <key>NSThirdPartyExceptionAllowsInsecureHTTPLoads</key>
                <true/>
            </dict>
        </dict>
    </dict>
```

**Comment by mmontoyas** [comment]
Hello,
Actually the proposed solution doesn't work for me.
I have tried:
<key>accounts.spotify.com</key>
			<dict>
				<key>NSIncludesSubdomains</key>
				<true/>
				<key>NSThirdPartyExceptionAllowsInsecureHTTPLoads</key>
				<true/>
			</dict>
<key>api.spotify.com</key>
            <dict>
                <key>NSIncludesSubdomains</key>
                <true/>
                <key>NSThirdPartyExceptionAllowsInsecureHTTPLoads</key>
                <true/>
            </dict>

I also tried with the generic domain :
<key>spotify.com</key>
            <dict>
                <key>NSIncludesSubdomains</key>
                <true/>
                <key>NSThirdPartyExceptionAllowsInsecureHTTPLoads</key>
                <true/>
            </dict>

Could you please advice on this ? This has to do with ATS support for IOS 9.
