### ISSUE TITLE
Feature request: I'd like to know what track is currently being played by Spotify iOS app

### ISSUE THREAD

**Issue by LucasCoelho** [spotify/ios-sdk#418]
If I have the Spotify app installed and my app uses this SDK, I'd like my app to be able to know that the user is listening to right now

**Comment by maxmars** [comment]
Same here. Thank you.

**Comment by mhuusko5** [comment]
+1

**Comment by mhuusko5** [comment]
And even better, be able to communicate with the Spotify app/tell it what to play

**Comment by lehrblogger** [comment]
+1

**Comment by stephenhandley** [comment]
For Apple Music, this functionality is provided by `MPMusicPlayerController.systemMusicPlayer().nowPlayingItem`. 

There is an application scoped player accessible from `MPMusicPlayerController.applicationMusicPlayer()`. 

Maybe I'm wrong, but I'm assuming SPTAudioStreamingController wraps the latter? 

Maybe it would be possible for SPTAudioStreamingController to have a similar access pattern to MPMusicPlayerController: 
`SPTAudioStreamingController.spotifyMusicPlayer() -> the spotify app player`
`SPTAudioStreamingController.applicationMusicPlayer() -> application scoped player (what's currently available from initWithClientId:)`

**Comment by J0shuaw** [comment]
+1 so much

**Comment by BeamerCola** [comment]
Anybody get this working?  I was under the impression you could access the metadata of whatever is playing regardless of app, but I'm finding I'm probably wrong...

**Comment by gesabo** [comment]
+1 for this functionality

**Comment by saru2020** [comment]
+1
But, still no response from the Spotify team?

**Comment by arirawr** [comment]
Hi all, the recommended way of doing this is through the new [App Remote SDK](https://developer.spotify.com/documentation/ios-app-remote/), which allows your application to interact with the Spotify app running in the background on a user’s device. Capabilities include getting metadata for the currently playing track and context as well as issuing playback commands.

You can easily subscribe to the Spotify app's `PlayerState` like this:
```
func playerStateDidChange(_ playerState: SPTAppRemotePlayerState) {
  // view info about current playback in playerState object
  debugPrint("Track name: %@", playerState.track.name)
}
```

You can also control the Spotify app's playback directly: `appRemote.authorizeAndPlayURI(spotifyuri)`

Check out the full documentation here: https://developer.spotify.com/documentation/ios-app-remote/
And let us know if you have any feedback here: https://github.com/spotify/ios-app-remote-sdk

I'm going to close this issue, as this functionality will not be implemented in the SDK this issue tracker pertains to 🙂
