### ISSUE TITLE
Trouble with authentication when user already logged into facebook 

### ISSUE THREAD

**Issue by ronakvora** [spotify/ios-sdk#420]
When using SPTAuthViewController and being already logged in, when I click the login button for facebook, it takes me to another view that says you're logged in as Ronak Vora. But, the delegate method authenticationViewController:didLoginWithSession doesn't fire. 

Is this a bug or am I doing something wrong? 

Thanks in advance.

Cheers,
Ronak

**Comment by bdaneshgar** [comment]
+1

**Comment by bass4aj** [comment]
+1

**Comment by ahallora** [comment]
+1

I would be nice if I could transfer a valid Facebook Access Token to the SPTAuthViewController so when the user logs into Spotify via the Facebook Login button from the SPTAuthViewController the previously provided Facebook Access Token is used to authenticate the Facebook user without having the user type in their Facebook credentials again.

**Comment by erdtman** [comment]
Sorry for not getting back earlier. In an attempt to get a better overview of the issues we are cleaning out some of the older issues. If this issue is still a problem in the latest SDK please reopen this issue or open a new one.
