### ISSUE TITLE
SPTAuthViewController issues

### ISSUE THREAD

**Issue by bdaneshgar** [spotify/ios-sdk#421]
Hi! I am having trouble authorizing Spotify. The first time I believe I logged in but it froze up on the last page of the authentication process. Now when I restart the app to log in and hit the 'log in with Spotify" button, the popover is a blank screen. Also when I delete and reinstall the app, the login screen appears but won't proceed past me entering my username and password. I appreciate the help here

**Comment by bdaneshgar** [comment]
I am following this tutorial http://pachulski.me/2015/spotifyframework-with-swift/

**Comment by bdaneshgar** [comment]
I appreciate any input

**Comment by matijse** [comment]
When you log in in the Spotify login window and leave the box "Remember me" ticked, you will be logged in to Spotify when the login screen opens for the second time. In my app this shows as a blank screen that closes after some time (which gives a new session/token).

You can log out of Spotify from within the Login view by running this code:

```
SPTAuthViewController *authViewController = [SPTAuthViewController authenticationViewController];
[authViewController clearCookies:nil];
```

**Comment by bdaneshgar** [comment]
Thank you! This solves that blank screen. My main issue at this point is that logging in is not performing the segue. This method is not being called:
```
- (void)authenticationViewController:(SPTAuthViewController *)viewcontroller didLoginWithSession:(SPTSession *)session {
    self.statusLabel.text = @"";
    [self showPlayer];
}
```
Also what makes the token valid? Because this isn't being called after I do log in:
```
    if ([auth.session isValid] && self.firstLoad) {
        // It's still valid, show the player.
        NSLog(@"sup2");
        [self showPlayer];
        return;
    }
```

**Comment by matijse** [comment]
Did you set the `delegate` of the `SPTAuthViewController`?

This should be a class that implements the `SPTAuthViewDelegate` protocol, which specifies the `didLoginWithSession` method (and the failure / cancel methods)


To keep sessions saved between app launches, specify a `sessionUserDefaultsKey` on the session before logging in:

```
[[SPTAuth defaultInstance] setSessionUserDefaultsKey:@kSpotifySessionUserDefaultsKey];
```

**Comment by bdaneshgar** [comment]
I set the delegate, the ``` didCancelLogin ``` method is being recognized. Just not ```didLoginWithSession```. 

Also here is in my ```viewWillAppear```, which won't print "Token is valid":
```
SPTAuth *auth = [SPTAuth defaultInstance];
    if (auth.session == nil) {
        NSLog(@"There is a token");
        self.statusLabel.text = @"";
        return;
    }
    if ([auth.session isValid] && self.firstLoad) {
        NSLog(@"Token is valid");
        [self showPlayer];
        return;
    }
    
    self.statusLabel.text = @"Token expired.";
    if (auth.hasTokenRefreshService) {
        NSLog(@"Token expired");
        [self renewTokenAndShowPlayer];
        return;
    }
```

**Comment by bdaneshgar** [comment]
I am using virtually the same code as in the Simple Track Playback demo's [LoginController](https://github.com/spotify/ios-sdk/blob/master/Demo%20Projects/Simple%20Track%20Playback/Simple%20Track%20Playback/LoginController.m
)

**Comment by erdtman** [comment]
Sorry for not getting back earlier. In an attempt to get a better overview of the issues we are cleaning out some of the older issues. If this issue is still a problem in the latest SDK please reopen this issue or open a new one.

**Comment by kerstin-h** [comment]
The delegate is never called after login if your callback method has a http in it. It should look something like: @"my-app-login://callback". This is a bit vague in the Spotify instructions.

Also the Spotify login popup comes up blank if you call it before the viewDidAppear in your view controller.
