### ISSUE TITLE
+[NSError errorWithSpError:] when initializing player

### ISSUE THREAD

**Issue by sajsanghvi** [spotify/ios-sdk#422]
Trying to login with a Spotify premium account. One account is throwing an exception. Other Spotify accounts work. 

+[NSError errorWithSpError:]: unrecognized selector sent to class 0x1988a24c0

Occurence begins with [SPTAudioStreamingController runBackgroundLoop]

Last code that runs on My end is 
[self.player2 loginWithSession:[SPTAuth defaultInstance].session callback:^(NSError *error) {
        
        printf("YUP");
    }];

The function does not print YUP and throws the error. 

I am 99% sure this is an error on Spotify's end because I have used the same method with about 20 other Spotify accounts and it all works. Could be an irregularity with this account too?

**Comment by ahallora** [comment]
I'm not answering on behalf of the Spotify team, but I guess it would ease the bugfixing for the Spotify guys, if you would disclose the username for the premium account that is generating the error. :smile:

**Comment by bassntweeter** [comment]
Please look at the solution presented in #474 and work from there.

**Comment by mxcl** [comment]
The solution in #474 does not help me, I haven't even gotten as far as asking to play a track in my code.

I'm extremely worried with how unmaintained this library is, what do Spotify expect us to do exactly?
