### ISSUE TITLE
Is it difficult to get a partnership with Spotify?

### ISSUE THREAD

**Issue by Jackc415** [spotify/ios-sdk#425]
I'm working on an iPhone app that uses Spotify. I want to put banner ads at the bottom of the screen, but I guess this is prohibited because my app is now using Spotify for commercial use. So I signed up for a partnership. Does Spotify reject partnerships, and if so, what can I do to make sure that Spotify would allow me to have ads in my app?

**Comment by thelinmichael** [comment]
Hey @Jackc415. This issue tracker isn't an appropriate place to discuss Terms of Use and partnerships, but that you direct these queries at https://partners.spotify.com/. It may take some time to get a response unfortunately. Meanwhile, I advise that you read the Terms of Use carefully and try to adhere to them as best as you can.
