### ISSUE TITLE
Crash in Spotify SDK

### ISSUE THREAD

**Issue by Brad-Jackson** [spotify/ios-sdk#426]
This is the call stack from a customers machine, so I am afraid I cannot give any more details.
I am using SDK version beta-10.

Exception SIGSEGV

+[SPTAudioStreamingController runBackgroundRunloop:] (in Manager) (SPTAudioStreamingController.m:1464)

Thanks

**Comment by sajsanghvi** [comment]
+1

**Comment by sajsanghvi** [comment]
Figured out the solution. the user does not have SPTstreamingauth activated. This parameter must be turned on when the user logs in with spotify. If that is not set and you try initializing the player, it comes up with this crash.

**Comment by Brad-Jackson** [comment]
Not sure what you mean by SPTstreamingauth, do you mean SPTAuthStreamingScope?

**Comment by sajsanghvi** [comment]
yes

**Comment by Brad-Jackson** [comment]
Ah, that is no help to me then.

**Comment by kcfin** [comment]
+1 I'm getting the same error (but I do have SPTAuthStreamingScope) - no idea why.

**Comment by erdtman** [comment]
Sorry for not getting back earlier. In an attempt to get a better overview of the issues we are cleaning out some of the older issues. If this issue is still a problem in the latest SDK please reopen this issue or open a new one.
