### ISSUE TITLE
Accounts API /api/token - Error 500 + 400

### ISSUE THREAD

**Issue by plougy** [spotify/ios-sdk#428]
I get sometime an **error 500** from `https://accounts.spotify.com/api/token` with the following data:
```Objective-C
NSDictionary *params = @{
        @"grant_type":@"authorization_code",
        @"code":self.authorizationCode,
        @"redirect_uri":[BKSpotifyAuth shared].redirectURL.absoluteString,
        @"client_id":[BKSpotifyAuth shared].clientID,
        @"client_secret":[BKSpotifyAuth shared].clientSecret
};
```

Otherwise, it's normal to sometime have a space + right brace `" }"` in the 2 last lettering for the authorization code?

[UPDATE]
We get also (often) **errors 400** with this response, while the authorization code is generated by the SDK just before this request:
```json
{"error":"invalid_grant","error_description":"Invalid authorization code"}
```

**Comment by erdtman** [comment]
Sorry for not getting back earlier. In an attempt to get a better overview of the issues we are cleaning out some of the older issues. If this issue is still a problem in the latest SDK please reopen this issue or open a new one.
