### ISSUE TITLE
multiple linker warnings : ( was built for newer iOS version (7.1) than being linked (7.0) )

### ISSUE THREAD

**Issue by virenenskully** [spotify/ios-sdk#431]
SDK Release: Beta-10 
Xcode version: Version 7.0 beta 6 (7A192o)

Issue: Multiple linker warnings

Additional Info: Changing the deployment to 7.1 does not help. 
Diagnosis: Apparently Spotify iOS SDK was released by building for 7.1 instead of documented 7.0. :( :(

Logs/Snapshot of my build:

Ld /Users/HIDDENNAME/Library/Developer/Xcode/DerivedData/Skully-elurlplvaxispbapjqamluzbvstl/Build/Products/Debug-iphoneos/Skully.app/Skully normal arm64

    export IPHONEOS_DEPLOYMENT_TARGET=7.0
    /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.0.sdk 
	
ld: warning: object file (/Users/HIDDENNAME/git/ios/skully-ios-clean-build/SKUL-854/3p/Spotify.framework/Spotify(ads.c.o)) was built for newer iOS version (7.1) than being linked (7.0)
ld: warning: object file (/Users/HIDDENNAME/git/ios/skully-ios-clean-build/SKUL-854/3p/Spotify.framework/Spotify(aes.c.o)) was built for newer iOS version (7.1) than being linked (7.0)
ld: warning: object file (/Users/HIDDENNAME/git/ios/skully-ios-clean-build/SKUL-854/3p/Spotify.framework/Spotify(ap.c.o)) was built for newer iOS version (7.1) than being linked (7.0)
ld: warning: object file (/Users/HIDDENNAME/git/ios/skully-ios-clean-build/SKUL-854/3p/Spotify.framework/Spotify(audio_streamer.c.o)) was built for newer iOS version (7.1) than being linked (7.0)
ld: warning: object file (/Users/HIDDENNAME/git/ios/skully-ios-clean-build/SKUL-854/3p/Spotify.framework/Spotify(bignum.c.o)) was built for newer iOS version (7.1) than being linked (7.0)
ld: warning: object file (/Users/HIDDENNAME/git/ios/skully-ios-clean-build/SKUL-854/3p/Spotify.framework/Spotify(browse_pb.c.o)) was built for newer iOS version (7.1) than being linked (7.0)
ld: warning: object file (/Users/HIDDENNAME/git/ios/skully-ios-clean-build/SKUL-854/3p/Spotify.framework/Spotify(crypto.c.o)) was built for newer iOS version (7.1) than being linked (7.0)
ld: warning: object file (/Users/HIDDENNAME/git/ios/skully-ios-clean-build/SKUL-854/3p/Spotify.framework/Spotify(itemlist.c.o)) was built for newer iOS version (7.1) than being linked (7.0)
ld: warning: object file (/Users/HIDDENNAME/git/ios/skully-ios-clean-build/SKUL-854/3p/Spotify.framework/Spotify(link.c.o)) was built for newer iOS version (7.1) than being linked (7.0)
ld: warning: object file (/Users/HIDDENNAME/git/ios/skully-ios-clean-build/SKUL-854/3p/Spotify.framework/Spotify(playlist.c.o)) was built for newer iOS version (7.1) than being linked (7.0)
ld: warning: object file (/Users/HIDDENNAME/git/ios/skully-ios-clean-build/SKUL-854/3p/Spotify.framework/Spotify(protobuf.c.o)) was built for newer iOS version (7.1) than being linked (7.0)
ld: warning: object file (/Users/HIDDENNAME/git/ios/skully-ios-clean-build/SKUL-854/3p/Spotify.framework/Spotify(sha1.c.o)) was built for newer iOS version (7.1) than being linked (7.0)
ld: warning: object file (/Users/HIDDENNAME/git/ios/skully-ios-clean-build/SKUL-854/3p/Spotify.framework/Spotify(shannon.c.o)) was built for newer iOS version (7.1) than being linked (7.0)
ld: warning: object file (/Users/HIDDENNAME/git/ios/skully-ios-clean-build/SKUL-854/3p/Spotify.framework/Spotify(tinfl.c.o)) was built for newer iOS version (7.1) than being linked (7.0)
ld: warning: object file (/Users/HIDDENNAME/git/ios/skully-ios-clean-build/SKUL-854/3p/Spotify.framework/Spotify(tsp.c.o)) was built for newer iOS version (7.1) than being linked (7.0)
ld: warning: object file (/Users/HIDDENNAME/git/ios/skully-ios-clean-build/SKUL-854/3p/Spotify.framework/Spotify(trackplayer.c.o)) was built for newer iOS version (7.1) than being linked (7.0)
ld: warning: object file (/Users/HIDDENNAME/git/ios/skully-ios-clean-build/SKUL-854/3p/Spotify.framework/Spotify(tremor_decoder.c.o)) was built for newer iOS version (7.1) than being linked (7.0)
ld: warning: object file (/Users/HIDDENNAME/git/ios/skully-ios-clean-build/SKUL-854/3p/Spotify.framework/Spotify(util.c.o)) was built for newer iOS version (7.1) than being linked (7.0)
ld: warning: object file (/Users/HIDDENNAME/git/ios/skully-ios-clean-build/SKUL-854/3p/Spotify.framework/Spotify(xml.c.o)) was built for newer iOS version (7.1) than being linked (7.0)
ld: warning: object file (/Users/HIDDENNAME/git/ios/skully-ios-clean-build/SKUL-854/3p/Spotify.framework/Spotify(zeroconf.c.o)) was built for newer iOS version (7.1) than being linked (7.0)
ld: warning: object file (/Users/HIDDENNAME/git/ios/skully-ios-clean-build/SKUL-854/3p/Spotify.framework/Spotify(spotify_embedded.c.o)) was built for newer iOS version (7.1) than being linked (7.0)
ld: warning: object file (/Users/HIDDENNAME/git/ios/skully-ios-clean-build/SKUL-854/3p/Spotify.framework/Spotify(base64.c.o)) was built for newer iOS version (7.1) than being linked (7.0)
ld: warning: object file (/Users/HIDDENNAME/git/ios/skully-ios-clean-build/SKUL-854/3p/Spotify.framework/Spotify(spotify_esdk.c.o)) was built for newer iOS version (7.1) than being linked (7.0)
ld: warning: object file (/Users/HIDDENNAME/git/ios/skully-ios-clean-build/SKUL-854/3p/Spotify.framework/Spotify(mod_ap_conn.c.o)) was built for newer iOS version (7.1) than being linked (7.0)
ld: warning: object file (/Users/HIDDENNAME/git/ios/skully-ios-clean-build/SKUL-854/3p/Spotify.framework/Spotify(mod_streamer.c.o)) was built for newer iOS version (7.1) than being linked (7.0)
ld: warning: object file (/Users/HIDDENNAME/git/ios/skully-ios-clean-build/SKUL-854/3p/Spotify.framework/Spotify(mod_socket_manager.c.o)) was built for newer iOS version (7.1) than being linked (7.0)
ld: warning: object file (/Users/HIDDENNAME/git/ios/skully-ios-clean-build/SKUL-854/3p/Spotify.framework/Spotify(mod_tsp.c.o)) was built for newer iOS version (7.1) than being linked (7.0)
ld: warning: object file (/Users/HIDDENNAME/git/ios/skully-ios-clean-build/SKUL-854/3p/Spotify.framework/Spotify(mod_trackplayer.c.o)) was built for newer iOS version (7.1) than being linked (7.0)
ld: warning: object file (/Users/HIDDENNAME/git/ios/skully-ios-clean-build/SKUL-854/3p/Spotify.framework/Spotify(korn.c.o)) was built for newer iOS version (7.1) than being linked (7.0)
ld: warning: object file (/Users/HIDDENNAME/git/ios/skully-ios-clean-build/SKUL-854/3p/Spotify.framework/Spotify(bitwise.c.o)) was built for newer iOS version (7.1) than being linked (7.0)
ld: warning: object file (/Users/HIDDENNAME/git/ios/skully-ios-clean-build/SKUL-854/3p/Spotify.framework/Spotify(codebook.c.o)) was built for newer iOS version (7.1) than being linked (7.0)
ld: warning: object file (/Users/HIDDENNAME/git/ios/skully-ios-clean-build/SKUL-854/3p/Spotify.framework/Spotify(codebook_perf.c.o)) was built for newer iOS version (7.1) than being linked (7.0)
ld: warning: object file (/Users/HIDDENNAME/git/ios/skully-ios-clean-build/SKUL-854/3p/Spotify.framework/Spotify(dsp.c.o)) was built for newer iOS version (7.1) than being linked (7.0)
ld: warning: object file (/Users/HIDDENNAME/git/ios/skully-ios-clean-build/SKUL-854/3p/Spotify.framework/Spotify(floor1.c.o)) was built for newer iOS version (7.1) than being linked (7.0)
ld: warning: object file (/Users/HIDDENNAME/git/ios/skully-ios-clean-build/SKUL-854/3p/Spotify.framework/Spotify(floor_lookup.c.o)) was built for newer iOS version (7.1) than being linked (7.0)
ld: warning: object file (/Users/HIDDENNAME/git/ios/skully-ios-clean-build/SKUL-854/3p/Spotify.framework/Spotify(framing.c.o)) was built for newer iOS version (7.1) than being linked (7.0)
ld: warning: object file (/Users/HIDDENNAME/git/ios/skully-ios-clean-build/SKUL-854/3p/Spotify.framework/Spotify(misc.c.o)) was built for newer iOS version (7.1) than being linked (7.0)
ld: warning: object file (/Users/HIDDENNAME/git/ios/skully-ios-clean-build/SKUL-854/3p/Spotify.framework/Spotify(res012.c.o)) was built for newer iOS version (7.1) than being linked (7.0)
ld: warning: object file (/Users/HIDDENNAME/git/ios/skully-ios-clean-build/SKUL-854/3p/Spotify.framework/Spotify(mapping0.c.o)) was built for newer iOS version (7.1) than being linked (7.0)
ld: warning: object file (/Users/HIDDENNAME/git/ios/skully-ios-clean-build/SKUL-854/3p/Spotify.framework/Spotify(mdct.c.o)) was built for newer iOS version (7.1) than being linked (7.0)
ld: warning: object file (/Users/HIDDENNAME/git/ios/skully-ios-clean-build/SKUL-854/3p/Spotify.framework/Spotify(info.c.o)) was built for newer iOS version (7.1) than being linked (7.0)
ld: warning: object file (/Users/HIDDENNAME/git/ios/skully-ios-clean-build/SKUL-854/3p/Spotify.framework/Spotify(make_tremor_tables.c.o)) was built for newer iOS version (7.1) than being linked (7.0)
ld: warning: object file (/Users/HIDDENNAME/git/ios/skully-ios-clean-build/SKUL-854/3p/Spotify.framework/Spotify(tlsf.c.o)) was built for newer iOS version (7.1) than being linked (7.0)
ld: warning: object file (/Users/HIDDENNAME/git/ios/skully-ios-clean-build/SKUL-854/3p/Spotify.framework/Spotify(tlsf3.c.o)) was built for newer iOS version (7.1) than being linked (7.0)
ld: warning: object file (/Users/HIDDENNAME/git/ios/skully-ios-clean-build/SKUL-854/3p/Spotify.framework/Spotify(diskcache.c.o)) was built for newer iOS version (7.1) than being linked (7.0)
ld: warning: object file (/Users/HIDDENNAME/git/ios/skully-ios-clean-build/SKUL-854/3p/Spotify.framework/Spotify(strlcpy.c.o)) was built for newer iOS version (7.1) than being linked (7.0)
ld: warning: object file (/Users/HIDDENNAME/git/ios/skully-ios-clean-build/SKUL-854/3p/Spotify.framework/Spotify(strncasecmp.c.o)) was built for newer iOS version (7.1) than being linked (7.0)
ld: warning: object file (/Users/HIDDENNAME/git/ios/skully-ios-clean-build/SKUL-854/3p/Spotify.framework/Spotify(bsd_socket_common.c.o)) was built for newer iOS version (7.1) than being linked (7.0)
ld: warning: object file (/Users/HIDDENNAME/git/ios/skully-ios-clean-build/SKUL-854/3p/Spotify.framework/Spotify(bsd_socket.c.o)) was built for newer iOS version (7.1) than being linked (7.0)
ld: warning: object file (/Users/HIDDENNAME/git/ios/skully-ios-clean-build/SKUL-854/3p/Spotify.framework/Spotify(os_util.c.o)) was built for newer iOS version (7.1) than being linked (7.0)

**Comment by ArturBaghdas** [comment]
add this line to your podfile - platform :ios, '7.0'
then run script "pod update"

**Comment by ronakvora** [comment]
You need to update both the Project's Deployment target, as well as any Target you're building's deployment target. If you click on Project > Info > iOS Deployment target, you can update the Project's settings. 

To update the target's Deployment target, click on the target, Build Settings, and search for IPHONEOS_DEPLOYMENT_TARGET.

Hope this helps.

**Comment by virenenskully** [comment]
tried both the approaches again and none of these work. :( still all the linker errors

**Comment by ronakvora** [comment]
Paste a picture of the warnings from the left side of XCode

**Comment by virenenskully** [comment]
![for-github-spotify-issue](https://cloud.githubusercontent.com/assets/13240744/10324776/218ca2e8-6c41-11e5-8d96-5c721ab9c48c.png)

**Comment by ronakvora** [comment]
No the whole thing. With the target.

**Comment by virenenskully** [comment]
![for-spotify](https://cloud.githubusercontent.com/assets/13240744/10469034/6107b77a-71b7-11e5-8973-24f272f7f5ef.png)

**Comment by ronakvora** [comment]
This still doesn't have the target in it. The Target is the highest level in the hierarchy.

**Comment by loretoparisi** [comment]
It seems that it was build using XCode 7.1beta, that set up the deployment target to the highest level, so iOS 7.1 as @ronakvora said.

**Comment by ronakvora** [comment]
Also, you need to upload the Deployment Target to 7.1. If you're using 7.0 (and are required to be compatible with 7.0), there's nothing you can do about this. You'd just have to wait for Spotify to rebuild their SDK.

**Comment by ronakvora** [comment]
If you have to use 7.0, you can suppress the warnings by trying: 

http://stackoverflow.com/questions/14617706/how-do-i-disable-warnings-for-a-static-framework-in-xcode

**Comment by DmytroAnkudinov** [comment]
Issue obsolete as of Oct 2016.
