### ISSUE TITLE
Error while renewing the session : Error Domain=com.spotify.auth Code=400 "No refresh token available in the session!

### ISSUE THREAD

**Issue by ramkrishnazingma** [spotify/ios-sdk#432]
Hi Spotify Developer,

I am getting these error while renewing the session.

Please find the below code.

I am getting the accessToken from server but when I create the SPTSession then it gives me error.

SPTSession *extendSession = [[SPTSession alloc] initWithUserName:@"soundrobin" accessToken:dictResult[@"access_token"] expirationTimeInterval:3600];

 [[SPTAuth defaultInstance] renewSession:extendSession callback:^(NSError *error, SPTSession *session) {
});

Please do the needful.

**Comment by ronakvora** [comment]
Did you set SPTAuth's tokenRefreshUrl and tokenSwapUrl to your backend's endpoint?

**Comment by ramkrishnazingma** [comment]
It is solved instead of "SPTSession *extendSession = [[SPTSession alloc] initWithUserName:@"soundrobin" accessToken:dictResult[@"access_token"] expirationTimeInterval:3600];" I have used the "SPTSession *extendSession = [[SPTSession alloc] initWithUserName:@"soundrobin" accessToken:dictResult[@"access_token"] encryptedRefreshToken:strEncryptedRefreshToken expirationDate:nil];".

And successfully get the updated access token.

**Comment by parthpatel1105** [comment]
@ramkrishnazingma  From where you get strEncryptedRefreshToken? I am having same issue while renew Spotify session. I am getting error like: 

`Error Domain=com.spotify.auth Code=400 "No refresh token available in the session!"`
