### ISSUE TITLE
Distribute dynamic framework as well as static framework for each release?

### ISSUE THREAD

**Issue by mhuusko5** [spotify/ios-sdk#433]
Would it be possible to build/distribute a dynamic framework version of the SDK for each release? There's issues with CocoaPods + Swift + static libraries as transitive dependencies...

**Comment by loretoparisi** [comment]
I you want to embed your Spotify.framework inside a separate SDK that you are using in your app, you can simply 

1) Open ```Spotify.framework```

```bash
macbookproloreto:ios-sdk admin$ cd Spotify.framework/
macbookproloreto:Spotify.framework admin$ ls -l
total 24
lrwxr-xr-x  1 admin  staff   24 20 Nov  2014 Headers -> Versions/Current/Headers
lrwxr-xr-x  1 admin  staff   26 20 Nov  2014 Resources -> Versions/Current/Resources
lrwxr-xr-x  1 admin  staff   24 20 Nov  2014 Spotify -> Versions/Current/Spotify
drwxr-xr-x  4 admin  staff  136 20 Nov  2014 Versions
```

2) Copy the headers in a new folder let's say SpotfiyStatic/

```bash
macbookproloreto:Spotify.framework admin$ cd Headers
macbookproloreto:Headers admin$ ls -l
total 552
-rw-r--r--  1 admin  staff   8637  8 Mag 15:50 SPTAlbum.h
-rw-r--r--  1 admin  staff  13528  8 Mag 15:50 SPTArtist.h
...
```

3) Copy the static library current version and rename as ".a" library

```bash
macbookproloreto:Spotify.framework admin$ ls -l Versions/Current/Spotify 
-rw-r--r--  1 admin  staff  10271912 16 Lug 16:40 Versions/Current/Spotify
```

At this point you should have a new folder like

```bash
SpotifyStatic/Headers/
SpotifyStatic/Headers/SPTAlbum.h
SpotifyStatic/Headers/SPTArtist.h
...
SpotfiyStatic/Spotify.a 
```

This is ready to be used in your .framework project to be embedded in your app.

Note: Of course it's a workaround, but basically it's just an unpacking of a .framework static library structure.

**Comment by erdtman** [comment]
We currently have no plans for a dynamic library.
