### ISSUE TITLE
Unable to play the track.

### ISSUE THREAD

**Issue by ramkrishnazingma** [spotify/ios-sdk#434]
When I am trying to play the track then it could not play and it goes to  "- (void)audioStreaming:(SPTAudioStreamingController *)audioStreaming didFailToPlayTrack:(NSURL *)trackUri" delegate method of SPTAudioStreamingController.

Also we can not get any information from api which stated that the track is not playable.

When I try to look into the web player of Spotify, search the song then I had found that the user neither  select nor play the song, so my question is that how the Spotify recognise that the track is not playable. For that I had attached the screenshot where I marked the red circle on particular track which was not playable.

Please do the needful and let me know that any information which available in the api for identify the track is not playable.

![screen shot 2015-09-01 at 7 38 33 pm](https://cloud.githubusercontent.com/assets/8779258/9607264/cc513f76-50e5-11e5-9aa1-acb180a632ee.png)

**Comment by CVertex** [comment]
From Australia, I see lots of the same issues. Sometimes I get a message from Spotify saying "this song isn't available in your country". Most of the time I see a greyed out track like you do.

I'm not sure of the exact reason those songs aren't available in your region, but my guess it has to do with a gap between licensing availability in your playback region and spotifys metadata.

I wish the spotify API would only expose songs that they had licensing rights to in their particular region, but it appears there's been an engineering trade made between metadata and content availability. Who knows, maybe soon that track will be available in your region?

**Comment by erdtman** [comment]
Sorry for not getting back earlier. In an attempt to get a better overview of the issues we are cleaning out some of the older issues. If this issue is still a problem in the latest SDK please reopen this issue or open a new one.
