### ISSUE TITLE
SPTAuthViewController should have a method to delete UIWebView Session cookies

### ISSUE THREAD

**Issue by loretoparisi** [spotify/ios-sdk#435]
If a user logins with a 'wrong account' (i.e. let's say a second account that belongs to that user), and he wants to switch to another account, he will not able to do that, since, as soon as the user is logged in through the UIWebView, some session cookie has been saved, so that, each time the user tries to login again, the app will get the oAuth steps completed already, and the SPTAuthViewController suddenly disappears, getting back the first logged in account. 

A concrete example is this one

1) A user logins with a free account X
2) The SDK gives back an error about this free account
3) The user tries now to login with another account (i.e. a premium)
4) The SPTAuthViewController will complete automatically the oAuth process resulting in the error 2)
5) The user has no way to switch to a new account 

The only way to delete these sessions cookies is to restart the app. In this case, the Spotify UIWebView  will start a oAuth process with clean cookies.

**Comment by matijse** [comment]
`SPTAuthViewController` has a method `clearCookies`

Example:

```
SPTAuthViewController *authViewController = [SPTAuthViewController authenticationViewController];
[authViewController clearCookies:nil];
```

**Comment by loretoparisi** [comment]
Wops! That's true!
