### ISSUE TITLE
playUris doesn't progress through the "playlist"

### ISSUE THREAD

**Issue by CVertex** [spotify/ios-sdk#436]
Howdy,

I'm using the new playUris:WithOptions:callback: method to queue about 16-30 tracks. Also, as per the docs, I've singletonized the SPTAudioStreamingController so there's only one instance running at a time

But when I try to make headless (no communication with a VC) playback, the SPTAudioStreamingController very often (almost 95% of the time) doesn't progress to the next track :( 

Even when I poll the SPTAudioStreamingController every second from my ViewController about 80% of the time the playlist doesn't move to the next track. 

It stalls on the first track at the end and doesn't progress forward.

Sometimes, I'll receive a generic error code 1001 from the track failure callback with the generic message "An unspecified playback error occurred".

I'm certain it;s not a regional issue as all these tracks work fine from the official Spotify Desktop App, and occasionally in my app. 

Using the old SPTrackProvider API seemed a lot more reliable.

This is driving me a bit bonkers... :unamused: 

Perhaps I'm using the API incorrectly. Any tips/advice? 

Thanks in advance,
CVertex

**Comment by indyfromoz** [comment]
Seeing the same problem prototyping a simple app. +1 for a fix to this issue, can anyone from Spotify please help?

Thanks!

**Comment by CVertex** [comment]
I'm still seeing this problem on beta 11. Almost 100% of the time it won't progress from track 0 to track 1 without manual intervention.

**Comment by CVertex** [comment]
This problem still happens on beta 12

**Comment by erdtman** [comment]
Sorry for not getting back earlier. In an attempt to get a better overview of the issues we are cleaning out some of the older issues. If this issue is still a problem in the latest SDK please reopen this issue or open a new one.
