### ISSUE TITLE
Playlist query returns insufficient (100) tracks

### ISSUE THREAD

**Issue by zakmandhro** [spotify/ios-sdk#437]
Hi there, the API call to return [tracks for a playlist](https://developer.spotify.com/web-api/get-playlists-tracks/) is limited to **100 tracks**.

We are getting complaints from several users that this limit doesn't work for them. They have 300+ tracks on some of their popular/followed playlists. 

Can you please update the API to increase the limit?

**Comment by jsimonsson** [comment]
The maximum amount of tracks in one fetch is 100. You can use offset and limit to fetch the remaining ones with more requests.
