### ISSUE TITLE
SPTAudioStreamingController  [OS_dispatch_source delegate]

### ISSUE THREAD

**Issue by joaoAvno** [spotify/ios-sdk#439]
Fatal Exception: NSInvalidArgumentException
-[OS_dispatch_source delegate]: unrecognized selector sent to instance 0x16e229b0

Thread : Fatal Exception: NSInvalidArgumentException
0  CoreFoundation                 0x248a1f8f __exceptionPreprocess
1  libobjc.A.dylib                0x33218c8b objc_exception_throw
2  CoreFoundation                 0x248a73a9 __methodDescriptionForSelector
3  CoreFoundation                 0x248a52c7 ___forwarding___
4  CoreFoundation                 0x247d4ba8 _CF_forwarding_prep_0
5  SonosPlayer                    0x0041966b __cb_on_connection_notify_block_invoke423 (SPTAudioStreamingController.m:986)
6  libdispatch.dylib              0x337a92e3 _dispatch_call_block_and_release
7  libdispatch.dylib              0x337a92cf _dispatch_client_callout
8  libdispatch.dylib              0x337acd2f _dispatch_main_queue_callback_4CF
9  CoreFoundation                 0x248673e9 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
10 CoreFoundation                 0x24865ae9 __CFRunLoopRun
11 CoreFoundation                 0x247b1f31 CFRunLoopRunSpecific
12 CoreFoundation                 0x247b1d43 CFRunLoopRunInMode
13 GraphicsServices               0x2c246201 GSEventRunModal
14 UIKit                          0x27f83879 UIApplicationMain
15 SonosPlayer                    0x001528db main (main.m:17)
16 libdyld.dylib                  0x337caaaf start

Any idea how to solve this crash?

**Comment by kcfin** [comment]
I had a similar crash...I made a simple mistake and just wasn't setting the delegate of the player. Try that if you're not?

**Comment by erdtman** [comment]
Sorry for not getting back earlier. In an attempt to get a better overview of the issues we are cleaning out some of the older issues. If this issue is still a problem in the latest SDK please reopen this issue or open a new one.
