### ISSUE TITLE
iOS 18 `authorizeAndPlayURI` broken

### ISSUE THREAD

**Issue by PhilipTrauner** [spotify/ios-sdk#440]
`authorizeAndPlayURI`  internally uses `UIApplication.openURL(_ url: URL) -> Bool`. While this method has been soft-deprecated for a while now, that appears to have changed in iOS 18.

```
BUG IN CLIENT OF UIKIT: The caller of UIApplication.openURL(_:) needs to migrate to the non-deprecated UIApplication.open(_:options:completionHandler:). Force returning false (NO).
```

`SPTSessionManager.initiateSession` does not appear to be affected.

## Workaround
This is the structure of the URL that `authorizeAndPlayURI` attempts to open:  

<details open>
<summary>when not playing as radio</summary>

```
spotify-action://authorize?response_type=token&client_id=<client-id>&redirect_uri=<redirect-uri>&play_uri=<play-uri>&bundle_id=<bundle-id>&minimum_version&analytics_id&remote_session_id=<remote-session-id>&scope=app-remote-control
```

</details>

<details>
<summary>when playing as radio</summary>

```
spotify-action://authorize?response_type=token&client_id=<client-id>&redirect_uri=<redirect-uri>&play_uri=<play-uri>&bundle_id=<bundle-id>&minimum_version&analytics_id&remote_session_id=<remote-session-id>&play_radio=true&scope=app-remote-control
```

</details>

`remote_session_id` is optional, and `play_uri` can be an empty string (`play_uri=`)

**Comment by zallanx** [comment]
Thanks for the super helpful report. Was not even aware that this was a hard depreciation that didn't jive with the prior versions of the SDK, which resulted in no audio.

Thankfully the new version, v 3.0.0 (https://github.com/spotify/ios-sdk/releases/tag/v3.0.0), solves this issue.

**Comment by PhilipTrauner** [comment]
as @zallanx mentioned, this is fixed in v3
