### ISSUE TITLE
Authentication workflow

### ISSUE THREAD

**Issue by JohnIve** [spotify/ios-sdk#441]
Hi,
I would like to add the spotify sdk to one on my app.
I test the iOS beta sdk 8 and iOS beta sdk 9 and i see that the authentication workflow is not the same.
iOS beta sdk 8 send the user to the spotify app and the iOS beta sdk 9 send the user to safari for login authentification.
There is a way to use the beta sdk 8 authentification workflow is the newer sdk ? check user authentification from the spotify application and return to the origin app.

**Comment by lawrencek7** [comment]
Hi, we had to roll-back the authentication method in iOS beta sdk 8 due to issues with that auth flow and that is why iOS beta sdk 9 (and all other sdk releases) use the web browser for auth. We are working to re-enable auth via the Spotify app in a future sdk release, but unfortunately I do not have any timing I can share right now.

**Comment by JohnIve** [comment]
Thank you for your reply,

When i use the sdk 8 i have this error "INVALID_REQUEST: Invalid app Identifier" if i use a validate app identifier can i use the sdk 8 in my app with the auth via the Spotify app ?

There is any risk or majeur issue for using this beta ?

If i can't, i will use the SPTAuthViewController for the authentication workflow and update the sdk when auth via the Spotify app will be enable.

Thanks

**Comment by lawrencek7** [comment]
When i use the sdk 8 i have this error "INVALID_REQUEST: Invalid app Identifier" if i use a validate app identifier can i use the sdk 8 in my app with the auth via the Spotify app ?
>No, this does not work right now. Please use the latest beta sdk.

There is any risk or majeur issue for using this beta ?
>Yes, auth doesn't work in this version

Please use the latest beta to avoid auth issues.

**Comment by JohnIve** [comment]
Ok,

i'll use the latest sdk and update it when auth via the Spotify app will be enable.

Kind regards!
