### ISSUE TITLE
How to get private playlists for the user?

### ISSUE THREAD

**Issue by mashkius** [spotify/ios-sdk#444]
I have been trying to get all the playlists for the user but only the ones, which are public are shown.
I have defined th scopes including the SPTAuthPlaylistReadPrivateScope.

    [SPTAuth defaultInstance].requestedScopes = @[SPTAuthStreamingScope,SPTAuthUserFollowModifyScope,SPTAuthUserLibraryModifyScope,SPTAuthUserReadPrivateScope,SPTAuthUserLibraryReadScope,SPTAuthUserFollowReadScope,SPTAuthPlaylistModifyPrivateScope,SPTAuthPlaylistModifyPublicScope,SPTAuthPlaylistReadPrivateScope,SPTAuthUserLibraryModifyScope

**Comment by matijse** [comment]
Are the other ones maybe collaborative playlists? See #423

**Comment by mashkius** [comment]
No,I have seen #423 but it did not help in getting the playlists.

**Comment by mashkius** [comment]
I don't know what has happened but it seems that Spotify has updated the api and it is able to get the private playlists.
