### ISSUE TITLE
SPTUser requestCurrentUserWithAccessToken returns user with territory as nil

### ISSUE THREAD

**Issue by mashkius** [spotify/ios-sdk#446]
SPTUser requestCurrentUserWithAccessToken returns user with territory as nil.
It returns displayName, canonicalUserName, etc. But the territory always nil.
I am trying to set this territory as a market and pass it on to other methods as the current country of the user might not be the same as registered with Spotify.
Any work-arounds?

**Comment by matijse** [comment]
You need the `SPTAuthUserReadPrivateScope` in order to read private properties, such as the user territory...
