### ISSUE TITLE
How to handle the interruption of phone call.

### ISSUE THREAD

**Issue by ramkrishnazingma** [spotify/ios-sdk#448]
As I have integrate the CoreTelephony framework for getting the status of phone call and play and stop the song. It works well when the application is active but it does not work in background. 

While testing the application on background I am getting the issue "AUIOClient_StartIO failing", so I had searched on google and found that it might be related to "AVAudioSession". As Spotify itself provide its own player so we can not alter there properties. 

Please guide me what should I do change in order to accomplish it.

**Comment by loretoparisi** [comment]
You need to handle audio interrupts like

```objective-c
AVAudioSession *session = [AVAudioSession sharedInstance];
    [[NSNotificationCenter defaultCenter] addObserver:self
                                             selector:@selector(audioSessionInterruptionNotification:)
                                                 name:AVAudioSessionInterruptionNotification
                                               object:session];
```


where your audio session interruption notification ```AVAudioSessionInterruptionNotification``` is something like 

```objective-c
-(void)audioSessionInterruptionNotification:(NSNotification*)notification {
    
    NSString* seccReason = @"";
    
    //Check the type of notification, especially if you are sending multiple AVAudioSession events here
    NSLog(@"Interruption notification name %@", notification.name);
    
    if ([notification.name isEqualToString:AVAudioSessionInterruptionNotification]) {
        seccReason = @"Interruption notification received";
        
        //Check to see if it was a Begin interruption
        if ([[notification.userInfo valueForKey:AVAudioSessionInterruptionTypeKey] isEqualToNumber:[NSNumber numberWithInt:AVAudioSessionInterruptionTypeBegan]]) {
            seccReason = @"Interruption began";
            
        } else if([[notification.userInfo valueForKey:AVAudioSessionInterruptionTypeKey] isEqualToNumber:[NSNumber numberWithInt:AVAudioSessionInterruptionTypeEnded]]){
            seccReason = @"Interruption ended!";
            //Resume your audio
        }
    }
}
```

You need to write your handling code then for interruption begin and end.

**Comment by ramkrishnazingma** [comment]
Thanks loretoparisi for your help.

I had checked it but got the same problem while the application in background as "AUIOClient_StartIO failing".

**Comment by ramkrishnazingma** [comment]
Why lawrencek7 you have closed the issue as it do not solve ? Please re-open the issue.

**Comment by ThuggishNuggets** [comment]
When an app using an `AVAudioSession` is backgrounded and the device receives a phone call and the user accepts that call, it triggers an `AVAudioSessionInterruptionNotification` with `AVAudioSessionInterruptionTypeKey == AVAudioSessionInterruptionTypeBegan `.

However, when the phone call ends, `AVAudioSessionInterruptionNotification` is never posted which means the code suggested by @loretoparisi is never executed. This is the case even if the app is currently executing in a backgrounded (see: not suspended) application state and running other code.

According to [Apple's Documentation on Responding to Interruptions](https://developer.apple.com/library/tvos/documentation/Audio/Conceptual/AudioSessionProgrammingGuide/HandlingAudioInterruptions/HandlingAudioInterruptions.html#//apple_ref/doc/uid/TP40007875-CH4-SW5):
> There is no guarantee that a begin interruption will have an end interruption. Your app needs to be aware of switching to a foreground running state or the user pressing a play button. In either case, determine whether your app should reactivate its audio session.

Which is, I assume, why people are attempting to use the CoreTelephony `CTCallCenter` class (or similar) to detect when phone call sessions end?

**Comment by ruchiDYL** [comment]
I am using this AVAudioSessionInterruptionNotification method for my app using Linphone-sdk, This notification does not notified until I accept the interrupted GSM call, in Case if I decline the GSM call my SIP call goes on hold already but I do not receive any kind of notification. Please suggest me if I am Missing some steps or any spacial case in my code … here is my code 
In View Will appear I added the observer like this 
     [[NSNotificationCenter defaultCenter] addObserver:self selector:@selector(handleAudioSessionInterruption:) name:AVAudioSessionInterruptionNotification object:[AVAudioSession sharedInstance]];

 Then implemented the method : 
- (void)handleAudioSessionInterruption:(NSNotification*)notification {
    
    NSNumber *interruptionType = [[notification userInfo] objectForKey:AVAudioSessionInterruptionTypeKey];
    NSNumber *interruptionOption = [[notification userInfo] objectForKey:AVAudioSessionInterruptionOptionKey];
    
    switch (interruptionType.unsignedIntegerValue) {
        case AVAudioSessionInterruptionTypeBegan:{
            NSLog(@"AVAudioSessionInterruptionTypeBegan");
            // • Audio has stopped, already inactive
            // • Change state of UI, etc., to reflect non-playing state
            LinphoneCore* lc = [LinphoneManager getLc];
            LinphoneCall *c = linphone_core_get_current_call(lc);
            NSLog(@"Sound interruption detected!");
            if ((c && linphone_call_get_state(c) == LinphoneCallStreamsRunning)) {
                linphone_core_pause_call(lc, c);

            }else if ((c && linphone_call_get_state(c) == LinphoneCallPausing) ||(c && linphone_call_get_state(c) == LinphoneCallPaused)){
                
            }
            [_pauseCallButton setSelected:YES];

        } break;
        case AVAudioSessionInterruptionTypeEnded:{
             NSLog(@"AVAudioSessionInterruptionTypeEnded");
            // • Make session active
            // • Update user interface
            // • AVAudioSessionInterruptionOptionShouldResume option
            if (interruptionOption.unsignedIntegerValue == AVAudioSessionInterruptionOptionShouldResume) {
                NSLog(@"Sound interruption ended!");
                
                LinphoneCore* lc = [LinphoneManager getLc];
                const MSList* c = linphone_core_get_calls(lc);
                if (c) {
                    ms_message("Auto resuming call");
                    linphone_core_resume_call(lc, (LinphoneCall*) c->data);
                    if ([_pauseCallButton isSelected]) {
                        [_pauseCallButton setSelected:NO];
                    }
                }
                
            }
        } break;
        default:
            break;
    }
}
