### ISSUE TITLE
'Repeat' not working as expected in SPTAudioStreamingController

### ISSUE THREAD

**Issue by zakmandhro** [spotify/ios-sdk#450]
I am trying to tell SPTAudioStreamingController to repeat a track from the current track in the queue:
```objc
SPTAudioStreamingController *player = /* initialization code */
player.repeat = YES;
```
The ```audioStreaming:didChangeRepeatStatus:``` delegate method fires but the player just continues on to next track in the queue.

What am I missing?

I am using beta-10.

**Comment by mashkius** [comment]
the repeat function does not repeat the current track from the queue. It repeats all queue when it ends.
