### ISSUE TITLE
Feature request: Programmatic access to SDK version

### ISSUE THREAD

**Issue by timburks** [spotify/ios-sdk#451]
Could we get an API call that returns an identifier for the Spotify SDK version that we are using? (Did I miss one if it exists?)

This could be any string or number that uniquely identifies the SDK version. It would be very helpful in error logs and detail screens.

**Comment by mindgraffiti** [comment]
+1

**Comment by DmytroAnkudinov** [comment]
Please use project version variables (number and string representations) found for every framework in its umbrella header. For example, for the framework `"SpotifyAudioPlayback.framework"` the umbrella header is `<SpotifyAudioPlayback.h>` and the variables representing the version are `SpotifyAudioPlaybackVersionNumber` and `SpotifyAuthenticationVersionString`.
The splitting and individual framework versions were introduced in Beta24.
