### ISSUE TITLE
SPTListPage.firstTrackPage return data changed

### ISSUE THREAD

**Issue by mashkius** [spotify/ios-sdk#452]
SPTListPage.firstTrackPage returned 0-99 items  few days ago.
Currently it does something strange. I haven't edited the code at all.
Is Spotify trying to change something here?

     playablePlaylist.firstTrackPage
     <SPTListPage: 0x7d88cbf0>: 0-4294967295 of 30 items

**Comment by ddramowicz** [comment]
I have had the same issue. Since you closed this issue, how did you resolve this, please?
