### ISSUE TITLE
A way of swapping/refreshing token without own server?

### ISSUE THREAD

**Issue by mashkius** [spotify/ios-sdk#453]
Is there a way to refresh/swap accessToken without setting my own server?
Probably with WEB API, but how?

**Comment by loretoparisi** [comment]
@mashkius oAuth 2.0 protocol requires 3rdparty services to act as a trusted authority. The key point is this:

```Shell
The proof-of-possession security concept assumes that the
   authorization server acts as a trusted third party that binds keys to
   access tokens.  These keys are then used by the client to demonstrate
   the possession of the secret to the resource server when accessing
   the resource.  The resource server, when receiving an access token,
   needs to verify that the key used by the client matches the one
   included in the access token.
```

So for your accounts security, you have to follow these rules:
https://tools.ietf.org/html/draft-ietf-oauth-pop-architecture-02#page-10

**Comment by aldkru** [comment]
But why isn't accounts.spotify.com the authorisation server?

**Comment by loretoparisi** [comment]
So, take a look at the following diagram. Here you have all the three actors in the oAuth 2.0 standard flow:

![token introspection and access token handles](https://cloud.githubusercontent.com/assets/163333/10118713/9f900b68-647f-11e5-86b1-966407bf0222.jpg)

-  The ```Client``` requesting the Access token. This is the app client.
- The ```Authorization Server```. This is the middleware that where the client sends authentication requests to be granted. This is the endpoint ```accounts.spotify.com``` in fact.
- The ```Resource Server```.  This is the API server, where the Client's ```User``` resources are hosted. In this case ```api.spotify.com``` or some server that wraps the api endpoint.

So your app will swap the ```Authorization Code``` for an ```Access token``` by sending a HTTP POST request to the ```Authorization Server``` with the client_id, client_secret, redirect_uri and grant_type=authorization_code to the ```api/token``` endpoint, like in this Node.js server:

```javascript
spotifyAPI.createRequest("https://accounts.spotify.com/");

var authHeader = 'Basic ' + new Buffer(sp_id + ':' + sp_secret).toString('base64');
var headers = {
    'Authorization': authHeader,
    "Content-Type": "application/x-www-form-urlencoded"
}

spotifyAPI.setHeaders(headers);
spotifyAPI.postP("api/token",{}, qs.stringify({
        grant_type: "authorization_code",
        client_id: sp_id,
        client_secret: sp_secret,
        redirect_uri: sp_callback,
        code: code
    }))
    .then(function(err_or_res) {
        if (err_or_res['error'] != null) {
            response.write(JSON.stringify(err_or_res));
            response.end();
        } else {
            refresh_token = err_or_res['refresh_token'];
            encrypted_token = encrypt(refresh_token,pass);
            err_or_res['refresh_token'] = encrypted_token;
            refresh_token = encrypted_token;
            response.write(JSON.stringify(err_or_res));
            response.end();
        }
    });
```

In this phase you will get the ```refresh_token``` and you have to ```encrypt``` it. Encryption of the refresh token on your server is the key point. From now on, your server is the only one that can encrypt/decrypt the refresh token.
In fact, when you need to refresh your access token, you will send back the encrypted access token to your server, that will ```decrypt``` it, and send a refresh request to the ```Authorization Server```:

```javascript
var refresh_token = decrypt(encrypted_token,pass);
spotifyAPI.createRequest('https://accounts.spotify.com/');
var authHeader = 'Basic ' + new Buffer(sp_id + ':' + sp_secret).toString('base64');
var headers = {
    'Authorization': authHeader,
    "Content-Type": "application/x-www-form-urlencoded"
}

spotifyAPI.setHeaders(headers);
spotifyAPI.post("api/token",{}, qs.stringify({
        grant_type: "refresh_token",
        client_id: sp_id,
        client_secret: sp_secret,
        refresh_token: refresh_token
    }))
    .then(function(err_or_res) {
        response.write(JSON.stringify(err_or_res));
        response.end();
    });

} else {
    response.sendErrorPacket(500, "");
}
```

The ```Authorization Server``` will send you a refreshed ```access token``` then. Between the ```Client``` app and the ```Authorization Server``` no secure information are traveling. All the communication happen between your server and the ```Authorization Server```.

**Comment by aldkru** [comment]
It's not very clear from this description exactly what the app and server do. For example you say that the app sends the request to exchange the code for an access token but then mysteriously it's the server that encrypts the refresh token. I think you must mean that the app gets the auth code directly from the auth server and sends this to the app server which exchanges it for the access and refresh tokens. Any other way leaves gaping holes. Still what do you think is achieved by encrypting the refresh token? If I can steal a plaintext token I can just as easily steal an encrypted one. If I present the stolen encrypted token to one of these app servers it will be decrypted and used to get a new access token.

**Comment by erdtman** [comment]
You can get an access token (and refresh token) by following this documentation https://developer.spotify.com/web-api/authorization-guide/
But as mentioned by @loretoparisi if you do not have a back end to keep the client secret secure you are breaking the security model of OAuth, at least if you go for the code grant flow.

I will close this issue now since there is not much more we can do.
