### ISSUE TITLE
Cocoa error 3840 on token renew

### ISSUE THREAD

**Issue by GabeJacobs** [spotify/ios-sdk#455]
We currently are having this issue when trying to renew tokens:

<code>*** Error renewing session: Error Domain=NSCocoaErrorDomain Code=3840 "The operation couldn’t be completed. (Cocoa error 3840.)" (JSON text did not start with array or object and option to allow fragments not set.) UserInfo=0x1718778c0 {NSDebugDescription=JSON text did not start with array or object and option to allow fragments not set.</code>

Is the API down?

**Comment by GabeJacobs** [comment]
Is there any kind of state the session could be in to reproduce this error. We think the session was in a bad state of some sort?

**Comment by ramkrishnazingma** [comment]
Which method you have used to renew the session ? As I ma having the same problem but I had solved it using these api "- (instancetype)initWithUserName:(NSString *)userName accessToken:(NSString *)accessToken encryptedRefreshToken:(NSString *)encryptedRefreshToken expirationDate:(NSDate *)expirationDate"

Hope it will work for you.

**Comment by erdtman** [comment]
Sorry for not getting back earlier. In an attempt to get a better overview of the issues we are cleaning out some of the older issues. If this issue is still a problem in the latest SDK please reopen this issue or open a new one.
