### ISSUE TITLE
No registered class for type 'artist'  error

### ISSUE THREAD

**Issue by mashkius** [spotify/ios-sdk#456]
Does anyone knows why I am getting this error while trying to get SPTTrack trackForUrl ?

**Comment by mashkius** [comment]
Error code = 102

**Comment by abrock17** [comment]
I'm seeing the same error.  Did you find a solution?

**Comment by mashkius** [comment]
Yes. I have wrapped it into a framework and didn't include -ObjC flag

**Comment by abrock17** [comment]
Thanks.  Can you give any more detail?  I have not done this before.  You wrapped the entire Spotify.framework in a swift Framework?  How did you go about this?

Thanks again.

**Comment by abrock17** [comment]
What solved it for me:  the -ObjC flag had been dropped at some point from my project - must have happened when upgraded to XCode 7.  I added it back and the SDK works as it did before.
