### ISSUE TITLE
iOS 9 requirements

### ISSUE THREAD

**Issue by ahallora** [spotify/ios-sdk#457]
With iOS 9 Apple is now enforcing an encrypt-all policy requiring all network requests to use the TLS 1.2 protocol among other things. Could you please provide the needed settings for the info.plist in order to make it work under iOS 9, e.g. 

```
<key>LSApplicationQueriesSchemes</key>
<array>
 <string>urlscheme</string>
 <string>urlscheme2</string>
 <string>urlscheme3</string>
 <string>urlscheme4</string>
</array> 
```

and 

```
<key>NSAppTransportSecurity</key>
<dict>
  <key>NSExceptionDomains</key>
  <dict>
    <key>yourserver.com</key>
    <dict>
      <!--Include to allow subdomains-->
      <key>NSIncludesSubdomains</key>
      <true/>
      <!--Include to allow insecure HTTP requests-->
      <key>NSTemporaryExceptionAllowsInsecureHTTPLoads</key>
      <true/>
      <!--Include to specify minimum TLS version-->
      <key>NSTemporaryExceptionMinimumTLSVersion</key>
      <string>TLSv1.1</string>
    </dict>
  </dict>
</dict>
```

See also:
http://stackoverflow.com/questions/30739473/nsurlsession-nsurlconnection-http-load-failed-on-ios-9
https://github.com/ChenYilong/iOS9AdaptationTips

**Comment by bassntweeter** [comment]
Amazon will retire SHA-1 on cloudfront the 30th of September 
https://aws.amazon.com/security/security-bulletins/aws-to-switch-to-sha256-hash-algorithm-for-ssl-certificates/

Up until then you need to add the following to your info.plist
```
<key>NSAppTransportSecurity</key>
<dict>
	<key>NSExceptionDomains</key>
	<dict>
		<key>cloudfront.net</key>
		<dict>
			<key>NSIncludesSubdomains</key>
			<true/>
			<key>NSExceptionRequiresForwardSecrecy</key>
			<false/>
		</dict>
	</dict>
</dict>
```

**Comment by bassntweeter** [comment]
The LSApplicationQueriesSchemes key is not needed since Beta 10 do not support Spotify App Authentication.
