### ISSUE TITLE
Why the "ios-streaming-sdk" needs to be updated

### ISSUE THREAD

**Issue by Anders27** [spotify/ios-sdk#46]
I post this on both the "spotify/ios-sdk" and "spotify/ios-streaming-sdk" issues list so nobody misses to read it ;-)

I was delighted to see that the iOS Streaming SDK finally was updated but soon found out that the only thing fixed was related to the upcoming changes to playlist URIs as explained here: 
https://developer.spotify.com/community/news/2018/06/12/changes-to-playlist-uris/
Thanks for that but I guess most of us including me, already fixed that ourself since the "SpotifyMetadata.framework" is now open source.

Spotify then writes here:
https://developer.spotify.com/community/news/2018/09/14/updates-mobile-platform/

"The documentation and download for the streaming SDKs from 2014 are available on GitHub here for iOS and here for Android. 
Note that these streaming SDKs are not actively maintained and no additional work on these are planned. 
We therefore urge you to work with the new SDKs going forward."

The new SDK can in no way replace the streaming SDK.

As stated here by one member of the Spotify team (jackfreeman)
https://github.com/spotify/ios-sdk/issues/12

snip...
"Additionally, since the Spotify app controls the audio, you will be more limited in working with the audio signal at a low level."

So for apps that needs access to the raw audio then the new SDK is useless.

Why not a least fix the very few bugs the streaming SDK contains?

In my particular case there is only one bug that affects my app, everything else works perfect.
Bug ID #858 "seekTo method is extremely slow when file caching is enabled".

There might be other bugs that affect other users but in my opinion, the streaming SDK works quite good and needs very little additional work to be perfect.

Or do as with the "SpotifyMetadata.framework" and release it as open source, then we app developers can fix the bugs and Spotify can totally forget SDK.

With the audio streaming SDK, Spotify has something that no other audio streaming companies can offer, including its biggest rival, Apple.

I don't know how many customers have been contacting me, telling me that they have now changed from using Apple Music into Spotify, and because of that, they can now work on the music they want in a way that is only possible because my app is using the features that the Spotify Streaming SDK offers.

In my opinion, the Spotify Streaming SDK is one vital cornerstone for the continuing success for Spotify. As Swedes say - "många bäckar små...".

**Comment by jackfreeman** [comment]
Closing this as it is not relevant to this SDK.

**Comment by kbirch** [comment]
Understand the 'not relevant' position, but there are valid concerns raised here and it would be super helpful to know if the long-term road map for this particular SDK includes some of the valuable functionality that is currently missing here but exists in older SDKs.  We're hopeful this new SDK is going to see some quick iterations to fill those gaps, but if that's not happening we may have to look at the older SDKs.

Is there any opportunity to see what features are coming and when in this SDK, or to know more definitely if Spotify is potentially limiting what external apps can do moving forward (now that they are 'urging' everyone over to this new more limited SDK option)?

**Comment by jackfreeman** [comment]
@kbirch There is no plan to have feature parity with this SDK and the old streaming one. As mentioned the streaming SDK is not being maintained or updated and has never left the beta stage, meaning use at your own risk. 

Some integrations may not be suitable for this new SDK (if they need low level audio access for example), but most integrations can achieve the desired result with this SDK and the Web API. This SDK and the Web API are the official and recommended way to integrate with Spotify on iOS. 

While we can't say exactly what's planned for future features, if there is a feature you need, feel free to open an issue with your suggestion and we will consider it for the roadmap.

**Comment by kbirch** [comment]
Okay, fair enough - thanks for the response @jackfreeman, appreciate you taking the time.  We've had reasonable success with this new SDK, there are just a few key things (i.e. continuing to communicate with and manipulate the app remote while our app is in the background) that are more easily handled with direct control and access to the streams rather than app-to-app type of architectures.  But, we will continue on that path and raise suggestions as appropriate.  Thanks again.
