### ISSUE TITLE
White login screen problem

### ISSUE THREAD

**Issue by Kileev** [spotify/ios-sdk#460]
I am trying to login but have a white screen only. What is the problem? 

![img_0103](https://cloud.githubusercontent.com/assets/7849766/10130374/d1f306ee-65d0-11e5-8a18-570fdc6cf217.PNG)

iPhone 5 (iOS 9). iOS SDK Beta 10.

**Comment by Kileev** [comment]
Found solution: http://stackoverflow.com/questions/30739473/nsurlsession-nsurlconnection-http-load-failed-on-ios-9

**Comment by lawrencek7** [comment]
If you would like to handle the specific domain, please add the following to your info.plist:
    <key>NSAppTransportSecurity</key>
    <dict>
        <key>NSExceptionDomains</key>
        <dict>
            <key>cloudfront.net</key>
            <dict>
                <key>NSIncludesSubdomains</key>
                <true/>
                <key>NSThirdPartyExceptionAllowsInsecureHTTPLoads</key>
                <true/>
            </dict>
        </dict>
    </dict>
