### ISSUE TITLE
Low bitrate on beta-10

### ISSUE THREAD

**Issue by GabeJacobs** [spotify/ios-sdk#461]
We upgraded to beta-10 and have noticed songs streaming at the 96 kbit/s quality even though the target bitrate is set to High. This did not used to happen. When we quit our app and re-open, it goes back to a high bitrate.

Is there way to set a minimum bitrate so that 96 kbit/s never happens? Or if it does, it checks to make sure it cannot stream better?

**Comment by GabeJacobs** [comment]
We are also experiencing this. Every once in a while there is terrible bitrate. When you quit our app and reopen, it is fine

**Comment by 909kishore** [comment]
+1

**Comment by GabeJacobs** [comment]
Still experiencing on Beta 12

**Comment by erdtman** [comment]
Sorry for not getting back earlier. In an attempt to get a better overview of the issues we are cleaning out some of the older issues. If this issue is still a problem in the latest SDK please reopen this issue or open a new one.
