### ISSUE TITLE
Crash (SpTrackListGetStatus)

### ISSUE THREAD

**Issue by ruslansokolov-cc** [spotify/ios-sdk#462]
sp_d068369db80442e9a6c1c4357d8304be + 2308580
sp_d068369db80442e9a6c1c4357d8304be + 2308576
sp_b7041fa3c7e84df49398ec93c231aa47 + 2310492
sp_d37d168c10b348908bbc1e281e975d65 + 2332468
sp_202819c8dbd84ee1a341f54ae732ab48 + 2363608
SpTrackListGetStatus + 2351024
SPTAudioStreamingController.m line 867
-[SPTAudioStreamingController trackListSize]
-[CCSpotifyMediaPlayer playNextTrack] + 3211852
-[JDCMediaViewController nextTapped] + 2940640
UIKit -[UIApplication sendAction:to:from:forEvent:] + 96
UIKit -[UIControl _sendActionsForEvents:withEvent:] + 612

**Comment by mashkius** [comment]
Is SpTrackListGetStatus your own method or is it from the old SDK?

**Comment by ruslansokolov-cc** [comment]
That's not our method. Should we update the SDK?

**Comment by mashkius** [comment]
You probably should as I worked only with beta10 and this looks like old SDK method.

**Comment by ruslansokolov-cc** [comment]
I've checked and it looks like we are using beta 10.

**Comment by erdtman** [comment]
Sorry for not getting back earlier. In an attempt to get a better overview of the issues we are cleaning out some of the older issues. If this issue is still a problem in the latest SDK please reopen this issue or open a new one.
