### ISSUE TITLE
App Store Rejection for using SPTAuthViewController

### ISSUE THREAD

**Issue by nickgarfield** [spotify/ios-sdk#463]
My application was just rejected by Apple for the following reason:

" 11.13 - Apps that link to external mechanisms for purchases or subscriptions to be used in the App, such as a "buy" button that goes to a web site to purchase a digital book, will be rejected

We noticed that your app provides access to external mechanisms for purchases or subscriptions to be used in the app, which does not comply with the App Store Review Guidelines.

We’ve attached screenshot(s) for your reference."

They provided screenshots of the following screens:

![1](https://cloud.githubusercontent.com/assets/8634334/10181841/b297a38c-66e2-11e5-9e9f-972052ea4969.png)
![2](https://cloud.githubusercontent.com/assets/8634334/10181843/b2a82a2c-66e2-11e5-9c8d-7e4c03f98144.png)
![3](https://cloud.githubusercontent.com/assets/8634334/10181842/b2a6806e-66e2-11e5-9fb4-01fb3ccf4abf.png)

I'm using the latest Spotify build and using the SPTAuthViewController to let the user log in. I've investigated Apple's claims and noticed that the user is taken out of the app and to spotify.com in Safari if they tap the "Forgot my password" button. From here, the user can tap the Spotify header at the top of the page to reach the Spotify homepage (which is apparently upsetting to Apple). 

Should I dispute Apple's claims or will there soon be a Spotify update that doesn't kick the user out of the app and into Safari when they tap the "Forgot my password" button? Could anyone point me to some examples of apps in the App Store that use the SPTAuthViewController login view so I could dispute Apple's rejection?

**Comment by darianovodon** [comment]
Had app rejected from app store for the same reason

>11.13 Details
>We  noticed that your app provides access to external mechanisms for purchases or subscriptions to be used in the app, which does not comply with the App Store Review Guidelines. 

>Specifically, we noticed that your app provides access to Spotify.

Can this be disputed? There surely are other apps in the app store that use spotify.

**Comment by nickgarfield** [comment]
I mentioned in our appeal that other really popular apps such as RunKeeper, Shazam, and PaceMaker (which won a 2015 Apple Design Award) also have the same issue, but Apple basically said they didn't care and upheld the rejection.

**Comment by bassntweeter** [comment]
This issue has been addressed in the Beta 11 released today.
