### ISSUE TITLE
Login Issue with iOS 9.0.2

### ISSUE THREAD

**Issue by adamzairia** [spotify/ios-sdk#465]
My app is using Spotify iOS-SDK 8. The app was worked well until iOS 8. but The login screen does not appear in iOS 9. 

I have reviewed on iPad running iOS 9.0.2 iPhone running iOS 9.0.2 on both Wi-Fi and cellular networks.

Specifically, your Spotify login is not loading. Please see attached screens
![temp puplvhzk](https://cloud.githubusercontent.com/assets/13445779/10212442/ff8c207a-6807-11e5-86bb-ef9a2196e46e.png)
hot(s) for reference.

**Comment by bassntweeter** [comment]
Hi, please add the following to your info.plist
```
	<key>NSAppTransportSecurity</key>
	<dict>
		<key>NSExceptionDomains</key>
		<dict>
			<key>cloudfront.net</key>
			<dict>
				<key>NSIncludesSubdomains</key>
				<true/>
				<key>NSThirdPartyExceptionAllowsInsecureHTTPLoads</key>
				<true/>
			</dict>
		</dict>
	</dict>
```
