### ISSUE TITLE
SPTAudioStreamingController replaceURIs causes crash when current list of tracks is empty.

### ISSUE THREAD

**Issue by dtrenz** [spotify/ios-sdk#466]
It would be nice if `replaceURIs:withCurrentTrackcallback:` would simply add URIs instead of crashing.

This wouldn't be that bad of an issue if there was a way to detect if the track list is empty, so I could do something like:

```swift
if (audioStreamingController.queueSize == 0) {
  audioStreamingController.playURIs(trackURIs, fromIndex: 0, callback: nil)
} else {
  audioStreamingController.replaceURIs(trackURIs, withCurrentTrack: 0, callback: nil)
}
```

Unfortunately, `queueSize` is deprecated and doesn't work with the new "track list."

Is there another way to detect if the track list is empty or not?

**Comment by CVertex** [comment]
Amen

**Comment by mashkius** [comment]
There is a property audioStreamingController.currentTrackIndex, which returns the currently playing track index in the queue. You could work around with this one. Not as useful as queueSize would be, but definitely an option.

What I have done, was save the queue somewhere in array and play it. When SPTAudioStreamingController delegate fires the didStopPlayingTrack method, I remove played track from the queue.
In this kind of fashion I can always replace any track in the queue and play it from whichever index I want to.

**Comment by erdtman** [comment]
Sorry for not getting back earlier. In an attempt to get a better overview of the issues we are cleaning out some of the older issues. If this issue is still a problem in the latest SDK please reopen this issue or open a new one.

replaceURIs has been removed
