### ISSUE TITLE
-skipPrevious: not working

### ISSUE THREAD

**Issue by sgoodwin** [spotify/ios-sdk#468]
In my app I queue up about 30 tracks and then skip ahead to the 5th one or so. When I try to go backwards to one of the previous songs, the player simply pauses instead. It reports no errors either. 

Is this a bug and can it get fixed soon please?

**Comment by CVertex** [comment]
I see the same problem!

**Comment by TokyoBirdy** [comment]
@sgoodwin Hi, I am wondering how you queue up the tracks ?

**Comment by sgoodwin** [comment]
I use the -queueURIs:clearQueue:callback: method on the SPTAudioStreamingController.

**Comment by TokyoBirdy** [comment]
So try to use this one instead
```
 -(void)replaceURIs:(NSArray *)uris withCurrentTrack:(int)index callback:(SPTErrorableOperationCallback)block;

````
We will deprecate the function 

````
 -queueURIs:clearQueue:callback:
````

**Comment by sgoodwin** [comment]
replaceURI's does result in music playing, but skipPrevious still doesn't work even when I use that

**Comment by JMSerruya** [comment]
Thanks for reporting!, will take a look into this and come back at you!

**Comment by erdtman** [comment]
Sorry for not getting back earlier. In an attempt to get a better overview of the issues we are cleaning out some of the older issues. If this issue is still a problem in the latest SDK please reopen this issue or open a new one.
