### ISSUE TITLE
Crashing on SPTPlaylistSnapshot fetch randomly

### ISSUE THREAD

**Issue by kcfin** [spotify/ios-sdk#469]
I've been getting a strange error where I'm fetching all of a user's playlists and getting the SPTPlaylistSnapshot for each - the SPTPlaylistSnapshot will occasionally return a fatal error when I try to retrieve any information about it.  This doesn't always happen - it seems completely random.  Certain times it fetches all of the playlists without any issues.  The fatal error states "fatal error: unexpectedly found nil while unwrapping an Optional value". As far as I can see, I'm checking all of my values before unwrapping.

```   
    func fetchSnapshotPlaylist(withSession session: SPTSession, withCallback callback: (SPTPlaylistSnapshot, Bool) -> Void) {
        fetchParsingPlaylists(withSession: session, withCallback: { (playlistList) -> Void in
            var index = 0;
            var shouldSave = false;
            
            
            
            for partialPlaylist in playlistList {
                SPTPlaylistSnapshot.playlistWithURI(partialPlaylist.uri, accessToken: session.accessToken, callback: {(error, object) -> Void in
                    if(error != nil) {
                        print("error: \(error.localizedDescription)");
                        return;
                    }
                    if let snapshot = object as? SPTPlaylistSnapshot {
                        index++;
                        if(index == playlistList.count) {
                            print(playlistList.count)
                            shouldSave = true;
                        }
                        callback(snapshot, shouldSave);
                    }
                })
            }
        })
    }
```

I get the crash when I try to retrieve the playlist's name

<img width="571" alt="screen shot 2015-10-07 at 4 18 49 pm" src="https://cloud.githubusercontent.com/assets/6119557/10353993/394fbfd0-6d10-11e5-98b5-1f3caab93cc8.png">

if I check with

`if let name = playlist.name`

first, it seems to only return to me about 1/3 of the users playlists.

Forgive me if the answer if obvious - I'm somewhat new at this.  But I've been looking into the issue for a while now and I can't seem to figure out the answer by myself.

Thanks!

**Comment by erdtman** [comment]
Sorry for not getting back earlier. In an attempt to get a better overview of the issues we are cleaning out some of the older issues. If this issue is still a problem in the latest SDK please reopen this issue or open a new one.
