### ISSUE TITLE
Apps built with Xcode 7.0.1 can't login to Spotify

### ISSUE THREAD

**Issue by 909kishore** [spotify/ios-sdk#471]
When the Spotify login dialog appears, it is blank.  This has been happening for several days.  Please help.

Even the Spotify sample project doesn't work:

<img width="818" alt="screenshot 2015-10-10 22 07 21" src="https://cloud.githubusercontent.com/assets/6827699/10414304/9430c18c-6f9b-11e5-9bea-ade0c07a0441.png">

**Comment by lawrencek7** [comment]
Please add the following to your info.plist:
```
    <key>NSAppTransportSecurity</key>
    <dict>
        <key>NSExceptionDomains</key>
        <dict>
            <key>cloudfront.net</key>
            <dict>
                <key>NSIncludesSubdomains</key>
                <true/>
                <key>NSThirdPartyExceptionAllowsInsecureHTTPLoads</key>
                <true/>
            </dict>
        </dict>
    </dict>
```

**Comment by 909kishore** [comment]
works.  thank you!  I assume this will be integrated in next sdk update?

**Comment by lawrencek7** [comment]
We actually expect Amazon (cloudfront.net domain) to fix this soon and then you would be able to remove this exception.

**Comment by hauran** [comment]
seems like we also had to whitelist facebook.com for facebook auth?

**Comment by 909kishore** [comment]
Even when we whitelist Facebook.com and all its subdomains, the CSS doesn't load consistently (see attached image).  

![ack css doesn t load consistently png](https://cloud.githubusercontent.com/assets/6827699/10436765/7415a9b0-70f6-11e5-854e-47521bb6feaf.jpeg)


1) How can we get the spotify idk working properly in Xcode 7.0.1?  Do we have to whitelist all servers where Facebook gets their CSS code too?  If so, what are all those servers?

2) I have seen an app where it flipped to the Spotify app when it required authorization, removing the need for the user to enter their password if they have Spotify installed.  I think it was an old version of Nusiki.  This would eliminate this issue and make logging in to Spotify apps immensely easier for users and developers.  When can we expect that feature to be included in the sdk?

**Comment by bassntweeter** [comment]
@909kishore for the second question that will happen in a couple of weeks.

**Comment by matijse** [comment]
For reference, these are the settings provided by Facebook for iOS 9: 

```
<key>NSAppTransportSecurity</key>
<dict>
  <key>NSExceptionDomains</key>
  <dict>
    <key>facebook.com</key>
    <dict>
      <key>NSIncludesSubdomains</key> <true/>        
      <key>NSThirdPartyExceptionRequiresForwardSecrecy</key> <false/>
    </dict>
    <key>fbcdn.net</key>
    <dict>
      <key>NSIncludesSubdomains</key> <true/>
      <key>NSThirdPartyExceptionRequiresForwardSecrecy</key>  <false/>
    </dict>
    <key>akamaihd.net</key>
    <dict>
      <key>NSIncludesSubdomains</key> <true/>
      <key>NSThirdPartyExceptionRequiresForwardSecrecy</key> <false/>
    </dict>
  </dict>
</dict>
```
Source: https://developers.facebook.com/docs/ios/getting-started

**Comment by 909kishore** [comment]
Thank you!

**Comment by 909kishore** [comment]
@bassntweeter any updates on in-app authentication? Thx!
