### ISSUE TITLE
Hundreds of Warnings?

### ISSUE THREAD

**Issue by nickgarfield** [spotify/ios-sdk#472]
Is it just me or do other people see like ~200 warnings when compiling with the latest build (11). A lot of the warnings refer to files not being found such as:

```warning: /var/folders/3s/q_gk9q0s0zn88yx8djd0fq8h0000gn/C/org.llvm.clang.fredrikschmidt/ModuleCache/1A91LOYA1JIGB/Foundation-A3SOD99KJ0S9.pcm: No such file or directory```

and also resolving external types:

```warning: Could not resolve external type c:objc(cs)NSObject```

**Comment by soundspectrum** [comment]
Yeah, we're getting that too ugh.

**Comment by nickgarfield** [comment]
Yeah, I haven't been able to upload the App Store. The binary keeps hanging in the "processing" phase in iTunesConnect. I can't tell if this is my fault or due in part to these warnings.

**Comment by Brad-Jackson** [comment]
I'm having the same problem.

**Comment by loretoparisi** [comment]
This happened to me when I wrote a audio processing callback that was saving the pcm file without setting up the flags to skip backup ```NSURLIsExcludedFromBackupKey```. Now, the file ```/var/folders/3s/q_gk9q0s0zn88yx8djd0fq8h0000gn/C/org.llvm.clang.fredrikschmidt/ModuleCache/1A91LOYA1JIGB/Foundation-A3SOD99KJ0S9.pcm``` is clearly a raw wav audio file from a cached file.

This could happen if some url path has not safely set the key ```NSURLIsExcludedFromBackupKey```

```Objective-C
- (BOOL)addSkipBackupAttributeToItemAtURL:(NSURL *)URL
{
    
    NSError *error = nil;
    BOOL success = [URL setResourceValue: [NSNumber numberWithBool: YES]
                                  forKey: NSURLIsExcludedFromBackupKey error: &error];
    
    if(!success){
        NSLog(@"Error excluding %@ from backup %@", [URL lastPathComponent], error);
    }
    
    return success;
}
```

that is

```Objective-C
FOUNDATION_EXPORT NSString * const NSURLIsExcludedFromBackupKey        NS_AVAILABLE(10_8, 5_1); 
// true if resource should be excluded from backups, false otherwise (Read-write, value type boolean NSNumber). This property is only useful for excluding cache and other application support files which are not needed in a backup. Some operations commonly made to user documents will cause this property to be reset to false and so this property should not be used on user documents.
```

**Comment by Brad-Jackson** [comment]
So how / where do you use this function?

**Comment by loretoparisi** [comment]
unfortunately we cannot use this, my guess is if this is for some reasons not used in the sdk :(

**Comment by bassntweeter** [comment]
We are currently working on solving this. The shift to Xcode 7 made the warnings appear. Thanks for your patience.

**Comment by loretoparisi** [comment]
@bassntweeter thank you! I correct myself, about those files (.pcm). These are ```ModuleCache``` from ```DerivedData``` files  like (from strings of a .o file)

```
SPTPartialAlbum
SPTJSONObjectBase
c:objc(cs)NSObject
/var/folders/3s/q_gk9q0s0zn88yx8djd0fq8h0000gn/C/org.llvm.clang.fredrikschmidt/ModuleCache/2B8RA361E6MY7/ObjectiveC-2CD0WTQVXITO7.pcm
decodedJSONObject
objc_object
objc_class
identifier
```

etc (See here: http://stackoverflow.com/questions/18547895/cant-get-rid-of-apple-llvm-5-0-error )

**Comment by bassntweeter** [comment]
This has been addressed in Beta 12.

**Comment by Muesly** [comment]
I'm still finding this with the latest beta 14 including warning like:

while processing /Users/tony/Code/Lost/iphone-client/MusicServicePlaylist.framework/MusicServicePlaylist(SPTOldConnectButton.o):
warning: /Users/juanma/Library/Developer/Xcode/DerivedData/ModuleCache/32EK2W4UJQOJQ/QuartzCore-3BTB4W6DBDTKJ.pcm: No such file or directory

**Comment by JMSerruya** [comment]
@Muesly Thanks for reporting, i'll fix this and include the fix in the next release!

**Comment by ablinov** [comment]
@JMSerruya Any word on when the next release will be?
