### ISSUE TITLE
Problem with playURIs:fromIndex:callback:

### ISSUE THREAD

**Issue by Ouatelse** [spotify/ios-sdk#475]
Hi,

I encounter a problem with the method "playURIs:fromIndex:callback:".

If i tried to play an URI that fail with a SPTAudioStreamingController, the callback is never called.
It's called only if it succeed.

I am logged in with a premium account on iPhone iOS 8.4.

Thank you.

John

**Comment by erdtman** [comment]
playURIs has been removed try the latest beta
