### ISSUE TITLE
Synchronize music play on multiple devices

### ISSUE THREAD

**Issue by adamzairia** [spotify/ios-sdk#477]
Is there a good method to sync music play on multiple devices (iPhone, Android)?

I'm using Parse as backend service. and When the Admin is started playing Spotify track on his phone, this song should play on other user's mobile devices at the same time. 

When the song is started playing, i'm uploading the song index & track URI to Parse server, and other phones are retrieving the updated parse data by using 5 sec NSTimer. 

The problem is only synchronization on multiple devices... Please let me know Spotify SDK delegate method or other way. 

Thank you!!

**Comment by erdtman** [comment]
This is out side the scope of the Spotify SDKs, sorry for not being of more help.
