### ISSUE TITLE
SPTSearch - performSearchWithQuery offset is broken

### ISSUE THREAD

**Issue by lamxing** [spotify/ios-sdk#478]
Calling [SPTSearch performSearchWithQuery:encodedString queryType:SPTQueryTypeTrack offset:offSetNumber accessToken:nil callback:^(NSError *error, id object) {}] always returns the first page result, regardless what number is passed into the "offset" parameter.  The returned SPTListPage object has over 1000 results, and the next page URL is given, so it must have more than 1 page of result.  Hitting the next page URL directly on browser shows the correct results (skipped the correct number of records).

Example:
* [SPTSearch performSearchWithQuery:@"michael+jackson" queryType:SPTQueryTypeTrack offset:0 
accessToken:nil callback:^(NSError *error, id object) {}]
* [SPTSearch performSearchWithQuery:@"michael+jackson" queryType:SPTQueryTypeTrack offset:20 accessToken:nil callback:^(NSError *error, id object) {}]
* [SPTSearch performSearchWithQuery:@"michael+jackson" queryType:SPTQueryTypeTrack offset:40 accessToken:nil callback:^(NSError *error, id object) {}]

All of the above call returns the same set of results.

**Comment by loretoparisi** [comment]
@lamxing a temporary solution can be to retrieve the whole results, and paginate them later. Take a look at 

```
/**
 * Search Spotify Track
 */
-(void)searchSpotifyTrackWithQuery:(NSString *)searchQuery
                       accessToken:(NSString*)accessToken
                        completion:(void (^)(id results, NSError* error))completion;
```

in this example project here https://github.com/loretoparisi/spotify-tvos-app-example/blob/master/spotify-tvos-framework-example/Classes/SpotifyHelper.h

**Comment by DmytroAnkudinov** [comment]
Fixed in Beta25.
