### ISSUE TITLE
Beta 12 still has Wifi Handoff issues

### ISSUE THREAD

**Issue by GabeJacobs** [spotify/ios-sdk#479]
I've been testing Beta 12 and I still get a playback issue when switching from Wifi to LTE

Every time I walk away from WIFI the music stops playing.

**Comment by zakmandhro** [comment]
+1 confirming that this issue is not resolved in Beta 12.

**Comment by JMSerruya** [comment]
duplicated from https://github.com/spotify/ios-sdk/issues/409

**Comment by JMSerruya** [comment]
Please retest with beta-14

https://github.com/spotify/ios-sdk/releases/tag/beta-14

**Comment by GabeJacobs** [comment]
This should be reopened, bug still exists in beta 16
