### ISSUE TITLE
Spotify offline mode

### ISSUE THREAD

**Issue by zhangyicococo** [spotify/ios-sdk#480]
Is it possible to download music on app's cache directory using iOS SDK like Spotify OSX app does?
So I wanted to download first and play local stored file when phone's network connection is lost.

Thank you.

**Comment by bassntweeter** [comment]
Unfortunately not.

**Comment by zhangyicococo** [comment]
Ok thanks.

**Comment by arthurnn** [comment]
Is there any work around this? 
Is this every going to be available in the SDK?
