### ISSUE TITLE
SPTListPage requestNextPageWithSession:callback: is failing

### ISSUE THREAD

**Issue by ddramowicz** [spotify/ios-sdk#481]
Hi - I'm having problems with SPTListPage `– requestNextPageWithSession:callback:` while fetching pages from a user's library.

I am able to fetch several pages (a different amount each time), but eventually it fails. I do not receive an error in the callback but instead the final SPTListPage object I receive looks something like this:

` "<SPTListPage: 0x1407d1d70>: 0-18446744073709551615 of 0 items"`, its nextPage value is NO, its isComplete value is YES, and its totalListLength value is 0. All previous, successfully fetched SPTListPage objects have a nextPage value of YES, an isComplete value of NO, and a totalListLength value of 3190.

This has rendered it impossible for me to successfully scan a users' library. Any help would be appreciated. I am using the latest version of the SDK. Thanks.

**Comment by bassntweeter** [comment]
Hi, please try to make your request directly against the WebAPI (https://developer.spotify.com/web-api/user-guide/) and see if that works.

**Comment by ddramowicz** [comment]
Hi there, I tested against the WebAPI and it works, however that is not really the point as I would prefer to use the SDK. I don't really see how this issue can be closed if this is a valid issue with the SDK...? Thanks.

**Comment by bimusiek** [comment]
Hey, we have exactly the same problem. WebAPI works properly but SPTListPage from time to time returns 0 items... 

Is there any know workaround?

**Comment by bimusiek** [comment]
So, I investigated more using WebApi that was also failing from time to time, but... here at least I was getting 502 error. 
With your SDK, there is no error, just empty list. 
I would consider this a bug as we should get in callback some `NSError`.

I have written SpotifyAPI helper if someone wants to use it, feel free :)
https://gist.github.com/bimusiek/7697ba2bccb53ccb2608
