### ISSUE TITLE
ld warning: was built for newer iOS version (7.1) than being linked (7.0)

### ISSUE THREAD

**Issue by Anders27** [spotify/ios-sdk#482]
My app still supports iOS 6 and thus I have the deployment target set to iOS 6.

This generates a lot of warnings as the one below:

ld: warning: object file (/Volumes/Macintosh HD/programming/programming/iPhone/spotify-ios-sdk/Spotify.framework/Spotify(ads.c.o)) was built for newer iOS version (7.1) than being linked (7.0)

Is there a way around this except building for iOS 7.1 and later?

Thanks,
Andy

**Comment by erdtman** [comment]
current release is built for iOS 7.0 we will not work with older versions.
