### ISSUE TITLE
currentPlaybackPosition always returns 0.

### ISSUE THREAD

**Issue by jhrasco** [spotify/ios-sdk#483]
I'm logging the currentPlaybackPosition with the below code snippets but the output is always 0. I'm using Beta 12.

- (void)coreAudioController:(SPTCoreAudioController *)controller didOutputAudioOfDuration:(NSTimeInterval)audioDuration {
    NSLog(@"%f - %f", self.player.currentPlaybackPosition, self.player.currentTrackDuration);
}

Output: 0.000000 - 188.653000

**Comment by iGGNoRe** [comment]
It seems to depend on how it is being used. Placing it using a `NSLog` line connected to pressing the play button prints the correct results for me, while placing it in a `while(true)` loop after a song starts resulted in it printing solid 0s, I'm assuming because that prevents anything else from being updated. Using the Demo Project and adding this to the `viewDidAppear` function gave me the correct results.

    dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0), ^{
        
            while (true) {
                sleep(2);
            
                dispatch_async(dispatch_get_main_queue(), ^{
                    NSLog(@"%f", self.player.currentPlaybackPosition);
                });
            }
        
        
        });

resulted in: 

    2015-11-16 00:51:22.245 Simple Track Playback[53956:1981031] track changed = spotify:track:1mnqraQ8oV8MX92rdOFLWW
    2015-11-16 00:51:22.247 Simple Track Playback[53956:1981031] is playing = 1
    2015-11-16 00:51:23.531 Simple Track Playback[53956:1981031] 1.033000
    2015-11-16 00:51:25.532 Simple Track Playback[53956:1981031] 2.913000
    2015-11-16 00:51:27.537 Simple Track Playback[53956:1981031] 5.026000
    2015-11-16 00:51:29.537 Simple Track Playback[53956:1981031] 6.907000
    2015-11-16 00:51:31.542 Simple Track Playback[53956:1981031] 8.974000
    2015-11-16 00:51:33.543 Simple Track Playback[53956:1981031] 10.855000
    2015-11-16 00:51:35.548 Simple Track Playback[53956:1981031] 12.968000
    2015-11-16 00:51:37.548 Simple Track Playback[53956:1981031] 15.034000


So I'm thinking it has to do with how rapidly the function you are trying to use it in is called? Also it looks like the `audioDuration` parameter should actually be the value you want, try printing that out and see what it results in because after reading the documentation it looks like that could be exactly what you are trying to get anyways.

**Comment by jhrasco** [comment]
Hi @iGGNoRe,

Thanks for a quick response. I just tried the code snippets you made but I'm still getting a 0 on currentPlaybackPosition. I also tried placing a log statement that print currentPlaybackPosition in pause/play action but still gave me a 0 value. Are you sure you're using the latest SDK?

**Comment by jhrasco** [comment]
Hi @iGGNoRe,

I know now what causing the issue. If I initialize the player like
self.player = [[SPTAudioStreamingController alloc] initWithClientId:auth.clientID],
it gives me the correct output of currentPlaybackPosition. However, if I initialize the player like
self.player = [[SPTAudioStreamingController alloc] initWithClientId:auth.clientID audioController:self.audioController],
it gives me a value of 0 for currentPlaybackPosition.

Is this an expected behaviour of the player if audioController parameter is not nil?
What I want to do is to notify me everytime the currentPlaybackPosition changes. Is there a better way to implement it?

**Comment by iGGNoRe** [comment]
@jhrasco That's what that `– coreAudioController:didOutputAudioOfDuration: ` is for, it's for updating progress bars, getting the time that has played so far, etc, which it sounds like you're wanting to do. You link it to the controller like you had done before and the parameter  `didOutputAudioOfDuration:(NSTimeInterval)audioDuration` in that function should contain exactly what you are looking for without even needing to call the `self.player.currentPlaybackPosition`.

**Comment by jhrasco** [comment]
@iGGNoRe, I tried to print the audioDuration but its value does not change. It outputs the same value everytime the didOutputAdioOfDuration method is called. Could you please verify on your end? I will really appreciate it. Thanks.

 By the way, as a temporary solution, I used KVO to observe the current playback position.

**Comment by iGGNoRe** [comment]
@jhrasco I figured it out! `– coreAudioController:didOutputAudioOfDuration:` is literally only returning what it JUST sent as output. If you initialize a variable and add the audioDuration to it on every call it produces the correct result.

    -(void)coreAudioController:(SPTCoreAudioController *)controller didOutputAudioOfDuration:(NSTimeInterval)audioDuration
    {
        self.time = self.time + audioDuration;
        NSLog(@"%f", self.time);
    }

**Comment by jhrasco** [comment]
@iGGNoRe, Thanks! Now I know. Great job on figuring it out. I really appreciate your help. Thanks again. :)

**Comment by iGGNoRe** [comment]
@jhrasco No problem, ended up being a learning experience for me as well!
