### ISSUE TITLE
Set a collaborative playlist

### ISSUE THREAD

**Issue by leonandes** [spotify/ios-sdk#484]
Hi, can you help me with a little doubt?
Is it possible to set a playlist as collaborative using only the iOS SDK?
I’m trying to find it in the documentation, but didn’t find any solution.

Hope you can help me

Thanks

**Comment by martinobonfiglioli** [comment]
Add this string to your requested scope permissions: "playlist-read-collaborative"
Isn't documented in the SDK but you can find the complete list from the web api documentation:
https://developer.spotify.com/web-api/using-scopes/

**Comment by erdtman** [comment]
The SDK is dependent on whats available in the web-api (https://developer.spotify.com/web-api/change-playlist-details/), I will close this issue for now if this is added to the web-api you could reopen this issue.

Request the feature form the web-api https://github.com/spotify/web-api
