### ISSUE TITLE
How to clear the queue?

### ISSUE THREAD

**Issue by dtrenz** [spotify/ios-sdk#488]
It appears that all of the methods for clearing the queue have been deprecated. What is the preferred method for clearing an Audios Streaming Controller queue, going forward?

**Comment by dtrenz** [comment]
bump

**Comment by cameronehrlich** [comment]
bump

**Comment by fotiDim** [comment]
With SDK version 20 this is an issue more than ever. You still have the 'queueURI:callback': method but no apparent way to clear the queue. If the queue is something supported by the SDK you need to provide a clear method.

**Comment by CVertex** [comment]
Yes, the latest beta needs this!!!

**Comment by DmytroAnkudinov** [comment]
Team responsible for SDK support does not have plans to provide a functionality to clear the queue, as the layer underlying SDK (and responsible for queueing in particular) will not be extended in that direction. We suggest using Spotify Playlists instead.

**Comment by patrickjquinn** [comment]
Any explanation as to why you decided against the queue being cleared? I'm seeing a lot of developer hostile actions here which, with each release, reduces the ability for developers to build on top of Spotify.
