### ISSUE TITLE
SPTAudioStreamingController loginWithSession error

### ISSUE THREAD

**Issue by pir800** [spotify/ios-sdk#490]
I am attempting to stream a track using the example posted, but I am getting an error attempting to login with session. My code is as basic as it gets. The session is valid before I attempt to login. I also needed to comment out the localizedDescription for the response error because apparently it's sending back an SPError object instead of a regular NSError and this is causing a crash.

The output I receive every time is "error login"

```
self.streamingPlayer = [[SPTAudioStreamingController alloc] initWithClientId:kSpotifyClientId];
    [self.streamingPlayer loginWithSession:[SPTAuth defaultInstance].session callback:^(NSError *error) {
        if (error != nil) {
            //NSLog(@"*** Logging in got error: %@", error.localizedDescription);
            NSLog(@"error login");
            return;
        }
        
        NSLog(@"player logged in");
        NSURL *trackURI = [NSURL URLWithString:@"spotify:track:2takcwOaAZWiXQijPHIx7B"];
        [self.streamingPlayer playURIs:@[ trackURI ] fromIndex:0 callback:^(NSError *error) {
            
            if (error != nil) {
                NSLog(@"*** Starting playback got error: %@", error.localizedDescription);
                return;
            }
        }];
    }];

```

I'm running iOS9.1 with the beta 12 framework.

**Comment by loretoparisi** [comment]
Are you using a premium account? Could you please dump the error object and when it crashes it helps to print the stacktrace using ```bt``` in the Xcode output.

**Comment by pir800** [comment]
Yeah I was using a premium account. I figured out this issue on my end about 20 minutes ago. I was combining two different tutorials and wasn't setting my scope to include "SPTAuthStreamingScope" before authorizing. Thanks for getting back.

**Comment by JMSerruya** [comment]
closing this for now then!
