### ISSUE TITLE
SPTAuthViewController appearing blank

### ISSUE THREAD

**Issue by AleLudovici** [spotify/ios-sdk#491]
Hi there,

I am using Swift and the following code to present the SPTAuthViewController but it appears blank. 

<code> authViewController.modalPresentationStyle = .OverCurrentContext</code>
<code>authViewController.modalTransitionStyle = .CrossDissolve</code>
<code>modalPresentationStyle = .CurrentContext</code>
<code>definesPresentationContext = true</code>
<code>presentViewController(authViewController, animated: false){}</code>

I found this issue in iOS 9 (simulator and iPhone 6s). Not tested in iOS 8.

**Comment by CVertex** [comment]
@AleLudovici Try clearing cookies before presenting the auth controller. If that doesn't work, try checking the right URL is being loaded in that UIWebView. You can confirm that using the simulator and safari

**Comment by bassntweeter** [comment]
Please proceed according to this ticket. https://github.com/spotify/ios-sdk/issues/457

**Comment by kerstin-h** [comment]
Make sure you call it after the viewDidAppear or it doesn't load properly and comes up blank.
