### ISSUE TITLE
Missing bitcode

### ISSUE THREAD

**Issue by connected-akemp** [spotify/ios-sdk#493]
Apple's latest requirements demand frameworks be built with bitcode, which the latest iOS SDK drop does not.

Without being properly built including bitcode, there is no longer anyway to build iOS apps including spotify.

As far as developer relations and third party integrations this should be a top priority.

**Comment by loretoparisi** [comment]
@connected-akemp  Absolutely needed! This issue is well discussed in https://github.com/spotify/ios-sdk/issues/445 and https://github.com/spotify/ios-sdk/issues/443

**Comment by JMSerruya** [comment]
Bitcode is now available in beta-14!

https://github.com/spotify/ios-sdk/releases/tag/beta-14

**Comment by JMSerruya** [comment]
Hello!, this has been fixed in beta-16! Thanks for your patience and feel free to leave a comment if you've any further problems with bitcode!
https://github.com/spotify/ios-sdk/releases/tag/beta-16
