### ISSUE TITLE
Beta 13 authentication confusion

### ISSUE THREAD

**Issue by GabeJacobs** [spotify/ios-sdk#496]
Hey,

I've integrated Beta 13, but I don't see any difference with login/authentication. Is there anything we have to do other than set our bundle ID (it's already set for us) to see the changes. 

Thanks,
Gabe

**Comment by JMSerruya** [comment]
i just uploaded a new version of Beta 13. I'm sorry for the confusion, please redownload!

https://github.com/spotify/ios-sdk/releases/download/beta-13/ios-sdk-deploy.zip
