### ISSUE TITLE
SPTAudioStreamingController crashes after adding "streaming" scope

### ISSUE THREAD

**Issue by rsieiro** [spotify/ios-sdk#499]
Steps to reproduce:

- Authenticate a user with the SDK **without** the `streaming` scope
- Try to stream a track, `loginWithSession` will fail with error code 8
- Reauthenticate the user adding the `streaming` scope
- Try to stream again, `loginWithSession` will crash

After the crash, running the app again and trying to stream works fine.

I also tried to dealloc `SPTAudioStreamingController` and create a new instance, but the crash happens anyway.

**Comment by CVertex** [comment]
I replicated that process, and it worked fine for me. Does it still do that for you?

**Comment by mstawecki** [comment]
@rsieiro Are you using the latest Framework and have `-ObjC` under "Other Linker Flags" in Xcode?

**Comment by rsieiro** [comment]
@mstawecki yes, I do have `-ObjC` under `Other Linker Flags`.
I am currently using Beta 12, will try Beta 13 and see if the crash still happens.

This is pretty hard to reproduce, since the account needs to be a "fresh" premium account. If the user ever authorized the app with the `streaming` scope before, then it won't crash.

**Comment by erdtman** [comment]
Sorry for not getting back earlier. In an attempt to get a better overview of the issues we are cleaning out some of the older issues. If this issue is still a problem in the latest SDK please reopen this issue or open a new one.
