### ISSUE TITLE
Access user library

### ISSUE THREAD

**Issue by nderkach** [spotify/ios-sdk#5]
Hi,

it would be nice to have access to the the library of an authenticated user to analyze his music preferences. Particularly, would be great to get a top artist list. such as with [this](https://developer.spotify.com/docs/apps/api/1.0/api-toplists-toplist.html) api call.

**Comment by erdtman** [comment]
We are deprecating the iOS-Metadata library.

The source code of the iOS-Metadata library has been released and can be found [here](https://github.com/erdtman/spotify-ios-metadata/). Spotify will not continue to maintain the released source code.

Either you can select to use the web-api directly or use the new open source iOS-Metadata library.

I will close this issue now.

We are sorry for the inconvenience that this creates, but looking back we think this is the best path forward.
