### ISSUE TITLE
Adding refresh/swap URL has caused initial login to fail (500)

### ISSUE THREAD

**Issue by mhuusko5** [spotify/ios-sdk#500]
Adding refresh/swap service URLs to avoid the 1 hour timeout has caused my initial login to start failing. After successfully bouncing back from Safari, the session object is nil and error is 500.

**Comment by CVertex** [comment]
I've noticed the same thing. After 1 hour, the SPTAuth.session object comes invalid. If you renew/refresh it, then the session object on SPTStreamingController becomes invalid, and you can't perform new actions like playUris or replaceUris without calling logout and login, which causes delays and interrupts the stream (in the case of replaceUris)...

**Comment by JMSerruya** [comment]
Hi! Thanks for reporting, we will take a look at this internally and prioritize it.

**Comment by volksport** [comment]
Any update? Not able to stay logged into Spotify

**Comment by volksport** [comment]
So we are setting
```
SPTAuth.defaultInstance.tokenSwapURL = [NSURL URLWithString:tokenSwapURL];
SPTAuth.defaultInstance.tokenRefreshURL = [NSURL URLWithString:tokenRefreshURL];
```

The server is setup, is receiving POSTs to the /swap endpoint whenever someone connects to Spotify, and appears to be receiving a code which is processed and sent back properly. But an hour later when the token expires the app takes us back to Spotify's website to login, which is quick, but shouldn't be necessary. The /refresh endpoint is never been called. At what point should this be happening? I don't see if there's anything we should be doing differently.

**Comment by iGGNoRe** [comment]
@volksport are you calling the `renewSession` method on your `SPTAuth.defaultInstance()`? That's what will call your `/refresh` url.

    if session.isValid() == false && auth.hasTokenRefreshService == true {
        auth.renewSession(session, callback: { (error, newSession) -> Void in
        . . .

**Comment by mhuusko5** [comment]
We're doing...

```obj-c
if (!SPTAuth.defaultInstance.session) {
        [UIApplication.sharedApplication openURL:SPTAuth.defaultInstance.loginURL];
        return;
}

 [SPTAuth.defaultInstance renewSession:SPTAuth.defaultInstance.session callback:^(NSError *error, SPTSession *session) {...
```

**Comment by mhuusko5** [comment]
Fixed on our end (refresh/swap service wasn't behaving properly).
