### ISSUE TITLE
while i add spotify framework my binary is rejected every time.

### ISSUE THREAD

**Issue by cloudjanak** [spotify/ios-sdk#507]

**Comment by CVertex** [comment]
What's your stated reason for being rejected? Usually, Apple give you a reason for being rejected

**Comment by cloudjanak** [comment]
Spotify Framework , i am using old framework.

**Comment by CVertex** [comment]
Use Application Loader instead of Xcode

_a guess_

**Comment by cloudjanak** [comment]
already tried with that also.

**Comment by cloudjanak** [comment]
With new Framework binary Rejected.

**Comment by JMSerruya** [comment]
What's the reason for rejection?

**Comment by cloudjanak** [comment]
Don't know but as i add spotify binary is rejected.

**Comment by cloudjanak** [comment]
Can we have skype communication,my id zetrixweb

**Comment by bassntweeter** [comment]
Without more details regarding why it is rejected it is not possible to help out, so I am closing this issue.
