### ISSUE TITLE
SPTPlaylistSnapshot createRequestForAddingTracks is not adding any tracks to the playlist, and not throwing an error. I am using the following piece of code:

### ISSUE THREAD

**Issue by arvind10n** [spotify/ios-sdk#508]
[SPTPlaylistSnapshot createRequestForAddingTracks:partialTrack toPlaylist: [NSURL URLWithString:[NSString stringWithFormat:@"%@",varArray.uri]] withAccessToken:[SPTAuth defaultInstance].session.accessToken error:&err];

The partialTrack variable is the array of SPPartialTrack Objects.

": Against All Odds (spotify:track:0P1gmN35r2OnPy59kgspnZ)", ": Against All Odds (spotify:track:728IDIbilgfPEr6KKFBDhX)", ": Against All Odds (spotify:track:42uYe00QcC7hvXa85Clckm)", ": Against All Odds (spotify:track:1ZIXm4irSIl43tjLSxxMFh)", ": Against All Odds (spotify:track:2QBc7eCEKHByE39PSZtzNK)", ": Against All Odds (spotify:track:6w19M2PM5nSJJ1G7KgRSL5)"

Can u plz help and resolve this issue.

**Comment by bassntweeter** [comment]
Hi, could you try that request directly against the web-api?

**Comment by erdtman** [comment]
Did you experience the same problem with a request directly towards the web-api?
