### ISSUE TITLE
Try to release swift version as Obj-c is now out dated 

### ISSUE THREAD

**Issue by cloudjanak** [spotify/ios-sdk#514]

**Comment by JMSerruya** [comment]
Hello, thank you for your suggestion. 

For the time being we wont release SWIFT demos, we are prioritizing other work in the iOS SDK. Objective-C is still an official supported language of the platform and writing a bridge is trivial. 

For more information, see Apple's documentation : https://developer.apple.com/library/ios/documentation/Swift/Conceptual/BuildingCocoaApps/MixandMatch.html

**Comment by cloudjanak** [comment]
Ok can you please add small demo where i can simply search song and playit.
And please use singleton class for all process this is too much complicated.
