### ISSUE TITLE
is there any delegate which determine song Playing is finished 

### ISSUE THREAD

**Issue by cloudjanak** [spotify/ios-sdk#515]

**Comment by cloudjanak** [comment]
Clients are sitting on head and you are still in Beta mode.

**Comment by JMSerruya** [comment]
@cloudjanak Please at least look at the documentation that we provide before opening a huge number of tickets.

https://developer.spotify.com/ios-sdk-docs/Documents/Protocols/SPTAudioStreamingPlaybackDelegate.html#//api/name/audioStreaming:didChangePlaybackStatus:
