### ISSUE TITLE
How can i simple play song i have track URI.

### ISSUE THREAD

**Issue by cloudjanak** [spotify/ios-sdk#520]

**Comment by JMSerruya** [comment]
https://developer.spotify.com/ios-sdk-docs/Documents/Classes/SPTAudioStreamingController.html#//api/name/playURI:callback:

**Comment by cloudjanak** [comment]
can you write simple method here Like 

-(void)playRemoteFile:(NSString*)songURL /* andBlock:(progressBlock)block*/{
    [[AFSoundManager sharedManager] startStreamingRemoteAudioFromURL:songURL andBlock:^(int percentage, CGFloat elapsedTime, CGFloat timeRemaining, NSError *error, BOOL finished) {

        
        NSInteger ti = (NSInteger)timeRemaining;
        NSInteger seconds = ti % 60;
        NSInteger minutes = (ti / 60) % 60;
        NSInteger eti = (NSInteger)elapsedTime;
        NSInteger eseconds = eti % 60;
        NSInteger eminutes = (eti / 60) % 60;
        
        if (!error) {
            if(timeRemaining>0){
                [self willChangeValueForKey:@"rTime"];
                [self willChangeValueForKey:@"eTime"];
                _rTime =[NSString stringWithFormat:@"%02ld:%02ld",(long)minutes, (long)seconds];
                _eTime =[NSString stringWithFormat:@"%02ld:%02ld",(long)eminutes, (long)eseconds];
                _per = 100-percentage;
                [self didChangeValueForKey:@"rTime"];
                [self didChangeValueForKey:@"eTime"];
            }else{
                [self willChangeValueForKey:@"rTime"];
                [self willChangeValueForKey:@"rTime"];
                _per=100;
                _rTime =@"0.0";
                _eTime =@"0.0";
                [self didChangeValueForKey:@"rTime"];
                [self didChangeValueForKey:@"eTime"];
            }
            
        } else {
            
            NSLog(@"There has been an error playing the remote file: %@", [error description]);
        }
        
    }];
}
