### ISSUE TITLE
Can i use old framework ? does this affects submission of Application to appStore ?

### ISSUE THREAD

**Issue by cloudjanak** [spotify/ios-sdk#523]

**Comment by JMSerruya** [comment]
It could affect the approval process if you use an old framework, see https://github.com/spotify/ios-sdk/issues/463 . 

We fixed that in beta-11, i suggest to use always our latest version since they include new features and bug fixes.

**Comment by cloudjanak** [comment]
Than when you update framework at that time i have to update myApp!!!  your most stable version?? MyApp is Rejected third time.
