### ISSUE TITLE
How to make sense with [SPTPartialTrack isPlayable]

### ISSUE THREAD

**Issue by martinobonfiglioli** [spotify/ios-sdk#528]
I found a solution for the right usage of `isPlayable` parameter of `SPTPartialTrack`

With the standard API of the SDK you are not able to retrieve the only playable tracks for the user's country, but is possible to change the `NSURLRequest` and append `market` parameter and the problem solved!

**First**, catch the standard `NSURLRequest` from the SDK
```
NSError *error;
NSMutableURLRequest *request = (NSMutableURLRequest*)[SPTPlaylistSnapshot createRequestForPlaylistWithURI:partial.uri
                                                                                            accessToken:self.session.accessToken
                                                                                                  error:&error];
```

**Then** add `market` parameter the the API call

```
[request setURL:[NSURL URLWithString:[NSString stringWithFormat:@"%@?market=%@",request.URL.absoluteString,[self getUserMarketPlace]]]];
```

**Finally**, call the API and parse parameter with the SDK standard objects

```
    [NSURLConnection sendAsynchronousRequest:request
                                       queue:[NSOperationQueue mainQueue]
                           completionHandler:^(NSURLResponse * _Nullable response, NSData * _Nullable data, NSError * _Nullable connectionError) {
                              
                               
                               if (connectionError) {
                                   if (completion) {
                                       completion(connectionError, nil);
                                   }
                                   return;
                               }
                               
                               NSError *jsonError;
                               NSDictionary *dict = [NSJSONSerialization JSONObjectWithData:data
                                                                                    options:NSJSONReadingAllowFragments
                                                                                      error:&jsonError];
                               
                               if (jsonError) {
                                   if (completion) {
                                       completion(jsonError,nil);
                                   }
                                   return;
                               }
                               
                               NSError *parsingError;
                               SPTPlaylistSnapshot *playlistResult = [SPTPlaylistSnapshot playlistSnapshotFromDecodedJSON:dict
                                                                                                                   error:&parsingError];
                               
                               if (completion) {
                                   completion(parsingError, playlistResult);
                               }
                               
                           }];
```
I don't know if this is the only or the correct solution, but without this the parameter `isPlayable` is not working properly.
I want know if is possible to set `market` parameter for all the SDK APIs in order to know which tracks are playable or not.

Thanks.

**Comment by patrickbusch** [comment]
I read the same in another thread, but for me isPlayable is not working using 
`SPTRequest.requestItemAtURI(url, session, market)`

**Comment by guilhermeprudente** [comment]
@martinobonfiglioli , thank you for that. I have followed that approach and it is working so far. 
I have also tested that the snapshot object used persists with the market filtering when requesting nextPages (nextPageWithSession), so that's important too for whoever is facing this issue!

**Comment by iGranDav** [comment]
It works well indeed! If you want to get user market available tracks only you can pass `from_token` into the market query but you need to ask for `ReadUserPrivateScope` during auth.

**Comment by erdtman** [comment]
Sorry for not getting back earlier. In an attempt to get a better overview of the issues we are cleaning out some of the older issues. If this issue is still a problem in the latest SDK please reopen this issue or open a new one.
