### ISSUE TITLE
Difference between SPTPartialTrack and SPTTrack ?

### ISSUE THREAD

**Issue by cloudjanak** [spotify/ios-sdk#529]

**Comment by bassntweeter** [comment]
From the documentation:


SPTPartialTrack represents a “partial” track on the Spotify service. You can promote this to a full track object using SPTTrack.

API Model: https://developer.spotify.com/web-api/object-model/#track-object-simplified

API Docs: https://developer.spotify.com/web-api/track-endpoints/
