### ISSUE TITLE
ITC.apps.preReleaseBuild.errors.invalidBinary

### ISSUE THREAD

**Issue by cloudjanak** [spotify/ios-sdk#536]
Binary always rejected

**Comment by thelinmichael** [comment]
Closing this issue since it's not living up to the standards of a good feature request or bug report. If you want to re-open it, please add more information to your post first to help others understand what you want.

**Comment by johntej110491** [comment]
![screen shot 2018-01-27 at 12 40 00 pm](https://user-images.githubusercontent.com/12079747/35469682-94a781f4-0360-11e8-8242-86a168255145.png)

Always: There was an error importing this build.
