### ISSUE TITLE
SPTAuth renewSession returns nil.

### ISSUE THREAD

**Issue by jhrasco** [spotify/ios-sdk#538]
Hi, I'm using the latest iOS SDK and whenever I tried to renew session with below code snippets, it returns a nil value for session.

[SPTAuth defaultInstance].clientID = <client id>;
 [SPTAuth defaultInstance].requestedScopes = @[SPTAuthStreamingScope, SPTAuthUserReadPrivateScope];

if (!self.session.isValid) {
        [[SPTAuth defaultInstance] renewSession:self.session callback:^(NSError *error, SPTSession *session) {
            if (!error) {
                 // The value of session is nil.
            }       
       }];
}

Do I need to setup tokenRefreshURL?

**Comment by erdtman** [comment]
Sorry for not getting back earlier. In an attempt to get a better overview of the issues we are cleaning out some of the older issues. If this issue is still a problem in the latest SDK please reopen this issue or open a new one.
