### ISSUE TITLE
SPTAuthViewController: 4.99$ Unlimited account Issue

### ISSUE THREAD

**Issue by loretoparisi** [spotify/ios-sdk#540]
Trying to login with a old Spotify Unlimited account (4.99$/mo), using the embedded ```SPTAuthViewController```, the sdk crashes. I do not have a stack trace already.

**Comment by erdtman** [comment]
Sorry for not getting back earlier. In an attempt to get a better overview of the issues we are cleaning out some of the older issues. If this issue is still a problem in the latest SDK please reopen this issue or open a new one.
