### ISSUE TITLE
Play does not resume after interruption , like call

### ISSUE THREAD

**Issue by ZetrixWeb-iOS** [spotify/ios-sdk#542]

**Comment by iGGNoRe** [comment]
This is unrelated to the SDK. It needs to be handled [through iOS directly.](https://developer.apple.com/library/ios/documentation/AVFoundation/Reference/AVAudioSessionDelegate_ProtocolReference/index.html)

[`- endInterruption`](https://developer.apple.com/library/ios/documentation/AVFoundation/Reference/AVAudioSessionDelegate_ProtocolReference/index.html#//apple_ref/occ/intfm/AVAudioSessionDelegate/endInterruption)

**Comment by GabeJacobs** [comment]
yeah, not Spotify's responsibility @JanakLN

**Comment by erdtman** [comment]
Closing this issue since interrupts has to be handled outside the Spotify SDK

For additional information see #202
