### ISSUE TITLE
Is there any way to know how much of the currrent song has been buffered?

### ISSUE THREAD

**Issue by matanvr** [spotify/ios-sdk#544]
I would like to buffer the whole song or up to a certain point before starting to play. Is there any way to accomplish this? My impression is that I'd need to implement my own version SPTCoreAudioController that would internally manage this. Thanks in advance.

**Comment by cloudjanak** [comment]
The spotify SDK is beta version not good to use in Live applications.Go with SoundCloud.

**Comment by matanvr** [comment]
I understand that it's a beta - I'm working on a side project that is aiming to create a giant speaker of multiple phones playing the same music. I have managed to get a prototype working perfectly with music thats locally loaded in my phone. However, the buffering on this SDK is really inconsistent - are there any suggestions to make this work?

**Comment by sosale151** [comment]
I have the same question, so it'd be great if I could get an answer too.

If it's not possible to know the exact amount of buffer, is there a way for me to know whether the current track is buffering?

**Comment by SoCohesive** [comment]
I have the same issue. This would be a great addition and would make the SDK much stronger and reliable. Please add it soon!!!!!

**Comment by SoCohesive** [comment]
@sosale151 @matanvr were you able to find any work arounds for this issue?

**Comment by sosale151** [comment]
Nope @SoCohesive

**Comment by erdtman** [comment]
there is currently no direct way, one way would be to override the caching function and handle it your self then you would get some of this information.

**Comment by sosale151** [comment]
@erdtman, could I have some more information about how to go about doing this?

**Comment by erdtman** [comment]
on the SPTAudioStreamingController object you can set diskCache which is an implementation of SPTDiskCaching.
See headers for documentation
