### ISSUE TITLE
valid session but not playing track

### ISSUE THREAD

**Issue by ZetrixWeb-iOS** [spotify/ios-sdk#545]

**Comment by cloudjanak** [comment]
issue with latest SDK

**Comment by JanakLN** [comment]
-(void)playSpotifyTrack:(NSURL*)playURI trackDuration:(float)duration {
    
    id sessionData = [[NSUserDefaults standardUserDefaults] objectForKey:@"SpotifyOAuthSession"];
    self.spotifySession = sessionData ? [NSKeyedUnarchiver unarchiveObjectWithData:sessionData] : nil;
    
    if([self.spotifySession isValid]){
        NSLog(@"Valid session");
    }else{
        [self spotifySessionCheckForPlaying];
    }
    
    [self.spotifyPlayer loginWithSession:self.spotifySession callback:^(NSError *error) {
        if (error != nil) {
            NSLog(@"*** Logging in got error: %@", error);
            return;
        }

        [self.spotifyPlayer playURIs:@[ playURI ] fromIndex:0 callback:^(NSError *error) {
            if (error != nil) {
                NSLog(@"*** Starting playback got error: %@", error);
                return;
            }
        }];
    }];
    
    [self startSeekBar:duration];
    
    [[UIApplication sharedApplication] beginReceivingRemoteControlEvents];
}

**Comment by EgaSetya** [comment]
did you find solution to this problem?

**Comment by JanakLN** [comment]
No,still waiting for solution

**Comment by erdtman** [comment]
Sorry for not getting back earlier. In an attempt to get a better overview of the issues we are cleaning out some of the older issues. If this issue is still a problem in the latest SDK please reopen this issue or open a new one.
