### ISSUE TITLE
Updating Playlist While Playing 

### ISSUE THREAD

**Issue by estock** [spotify/ios-sdk#547]
I would like to check at the end of each song if the playlist has any new tracks but I can't figure out a way to do this  ... is there a way to update the playlist that has already been  set using the playURIs method?

**Comment by CVertex** [comment]
You can use replaceURIs to replace the existing loaded playlist with another set of URIs.

Let me know if that works for you

**Comment by erdtman** [comment]
Sorry for not getting back earlier. In an attempt to get a better overview of the issues we are cleaning out some of the older issues. If this issue is still a problem in the latest SDK please reopen this issue or open a new one.
