### ISSUE TITLE
Renew session error critical issue  :BUG

### ISSUE THREAD

**Issue by ZetrixWeb-iOS** [spotify/ios-sdk#548]
error Error Domain=com.spotify.auth Code=400 "No refresh token available in the session!" UserInfo={NSLocalizedDescription=No refresh token available in the session!}

**Comment by JanakLN** [comment]
can you please solve above issue?

**Comment by JanakLN** [comment]
No refresh token available in the session!

**Comment by ozzotto** [comment]
Any progress with that? Thanx

**Comment by erdtman** [comment]
Sorry for not getting back earlier. In an attempt to get a better overview of the issues we are cleaning out some of the older issues. If this issue is still a problem in the latest SDK please reopen this issue or open a new one.

Are you using the Code grant flow?
