### ISSUE TITLE
Domain=com.spotify.ios-sdk.playback Code=4 "An unexpected NULL pointer was passed as an argument to a function." UserInfo={NSLocalizedDescription=An unexpected NULL pointer was passed as an argument to a function.}

### ISSUE THREAD

**Issue by JanakLN** [spotify/ios-sdk#549]

**Comment by JMSerruya** [comment]
Closing this issue since it's not living up to the standards of a good feature request or bug report. If you want to re-open it, please add more information to your post first to help others understand what you want.
