### ISSUE TITLE
Music[40983:2101047] *** Logging in got error: Error Domain=com.spotify.ios-sdk.playback Code=8 "Login to Spotify failed because of invalid credentials." UserInfo={NSLocalizedDescription=Login to Spotify failed because of invalid credentials.}

### ISSUE THREAD

**Issue by JanakLN** [spotify/ios-sdk#550]

**Comment by JMSerruya** [comment]
Closing this issue since it's not living up to the standards of a good feature request or bug report. If you want to re-open it, please add more information to your post first to help others understand what you want.
