### ISSUE TITLE
(SPTAudioStreamingController) currentTrackDuration and currentPlaybackPosition are returning zero during playback

### ISSUE THREAD

**Issue by owenworley** [spotify/ios-sdk#556]
I am encountering an intermittent issue where as I am playing back music and receiving 0 from both currentTrackDuration and currentPlaybackPosition on my instance of SPTAudioStreamingController.

I cannot provide reproduction steps as it is an intermittent event which does not always happen.

**Comment by cjwhitsitt** [comment]
I'm getting this as well. It happened twice in a row and I'm now unable to reproduce, even following what I believed to be the exact same steps after deleting and reinstalling the app.

**Comment by CVertex** [comment]
Same here. Happens intermittently, but not reproducible.

**Comment by cjwhitsitt** [comment]
This is happening for me 100% of the time now in beta 20.

**Comment by gchilds** [comment]
This has moved to `playbackState.currentTrack.durationMs`. See #719
