### ISSUE TITLE
How to retrieve more than 20 tracks on SPTYourMusic 

### ISSUE THREAD

**Issue by thiagoramos23** [spotify/ios-sdk#557]
Hello guys!

I'm using this method SPTYourMusic.savedTracksForUserWithAccessToken to get tracks on my library. I noticed that this method only get 20 tracks, how can I get more tracks or there is a way to paginate this and get another 20 tracks and so on?

Thanks. 

Great work with this library.

**Comment by iGGNoRe** [comment]
Using that method returns an [SPTListPage](https://developer.spotify.com/ios-sdk-docs/Documents/Classes/SPTListPage.html), which you can call the following on to get more tracks (pages):

[`– requestNextPageWithSession:callback:`](https://developer.spotify.com/ios-sdk-docs/Documents/Classes/SPTListPage.html#//api/name/requestNextPageWithSession:callback:)
[`– requestNextPageWithAccessToken:callback:`](https://developer.spotify.com/ios-sdk-docs/Documents/Classes/SPTListPage.html#//api/name/requestNextPageWithAccessToken:callback:)

**Comment by RocketCity** [comment]
Very helpful example of paging in https://github.com/spotify/ios-sdk/issues/447 by @loretoparisi

**Comment by erdtman** [comment]
Sorry for not getting back earlier. In an attempt to get a better overview of the issues we are cleaning out some of the older issues. If this issue is still a problem in the latest SDK please reopen this issue or open a new one.
