### ISSUE TITLE
Errors on " spotify-action:// " and " App Transport Security "

### ISSUE THREAD

**Issue by RudyRosciglione** [spotify/ios-sdk#558]
I got basic errors on Spotify login, i have since previous solutions, but i tried many things and so far they all failed. I pretty sure i'm missing a little point which would make it work. Any ideas? 

You can clone the project : https://github.com/RudyRosciglione/Pancake

The two errors : 
2016-01-04 11:20:56.590 Pancake[24835:5095384] -canOpenURL: failed for URL: "spotify-action://" - error: "This app is not allowed to query for scheme spotify-action"

2016-01-04 11:21:06.248 Pancake[24835:5095960] App Transport Security has blocked a cleartext HTTP (http://) resource load since it is insecure. Temporary exceptions can be configured via your app's Info.plist file.
AUTHENTICIFATION ERROR

<img width="1552" alt="screen shot 2016-01-04 at 11 20 14" src="https://cloud.githubusercontent.com/assets/1166152/12087705/6d82c634-b2d5-11e5-9304-cc972424ab9d.png">
<img width="1552" alt="screen shot 2016-01-04 at 11 20 18" src="https://cloud.githubusercontent.com/assets/1166152/12087706/6d87740e-b2d5-11e5-8401-922481ebe71a.png">

When i run the app.
<img width="1524" alt="screen shot 2016-01-04 at 11 21 16" src="https://cloud.githubusercontent.com/assets/1166152/12087779/11a52e6e-b2d6-11e5-8706-dc99087ae8f4.png">

**Comment by dcvz** [comment]
The `App Transport Security` error is probably against your localhost. Read [this](http://ste.vn/2015/06/10/configuring-app-transport-security-ios-9-osx-10-11/) and add localhost to the exceptions, although you may have to use `127.0.0.1` instead.

The `spotify-action://` is not too important (that's not why your authentication is failing) but it's for allowing your users to authenticate through the Spotify app if it's installed. Read up on that [here](http://useyourloaf.com/blog/querying-url-schemes-with-canopenurl.html) (skip to the bottom where it titles: App Linked with iOS 9) and add `spotify-action`.

**Comment by RudyRosciglione** [comment]
@dcvz Thank for your input. @steffex made a pull this morning and he fixed the ```App Transport Security``` - I forget to add information in my ```info.plist```, he fixed also some codes lignes. As you could see - https://github.com/RudyRosciglione/Pancake

About the ```spotify-action://``` i will check this out as soon as possible sounds to not be complicated. 
Thanks anyway!
