### ISSUE TITLE
Calling playURIs:withOptions: on the same URI list and trackIndex as currently playing crashes app

### ISSUE THREAD

**Issue by jakereps** [spotify/ios-sdk#559]
Using a UITableView `didSelectRowAtIndexPath` runs player.playURIs(self.trackList, withOptions:...) and having the options set to `options.trackIndex = Int32(indexPath.row)`

When selecting a track that is already currently playing, instead of restarting the song like one would assume would happen the app just crashes with:

    2016-01-11 22:11:01.822  -[SPTPartialTrack absoluteString]: unrecognized 
    selector sent to instance 0x7fa08d0a36b0
    2016-01-11 22:11:01.826  *** Terminating app due to uncaught 
    exception 'NSInvalidArgumentException', reason: '-[SPTPartialTrack absoluteString]: 
    unrecognized selector sent to instance 0x7fa08d0a36b0'

Going through and selecting every song in the list/tableView starts the track just as expected, but pressing on the track that is already playing crashes. Any advice?

My entire `didSelectRowAtIndexPath` function looks like this, so there is nothing weird going on code-wise, is this a bug or just not possible to do?:

```swift
    let options = SPTPlayOptions()
    options.trackIndex = Int32(indexPath.row)
    self.player!.playURIs(self.trackList, withOptions: options, callback: nil)
```

#### Edit:

I got it to work using the following block in didSelectRowAtIndexPath:

```swift
    self.player!.setIsPlaying(false) { (error) -> Void in
        if error != nil {
            print("Error in stopping playback: \(error)")
            return
        }

        let options = SPTPlayOptions()
        options.trackIndex = Int32(indexPath.row)
        self.player!.playURIs(self.trackList, withOptions: options, callback: nil)
    }
```
It seems like this shouldn't be necessary though and should just start the track over as easily as it can change indices. Leaving open as a bug?

**Comment by iGGNoRe** [comment]
I got it to work using the following block in `didSelectRowAtIndexPath`:

        self.player!.setIsPlaying(false) { (error) -> Void in
            if error != nil {
                print("Error in stopping playback: \(error)")
                return
            }
            
            let options = SPTPlayOptions()
            options.trackIndex = Int32(indexPath.row)
            self.player!.playURIs(self.trackList, withOptions: options, callback: nil)
        }

It seems like this shouldn't be necessary though and should just start the track over as easily as it can change indices. Leaving open as a bug?

**Comment by erdtman** [comment]
playURIs has been removed
