### ISSUE TITLE
remoteApp disconnects after long time on pause, App is active

### ISSUE THREAD

**Issue by paicolman** [spotify/ios-sdk#56]
My app connects with the spotify app correctly and everything works fine. One use case, though, is to play some music for a short time and then pause for long time (around ~10 minutes max). Unfortunately, the remoteApp stops responding after around 5 minutes of no action. Is there a way to keep the connection alive?

My app is during that time active - I force it to remain active to prevent the problem of disconnecting when on background...

**Comment by jackfreeman** [comment]
@paicolman This is because iOS doesn't allow apps to live in the background indefinitely. Spotify will start a background task if App Remote is connected and music is paused but it will shutdown when the background time allotted by iOS has expired.
