### ISSUE TITLE
NSJSONSerialization crashing app - reason: 'data parameter is nil'

### ISSUE THREAD

**Issue by jakereps** [spotify/ios-sdk#560]
Calling `requestNextPageWithAccessToken` is occasionally causing my app to crash due to an unhanded exception within the framework. Specifically it occurs while fetching the next pages while scrolling through a tableView. As shown in the stack it is thrown within framework code:

    2016-01-12 13:07:14.597 app[--] *** Terminating app due to uncaught 
    exception 'NSInvalidArgumentException', reason: 'data parameter is nil'
    *** First throw call stack:
    (
    	0   CoreFoundation                      0x0000000110cb4e65 __exceptionPreprocess + 165
    	1   libobjc.A.dylib                     0x000000010ff83deb objc_exception_throw + 48
    	2   CoreFoundation                      0x0000000110cb4d9d +[NSException raise:format:] + 205
    	3   Foundation                          0x000000010fc76089 +[NSJSONSerialization JSONObjectWithData:options:error:] + 67
    	4   app                                 0x000000010f52078f +[SPTListPage listPageFromData:withResponse:expectingPartialChildren:rootObjectKey:error:] + 92
    	5   app                                 0x000000010f520aed __53-[SPTListPage requestPageAtURL:accessToken:callback:]_block_invoke + 172
    	6   libdispatch.dylib                   0x0000000113ab4e5d _dispatch_call_block_and_release + 12
    	7   libdispatch.dylib                   0x0000000113ad549b _dispatch_client_callout + 8
    	8   libdispatch.dylib                   0x0000000113abd2af _dispatch_main_queue_callback_4CF + 1738
    	9   CoreFoundation                      0x0000000110c14d09 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
    	10  CoreFoundation                      0x0000000110bd62c9 __CFRunLoopRun + 2073
    	11  CoreFoundation                      0x0000000110bd5828 CFRunLoopRunSpecific + 488
    	12  GraphicsServices                    0x0000000115109ad2 GSEventRunModal + 161
    	13  UIKit                               0x0000000111aff610 UIApplicationMain + 171
    	14  app                                 0x000000010f4f01bd main + 109
    	15  libdyld.dylib                       0x0000000113b0992d start + 1
    )
    libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by fotiDim** [comment]
I still see this crash in beta-16. Wasn't it supposed to be fixed?

**Comment by DmytroAnkudinov** [comment]
Fixed in Beta25.

**Comment by WCL-LV** [comment]
I also have this issue in my personal project.I want to know how can you solve this?

**Comment by fotiDim** [comment]
Did you update on the latest SDK?

**Comment by WCL-LV** [comment]
Actually,When I use this method [NSJSONSerialization JSONObjectWithData:options:error:].It appears this issue.Not in spotify SDK.I found here by google.
