### ISSUE TITLE
beta 14 and iOS 7 crashes the Spotify app

### ISSUE THREAD

**Issue by Anders27** [spotify/ios-sdk#564]
With Spotify SDK beta 14 running on iOS 7, the Spotify app(!) crashes during login attempt.
My app is not affected by the crash but login fails.

I’ve tested with two devices, an iPhone 4 and iPad Mini.

Works fine with devices running iOS 8.

On iOS 9 login works the old way but with console error:
-canOpenURL: failed for URL: "spotify-action://" - error: "This app is not allowed to query for scheme spotify-action"

Adding 
LSApplicationQueriesSchemes with "spotify-action"
to the Info.plist takes away the error but then login fails!

I had to go back to Spotify SDK beta 12, then everything works OK.

Below is the crash log for the crashed Spotify app.

Incident Identifier: 0B762D52-2675-4F20-855C-01F595F39EF7
CrashReporter Key:   d60a85b6e3d56cc72103e14f7b392c1bbe6ba7aa
Hardware Model:      iPad2,5
Process:             Spotify [26627]
Path:                /var/mobile/Applications/A073AA14-53E6-4D50-9AF4-87A11F5DC102/Spotify.app/Spotify
Identifier:          com.spotify.client
Version:             460001466 (4.6.0)
Code Type:           ARM (Native)
Parent Process:      launchd [1]

Date/Time:           2016-01-11 09:51:20.944 +0100
OS Version:          iOS 7.1.2 (11D257)
Report Version:      104

Exception Type:  EXC_CRASH (SIGABRT)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Triggered by Thread:  0

Last Exception Backtrace:
0   CoreFoundation                	0x2ec83f7e __exceptionPreprocess + 126
1   libobjc.A.dylib               	0x3984fcca objc_exception_throw + 34
2   CoreFoundation                	0x2ec87912 -[NSObject(NSObject) doesNotRecognizeSelector:] + 198
3   CoreFoundation                	0x2ec861fe ___forwarding___ + 702
4   CoreFoundation                	0x2ebd5764 _CF_forwarding_prep_0 + 20
5   Spotify                       	0x014864e4 0x4a000 + 21218532
6   Spotify                       	0x01486c48 0x4a000 + 21220424
7   Spotify                       	0x00522a64 0x4a000 + 5081700
8   libdispatch.dylib             	0x39d3782e _dispatch_call_block_and_release + 6
9   libdispatch.dylib             	0x39d3781a _dispatch_client_callout + 18
10  libdispatch.dylib             	0x39d3e49a _dispatch_main_queue_callback_4CF$VARIANT$mp + 274
11  CoreFoundation                	0x2ec4e89c __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 4
12  CoreFoundation                	0x2ec4d170 __CFRunLoopRun + 1296
13  CoreFoundation                	0x2ebb7eba CFRunLoopRunSpecific + 518
14  CoreFoundation                	0x2ebb7c9e CFRunLoopRunInMode + 102
15  GraphicsServices              	0x33ade65e GSEventRunModal + 134
16  UIKit                         	0x31504148 UIApplicationMain + 1132
17  Spotify                       	0x00086fea 0x4a000 + 249834
18  libdyld.dylib                 	0x39d5cab2 tlv_initializer + 2

**Comment by zackfletch00** [comment]
+1, also experienced this issue on iOS 7.
Will make my app iOS 8+ for now (users will likely already have Spotify's app installed and therefore experience the same crash unless they uninstall Spotify).
