### ISSUE TITLE
SPTAuthViewController on slow networks

### ISSUE THREAD

**Issue by Muesly** [spotify/ios-sdk#565]
When network performance is slow the auth controller view appears as a blank white page with just a cross.  It would be good to have a loading indicator for the user to see, until the login controls appear.

**Comment by GabeJacobs** [comment]
This would be great

**Comment by loretoparisi** [comment]
To achieve this I had to create a custom ```UIWebView```, a custom ```UIView``` for the progress (the blue progress bar at the top). Then I added a ```UIRefreshControl``` as well to the web view.

![screen shot 2016-01-14 at 19 01 18](https://cloud.githubusercontent.com/assets/163333/12332877/489c86a6-baf1-11e5-8d7d-d0fab3980ef1.png)

**Comment by ahallora** [comment]
@loretoparisi , that is amazing!! Care to share how you managed to hook into the Spotify uiwebview and add your own loading indicator at the top? :smile:

**Comment by loretoparisi** [comment]
@ahallora let me clean up the code...

**Comment by CVertex** [comment]
This is great! Will be nice to have in the SDK itself

**Comment by loretoparisi** [comment]
@CVertex Yes I think it should be definitively in the sdk since the user needs more control over a floating window.

**Comment by charleshkang** [comment]
@loretoparisi Could I please take a look at how you incorporated the authVC with an embedded UIWebView?

**Comment by DmytroAnkudinov** [comment]
SPTAuthViewController has been deprecated in Beta25 and should not be used anymore, as it will be removed in the subsequent releases. Please use SFSafariViewController instead.
