### ISSUE TITLE
playURI:callback: is marked as deprecated in SPTAudioStreamingController.h, but not documented as deprecated.

### ISSUE THREAD

**Issue by dtrenz** [spotify/ios-sdk#566]
Neither the HTML docs nor the inline method docs indicate that the `playURI:callback:` method is deprecated, even though it is marked for deprecation in code.

Is it deprecated, or was it accidentally deprecated?

[SPTAudioStreamingController HTML documentation](https://developer.spotify.com/ios-sdk-docs/Documents/Classes/SPTAudioStreamingController.html#//api/name/playURI:callback:)

**SPTAudioStreamingController.h#playURI:callback:**
```obj-c
/** Play a Spotify URI.
 
 Supported URI types: Tracks, Albums and Playlists

 @see -playURIs:withOptions:callback:

 @param uri The URI to play.
 @param block The callback block to be executed when the playback command has been
 received, which will pass back an `NSError` object if an error ocurred.
 */
-(void)playURI:(NSURL *)uri callback:(SPTErrorableOperationCallback)block DEPRECATED_ATTRIBUTE;
```

**Comment by bass4aj** [comment]
I have been wondering this as well

**Comment by erdtman** [comment]
it should have been updated with the latest release
