### ISSUE TITLE
AudioStreamingController stop method does not clear queue, as documented.

### ISSUE THREAD

**Issue by dtrenz** [spotify/ios-sdk#567]
From: https://developer.spotify.com/ios-sdk-docs/Documents/Classes/SPTAudioStreamingController.html#//api/name/stop:
> Stop playback and clear the queue and list of tracks.

Expected: Calling `stop` should clear the player queue.
Actual: Tracks in queue remain in queue after calling `stop`.

**Comment by erdtman** [comment]
Sorry for not getting back earlier. In an attempt to get a better overview of the issues we are cleaning out some of the older issues. If this issue is still a problem in the latest SDK please reopen this issue or open a new one.
