### ISSUE TITLE
No Items for when converting from PartialPlaylist to PlaylistSnapshot

### ISSUE THREAD

**Issue by dcvz** [spotify/ios-sdk#568]
<img width="672" alt="screen shot 2016-01-16 at 10 56 18 pm" src="https://cloud.githubusercontent.com/assets/2475932/12374708/78dd1434-bca4-11e5-8076-f9bb5965794f.png">
clearly shows that there are items in the playlist but the page items is nil, happens for all playlists

**Comment by dcvz** [comment]
further attempts show that it's only while using the `SPTPlaylistSnapshot.playlistWithURI`. If I create the request using `SPTPlaylistSnapshot`'s method and run the request through `SPTRequest` it gives me valid data.

**Comment by erdtman** [comment]
We are deprecating the iOS-Metadata library.

The source code of the iOS-Metadata library has been released and can be found [here](https://github.com/erdtman/spotify-ios-metadata/). Spotify will not continue to maintain the released source code.

Either you can select to use the web-api directly or use the new open source iOS-Metadata library.

I will close this issue now.

We are sorry for the inconvenience that this creates, but looking back we think this is the best path forward.
