### ISSUE TITLE
Creating request for next page on a search result create a terminal page

### ISSUE THREAD

**Issue by dcvz** [spotify/ios-sdk#570]
After performing a search using `SPTSearch.performSearchWithQuery` you get a good `SPTListPage`object. However, if you try to use `createRequestForNextPageWithAccessToken` on it and perform the request it will return a new page that has lost information about the total size of the results and what the next page URL is. Using the `SPTListPage`'s `requestNextPageWithSession` works correctly though.

**Comment by erdtman** [comment]
We are deprecating the iOS-Metadata library.

The source code of the iOS-Metadata library has been released and can be found [here](https://github.com/erdtman/spotify-ios-metadata/). Spotify will not continue to maintain the released source code.

Either you can select to use the web-api directly or use the new open source iOS-Metadata library.

I will close this issue now.

We are sorry for the inconvenience that this creates, but looking back we think this is the best path forward.
