### ISSUE TITLE
Full Territories where Spotify is available (RSS Feed like)

### ISSUE THREAD

**Issue by loretoparisi** [spotify/ios-sdk#572]
Given that the home page has the whole list

https://www.spotify.com/it/select-your-country/

and the F.A.Q as well here https://support.spotify.com/us/learn-more/faq/#!/article/full-list-of-territories-where-spotify-is-available

is there a RSS like feed to retrieve the updated official list of territories where Spotify is available right now in order to do this programmatically (client or server side)?

Thank you.

**Comment by CVertex** [comment]
I don't know of a complete list. Perhaps you could fetch a large set of tracks and union the availability regions?
Not ideal

**Comment by loretoparisi** [comment]
@CVertex Not sure, by the way I find very useful parsing the official web page turned into an api through import.io ( https://www.import.io/ )

https://api.import.io/store/connector/072b2111-ef9c-4f06-8c6c-ead3925ed9a9/_query?input=webpage/url:https%3A%2F%2Fwww.spotify.com%2Fit%2Fselect-your-country%2F&&_apikey=5ff4fc3c12ec4ab993d2f0e80fce42774edddc5af1b08eabb1f2523cb1a1cc27a083a9b47ad2d880252fe128088a2a37971bad5e7e38b1fce3c71cac91d46c8fe80d4bf1354724fb311ef4b8a736d075

This will give you back an array (currently is 64 items) of countries:

```json
{
            "marketpull_link/_title": "Andorra",
            "marketpull_link/_source": "/ad/select-your-country/",
            "marketpull_link/_text": "Andorra",
            "marketpull_link": "https://www.spotify.com/ad/select-your-country/"
}
```

Unfortunately, there is no ISO 3166-1 country code for each country, in any case this is very easy to handle via a static map.

**Comment by erdtman** [comment]
We are deprecating the iOS-Metadata library.

The source code of the iOS-Metadata library has been released and can be found [here](https://github.com/erdtman/spotify-ios-metadata/). Spotify will not continue to maintain the released source code.

Either you can select to use the web-api directly or use the new open source iOS-Metadata library.

I will close this issue now.

We are sorry for the inconvenience that this creates, but looking back we think this is the best path forward.
