### ISSUE TITLE
SimpleTrackPlayback crashes Spotify app on iOS 7

### ISSUE THREAD

**Issue by Anders27** [spotify/ios-sdk#573]
I'm reporting this problem again since it makes it impossible to uses SDK Beta 14.

This is the same problem as issue #564. This time I tested with the "Simple Track Playback" demo sample and below is the crash report.

Since this doesn't seem to be a problem with SDK beta 14 but with the Spotify app itself, it should probably be reported to the team develops the Spotify iOS app. I don't know where and how to report but let me know ho to do it and I will report it.

Partial crash log:

Incident Identifier: 65096A67-8F8F-46C0-A5F6-636E03F2A5AE
CrashReporter Key:   aee79ffed77b40aa9fe29236a6bb0ef26a2b0f20
Hardware Model:      iPhone3,1
Process:             Spotify [141]
Path:                /var/mobile/Applications/1DD4762D-0A01-4D1A-A8EA-36CC5F58D9D5/Spotify.app/Spotify
Identifier:          com.spotify.client
Version:             470000985 (4.7.0)
Code Type:           ARM (Native)
Parent Process:      launchd [1]

Date/Time:           2016-01-23 11:26:29.503 +0100
OS Version:          iOS 7.1.2 (11D257)
Report Version:      104

Exception Type:  EXC_CRASH (SIGABRT)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Triggered by Thread:  0

Last Exception Backtrace:
0   CoreFoundation                  0x2fb65f7e **exceptionPreprocess + 126
1   libobjc.A.dylib                 0x3a316cca objc_exception_throw + 34
2   CoreFoundation                  0x2fa9fa36 -[__NSPlaceholderArray initWithObjects:count:] + 414
3   CoreFoundation                  0x2faa933c +[NSArray arrayWithObjects:count:] + 40
4   Spotify                         0x01517490 0x9e000 + 21468304
5   Spotify                         0x01518416 0x9e000 + 21472278
6   Spotify                         0x01518090 0x9e000 + 21471376
7   Spotify                         0x01517ea4 0x9e000 + 21470884
8   Spotify                         0x00578704 0x9e000 + 5089028
9   libdispatch.dylib               0x3a7fe82e _dispatch_call_block_and_release + 6
10  libdispatch.dylib               0x3a7fe81a _dispatch_client_callout + 18
11  libdispatch.dylib               0x3a7fe772 _dispatch_main_queue_callback_4CF$VARIANT$up + 250
12  CoreFoundation                  0x2fb3089c __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE** + 4
13  CoreFoundation                  0x2fb2f170 __CFRunLoopRun + 1296
14  CoreFoundation                  0x2fa99eba CFRunLoopRunSpecific + 518
15  CoreFoundation                  0x2fa99c9e CFRunLoopRunInMode + 102
16  GraphicsServices                0x3499f65e GSEventRunModal + 134
17  UIKit                           0x323e6148 UIApplicationMain + 1132
18  Spotify                         0x000dd03a 0x9e000 + 258106
19  libdyld.dylib                   0x3a823ab2 tlv_initializer + 2

**Comment by Anders27** [comment]
Still the same problem with the latest release of the Spotify app version 4.8.0.1085 releases January 27.

It's impossible to file a bug report to Spotify. 

Is any Spotify developer reading anything here?

**Comment by JMSerruya** [comment]
Hi @Anders27 .

Yes, we read!

We will take a look and decide the priority of this issue.

Thanks for reporting.

**Comment by Anders27** [comment]
This problem is not fixed with the latest greatest Spotify app version 5.1.0.1019.
Come on, it should be super simple to fix that crash. It's a real showstopper, I can't update my app using the latest iOS SDK beta since I still have users on on iOS 7. And I hate looking a crash reports even though they are related to the Spotify SDK and not related to my own programming errors. Please fix this.

**Comment by Anders27** [comment]
This problem is still not fixed with the latest greatest Spotify app version 5.2.0.1206 released March 23 2016!

**Comment by DmytroAnkudinov** [comment]
@Anders27 Could you please verify if issue is still reproducible?

**Comment by DmytroAnkudinov** [comment]
No update from issue poster for more than two weeks. Closing the issue as fixed as functionality pertaining to the issue has been refactored and there are no reports confirming that issue could be reproduced.

If you can reproduce the issue on an iOS SDK Beta 25 or newer, please open a new issue.
