### ISSUE TITLE
Find out which track is playing from another app

### ISSUE THREAD

**Issue by alanPTK** [spotify/ios-sdk#574]
I'm developing an iOS app that needs to get the artist's name and the song's title from a track playing on Spotify in background.

This is the flow:

1) User is listening something on Spotify (web or native app)
2) User opens my app
3) App finds out which track is playing
4) Another track plays
5) App detects this and get the new track metadata

I looked in the Spotify SDK Api reference and found nothing.

Is it possible in the current SDK ? If not, is there any alternative ?

Thanks.

**Comment by stephenhandley** [comment]
@alanPTK you ever figure out how to do this?

**Comment by J0shuaw** [comment]
I am also very interested in this topic!

**Comment by alanPTK** [comment]
No, I'm still waiting for an answer..

**Comment by JUSTINMKAUFMAN** [comment]
Also interested in this.

**Comment by gesabo** [comment]
also interested in this

**Comment by arirawr** [comment]
Hey all, as mentioned in #418, this functionality is now offered in the [App Remote SDK](https://developer.spotify.com/documentation/ios-app-remote/).

The SDK allows your application to interact with the Spotify app running in the background on a user’s device. Capabilities include getting metadata for the currently playing track and context as well as issuing playback commands.

You can easily subscribe to the Spotify app's PlayerState like this:
```
func playerStateDidChange(_ playerState: SPTAppRemotePlayerState) {
  // view info about current playback in playerState object
  debugPrint("Track name: %@", playerState.track.name)
}
```

You can also control the Spotify app's playback directly: `appRemote.authorizeAndPlayURI(spotifyuri)`

Check out the full documentation here: https://developer.spotify.com/documentation/ios-app-remote/
And let us know if you have any feedback here: https://github.com/spotify/ios-app-remote-sdk

I'm going to close this issue, as this functionality will not be implemented in the SDK this issue tracker pertains to 🙂
