### ISSUE TITLE
isPlaying of SPTAudioStreamingController is not correct when interrupted by other music players

### ISSUE THREAD

**Issue by kraghavan-cc** [spotify/ios-sdk#575]
Usecase:
1. Use my app to start playing a track from spotify. The isPlaying BOOL of SPTAudioStreamingController returns YES.  (Expected)
2. Now go to background while music is still playing.
3. Launch a different music player example stitcher. Stitcher takes over the audio control and user will now hear stitcher (Expected)
4. Launch my app again and look for  isPlaying BOOL of SPTAudioStreamingController. It still returns YES whereas the expected result is NO because spotify has paused/stopped since stitcher is playing.

**Comment by Anders27** [comment]
You need to handle audio interruptions yourself as explained here:
https://github.com/spotify/ios-sdk/issues/202

**Comment by erdtman** [comment]
I will close this issue since #202 provides a solution to this as far as I can see.

If you disagree please reopen and update the issue with more information.
