### ISSUE TITLE
Corrupted data being returned in playlist track results

### ISSUE THREAD

**Issue by mhuusko5** [spotify/ios-sdk#576]
The playlist `spotify:user:benjaminwigum:playlist:4IKrSiKgbE1OebJmZ5ifiu` contains a track which has no available territories. This is normal/common – some tracks are no longer available and stay in playlists (albeit greyed out in the standard Spotify UIs).

In this case though, the track being returned by the spotify sdk has a URI of `spotify:local:::%5BRemastered+2010%5D+HOLA+BLANCO+-+Jay+Z+%26+Coldplay+-+Viva+La+Hova:159`, which is quite bizarre/not the format of `spotify:track:2345678`.
Worse yet, the artist object(s) returned for the track have mostly nil'd out fields (including URI).

**Comment by erdtman** [comment]
Sorry for not getting back earlier. In an attempt to get a better overview of the issues we are cleaning out some of the older issues. If this issue is still a problem in the latest SDK please reopen this issue or open a new one.
