### ISSUE TITLE
Logout and remove saved credential 

### ISSUE THREAD

**Issue by JanakLN** [spotify/ios-sdk#577]

**Comment by GabeJacobs** [comment]
@JanakLN you have to be more description about your issues. I don't work for Spotify but I care about making this project the best project possible and unless you are descriptive there is no way it can be improved.

**Comment by iGranDav** [comment]
I think @JanakLN wanted to ask about a feature which invalidate the current `access_token`

When I set the current `SPTAuth` session to `nil` on the default auth instance it does not invalidate it for example.
