### ISSUE TITLE
Authorization Error

### ISSUE THREAD

**Issue by psendyk** [spotify/ios-sdk#58]
I've been having trouble implementing the login part of an app I'm making. I followed the [Spotify iOS SDK Quick Start](https://developer.spotify.com/documentation/ios/quick-start/) but after the user inputs his credentials, the session initiation fails with an error: "Domain=com.spotify.sdk.login Code=1 "invalid_client"". Here's the code for reference: 

`class LoginViewController: UIViewController, SPTSessionManagerDelegate {

    var spotifyController: SpotifyController!
    
    override func viewDidLoad() {
        super.viewDidLoad()

        // Do any additional setup after loading the view.
    }
    
    @IBAction func loginButton(_ sender: Any) {
        let requestedScopes: SPTScope = [.playlistReadPrivate]
        self.sessionManager.initiateSession(with: requestedScopes, options: .default)
    }
    
    // AUTHORIZATION
    
    let SpotifyClientID = "[my client id]"
    let SpotifyRedirectURL = URL(string: "[my redirect url]")!
    
    lazy var configuration = SPTConfiguration(
        clientID: SpotifyClientID,
        redirectURL: SpotifyRedirectURL
    )
    
    lazy var sessionManager: SPTSessionManager = {
        if let tokenSwapURL = URL(string: "https://[my app].herokuapp.com/api/token"),
            let tokenRefreshURL = URL(string: "https://[my app].herokuapp.com/api/refresh_token") {
            self.configuration.tokenSwapURL = tokenSwapURL
            self.configuration.tokenRefreshURL = tokenRefreshURL
            self.configuration.playURI = ""
        }
        let manager = SPTSessionManager(configuration: self.configuration, delegate: self)
        return manager
    }()
    
    
    func sessionManager(manager: SPTSessionManager, didInitiate session: SPTSession) {
        debugPrint("success", session)
        performSegue(withIdentifier: "logInToListen", sender: self)
    }
    
    func sessionManager(manager: SPTSessionManager, didFailWith error: Error) {
        debugPrint("fail", error)
    }
    func sessionManager(manager: SPTSessionManager, didRenew session: SPTSession) {
        print("renewed", session)
    }
    
    func application(_ app: UIApplication, open url: URL, options: [UIApplication.OpenURLOptionsKey : Any] = [:]) -> Bool {
        self.sessionManager.application(app, open: url, options: options)
        return true
    }`

Has anyone encountered this error before or knows what might be causing it?

**Comment by santosgagbegnon** [comment]
I had a similar problem ["Domain=com.spotify.sdk.login Code=1 "invalid_grant".] I think it may be a bug within the Heroku token swap program, using: https://github.com/simontaen/SpotifyTokenSwap rather than the one in the Quick Start tutorial solved my issue.

**Comment by psendyk** [comment]
It solved the problem. Thanks!
