### ISSUE TITLE
iOS 9.3 beta 2 breaks loginWithSession method on LTE (and thus all playback)

### ISSUE THREAD

**Issue by GabeJacobs** [spotify/ios-sdk#582]
Steps to reproduce:

1) Install iOS 9.2 beta 2
2) Turn off wifi, be in LTE, 4G, or 3G
3) Authenticate with a premium Spotify account 
4) Try playing a song or calling the [SPTAudioStreamingController loginWithSession] method

We noticed that loginWithSession was not reaching its callback. It was not returning an error, but instead not returning at all. This means that when we tried to play a song, nothing would happen.

We have tried playing song from other apps that use the api and those songs do not play either. I'm sure it is a iOS 9.3 bug, but it's possible Apple will ship it anyway since it does not seem to effect other SDKs.

**Comment by bassntweeter** [comment]
@GabeJacobs I have tried to reproduce this with iOS 9.3 beta 3, however to no avail. Are you still able to reproduce this on iOS 9.3 beta 3?
Please reopen the ticket if you can reproduce it on beta 3.

**Comment by GabeJacobs** [comment]
@bassntweeter We updated to beta 3 and still getting this error. I could take a video showing multiple spotify iOS apps failing to play on LTE.

**Comment by GabeJacobs** [comment]
@bassntweeter Actually never mind! It's fixed!

**Comment by bassntweeter** [comment]
@gabejacobs ok. Again massive thanks for helping us out!

**Comment by GabeJacobs** [comment]
@bassntweeter Np! Still trying hard to reproduce that authentication error. Still getting it but I don't know why. The one thing I will say about the SDK is that the wifi handoff error is by far our biggest problem. We get complaints all the time and if I had to pick one single thing to fix, it would be that. Thanks all the work you've done! I'll keep trying to reproduce the authentication bug. Feel free to close this thread for good.

**Comment by GabeJacobs** [comment]
@bassntweeter P.S. is there anyway you could make an introduction to someone working on the Web API?

**Comment by bassntweeter** [comment]
@GabeJacobs Thanks for you feedback. That is actually exactly what we are focusing on. We have a version now that we not yet released publicly that is better on handling the wifi handoff, but it is not perfect yet. Maybe we will release an intermediate with slightly better handoff capabilities, but I would prefer to have it properly fixed before releasing it publicly.
