### ISSUE TITLE
BETA 14 in Xcode 7.2 showing hundreds of warnings

### ISSUE THREAD

**Issue by abrasdev** [spotify/ios-sdk#583]
Hi,

When I compile Spotify's BETA 14 framework I get a hundreds of warnings. I'm using the example project with the deployment target set to iOS 8.0. I tried different projects, but they all show the same warnings. 

![screen shot 2016-02-04 at 3 11 07 pm](https://cloud.githubusercontent.com/assets/10623550/12823151/a2804836-cb51-11e5-83f3-14f3fc50377d.png)

Any ideas when this is going to be fixed?

Thanks,

Abras

**Comment by barumrho** [comment]
I am seeing the same issue with beta 14.

**Comment by ahallora** [comment]
I was using Beta 14 alongside AFNetworking 2.6 (via cocoapods). When I updated AFNetworking to 3.0 all the warnings disappeared.... also related to the Spotify-framework. 

Magic. I guess. :confused:

**Comment by CVertex** [comment]
"Clean all" before rebuilding

**Comment by abrasdev** [comment]
"Clean all" doesn't help.

**Comment by CVertex** [comment]
I had an identical problem, clean worked for me... 

There are several issues on this board about this problem. Here's one, https://github.com/spotify/ios-sdk/issues/472

**Comment by mindgraffiti** [comment]
Clean and removing derived data did nothing for me. I see 12 warnings for Beta 14. I am using a deploy target of iOS 8.0 in my current project. Same warning types as @abrasdev 

`warning: /var/folders/4x/w_2gzbs13bg4lm0d51kn97680000gn/C/org.llvm.clang.juanma/ModuleCache/XKI7XJWMO0JO/Foundation-K7W1BMS6PHG4.pcm: No such file or directory`

**Comment by abrasdev** [comment]
@mindgraffiti grab the source code from this link: https://github.com/spotify/ios-sdk/archive/beta-14.zip

This was the only thing that fixed for me. This code is different from the one you get when you tap "Download Zip" on the main page.

Cleaning doesn't fix this bug.

**Comment by Frizlab** [comment]
@abrasdev Actually, downloading the archive from the tag (beta-14) downloads the beta-13, (both tags beta-13 and beta-14 point to the same commit), which is not BitCode compatible…

So our current option is either to have BitCode compatible code but hundreds of warnings when compiling, or a non-BitCode-compatible release, but without the warnings!

@JMSerruya Can we have a fix soon? If you are already BitCode compatible, it's just a matter of compilation options to avoid the warning; it should not take long!

Thanks you

**Comment by JMSerruya** [comment]
Derived data warnings were fixed in beta-15
