### ISSUE TITLE
Crashes related to Spotify.AudioStreaming

### ISSUE THREAD

**Issue by sridevi-cc** [spotify/ios-sdk#585]
We keep observing several crashes related to spotify audio streaming periodically.
Below is a crashlytics link for your analysis:
http://crashes.to/s/c12f6c04885

**Comment by CVertex** [comment]
I see a similar crash amongst my users too. Happens maybe once or twice a day..
I have no further information to add to it

**Comment by ozzotto** [comment]
Have you assigned a diskCache to SPTAudioStreamingController? If so, this seems to cause the crash when the cache tries to write in a passcode locked device when locked. To temporarily avoid crashing set diskCache property to nil.

**Comment by JMSerruya** [comment]
Hello!, This has been addressed in our Beta-15 release which is now ready for download!

https://github.com/spotify/ios-sdk/releases/tag/beta-15

Closing this and feel free to comment or re-open if you're still having issues!
