### ISSUE TITLE
Typos on a few methods

### ISSUE THREAD

**Issue by charleshkang** [spotify/ios-sdk#589]
![1](https://cloud.githubusercontent.com/assets/12476080/13017785/4dcf8970-d194-11e5-8d31-9bd259a6b3c5.png)
![2](https://cloud.githubusercontent.com/assets/12476080/13017786/4dd06570-d194-11e5-8cdd-5e43663fa81d.png)

createPlaylistForName and createRequestForCreatingPlaylistWithName both have an extra word, thought I would let you guys know!

This is my first issue, so please let me know how to make them better for next time.

**Comment by charleshkang** [comment]
Here's what they _should_ be! 
"Create a new playlist and add it to this playlist list"

"Get a user's playlist list"

**Comment by erdtman** [comment]
won´t fix
