### ISSUE TITLE
AppRemote calls crashing on pause/play

### ISSUE THREAD

**Issue by kingnoodle** [spotify/ios-sdk#59]
I'm creating a Swift app.  Connects to Spotify correctly, session manager establishes connection with following scopes [.appRemoteControl, .playlistReadPrivate].  AppRemote appears to connect, and authenticate and provides read functions (e.g. appRemote.playerAPI?.getPlayerState) but when I try to call appRemote.playerAPI?.pause it crashes:

2018-11-14 00:43:25.209 SpotifyTestbed[20662:5453791] AppRemote: Sending request: <SPTAppRemoteCallRequest: 0x15dcc280; id: 2, method: com.spotify.set_playback_speed>
2018-11-14 00:43:25.400 SpotifyTestbed[20662:5453791] +[NSError spt_transport_endOfStreamError]: unrecognized selector sent to class 0x3958f188
2018-11-14 00:43:25.401 SpotifyTestbed[20662:5453791] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '+[NSError spt_transport_endOfStreamError]: unrecognized selector sent to class 0x3958f188'

Any pointers to what's causing this appreciated.  I assume it's me somewhere, but the appRemote functions so I can't see where.

Thanks

**Comment by jackfreeman** [comment]
@kingnoodle  you need to add "-Objc" to your other linker flags. See step 2 under [dependencies](https://github.com/spotify/ios-sdk#add-dependencies)

**Comment by kingnoodle** [comment]
Thanks Jack, rookie error, forgot that step when I cloned a previous project.

So that stops the app crashing, but issuing the appRemote.playerAPI?.pause call still causes Spotify to error and disconnect.  So my didDisconnectWithError delegate function gets called now with the End of stream error as follows:

2018-11-14 19:21:32.263 SpotifyTestbed[21240:5608068] AppRemote: Sending request: <SPTAppRemoteCallRequest: 0x16587c20; id: 2, method: com.spotify.set_playback_speed>
2018-11-14 19:21:32.492 SpotifyTestbed[21240:5608068] AppRemote: Disconnected with error: Error Domain=com.spotify.app-remote.transport Code=-2001 "End of stream." UserInfo={NSLocalizedFailureReason=One of the streams has reached the end., NSLocalizedRecoverySuggestion=Reconnect to the Spotify app., NSLocalizedDescription=End of stream.}
didDisconnectWithError:Optional(Error Domain=com.spotify.app-remote Code=-1002 "Connection terminated." UserInfo={NSLocalizedRecoverySuggestion=Try to reconnect., NSLocalizedFailureReason=The Spotify app might have been suspended., NSLocalizedDescription=Connection terminated., NSUnderlyingError=0x166a0280 {Error Domain=com.spotify.app-remote.transport Code=-2001 "End of stream." UserInfo={NSLocalizedFailureReason=One of the streams has reached the end., NSLocalizedRecoverySuggestion=Reconnect to the Spotify app., NSLocalizedDescription=End of stream.}}})


Any suggestions as to why Spotify is disconnecting here?  It's suggesting I reconnect, but disconnecting with an error every time I PAUSE doesn't seem right!

Any thoughts appreciated
Philip

**Comment by jackfreeman** [comment]
@kingnoodle Can you give more specifics?

Device:
iOS Version:
Xcode Version:
Spotify Version:

Also does the issue occur with the provided NowPlayingApp as well?

**Comment by kingnoodle** [comment]
@jackfreeman Good question.  Got me thinking, so I just changed to run on iPhone SE running iOs 12.1 and my app works fine.  Play - Pause - Play - Pause all fine.

My problem setup is as follows:
Device: iPad an old model A1416 (MD328B/A if that makes sense)
iOS Version: 9.3.5
Xcode Version: 10.1
Spotify Version: 8.4.62.490 (latest compatible version for iOS version)

I thought Spotify iOS API is good for iOS 9.0 onwards...

**Comment by jackfreeman** [comment]
@kingnoodle The SDK will work with ios 9 but it will require an app switch to restart when paused on ios 9. iOS 10 and up will not cause an immediate disconnect when pausing however.

**Comment by kingnoodle** [comment]
@jackfreeman  Thanks for the quick response Jack :-)

Dose that mean it's a valid lifecycle for me to expect to receive an error when I pause and then reconnect when I want to resume play?

**Comment by jackfreeman** [comment]
@kingnoodle Yes, you should architect your app in a way that handles disconnects at any time. If paused for too long or the system requires additional resources and suspends Spotify in the background you may run into this on newer iOS version too.

**Comment by jackfreeman** [comment]
Please see our [Application Lifecycle Guide](https://developer.spotify.com/documentation/ios/guides/application-lifecycle/) for more info.
