### ISSUE TITLE
Getting blank authorization screen in Beta 14

### ISSUE THREAD

**Issue by zakmandhro** [spotify/ios-sdk#591]
Hi all, several users are reporting a **blank auth screen** (webview) as of SDK Beta 14. We have no change to authorization code since Beta 12, which used to work fine.

One caveat: We do not have a bundle ID because we are leveraging the webview auth flow.

Question: Is bundle ID "required" for Beta 14? It seems to work most of the time. If we do add bundle ID, is it going to impact live users with older version of SDK?

**Comment by bassntweeter** [comment]
@zakmandhro From beta 14 and forward the SDK will go for SSO and pop over to the Spotify App for authentication. Therefore you must register your bundle id. Registering the bundle id shall not impact live users with older versions of the SDK

**Comment by zakmandhro** [comment]
@bassntweeter thanks for confirming!
