### ISSUE TITLE
Is it possible to create an alarm clock app using the SDK to save and play from a user's playlist?

### ISSUE THREAD

**Issue by charleshkang** [spotify/ios-sdk#592]
I think a user has to be premium for this to work, but that's fine for now.

The app should be done by this week, and I wanted to make sure that this is indeed possible because I know you can pick music from your iTunes library, just want to make sure I will be able to do this with my Spotify playlists as well.

Any help is appreciated!

**Comment by Dmitry1007** [comment]
Why was this not answered?

**Comment by admarple** [comment]
I haven't confirmed that this was the case when charleskhang closed the question, but Section IV.1.15 of the [Spotify Developer Terms of Use](https://developer.spotify.com/developer-terms-of-use/) explicitly restricts the use of Spotify Content for alarms or alert tones.
