### ISSUE TITLE
Streaming works without requesting streaming scope on non-Verizon and non-AT&T devices

### ISSUE THREAD

**Issue by bass4aj** [spotify/ios-sdk#594]
If I request no scope, but the user has a premium account, then they can still stream music on ipods/ipads with wifi, and any iphones that are not Verizon or AT&T. Verizon and AT&T phones will not stream without a "streaming" scope on cellular or wifi. 

I am not sure which case is supposed to be correct, but they probably shouldn't be inconsistent.

**Comment by erdtman** [comment]
Is this still the case?
