### ISSUE TITLE
SPTPlaylistSnapshot createRequestForPlaylistWithURI doesn't give you the option to set the market

### ISSUE THREAD

**Issue by abrasdev** [spotify/ios-sdk#595]
Using the method createRequestForPlaylistWithURI from SPTPlaylistSnapshot returns tracks that are not playable on certain territories.

Since this method doesn't take the market parameter, isPlayable is always TRUE. So there is no way to check if the song is indeed playable or not. Unless you try to play it.

There needs to be a way to pass the market parameter to this API.

**Comment by guilhermeprudente** [comment]
I am facing the same issue currently. Also happens with playlistWithURI:session:callback - a market parameter is needed here!

**Comment by martinobonfiglioli** [comment]
Take a look here #528 if you want try a **workaround**. 

Definitely **+1** to manage 'market' parameter without workaround.

**Comment by erdtman** [comment]
We are deprecating the iOS-Metadata library.

The source code of the iOS-Metadata library has been released and can be found [here](https://github.com/erdtman/spotify-ios-metadata/). Spotify will not continue to maintain the released source code.

Either you can select to use the web-api directly or use the new open source iOS-Metadata library.

I will close this issue now.

We are sorry for the inconvenience that this creates, but looking back we think this is the best path forward.
