### ISSUE TITLE
I can't play more than 99 songs

### ISSUE THREAD

**Issue by djcors** [spotify/ios-sdk#596]
hi team, I'm trying to play playlist whit 221 songs

the code in the playlist view before pass to player view with segue:

`if(segue.identifier == "player") {
            if let PlayerViewController = segue.destinationViewController as? PlayerViewController {
                PlayerViewController.session = self.session
                PlayerViewController.track = self.arrary_tracks[item_select]
                PlayerViewController.uris = self.uris
                PlayerViewController.index = Int32(item_select)
            }
        }`

all data of track pass to player view correctly, but when i select a track with index of 100 or more, don't start this song.
another case is when i push next button to the 99 to 100 index song the player come back to first song

start player function:

`self.appDelegate.player?.playURIs(self.uris, withOptions: self.options, callback: { (error:NSError!) -> Void in`

* Options:

self.options.trackIndex = self.index
self.options.startTime = 0

But all song information is updated, artwork, name, artist, album, etc

Output:

correctly -> 99 or less
![worked index 98](https://cloud.githubusercontent.com/assets/3682936/13203984/e3b57518-d891-11e5-8334-bc913023c13c.png)

don't work -> 100 or more
![dont worked index 100](https://cloud.githubusercontent.com/assets/3682936/13203985/e3d1699e-d891-11e5-9351-5054be5fffa6.png)

printed
* Object
* Index
* Uri

**Comment by CVertex** [comment]
The 100 track play limit is documented on the playUris method, so the 100 max is by design.

I'd like this limit increased to something much higher too. 
I don't see why it's limited to 100

**Comment by elmateo487** [comment]
How is there no provided solution on how to handle more than 100 songs?

How is everyone doing it? It seems super messy to have to manage 99 songs at a time in different arraylists. In fact, this limitation is actually just ridiculous. If it is because they don't want to send more than 100 at a time, then provide a way to paginate.
