### ISSUE TITLE
App crashing

### ISSUE THREAD

**Issue by ZetrixWeb-iOS** [spotify/ios-sdk#598]
func getArtworkURL(track : SPTPartialTrack,completion: (success : Bool , imageURL : NSURL) -> Void)
    {
        MusicHelper.sharedInstance().spotifySessionCheckForPlaying
        SPTRequest.requestItemFromPartialObject(selectedTrackSPT, withSession: MusicHelper.sharedInstance().spotifySession, callback: {
            (error, obj) -> Void in
            if let object  = obj as? SPTTrack where error == nil
            {
                if let url = object.album.largestCover.imageURL where (object.album != nil && object.album.largestCover != nil) {
                    completion(success: true , imageURL : url)
                }else{
                    completion(success: true , imageURL : NSURL(string: "https://lh3.googleusercontent.com/OmKzDE7fPE9R2-DdXbL48_vQcHD7lH2Xxd__8jZVPkN8sQM49jGriA-Bm8Qk9z7SMVjb=s86")!)
                }
            }
        })
        
    }

Crash log
https://fabric.io/letsnurture8/ios/apps/com.queuemusic.queuemusic/issues/56cada94f5d3a7f76b036bbc

**Comment by DmytroAnkudinov** [comment]
Method `requestItemFromPartialObject` is not present in class `SPTRequest` as of Beta24.
