### ISSUE TITLE
How to detect that a spotify song won't play

### ISSUE THREAD

**Issue by jeffb6688** [spotify/ios-sdk#599]
I'm noticing that some Spotify tracks won't play. Some examples of tracks that won't play are:

    spotify:track:5Iterv0z4SsKPyX9kqXnWL
    spotify:track:6qObv6UQDq7kxZdloyY1xG
    spotify:track:68ZFbusYUVagHi4RMLrMGk

Obviously, this does not make for a good product experience if the player just stops. How can I programmatically detect that the Spotify player is hanging up trying to play one of these tracks? When I try to play these tracks, none of the audioStreaming delegate methods fire.

**Comment by abrasdev** [comment]
Each track has a property called isPlayable. If it's returning YES and it's not playing it is probably because it's not available on your country. So to avoid getting those kind of tracks, always send the user's country in your queries.

**Comment by jeffb6688** [comment]
thanks
