### ISSUE TITLE
Not playing the correct URI

### ISSUE THREAD

**Issue by ethanyqc** [spotify/ios-sdk#60]
Hi
I am using the ios sdk. I have all the connecting part done. However, running

```
fileprivate let trackIdentifier = "spotify:track:32ftxJzxMPgUFCM6Km9WTS"
appRemote.playerAPI?.play(trackIdentifier, callback: defaultCallback)
```
The track URI that is playing in Spotify is not the same as the trackIdentifier I declared. This happens too when I use the official demo project in GitHub(the uri playing is different than declared). Can you please help me? Thanks a lot.

**Comment by parth0072** [comment]
Hey @ethanyqc  have you found the solution ? I have same problem.
