### ISSUE TITLE
Firts time play song , after that not able to play song

### ISSUE THREAD

**Issue by ZetrixWeb-iOS** [spotify/ios-sdk#602]
-(void)playSpotifyTrack:(NSURL*)playURI trackDuration:(float)duration {
    [self stopTimer];
     SPTAuth *auth = [SPTAuth defaultInstance];
    id sessionData = [[NSUserDefaults standardUserDefaults] objectForKey:@"SpotifyOAuthSession"];
    self.spotifySession = sessionData ? [NSKeyedUnarchiver unarchiveObjectWithData:sessionData] : nil;
    
    if([self.spotifySession isValid]){
        NSLog(@"Valid session");
    }else{
        [auth renewSession:self.spotifySession callback:^(NSError *error, SPTSession *session) {
            if(error == nil){
                id sessionData = [NSKeyedArchiver archivedDataWithRootObject:session];
                [[NSUserDefaults standardUserDefaults] setObject:sessionData forKey:@"SpotifyOAuthSession"];
                [[NSUserDefaults standardUserDefaults] synchronize];
            }else{
                NSLog(@"%@",error);
            }
        }];
    }
    
    if (self.spotifyPlayer == nil ) {
        self.spotifyPlayer = [[SPTAudioStreamingController alloc] initWithClientId:auth.clientID];
        if(self.spotifyPlayer.playbackDelegate == nil){
            self.spotifyPlayer.playbackDelegate = self;
        }
        self.spotifyPlayer.diskCache = [[SPTDiskCache alloc] initWithCapacity:1024 * 1024 * 64];
        [self.spotifyPlayer loginWithSession:self.spotifySession callback:^(NSError *error) {
            if (error != nil) {
                NSLog(@"*** Logging in got error: %@", error);
                return;
            }else{
            
            [self.spotifyPlayer playURIs:@[ playURI ] fromIndex:0 callback:^(NSError *error) {
                if (error != nil) {
                    NSLog(@"*** Starting playback got error: %@", error);
                    return;
                }
            }];
            }
        }];
    }
    else {
        [self.spotifyPlayer playURIs:@[ playURI ] fromIndex:0 callback:^(NSError *error) {
            if (error != nil) {
                NSLog(@"*** Starting playback got error: %@", error);
                return;
            }
        }];
    }
    
    [self startSeekBar:duration];
    
    [[UIApplication sharedApplication] beginReceivingRemoteControlEvents];
}

**Comment by erdtman** [comment]
Sorry for not getting back earlier. In an attempt to get a better overview of the issues we are cleaning out some of the older issues. If this issue is still a problem in the latest SDK please reopen this issue or open a new one.
