### ISSUE TITLE
Have access to user playlists but can't find method to get user track from those playlists. 

### ISSUE THREAD

**Issue by charleshkang** [spotify/ios-sdk#605]
Tried looking at the methods on SPTRequest and SPTPlaylistTrack but I haven't found any methods to get a track from user playlists. 

Anyone know which method I should be using to get the tracks and get them to display in tableview? I was successful in displaying my playlists but getting my tracks is proving to be a huge problem.

**Comment by iGranDav** [comment]
You probably want to take a look at `SPTYourMusic` but please keep those issues for issues on the SDK not implementation issues. Use StackOverflow with the `spotify` tag for this.

**Comment by charleshkang** [comment]
Sorry @iGranDav! I've fixed the error and I'll close this now.
