### ISSUE TITLE
SPTAuthViewController importing from <Spotify/Spotify.h> instead of "Spotify.h"

### ISSUE THREAD

**Issue by joshdholtz** [spotify/ios-sdk#607]
I am using `0.13.0` of the SDK from CocoaPods. The import for the Spotify SDK from CocoaPods is `#import <Spotify-iOS-SDK/Spotify.h>` but the Spotify SDK is trying to import from `#import <Spotify/Spotify.h>` internally in `SPTAuthViewController.h` which does not exist. I changed that to `#import "Spotify.h"` locally (had to unlock the file from the code that was pulled down from CocoaPods and everything built fine.

I would gladly PR for this but I do not believe the source is available here for me to do that.

## Current code in 0.13.0
```objc
// SPTAuthViewController.h

#import <UIKit/UIKit.h>
#import <Foundation/Foundation.h>
#import <Spotify/Spotify.h>
```

## Should be...
```objc
// SPTAuthViewController.h

#import <UIKit/UIKit.h>
#import <Foundation/Foundation.h>
#import "Spotify.h"
```

**Comment by jakereps** [comment]
This SDK isn't supported through CocoaPods... The only ones up there are unofficial and haven't been updated in at least a year.

**Comment by joshdholtz** [comment]
:pensive:
