### ISSUE TITLE
not able to get playerState via getPlayerState()

### ISSUE THREAD

**Issue by shavik** [spotify/ios-sdk#61]
Hi, I am not able to get playerState.

I am trying to call playerApi's getPlayerState using Timer continuously after a second delay, it stops working after some time. Callback in not being called.

What's the better way to update the slider value of a track position.

Thanks

**Comment by jackfreeman** [comment]
@shavik this is the correct way to continuously grab player state and update the slider value. Do you have any more info related to this issue? Does the App Remote disconnect and print out an error? Can you provide a sample project?
