### ISSUE TITLE
SPTSearch.createRequestForSearchWithQuery only supports single query type

### ISSUE THREAD

**Issue by cluxton** [spotify/ios-sdk#611]
Hi, I came across a minor inconvenience when using `SPTSearch`. I was implementing a generic search similar to the one in the Spotify app (returns all artists, albums and tracks from a single query) .

 The `createRequestForSearchWithQuery` function only accepts a single SPTSearchQueryType. To get all 3 search results back I had to manually build the http request: `https://api.spotify.com/v1/search?q=SomeQuery&type=track,artist,album&limit=6`.

Would it be worthwhile adding another overload that accepts an array `[SPTSearchQueryType]`?

**Comment by erdtman** [comment]
We are deprecating the iOS-Metadata library.

The source code of the iOS-Metadata library has been released and can be found [here](https://github.com/erdtman/spotify-ios-metadata/). Spotify will not continue to maintain the released source code.

Either you can select to use the web-api directly or use the new open source iOS-Metadata library.

I will close this issue now.

We are sorry for the inconvenience that this creates, but looking back we think this is the best path forward.
