### ISSUE TITLE
openURL failure when user has unicode letters in their name: Hérmes

### ISSUE THREAD

**Issue by dnosk** [spotify/ios-sdk#616]
When deep linking to the Spotify app and back for authentication using openURL, I get this error: XXX://callback?error=unknown_error&error_description=Error%20Domain%3Dcom.spotify.hermes%20Code%3D126%20%22(null)%22

Not only does this not work when Hérmes tries it, it breaks openURL for all other users as well. It usually resets itself after a day.

Is there any way to encode special characters in this deep link?

**Comment by GabeJacobs** [comment]
https://github.com/spotify/ios-sdk/issues/505

**Comment by JMSerruya** [comment]
Duplicated. Thanks @gabe
