### ISSUE TITLE
All API routes returning 502

### ISSUE THREAD

**Issue by GabeJacobs** [spotify/ios-sdk#618]
https://api.spotify.com/v1/tracks/3z3bcIS2CBJ5pqWQjKPiIo

Search and all routes are down

**Comment by GabeJacobs** [comment]
seems to be every so often returning 502 now

**Comment by abrasdev** [comment]
+1

**Comment by iGranDav** [comment]
Since they are migrating their servers infrastructure this could be occur indeed.

https://news.spotify.com/us/2016/02/23/announcing-spotify-infrastructures-googley-future/

**Comment by ahallora** [comment]
https://twitter.com/SpotifyPlatform/status/706887995924811776 
https://twitter.com/SpotifyPlatform/status/706907241333579776
Should be fixed now. :)

**Comment by erdtman** [comment]
This should have been solved now so I will close this issue, if you have further problems please reopen the issue.
