### ISSUE TITLE
Removing track from saved tracks not reflected in desktop app

### ISSUE THREAD

**Issue by patrickbusch** [spotify/ios-sdk#619]
Removing a track with the request helper method (see https://developer.spotify.com/ios-sdk-docs/Documents/Classes/SPTYourMusic.html#//api/name/createRequestForRemovingTracksFromSaved:forUserWithAccessToken:error: ) from saved tracks does not reflect the change in the desktop app.

In the iOS app though when querying the API if the given track is still saved, the response is correct.

So this may be not an API problem in itself but would still be a problem if changes made from my app are not reflected in other apps.

Saving a track to your music, however, works perfectly fine.

**Comment by jakereps** [comment]
This seems to be an actual Spotify backend issue. A few nights ago I followed a playlist on my phone, and today it wasn't on my desktop app. My girlfriend also just tried to pull up a song on her laptop that she saved on her phone today to show me and it isn't in her saved songs on the desktop app even though playing the song on her phone shows her saved song list on her desktop app as currently playing (the speaker in the icon circle on the sidebar and a green bar next to it).

**Comment by patrickbusch** [comment]
Saving songs only works for me when using the createRequestForSavingTracks method, it does not work with the saveTracks method directly

**Comment by erdtman** [comment]
We are deprecating the iOS-Metadata library.

The source code of the iOS-Metadata library has been released and can be found [here](https://github.com/erdtman/spotify-ios-metadata/). Spotify will not continue to maintain the released source code.

Either you can select to use the web-api directly or use the new open source iOS-Metadata library.

I will close this issue now.

We are sorry for the inconvenience that this creates, but looking back we think this is the best path forward.
