### ISSUE TITLE
[Legal] Who can I contact to get clarification on the developer TOS?

### ISSUE THREAD

**Issue by Luke-k-dev** [spotify/ios-sdk#62]
I would like to add support for the Spotify platform in an iOS app. Who can I contact to ask some questions about this? The app is currently non-commercial but will be soon, it also does not deliver any streaming content and will offer features and capabilities not offered by Spotify. Thank you!

**Comment by arirawr** [comment]
Hey @Luke-k-dev - I'm not a lawyer and can't interpret our Terms of Service for you. If you are unsure about our terms, I recommend you consult legal counsel.

If you would like to apply for commercial approval, you can do so by creating a client ID on the [Spotify for Developers Dashboard](https://developer.spotify.com/dashboard) and selecting "Yes" when asked about commercial approval. This will prompt you to answer some more detailed questions about your integration, which will be sent to our partnerships team.

**Comment by natestrang** [comment]
@arirawr I realize this has been closed for some time now, but I found your response here and I'm having trouble locating the place where I can select "yes" when asked about commercial approval. Has this flow changed since this thread was closed? Thanks in advance

**Comment by arirawr** [comment]
@natestrang I haven't been at Spotify for over a year now and am not aware of the current processes.
