### ISSUE TITLE
`SPTTrack +trackWithURI:`, when hitting rate limit, returns malformed track but no error in callback

### ISSUE THREAD

**Issue by mhuusko5** [spotify/ios-sdk#621]
As title says, when hitting rate limit error, am being called back to with nil error, and a SPTPartialTrack with unfilled properties (debugging reveals its internal decoded json object has a value of `{ error: ... }`).

**Comment by michalumni** [comment]
I have had this problem as well.

**Comment by erdtman** [comment]
We are deprecating the iOS-Metadata library.

The source code of the iOS-Metadata library has been released and can be found [here](https://github.com/erdtman/spotify-ios-metadata/). Spotify will not continue to maintain the released source code.

Either you can select to use the web-api directly or use the new open source iOS-Metadata library.

I will close this issue now.

We are sorry for the inconvenience that this creates, but looking back we think this is the best path forward.
