### ISSUE TITLE
NativeScript plugin available now... If any suggestion improvements, please post on repo

### ISSUE THREAD

**Issue by NathanWalker** [spotify/ios-sdk#622]
https://www.npmjs.com/package/nativescript-spotify

![out](https://cloud.githubusercontent.com/assets/457187/13718867/0ce29c20-e7a3-11e5-8692-89645902ac6f.gif)

This can be closed shortly. Just wanted core Spotify team to know this is available now.
Thanks for an excellent and fun SDK!
Android support coming soon.

**Comment by loretoparisi** [comment]
:+1:

**Comment by charleshkang** [comment]
I looked at NativeScript but what exactly is this for? Allow people to build iOS and Android apps with JS?

**Comment by NathanWalker** [comment]
@charleshkang Yep. NativeScript uses pure `native` UI, can interface with all native classes on iOS and Android, the developer experience is excellent and the performance is fantastic.
