### ISSUE TITLE
didStartPlayingTrack is hit twice, tested

### ISSUE THREAD

**Issue by elmateo487** [spotify/ios-sdk#623]
I have tested this extensively,

If you play a set of uris with playUris, lets say uris 5 through 10, with nil options, and nil callback, then if you do playUris again with uris 7 through 15, since uri 7 was in the previous list of playing uris, didStartPlayingTrack is hit twice.

If you are playing uris 5 through 10, and you do another playUris, but you play uris 4-10, it will not hit twice.

In short, if you are playing a list of uris, and you play a new list of uris, if the first song of that new list is in the previous list of uris you were playing, didStartPlayingTrack is hit twice. If the first song is not in that list, didStartPlayingTrack is hit once.

The easy way to test this is to just call playUris on a set of Uris, then with a button press, play that same set of Uris again. It doesn't matter if you do a "stop" first.

**Comment by elmateo487** [comment]
also, passing nil into the callback in replaceUris will crash the app

**Comment by DmytroAnkudinov** [comment]
As of Beta24, `playURIs` is obsolete and has been removed from the SDK.
