### ISSUE TITLE
Some songs won't play even returning isPlayable TRUE

### ISSUE THREAD

**Issue by abrasdev** [spotify/ios-sdk#624]
Some songs simply won't play. You call playURIs:withOptions:callback: as usual, the callback returns with error = nil, but nothing happens.

The user's region is permitted to play the track.

You can use the following track to see the bug:

```
Title: First
Artist: Lauren Daigle
Album: How Can It Be
URL: spotify:track:1ZspFyNrkSPVwdPjKShOme
```

It happens with every app that uses Spotify SDK that I've tried.

Thanks,

Abras

**Comment by martinobonfiglioli** [comment]
This happened because of this #528

**Comment by abrasdev** [comment]
@martinobonfiglioli Unfortunately, that's not the case. As I said_ "The user's region is permitted to play the track"_. Which means that I'm already appending the `market` parameter.

This is a bug on their side. I **can** play this exact song on the Spotify app, but **can't** on any 3rd party app that uses this SDK.

**Comment by martinobonfiglioli** [comment]
@abrasdev how you can be sure to play that song for that country? 
Because without **market** parameter, `[SPTPartialTrack availableTerritories]` are also wrong

**Comment by abrasdev** [comment]
@martinobonfiglioli two reasons:

1. I'm sending the `market` parameter to the request. What makes Spotify only return the songs that are playable on the user's country.

2. This exact same song is playable on the Spotify app. When a song is not playable because of the market, the Spotify app won't play it either. It's not like it has "special credentials" that allows it to play songs from different market. It won't.

**Comment by DmytroAnkudinov** [comment]
As of Beta24, method `playUris` is obsolete and has been removed from the SDK. Issue is not reproducible on  the method `playSpotifyURI`
