### ISSUE TITLE
SPTAudioStreamingController playURIs method does not play albums

### ISSUE THREAD

**Issue by happyruss** [spotify/ios-sdk#626]
It appears that the playURIs method (the only method that is currently not deprecated to play something by URI) works fine for tracks and playlists, but not for albums. How can I play through an entire album?
       
        //works
       //NSURL *albumUrl = [NSURL URLWithString:@"spotify:track:58s6EuEYJdlb0kO7awm3Vp"];
      //NSURL *albumUrl = [NSURL URLWithString:@"spotify:user:synervoz:playlist:62O4AAhv5acaSfoQj5OtOg"];

        //does not work
         NSURL *albumUrl = [NSURL URLWithString:@"spotify:album:3rsvC3VIVtcxXy5UaZSX64"];

        [self.spotifyPlayer playURIs:@[ albumUrl ] fromIndex:0 callback:^(NSError *error) {
           //callback is only triggered and playing only begins when the URL points to a track, not an album
            if (error != nil) {
                NSLog(@"*** Starting playback got error: %@", error);
                return;
            }
        }];

Pulled latest framework today.

**Comment by happyruss** [comment]
Currently using this as a workaround until the issue is resolved or marked as by-design:

    [SPTAlbum albumWithURI:[NSURL URLWithString:albumUriString]
               accessToken:[SPTAuth defaultInstance].session.accessToken
                    market:nil
                  callback:^(NSError *error, id object) {
                      if (error != nil) {   }
                      NSLog(@"Got album %@", object);
                      SPTAlbum *fullAlbum = object;
                      
                    NSMutableArray *trackList = [[NSMutableArray alloc] init];
                      for (int i=0; i < fullAlbum.firstTrackPage.items.count; i++) {
                          SPTTrack *t = fullAlbum.firstTrackPage.items[i];
                          [trackList addObject:t.uri];
                       }

                      [self setupSpotifyPlayerForAutoplay];

                      [self.spotifyPlayer playURIs:trackList fromIndex:0 callback:^(NSError *error) {
                          if (error != nil) {
                              NSLog(@"*** Starting playback got error: %@", error);
                              return;
                          }
                          theTimer = [NSTimer scheduledTimerWithTimeInterval:1.0f target:self selector:@selector(updateCounter:) userInfo:nil repeats:YES];
                      }];
                  }];

**Comment by timbodeit** [comment]
+1

If this was indended by design, SPTAlbum should not have a `playableUri` method.

@happyruss Did any of the deprecated methods work for you? I see them crashing at `-[SPTAudioStreamingController expandUnsupportedURIs:callback:]`

**Comment by happyruss** [comment]
At the time they werent deprecated though i do remember i had to apply a workaround to get playlists to work using a weird algorithm i made up, though this should be commented as such I believe. Perhaps spotify updated thrir api and deprecated some stuff

**Comment by DmytroAnkudinov** [comment]
As of Beta24, `playURIs` is obsolete and has been removed from the SDK, while method `playSpotifyURI` allows playing albums.
