### ISSUE TITLE
Documentation improvement: addTracksToPlaylist() accepts array of NSURLs, too

### ISSUE THREAD

**Issue by brki** [spotify/ios-sdk#627]
I'm happy to see that this SPTPlaylistSnapshot method also accepts an array of `NSURL` for the `tracks` parameter (for my use case I already have the track ids; it doesn't make sense to fetch the SPTTrack objects).

I found this out by experimentation; it would be nice if the documentation says that it's possible.

Here is the beta-14 documentation:

```
/** Append tracks to the playlist.

 @note This operation is asynchronous on the server, it can take a couple of seconds for your changes to propagate everywhere after this operation has started.

 @param tracks The tracks to add, as `SPTTrack` or `SPTPartialTrack` objects.
 @param session An authenticated session. Must be valid and authenticated with the `SPTAuthPlaylistModifyScope` or `SPTAuthPlaylistModifyPrivateScope` scope as necessary.
 @param block The block to be called when the operation is started. This block will pass an error if the operation failed.
 */
-(void)addTracksToPlaylist:(NSArray *)tracks
               withSession:(SPTSession *)session
                  callback:(SPTErrorableOperationCallback)block;
```

**Comment by erdtman** [comment]
We are deprecating the iOS-Metadata library.

The source code of the iOS-Metadata library has been released and can be found [here](https://github.com/erdtman/spotify-ios-metadata/). Spotify will not continue to maintain the released source code.

Either you can select to use the web-api directly or use the new open source iOS-Metadata library.

I will close this issue now.

We are sorry for the inconvenience that this creates, but looking back we think this is the best path forward.
