### ISSUE TITLE
SPTAuthCallback, undeclared type

### ISSUE THREAD

**Issue by elmateo487** [spotify/ios-sdk#628]
After updating to Xcode 7.3, and swift 2.2, SPTAuthCallback cannot be used in a Swift project as it cannot be found. I have done a clean, reimported the latest spotify framework, and am unable to use SPTAuthCallback.

It should be noted that functions such as sptauth.renewSession that take an SPTAuthCallback closure, do still work. But the following doesn't

<img width="933" alt="screen shot 2016-03-22 at 12 54 33 am" src="https://cloud.githubusercontent.com/assets/5479251/13945200/adfeedc0-efc8-11e5-9868-b890c9a2a47f.png">

So to fix the issue I have to do the following, and let the type be inferred.

<img width="551" alt="screen shot 2016-03-22 at 12 57 44 am" src="https://cloud.githubusercontent.com/assets/5479251/13945267/27bf6400-efc9-11e5-857f-2c0ccc0f8d3f.png">

**Comment by michalumni** [comment]
Same problem +1.  Thanks for solution.

**Comment by DmytroAnkudinov** [comment]
Please create a new issue if the problem still persists at newer versions of XCode and Spotify frameworks Beta24 or newer.
