### ISSUE TITLE
Auth issue?

### ISSUE THREAD

**Issue by nathanandersen** [spotify/ios-sdk#629]
`-canOpenURL: failed for URL: "spotify-action://" - error: "(null)"`

Hello - I have ported over the ObjC iOS code into Swift for my app, and when I try and run everything with no changes, my app opens, then pops open Safari, I log into Spotify, then it returns and everything is ok... except no other functions have been called in sequence, the next `application(...` function was not called.

Does anyone have any insight about this bug?

**Comment by nathanandersen** [comment]
I have added `LSApplicationQueriesSchemes` as an `Array` to my `Info.plist`, with one element: `spotify-action`.

When I take this element out, I get the error: `..."spotify-action://" - error: "This app is not allowed to query for scheme spotify-action"`.

**Comment by evanfrawley** [comment]
did you end up getting this bug resolved?

**Comment by nathanandersen** [comment]
I believe that if you add your Bundle ID on the Spotify app settings, that should resolve this issue.

**Comment by evanfrawley** [comment]
okay, I've added that to the settings, but I still keep getting the `-canOpenURL: failed for URL: "spotify-action://" - error: "(null)"` when the `spotify-action` is in Info.plist and `"spotify-action://" - error: "This app is not allowed to query for scheme spotify-action"` when that string isn't. Before, in the simulator, I was able to log in via Facebook, but now I get an error that states that "Safari cannot open wab page because address is invalid". Do you have any suggestions?

**Comment by AlexChesters** [comment]
@evanfrawley I'm experiencing the same issue. Did you manage to resolve this?

**Comment by javierquevedo** [comment]
I have the same issue as well

**Comment by surayashivji** [comment]
I'm also having the issue - any fix?

**Comment by erdtman** [comment]
"spotify-action://" can only be used if the Spotify app is installed, if it is not installed you can push the user to install or user the SafariViewController

**Comment by yusufkamilak** [comment]
@erdtman as you said, when application installed, I can send user there and come back. But when app is not installed, how can I push user to download Spotify or show in Safari. I couldn't clearly understand what you mean with SafariViewController. Do i have to create a webview to show that url? Can't I send to safari as many applications do?

**Comment by burakakyalcin** [comment]
@yusufkamilak no you just have to create it programmatically like this

let safariVC = SFSafariViewController(url: auth.spotifyWebAuthenticationURL())
