### ISSUE TITLE
Not logging in through app

### ISSUE THREAD

**Issue by nathanandersen** [spotify/ios-sdk#631]
Hello,

I have followed the Spotify tutorial, but when I try and login, it redirects me to the Spotify app, and then returns with this error `Error Domain=com.spotify.auth Code=0 "unknown_error" UserInfo={NSLocalizedDescription=unknown_error}`, and does not authenticate.

Anyone know anything?

**Comment by nathanandersen** [comment]
Amusingly, now I get this error.

`Error Domain=com.spotify.auth Code=0 "invalid_app_identifier" UserInfo={NSLocalizedDescription=invalid_app_identifier}`.

However, when I delete the app, I am able to login.

**Comment by nathanandersen** [comment]
This only happens when the Spotify app is present.

**Comment by bassntweeter** [comment]
@nathanandersen Please register your bundle id at developer.spotify.com

**Comment by adamontherun** [comment]
@bassntweeter I'm getting this same error, about 1 out of 3 times when trying to login when I have the spotify app installed on my phone. I do have the bundle ID registered. anything you can suggest to help?
