### ISSUE TITLE
user-top-read scope

### ISSUE THREAD

**Issue by hauran** [spotify/ios-sdk#633]
I want to use the new web API  https://developer.spotify.com/web-api/get-users-top-artists-and-tracks.
Do I have to wait for a new ios sdk so the "user-top-read" scope is included or is there a way to bypass this?

**Comment by matijse** [comment]
I didn't test it, but I previously used the `playlist-read-collaborative` scope without it being included in one of the predefined scopes (just pass that string as a scope in the array).

So I assume you can just request `user-top-read` scope by passing that string in the array of requested scopes...

**Comment by erdtman** [comment]
The SDK does not contain a complete list of available scopes so yes you can send in additional scopes as strings.

I´m closing this issue for now, if you have further problems pleas reopen it with additional information.
