### ISSUE TITLE
getRelativeTrackMetadata:callback: is deprecated but is not reflected in the documentation

### ISSUE THREAD

**Issue by zach-cmiel** [spotify/ios-sdk#634]
The SPTAuthStreamingController method, getRelativeTrackMetadata:callback: is deprecated, but the documentation does not show that.

<img width="1022" alt="deprecated" src="https://cloud.githubusercontent.com/assets/16199352/14223694/3f59e486-f849-11e5-8d40-8b41248d358a.png">

I was able to figure out how to find the next and previous songs when the player isn't in shuffle mode, but when it is in shuffle mode, how would I be able to get the metadata for the next and previous songs?

**Comment by zach-cmiel** [comment]
This is the same with getAbsoluteTrackMetadata:callback:

**Comment by DmytroAnkudinov** [comment]
Obsolete method removed from SDK in Beta17.
