### ISSUE TITLE
Crashes on SPTSearch during connection loss

### ISSUE THREAD

**Issue by bass4aj** [spotify/ios-sdk#635]
Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'data parameter is nil'
*** First throw call stack:
(
	0   CoreFoundation                      0x0000000104f3fd85 __exceptionPreprocess + 165
	1   libobjc.A.dylib                     0x0000000106d5adeb objc_exception_throw + 48
	2   CoreFoundation                      0x0000000104f3fcbd +[NSException raise:format:] + 205
	3   Foundation                          0x00000001054374d1 +[NSJSONSerialization JSONObjectWithData:options:error:] + 67
	4   NoteVote                            0x000000010308bc7a +[SPTSearch searchResultsFromData:withResponse:queryType:error:] + 72
	5   NoteVote                            0x000000010308bfbf __81+[SPTSearch performSearchWithQuery:queryType:offset:accessToken:market:callback:]_block_invoke32 + 80
	6   libdispatch.dylib                   0x000000010b61bd9d _dispatch_call_block_and_release + 12
	7   libdispatch.dylib                   0x000000010b63c3eb _dispatch_client_callout + 8
	8   libdispatch.dylib                   0x000000010b6241ef _dispatch_main_queue_callback_4CF + 1738
	9   CoreFoundation                      0x0000000104e990f9 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
	10  CoreFoundation                      0x0000000104e5ab99 __CFRunLoopRun + 2073
	11  CoreFoundation                      0x0000000104e5a0f8 CFRunLoopRunSpecific + 488
	12  GraphicsServices                    0x000000010802ead2 GSEventRunModal + 161
	13  UIKit                               0x00000001057a6f09 UIApplicationMain + 171
	14  NoteVote                            0x0000000103003b72 main + 114
	15  libdyld.dylib                       0x000000010b67092d start + 1
	16  ???                                 0x0000000000000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException

This occurs when I try to call SPTSearch.performSearchWithQuery when there is no internet connection. According to Fabric, the crash happens on SPTSearch.m line 61. Is there a recommended way to handle this, or is this a bug within the SDK?

**Comment by bass4aj** [comment]
UPDATE: I saw there was a closed issue similar to this, #380, that was supposedly fixed in Beta 10. I am noticing this issue now in Beta 14

**Comment by Jackc415** [comment]
I still have this issue as well :/

**Comment by DmytroAnkudinov** [comment]
See #766

**Comment by DmytroAnkudinov** [comment]
Fixed in Beta25.
