### ISSUE TITLE
SPTAudioStreamingController currenTrackIndex incorrect

### ISSUE THREAD

**Issue by philiptmassey** [spotify/ios-sdk#636]
When using the methods in SPTAudioStreamingPlaybackDelegate, I've noticed that the currentTrackIndex is incorrect. After calling skipNext() and skipPrevious(), the index doesn't change and/or skips too far. Has anyone else been experiencing this?

**Comment by erdtman** [comment]
Sorry for not getting back earlier. In an attempt to get a better overview of the issues we are cleaning out some of the older issues. If this issue is still a problem in the latest SDK please reopen this issue or open a new one.

**Comment by bishalg** [comment]
@erdtman : can't find the property  `currentTrackIndex` on `SPTAudioStreamingController` on the latest SDK after update what is the alternative to get `currentTrackIndex` from `SPTAudioStreamingController`.
