### ISSUE TITLE
No artwork showed for user playlists

### ISSUE THREAD

**Issue by Kry256** [spotify/ios-sdk#637]
When i call _playlistsForUserWithSession:_ of **SPTPlaylistList** class, the query rightly give me a list of **SPTPartialPlaylist**.
The issue is that 

- **_images_**
- **_smallestImage_**
- **_largestImage_**

properties are empty or **nil** so I am not able to show any artwork.

**Comment by avazquezpr** [comment]
Hi @Kry256 
First you need to get the URL of the artwork, then you would use that URL to get the data and using that data you create a UIImage.

**Comment by Kry256** [comment]
Hi @avazquezpr,
yeah that is what I was doing. The problem now is that the URL isn't provided by the query that I mentioned before, for an unknown reason.
In particular I am using the **imageURL** property stored inside the **_SPTImage_** object, that is the object type of **smallestImage** and **largestImage**, properties of **_ SPTPartialPlaylist_** that is the object returned by the method _ playlistsForUserWithSession:_

**Comment by avazquezpr** [comment]
Ohh i see... Seems weird as i am doing something similar. This is my code in swift, tested and working. 
         
            // URL for the Album Artwork
            let playlistArtWorkURL = currentPlaylist.largestImage.imageURL
            
            // Data in AlbumArtwork
            let albumArtWorkData = NSData(contentsOfURL: playlistArtWorkURL)
            let localAlbumArtwork = UIImage(data: albumArtWorkData!)

**Comment by Kry256** [comment]
Which kind of object is _**currentPlaylist**_ ?

**Comment by avazquezpr** [comment]
SPTPartialPlaylist actually. I first call playlistsForUserWithSession: and in the callback method you get a page of playlists. I then make every playlist on that page an SPTPlaylistSnapshot, then SPTPartialPlaylist and after that is when i execute the code i wrote earlier.

**Comment by Kry256** [comment]
Same for me...and you see the artwork for all your playlist?

**Comment by avazquezpr** [comment]
Yup! Hope you can sort this out.. Really don't know what could be going on if we are almost doing the same thing.
