### ISSUE TITLE
SPTUser requestUser:withAccessToken:callback returns ProductTypeUnknown despite SPTAuthUserReadPrivateScope granted

### ISSUE THREAD

**Issue by mindgraffiti** [spotify/ios-sdk#638]
1. While using the Authorization Code Flow, simulate a premium user granting permission after login. 
2. Get a session by using `-[SPTAuth defaultInstance] handleAuthCallbackWithTriggeredAuthURL:callback:`
3. Make a request to `-requestUser:withAccessToken:callback`

_Actual:_
Returns an object that is SPTUser, with product type `SPTProductUnknown`.

_Expected:_
Returns an object that is SPTUser, with product type specified `SPTProductPremium`

_Notes:_
The correct product type for a user is reported when using the deprecated method `userInformationForUserSession:callback:` found in`SPTRequest`.

**Comment by brki** [comment]
For what it's worth, I use ``SPTAuth.requestCurrentUserWithAccessToken()``, and that does return the correct product type *for premium users*.  Unfortunately for free users it still returns ``SPTProductUnknown``, even if the ``SPTAuthUserReadPrivateScope`` has been granted.

**Comment by mindgraffiti** [comment]
@brki thanks! That's what I was looking for. `[SPTUser requestCurrentUserWithAccessToken:]` is working for returning the correct product type for premium users.

**Comment by bass4aj** [comment]
You should close the issue

**Comment by mindgraffiti** [comment]
Why? Neither method fully supports reporting all of the correct product types. This is still an issue.

**Comment by cjwhitsitt** [comment]
As of beta 17, I am still getting SPTProductUnknown from [SPTUser requestCurrentUserWithAccessToken:callback:] for a free user. I have yet to see a premium user trigger the unknown value in beta 17.

I'm requesting SPTAuthStreamingScope and SPTAuthUserReadPrivateScope.

**Comment by erdtman** [comment]
We are deprecating the iOS-Metadata library.

The source code of the iOS-Metadata library has been released and can be found [here](https://github.com/erdtman/spotify-ios-metadata/). Spotify will not continue to maintain the released source code.

Either you can select to use the web-api directly or use the new open source iOS-Metadata library.

I will close this issue now.

We are sorry for the inconvenience that this creates, but looking back we think this is the best path forward.
