### ISSUE TITLE
app crash: `attempt to insert nil in NSDictionary` on executing handleAuthCallbackWithTriggeredAuthURL:callback:

### ISSUE THREAD

**Issue by mindgraffiti** [spotify/ios-sdk#639]
- set the `tokenSwapURL`
- verify token swap service is running
- log in as a premium user, app successfully receives` auth_code` in the callback URL. Handle URL.
- make a cURL command with `auth_code` to verify Spotify Web API endpoint is working (it is)
- set up callback
```
SPTAuthCallback authCallback = ^(NSError *error, SPTSession *session) {
        if (error != nil) {
            DDLogError(@"Spotify Auth failed: %@", error.userInfo[@"NSDebugDescription"]);
            return;
        }
        
        [self requestSpotifyUserInfo:session];
    };
```
- then use this method to request a session:
`[[SPTAuth defaultInstance] handleAuthCallbackWithTriggeredAuthURL:url callback:authCallback];`

**_Before Spotify service makes an API request to the tokenSwapURL, the app crashes._**

```
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[0]'
*** First throw call stack:
(
	0   CoreFoundation                      0x0000000110f8dd85 __exceptionPreprocess + 165
	1   libobjc.A.dylib                     0x0000000114d34deb objc_exception_throw + 48
	2   CoreFoundation                      0x0000000110e8a23e -[__NSPlaceholderDictionary initWithObjects:forKeys:count:] + 318
	3   CoreFoundation                      0x0000000110e9c5bb +[NSDictionary dictionaryWithObjects:forKeys:count:] + 59
	4   MyApp VER                         0x000000010d29a057 __90-[SPTAuth _handleAuthCallbackWithTriggeredAuthURL:tokenSwapServiceEndpointAtURL:callback:]_block_invoke + 5682
	5   libdispatch.dylib                   0x00000001157abd9d _dispatch_call_block_and_release + 12
	6   libdispatch.dylib                   0x00000001157cc3eb _dispatch_client_callout + 8
	7   libdispatch.dylib                   0x00000001157b4b2f _dispatch_root_queue_drain + 1829
	8   libdispatch.dylib                   0x00000001157b4405 _dispatch_worker_thread3 + 111
	9   libsystem_pthread.dylib             0x0000000115b094de _pthread_wqthread + 1129
	10  libsystem_pthread.dylib             0x0000000115b07341 start_wqthread + 13
)
libc++abi.dylib: terminating with uncaught exception of type NSException
```

**Comment by mindgraffiti** [comment]
For what it's worth to anyone else reading this. 

If your service sends a malformed request to Spotify, Spotify sends a malformed response back to you. The malformed response, if your service is not catching and cleaning it, will get passed to the `handleAuthCallbackWithTriggeredAuthURL`, which then does no error checking and attempts to stuff the malformed response into a dictionary.

**Comment by cjwhitsitt** [comment]
This does seem to be fixed in beta 17. I manually modified the request and response going to and from my swap service to see what happens. If I change a value or the formatting (e.g., change the response body to "Not happening" instead of a proper dictionary), things seem to be filtered through the didFailToLogin: method as I would expect.

**Comment by woodenlabs** [comment]
I am facing that issue today. Is there any solution which you found?

**Comment by cjwhitsitt** [comment]
@woodenlabs I would only see this when your swap/refresh endpoint gave a bad response. Fixing the endpoints fixed the issue for me.
