### ISSUE TITLE
Need status on app submission

### ISSUE THREAD

**Issue by jennyhu19** [spotify/ios-sdk#64]
We submitted an app for approval 3 months ago and haven't heard back/don't know how to proceed. Can anyone help?

**Comment by arirawr** [comment]
Hi @jennyhu19 - if you applied through Spotify for Developers, your application has been sent to the partnerships team. We receive a huge volume of submissions and the approval process can take several months. I'm not able to provide updates on individual applications, but you will be contacted by the partnerships team directly if your application is approved.
