### ISSUE TITLE
Previous track still heard for a split second when stopping the track and playing a new track

### ISSUE THREAD

**Issue by sosale151** [spotify/ios-sdk#642]
When I play a song using the spotify sdk and then immediately play another track, for a brief moment the previous track is still heard. The old track plays for a split second before the new track can begin. 

I play the new song inside the callback block of the 'stop' method in the SPTAudioStreamingController.

Is there any way to prevent this from happening? This stutter of sorts causes an annoying user experience.

**Comment by brki** [comment]
Hi @sosale151 ,

Try pausing playback before stopping.  So: pause, stop, play.

This works for me.

**Comment by sosale151** [comment]
Yup, that's what I ended up doing. Seems hacky though.

**Comment by DmytroAnkudinov** [comment]
Issue is not reproducible as of Beta24.

**Comment by cameronehrlich** [comment]
Thanks @brki for the tip!

I still think the sdk still doesn't make obvious the proper way to switch to a new song.  Am I supposed to enqueu it and then advance to the next track? Am I supposed to pause, stop, and the play the next song?
