### ISSUE TITLE
Beta 15 Undefined Symbols

### ISSUE THREAD

**Issue by mhuusko5** [spotify/ios-sdk#647]
I was using this podspec (https://github.com/mhuusko5/Podspecs/blob/master/Spotify-iOS-SDK.podspec) to integrate all previous versions of the SDK successfully. As of today/beta 15, I can no longer build because of a bunch of undefined symbols (all of them).

Was wondering what's changed build/framework wise in beta 15?

**Comment by mhuusko5** [comment]
This is still present in beta 16. Any info on what has changed in your build process would be appreciated.

**Comment by mhuusko5** [comment]
Bump. @JMSerruya @bassntweeter?

**Comment by mabidakun** [comment]
Hi Guys,
Are there any plans to resolve this soon?

**Comment by DmytroAnkudinov** [comment]
Issue obsolete as of Beta24, as there is no more single Spotify Framework. If the issue still persists on separate frameworks, please file a new issue for every framework that you encounter this issue.
