### ISSUE TITLE
ERROR: missing required parameter

### ISSUE THREAD

**Issue by loretoparisi** [spotify/ios-sdk#648]
I often get this error in the sdk: `missing required parameter` coming inside the authentication controller.
I'm not sure which is the parameter it is referring to. How to debug this and/or get more logging info?

![cgt2hu7vaaashrj](https://cloud.githubusercontent.com/assets/163333/14597777/2f6a2424-054f-11e6-9a41-4eaa1657151d.jpg)

**Comment by NathanWalker** [comment]
I'm also seeing this. Would be great to know what parameter is missing?

**Comment by spkrka** [comment]
Thanks for the report, the error message should be improved now. Please report back if it isn't.

**Comment by DmytroAnkudinov** [comment]
No additional reports for 6 months, closing the issue.

**Comment by barra14** [comment]
I am receiving this issue but it includes "client_id"
