### ISSUE TITLE
[Question] Multiple SPTAudioStreamingControllers

### ISSUE THREAD

**Issue by ardaerzin** [spotify/ios-sdk#651]
Are we allowed to use multiple SPTAudioStreamingControllers in our apps? When I try having 2, one of them tends to fail to load tracks.

**Comment by ardaerzin** [comment]
found the answer in the [docs](https://developer.spotify.com/ios-sdk-docs/Documents/Classes/SPTAudioStreamingController.html)

**Comment by CVertex** [comment]
I found this the other day. Seems to contradict the docs
https://github.com/spotify/ios-sdk/issues/73

How are we supposed to support cross-fading between two tracks then?
