### ISSUE TITLE
SPTTrackProvider

### ISSUE THREAD

**Issue by ardaerzin** [spotify/ios-sdk#653]
I'm trying to implement my own trackprovider, but I'm having some issues. After the first failed attempt I found #200 and so now my track provider is like this

    var URIs : [NSURL] = []
    func tracksForPlayback() -> [AnyObject]! {
        return URIs
    }
    func playableUri() -> NSURL! {
        return nil
    }

I'm using the `playTrackProvider` method to play, but getting this error:

    Error Domain=com.spotify.ios-sdk.playback Code=5 "An unexpected argument value was passed to a function." UserInfo={NSLocalizedDescription=An unexpected argument value was passed to a function.}

And there are nothing with the songs. If I return one of the urls in the playableUri method, that song plays without any problems.

    func playableUri() -> NSURL! {
        return URIs.first!
    }

**Comment by DmytroAnkudinov** [comment]
Method `playTrackProvider` is absent from Beta24.
