### ISSUE TITLE
[Error] SPTAudioStreamingController repeat property & swift

### ISSUE THREAD

**Issue by ardaerzin** [spotify/ios-sdk#654]
ain't a love story

![screen shot 2016-04-20 at 12 19 57 am](https://cloud.githubusercontent.com/assets/5512833/14657479/67d95772-068e-11e6-940a-cf347c1f3765.png)

**Comment by mhuusko5** [comment]
self.`repeat` = false

**Comment by philiparpin** [comment]
Was this ever fixed?

**Comment by erdtman** [comment]
How to do this will change in beta 22
