### ISSUE TITLE
Searching for a specific artist's track Using Strings 

### ISSUE THREAD

**Issue by yacubelmi** [spotify/ios-sdk#656]
Hi I’m trying to search integrate spotify with my last fm. The last fm searches artist name, track and information of said artist. but also it also search information of artist. I’m looking into adding a play music feature which will play the selected track.  

http://prezi.com/egd8xoojwrun/?utm_campaign=share&utm_medium=copy 

I’ve made a presentation explaining  what i mean. I would welcome any ideas you may have.

**Comment by pbirdp** [comment]
The last.fm api can return the musicbrainz id for most artists and tracks. I match these with the echo nest api which accepts these id's as an input and can return Spotify uri's when you specify Spotify as one of the return buckets.

**Comment by yacubelmi** [comment]
ahh kool thanks, however i have looked up echo nest and i’m not overly familiar with it. Do you have an example how you could do this. I’m really new to this, sorry.

**Comment by pbirdp** [comment]
I am also new at this :)

With the mbid you got from last.fm you can for example get the top 100 tracks for an artist like this. 
In this case I used swiftyJSON (https://github.com/SwiftyJSON/SwiftyJSON) to parse the return data.

    let urlString: String
            urlString = "http://developer.echonest.com/api/v4/song/search?api_key=“your key”&artist_id=musicbrainz:artist:\(mbid)&sort=song_hotttnesss-desc&results=100&bucket=id:spotify&bucket=tracks&format=json"

 if let url = NSURL(string: urlString) {
                if let data = try? NSData(contentsOfURL: url, options: []) {
                    let json = JSON(data: data)
                    let tracks = json["response"]["songs"].arrayValue

// If successful we know have an array of tracks. To retrieve for example the spotify Uri for the first track in this array we can do 

  if  let track = tracksl[0]["tracks"][0]["foreign_id"].string


// To get information about the artist, take a look at the profile method in the echonest api. You can retrieve lots of information with its buckets for biographies, reviews, images etc.

**Comment by erdtman** [comment]
We are deprecating the iOS-Metadata library.

The source code of the iOS-Metadata library has been released and can be found [here](https://github.com/erdtman/spotify-ios-metadata/). Spotify will not continue to maintain the released source code.

Either you can select to use the web-api directly or use the new open source iOS-Metadata library.

I will close this issue now.

We are sorry for the inconvenience that this creates, but looking back we think this is the best path forward.
