### ISSUE TITLE
Podspec missing for 0.16.0 release

### ISSUE THREAD

**Issue by cnoon** [spotify/ios-sdk#659]
Hello!

Would it be possible to get a podspec built for the 0.16.0 release? I've spent a fair amount of time trying to put one together myself to no avail. It would really make this release easier to adopt for those of us using CocoaPods to pull in Spotify.

Thanks in advance!

**Comment by jakereps** [comment]
Are you asking for them to support CocoaPods in general, because this has never officially had a pod. Any pods listed on there, at least since libSpotify, have been unofficial and haven't been updated in well over a year.

**Comment by volksport** [comment]
We maintain a podspec that worked until beta 14, but beta 15 broke it.

**Comment by cnoon** [comment]
Thanks for the info @jakereps. I didn't realize the podspecs weren't officially supported by the Spotify team. I guess then that yes, I would like to formally request the Spotify framework support CocoaPods.

**Comment by cnoon** [comment]
@volksport, do you have any plans to create a podspec for beta 16? We need to pick up the bitcode changes, and I'm having a tough time with missing symbols when trying to modify the beta 14 podspec.

**Comment by mhuusko5** [comment]
Haven't had any luck integrating beta 15/16 with cocoapods (missing symbols). Put out podspecs for both (optimistically thinking framework/release at the source links might get fixed/replaced), but alas nothing yet. For now, it's manual integration..

**Comment by DmytroAnkudinov** [comment]
Added "playback" label as this is currently the only framework where enhancement would matter (in terms of this repository issue list) in the future.

**Comment by mhuusko5** [comment]
Think we can close this issue. We're far past beta 16, and I have updated the podspec for the latest few versions/since the missing symbols errors went away.
