### ISSUE TITLE
SPTAudioStreamingController playURIs method not playing all tracks of an array .

### ISSUE THREAD

**Issue by anupamwcities** [spotify/ios-sdk#661]
Hi, I'm using  **Spotify iOS SDK Beta version 15** in my application to play Spotify Tracks . 
```
[[APP_DELEGATE spotifyPlayer] playURIs:self.trackURIArray fromIndex:self.indexValue callback:^(NSError *error)
                           {                         
                               if (error==nil)
                               {  }                               
                           }];
```
after playing 2 or 3 tracks  **SPTAudioStreamingController**  stopped playing rest of tracks but returning `[[APP_DELEGATE spotifyPlayer] isPlaying] `is YES .

any help will be appreciated .

**Comment by erdtman** [comment]
playURIs has been removed, have a look at the latest beta for whats available now
