### ISSUE TITLE
Beta 15/16: SPTYourMusic savedTracksForUserWithAccessToken: SPTListPage response always uninitialised/items nil

### ISSUE THREAD

**Issue by mhuusko5** [spotify/ios-sdk#664]
^^^

**Comment by mhuusko5** [comment]
-ObjC linker flag fixed this

**Comment by mhuusko5** [comment]
@bassntweeter even with the above flag, this still happens occasionally (in beta 16).

**Comment by erdtman** [comment]
We are deprecating the iOS-Metadata library.

The source code of the iOS-Metadata library has been released and can be found [here](https://github.com/erdtman/spotify-ios-metadata/). Spotify will not continue to maintain the released source code.

Either you can select to use the web-api directly or use the new open source iOS-Metadata library.

I will close this issue now.

We are sorry for the inconvenience that this creates, but looking back we think this is the best path forward.
