### ISSUE TITLE
Genres field always empty?

### ISSUE THREAD

**Issue by StartNinja** [spotify/ios-sdk#665]
Hey guys I am currently working with the Spotify SDK. I implemented a Login and asking for permission to access the Users Playlist.

When the user gives me the permission I can access all their tracks and get all kinds of information out of them, but for some reason the genre seems to be empty most of the time. Is this just because Spotify tends to not give many artists genres or is this just hidden away somewhere, and I'm just not looking in the right place? So far I've checked the genres property in the album object and the one in the artist object.

**Comment by erdtman** [comment]
We are deprecating the iOS-Metadata library.

The source code of the iOS-Metadata library has been released and can be found [here](https://github.com/erdtman/spotify-ios-metadata/). Spotify will not continue to maintain the released source code.

Either you can select to use the web-api directly or use the new open source iOS-Metadata library.

I will close this issue now.

We are sorry for the inconvenience that this creates, but looking back we think this is the best path forward.
