### ISSUE TITLE
(Spotify iOS SDK) renewSession always return nil session

### ISSUE THREAD

**Issue by piffarettig** [spotify/ios-sdk#666]
I am building a small app on iOS that uses the Spotify SDK in order to make requests to its Web Api. The thing is, I am using the function STPAuth.renewSession to renew the token whenever I want to make a request. But for that function documentation says 'If no token refresh service has been specified the callback will return nil as session'. And that's what is happening to me. I'm always getting a nil 'renewedSession' (https://developer.spotify.com/ios-sdk-docs/Documents/Classes/SPTAuth.html#//api/name/renewSession:callback:)

I ve searched over there and found that this guy on this video uses a server that runs some script and he turns on using terminal, specifying a token refresh service URL on his app (https://www.youtube.com/watch?v=GeO00YdJ3cE) but nothing of that appears mentioned on the Spotify's iOS SDK tutorial..

How is that specifically done? Or Maybe there is an alternative way..

Thank you in advance :)

PS Also wrote on: http://stackoverflow.com/questions/36946703/spotify-ios-sdk-renewsession-always-return-nil-session

**Comment by ardaerzin** [comment]
I am using [this one](https://github.com/simontaen/SpotifyTokenSwap)

**Comment by piffarettig** [comment]
Thank you for your answer! But how do I do for example if i want to upload it to the appstore?

**Comment by ardaerzin** [comment]
I do not know of any problems regarding appstore, maybe because I haven't submitted my app yet. Any specifics?

**Comment by ksinghal** [comment]
I am having the same issue, I have tried the token swap server you posted, but I keep getting no error, and no session when I call the "renewSession" function. I also do not see any activity on my token swap server when i call that function, so I'm not sure if spotify is down or something?

**Comment by Voxar** [comment]
Hi. Have you set the `SPTAuth` properties `tokenSwapURL` and `tokenRefreshURL` to your token swap endpoint URI.

**Comment by arirawr** [comment]
Closing this - please see solution here: https://github.com/spotify/ios-sdk/issues/880
