### ISSUE TITLE
	 __59+[SPTRequest requestItemAtURI:withSession:market:callback:]_block_invoke

### ISSUE THREAD

**Issue by michalumni** [spotify/ios-sdk#670]
This error is occurring regularly in my code, please advise

Fatal Exception: NSInvalidArgumentException
data parameter is nil

**Comment by erdtman** [comment]
We are deprecating the iOS-Metadata library.

The source code of the iOS-Metadata library has been released and can be found [here](https://github.com/erdtman/spotify-ios-metadata/). Spotify will not continue to maintain the released source code.

Either you can select to use the web-api directly or use the new open source iOS-Metadata library.

I will close this issue now.

We are sorry for the inconvenience that this creates, but looking back we think this is the best path forward.
