### ISSUE TITLE
Issue while play new song

### ISSUE THREAD

**Issue by parthpatel1105** [spotify/ios-sdk#672]
I am playing a song. It seems fine. But if i have to play new song by clicking on new song then new song will take few seconds for buffering. But before start of new song , some catch of last song's played. Please let me know how can i solved this issue?

**Comment by GiorgiaMiQ** [comment]
I'm experiencing the same problem

**Comment by erdtman** [comment]
Sorry for not getting back earlier. In an attempt to get a better overview of the issues we are cleaning out some of the older issues. If this issue is still a problem in the latest SDK please reopen this issue or open a new one.
