### ISSUE TITLE
Alternative of deprecated methods/constants in Spotify IOS SDK beta 16

### ISSUE THREAD

**Issue by NPhadtare** [spotify/ios-sdk#673]
I am using Spotify IOS SDK beta 6. I have to upgrade my SDK to beta 16. As I observed that many methods/constants of beta 6 version are mark deprecated version beta 16. SDK version beta 16 only marks them deprecated but not suggests any alternative of these methods. Please suggest from where I found these. Please find below few methods that mark deprecated:

(void)userInformationForUserInSession:(SPTSession *)session callback: SPTRequestCallback)block
(void)albumWithURI:(NSURL *)uri session:(SPTSession *)session callback  (SPTRequestCallback)block
SPTAudioStreamingMetadataTrackName (Constant)
SPTAudioStreamingMetadataAlbumName (Constant)
SPTAudioStreamingMetadataArtistURI (Constant)
SPTAudioStreamingMetadataAlbumURI (Constant)
SPTAudioStreamingMetadataTrackURI (Constant)
SPTAudioStreamingMetadataArtistName (Constant)
currentTrackMetadata (Its dictionary)
(void)requestItemAtURI:(NSURL *)uri withSession:(SPTSession *)session callback:(SPTRequestCallback)block
(void)performSearchWithQuery:(NSString *)searchQuery queryType (SPTSearchQueryType)searchQueryType session:(SPTSession *)session callback:(SPTRequestCallback)block
(void)queueURI:(NSURL *)uri clearQueue:(BOOL)clear callback:(SPTErrorableOperationCallback)block
(NSURL *)loginURLForClientId:(NSString *)clientId withRedirectURL:(NSURL *)redirectURL scopes:(NSArray *)scopes;
(void)performSearchWithQuery:(NSString *)searchQuery queryType:(SPTSearchQueryType)searchQueryType session:(SPTSession *)session market:(NSString *)market callback:(SPTRequestCallback)block
(void)requestItemFromPartialObject:(id <SPTPartialObject>)partialObject withSession:(SPTSession *)session callback:(SPTRequestCallback)block

**Comment by erdtman** [comment]
In the latest beta most deprecated methods has been removed, have a look at it and come back if you have further questions.
