### ISSUE TITLE
trackMetadata is not being updated correctly

### ISSUE THREAD

**Issue by ardaerzin** [spotify/ios-sdk#674]
I use the `queueURIs(spotifyUris, clearQueue: true)` method to play a playlist which has only 1 track. It works fine for the first playback, I get the initial `audioStreaming(audioStreaming: SPTAudioStreamingController!, didChangeToTrack trackMetadata: [NSObject : AnyObject]!)` call with proper track information and when the playback finishes trackMetadata is replaced with nil.

However if I hit play for the same playlist and go thru `queueURIs` method, the player plays just fine but the metadata does not get updated and stays nil. Obviously the work around is playing a different track, so lets say if the playlists has 2 songs instead of 1, I never get this problem.

**Comment by d-kunin** [comment]
`trackMetadata` is not present since beta20. In beta20 please use 'didChangePlaybackState'
