### ISSUE TITLE
Apple rejection because of cover art in screenshots

### ISSUE THREAD

**Issue by zach-cmiel** [spotify/ios-sdk#678]
Hi, my app has been rejected by Apple because of the use of album cover art in my screenshots. Is it against Spotify's terms to use cover art in the screenshots? Do I have the right to display it in my screenshots?

**Comment by ahallora** [comment]
How do you present the cover art? Could you provide a screenshot?

**Comment by Jackc415** [comment]
My app was rejected too, this is one of my screenshots:

![4 7-inch-4](https://cloud.githubusercontent.com/assets/13828785/17465391/9c74599c-5caa-11e6-9baf-fb7f6b79600d.jpg)

**Comment by CPDigitalDarkroom** [comment]
I don't think you're allowed to use third-party album art in screenshots. I had the same rejection and the reviewer said Spotify may have a license to display them but that doesn't extend to other developers using the images to market their app. 

Using the images in the app was fine just not in the marketing screenshots.

**Comment by GabeJacobs** [comment]
We went through this as well and ended up not fighting and creating fake screenshots, as well as using album arts of friends we know. Better off just doing this than fighting a legal battle

**Comment by erdtman** [comment]
I will have to direct you to the terms of use. 
https://developer.spotify.com/developer-terms-of-use/

With that said I would recommend Gabes solution, to create fake images
