### ISSUE TITLE
Bad error message when fetching too many albums

### ISSUE THREAD

**Issue by timbodeit** [spotify/ios-sdk#679]
1. It is not documented in the iOS Framework, that `+albumsWithURIs: accessToken: market: callback:` on `SPTAlbum` has a maximum number of Album URIs, that you're allowed to pass.
2. When you are passing too many Album URIs, the number of URIs is not checked by the Framework. The resulting error message is terrible: `The data couldn’t be read because it isn’t in the correct format.`
- [ ] There should be documentation in SPTAlbum.h specifying the maximum number of URIs allowed for the method
- [ ] The method should check the number of URIs passed and if it is too high, automatically separate it into multiple network requests or throw an error explaining this without making a network request.

**Comment by Voxar** [comment]
Hi, Thanks for taking your time to report this!

I checked the [web-api docs](https://developer.spotify.com/web-api/get-several-albums/) which states the max is 20.

**Comment by erdtman** [comment]
We are deprecating the iOS-Metadata library.

The source code of the iOS-Metadata library has been released and can be found [here](https://github.com/erdtman/spotify-ios-metadata/). Spotify will not continue to maintain the released source code.

Either you can select to use the web-api directly or use the new open source iOS-Metadata library.

I will close this issue now.

We are sorry for the inconvenience that this creates, but looking back we think this is the best path forward.
