### ISSUE TITLE
Beta-16 (0.16.0) - Use of undeclared type 'SPT...'

### ISSUE THREAD

**Issue by mabidakun** [spotify/ios-sdk#680]
Hi,

When we use the CocoaPod (https://cocoapods.org/pods/Spotify-iOS-SDK), we see that this issue still exists in beta-16 (0.16.0).
The `Use of undeclared type ...` errors appear to relate to the `x86_64` architecture "seeming" to not be present in `libSpotify.a`
Inspecting `libSpotify.a`, we see that the architecture is there :-

```
$ file libSpotify.a

libSpotify.a: Mach-O universal binary with 4 architectures
libSpotify.a (for architecture armv7):	current ar archive random library
libSpotify.a (for architecture i386):	current ar archive random library
libSpotify.a (for architecture x86_64):	current ar archive random library
libSpotify.a (for architecture arm64):	current ar archive random library
```

So it looks like the symbols are not resolved because the lib is not found during linking.

Thus, we worked around the issue as follows:

1. Adding `$(PROJECT_DIR)/Pods/Spotify-iOS-SDK` to `FRAMEWORK_SEARCH_PATHS`
2. Adding `$(PROJECT_DIR)/Pods/Spotify-iOS-SDK/**` to `LIBRARY_SEARCH_PATHS`
3. Adding `-l"Spotify"` to `OTHER_LDFLAGS`

We are now able to link our application with libSpotify.a. 

Hope this helps.

**Comment by mhuusko5** [comment]
Ooo, interesting. Want to try adding those changes to https://github.com/mhuusko5/Podspecs/blob/master/Spotify-iOS-SDK.podspec?

**Comment by mhuusko5** [comment]
This seems to be back as of beta 20, even with a podspec using @mabidakun's fix.

**Comment by Voxar** [comment]
Hi, we are not actively supporting CocoaPods or any other manager at the moment. I guess our recent framework split broke the podspec quite significantly. 

I'll close this issue as a lot has happened since it was opened. 

Thanks @mhuusko5 for trying to keep the spec alive!

**Comment by mhuusko5** [comment]
The spec lives!
Have updated it for Beta 24 (split represented by subspecs), and the above errors are gone.
