### ISSUE TITLE
Consider making the SDK _partially_ open source.

### ISSUE THREAD

**Issue by dtrenz** [spotify/ios-sdk#681]
Hello Spotify iOS Team,

Please don't take this the wrong way, but it seems like you may be a bit overwhelmed by the volume of issues on this project. I'm certain that you are doing everything you can to try to address and prioritize features and improvements, but I had an idea recently that I wanted to pitch: 

**Consider making parts of this project open source.**

I completely understand the need to keep areas if the SDK — such as auth & audio streaming — closed and protected, but it seems to that the part of the SDK that is essentially an iOS client for the web API could be made open source.

The goal of making this area of the SDK open source would be that we (the OSS community) could help you maintain & resolve issues while also increasing parity between the iOS SDK and the web API endpoints; there are many web API endpoints that many would benefit from their availability in the iOS SDK.

My recommendation would be to convert this repo to some sort of "Spotify iOS Core SDK" and then start a new repo (in Swift!) that would complement and extend the "core" SDK with web service endpoint methods. Ideally, this might mean that an iOS project could add just use `Spotify/Core` pod if only using audio streaming is needed, or additionally add a `Spotify/WebAPI` pod. Or perhaps, there could be a `Spotify/Catalog` pod and a `Spotify/User` pod?

I'm interested in your thoughts on this. I really appreciate your service and I think many could benefit from this kind of shift, including Spotify. I'm sure many, many developers would be happy to contribute to a Spotify open source effort.

Thank You - Dan

**Comment by ardaerzin** [comment]
this might be interesting. many of us here work on temporary fixes/workarounds already, and with such an approach we can actually be doing some valuable work together.

**Comment by erdtman** [comment]
Hi @dtrenz 
I agree these libraries have not gotten the love they deserve.

We are looking at open sourcing parts of it. But as you mentioned we cannot open source all of it so we need to do some consolidation before such move is possible.

This is not a promise but I hope to give some more updates the upcoming months.

//Samuel

**Comment by mhuusko5** [comment]
Would love any updates on this topic. An open sourced core (the request/model layer) would be invaluable. With group support, filling in missing functionality from the Web API, and making any necessary changes for a Mac distribution, could be done in a matter of days. Everyone in the community would benefit greatly from these kinds of enhancements, and it could free up the internal Spotify team to continue forward with the more involved (and private) streaming related work (or just to take a few days off 😺 ).

**Comment by mxcl** [comment]
WAY easier to only support Apple Music in apps at this point.

**Comment by GabeJacobs** [comment]
@mxcl really? We've found an incredibly amount of trouble integrating Apple Music. Have you not had these issues? 

http://stackoverflow.com/questions/38918616/mpmusicplayercontroller-wont-interact-with-remote-controls

http://stackoverflow.com/questions/36834164/beginreceivingremotecontrolevents-not-triggering-events-for-apple-music/38918111?noredirect=1#comment65193375_38918111

Sorry to bring this off-topic. Maybe message me directly if you want to discuss them (gabe@cymbal.fm)

**Comment by sajsanghvi** [comment]
@GabeJacobs 100%. More than just those issues. Queueing often doesn't work. If you use Apple Music within Shazam etc. it is completely broken.

**Comment by Voxar** [comment]
Hi. It's not such an overwhelming amount of issues but an underwhelming amount of manpower put on the Mobile SDKs. We have however been pushing to remedy the situation lately and the recent framework split is indeed a preparation to open up parts of it.

Speaking of that, today we celebrate the source release of the [Spotify Authentication Library for Android](https://github.com/spotify/android-auth)!

**Comment by erdtman** [comment]
We are deprecating the iOS-Metadata library.

The source code of the iOS-Metadata library has been released and can be found here. Spotify will not continue to maintain the released source code.

Either you can select to use the web-api directly or use the new open source iOS-Metadata library.

I will close this issue now.

We are sorry for the inconvenience that this creates, but looking back we think this is the best path forward.
