### ISSUE TITLE
Make old versions of song files available

### ISSUE THREAD

**Issue by willcray** [spotify/ios-sdk#682]
Please consider providing access to old versions of songs after artists revise them. For instance, on Kanye's "Life of Pablo", he edited the song "Waves" several times. I would like to be able to "get" the old versions, as well as the current version. Thanks for your consideration.

**Comment by GabeJacobs** [comment]
The artist owns the media, not spotify

**Comment by d-kunin** [comment]
It is not technically possible at the moment.
