### ISSUE TITLE
Audio analysis on entire file

### ISSUE THREAD

**Issue by knagle** [spotify/ios-sdk#685]
Algoriddim Djay 2 appears to have direct access to an entire song file almost immediately once I select a Spotify track for streamed playback. The software then appears to perform analysis such as beat tracking, which takes about 5-7 seconds, and presents you with a coloured waveform that you can zoom in and investigate/manipulate during playback.

For our app we are wanting to have similar access to the song file, but the most audio data we can get access to is the `audioFrames` in `attemptToDeliverAudioFrames` if we subclass `SPTCoreAudioController`. Is there another way to access the Spotify audio file? We want to perform our own custom audio analysis, separate to the 'audio-features' information already available from the Spotify API.

**Comment by shorttermproject** [comment]
I Second this, I am developing Beat Slice for iOS and would like to add the same capabilities.

**Comment by laura-digio** [comment]
I need to develop something similar in my app too. Any guidance regarding this topic would be greatly appreciated.

**Comment by loretoparisi** [comment]
@knagle why you want to perform further analysis on the device if you have the whole audio data from the spotify [audio-features](https://developer.spotify.com/web-api/get-audio-features/) api that gives you access to the `analysis_url`?

**Comment by hughrawlinson** [comment]
Hi! This isn't a feature of the iOS SDK, but you can use the same token that you use with iOS SDK to make a request to the [Audio Analysis](https://developer.spotify.com/web-api/get-audio-analysis/) endpoint of the Spotify Web API to get the full analysis for a song by its ID. We won't be able to provide access to the raw audio file.
