### ISSUE TITLE
tvOS SDK?

### ISSUE THREAD

**Issue by hfisselier** [spotify/ios-sdk#688]
Hello

We develop a musical application on AppleTV. We need to play Spotify tracks on AppleTV (without AirPlay) but it seems that there is no public SDK for tvOS. Have you one in your near roadmap?

Best regards

Hubert

**Comment by ozzotto** [comment]
+1

**Comment by loretoparisi** [comment]
I think that this is largely discussed [here](https://github.com/spotify/ios-sdk/issues/443).

**Comment by DmytroAnkudinov** [comment]
Closed as duplicate.
