### ISSUE TITLE
Spotify App itself crashes on iOS7 during oAuth

### ISSUE THREAD

**Issue by matijse** [spotify/ios-sdk#689]
When using the auth flow via `SPTAuthViewController`, the user is directed to the Spotify App when it has that app installed. On iOS 7 devices (iPhone 4), this results in the Spotify App itself crashing, so the user is unable to connect their account to my app...

If there is anything I can do to debug or logs I can send to help you fix this, please let me know.

**Comment by Anders27** [comment]
I've reported this bug several times
https://github.com/spotify/ios-sdk/issues/643

and checked every new update of the Spotify app but the bug is still there.
It should be dead simple to fix.
My solution for now is to use SDK Beta 12 (which contains other bugs but doesn't crash the Spotify app).

**Comment by matijse** [comment]
Unfortunately using an old SDK will not be an option anymore, since the old SDK's don't have IPv6 support, which is now required by Apple (see #676)

**Comment by Anders27** [comment]
I've updated my app twice using SDK beta 12 since this IPv6 thing came up, my app passed approval both times, the last time was yesterday.
The Apple review process is completely arbitrary.

**Comment by DmytroAnkudinov** [comment]
SPTAuthViewController has been deprecated in Beta25 and should not be used anymore, as it will be removed in the subsequent releases. Please use SFSafariViewController instead.
