### ISSUE TITLE
Publish a commercial use app

### ISSUE THREAD

**Issue by lorenzoferrante** [spotify/ios-sdk#69]
Hi there, 
I’m trying to make a commercial use iOS app. I’ve already sent the app in review by creating a commercial app in the Spotify Developer Dashboard, but I got no response.
How can I talk to someone who can review my app? 
Thanks a lot.

**Comment by arirawr** [comment]
Hi @lorenzoferrante - if you applied through Spotify for Developers, your application has been sent to the partnerships team. We receive a huge volume of submissions and the approval process can take several months. I'm not able to provide updates on individual applications, but you will be contacted by the partnerships team directly if your application is approved.
