### ISSUE TITLE
Access currently playing track from any device

### ISSUE THREAD

**Issue by steve228uk** [spotify/ios-sdk#690]
Hello!

We're trying to build something that will access the currently playing track on say a Mac and display the track info on an iPhone. Is this something that's possible?

I've tried using `SPTAudioStreamingController` but that seems to only work with what's playing locally.

Any help is appreciated.

Thanks!

**Comment by erdtman** [comment]
There is currently no solution to get what is playing outside your app.

**Comment by sajsanghvi** [comment]
Use the apple script Api to get the current song from your Mac and then you can send it to the iPhone client

**Comment by d-kunin** [comment]
The feature you've mentioned is called Spotify Connect and currently is not available in the mobile SDK. 
:(

**Comment by stephenhandley** [comment]
@d-kunin is there any ETA for this being released in the mobile SDK?

**Comment by nguyenchr** [comment]
does anyone know how apps like musixmatch do this if it's not possible to get this information?

**Comment by arirawr** [comment]
@nguyenchr I'm not sure about the details of Musixmatch's implementation, but you can use the Web API to do this: https://beta.developer.spotify.com/documentation/web-api/reference/player/

Though there are no functions built into the iOS SDK, you can use the same access token to make HTTP requests to the Connect Web API endpoints.

**Comment by nguyenchr** [comment]
@arirawr thanks :)
sounds workable for me

**Comment by jkarlsso** [comment]
@nguyenchr Tip: make sure you read the license agreement needed for the
access carefully. I found it too restrictive.
