### ISSUE TITLE
Get 'code' from iOS SDK

### ISSUE THREAD

**Issue by cbrandberg** [spotify/ios-sdk#691]
According to the Web API 'Authorization Code Flow' I need a 'code' to be able to refresh my token.
Is there any possibility to get the 'code' from the iOS SDK?

**Comment by loretoparisi** [comment]
@cbrandberg what you want is like:

```objective-c
NSURL *loginURL = [SPTAuth loginURLForClientId:kSpotifyClientId withRedirectURL:[NSURL URLWithString:kSpotifyCallbackURL]
                                            scopes:[self getAccessTokenScopes]
                                      responseType:@"code"];
```

**Comment by cbrandberg** [comment]
I couldn't find the scope... but I tried with this code: 
     
  ```
 let loginURL = SPTAuth.loginURLForClientId(kClientID, withRedirectURL:NSURL(string:kCallbackURL), scopes: [SPTAuthSessionUserDefaultsKey] , responseType: "code")
        
        SPTRequest.requestItemAtURI(loginURL, withSession: session) { (error: NSError!, object: AnyObject!) in
            if error != nil {
                print("failed to get users playlists with error: \(error)")
            }
            print("code: \(object)")
        }
```

But I get this error:
Undefined symbols for architecture arm64:
  "_SPTAuthSessionUserDefaultsKey", referenced from:
      Spotify.SpotifySession.getSpotifyCode () -> () in SpotifySession.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by cbrandberg** [comment]
I can't find that scope :https://developer.spotify.com/web-api/using-scopes/
In which header file is that located?

**Comment by loretoparisi** [comment]
The docs is [here](https://developer.spotify.com/ios-sdk-docs/Documents/Classes/SPTAuth.html#//api/name/loginURLForClientId:withRedirectURL:scopes:responseType:). The one you were looking for was the web api, while this one is the iOS SDK.

**Comment by cbrandberg** [comment]
You're correct, but the scopes in the iOS SDK are representing the ones for the Web API. The only scopes available in "SPTAuth.h" for iOS SDK are the following:

```
 /** Scope that lets you stream music. */
FOUNDATION_EXPORT NSString * const SPTAuthStreamingScope;

/** Scope that lets you read private playlists of the authenticated user. */
FOUNDATION_EXPORT NSString * const SPTAuthPlaylistReadPrivateScope;

/** Scope that lets you modify public playlists of the authenticated user. */
FOUNDATION_EXPORT NSString * const SPTAuthPlaylistModifyPublicScope;

/** Scope that lets you modify private playlists of the authenticated user. */
FOUNDATION_EXPORT NSString * const SPTAuthPlaylistModifyPrivateScope;

/** Scope that lets you follow artists and users on behalf of the authenticated user. */
FOUNDATION_EXPORT NSString * const SPTAuthUserFollowModifyScope;

/** Scope that lets you get a list of artists and users the authenticated user is following. */
FOUNDATION_EXPORT NSString * const SPTAuthUserFollowReadScope;

/** Scope that lets you read user's Your Music library. */
FOUNDATION_EXPORT NSString * const SPTAuthUserLibraryReadScope;

/** Scope that lets you modify user's Your Music library. */
FOUNDATION_EXPORT NSString * const SPTAuthUserLibraryModifyScope;

/** Scope that lets you read the private user information of the authenticated user. */
FOUNDATION_EXPORT NSString * const SPTAuthUserReadPrivateScope;

/** Scope that lets you get the birthdate of the authenticated user. */
FOUNDATION_EXPORT NSString * const SPTAuthUserReadBirthDateScope;

/** Scope that lets you get the email address of the authenticated user. */
FOUNDATION_EXPORT NSString * const SPTAuthUserReadEmailScope;

FOUNDATION_EXPORT NSString * const SPTAuthSessionUserDefaultsKey;
```

**Comment by loretoparisi** [comment]
@cbrandberg wait, are you talking about access token scopes or the `code` response type in the oAuth flow?

**Comment by cbrandberg** [comment]
I think I need to explain my problem in more details...

So, I'm currently using the SPTAuthViewController to enable login for the users. 
I don't want the login-process in Safari, I want it within the application, as it currently is.

The problem I have is to refresh my token thereafter.
I have created an amazon web-service lambda function, which takes, according to the Web API, a 'code'. So I don't want to create two URLs, which is the approach described inhttps://github.com/simontaen/SpotifyTokenSwap, rather send in the 'code' which the iOS SDK is extracting (somehow) since this parameter also is needed in this github approach.

**Comment by erdtman** [comment]
Not sure I understand your problem, is it that you have to create two back-end endpoints? you could create one and differentiate on the input parameters or a query parameter e.g.
https://example.com/swapandrefresh?type=swap and https://example.com/swapandrefresh?type=refresh

**Comment by erdtman** [comment]
Since there has been no further comments here I will close this issue. If this still an issue please reopen.
