### ISSUE TITLE
Enhancement request - Make session duration longer

### ISSUE THREAD

**Issue by Anders27** [spotify/ios-sdk#693]
Why must the token expire every hour? 

I’m mainly a C++ audio developer so maybe I don’t even understand why it’s needed and what it does but if it could last for a couple of hours or maybe 5-6 hours, then the average user would never experience FAS or the brief flash of the SPTAuthViewController.

Please make the session last longer.

**Comment by sethmills21** [comment]
totally agree, every hour is crazy. If anyone is going to build a meaningful app on top of this sdk - the expiration should at least be 30 days IMO

**Comment by mhuusko5** [comment]
Add a token renew/refresh URL, and you can renew the token automatically without user intervention.

**Comment by loretoparisi** [comment]
+1 this should be `86400` secs. By the way, the only meaningful solution with `3600` sec expiration so far, is to update the `access_token` server-side using the `refresh_token`. See [Requesting access token from refresh token](https://developer.spotify.com/web-api/authorization-guide/#authorization-code-flow)

**Comment by sethmills21** [comment]
oh word @mhuusko5? OK, that makes it much better :)

**Comment by erdtman** [comment]
As mentioned earlier the solution to this is to use the refresh_token. 
This is nothing that we will change so I will close this issue for now.
