### ISSUE TITLE
API abstraction alternatives for tokenSwapURL and tokenRefreshURL

### ISSUE THREAD

**Issue by matsev** [spotify/ios-sdk#694]
Would it be possible to provide other abstractions than `tokenSwapURL` and `tokenRefreshURL` when executing the [Authorization Code Flow](https://developer.spotify.com/web-api/authorization-guide/#authorization-code-flow)?

Currently, it is not possible to implement a server side "swap" and "replace" service hosted on [AWS Lambda](https://aws.amazon.com/lambda/), [Google Cloud Functions](https://cloud.google.com/functions/), [Azure Functions](https://azure.microsoft.com/en-us/services/functions/) or similar serverless platforms. The reason being is that the iOS SDK API requires that a http based server is used, since it dictates the use of `tokenSwapURL` and `tokenRefreshURL`. One suggestion to facilitate these services is to update the API to pass just the data exchanged by these URLs. 

In case of `swap` the client need the a way to get the `code`, `redirect_uri` and `client_id` parameters and a way to pass in the resulting `access_token`, `token_type`, `scope`, `expires_in` and `refresh_token` values after the call to the backend service. 
Likewise, in the `refresh` use case, the client asks for the `refresh_token` (not strictly necessary since it could keep a reference to it outside of the SDK) and pass in the resulting `access_token`, `token_type`, `scope` and `expires_in` values after the server refresh.

**Comment by erdtman** [comment]
There are no plans to do the suggested change.

If you cannot work with an HTTP back-end for the swap and refresh I would recommended to implement the raw OAuth flows. There are also dedicated OAuth libraries that could be used.
