### ISSUE TITLE
Improved server API for tokenSwapURL and tokenRefreshURL

### ISSUE THREAD

**Issue by matsev** [spotify/ios-sdk#696]
After playing around with the iOS SDK for some time, I believe that the server API can be improved. Preferably, the iOS SDK should not be tied to the data transfer protocol (as I suggested in #694). However, if you still HTTP based requests I think that the SDK should make the following requests:

```
https://my-server.com/swap
Content-Type: application/json
{
  "client_id": "abc123",
  "code", "secret",
  "redirect_uri": "http://my-app.com/callback"
}
```

```
https://my-server.com/refresh
Content-Type: application/json
{
  "refresh_token", "refresh"
}
```

Motivation:
- JSON is pretty much the defacto standard when developing mobile apps. 
- By providing the `client_id` as a parameter the same server instance can serve multiple Spotify Apps with different client ids (currently, one must deploy one server instance for each clilent id).
- The `redirect_uri` must be provided as part of the initial authorization request to https://accounts.spotify.com/authorize , so the client must have this information. By also requiring (and validating) in step [4. Your application requests refresh and access tokens](https://developer.spotify.com/web-api/authorization-guide/) introduce an unnecessary source of errors. Instead, if the SDK provides the parameter, the server implementation can just pass through the value when calling the https://accounts.spotify.com/api/token endpoint.

**Comment by erdtman** [comment]
Thanks for the feedback. 

You can work around the one server for multiple clients by including the client_id in the path, e.g. https://my-server.com/swap/<client_id>, you could even include the redirect_uri in the path, e.g. https://my-server.com/swap/<client_id>/<urlencode(redirect_uri)>

So for now we will not do any update.
