### ISSUE TITLE
Pre-loading track // Crossfading

### ISSUE THREAD

**Issue by ADPuckey** [spotify/ios-sdk#699]
I'm attempting to perform a cross-fade in my app.  This issue was brought up earlier [here](https://github.com/spotify/ios-sdk/issues/73) in which iKenndac referenced his own answer on [this StackOverflow question](http://stackoverflow.com/questions/15857209/how-do-i-audio-crossfade-using-cocoalibspotify).  He suggests to use `preloadTrackForPlayback:callback:`, which doesn't exist in the new iOS SDK. 

I attempted to use CocoaLibSpotify code to subclass `SPTAudioStreamingController` and use the preload track method.  I'm hitting a dead end because I can't seem to negotiate what I should pass for the `aSession` parameter to `-(NSInteger)session:(id <SPSessionPlaybackProvider>)aSession shouldDeliverAudioFrames:(const void *)audioFrames ofCount:(NSInteger)frameCount streamDescription:(AudioStreamBasicDescription)audioDescription`, and also libspotify never supported arm64 which seems to be a new requirement.

Any guidance?  Crossfading is a very popular request and just implementing an equivalent preload track method would be wonderful.

**Comment by ahallora** [comment]
It would be awesome to be able to cross fade with the iOS SDK. That's a "nice to have" feature. Can't help you though; and neither can Spotify cf. https://developer.spotify.com/technologies/libspotify/: 

> Important! LibSpotify and CocoaLibSpotify are no longer under active development on any platform and are considered deprecated. If you are building applications for iOS or Android, please use the iOS SDK or Android SDK. We hope to be able to provide you with a new library for other platforms during 2016.

> Until then, you can still provision new keys for your project. However, please be aware that we cannot offer active support or guarantee future functionality on LibSpotify or CocoaLibSpotify.

**Comment by laura-digio** [comment]
There are apps like Serato Pyro or Pacemaker able to perform great mixing between Spotify songs. How can they do it if the SDK does not provide means to preload tracks?

**Comment by ozzotto** [comment]
Maybe they are still using CocoaLibSpotify. Don't know for sure. Any ideas?

**Comment by erdtman** [comment]
It is not possible to pre-load tracks with the iOS-SDK. And there are no plans to enable that.

Sorry for not giving more positive answer.

**Comment by laura-digio** [comment]
@ozzotto It doesn't seem probable, since these apps have recent updates in the App Store and libspotify doesn't support 64-bit (Apple announced that from February 1, 2015, all apps must be 64-bit). It's really intriguing how they achieve such mixing.
