### ISSUE TITLE
using appRemote when my app is backgrounded

### ISSUE THREAD

**Issue by mph070770** [spotify/ios-sdk#7]
Is it possible to connect to Spotify and start music playback when my control app is backgrounded? 

I have a bluetooth LE trigger for my app (a Flic BTLE button) which, when pressed, makes my app play a Spotify URI. This works fine when the app is in the foreground. 

I'd like the button to work in the background. The background mode of the flic button itself is working - it correctly triggers:

`func flicButton(_ button: SCLFlicButton, didReceiveButtonClick queued: Bool, age: Int)` 

but, the call to connect to the Spotify app fails - i.e. 

`authoriseAndPlayURI` and `connect` 

calls don't work when the app is backgrounded.

Is it possible to make these remote SDK framework calls work when my app is backgrounded?

**Comment by jackfreeman** [comment]
I do not believe UIApplication's `openURL:` can work from the background making this impossible.

**Comment by mph070770** [comment]
Thank you for the quick reply.  I assume there's no other way to start Spotify app playback if my app is backgrounded? Is it possible to keep an appremote connection open when my app is backgrounded, or does iOS stop everything working?

**Comment by jackfreeman** [comment]
@mph070770 if your app is backgrounded but not in a suspended state it should be possible to continue communicating with the Spotify app.

**Comment by cjam** [comment]
What UIBackgroundMode would that require?

**Comment by cjam** [comment]
Using the location API I was able to keep my app in the background which kept the connection between itself and Spotify.  I wonder if there is a way to do this with background refresh mode instead as it would likely use less power.

**Comment by ngaddamLogi** [comment]
I got this working in the background mode but I wasn't able to achieve it when the phone was locked. Still waiting for a solution on that.

**Comment by rolflocher** [comment]
@ngaddamLogi which background mode did you use?
