### ISSUE TITLE
request: add `updated` property 

### ISSUE THREAD

**Issue by thegreatmichael** [spotify/ios-sdk#700]
perhaps i'm going about this all wrong (please suggest an alternative), but it seems it might help my use case if you could add `updated` to 
1. `SPTPlaylistList` returned from `SPTPlaylistList.playlistsForUserWith*:callback:` 
2. `SPTPlaylistSnapshot` returned from `SPTPlaylistSnapshot.playlistWithURI:session:callback:`

This way I can cache this metadata (parts or all of the user's library) so that I can know whether any of them need updating...

I guess I'd also need some other property elsewhere... 

I'd like to make one request that comes back and tells me that the user updated their library since I last cached it (perhaps by my code comparing a cached object's `updated` property with the date returned from this request). A first implementation might not give me enough info to narrow it down, so maybe when I see that my cache is stale, i'd just re-request all the cached info, but maybe eventually i could somehow find out which playlist was CRUDed.

**Comment by mhuusko5** [comment]
👍 on some indicator that playlists, or saved tracks, have changed

**Comment by NOlivNeto** [comment]
Well... In `SPTPlaylistSnapshot` you have `snapshotId`, which is precisely what you want. Everytime some change happens in a playlist, it's `snapshotId` also changes. So you just need to store it and, after calling `playlistWithURI`, check if the value is the same you have.

For `SPTPlaylistList` you don't have this element. But the request is not that big, you could just iterate throw all the playlist objects inside of it, requesting the snapshot and comparing it to what you have stored.

I do that way and it works well.

**Comment by mhuusko5** [comment]
_It works_ is different from _it works well_. Iterating through potentially 10s or >100 playlists in `SPTPlaylistList.playlistsForUserWith*:callback:` and requesting snapshots (even if batching), every time some playlist screen in your app loads, is a good way to hit API limits/throttling.

Would be a _huge_ improvement if SPTPartialPlaylist's possessed `snapshotId` instead.

Then of course, a similar mechanism for saved tracks would be necessary as well.

**Comment by NOlivNeto** [comment]
@mhuusko5 +1

**Comment by erdtman** [comment]
We are deprecating the iOS-Metadata library.

The source code of the iOS-Metadata library has been released and can be found here. Spotify will not continue to maintain the released source code.

Either you can select to use the web-api directly or use the new open source iOS-Metadata library.

I will close this issue now.

We are sorry for the inconvenience that this creates, but looking back we think this is the best path forward.
