### ISSUE TITLE
Requests to fetch a subset of saved tracks will sometimes return an empty array of tracks. 

### ISSUE THREAD

**Issue by trufflin** [spotify/ios-sdk#701]
Hello, I've found that URL requests to load a subset of saved tracks will (rarely) return an empty track array. I am able to build an SPTListPage from the data returned to me, but all fields are essentially zeroed out, and [SPTListPage isComplete] will return YES. 

An example of the request syntax is: 
https://api.spotify.com/v1/me/tracks?offset=2380&limit=20

This seems to happen on roughly 1% of my requests for saved tracks. It could be a client bug on my end, but I believe I am handling the returned data correctly, and that the data has not been corrupted. I suspect this might be an API / server-side issue?

Thank you.

**Comment by erdtman** [comment]
We are deprecating the iOS-Metadata library.

The source code of the iOS-Metadata library has been released and can be found here. Spotify will not continue to maintain the released source code.

Either you can select to use the web-api directly or use the new open source iOS-Metadata library.

I will close this issue now.

We are sorry for the inconvenience that this creates, but looking back we think this is the best path forward.
