### ISSUE TITLE
SPTUser territory returns nil (Beta 17)

### ISSUE THREAD

**Issue by alanbithell** [spotify/ios-sdk#705]
Calling SPTUser.requestCurrentUserWithAccessToken returns an SPTUser instance with nil territory.

I cant see this having been mentioned by anyone else, its causing me issues with certain calls where market is required to make the results useful.

**Comment by matijse** [comment]
You need the `SPTAuthUserReadPrivateScope` scope in order to read this data from a user...

**Comment by alanbithell** [comment]
Doh
