### ISSUE TITLE
SPTAudioStreamingController currentPlaybackPosition if user is not premium member?

### ISSUE THREAD

**Issue by intralizee** [spotify/ios-sdk#706]
I'm new to Spotify's iOS SDK and I'm trying to figure out if it's possible to get current playback position & name of song; if users are not premium members.

It seems to not be possible when using SPTAudioStreamingController because SPTAudioStreamingController returns zero if user is not a premium member for currentPlaybackTime.

I'm assuming I can only get data from SPTAudioStreamingController when logged in as premium and I'm wondering if there is any possible way of accessing song name & player position when non premium.

**Comment by NOlivNeto** [comment]
You cannot get player position if you're not with a premium account, because without a premium account you can't even login to player. It calls for `audioStreaming:didEncounterError` on your delegate if you try.

You can get the songs name if you have it's URI or ID, getting then via trackWithUri on SPTTrack.

**Comment by intralizee** [comment]
Thanks for the info and that's a bummer that user has to be a premium user or no dice.

I wonder why it's implemented that way, Apple's MPMusicPlayerController makes the info public for iTunes when listening to local music files or using apple music.

I can get the info on OSX for Spotify music without logged into an premium account but have yet to look into Windows.

**Comment by NOlivNeto** [comment]
You can get some information without a premium account, like playlists, authors, songs information, search... You just can't stream audio.

What info specifically are you trying to get?

**Comment by intralizee** [comment]
I tried some examples provided by Spotify and ran into that error you mentioned. When trying to get the info it would just give me an empty value.

I'm after the song name that is currently playing and player position (current time in song).

**Comment by NOlivNeto** [comment]
@intralizee Unfortunately, you'll not be able to do that, because you can't even login the player. So the player will never play, thus you can't get what it's playing nor the playback position (after all, It's not playing)

**Comment by d-kunin** [comment]
@NOlivNeto mentioned, there is no way you can get if the user is not premium.
