### ISSUE TITLE
Beta 17: Callback-based player login/logout methods remove (necessary for workarounds)

### ISSUE THREAD

**Issue by mhuusko5** [spotify/ios-sdk#711]
Wanted to create a succinct issue/hopefully get a response re: the callback based player login methods removed in Beta 17. As previously stated, they are necessary to workaround existing bugs such as those affecting LTE/network switching, and thus more or less _need_ to be re-introduced in the next beta in order to be able to upgrade to it/retain our workarounds (and the next beta is more important than 15/16/17 were, because it brings the IPV6/App Store fix).

Thanks!

**Comment by NOlivNeto** [comment]
Could you name those methods?

**Comment by mhuusko5** [comment]
`- (void)logout:(SPTErrorableOperationCallback)block` and `- (void)loginWithSession:(SPTSession *)session callback:(SPTErrorableOperationCallback)block`

**Comment by d-kunin** [comment]
Odds are high that reintroduction won't happen. There is another way to fix network switching issues that we will try to implement.

**Comment by mhuusko5** [comment]
Okay so beta 17/20 aren't shippable (can't ship with user's not able to switch to LTE without app breaking). Good to know.

What's the plan if this new internal LTE fix doesn't work (like the last year's worth of attempts)? Also what's the timeframe?

**Comment by mhuusko5** [comment]
Closing this as although the callback based logins are highly desirable, the LTE issue they were vital to fixing seems mostly addressed in beta 20.
Thanks.
