### ISSUE TITLE
SPTAudioStreamingController.currentTrackURI and .currentTrackDuration return wrong values

### ISSUE THREAD

**Issue by brianhans** [spotify/ios-sdk#713]
With the beta 20 two properties no longer work. The currentTrackURI will always return nil, even if there is a current track playing (tested in both my app and the demo app) and the currentTrackDuration will always return 0. 

You can still use the properties of the SPTPartialTrack to get these values.

**Comment by CVertex** [comment]
We're seeing the same issues

**Comment by gchilds** [comment]
I'm seeing this too. I use this function property everywhere. When's the next beta?

**Comment by d-kunin** [comment]
Please dont use `currentTrackX` properties, they will be removed soon.
Instead you can use `SPTAudioStreamingPlaybackDelegate:didChangePlaybackState:` and get everything you need from `SPTPlaybackState.currentTrack`

**Comment by mhuusko5** [comment]
I know someone on the team has an addiction to delegate methods, but this is a little too silly/too far. If you want to provide a delegate/reactive means to receiving this information, _as well_, fine.. but a media player is a very stateful system, and synchronous access to this info is a must for most use cases.
