### ISSUE TITLE
Beta 20: `playURI: callback:` method sig no longer exists

### ISSUE THREAD

**Issue by NathanWalker** [spotify/ios-sdk#714]
This is the only `playURI` function that exists now:
https://github.com/spotify/ios-sdk/blob/master/Spotify.framework/Versions/A/Headers/SPTAudioStreamingController.h#L191

Why is this?
The changelog mentions (in part):
```
API Changes Updated functions:

-(void)playURI:(NSURL *)uri callback:(SPTErrorableOperationCallback)block;
```
https://github.com/spotify/ios-sdk/blob/master/CHANGELOG.md

However it appears they were instead removed?

If this was a mistake with the Beta 20 release, could someone please provide an ETA on when a patch release could be made to include back that now missing function?

**Comment by akelagercrantz** [comment]
You can achieve the same functionality with the `-playURI:startingWithIndex:callback:` method as the `-playURI:callback:` by passing index `0`.

The changelog might not have been very clear in this respect, but the change that it refers to is the added index parameter.

**Comment by NathanWalker** [comment]
Ok good to know, thanks.
