### ISSUE TITLE
Beta 20 how to queue tracks

### ISSUE THREAD

**Issue by gchilds** [spotify/ios-sdk#717]
The last queue function I can see -(void)queueURI:(NSURL *)uri callback:(SPTErrorableOperationCallback)block; has been marked as deprecated.

What does this mean for queueing in general? Can we create a single URI that represents multiple tracks? Or do we need to create a playlist?

We can of course do our own queues, but then how do we make sure the next track has been "warmed"/pre-queued/pre-fetched, ready for immediate playback?

I guess my overall question is what is the intention here with queueing?
Should we prefer playlists? Can we create invisible/ephemeral playlists that don't pollute the user's spotify experience? If this is so, then what of the maximum number of playlists allowed?

**Comment by CVertex** [comment]
@d-kunin I'm curious about this too.

What happened to playUris and replaceUris?

The spotify web widget supports ephemeral/temp playlists. It'd make sense for this SDK to support that same functionality

**Comment by NickCJ83** [comment]
@d-kunin i've got a similar issue to @gchilds happening. Any thoughts?

**Comment by d-kunin** [comment]
@gchilds please see my response here https://github.com/spotify/ios-sdk/pull/712#issuecomment-241679677

> queueURI will be there in the following release and not marked as deprecated anymore.
replaceUris most like will not come back since underlying queue api has been reduced.

> In general, you can expect that the SDK will provide less endpoints, since we want to have a sustainable strategy and be able to maintain it. Having too much stuff is not an option for now. We will try to provide you with core functionality so that you can build what you need upon it.

You can use `queueURI` and expect it to be present in the following releases.
Can you please describe your use case in more details so that we can see what possible could be helpful? You dont play the users' playlists but build set of track on your own to be played?

**Comment by gchilds** [comment]
Thanks, @d-kunin - I'm glad to hear queueURI is not going away.

Yes, we generate playlists in our app. We need to be able to communicate what we're going to play next so the SDK can minimise loading time. So far, `playURI` and `queueURI` seem to have this covered, although the SDK's internal queue is invisible to us, apart from `nextTrack` in `didChangePlaybackState`, and it's not clear what to do when `queueURI` quietly fails.  A way to inspect (or set?) what is enqueued would help here.

The user can also change items in the playlist, without stopping the current track, which invalidates the next track, so we need a way of replacing the queued track without stopping the current one.
Right now the only way to cancel items queued with`queueURI` appears to be by calling `playURI` again. To work around this we would have to make a note that the SDK's `nextTrack` and subsequent tracks are wrong, and remember to call `playURI` just before the next track would have started. This was easy in all the previous SDK's using `replaceURIs`, but now seems to be impossible.

Something like 

    // some func that would have called `replaceURIs`
    self.trackURIs = newURIs
    // would be nice to be able to inform SDK of new nextTrack here, or at least clear nextTrack
    self.queuedTracksAreNowBogus = true

    ...

    // later on, in kvo callback or by polling `currentPlaybackPosition`
    if fabs(currentPlaybackPosition-trackDuration) < 1  {
        if self.queuedTracksAreNowBogus {
          // next track is wrong, clear it by playing right track
          // slow path, `playURI` will clear buffers and take longer to load. Bad 😞
          playURI(...)
          self.queuedTracksAreNowBogus = false
       } else {
         // do nothing, SDK will continue to next track. Good because prebuffering is working
       }
    }

A `clearQueue` call would help a lot - unless you have a better suggestion?

**Comment by cameronehrlich** [comment]
Yes, like @gchilds said, a `clearQueue` call would make my life a lot easier.

**Comment by NickCJ83** [comment]
@d-kunin any more news on this? Seems like it would be handy for quite a few of us

**Comment by haskinsj87** [comment]
I can't seem to get `queueURI` working at all. There is no `queuePlay` method. If I use the `playURI` method, songs will not queue there. I am trying to build a set of tracks to play not in a playlist. 

Is there something I'm missing to get queueing to work properly? 
Is there any estimate on when the next beta will release?

**Comment by gchilds** [comment]
To get `queueURI` to work, you must wait at least until `didChangePlaybackState` has a non nil `currentTrack`. I've found that sometimes that's not quite enough though, so I wait until the track has been playing for a few seconds, then call  `queueURI`. 

A successful call to `queueURI` causes a `didChangePlaybackState` callback, with a non-nil `nextTrack`.

Because `queueURI` still sometimes silently fails for me, and the queue state is opaque, you can't always trust that `nextTrack` is what you expect, so I poll the current playing track to see if it's about to end (you have to do that anyway to detect a track finishing as `didStopPlayingTrack` is missing in beta20) - if it is ending, I double check that the `nextTrack` is correct and if so, I allow the track to skip naturally, otherwise I call `playURI`. `playURI` is currently the only way I know of resetting the SDK's queue. 

This gives me a fairly robust queue implementation. When `queueURI` works I get a quick transition. When it doesn't, queueing the next track takes longer, but at least I have a working queue.

The above queuing method was derived through guessing and many experiments. If someone from spotify knows a better way, please let us know!

**Comment by DmytroAnkudinov** [comment]
There are no plans to implement a `clearQueue` method in underlying library. 

Regarding @gchilds last comment: currently you should call `queueSpotifyURI` after the callback `didChangeMetadata` event has been fired for `playSpotifyUri`. We plan to implement it so you won't need to wait for the event. Thank you for the report.

**Comment by jlee9595** [comment]
Hello, are there still plans to implement `playSpotifyUri` so that it doesn't need to wait for `didChangeMetadata` to use it? Thank you!
