### ISSUE TITLE
How to tell if a SPTrack has finished playing in beta 20

### ISSUE THREAD

**Issue by GabeJacobs** [spotify/ios-sdk#718]
I used to use this snippet of code to tell if a song has finished playing, but it not longer works with the changes. The delegate call didStopPlayingTrack doesn't do the trick unfortuantely 

```
- (void)audioStreaming:(SPTAudioStreamingController *)audioStreaming didChangeToTrack:(NSDictionary *)trackMetadata {
	if (trackMetadata == nil) {
		// SONG ENDED
	}
}
```

Anyone have an idea?

**Comment by mhuusko5** [comment]
I've gone with checking for (...durationMs - ...currentPlaybackPosition) < tolerance, in the new playback state callback (it gets called on track end).

**Comment by GabeJacobs** [comment]
@mhuusko5 Yeah I was playing with that, but it's really not exact, which scares me. There's gotta be an exact way no?

**Comment by mhuusko5** [comment]
Haha "there's gotta be" has no place in this repo/sdk ;)

Jokes aside, for now, the described method should be fine/'exact'. The playback state delegate method is called a few times potentially at track start, and then once at track end, but not in between (on pause/unpause etc). At least as far as I can tell.

**Comment by GabeJacobs** [comment]
@mhuusko5 I'm having an issue determining when if it's getting called at the start or at the end. Anything you can do to know in didChangePlaybackState whether or not it's at end or start?

**Comment by mhuusko5** [comment]
As described, I'm doing the the duration/position compare atm, but just checking for audioStreaming.currentPlaybackPosition greater than 0 should be sufficient.

**Comment by NOlivNeto** [comment]
> Haha "there's gotta be" has no place in this repo/sdk ;)

+1 Haha 😂

**Comment by gchilds** [comment]
@mhuusko5 what's your tolerance? I can't seem to go under 1s without risking missing the end. without being able to queue (#717) detecting the end of the track has become more important.

**Comment by NathanWalker** [comment]
I am also struggling with this and using the same strategy above (...durationMs - ...currentPlaybackPosition) < tolerance) ... however I'm playing the next track when the currently playing track ends, and when doing so, the next track will play for like .7 secs usually and then stop. I believe this may be because the playerstate delegate method gets called up to 3-4 times whenever a new track plays and checking `currentPlaybackPosition` may be causing an issue?

Needless to say, relying solely on a delegate method for something as simple as track end is ridiculous. Especially provided the previous `DidStartPlayingTrack` and `DidStopPlayingTrack` worked great for this purpose. Sigh, wtf.

**Comment by NickCJ83** [comment]
@NathanWalker feeling your pain bro. Feels like we just took a massive step backwards :(

**Comment by mhuusko5** [comment]
@gchilds I've got the tolerance at 5 seconds, but it could be much larger.. because this isnt a method that fires regularly with a bunch of false positives – you only have to tell the difference between a beginning of track firing, and end.

**Comment by mhuusko5** [comment]
> the next track will play for like .7 secs usually and then stop. I believe this may be because the playerstate delegate method gets called up to 3-4 times whenever a new track plays and checking currentPlaybackPosition may be causing an issue? 

@NathanWalker haven't encountered this yet. Will watch out for it.

**Comment by undrtone** [comment]
This appears to be a show-stopping issue for us. We need to reliably detect when a single track has finished playing. (Our application creates playlists from multiple streaming services, so we do not have the luxury of using queues). The sample application uses a playlist URI, so does not demonstrate this use case.

Here is what we have determined:

1. Neither `audioStreaming:didStartPlayingTrack:` nor `audioStreaming:didStopPlayingTrack:` are ever called.

2. The header doc states that `audioStreaming:didChangePlaybackState:` is an informal event. We don't rely on it, but do see it called multiple times with the same metadata.

3. `audioStreaming:didChangePlaybackStatus:isPlaying:` is called multiple times when a track ends, with `isPlaying = NO`.

4. At any time, `SPTAudioStreamingController currentTrackURI = nil` and `currentTrackDuration = 0`.

5. The above trick (distance to end < tolerance) worked to identify a song has completed. But...

6. If we try to play another Spotify track URI immediately after one ends, the `SPTAudioStreamingControllerDelegate` continues to be notified about the state of the previous track, with `isPlaying = false` and `currentPlaybackPosition = <previous track end position>`. This is very difficult to discern.

@d-kunin Could beta-21 restore the original pattern of calling `audioStreaming:didChangeToTrack:` with `trackMetadata=nil`? Or, could you ensure the delegate method `audioStreaming:didStopPlayingTrack:` is called.

Thanks,
michael

**Comment by mhuusko5** [comment]
#1->4 are obviously frustrating, but it sounds like #6 is the real problem. I haven't personally encountered it, but I think that's just because of how my state machine around the player works - I don't allow duplicate events in a row.
Keeping an ended flag or deduping events down the line may be solutions to look into given that even if previous functionality were to be restored, it wouldn't be until the next beta.

**Comment by NOlivNeto** [comment]
I can't understand how a team of high-skilled developers (like I suppose there is in Spotify) think it's a good idea to control almost everything of a streaming in a single method without any reability.

Sometimes I feel you don't want us to use your product.

We are going backwards!!!

**Comment by ahallora** [comment]
@d-kunin THIS:
> Or, could you ensure the delegate method audioStreaming:didStopPlayingTrack: is called.

**Comment by gchilds** [comment]
But `didStopPlayingTrack` isn't being called (#723)

**Comment by CVertex** [comment]
@d-kunin Have you had a chance to read this thread? This is very important for me. I understand the desire to remove surface area, but this makes detecting end of tracks much harder

**Comment by d-kunin** [comment]
@CVertex for collections like albums and playlists checking if `currentTrack.uri` has been changed should work, but for a single track we will try to provide something in the following releases.

**Comment by CVertex** [comment]
@d-kunin Thanks. I look forward to seeing future releases. If you need help thinking through the API. Please discuss with us here

**Comment by d-kunin** [comment]
`didStart/StopPlayingTrack` was reintroduced in beta 21. However I recommend to use `SPTPlaybackEvent`s `kSpPlaybackNotifyTrackChanged` and `kSpPlaybackNotifyTrackDelivered` instead.
