### ISSUE TITLE
NowPlayingDemo App OOTB failing to authenticate

### ISSUE THREAD

**Issue by eanntuan** [spotify/ios-sdk#72]
Hi everyone,

I've downloaded the Spotify SDK, and am just trying to run the demo app, NowPlayingView Demo project out of the box, and am having trouble connecting to Spotify.

I do have Spotify premium, music is already playing when I build the app on XCode. I'm deploying my iPhone6. I'm able to see the "Spotify App Remote" view, but after tapping the "Play" button, it redirects me to my Spotify app, then redirects back and crashes. It fails on "didFailConnectionAttemptWithError."

Here's the console log:
2019-01-03 16:40:55.739977-0500 NowPlayingView[45496:1889155] AppRemote: Connecting...
2019-01-03 16:40:55.814105-0500 NowPlayingView[45496:1889155] AppRemote: Established a connection to the Spotify app.
2019-01-03 16:40:55.985353-0500 NowPlayingView[45496:1889155] AppRemote: Failed to authenticate with the Spotify app.
2019-01-03 16:40:55.987605-0500 NowPlayingView[45496:1889155] AppRemote: Failed to establish a sesssion with error: Error Domain=com.spotify.app-remote.wamp-client Code=-1001 "wamp.error.authorization_failed" UserInfo={details={
    message = "No token provided.";
}, NSLocalizedFailureReason=wamp.error.authorization_failed}
didFailConnectionAttemptWithError
2019-01-03 16:40:59.247482-0500 NowPlayingView[45496:1889155] AppRemote: Disconnected with error: (null)

After extensive research, it looks like the access token is null, hence the failure to authenticate? I've also tried creating my own app in the developer portal, added in my own clientID and redirectURI.

What am I missing?

Thanks so much!

**Comment by pmaddi** [comment]
@eanntuan How did you solve this issue? (I'm getting the same error)

**Comment by eanntuan** [comment]
Hello! I actually had to refer back to this post as I ran into this issue again on another app. I can't remember the exact steps, but here are the things I did try:
 - Make sure the bundle ID and the redirect URI are the same on the Project settings and the Info.plist (URL types > URL Identifier/URL Schemes)
- Make sure you're using an actual device rather than the simulator.

Let me know if you resolve your issue!

**Comment by kjanjuha** [comment]
@eanntuan I can't seem to get this working. Do you have a link to your repo so that I can take a look? Is that ok?

**Comment by bhartyrs** [comment]
Update?

**Comment by sean-williams24** [comment]
I'm also getting the same issue! Did anyone manage to fix it>?

**Comment by bhartyrs** [comment]
Need an update on this if anyone still having this problem.

**Comment by sean-williams24** [comment]
I'm also getting the same issue which states no token was provided, which is clearly why I can't connect. I tried installing the Ruby setup multiple times but I keep getting a BUILD FAILED on rbenv install. My app only needs to add albums to a users account so I don' t believe I need to go down the token swap route anyway. I'm pretty sure the Implicit Grant flow will be ok for me, but that just stalls when I switch to the Spotify app as well.

**Comment by bhartyrs** [comment]
> Hello! I actually had to refer back to this post as I ran into this issue again on another app. I can't remember the exact steps, but here are the things I did try:
> 
> * Make sure the bundle ID and the redirect URI are the same on the Project settings and the Info.plist (URL types > URL Identifier/URL Schemes)
> * Make sure you're using an actual device rather than the simulator.
> 
> Let me know if you resolve your issue!

I have the same error. Could you post your code?

**Comment by twalenzyk** [comment]
Hi all,

I've just ran into the same issue.  I could solve it by checking the bundle name in xcode project setting. Also check URL Types (which was still different).
Ensure they match to what you have set up in spotify dashboard.
