### ISSUE TITLE
SPTSearch- performSearchWithQuery: queryType: offset: accessToken: callback: - doesn't work on Simulator but works on device?

### ISSUE THREAD

**Issue by NathanWalker** [spotify/ios-sdk#720]
Anyone else experienced this?

In the iOS Simulator, it will always return a `SPTListPage` like this:

```
<SPTListPage: 0x7fafbd273c50>: 0-18446744073709551615 of 0 items
```

The `items` key on the `SPTListPage` will always be `null`.

However when run on a device, it works fine. Anyone have thoughts on what is going on?
Using Beta 20.  I had seen this same behavior with Beta 17 as well.

**Comment by gchilds** [comment]
Wow - I didn't know the SDK supported search, I've been talking directly to the API.

**Comment by Voxar** [comment]
@NathanWalker  Have you noticed this problem with any other methods? Is your device an 32 bit one? Like iPhone 5 or earlier?

**Comment by erdtman** [comment]
We are deprecating the iOS-Metadata library.

The source code of the iOS-Metadata library has been released and can be found here. Spotify will not continue to maintain the released source code.

Either you can select to use the web-api directly or use the new open source iOS-Metadata library.

I will close this issue now.

We are sorry for the inconvenience that this creates, but looking back we think this is the best path forward.
