### ISSUE TITLE
Beta 20: allowCaching and diskCache - may cause issue with subsequent track plays

### ISSUE THREAD

**Issue by NathanWalker** [spotify/ios-sdk#722]
```
-(BOOL)startWithClientId:(NSString *)clientId audioController:(SPTCoreAudioController *)audioController allowCaching:(BOOL)allowCaching error:(NSError *__autoreleasing*)error;
```

Using `allowCaching` set to `true` on iPhone 5s and using:
```
if ([self.player startWithClientId:auth.clientID audioController:nil allowCaching:YES error:&error]) {
            self.player.delegate = self;
            self.player.playbackDelegate = self;
            self.player.diskCache = [[SPTDiskCache alloc] initWithCapacity:1024 * 1024 * 64];
```
Based from the example. It appears some tracks that have already played will play for about 1-2 secs and then stop, and you can no longer play them at all.

Not sure what is going on, been debugging this weekend, but it appears it may be related to the new `allowCaching` option? Need help.

**Comment by d-kunin** [comment]
Should not be related to `allowCaching`, since the options is there for a very simple `if` statement. Do you have enough free space on the device?

**Comment by gchilds** [comment]
@d-kunin I'm seeing exactly the same behaviour as @NathanWalker . There's one track that spontaneously stops after 1 second if `allowCaching = true`. I have 74GB free on the device. 

We will work around this for now by turning caching off.

**Comment by volksport** [comment]
I believe I'm also having this issue in Beta 20 (haven't fully tested Beta 21 yet). Most songs stop playing before they finish.

Current one I was just listening to stopped at 1:56 of  3:02. Previous one stopped at 11 seconds in.

Happening pretty often.

**Comment by d-kunin** [comment]
We gonna take a look before beta 22 is out.

**Comment by erdtman** [comment]
Beta 22 has been released please verify if this solves this issue.

**Comment by CVertex** [comment]
I've noticed that caching seems fine in beta 22.. Will continue testing to see what happens.

**Comment by gchilds** [comment]
I've had no problems with caching since b23 came out.

**Comment by Voxar** [comment]
Awesome!
