### ISSUE TITLE
audioStreaming:didStartPlayingTrack: & didStopPlayingTrack: missing from beta 20

### ISSUE THREAD

**Issue by gchilds** [spotify/ios-sdk#723]
Despite being in the header file

`-(void)audioStreaming:(SPTAudioStreamingController *)audioStreaming didStartPlayingTrack:(NSURL *)trackUri;`

and 

`-(void)audioStreaming:(SPTAudioStreamingController *)audioStreaming didStopPlayingTrack:(NSURL *)trackUri;`

are never called. 

Any idea of what replaces these? I'm looking for a good place to call `queueURI` (#717)

I've branched the SDK, modified it and reproduced the problem in the Simple Track Playback example code:

https://github.com/gchilds/ios-sdk.git

steps to reproduce

1. run the project
2. log in
3. tap PlayURI 
4. tap Play/Pause

observe that `didStartPlayingTrack`, `didStopPlayingTrack` are not called.
If you queue up another track with `QueueURI` and hit skip, observe that another `SPTAudioStreamingPlaybackDelegate` method, `audioStreamingDidSkipToNextTrack`,  _is_ called.

**Comment by cjwhitsitt** [comment]
I'm also not seeing the `audioStreaming: didStartPlayingTrack:` and `audioStreaming: didStopPlayingTrack:` methods get called.  However, `audioStreaming:didChangePlaybackStatus:` is called. I think the completion block for `playURI:` can serve as a replacement for `didStartPlayingTrack:`. There's not a good complete replacement for `didStopPlayingTrack:` that I found.

**Comment by d-kunin** [comment]
Please dont use `didStartPlayingTrack/didStopPlayingTrack` as they will be removed.
If you need to know if track has changed, you can use data from `didChangePlaybackState`, memorizing `currentTrack` and comparing it every time you receive the event. 
```
if (playbackState.currentTrack.uri != lastTrackUri) {
  lastTrackUri = playbackState.currentTrack.uri;
  // handle track change
}
```

**Comment by undrtone** [comment]
Hi Dmitry ( @d-kunin ),

Unfortunately, this does not work when the URI refers to a single track and you want to detect the song has finished playing. (for eg. `spotify:track:6mFkJmJqdDVQ1REhVfGgd1`)

When the song starts, `audioStreaming:didChangePlaybackState:` is called and `playbackState.currentTrack.uri` is set correctly. However, when the song stops,  `playbackState.currentTrack.uri` is still set to the track's URI.

At that point, you could compare `SPTAudioStreamingController.currentPlaybackPosition` with `playbackState.currentTrack.durationMs` to determine if the play head is at the end of the track? But, it feels like the SDK could offer something simpler.

Thanks,
Michael

**Comment by d-kunin** [comment]
Hi Michael ( @undrtone ),

We will check what we can do. Do you build some kind of queue on your own so that you need this kind of information?

**Comment by cjwhitsitt** [comment]
Thanks for the info Dmitry. I do have my own queue due to the nature of my app. As Michael mentioned, the current implementation doesnt seem ideal for this use case.

**Comment by GabeJacobs** [comment]
@d-kunin just to back cjwhitsitt up here, I too manage my own queue

**Comment by mhuusko5** [comment]
Same. It's unfortunate that the SDK's API has moved in the direction of black-box with state notifications. That kind of design is optimised for reproducing a very specific architecture/product of a simple reactive UI around the SDK/player, that updates when told... and doesn't allow for (or at least makes difficult) building a fuller semantic system around the SDK. This is counter to my needs, and I'm guessing the needs of the general developer base (excluding those building simple/prototype apps).

But more relevantly, its very counter to "Having too much stuff is not an option for now. We will try to provide you with core functionality so that you can build what you need upon it." (which is a perfectly respectable goal/change of direction).
That is to say, if one is going to provide a small core to be built upon by others, that core needs to be flexible/generic and un-opinionated.

Hopefully going forward this can be kept in mind, and middle grounds in some API areas can be achieved. I am thankful for the more continuous communication via @d-kunin lately.. it should make this more possible.

**Comment by cjwhitsitt** [comment]
With beta 20, when a song ends and `didChangePlaybackState:` is called, the difference between `playbackState.currentTrack.durationMs` and `audioStreaming.currentPlaybackPosition` will be between .4 and .6 seconds. This is not an intuitive solution but setting a tolerance of .6 seconds is working for me.

Note: `audioStreaming.currentPlaybackDuration` is not working in beta 20 (#556)

**Comment by gchilds** [comment]
I see differences of .7s, so for peace of mind I'm using a 1s tolerance

**Comment by drew55** [comment]
Like others, we manage our own queue as well.  If there was a BOOL passed into `audioStreaming:didStopPlayingTrack:` if the track completed/finished naturally.  It seems like a lot of devs here really need this track-finished callback.

**Comment by Anders27** [comment]
Besides an iOS version, I also have an Android version of my app that uses the Android Spotify SDK, currently beta 13.

The Android SDK has similar “delegates” (events) as didStartPlayingTrack and didStopPlayingTrack:

TRACK_END
Deprecated. 
Use TRACK_CHANGED to monitor current track and PLAY and PAUSE to monitor playback state.

TRACK_START
Deprecated. 
Use TRACK_CHANGED to monitor current track and PLAY and PAUSE to monitor playback state.

It’s the same problem here, if those “events” goes away it will break my app and probably many other apps.

Can someone from Spotify explain why they think those delegates/events should not be supported anymore?

How hard can it be to keep them even though other newer delegates/events are added?

If they go away, then there must be replacements that still give us the same info.

**Comment by d-kunin** [comment]
@Anders27 I have an update specifically for you :) Android SDK has just been updated to beta21. 
It contains changes similar to iOS. But all the information about changed/finished  tracks could be figured out from `PlayerEvent`. You can expect similar approach to be introduced in upcoming beta21 for iOS. The event will have the same name and semantics.

**Comment by Anders27** [comment]
I update my Android player with the latest beta 21. A little work was needed but so far everything works great.
And in my specific user case, iOS beta 20 works fine except for the iOS 7 login problem.

**Comment by d-kunin** [comment]
They work in beta21. But don't forget to change signatures to use `NSString*` instead of `NSURL*`
