### ISSUE TITLE
Track URIs being remapped in Beta20 

### ISSUE THREAD

**Issue by gchilds** [spotify/ios-sdk#724]
When playing a track, e.g. `spotify:track:6XGSVfrX3RanlUSIzLhwGS`, the delegate method `didChangePlaybackState` will eventually be called with that track set in `playbackState.currentTrack`. Sometimes this track's URI is mapped to another distinct yet functionally identical (?) URI, e.g. `spotify:track:2IBFtZeJ3DxKOgIFnwsyMM`.

Maybe this is due to global / local market URIs, like you see in the https://api.spotify.com/v1/tracks API?

In any case, this is confusing my app, which uses track URIs to manage metadata.
I have several possible ways forward

  • build a URI map as`didChangePlaybackState` responds to `playURI` calls
  • fuzzily match `currentTrack` metadata with my metadata
  • use the `tracks` API to figure out what the SDK already knows 

Anything else?

I'm sure this remapping is good news for users if it results in more tracks being playable in their markets, but it would have been ideal to have access to the original URI or at least some documentation on the possibility of the SDK changing URIs behind the scenes. 

A lot of solutions to beta 20 problems are fuzzy and involve second guessing / shadowing SDK state (#717, #718, #719,  #723), state that could very easily be communicated to the user. 

Beta 20 seems harder than it should be. Why is this?

**Comment by CVertex** [comment]
It seems the new SDK is mimicking the desktop app. If you supply a global track URI, it'll find the local track URI for the users territory and play that instead (if is_playable is true).

More information about track linking is available at 
https://developer.spotify.com/web-api/track-relinking-guide/

Perhaps the SDK could make us aware of the relink?

I'm discovering a bunch of similar issues regarding shadowing state, as you mention @gchilds. 
So much extra effort is required because currentTrackURI is nil.
:angry:

**Comment by d-kunin** [comment]
We will see what we can do, I will follow up on this later.

**Comment by d-kunin** [comment]
It seems to be fixable in the next release.

**Comment by CVertex** [comment]
@d-kunin what's the rough plan?
Will you avoid the remap? Or present the global uri with the did change to track callback?

**Comment by d-kunin** [comment]
@CVertex current metadata will most likely expose `playback_source_uri` or something similar. It must be equal to the the uri that is passed to `playUri` method even if substitube/relink has happened. It is valid only for single tracks, of course.

**Comment by CVertex** [comment]
@d-kunin Thanks for looking into this, look forward to testing this in 21

**Comment by d-kunin** [comment]
Please check [the demo](https://github.com/spotify/ios-sdk/blob/master/Demo%20Projects/Simple%20Track%20Playback/Simple%20Track%20Playback/ViewController.m#L248) for relink/remap detection examlpe.
