### ISSUE TITLE
seekToOffset 0 breaks music playback in beta20

### ISSUE THREAD

**Issue by gchilds** [spotify/ios-sdk#725]
Repro: 
  1. clone https://github.com/gchilds/ios-sdk
  2. run Simple Track Playback from demo projects
  3. Tap `PlayURI` and `Play/Pause`
  4. wait a moment then tap `seek 0`

observe that audio does seek to zero & plays half a buffer, but then stops. queuing up extra tracks and hitting next may get audio playing again, but it is choppy.

Seeking to a small, positive offset, like 0.01s, does work.

**Comment by CVertex** [comment]
@gchilds that's incredible.. Have Spotify tested this release at all?

**Comment by d-kunin** [comment]
Thanks @gchilds, we will check it. Seems like there is internal conversion from NSTimeInterval to uint32_t.

**Comment by Anders27** [comment]
Seeking to 0 has never worked OK, I've always clamped the value to 0.01 sec.
I first started with beta 7 or something and this problem has always existed.

**Comment by CVertex** [comment]
@Anders27 I've been using it since beta15/16 without issue

**Comment by CVertex** [comment]
@d-kunin Thanks for looking into this. Will this be addressed in beta 21?

**Comment by cjwhitsitt** [comment]
@gchilds, are you able to seek to a larger position in the song? I don't seem to be able to seek at all, otherwise, playback stops and resuming causes the song to start from the beginning.

If this isn't what you're seeing, I'll create another bug.

**Comment by cjwhitsitt** [comment]
This seems to be a song-specific issue relating to an unreliable duration, so I'm creating a new bug.

**Comment by gchilds** [comment]
@cjwhitsitt I can break audio playback by seeking, but not reliably. 
I haven't logged it yet, because it seems related to a particular router (yes, really) that was implicated in a pre-beta 20 bug where after the current track finished the next track would not start & audio died in general (#???). I think audio eventually restarts with my seek problem, but choppily and not from the beginning. If I can get a reliable repro I'll create the issue. I see you've created yours.

**Comment by d-kunin** [comment]
Fixed in beta21.
