### ISSUE TITLE
Should we use Beta 20?

### ISSUE THREAD

**Issue by Anders27** [spotify/ios-sdk#726]
This page:
https://developer.spotify.com/technologies/spotify-ios-sdk/#downloading-the-sdk

"Download the latest iOS SDK Beta"
https://github.com/spotify/ios-sdk/releases
still points to Beta 17

Does that mean that beta 20 isn't officially released?

**Comment by d-kunin** [comment]
You can use beta 20, all following releases will be more like beta 20 in terms of API. 
The website has not been updated yet. I will do it now :) Thanks!
