### ISSUE TITLE
beta 20 issues

### ISSUE THREAD

**Issue by drew55** [spotify/ios-sdk#728]
We have a big new forthcoming app nearing release and this beta is introducing major questions that we can offer support for Spotify.  As some have pointed out, the SDK is regressing to the point of being unusable.  Here's all the stuff that's popped up in beta 20:

1) The changes to the caching API don't allow us to know the total size of a track item being retrieved as far as I can tell.  We therefore cannot report to the user what percent or portion of the current track has been downloaded etc.  There needs to be a away to have some kind of knowing the current track total byte size.

2) SPTPlayOptions is now totally gone!  there's no way to resume a track at a given time reliably?

3) Like others have posted, we manage our own track queue. If there was a BOOL passed into audioStreaming:didStopPlayingTrack: if the track completed/finished naturally. It seems like a lot of devs here really need this track-finished callback.

**Comment by d-kunin** [comment]
Partial response:
2) We will add `startAt` parameter to `playURI:(NSURL *)uri startingWithIndex:(NSUInteger)index`
3) `audioStreaming:didStopPlayingTrack` will be fixed, but there will be no flags to it

**Comment by drew55** [comment]
Thanks for the response, d-k.

Hopefully (1) can be addressed since it lets us offer the user some pretty awesome visual feedback about the network (or cache status).   One way this could be addressed is that the `totalSize` field is altered (fixed?) to how it was in b17 where it reported the total size of the cache object instead of the byte size of the data item.   

Thanks for attending to us, d-k -- it will be worth it when you see what we're making!  We think Spotify will be quite pleased!

**Comment by d-kunin** [comment]
@drew55 can you please create a separate issue for (1) ?

**Comment by d-kunin** [comment]
2) and 3) are fixed in beta 21. For 1) You can create a separate issue with the reasoning why you need that. Have fun :)
