### ISSUE TITLE
API down?

### ISSUE THREAD

**Issue by GabeJacobs** [spotify/ios-sdk#729]
Our search results are always returning 0 results. Please help!

https://api.spotify.com/v1/search?q=hello&type=track

https://developer.spotify.com/web-api/console/get-search-item

**Comment by mhuusko5** [comment]
If you haven't already, https://github.com/spotify/web-api/issues might be a good place to post

**Comment by GabeJacobs** [comment]
Thanks i'll try there too

**Comment by GabeJacobs** [comment]
all good now
