### ISSUE TITLE
Can't establish remote connection - delegate does not provide errors

### ISSUE THREAD

**Issue by martinobonfiglioli** [spotify/ios-sdk#73]
Got this error and delegate never response
>[BoringSSL] nw_protocol_boringssl_get_output_frames(1301) [C30.1:2][0x10b990500] get output frames failed, state 8196

It's happens most of the time 8/10 I can't understand reason

SPTConfiguration init

```
_remoteConfiguration = [[SPTConfiguration alloc] initWithClientID:kMXMSpotifyClientId
                                                      redirectURL:kMXMSpotifyCallbackURL];
_remoteConfiguration.playURI = @"";
_remoteConfiguration.tokenSwapURL = kMXMSpotifySwapURL;
_remoteConfiguration.tokenRefreshURL = kMXMSpotifyTokenRefreshServiceURL;
```

SPTAppRemote init

```
_appRemote = [[SPTAppRemote alloc] initWithConfiguration:_remoteConfiguration
                                                 logLevel:SPTAppRemoteLogLevelDebug];
_appRemote.connectionParameters.accessToken = [self getAccessToken];
_appRemote.delegate = self;
```

On applicationDidBecomeActive

```
if (self.appRemote.connectionParameters.accessToken && !self.appRemote.connected) {
    [self.appRemote connect];
}
```

Same error even if I try to do manual connect

`[self.appRemote authorizeAndPlayURI:@""];`

The other 2/10 times everything works perfect!

Anyone had same issue? There's something I can do to solve it?

**Comment by martinobonfiglioli** [comment]
I solved my issue by adding a delay on `connect` call when application did become active
I know that this SDK isn't thread safe and all the API work in the main thread but for some reason I cant start the connection process immediately after the app startup, I need to wait some second

**Comment by sslash** [comment]
> I solved my issue by adding a delay on `connect` call when application did become active
> I know that this SDK isn't thread safe and all the API work in the main thread but for some reason I cant start the connection process immediately after the app startup, I need to wait some second

This is so strange. I could not get `appRemoteDidEstablishConnection` to trigger unless I added a 1 second delay before calling `appRemote.connect()`. Are you doing this in a production app? Seems a bit dangerous to rely on doing this..
