### ISSUE TITLE
Inconsistent / broken auth experience in bundled *demo* app? (Simple Track Playback Example)

### ISSUE THREAD

**Issue by trufflin** [spotify/ios-sdk#730]
I sent my Spotify-integrated app to a friend to test, and she's experiencing very odd login behavior. In desperation, I started looking at the bundled SimpleTrackPlayback demo app, to see what I might be doing wrong. However, both she and I experience auth issues even with the demo app: 

iPhone 6, iOS9+, Beta20
For ref, I have both the native Spotify and FB apps also installed, and I am also auth-ed on FB in Safari. 

SimpleTrackPlayback Demo app, with no changes whatsoever: 

* Attempt to login to demo
* Switches to Spotify app briefly
* Switches back to demo app, just sits at "Logging in ..." screen
* Console log shows: "Simple Track Playback[1823:721828] *** Auth error: Error Domain=com.spotify.auth Code=0 "unknown_error" UserInfo={NSLocalizedDescription=unknown_error}"

If I set "auth.allowNativeLogin = NO" in the demo app, it works on my device, but still fails on my friend's, which is a second mystery. The third and final mystery is why my own app's login flow behavior is also broken, but in a different way. If nothing else, it seems like the desperation move of "auth.allowNativeLogin = NO" does not always guarantee that login flow will remain within the app (this is the behavior she is getting). 

There are a lot of open issues related to similar login questions. I'm hoping that fixing / explaining the demo app behavior will be easier, since there's no question what the code looks like. 

Thanks in advance.

**Comment by trufflin** [comment]
The issues I experienced are at least partly due to my unfamiliarity with SSO. I changed the demo app to point to my own Spotify clientId and to use my registered bundleId, updated my bundleId on the Spotify dev portal*, updated all the required callback URIs locally and on my token swap service, and the app flip-flop began to work properly. Not sure if these steps are stated somewhere in the demo notes; if not, perhaps it could be clarified for others trying to get a handle on all the various login mechanisms and flows. 

Regarding my own app, I seem unable to prevent my friend's device from using SSO, so I have implemented the appropriate URL handling in the app delegate, and will see if that works. I am unable to get my device to SSO for my app, for some reason, so will wait to hear from my friend before closing this thread. Hope this is helpful to someone else. 

* Thanks to another SDK user on this forum for the "update bundleId on the dev portal" tip.

**Comment by trufflin** [comment]
OK, so now, even in the demo app, which worked an hour ago, I am getting this: 
Error Domain=com.spotify.auth Code=0 "unknown_error" UserInfo={NSLocalizedDescription=unknown_error}

Exact same behavior as this dev:
https://github.com/spotify/ios-sdk/issues/631

I have confirmed my bundleId is correct in my developer account on Spotify, not sure what else to do. It's occurring 100% of the time.

**Comment by cameronehrlich** [comment]
I ran into this error too, if you kill the native spotify app first and then try again, it should authorize successfully.  For now, I just disabled native authentication to avoid this bug.  
`auth.allowNativeLogin = NO;`

**Comment by trufflin** [comment]
Hey @cameronehrlich, thanks for the reply. Likewise, I am sticking to "allowNativeLogin = NO" for now as well. Another problem, though, is that my tester's device is still exiting my app when she attempts to login using Facebook, instead of just bringing up the manual embedded FB dialog within the Spotify / SPTAuthVC flow. It then never returns to my app, breaking login flow. Did you deal with that somehow as well?

**Comment by NOlivNeto** [comment]
@trufflin I have experienced it with both the android and iOS spotify SDKs. I actually think it's an issue with the Spotify App. https://github.com/spotify/android-sdk/issues/261

**Comment by trufflin** [comment]
Hey @NOlivNeto, thanks for the cross-ref, that does sound like similar behavior. I have my app out to another friend who will be testing w/FB login on iOS, so curious to see what behavior he gets.

**Comment by d-kunin** [comment]
@trufflin this issue seems to be the same as https://github.com/spotify/ios-sdk/issues/650 
Could you please point out the difference and close it if there is none?

**Comment by trufflin** [comment]
Yep, it does seem to be a dupe. Thanks, all.
