### ISSUE TITLE
Unavailable tracks silently fail to play/queue in Beta20

### ISSUE THREAD

**Issue by gchilds** [spotify/ios-sdk#731]
In Beta 17 when I play a track unavailable in my territory (AU) via a global URI, the Simple Track Playback app

 1. calls `didFailToPlayTrack`, and
 2. skips to the next track

e.g. `playURIs`(["spotify:track:7ueLs9KrHvrGIydo6IjyPV", "spotify:track:1RTK4s1cXfkgNT7cbxeMQz"])

In Beta 20, neither of these things happen when you `playURI` the first and `queueURI` the second track, although `didChangePlaybackStatus` is called with `isPlaying = false`. 

Also, `queueURI` reports success, yet fails silently.

The automatic skipping was useful in the previous SDK, where you could be certain of what your next track was, but I would argue for not bringing it across to Beta 20.

But we **must** know when the track has failed to play or queue. These calls shouldn't fail silently.

**Comment by CVertex** [comment]
We are seeing the same thing too.

In older SDK version, playing an unplayable track would call `didFailToPlayTrack`, then skip.
Now, it's just stalling playback and failing silently.

In beta20, it seems to be _trying_ to link a source track URI to a territory track URI, but when it can't find one, it fails.

This is going to affect our app too. 

@d-kunin Could you please address this in beta 21?
When a track URI can't played/enqueued (even after relink attempts), could the SDK please call didFailToPlayTrack?

**Comment by NickCJ83** [comment]
I'm seeing this too. Starting to feel a bit hopeless now with this SDK :(

**Comment by gchilds** [comment]
I'm sorry to see that this issue hasn't been tagged for beta 21. Working around this is not going to be fun - we can hackily try and guess if `playURI`/`queueURI` has failed by looking for unsolicited `isPlaying` being set to `false` or trying to second guess which tracks will fail by hitting the `tracks` API  to query if a URI is available in your market. 

or swizzling something in the SDK itself to surface the error? any pointers would be greatly appreciated.

**Comment by d-kunin** [comment]
It seems like we wont fix it for quining/playlists etc case. The reason is that you are supposed to get URIs from web api that does not return you unavailable tracks. 

I also want to point you out that the ToC that does not permit storing/caching of the URIs [Section IV. Local Caching](https://developer.spotify.com/developer-terms-of-use/).

We will try to give you an event/hint for a single track, but for the playlist it is not possible and not planned.

Sorry guys.

**Comment by gchilds** [comment]
Thanks for the update, @d-kunin 

I don't understand why this is complex.
We want the SDK to return an error for a track URI cannot be played for whatever reason.
The previous beta error'd through didFailToPlay and skipped the track.
Maybe this is complex, but if the track failed to play, could the SDK properly use the error callback, instead of being silent.

This makes common sense to me from an engineering and code quality point of view.
