### ISSUE TITLE
URGENT - Community feedback - Proposal Beta 21

### ISSUE THREAD

**Issue by MuruMusic** [spotify/ios-sdk#732]
This is a community call out - Feedback welcome

I have already reached out to some of you privately, to get a better understanding of what the urgent issues are in this beta 20.

This thread’s main goal is to identify issues which prevent me and others from shipping app updates. It’s been months since I’ve shipped an update, as this SDK has been a roadblock.

Some “low hanging fruit” could be addressed quickly and it is my suggestion we focus on them first.

After speaking with several of you, the following issues are urgent:

https://github.com/spotify/ios-sdk/issues/731 - Unavailable tracks silently fail to play/queue
https://github.com/spotify/ios-sdk/issues/722 - allowCaching and diskCache bugs
https://github.com/spotify/ios-sdk/issues/724 - Track URIs being remapped
https://github.com/spotify/ios-sdk/issues/721 -  iOS 7 - login web view fails

If anyone has other critical issues, please add a comment below.

@d-kunin  please let us help you, help us. It would be amazing if we could work together to get the above issues fixed ASAP, so that all of us can actually ship our product. Please understand how serious this is affecting us.

We are happy to work with you to get through these bugs quickly.

I think this could be a good approach for the next release. Beta 22 can focus on major changes and complex issues.

Guys - lets all help where we can. 
@d-kunin  - please give us a timeline and what you need from us, to make this happen asap.

Much appreciated peeps.

**Comment by NickCJ83** [comment]
Yup @MuruMusic this works for me - i think #718  is also annoying but can wait.

Just want to be able to deploy my app, but if we do now, its bug central and no way of going back!

**Comment by erdtman** [comment]
We are sorry about the inconveniences that the update caused.
We are working on a beta 21 release you can monitor whats included by the label "beta 21" (https://github.com/spotify/ios-sdk/issues?q=is%3Aissue+is%3Aopen+label%3Abeta-21)

As you can see #721, #724, and #718 is included as of now.

We will consider #731 and #722 for the next release.

**Comment by MuruMusic** [comment]
@erdtman thank you for responding. I encourage others to weigh in here, but #731 is a pretty big problem for us - We can't reliably deploy our app with this failing. Do you have a work around for this at all? Otherwise I would kindly urge you to include it with beta 21.

**Comment by gchilds** [comment]
@erdtman we're having to do some epic workarounds to make our app work with this build, #731 is literally a showstopper for us.

**Comment by d-kunin** [comment]
Please see my response for #731 https://github.com/spotify/ios-sdk/issues/731#issuecomment-242461530

I closing this one since we have planned beta 21 already as @erdtman have mentioned and it is really unlikely for us to add #722 to it.
