### ISSUE TITLE
tvOS build target

### ISSUE THREAD

**Issue by matijse** [spotify/ios-sdk#736]
The changelog of beta20 describes the option to disable caching for use on tvOS. (https://github.com/spotify/ios-sdk/blob/master/CHANGELOG.md)

I've created a sample application, but although everything seems to work, when running/building, I get a warning that the SDK is not build for tvOS (only iOS). 

Was this just a preliminary test, or can we expect a build for tvOS in a future beta? As I understand, with the current build, we can only develop and test, but not submit to the app store.

These are the warnings I get (a lot, each for a different file in the SDK)

```
URGENT: building for tvOS simulator, but linking in object file (<project_dir>/Spotify.framework/Spotify(SPTAudioStreamingController.o)) built for iOS. Note: This will be an error in the future.
```

**Comment by d-kunin** [comment]
The current `support` for tvOS is for testing purposes only. We have plans to support tvOS, but we dont have any terms that I can announce.

**Comment by loretoparisi** [comment]
@d-kunin thanks for the update, this is a very old issue well discussed [here](https://github.com/spotify/ios-sdk/issues/443), maybe you could label that issue as `feature request`. Thank you.
