### ISSUE TITLE
Beta 21 works perfect!

### ISSUE THREAD

**Issue by Anders27** [spotify/ios-sdk#740]
For my needs, beta 21 works perfect.
Thanks!

Minor thing:
The documentation (and also comments in some header files) needs to be updated,
especially important for developers that are new to the SDK.

**Comment by erdtman** [comment]
Thanks!

Are you referring to the [API documentation](https://developer.spotify.com/ios-sdk-docs/Documents/index.html), or the [getting started tutorial](https://developer.spotify.com/technologies/spotify-ios-sdk/tutorial/)?

**Comment by Anders27** [comment]
API documentation, haven't looked at the getting started tutorial.

For example:

In the Spotify doc set for beta 21

SPTAudioStreamingDelegate
doesn’t list
didReceiveError

SPTAudioStreamingPlaybackDelegate
still lists
audioStreaming:didFailToPlayTrack:

etc

Headers lacks comments or are wrong:

SPTAudioStreamingController.h

/** Returns `YES` if repeat is on, otherwise `NO`. */
@property (atomic, readonly) SPTVolume volume;

No comments:

-(void)audioStreaming:(SPTAudioStreamingController *)audioStreaming didReceivePlaybackEvent:(SpPlaybackEvent)event withName:(NSString*)name;

-(void)audioStreaming:(SPTAudioStreamingController *)audioStreaming didChangePosition:(NSTimeInterval)position;

**Comment by Voxar** [comment]
Thank you for the list! Fixed in upcoming b22
