### ISSUE TITLE
b20/21 -- Caching API 

### ISSUE THREAD

**Issue by drew55** [spotify/ios-sdk#745]
In b20, the caching API changed.  With previous betas, the caching API offered `.totalSize` to let us know the total byte size of the object being written out, allowing us to offer a graphical feedback for what part of the track data has been obtained.  In the attached screenshot, note the green shaded areas representing the data obtained (it's fragmented because I shuttled around to different parts of the track before I took the screenshot).

In b20/21, `.totalSize` seems to now be set to the size of `.data` rather than the total size of the data item.  Since the graphical representation of the track data is such a nice feature of our player, we ask that the ability to know the total data object size is somehow reported (or, that `.totalSize` goes back to containing the total byte size of the cache data item).

Thanks!

![tunr](https://cloud.githubusercontent.com/assets/20958826/18217025/161554e8-7120-11e6-8221-7f99fd6b4a6d.jpg)

**Comment by Voxar** [comment]
Hi!

That's a cool feature indeed! We're simplifying the base implementations a bit but you can implement your own `SPTDiskCaching` if you need more features. See `SPTDiskCaching.h` and `SPTAudioStreamingController.diskCache`!

**Comment by drew55** [comment]
@Voxar 

Hi!  Finally getting back into this issue after a while!

The current caching API is perfect -- good job to the team for making this happen and is making our software look and run great with Spotify!  Can't wait for y'all to see it!
