### ISSUE TITLE
SPTAudioStreamingController loginWithAccessToken results to "audioStreaming:didReceiveError:withName: unrecognized selector sent to instance"

### ISSUE THREAD

**Issue by ozzotto** [spotify/ios-sdk#747]
Though the `SPTAudioStreamingDelegate` method `-(void)audioStreaming:(SPTAudioStreamingController *)audioStreaming didReceiveError:(SpErrorCode)errorCode withName:(NSString*)name;` is marked as optional when calling `loginWithAccessToken` causes "unrecognized selector sent to instance".

**Comment by erdtman** [comment]
I have fond the issue, we did not check the selector availability in all places, I will try to include it in beta 22

**Comment by erdtman** [comment]
beta 22 has now been released
