### ISSUE TITLE
Unable to set repeat status but SPTPlaybackState has an isRepeating property

### ISSUE THREAD

**Issue by cjwhitsitt** [spotify/ios-sdk#749]
In beta 21, I'm unable to find a way to change the repeat status even though the `SPTPlaybackState` has an `isRepeating` property. It's always false since I can't figure out how to set it.

I also noticed that the documentation online and in the header files don't agree. The online documentation includes a repeat property still on the `SPTAudioStreamingController` but the header file does not. The header file also includes this:

```
/** Returns `YES` if repeat is on, otherwise `NO`. */
@property (atomic, readonly) SPTVolume volume;
```

That comment used to be for the `repeat` property that was removed according to the changelog.

**Comment by cjwhitsitt** [comment]
I just looked at a diff and realized the comment was there in beta 20. Regardless, it would be nice to have that comment corrected for clarity.

**Comment by erdtman** [comment]
Thanks for reporting this, we will update the documentation and expose shuffle and repeat functions.

**Comment by erdtman** [comment]
beta 22 has now been relesed
