### ISSUE TITLE
Adding a track to a playlist

### ISSUE THREAD

**Issue by markstuartwalker** [spotify/ios-sdk#75]
The iOS SDK doesn’t seem to include all of the functionality of the web API. Specifcically the ability to add tracks to a playlist.

Is the intention to grow the SDK until it is fully featured or should I mix the SDK alongside the API? And are the tokens equivalent on both systems?

**Comment by fotiDim** [comment]
@markstuartwalker you can use the token you get from the SDK on the API. Just make sure you request the appropriate scopes first.
