### ISSUE TITLE
Is possible to login wihtout going over the web site?

### ISSUE THREAD

**Issue by escamoteur** [spotify/ios-sdk#751]
Hi,

I'm planing an App for small Kids. Obviuosly they are not able to enter the login credentials for Spotify. So their parents would need to do this. As it's not a solution for the kids to always ask their parents when they want to hear music I need a solution to store the credentials on the device after entering once.

Is this in any way possible?

Best
Thomas

**Comment by erdtman** [comment]
Use the code grant flow to get a god that is swapped for a access token and a refresh token. the refresh token can then be used to get new access tokens creating a long lived session.
There is a ruby example of the server implementation in the demo project and it is documented how to build your own here https://developer.spotify.com/technologies/spotify-ios-sdk/token-swap-refresh/
To get some more context see https://github.com/spotify/ios-sdk/issues/617

**Comment by escamoteur** [comment]
Yes, but this will only work as long as the App is running or do I missunderstand this? Doesn't the refresh token time out too?

Best
Tom

**Comment by erdtman** [comment]
The refresh token has a very long time to live, so to avoid multiple logins we recommend the use of refresh token.

**Comment by escamoteur** [comment]
How long? So I would just store the refresh token and request a new authtoken at App Startup?

**Comment by erdtman** [comment]
Don´t know the exact time, but is long and it is the best you would get. Exactly you can request a new access token with the refresh token at App Startup. The important thing is that it is strongly recommended that the token request is done from your backend so that the client secret is not compiled into the client.

**Comment by escamoteur** [comment]
So I would need a separate server for my App. What harm could be done with the secret key? Without a user login there could not be done much?
