### ISSUE TITLE
Token refresh after app access revoked returns invalid JSON

### ISSUE THREAD

**Issue by matijse** [spotify/ios-sdk#752]
According to https://developer.spotify.com/news-stories/2016/07/25/app-ready-token-revoke/ the API will return an error when trying to refresh a token of which the owner has revoked access to your app.

However, when I refresh with beta 21, I get an error of malformed JSON:

```
Error Domain=NSCocoaErrorDomain Code=3840 "JSON text did not start with array or object and option to allow fragments not set." UserInfo={NSDebugDescription=JSON text did not start with array or object and option to allow fragments not set.}
```

The following code generates this error:

```
let auth = SPTAuth.defaultInstance()
auth.renewSession(auth.session, callback: { (error: NSError!, session: SPTSession!) -> Void in
    if error != nil {
        print(error)
    }
})
```

**Comment by erdtman** [comment]
I will need some more information, I have tested to setup Simple Track Player with the ruby script and I get the actual error.

`2016-09-19 12:00:11.919 Simple Track Playback[60674:942105] *** Error renewing session: Error Domain=com.spotify.auth Code=400 "Refresh token revoked" UserInfo={NSLocalizedDescription=Refresh token revoked}`

Are you using the example script or have you implemented your own back-end?

**Comment by matijse** [comment]
Ah right... Didn't realise the back-end script handles this... I have a custom back-end, so I assume the error comes from there. I will re-open if I find an error on the Spotify side.

Thanks.
