### ISSUE TITLE
Get recently played songs

### ISSUE THREAD

**Issue by ProgrammerHugo** [spotify/ios-sdk#754]
Hi ,  for an upcoming project the customer needs to get the recently played songs from the logged user.  Can the SDK retrieve this? I searched the documentation and internet without luck

**Comment by erdtman** [comment]
No, it is not possible to get this via the SDK since the web-api that the iOS-SDK wraps does not support it.

Sorry for not being able to give you a more positive answer.

**Comment by jordancdavis** [comment]
The web-api supports recently played songs. the iOS-SDK does not because the scope is not provided during authentication.

https://developer.spotify.com/web-api/console/get-recently-played/

**Comment by jalleyne** [comment]
@erdtman any update on this given @jordancdavis response?
