### ISSUE TITLE
queueSpotifyIRI: will not replace a previously queued URI

### ISSUE THREAD

**Issue by alexcone** [spotify/ios-sdk#755]
I play track A with playSpotifyURI:startingWithIndex:startingWithPosition:callback:
when I receive a didChangeMetadata: I queue track B with queueSpotifyURI:callback:
- user requests track C to be played after track A
I try to change the queued track with queueSpotifyURI:callback: but the next remains track B (both by checking the nextTrackMetadata and by simply waiting for the track to roll after track A completes)

only playSpotifyURI seems to clear the queued track, and calling it with the currently playing track produces audible artifacts

if the SDK no longer allows us to build and manage an arbitrary length list of tracks and we are limited to a single queued track, we need to be able to change the queued track while the current track is playing.

**Comment by erdtman** [comment]
There is no direct replacement for playURIs. The idea is that you should work with Spotify playlists and not compile playlists outside of Spotify and only using Spotify as source for the raw song.

see also #742 

Sorry for the inconvenience
