### ISSUE TITLE
Logout method from STPAuth?

### ISSUE THREAD

**Issue by bensebborn** [spotify/ios-sdk#757]
Hi

I can see discussions around a logout method from the streaming View Controller. However, we don't use this, so we're wondering if there's a way to force a logout?

We're using STPAuthViewController to initiate the login.

Can we just set auth.session = nil?

Thanks

**Comment by erdtman** [comment]
What do you want to achieve?

**Comment by skiddle** [comment]
We want to let the user authenticate as a different user. Ideally via a manual logout action, rather than prompting for authentication each time they use the feature

**Comment by erdtman** [comment]
To login (authorize access for) a new user with the STPAuthViewController, you can start by calling the clearCookies function. after that the user will have to login again. For the streaming controller, use the logout and loginWithAccessToken functions. you should not need to stop and start it.

If you want the session to be longer than one hour for a user use the code flow and refresh token, see https://developer.spotify.com/web-api/authorization-guide/

**Comment by bensebborn** [comment]
Thanks works, thanks

**Comment by ozgemutlu** [comment]
Please help, I have a problem with Spotify API. I used Spotify API on my Spring Boot project. I can log in and do whatever I want after authorization but if I click the button "Not You?" on the Spotify Dialog after login and then try to log in again, it says "Wrong User Name Or Password",  I can't login again. What am I doing wrong ? Do I need to clear cookies for "account.spotify.com" ? How can I do that if it is ?  I can only login again if I authorize again from the beginning not by clicking "Not You?". Sorry for my English, hope you all understand my problem.
