### ISSUE TITLE
Xcode 8 warnings

### ISSUE THREAD

**Issue by iwasrobbed** [spotify/ios-sdk#758]
Seeing this error while using Xcode 8 and isolated it to the Spotify framework:

> Some object files have incompatible Objective-C category definitions. Some category metadata may be lost. All files containing Objective-C categories should be built using the same compiler.

Is it possible for you all to re-generate the framework using Xcode 8? 🙏

**Comment by erdtman** [comment]
This will happen, but we cannot say when. It depends on when the build servers for the SDK will be updated.

Sorry for the inconvenience.

**Comment by DmytroAnkudinov** [comment]
"Beta-24" release has been built using XCode 8. @iwasrobbed  could you please confirm that the issue is no longer present.

**Comment by iwasrobbed** [comment]
@DmytroAnkudinov Sorry for the delay; I wasn't expecting that big of an API change in the new build so I won't be able to integrate it immediately. I'll check back in soon once I get time

**Comment by DmytroAnkudinov** [comment]
iOS SDK is now built with XCode 8. If you still experience issues and warnings, please open a new issue for the latest version of SDK.
