### ISSUE TITLE
Use of iOS-SDK tokens for the web API

### ISSUE THREAD

**Issue by markstuartwalker** [spotify/ios-sdk#76]
Is it possible to use the tokens from iOS-SDK authentication for web API authentication?

I wish to use the authentication token from iOS-SDK to make authenticated Web API calls. Is this possible?

**Comment by auriga-dev** [comment]
yes it is I've been doing that

**Comment by arirawr** [comment]
Hey @markstuartwalker, yes, that is possible. You just need to make sure your token has the right [scopes](https://developer.spotify.com/documentation/general/guides/scopes/).
