### ISSUE TITLE
Beta 22: `SPTPlaylistSnapshot +playlistsWithURIs...` is gone.

### ISSUE THREAD

**Issue by mhuusko5** [spotify/ios-sdk#761]
## Description
`SPTPlaylistSnapshot +playlistsWithURIs:session:callback:` is gone, and no `SPTPlaylistSnapshot +playlistsWithURIs:accessToken:callback:` was added in its place.

### Severity
Major

**Comment by Voxar** [comment]
Thank you for notifying us! We're moving fast and breaking things. We'll look things through and push a new version.

**Comment by mhuusko5** [comment]
No problemo, breaking stuff is fine as long things do indeed move fast. Looking forward to a fix :)

Thanks for the quick response!

**Comment by Voxar** [comment]
Thanks!
