### ISSUE TITLE
in b23 seekTo: and playSpotifyURI: ignore fractional target track position

### ISSUE THREAD

**Issue by alexcone** [spotify/ios-sdk#762]
## Description
Our app needs to seek to a precise position.  If I seek to a position of 20.75 the callback didSeekToPosition shows the seek went to 20.00 seconds into the stream

### Versions
iOS SDK version
Beta 23

### Severity
Very Severe as it breaks a significant aspect of our application.

## Steps to Reproduce
Call SPTAudioStreamingController's seekTo: with a position of 20.75
Print out the position returned in didSeekToPosition: to see the position is exactly 20.00

### Actual behavior
Seeks are rounded down to the nearest whole integer seconds value.  Sub-second seeks are ignored.

### Expected behavior
Seeks should seek to the exact position requested (as it did in previous SDK versions)

## Logs
Playhead position check found position delta 0.7300.
 - Playhead positioning requested: 593.7300 current: 593.0000.
Playhead positioning seek completed with position 593.0000 (requested:  593.7300 - delta 0.7300).

**Comment by erdtman** [comment]
I have identified the bug and will create a fix for next release.
We are expecting to release next version by the end of next week.

**Comment by erdtman** [comment]
Should be resolved in the 24 release.
