### ISSUE TITLE
Add header to Spotify Refresh/Swap Token?

### ISSUE THREAD

**Issue by ClockWise89** [spotify/ios-sdk#763]
I'm implementing an app which requires the authorization code flow, i.e. I will need the swap and refresh service to allow the user to only log in once. We have currently set up both services on our backend, and when we try locally it works fine (not used in app though). But when I specify the same urls in the app and try to run my login fails with an error code of -1012, and the following message:
`Error Domain=NSURLErrorDomain Code=-1012 "(null)" UserInfo={NSErrorFailingURLStringKey=http://mybackend.com/spotifyswaptoken, NSUnderlyingError=0x7ffde932ce70 {Error Domain=kCFErrorDomainCFNetwork Code=-1012 "(null)" UserInfo={_kCFURLErrorAuthFailedResponseKey=<CFURLResponse 0x7ffde60b2960 [0x105cc7a40]>{url = http://mybackend.com/spotifyswaptoken}}}, NSErrorFailingURLKey=http://mybackend.com/spotifyswaptoken}`

When we run our scripts locally without using the app they seem to work as they should. Our backend require a token in the header to be able to be reached, could this cause issues? Since I only set the urls I can't specify how they are being called and thus I can't append our header token to the backend. Could this be the issue, and is it possible to set the header for the swap/refresh service?

Without specifying swap/refresh urls everything works fine, except that the user needs to login every hour.

**Comment by erdtman** [comment]
It sounds likely the issue, that you cannot add the header that your back-end requires.

We have no current plans to update this, but the functionality of token swap and refresh is relatively simple so I would recommend you to have a look at implementing the back-end calls for swap and refresh on your own.

Have a look at the flows chart [here](https://developer.spotify.com/web-api/authorization-guide/#authorization-code-flow)
Things to note, in step one you can redirect to the spotify client directly using spotify-action://authorize?client_id=123&...

**Comment by ClockWise89** [comment]
Hi, thanks for the quick answer. I managed to get our backend developers to remove the token requirement in the header and now it seems to work.
