### ISSUE TITLE
Get current playing track info - Spotify API

### ISSUE THREAD

**Issue by jiamijongejan** [spotify/ios-sdk#764]
At the moment I'm working on a Spotify API Swift app. Now I want to get the current playing track name, artist name and the cover image showing up in the ViewController. But I don't know exactly how I can get them. (It's my first time working with an API like this and also Swift, haha)

I'm working with the Spotify API documentation for iOS (https://developer.spotify.com/technologies/spotify-ios-sdk/), this is written in ObjectiveC, but I'm working in Swift. In the ObjectiveC example, I see something like this:

`self.trackTitle.text = self.player.metadata.currentTrack.name;`
But this isn't really working for Swift?,

I found this code to print the track name, but this one isn't showing up on the ViewController. And if I make a label, and print the 'trackName', in the label, I got a error like: Use of unresolved identifier.

```
func audioStreaming(audioStreaming: SPTAudioStreamingController!, didStartPlayingTrack trackUri: NSURL!) {      
        let trackName = audioStreaming.currentTrackMetadata[SPTAudioStreamingMetadataTrackName] as! String

        print(trackName)
    }


songTitle.text = String(trackName)
```

Does anyone know, how I can print the current track in the ViewController?

**Comment by erdtman** [comment]
Have you seen https://www.youtube.com/watch?v=GeO00YdJ3cE all details are not up to date but the general concept is right.

**Comment by jiamijongejan** [comment]
Yeah, I saw that one, but that one isn't in Swift..

**Comment by erdtman** [comment]
I might be wrong but the title says "iOS Swift Tutorial: Stream Music from Spotify" and to me the code looks like swift.

**Comment by erdtman** [comment]
Any success here?

**Comment by erdtman** [comment]
Since I have not gotten any feedback on this I will close this issue, but feel free to reopen.

**Comment by hoonk** [comment]
Set these delegates `SPTAudioStreamingDelegate, SPTAudioStreamingPlaybackDelegate`

Somewhere, set the delegates to the viewController, e.g. `player.delegate = self; player.playbackDelegate = self`

Then, using this delegate function, you should get the data whenever the player's meta data changes.

```
func audioStreaming(_ audioStreaming: SPTAudioStreamingController!, didChange metadata: SPTPlaybackMetadata!) {
        print("Spotify Meta Data Changed")
}
```
