### ISSUE TITLE
[SPTListPage requestNextPageWithSession:callback:] is still failing

### ISSUE THREAD

**Issue by JwJason** [spotify/ios-sdk#767]
## Description
#481 is still a problem.
### Versions

iOS SDK version = 21
### Severity

Major
## Steps to Reproduce

Using [SPTListPage requestNextPageWithSession:callback:], OR creating my own custom method for fetching list pages (using [SPTRequest createRequestForURL ...]), I'll sometimes get a 502 bad gateway error (which won't be reported as an error by the SDK, unless I roll my own custom method and check the HTTP response code).

**Comment by erdtman** [comment]
We are deprecating the iOS-Metadata library.

The source code of the iOS-Metadata library has been released and can be found here. Spotify will not continue to maintain the released source code.

Either you can select to use the web-api directly or use the new open source iOS-Metadata library.

I will close this issue now.

We are sorry for the inconvenience that this creates, but looking back we think this is the best path forward.
