### ISSUE TITLE
[NSJSONSerialization JSONObjectWithData:options:error:] -> [NSException raise:format:]

### ISSUE THREAD

**Issue by Anders27** [spotify/ios-sdk#768]
In “Xcode - Organizer - Crashes” I see a couple of crash reports for my app like the one below:

Thread 0 Crashed:
0   libsystem_kernel.dylib          0x000000018121011c **pthread_kill + 8
1   libsystem_pthread.dylib         0x00000001812dcef8 pthread_kill + 112 (pthread.c:1247)
2   libsystem_c.dylib               0x0000000181181dc8 abort + 140 (abort.c:91)
3   libc++abi.dylib                 0x0000000180cb53f4 abort_message + 132 (abort_message.cpp:47)
4   libc++abi.dylib                 0x0000000180cd1e98 default_terminate_handler() + 304 (cxa_default_handlers.cpp:67)
5   libobjc.A.dylib                 0x0000000180cdc248 _objc_terminate() + 124 (objc-exception.mm:678)
6   libc++abi.dylib                 0x0000000180ccef44 std::__terminate(void (*)()) + 16 (cxa_handlers.cpp:62)
7   libc++abi.dylib                 0x0000000180cce85c __cxa_throw + 136 (cxa_exception.cpp:147)
8   libobjc.A.dylib                 0x0000000180cdc094 objc_exception_throw + 332 (objc-exception.mm:568)
9   CoreFoundation                  0x0000000181676cf8 +[NSException raise:format:] + 120 (NSException.m:140)
10  Foundation                      0x0000000181fd149c +[NSJSONSerialization JSONObjectWithData:options:error:] + 76 (NSJSONSerialization.m:1907)
11  myApp                               0x0000000100101cf0 +[SPTListPage listPageFromData:withResponse:expectingPartialChildren:rootObjectKey:error:] + 100
12  myApp                               0x0000000100102060 __53-[SPTListPage requestPageAtURL:accessToken:callback:]_block_invoke + 168
13  libdispatch.dylib               0x00000001810c14bc _dispatch_call_block_and_release + 24 (init.c:760)
14  libdispatch.dylib               0x00000001810c147c _dispatch_client_callout + 16 (object.m:506)
15  libdispatch.dylib               0x00000001810c6b84 _dispatch_main_queue_callback_4CF + 1844 (inline_internal.h:1063)
16  CoreFoundation                  0x000000018162cd50 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE** + 12 (CFRunLoop.c:1613)
17  CoreFoundation                  0x000000018162abb8 __CFRunLoopRun + 1628 (CFRunLoop.c:2718)
18  CoreFoundation                  0x0000000181554c50 CFRunLoopRunSpecific + 384 (CFRunLoop.c:2814)
19  GraphicsServices                0x0000000182e3c088 GSEventRunModal + 180 (GSEvent.c:2245)
20  UIKit                           0x0000000186842088 UIApplicationMain + 204 (UIApplication.m:3772)
21  myApp                               0x000000010000809c main + 84 (main.m:15)
22  libdyld.dylib                   0x00000001810f28b8 start + 4 (start_glue.s:78)

Why does this happen?
Is there some trouble with some of the Spotify files? 

9   CoreFoundation                  0x0000000181676cf8 +[NSException raise:format:] + 120 (NSException.m:140)
10  Foundation                      0x0000000181fd149c +[NSJSONSerialization JSONObjectWithData:options:error:] + 76 (NSJSONSerialization.m:1907)

The crashes occurs on both iOS 9 and 10. I’m currently using Beta 21 of the Spotify SDK

**Comment by erdtman** [comment]
We are deprecating the iOS-Metadata library.

The source code of the iOS-Metadata library has been released and can be found here. Spotify will not continue to maintain the released source code.

Either you can select to use the web-api directly or use the new open source iOS-Metadata library.

I will close this issue now.

We are sorry for the inconvenience that this creates, but looking back we think this is the best path forward.

**Comment by Anders27** [comment]
Too bad!

Where do we find the new open source iOS-Metadata library?

**Comment by erdtman** [comment]
sorry missed the link in this reply, you find it [here](https://github.com/erdtman/spotify-ios-metadata/)
