### ISSUE TITLE
didChangeToTrack or didReceivePlaybackEvent Not called in beta 22 or 23

### ISSUE THREAD

**Issue by GabeJacobs** [spotify/ios-sdk#771]
Hey,

I was wondering if anyone else was experiencing this issue. I'm trying to get a notification when a song ends, but since upgrading from beta 21, it not longer works. I usually do something like this:

```
- (void)audioStreaming:(SPTAudioStreamingController *)audioStreaming didChangeToTrack:(NSDictionary *)trackMetadata {
	if (trackMetadata == nil) {  // Finished playing track.
		self.spotifyFinishCallback(self);
	}
}
```
But now the delegate call doesn't happen even after a song finishes. I went back to beta 21 and it works fine. Any idea?

**Comment by alexcone** [comment]
The delegate pattern has changed - we get a didChangeMetadata: callback now and one must see what has changed to determine next action...

**Comment by Voxar** [comment]
As @alexcone says a bunch of things changed between 21 and 22. Please review [the changelog](https://github.com/spotify/ios-sdk/blob/master/CHANGELOG.md)

Also see `- (void)audioStreaming:(SPTAudioStreamingController *)audioStreaming didStartPlayingTrack:(NSString *)trackUri;` for change of track notification.
