### ISSUE TITLE
Beta 23: SPTPlaylistSnapshot +playlistWithURI is gone

### ISSUE THREAD

**Issue by JwJason** [spotify/ios-sdk#775]
SPTPlaylistSnapshot +playlistsWithURIs was added back into Beta 23. However, SPTPlaylistSnapshot +playlistWithURI was not.

**Comment by Voxar** [comment]
Hi!

Is this what you are looking for? https://github.com/spotify/ios-sdk/blob/master/Spotify.framework/Versions/A/Headers/SPTPlaylistSnapshot.h#L98

**Comment by erdtman** [comment]
We are deprecating the iOS-Metadata library.

The source code of the iOS-Metadata library has been released and can be found here. Spotify will not continue to maintain the released source code.

Either you can select to use the web-api directly or use the new open source iOS-Metadata library.

I will close this issue now.

We are sorry for the inconvenience that this creates, but looking back we think this is the best path forward.
