### ISSUE TITLE
PLAYLIST SORT BY DATE ADDED - REAL TIME CONNECT TO FRIENDS

### ISSUE THREAD

**Issue by joshbhill123** [spotify/ios-sdk#776]
I am writing to propose new features for Spotify on a mobile device either IOS or Android. 

Firstly, you should have the ability to sort songs within playlists by date added as it is frustrating constantly scrolling down to listen to my latest songs on a playlist on a mobile device. I acknowledge this feature is available on desktop version of Spotify.

Secondly, there should be a feature that enables your profile to connect to friends and visa versa so others can "piggyback" each other live streaming music.

Good musiking!!!

**Comment by Voxar** [comment]
Hi

Please check out https://community.spotify.com for Spotify app feature requests and help.

(you can sort playlists by "Recently added". Swipe downwards a little bit in the playlist view and tap the button to the right of the filter textbox)
