### ISSUE TITLE
delegate methoad's not calling ?

### ISSUE THREAD

**Issue by lovekes** [spotify/ios-sdk#777]
Spotify sample code delegate method's not call in iOS 9.3 .
my location India.
this issue comes in iPhone 5 , 5S
- (void)audioStreamingDidLogin:(SPTAudioStreamingController *)audioStreaming;
- (void)audioStreaming:(SPTAudioStreamingController *)audioStreaming didStartPlayingTrack:(NSString *)trackUri;

& etc........

any helps tell me. skype : lokeshkumawat27

**Comment by Voxar** [comment]
Thank you for reporting this @lovekes.

**Comment by Voxar** [comment]
We found the issue. Fixed in next version.
