### ISSUE TITLE
Spotify Playlist URL Debugger

### ISSUE THREAD

**Issue by SamwillChainsaw** [spotify/ios-sdk#780]
## Description
I would like to debug a Spotify playlist URL. I updated the playlist, but when I share the URL I can still see the old songs in my browser. Is there a tool with which I can force URL to update? If not, is there an option to create new URL link, without losing followers?

Thanks for your help,
Oskar

**Comment by erdtman** [comment]
Have you tried this using the web-api directly or only with the iOS-SDK?

**Comment by erdtman** [comment]
I will close this issue since I have not gotten any reply.
