### ISSUE TITLE
Beta 24 emits a lot of warnings

### ISSUE THREAD

**Issue by Anders27** [spotify/ios-sdk#782]
Trying out the new beta 24, emits a lot of warnings:

while processing /Volumes/Macintosh HD/programming/programming/iPhone/spotify-ios-sdk/SpotifyAudioPlayback.framework/SpotifyAudioPlayback(SPTCircularBuffer.o):
warning: /var/folders/lg/ssvy6y5n2g390pthrdmx54j000000w/C/org.llvm.clang.28/ModuleCache/25DR2ALIHKKZE/Darwin-1046FB3FTEP9R.pcm: No such file or directory
note: Linking a static library that was built with -gmodules, but the module cache was not found.  Redistributable static libraries should never be built with module debugging enabled.  The debug experience will be degraded due to incomplete debug information.

while processing /Volumes/Macintosh HD/programming/programming/iPhone/spotify-ios-sdk/SpotifyAudioPlayback.framework/SpotifyAudioPlayback(SPTCircularBuffer.o):
warning: /var/folders/lg/ssvy6y5n2g390pthrdmx54j000000w/C/org.llvm.clang.28/ModuleCache/25DR2ALIHKKZE/Foundation-2TOALRFTUZZRU.pcm: No such file or directory
while processing /Volumes/Macintosh HD/programming/programming/iPhone/spotify-ios-sdk/SpotifyAudioPlayback.framework/SpotifyAudioPlayback(SPTCircularBuffer.o):
warning: /var/folders/lg/ssvy6y5n2g390pthrdmx54j000000w/C/org.llvm.clang.28/ModuleCache/25DR2ALIHKKZE/ObjectiveC-2DLINTQGM7IIW.pcm: No such file or directory
while processing /Volumes/Macintosh HD/programming/programming/iPhone/spotify-ios-sdk/SpotifyAudioPlayback.framework/SpotifyAudioPlayback(SPTAudioStreamingController.o):
warning: /var/folders/lg/ssvy6y5n2g390pthrdmx54j000000w/C/org.llvm.clang.28/ModuleCache/25DR2ALIHKKZE/CoreGraphics-1BC0T5CZPMQIW.pcm: No such file or directory
while processing /Volumes/Macintosh HD/programming/programming/iPhone/spotify-ios-sdk/SpotifyAudioPlayback.framework/SpotifyAudioPlayback(SPTAudioStreamingController.o):
warning: /var/folders/lg/ssvy6y5n2g390pthrdmx54j000000w/C/org.llvm.clang.28/ModuleCache/25DR2ALIHKKZE/AudioToolbox-WAC3RDSIP57T.pcm: No such file or directory
while processing /Volumes/Macintosh HD/programming/programming/iPhone/spotify-ios-sdk/SpotifyAudioPlayback.framework/SpotifyAudioPlayback(SPTAudioStreamingController.o):
warning: /var/folders/lg/ssvy6y5n2g390pthrdmx54j000000w/C/org.llvm.clang.28/ModuleCache/25DR2ALIHKKZE/UIKit-3360QUVT1CRY3.pcm: No such file or directory
while processing /Volumes/Macintosh HD/programming/programming/iPhone/spotify-ios-sdk/SpotifyAudioPlayback.framework/SpotifyAudioPlayback(SPTAudioStreamingController.o):
warning: /var/folders/lg/ssvy6y5n2g390pthrdmx54j000000w/C/org.llvm.clang.28/ModuleCache/25DR2ALIHKKZE/CoreFoundation-K3IYNI87DKXK.pcm: No such file or directory
while processing /Volumes/Macintosh HD/programming/programming/iPhone/spotify-ios-sdk/SpotifyAudioPlayback.framework/SpotifyAudioPlayback(SPTAudioStreamingController.o):
warning: /var/folders/lg/ssvy6y5n2g390pthrdmx54j000000w/C/org.llvm.clang.28/ModuleCache/25DR2ALIHKKZE/SystemConfiguration-10T9PJ7OQ2U9B.pcm: No such file or directory
while processing /Volumes/Macintosh HD/programming/programming/iPhone/spotify-ios-sdk/SpotifyAudioPlayback.framework/SpotifyAudioPlayback(SPTAudioStreamingController.o):
warning: /var/folders/lg/ssvy6y5n2g390pthrdmx54j000000w/C/org.llvm.clang.28/ModuleCache/25DR2ALIHKKZE/Dispatch-BFRSA8R4BP7S.pcm: No such file or directory
while processing /Volumes/Macintosh HD/programming/programming/iPhone/spotify-ios-sdk/SpotifyAudioPlayback.framework/SpotifyAudioPlayback(SPTAudioStreamingController.o):
warning: /var/folders/lg/ssvy6y5n2g390pthrdmx54j000000w/C/org.llvm.clang.28/ModuleCache/25DR2ALIHKKZE/CoreAudio-17CB8LD96HBFY.pcm: No such file or directory
while processing /Volumes/Macintosh HD/programming/programming/iPhone/spotify-ios-sdk/SpotifyAudioPlayback.framework/SpotifyAudioPlayback(SPTCoreAudioController.o):
warning: /var/folders/lg/ssvy6y5n2g390pthrdmx54j000000w/C/org.llvm.clang.28/ModuleCache/25DR2ALIHKKZE/AudioUnit-RZC5H4E5C19H.pcm: No such file or directory
while processing /Volumes/Macintosh HD/programming/programming/iPhone/spotify-ios-sdk/SpotifyAudioPlayback.framework/SpotifyAudioPlayback(SPTCoreAudioController.o):
warning: /var/folders/lg/ssvy6y5n2g390pthrdmx54j000000w/C/org.llvm.clang.28/ModuleCache/25DR2ALIHKKZE/AVFoundation-3ODBO1W70S050.pcm: No such file or directory
while processing /Volumes/Macintosh HD/programming/programming/iPhone/spotify-ios-sdk/SpotifyAuthentication.framework/SpotifyAuthentication(SPTConnectButton.o):
warning: /var/folders/lg/ssvy6y5n2g390pthrdmx54j000000w/C/org.llvm.clang.28/ModuleCache/25DR2ALIHKKZE/QuartzCore-W2EYA9XA88YX.pcm: No such file or directory
while processing /Volumes/Macintosh HD/programming/programming/iPhone/spotify-ios-sdk/SpotifyAuthentication.framework/SpotifyAuthentication(SPTStoreViewController.o):
warning: /var/folders/lg/ssvy6y5n2g390pthrdmx54j000000w/C/org.llvm.clang.28/ModuleCache/25DR2ALIHKKZE/StoreKit-299RAFYLOE983.pcm: No such file or directory

**Comment by DmytroAnkudinov** [comment]
We have verified and fixed this. The fix will be in the next release.
Thank you for your report.
