### ISSUE TITLE
SpotifyMetadata.framework should be built as a universal framework

### ISSUE THREAD

**Issue by mhuusko5** [spotify/ios-sdk#783]
It has no obvious dependencies on UIKit, and thus should be built to target iOS _or/and_ macOS.

Also, a friendly reminder/note – it would be fantastic if just SpotifyMetadata could be open sourced some time, so the community could work to bring it to full parity with the web api.

**Comment by erdtman** [comment]
We are deprecating the iOS-Metadata library.

The source code of the iOS-Metadata library has been released and can be found here. Spotify will not continue to maintain the released source code.

Either you can select to use the web-api directly or use the new open source iOS-Metadata library.

I will close this issue now.

We are sorry for the inconvenience that this creates, but looking back we think this is the best path forward.
