### ISSUE TITLE
Use of ios-sdk-build-24

### ISSUE THREAD

**Issue by idelfonsog2** [spotify/ios-sdk#784]
## Description
Do I need to use the latest build-24 in order for my ios application to work? I/m having that about the methods been deprecated and not work anymore. also is there like a slack support group?

### Versions
iOS SDK version: ios-sdk-23
Spotify app version (if native SSO flow is involved)

### Severity
Trivial

**Comment by erdtman** [comment]
Only if you have issues that you want us to resolve.
You must use a version later then 19 because since that is where the ipv6 support was added that is a requirement from apple.
