### ISSUE TITLE
Uri sent to the player is different form the one returned in method 'didStartPlayingTrack'

### ISSUE THREAD

**Issue by sergiobravotalero** [spotify/ios-sdk#788]
*If you are filing a bug report, please include information for the topics below. Also, please make sure to only report one bug/feature request/question per issue.*

## Description
The uri sent to the player is different form the one returned in method 'didStartPlayingTrack'

### Versions
iOS SDK version Beta 25
Xcode 8.1, Swift 3.

### Severity
Major

## Steps to Reproduce
1. Sent an uri to player.playSpotifyURI
2. didStartPlayingTrack method of SPTAudioStreamingPlaybackDelegate returns other uri (trackUri).

### Actual behaviour
The uris being sent to the player are different to the one returned as trackUri.

### Expected behaviour
The uri that the player is asked to play should be the same as the one being returned in SPTAudioStreamingPlaybackDelegate methods.

**Comment by matijse** [comment]
Is the right song playing? Are both uri's from the same song? If so, this is expected: https://developer.spotify.com/web-api/track-relinking-guide/

**Comment by erdtman** [comment]
@sergiobravotalero is it track re-linking that you see as mentioned by @matijse or do you think this is something else?

**Comment by erdtman** [comment]
Since I have not gotten any reply here I will close this issue
