### ISSUE TITLE
SPTPlaylistSnapshot has no items

### ISSUE THREAD

**Issue by Zwaaan** [spotify/ios-sdk#790]
I'm calling 
SPTPlaylistSnapshot playlistsWithURIs:[list] accessToken:self.session.accessToken callback:^(NSError *error, id object)

and I get two SPTPlaylistSnapshot in the request with some info, however when I look in the page like firstTrackPage the items are nil.

Is this an issue or am I using the playlist wrong? How do I get the tracks from a playlist?

I've updated to the Beta 24 and haven't for 8 months 

Edit: The same thing happens when I do a search with SPTSearch and get a SPTListPage, the items are always nil.

**Comment by NOlivNeto** [comment]
I'm also having this problem. My app isn't working at all with it. Please, fix it asap.

**Comment by Zwaaan** [comment]
Please Spotify, respond if you are considering fixing this since my customers are upset it's not working! :)

**Comment by erdtman** [comment]
Sorry for not getting back earlier.

Does the `playlistWithURI` work? `playlistsWithURIs` depends heavely on `playlistWithURI`
`+(void)playlistWithURI:(NSURL *)uri accessToken:(NSString *)accessToken callback:(SPTRequestCallback)block;`

We are in the final stage of releasing the source code of the metadata library, so hopefully we can get more movement in the metadata parts as that happens.

**Comment by Zwaaan** [comment]
@erdtman No nothing with items work, I tried SPTSearch as well.
Thanks for responding! I would say fetching the tracks from a playlist is highly essential for a Spotify SDK so I hope this bug is prioritized :)

**Comment by erdtman** [comment]
We are deprecating the iOS-Metadata library.

The source code of the iOS-Metadata library has been released and can be found here. Spotify will not continue to maintain the released source code.

Either you can select to use the web-api directly or use the new open source iOS-Metadata library.

I will close this issue now.

We are sorry for the inconvenience that this creates, but looking back we think this is the best path forward.
