### ISSUE TITLE
Contradictory documentation

### ISSUE THREAD

**Issue by MchlG** [spotify/ios-sdk#792]
I am trying to determine the best way to play an array of SPTTrack's . It looks like using queueUri:callback is a good option, but when reading the documentation at [this link](https://developer.spotify.com/ios-sdk-docs/Documents/Classes/SPTAudioStreamingController.html#//api/name/queueURI:callback:)
it says this method is deprecated. However much of this documentation looks outdated since much of it is inaccurate. The method description in the header file does not say that the queueUri:callback method is deprecated which leads me to believe that the documentation at the above link is wrong. 

I am using beta 24

Could someone please tell me if this method is deprecated or not? If it is deprecated, is there no method provided by this SDK to prepare a queue of tracks for playback?

**Comment by erdtman** [comment]
queueURI (or queueSpotifyURI) is not deprecated
see https://spotify.github.io/ios-sdk/Classes/SPTAudioStreamingController.html#//api/name/queueSpotifyURI:callback:

The documentation you linked to is the old one, how did you end up there? have we missed to update some links?

**Comment by MchlG** [comment]
Ah ok thanks for clearing that up. 

Simply type "SPTAudioStreamingController" into google search bar and the first search result for me is the documentation that I linked above...
