### ISSUE TITLE
Play an array of Spotify URIs

### ISSUE THREAD

**Issue by Kry256** [spotify/ios-sdk#794]
Hi, I'm updating the SDK from beta 17 to beta 24.
In the previous version fo the SDK I was able to play an array of URIs (i.e. the array in the response of this query)

`[SPTYourMusic savedTracksForUserWithAccessToken:[self getAccessToken]
										   callback:^(NSError *error, id result) {`
 `          // The array which I was able to put in play`
`NSArray *uris = ((SPTListPage *)result).items;`
`}`

Now it seems there's only the possibility to put in play a single uri

`- (void)playSpotifyURI:(NSString *)spotifyUri startingWithIndex:(NSUInteger)index startingWithPosition:(NSTimeInterval)position callback:(SPTErrorableOperationCallback)block`

How could I solve this? If I can't play even an array of URIs, over that a single one, for me will be quite impossible to complete the "update process".

**Comment by erdtman** [comment]
I´m sad to here that our update to the SDK is causing you problems.

There is as you have found no direct way to play an arbitrary list of tracks, the available workaround is to use queueURI function.

The good thing this is that you now can play all types URIs and not only tracks. With this change we encourage you to play Spotify playlists/albums/artists directly and not create them outside of the Spotify ecosystem.

**Comment by Kry256** [comment]
Ok, I understand this.
But in this way, when I play the list `savedTracksForUserWithAccessToken` I'm not able to retrieve informations about `prevTrack` and `nextTrack` metadata, thing that `SPTAudioStreamingController` automatically does when I put in play a playlist/album.
Should I manually manage it, for this scenario?

**Comment by erdtman** [comment]
I have asked internally and you can use the URI spotify:collection:tracks to play saved tracks.

Hope this helps

**Comment by Kry256** [comment]
Cool, that's work, thank you!
