### ISSUE TITLE
Crash when Querying for User Library

### ISSUE THREAD

**Issue by BananaFudgkins** [spotify/ios-sdk#797]
## Description
Currently 

### Versions
iOS SDK version : 10.1

### Severity
Major

## Problematic code
`- (void)getSpotifyLibrary {
    [SPTYourMusic savedTracksForUserWithAccessToken:[[SpotifyPlayer sharedInstance] session].accessToken callback:^(NSError *error, id object) {
        if (!error) {
            NSError *jsonError;
            SPTListPage *libraryListPage = [SPTListPage listPageFromDecodedJSON:object
                                                       expectingPartialChildren:NO rootObjectKey:nil error:&jsonError];
            NSLog(@"%lu items were returned.", libraryListPage.items.count);
        } else {
            NSLog(@"Could not get the user's saved tracks");
        }
    }];
}`

## Behaviour
Currently, when using the code above, my app will crash as the SPTListPage class throws an exception when trying to retrieve the current user's saved tracks.

## -[SPTListPage objectForKeyedSubscript:]: unrecognized selector sent to instance 0x17009a450

Thanks in advance to anyone that is able to help me with this issue.

**Comment by erdtman** [comment]
We are deprecating the iOS-Metadata library.

The source code of the iOS-Metadata library has been released and can be found here. Spotify will not continue to maintain the released source code.

Either you can select to use the web-api directly or use the new open source iOS-Metadata library.

I will close this issue now.

We are sorry for the inconvenience that this creates, but looking back we think this is the best path forward.
