### ISSUE TITLE
SPTAuthViewController deprecated?

### ISSUE THREAD

**Issue by MchlG** [spotify/ios-sdk#798]
Is SPTAuthViewController deprecated? [HERE](https://spotify.github.io/ios-sdk/Classes/SPTAuthViewController.html#overview) the docs mention nothing about this class being deprecated.

 However  [As stated HERE](https://github.com/spotify/ios-sdk/blob/2db9f565b45e683b4bb62c1ee1bdc34660f07c8f/SpotifyAuthentication.framework/Headers/SPTAuthViewController.h)  it appears that this class is deprecated and one should use SFSafariViewController instead. Which is the correct documentation and which is the preferred login method? Thanks

**Comment by matijse** [comment]
As of beta 25 `SFSafariViewController` is the way to go: https://github.com/spotify/ios-sdk/blob/master/CHANGELOG.md

**Comment by erdtman** [comment]
Correct the SPTAuthViewController will be deprecated and discontinued.
Longterm in favor of SPTAuthViewController and the SSO flow. If you are supporting older iOS versions you can do the webview your self, as can be seen in the example code [here](https://github.com/spotify/ios-sdk/blob/master/Demo%20Projects/Simple%20Track%20Playback/Simple%20Track%20Playback/WebViewController.h)

**Comment by danielsalare** [comment]
Hi, does anyone have an example code on what should be called, I'm getting the same error (one year later) I know how to open a SFViewcontroller, just don't know what should be send. Thanks for any of your comments
