### ISSUE TITLE
Spotify stopped redirecting back to our app

### ISSUE THREAD

**Issue by philiparpin** [spotify/ios-sdk#799]
## Description
When attempting to login with Spotify, the Spotify app nor the Spotify website redirects back to our iPhone application when pressing either Ok or Cancel on the permissions page.

### Versions
iOS SDK Version: 25
Spotify app Version: 6.8.0

### Severity
Catastrophic

## Steps to Reproduce
1. Attempt to use OpenURL with either the SpotifyAppURL or SpotifyWebURL
2. Approve permissions

### Actual behaviour
Nothing occurs

### Expected behaviour
Redirected back to iPhone application with URL specified at developer.spotify.com

**Comment by matijse** [comment]
Seems to be a temporarily issue: https://twitter.com/SpotifyPlatform/status/798550633359888385

**Comment by karthickkumarmr** [comment]
I am seeing the same problem here

**Comment by karthickkumarmr** [comment]
@philiparpin Is the problem still existing for you? I am facing the same issue here.

**Comment by philiparpin** [comment]
No the problem has been solved for me.

**Comment by karthickkumarmr** [comment]
@philiparpin How did the problem got resolved? Is there anything specific you did in your code ?

**Comment by mickychen0524** [comment]
@philiparpin @karthickkumarmr 
were you able to address this issue?

**Comment by karthickkumarmr** [comment]
Yes the problem got resolved
