### ISSUE TITLE
Can I use the SDK to play music without the Spotify App installed?

### ISSUE THREAD

**Issue by grsouza** [spotify/ios-sdk#80]
I wonder if it's possible to use the SDK for streaming without the Spotify app installed.

**Comment by arirawr** [comment]
Hi @grsouza - this SDK does playback by remote controlling the Spotify app, so having the Spotify app installed is required.

**Comment by grsouza** [comment]
Hi @arirawr thanks for the response, there's a way of playing music without the need of the app?

**Comment by jmonzada** [comment]
How does Noon pacific app play Spotify music without the app installed on a iOS device?

**Comment by ngocketit** [comment]
So if I build an app using the SDK, when users are installing it, do they need to also install the Spotify app in order for my app to work? What about React native/Flutter SDK? Are they behaving similar to the native iOS/Android SDK?

**Comment by alvarorose** [comment]
@danielgronlund @kkarayannis I would love to know how the Vertigo app is able to play music without playing it in the iOS Spotify app.

**Comment by alvarorose** [comment]
@jmonzada were you able to solve it? @arirawr any idea? 

thanks
