### ISSUE TITLE
Playback is stopped when phone is locked

### ISSUE THREAD

**Issue by sergiobravotalero** [spotify/ios-sdk#803]
Though I added the following elements to the info.plist, when the phone goes to background mode, playback is stopped.

Required background modes (Array)

Item 0 = App plays audio or streams audio/video using AirPlay
Item 1 = App downloads content from the network

**Comment by MchlG** [comment]
That isn't enough to allow for background playback. You also need to establish an AVAudioSession [(Here)](https://developer.apple.com/reference/avfoundation/avaudiosession) 

Here is the Swift 3 code i'm using and is working on iOS 10.1 

`
func setupAudioSession(){
    
    UIApplication.shared.beginReceivingRemoteControlEvents()
    
    do {
        try AVAudioSession.sharedInstance().setCategory(AVAudioSessionCategoryPlayback, with: AVAudioSessionCategoryOptions.mixWithOthers)
    
        self.becomeFirstResponder()
        
        do {
            try AVAudioSession.sharedInstance().setActive(true)
            
        } catch let error as NSError {
            print(error.localizedDescription)
        }
    } catch let error as NSError {
            print(error.localizedDescription)
    }
}`

**Comment by sergiobravotalero** [comment]
I used the code above and now the music plays regardless of how the ring/silent switch is set. But music still doesn't sound if user locks the iPhone.

**Comment by keithlee** [comment]
@sergiobravotalero Did you solve the issue? If so, how?
