### ISSUE TITLE
30 Second Preview of track

### ISSUE THREAD

**Issue by groebe1kenobi** [spotify/ios-sdk#81]
I am looking for a way to play a 30 second preview of a track that I could embed in my app like how it is done with the Web API.

 [Web API example](https://jsfiddle.net/JMPerez/0u0v7e1b/)

**Comment by arirawr** [comment]
Hi @groebe1kenobi - this SDK is for full-track playback. 30-second previews can only be obtained through the Web API (documentation [here](https://developer.spotify.com/documentation/web-api/reference/tracks/get-track/)). You can use the access token from the iOS SDK to make requests to the Web API.

**Comment by solkpolk** [comment]
Once you have the track URI how do you play the sound?
