### ISSUE TITLE
Documentation: promote partial to a full [track/artist/album/playlist]

### ISSUE THREAD

**Issue by foges** [spotify/ios-sdk#812]
For SPTPartial[Track/Artist/Album/Playlist], the documentation states:

```
You can promote this to a full [track/artist/album/playlist] object using SPT[Track/Artist/Album/Playlist].
```

It would be great if the documentation were to reflect how this promotion works. The only way I've found so far is to use the `uri` and create a request to the spotify API. It would be great to know if there is a way to do this without creating a request. Specific use cases involve finding the set of artists associated with an `SPTPartialAlbum`.

Related to this, the documentation on this page (https://spotify.github.io/ios-sdk/Constants/SPTSearchQueryType.html) states that `SPTQueryTypeTrack` should result in `SPTTrack` results, but I seem to be getting `SPTPartialTrack` (similarly for `SPTQueryTypeAlbum` and `SPTQueryTypeArtist`). 

Thanks!

**Comment by erdtman** [comment]
I'm sorry to inform you but the metadata part of the iOS-SDK has been deprecated so the documentation will not be updated here.
However the source code has been released, see https://github.com/erdtman/spotify-ios-metadata/
