### ISSUE TITLE
MPNowPlayingInfoCenter controls not showing  on real device

### ISSUE THREAD

**Issue by sergiobravotalero** [spotify/ios-sdk#813]
## Description
The MPNowPlayingInfoCenter controls to allow user to change tracks or toggle play/pause don't appear on a real device but they do on iOS simulator.

### Versions
iOS SDK version 25

**Comment by erdtman** [comment]
Sorry I don't think this is related to the Spotify iOS-SDK, but is an issue with the interaction with iOS.
