### ISSUE TITLE
App authentication not working in iOS 10.2

### ISSUE THREAD

**Issue by ozzotto** [spotify/ios-sdk#815]
## Description
Although both `[SPTAuth supportsApplicationAuthentication]` and `[SPTAuth spotifyApplicationIsInstalled]` return YES, `[[SPTAuth defaultInstance] canHandleURL:[[SPTAuth defaultInstance] spotifyAppAuthenticationURL]]` returns NO.
Thus, we cannot open Spotify app to perform app authentication.

### Versions
iOS 10.2
iOS SDK version 25
Spotify app version 6.8.0.3786

### Severity
Trivial

**Comment by erdtman** [comment]
The documentation is not super clear here but this is not how it is meant to be used.
The canHandleURL is called with the returned url after user has authorized the request i.e. before calling handleAuthCallbackWithTriggeredAuthURL. 

see https://developer.spotify.com/technologies/spotify-ios-sdk/tutorial/ for more details

**Comment by ozzotto** [comment]
I am following the documentation guidelines, however in the
`- (BOOL)application:(UIApplication *)application openURL:(NSURL *)url sourceApplication:(NSString *)sourceApplication annotation:(id)annotation`
the `[[SPTAuth defaultInstance] canHandleURL:url]` where url is the spotifyAppAuthenticationURL returns NO and thus the Spotify app does not open.

**Comment by Feykoo** [comment]
@ozzotto do you solved the problem with canHandleURL: ?

**Comment by ozzotto** [comment]
Not yet. Seems broken in beta-25.

**Comment by arirawr** [comment]
Hi @ozzotto, what is your redirectURL?

**Comment by ozzotto** [comment]
myapp://spotify

**Comment by arirawr** [comment]
Thanks, all lowercase?

**Comment by ozzotto** [comment]
Yes. I have replaced the actual app name here  with "myapp". If you want the actual redirect url please tell me.

**Comment by arirawr** [comment]
Just wanted to know if it was all lowercase, as that would cause it not to match the value of `url` in this function.

**Comment by arirawr** [comment]
If it is, try to refer to the function in the iOS SDK tutorial, which I've included below:

```
- (BOOL)application:(UIApplication *)app
            openURL:(NSURL *)url
            options:(NSDictionary *)options
{
    // If the incoming url is what we expect we handle it
    if ([self.auth canHandleURL:url]) {
        // Close the authentication window
        [self.authViewController.presentingViewController dismissViewControllerAnimated:YES completion:nil];
        self.authViewController = nil;
        // Parse the incoming url to a session object
        [self.auth handleAuthCallbackWithTriggeredAuthURL:url callback:^(NSError *error, SPTSession *session) {
            if (session) {
                // login to the player
                [self.player loginWithAccessToken:self.auth.session.accessToken];
            }
        }];
        return YES;
    }
    return NO;
}
```

**Comment by jameszaghini** [comment]
Have you set the `redirectURL` on the `STPAuth.defaultInstance`?

`canHandleURL` returns `true` if I set the `redirectURL` there, `false` otherwise.

```
if let spotifyAuth = SPTAuth.defaultInstance() {
    spotifyAuth.clientID = "1234567890"
    spotifyAuth.redirectURL = URL(string: "myapp://spotify")!
    spotifyAuth.requestedScopes = [SPTAuthUserReadEmailScope, SPTAuthUserReadPrivateScope, SPTAuthStreamingScope]
    spotifyAuth.sessionUserDefaultsKey = "com.myapp.something"
    spotifyAuth.tokenSwapURL = tokenSwapURL
    spotifyAuth.tokenRefreshURL = tokenRefreshURL
}
```

**Comment by ozzotto** [comment]
I have set the `redirectURL` on the `[SPTAuth defaultInstance]`.
My code is the following

```
SPTAuth *auth = [SPTAuth defaultInstance];
SPTAuthCallback authCallback = ^(NSError *error, SPTSession *session) {
    if (error) {
        //do something
    } else {
        auth.session = session;
        //do something
    }
};
if ([auth canHandleURL:url]) {
    [auth handleAuthCallbackWithTriggeredAuthURL:url callback:authCallback];
    return YES;
}
```
However the `[auth canHandleURL:url]` returns `NO` when url is `spotify-action://authorize?nolinks=true&nosignup=true&response_type=code&scope=streaming%20user-read-private%20user-library-modify&utm_source=spotify-sdk&utm_medium=ios-sdk&utm_campaign=ios-sdk&redirect_uri=myapp%3A%2F%2Fspotify&show_dialog=true&client_id=clientId`
