### ISSUE TITLE
Is there any kind of demo account I could have access to as a developer?

### ISSUE THREAD

**Issue by Sethmr** [spotify/ios-sdk#816]
I will say it is slightly annoying that I signed up for a free trial of Spotify specifically in order to provide https://github.com/Sethmr/SpotifyInSwift to the community and have been charged now for a membership I originally canceled right after making it for the trial duration. I personally don't use Spotify, and just wanted to offer something the community needed. chief117project3 is the username of the spoof account I used.

I won't ask for a refund, but is there any kind of demo/developer account I could get my hands on for future testing and upkeep of my Github repo?? It doesn't need to have normal privileges, but just whatever I need in order to maintain the basic functionality of the demo project.

If you want to contact me directly, my email is sethmr21@gmail.com.

**Comment by erdtman** [comment]
Hi @Sethmr,
I´m sorry to hear that you where charged even thought you had explicitly asked to stop.
I still think you should contact our customer service with this issue, fill out the form [here](https://support.spotify.com/us/contact-spotify-support/) and they should be able to help you.

Regarding test accounts for developers, no we don´t have any of those.

**Comment by Sethmr** [comment]
Like I said, I am not worried about the money. I just was pushing for some form of developer account. Thank you for your time!
