### ISSUE TITLE
Is this project still alive and under active development? 

### ISSUE THREAD

**Issue by floodfx** [spotify/ios-sdk#817]
Lots of open bugs...  A single commit since Oct 28 (and that was small README update)...  

Sorry if this comes across as harsh.  Just wondering if worth investing (further) time into building stuff with the Spotify IOS SDK.

**Comment by volksport** [comment]
I'd say it's actively maintained. They may just been on vacation for Dec :)

**Comment by erdtman** [comment]
Yes this project is maintained during summer and fall we make a push where we went from 200+ issues to todays 52 (excluding feature requests).
In this process we have split up metadata, playback and auth, to improve maintainability. Metadata library (web-api wrapper) has been open sourced to allow the community to contribute.
On Android side we have also open sourced the auth library part, and intend to do similarly for iOS.

I hope this gave you some more confidence.
Of course it is not optimal with 52 open issues but it will take some time to get it down further.
