### ISSUE TITLE
SPTAuthViewController only shows empty white Popup

### ISSUE THREAD

**Issue by escamoteur** [spotify/ios-sdk#819]
## Description
When displaying SPTAuthViewController only  white empty popup with a closing X is shown. When closing the passed delegates UserCanceled method is called

### Versions
iOS SDK:  beta-25
Spotify app version (if native SSO flow is involved) 6.8.03

Although I have the SpotifyApp install it does not get picked up when showing the 
SPTAuthViewController

### Severity
Catastrophic

## Steps to Reproduce
I made a C# binding for Xamarin which seems fine as the delegates get called. Also when starting the PlayerService I get true and no error.

This is what I inialize to show the ViewController

```C#
                var login = new SPTAuthViewController();
                login.DefinesPresentationContext = true;
                login.Delegate = new LoginDelegate();
                var currentViewController = GetVisibleViewController();
                currentViewController.PresentViewController(login,true,null);


    public class LoginDelegate : SPTAuthViewDelegate
    {
        public override void AuthenticationViewController(SPTAuthViewController authenticationViewController, SPTSession session)
        {
        }

        public override void AuthenticationViewController(SPTAuthViewController authenticationViewController, NSError error)
        {
        }

        public override void AuthenticationViewControllerDidCancelLogin(SPTAuthViewController authenticationViewController)
        {
        }
    }
```

### Actual behaviour
![screen shot 2016-12-20 at 18 15 17](https://cloud.githubusercontent.com/assets/16635729/21360757/8057dad0-c6e1-11e6-9a34-1c912c5a3b60.png)

### Logs
Is there a way to enable logging?

**Comment by MchlG** [comment]
SPTAuthViewController is deprecated anyway you should use SFSafariViewController , [refer here](https://github.com/spotify/ios-sdk/issues/798)

**Comment by escamoteur** [comment]
Thanks a lot I read about Apps being rejected by the Appstore when doing login in safari,  that's why I was trying this way.

**Comment by escamoteur** [comment]
Thanks, with the SafariViewController it works, only the SafariViewController did not close itself automatically.

**Comment by danielsalare** [comment]
Hi, one year later to the party .. 

Does anyone have an example code... or could give any advise on how to approach this, I know how to load a SFSafariViewcontroller, but not quite sure what it should open or send. 

thanks
