### ISSUE TITLE
How do we play a user's saved songs?

### ISSUE THREAD

**Issue by keithlee** [spotify/ios-sdk#822]
In a previous SDK I was able to retrieve a user's saved songs by calling "SPTYourMusic savedTracksForUserWithAccessToken" which returns an SPTListPage

I could then use "player playUris" with the provided SPTListPage to play the list of saved songs.

Now that only playSpotifyURI is available and no url for saved songs exist, how do we replicate this previous behavior?

**Comment by erdtman** [comment]
playURI with spotify:collection:tracks

**Comment by keithlee** [comment]
@erdtman Where do you find spotify:collection:tracks? I've searched the repository for collection and tracks and they don't exist. There is a tracksForPlayback but that isn't the type required by playSpotifyURI. playURI no longer exists in beta 25 which would accept an array

**Comment by keithlee** [comment]
@erdtman Solved it. For future reference. playSpotifyURI("spotify:collection:tracks")

**Comment by erdtman** [comment]
Sorry for not replying, but good to see that you solved it!
