### ISSUE TITLE
Tracks that are no longer playable still appear in Playlist

### ISSUE THREAD

**Issue by dsuper66** [spotify/ios-sdk#827]
I am using iOS SDK Beta 25. 

I have a playlist (6qzQiQYFUu0Wc5JBcB1xiV) where 15 out of 16 tracks seem to be no longer available, e.g., Wait A Minute (37tp9qtF4YQF0nvaQ3ryB7) by Safakash. These tracks are no longer returned by a search, but when I retrieve the tracks for the playlist they are still there... when I try to play them they fail (more precisely the player advances through all the tracks in the playlist until it reaches the available track and then it pauses).

The official Spotify app has part of the same problem, the playlist count shows as 16, but when the playlist is opened only one track (the one that is still available) is shown.

I have tried testing the tracks using isPlayable and isTrack, but both show true. 

I would prefer if the expired tracks did not appear in the playlist, but as this problem also affects the official app, I would settle for knowing how to identify them as invalid and not displaying them, which is what the official Spotify app does.

**Comment by erdtman** [comment]
The metadata framework has been deprecated and the source code released [here](https://github.com/erdtman/spotify-ios-metadata/). However this sounds more related to the web-api, i.e. please report this to Spotify web-api [here](https://github.com/spotify/web-api)
