### ISSUE TITLE
Can't find any way get a Playlist’s Tracks

### ISSUE THREAD

**Issue by singhamit089** [spotify/ios-sdk#828]
*I want to get full details of the tracks of a playlist owned by a Spotify user, but can't find any method related to it in SDK*

## Description
As described in the [documentation](https://developer.spotify.com/web-api/get-playlists-tracks/) following GET will provide the required detail
> https://api.spotify.com/v1/users/{user_id}/playlists/{playlist_id}/tracks
but in Spotify iOS SDK none of the Object/Request has any provision to get these data.

### Versions
iOS SDK version : Spotify-iOS-SDK, 0.25.0 as updated from cocoapods

### Severity
Minor

**Comment by erdtman** [comment]
The metadata framework has been deprecated and the source code has been released [here](https://github.com/erdtman/spotify-ios-metadata/). You can either use the web-api directly ore use the released source code as is.
