### ISSUE TITLE
SPTListPage attribute item is returning nil after a SPTYourMusic request

### ISSUE THREAD

**Issue by velouria** [spotify/ios-sdk#834]
## Description
After logging in successfully using the scope SPTAuthUserLibraryReadScope, I try requesting the users's Saved Tracks using SPTYourMusic request and the SPTListPage response object has the attribute items always nil.

### Versions
iOS SDK Beta 25

### Severity
Major

## Steps to Reproduce

```
let accessToken = SPTAuth.defaultInstance().session.accessToken
let request: URLRequest = try! SPTYourMusic.createRequestForCurrentUsersSavedTracks(withAccessToken: accessToken)
SPTRequest.sharedHandler().perform(request) { (error, response, data) in
            if error == nil {
                        let listPage = try! SPTListPage(from: data, with: response, expectingPartialChildren: false, rootObjectKey: nil)

```

listPage.items is always nil.
listPage.totalListLength has the expected number of elements.

**Comment by mick111** [comment]
Adding -ObjC in "Other Linker Flags" in Build Settings solved this problem for me.

**Comment by velouria** [comment]
It solved the problem! Now it seems to be working fine!
Thanks @mick111
