### ISSUE TITLE
Not getting playlist

### ISSUE THREAD

**Issue by subrata-dal** [spotify/ios-sdk#835]
*If you are filing a bug report, please include information for the topics below. Also, please make sure to only report one bug/feature request/question per issue.*

## Description
I am trying to fetch playlist for user evzdrp_spotify, each time its return nil. in have send spotifyAuth!.requestedScopes = [SPTAuthStreamingScope, SPTAuthPlaylistReadPrivateScope, SPTAuthPlaylistReadCollaborativeScope, SPTAuthUserLibraryReadScope, SPTAuthUserLibraryModifyScope, SPTAuthUserReadPrivateScope, SPTAuthUserReadTopScope]
and got valid session id. 

### Versions
iOS SDK version
Spotify app version (if native SSO flow is involved)

### Severity
Trivial, Minor, Major, Catastrophic

## Steps to Reproduce
1. Step by step instructions on how to reproduce this bug.
2. The more detailed your list of instructions, the easier it is for the developer to track down the problem!

### Actual behaviour
Describe what happens when you perform the steps above.

### Expected behaviour
Describe what you expected to happen when performing the steps above.

## Logs
Please include any relevant log output that might assist in tracking down the problem.

**Comment by arirawr** [comment]
Hi there - apologies for the late reply. If this is still an issue, please reopen and let me know the ID of the playlist you are trying to get and the code you are using.
