### ISSUE TITLE
SPTAudioStreamingPlaybackDelegate methods are not being called

### ISSUE THREAD

**Issue by lrholmes** [spotify/ios-sdk#838]
I'm not able to receive any responses from the various `SPTAudioStreamingPlaybackDelegate` methods - in particular, I need to use `didStopPlayingTrack`. 

Any ideas as to why this might be happening or how to debug? (player delegate has been set)

**Comment by adambolcsfoldi** [comment]
`SPTAudioStreamingController` has two delegates, a plain `delegate` and a `playbackDelegate`. Are you setting the right one?

**Comment by lrholmes** [comment]
@adambolcsfoldi well, yep. After having lifted my head off the desk I can confirm that this was the issue - thank you very much!
