### ISSUE TITLE
Remote Control App

### ISSUE THREAD

**Issue by gempers** [spotify/ios-sdk#841]
I'm trying to implement a way to control my Spotify session on my computer or other device through an iPhone App I'm developing. Namely I'm trying to pause and play the current track. Something like this functionality, but it applies to my overall session instead of the player:

`player.setIsPlaying(!playpause.playbackState.isPlaying, callback: nil)`

Is this possible with the current sdk?

**Comment by erdtman** [comment]
Sorry that is not possible with current SDK :(
