### ISSUE TITLE
SPTTrack.tracks(withURIs: ...) randomly stops working

### ISSUE THREAD

**Issue by MchlG** [spotify/ios-sdk#842]
## Description

For the last couple of months I have been using this method to get an array of SPTTrack from an array of valid URIs ...

      `SPTTrack.tracks(withURIs: uris, accessToken: SPTAuth.defaultInstance().session.accessToken, market: nil, callback: {(tracksResponse)-> Void in
           
           if tracksResponse.0 != nil {
                print("ERROR GETTING TRACKS FROM URI STRINGS \(tracksResponse.0)")
            } else if let tracks = tracksResponse.1 as? [SPTTrack] {
                callback(tracks)
            } else {
                print("WARNING FAILED TO GET TRACKS FROM URI STRINGS WITH NO ERROR")
            }

        })`

This was working fine for months up until 30 minutes ago (roughly -> February 28th, 6:45pm EST). Now all of the sudden it does not return any error, nor does it return any tracks, it just returns `nil` for `tracksResponse.0` and `nil` for `tracksResponse.1`

what is really weird is that this is only happening on my actual device. When i run this on the simulator everything works just fine like it used to.

### Versions
iOS Metadata version
version 24

### Severity
Catastrophic

## Steps to Reproduce
1. authenticate as Spotify to get valid access token
2. call method I have shown above passing in valid array of URIs and a valid access token

### Actual behaviour
no tracks are returned and no error is returned

### Expected behaviour
return either an error or an array of SPTTrack

Please any help or advice would be amazing! I have no idea whats going on, thanks

**Comment by binhnguyen1512** [comment]
Can you help me active my phone?

**Comment by MusicSplitterGit** [comment]
This just started working again , with no changes needed on my part. Not sure what it was. Going to close this issue

**Comment by MchlG** [comment]
This issue resolved itself, It has started working again with no change needed by me. Closing the issue for now.

**Comment by MchlG** [comment]
I began experiencing this issue again today. It seems that calling `SPTTrack.tracks(...)` only works when passed a small number of URI-strings, something like less than 40. Every time I call this method and pass it 100+ URI-strings, it either returns with 
_"Error Domain=NSCocoaErrorDomain Code=3840 "No value." UserInfo={NSDebugDescription=No value.}"_

or it returns without any error but `response.1` is nil and thus no SPTTracks returned.

Is anyone else experiencing this issue? Any solutions? Thanks
