### ISSUE TITLE
Being ignored by Spotify for approval of iOS app commercialization

### ISSUE THREAD

**Issue by edwinfinch** [spotify/ios-sdk#843]
**I'd love to hear from someone who actually works at Spotify, instead of being ignored by Spotify staff**, like all of us have on [this thread](https://github.com/spotify/ios-sdk/issues/807). I've tried emailing Spotify directly, but **this issues form seems to be the best way I've found to 100% know that someone who works for Spotify has actually read your words**. I understand the employees here may not be fully involved in the commercialization process, though they do work for the company that's ignoring developers for their platform and someone needs to know what's going on. 

_First off before I get into it I want to say: I am a big fan of Spotify. I absolutely love the platform, the community, and most of the company 😛 . This is basically my only issue with Spotify, and I hope you understand my passion comes from the fact that I want to build something awesome with Spotify, and it blows being ignored by the service which I love so much._ 

Here goes a slightly long complaint of trying to apply for commercialization because frankly I am quite tired of being ignored, and I really hope some change will come. 

To start off: I'm not even the one who's suffering the most, some people have literally been waiting **years** to hear back from Spotify about commercialization. So I hope in this post I can voice other people's frustrations as well, if at least a little. 

Personally, we've decided to drop working on Spotify support completely until we get commercialization approval from you guys, which honestly feels like it will never happen. We applied for a second time nearly 3 months ago and haven't heard a single word back.

The only two scenarios I've ever seen with commercialization approval are:

**1. You apply, wait forever & never hear back at all.** I assume this is because legally, the app/developer fits the bill, but Spotify is ignoring their application because they don't want to give them written permission, for whatever reason.

**2. You apply, wait an insanely long time & get rejected and told to resubmit.** Obviously if you don't fit their terms, legally they gotta reject you, that part makes sense. However, it's the insanely long wait that simply doesn't make sense. 

Back when I first applied for commercialization, the Google Form that I used to apply was not closed, so you could see what everyone else submitted as well. There were probably only about 25-30 actual applications (that was ~5-6 months ago, though I can't imagine it's increased much since then). This means that there's no way that they're bogged down based on the number of applications that are sent in, they must for some reason, be purposely slowing the process down.

Feels like every few months someone hops on the Google Form who works for Spotify and blows through some of them, because although I'm not an expert, I highly doubt it takes more than an hour per app/developer to know whether or not they fit the bill to be approved for commercialization. 

In the end it feels like if you legally fit the bill for commercialization approval, Spotify will ignore you, otherwise you will get a response back (after an insanely long wait) telling you to fix your mistakes and resubmit.

I'd love to know if there are actually any apps that exist that have been approved for commercialization, and I'd love to see proof of these up and running in the App Store/Play Store. Because honestly at this point it feels like nobody has ever been approved, and we'll just keep getting ignored by Spotify.

Thanks for reading my post, and I don't want to sound like I am blaming the developers of the Spotify SDK for this specifically. I simply posted this here because this issues form seems to be the best way for anyone at Spotify to actually read your words instead of just being ignored.

**Comment by jcnh74** [comment]
Thanks for posting. I'm in active development and this is concerning. I have not event been able to submit yet but if this process is funked up then I might have to abandon my project. I know there are a bunch of Apps on the App Store currently that tie nicely into Spotify. For instance "DJay 2" by Algoriddim is a very nice app running music from both Apple Music and Spotify. Also, by the looks of it, It's been 4 months since any new code was pushed to this repo which makes me think the Spotify devs are on hiatus and getting a response here may be futile.

**Comment by edwinfinch** [comment]
Just got an thorough email from Spotify after posting here, on Spotify Community, emailing them, and contacting them through their live online support (which I believe is the one that did the trick).

In the end we got rejected for a second time, the two reasons being 1. we didn't fit the branding guidelines and 2. we were branded as a "white-label" app, so we gotta figure out exactly how we came across like that and seek for another way to explain or commercialize in this case. We'll be working on a way to clarify these 2 points and reapply again (not gonna give up, sorry).

Regardless, that's not what matters. Here's the most important part of the email they wrote:

> We would like to start by thanking you for your patience. We understand that this process is long, and that that might have an impact on your project. The main reason for the long lead times is that we have a high volume of requests and, as such, it takes us time to process them. It is important to remember that, as described in our terms of services, we do not commit to specific response times, nor are we required to provide requesters with approval or rejection. In the case of no response, the requester cannot proceed with a commercial integration with the Spotify Platform, as written approval has not been given. Having said that, we thank you for your candid feedback and we will take that as input in our work to improve this process.

You guys can take this as you'd like. I'm just glad I heard anything back at all and appreciate that Spotify took the time to write this email for me.

**Comment by jcnh74** [comment]
Thanks for the update. Can you tell me what "white-label" means and what your branding guidelines issue? Also how did you go about getting your TOS written up. Thanks for time.

**Comment by edwinfinch** [comment]
No problem, glad to share my adventures.

I had never heard of the term "white label" before, however, I believe it means this (from Wikipedia):

> A white label product is a product or service produced by one company (the producer) that other companies (the marketers) rebrand to make it appear as if they had made it.

As for TOS we initially used TermsFeed, which seems to cover a lot of ground (and covered exactly what we needed). If worse comes to worst, and we need to improve upon our TOS for some reason, we could get a lawyer to draw them up.

**Comment by edwinfinch** [comment]
Interesting how I've been waiting over a month now for answers to just simple questions :(

Based on this it's pretty much confirmed Spotify doesn't want anyone to commercialize. Really sad stuff to be honest, so much lost potential, and for what?

[I loved you Spotify, we coulda been together!](https://youtu.be/WU9DzMhdeEo?t=4m46s)

**Comment by edwinfinch** [comment]
Who remembers this issue lol

**Comment by jeffreydexter** [comment]
Hey Edwin - thanks for sharing your experience with Spotify commercialization. I was wondering if you had any updates on your project or if you've heard back from Spotify yet? Do you know of any success stories where an app has been cleared for commercial use?

**Comment by edwinfinch** [comment]
Hey @jeffreydexter - we've decided to completely drop Spotify support unless by some miracle Spotify decides they want to support their 3rd party developers (which I doubt will ever happen).

I haven't even heard back from Spotify about the 2 simple questions I asked back in March (over 3 months now, can you believe it?!). 

To put it blunt: it's immensely clear they do not give a flying fuck about their 3rd party developers. 

For whatever reason, they don't want anyone developing a commercialized 3rd party app and will do whatever it takes for you to get demotivated/discouraged/disinterested so you don't continue forth. 

Honestly Spotify should just completely remove the commercialization "route" (even though it's not actually possible), and get rid of that submission form to stop misleading developers.

It's actually soul-crushing: based on thinking Spotify would actually follow through, we made a massive Kickstarter promise which we'll probably never be able to deliver on, even though about half of our backers backed with Spotify support at the front of their minds.

**Comment by jcnh74** [comment]
@edwinfinch if it's any consolation I decided to make my app free and avoid the pitfalls of Spotify's commercialization. I released my app on the Apple App store for free. figured it was a dead-end street and now thinking in a whole different way for future releases which removes Spotify completely and goes in a different direction. Lucky for me I am not beholden to investors and my app was more of an experiment in hopes of making a few bucks.

Here it is in all it's (FREE) glory :(

http://gmixr.com/
https://itunes.apple.com/us/app/gmixr/id1217135612?mt=8

**Comment by edwinfinch** [comment]
Thanks for sharing @jcnh74, sorry that you had to do that 😢 

Hope your new direction works out well! Keep on trucking 😀

**Comment by edwinfinch** [comment]
Monthly "who remember" post :)

**Comment by hughrawlinson** [comment]
Hi! Sorry to hear you had trouble with the commercialization process. Unfortunately, we're not able to approve every application. Our teams are working on improving the process. If you have any further questions, please reach out to the email that you corresponded with - they're better equipped to answer than the staff who monitor this forum.
