### ISSUE TITLE
iPhone lock screen controls don't show up when using SPTAudioStreamingController

### ISSUE THREAD

**Issue by MchlG** [spotify/ios-sdk#845]
## Description
Using SPTAudioStreamingController doesn't make the iPhone lock screen audio controls show up.  I use the following code to start an audio session

      `func setupAudioSession(){

         UIApplication.shared.beginReceivingRemoteControlEvents()

         do {
             try    AVAudioSession.sharedInstance().setCategory(AVAudioSessionCategoryPlayback, with: AVAudioSessionCategoryOptions.mixWithOthers)

             self.becomeFirstResponder()

             do {
                 try AVAudioSession.sharedInstance().setActive(true)
                      print("AVAudioSession is Active")
             } catch let error as NSError {
                      print(error.localizedDescription)

             }
         } catch let error as NSError {
                  print(error.localizedDescription)
         }
      }`

and then once my audio begins I call 

    `func setupLockScreen(){
              let commandCenter = MPRemoteCommandCenter.shared()
              commandCenter.nextTrackCommand.isEnabled = true
              commandCenter.nextTrackCommand.addTarget(self, action:#selector(skipTrack))
              MPNowPlayingInfoCenter.default().nowPlayingInfo = [MPMediaItemPropertyTitle: "TESTING"]
    }`

I have background modes enabled, I am able to play audio in the background without any issue. The only problem i have is that the iPhone lock screen doesn't display any controls, nothing shows up on the lock screen at all that indicates that audio is playing. 

I think this may be because in order for the lock screen controls to show up I need to be using one of the iOS audio players liked AVPlayer or AVAudioPlayer. But then how is does the Spotify app get the lock screen controls to work?

### Versions
iOS SDK version
24

### Severity
minor

## Steps to Reproduce
1. use code I've shown above to start an audio session
2. Use SPTAudioStreamingController to begin playing music from Spotify
3. observe no lock screen controls on iPhone screen

### Actual behaviour
iPhone lock screen controls are not shown when playing audio

### Expected behaviour
audio controls displayed on iPhone lock screen when playing audio

**Comment by brki** [comment]
Hi,

it should work (a similar setup does for me using the ios-sdk beta 25).  Perhaps you need to also set some other items in the nowPlayingInfo dictionary.  Have you tried setting `MPNowPlayingInfoPropertyPlaybackRate` (1 if playing, 0 otherwise), `MPMediaItemPropertyPlaybackDuration`, and `MPNowPlayingInfoPropertyElapsedPlaybackTime` ?

**Comment by MchlG** [comment]
Yes I tried setting those keys and it still doesn't work. Could you show me the code you've used for your setup? Can I call `setupAudioSession()`  when the app launches? Or do i need to call it right before I begin playing? And should I be setting up the buttons, calling `commandCenter.nextTrackCommand.isEnabled = true` before or after I start playing audio? 

Thanks for your help

**Comment by aljosac** [comment]
when I initialize my playerController I have the following lines of code 

    commandCenter = MPRemoteCommandCenter.shared()
    nowPlayingInfo = MPNowPlayingInfoCenter.default()

In my updateUI block for my playerController I have the following block of code 

    MPNowPlayingInfoCenter.default().nowPlayingInfo = [MPMediaItemPropertyTitle:meta.name,
                                                       MPMediaItemPropertyArtist: meta.artistName,
                                                       MPMediaItemPropertyAlbumTitle: meta.albumName,
                                                       MPMediaItemPropertyPlaybackDuration: meta.duration,
                                                       MPNowPlayingInfoPropertyElapsedPlaybackTime: 0.0,
                                                       MPMediaItemPropertyArtwork: `artImage]`


I also have the following function called in my viewDidLoad 



    func setupCommands() {

        commandCenter.playCommand.addTarget { event in
            SPTAudioStreamingController.sharedInstance().setIsPlaying(true, callback: nil)
            return MPRemoteCommandHandlerStatus.success
        }

        commandCenter.pauseCommand.addTarget { event in
            SPTAudioStreamingController.sharedInstance().setIsPlaying(false, callback: nil)
            return MPRemoteCommandHandlerStatus.success
        }

        commandCenter.nextTrackCommand.addTarget { event in
            SPTAudioStreamingController.sharedInstance().skipNext(nil)
            return MPRemoteCommandHandlerStatus.success

        }
        
        commandCenter.previousTrackCommand.addTarget { event in
            SPTAudioStreamingController.sharedInstance().skipPrevious(nil)
            return MPRemoteCommandHandlerStatus.success
        }
        
    }

There are also a couple of other places I have put code but those don't seem as important, just managing the playback rate and such

**Comment by MusicSplitterGit** [comment]
Hi thanks for help and the example code but unfortunately this still isn't showing anything on the lock screen. I've added the code exactly like you have it, setting up command center after player controller is initialized, updating the nowPlayingInfo with the appropriate track info and setting up the commands in the viewDidLoad() of my Now-Playing view.

**Comment by MusicSplitterGit** [comment]
I finally found the problem. 

When i was setting up AVAudioSession, I was using this line->
` try AVAudioSession.sharedInstance().setCategory(AVAudioSessionCategoryPlayback, with: AVAudioSessionCategoryOptions.duckOthers)`

once  change that line to the following, lock screen controls displayed and worked fine -> 
`try AVAudioSession.sharedInstance().setCategory(AVAudioSessionCategoryPlayback, with: [])`

So i guess the problem was passing in an argument for AVAudioSessionCategoryPlaybackOptions . I tried passing in .duckOther and .mixWithOthers and in both cases it causes the lock screen controls to not display at all

**Comment by hughrawlinson** [comment]
Seems like this issue is resolved - please reopen it if I'm wrong!
