### ISSUE TITLE
SPTSearch.perform(withQuery: text, queryType: .queryTypeTrack, accessToken: nil, market: nil) suddenly stopped working

### ISSUE THREAD

**Issue by henrydeclety** [spotify/ios-sdk#863]
This method is now producing the error "The operation couldn’t be completed. (com.spotify.ios-sdk error 104.)" since yesterday. It was working fine in the last few months, I just updated the frameworks with the latest one the repository but no luck.

**Comment by bishalg** [comment]
@henrydeclety : any updates on this issue ?

This working for case where user has connected there Spotify Account else its NOT working.

This must be a implementation bug on the SDK coz - if we check the Spotify Web API Console 
https://developer.spotify.com/web-api/console/get-search-item/

It clearly says we need token 
```
{
  "error" : {
    "status" : 401,
    "message" : "No token provided"
  }
}
```

But from iOS SDK Code it says access token can be nil.
https://github.com/spotify/ios-sdk/blob/54261ba981991218e86bdb72de04f25ce3a164a8/SpotifyMetadata.framework/Headers/SPTSearch.h#L39
`@param accessToken A valid access token, or `nil`.`

**Comment by arirawr** [comment]
Hi @henrydeclety and @bishalg! 

You do indeed need an access token for all requests to the Spotify API, as per this change: [https://developer.spotify.com/news-stories/2017/01/27/removing-unauthenticated-calls-to-the-web-api/](https://developer.spotify.com/news-stories/2017/01/27/removing-unauthenticated-calls-to-the-web-api/)

I've made a note to update the documentation for the iOS SDK. Good catch, and thanks for flagging this.

**Comment by arirawr** [comment]
This has now been updated in the documentation!
