### ISSUE TITLE
Error : Unexpected status: 405

### ISSUE THREAD

**Issue by manjunathgudisi** [spotify/ios-sdk#866]
*If you are filing a bug report, please include information for the topics below. Also, please make sure to only report one bug/feature request/question per issue.*

## Description
Getting **Unexpected status: 405** error

### Versions
iOS SDK version: iOS10
Spotify app version: Im not using Spotify iOS SDK. Instead, Im running the below code.

```
public func loadSpotifyAccessToken(completionHandler: @escaping (Bool) -> Void) -> URLSessionDataTask {
        let urlBuilder = "http://accounts.spotify.com/api/token"
        var request = URLRequest(url: URL(string: urlBuilder)!)
        request.httpMethod = "POST"
        request.httpBody = "grant_type=client_credentials".data(using: String.Encoding.utf8)
        request.setValue("application/x-www-form-urlencoded", forHTTPHeaderField: "Content-Type")
        request.setValue("Basic " + SPOTIFY_CLIENT_ID_SECRET, forHTTPHeaderField: "Authorization")
        return ApiConfig.instance().executeRequest(request: request, completionHandler: { (dt, response, error) in
            guard error == nil, let data = dt else {
                completionHandler(false)
                return
            }
            let json = ApiConfig.instance().convertToJsonObject(data: data) as? [String: Any]
            let accessToken = json?["access_token"] as? String
            if !(accessToken?.isEmpty ?? true) {
                self.spotifyAccessToken = accessToken!
                completionHandler(true)
                return
            }
            completionHandler(false)
        })
    }
```
I have a valid SPOTIFY_CLIENT_ID_SECRET and its working fine in Postman. Im able to get the token from Postman using same SPOTIFY_CLIENT_ID_SECRET.

### Severity
Trivial

## Steps to Reproduce
Just run the above code

### Actual behaviour
"{\"error\":\"server_error\",\"error_description\":\"Unexpected status: 405\"}"

### Expected behaviour
It should return JSON feed like below
{
    "access_token": "xxxxxx",
    "token_type": "Bearer",
    "expires_in": 3600
}

## Logs
<Nothing>

**Comment by manjunathgudisi** [comment]
Hi, Anyone help me on this plz. Thanks, Manju

**Comment by hughrawlinson** [comment]
Hi @manjunathgudisi - we usually see this error when your authorization header is malformed. Regardless, you should not implement the client credentials oauth flow (or any other oauth flows that require a client secret) in an iOS client. It's trivial for an attacker to grep your binary for your client secret, which would enable them to make requests on behalf of your app. You should remove any client secret from your app, and implement a backend to handle this authentication flow securely without exposing your client secret. For your reference, [here's an example implementation](https://glitch.com/edit/#!/spotify-client-credentials?path=README.md:1:0) of the client flow in node.js. If you ever suspect that your client secret has been compromised (and if you have distributed a binary containing your client secret, you should suspect that it has), you must regenerate your client id in the settings of your application on developer.spotifiy.com, which will revoke all existing access and refresh tokens.
