### ISSUE TITLE
Why is this rule existing?

### ISSUE THREAD

**Issue by trilleplay** [spotify/ios-sdk#867]
The iOS SDK is explicitly prohibited from use for in-car apps, alarm clock apps, ring-tone apps, voice-assistants, **broadcast aka “listen together” apps**, and to create offline experiences for wearable or other devices.

The bold part of the text is what I'm talking about?
So why, spotify?

**Comment by hughrawlinson** [comment]
Hey @trilleplay,

These kinds of restrictions are usually due to licensing agreements. They're unlikely to change in the short term.

Best,

Spotify Developer Support
