### ISSUE TITLE
Frameworks not found - SpotifyAuthentication or SpotifyAudioPlayback

### ISSUE THREAD

**Issue by HaynesStephens** [spotify/ios-sdk#871]
## Description
I completed the Beginner's Tutorial, but when I tried to run the app I got the following error:  "Build Failed: Apple Mach-O Linker Error - Linker command failed with exit code 1 (use -v to see invocation)". When I look at the error further it says, "ld: framework not found SpotifyAuthentication." 

<img width="735" alt="screen shot 2017-07-22 at 6 56 45 pm" src="https://user-images.githubusercontent.com/18712416/28496791-9d7874f4-6f0f-11e7-9d34-83cacbdef4f7.png">

I believe this is happening because SpotifyAuthentication is at the top of the list. When I put SpotifyAudioPlayback at the top, then it returns the error "ld: framework not found SpotifyAudioPlayback." 

### Versions
iOS SDK version beta 25
Xcode version 8.3.3
Spotify app version (if native SSO flow is involved)

### Severity
Trivial. I'm new to Swift and Xcode so I don't think this is a tough issue at all, I just don't know what the fix is.

## Steps to Reproduce
1. I downloaded the beta 25 version of the iOS SDK, unzipped it, and moved it into a directory on my desktop.
2. I completed the Beginner Tutorial, to my knowledge, exactly. I dragged in the frameworks from the unzipped file into my Xcode project. I inputted "-ObjC" into the Other Linker Flags and I inputted my Client ID and Callback URL into the AppDelegate.m file. 
3. I clicked the "Run" button in Xcode.

### Actual behaviour
I got the following error:  "Build Failed: Apple Mach-O Linker Error - Linker command failed with exit code 1 (use -v to see invocation)". When I look at the error further it says, "ld: framework not found SpotifyAuthentication."

### Expected behaviour
I expected the app to open in the simulator and work properly, playing that song that is referenced in the tutorial instructions.

**Comment by AEDWIP** [comment]
I followed the direction very carefully. I am using objc and everything worked as expected. xcode is xcode so I do not think the issues is swift vs. Objc. My guess is that maybe you did not copy the spotify frameworks into your local xcode project?

**Comment by HaynesStephens** [comment]
Oh okay. I was under the impression that you could load the framework from any directory. So I moved the Frameworks and the AppDelegate.h file and the AppDelegate.m file all into my project directory, spotifyTut/, and the building succeeds, **but now I get another issue**. 
<img width="309" alt="screen shot 2017-07-23 at 9 08 57 am" src="https://user-images.githubusercontent.com/18712416/28502147-a44644dc-6f87-11e7-8e2b-e7a8cb5f548f.png">

The app doesn't open a browser for log in or play any songs. It just stays at the white screen and is silent. The only output that I get is a message that ends in `[MC] Reading from private effective user settings.`, but nothing past that. **Any idea what could be going on here?**
<img width="325" alt="screen shot 2017-07-23 at 9 20 31 am" src="https://user-images.githubusercontent.com/18712416/28502172-39a75e08-6f88-11e7-8088-fcc7018be936.png">

**Comment by andrebng** [comment]
On Xcode 9, it worked for me after I added the frameworks directly under "Build Phases" -> "Link Binary With Libraries" -> "+" and selecting the frameworks. Before I removed the frameworks that have been added there.

**Comment by hughrawlinson** [comment]
@HaynesStephens did @andrebng's fix work for you? If not, please feel free to reopen this ticket.

**Comment by cdarbs11** [comment]
EXACT same thing as Hayes is happening to me, and I believe I followed the tutorial precisely. Andrebng's fix did not solve the issue: I get a white screen shown here-

<img width="1280" alt="screen shot 2017-11-18 at 10 05 01 pm" src="https://user-images.githubusercontent.com/23706559/32987956-34e570de-ccae-11e7-96e4-c5c757b1a41c.png">

And a messages in the debug navigator as follows:
<img width="1280" alt="screen shot 2017-11-18 at 10 04 44 pm" src="https://user-images.githubusercontent.com/23706559/32987962-66b3e7bc-ccae-11e7-8252-921a8f527e42.png">

Alot of deprecated errors:
<img width="1280" alt="screen shot 2017-11-18 at 10 18 45 pm" src="https://user-images.githubusercontent.com/23706559/32987969-8e2ed2ac-ccae-11e7-83a7-907b47761d0f.png">

<img width="628" alt="screen shot 2017-11-18 at 10 18 59 pm" src="https://user-images.githubusercontent.com/23706559/32987971-981bd080-ccae-11e7-9f1e-de235410669a.png">

Any ideas Hugh and others? Woud be incredibly appreciated as I've been bumping my head against a wall for hours figuratively, and am tempted to start doing it literally.
