### ISSUE TITLE
Can't get a preview_url - "Null" preview_url

### ISSUE THREAD

**Issue by balutaeugen** [spotify/ios-sdk#874]
## Description
Can't get a preview_url

### Versions
iOS SDK version - 25 beta

### Severity
Major

## Steps to Reproduce
Just try to get a request to Web API in order to get a preview_url

### Actual behaviour
Can't get a preview_url, because it's "null" every time

### Expected behaviour
To actually get a preview_url

## Logs
```
"id" : "3n3Ppam7vgaVa1iaRUc9Lp",
  "name" : "Mr. Brightside",
  "popularity" : 79,
  "preview_url" : null,
  "track_number" : 2,
  "type" : "track",
```

**Comment by hughrawlinson** [comment]
Hi @balutaeugen - [as documented](https://developer.spotify.com/web-api/get-track/), the preview url will be null when a preview is not available. A preview can be unavailable for many reasons, including licensing, technical, or product.

**Comment by AkhilNairAmey** [comment]
@balutaeugen This is a confusing answer when OP has used the example on the documentation page which clearly shows the `preview_url` as not null. It is obvious the preview url will be null when the preview is not available. What is not obvious is why practice is different to the example in the API documentation.
