### ISSUE TITLE
Are you going to have an iOS or MacOS SDK that is purely implemented in Swift 3/4?

### ISSUE THREAD

**Issue by shyamalschandra** [spotify/ios-sdk#876]
Are you going to have an iOS or MacOS SDK that is purely implemented in Swift 3/4?

**Comment by hughrawlinson** [comment]
Hi @shyamalschandra - probably not. Spotify isn't a swift shop, so it seems unlikely to me that we'll build an SDK implemented in Swift 3/4. However, any future versions of this SDK will likely be callable from Swift 3/4.
