### ISSUE TITLE
Adding scope ugc-image-upload to SPTAuth.defaultInstance().requestedScopes

### ISSUE THREAD

**Issue by mennolaan** [spotify/ios-sdk#878]
Per api https://developer.spotify.com/web-api/upload-a-custom-playlist-cover-image/

I like to add ugs-image-upload to my requestScope property of SPTAuth.defaultInstance().requestedScopes, therefor I will be able to set up a custom url put request. The problem is that the current enum in ios sdk doenst have a scope for ugc-image-upload. Wich will influence the accesstoken received from SPTAuth.defaultInstance().requestedScopes. 

### Versions
iOS SDK version
Beta-25

### Severity
Minor

### Actual behaviour
 error =     {
        message = "Unauthorized.";
        status = 401;
    };

### Expected behaviour
 Succes =     {
        message = "Accepted.";
        status = 202;
    };

**Comment by hughrawlinson** [comment]
Thanks for the report @mennolaan - we'll look into it.

**Comment by bih** [comment]
Hey @mennolaan,

I went ahead and added this in a branch. Check out the `ugc-image-upload` branch on this repository. Here's [a convenient link to it](https://github.com/spotify/ios-sdk/pull/903).

Use that and try this in your `AppDelegate.m` file:
```objc
auth.requestedScopes = @[SPTAuthStreamingScope, SPTAuthUgcImageUploadScope];
```

I think that should solve your problem. Can you let me know if this works for you?

**Comment by mennolaan** [comment]
Thank you bih, I had found that same workaround by manually setting the request scopes by hand instead of enums. But I was a bit afraid that if I was using this feature in my ios app while even the official spotify app didn't have this feature, somehow my dev key would be banned ;) Glad to hear that the solution is a official solution.
