### ISSUE TITLE
Playback of non-Streamed music

### ISSUE THREAD

**Issue by JonJC** [spotify/ios-sdk#879]
Hi - I've just read https://github.com/spotify/ios-sdk/issues/308
I'm assuming that that answer is still valid - i.e.
1. there's no way for an (iOS) app to access songs downloaded by the Spotify app
2. there's no way for an (iOS) app to download songs from Spotify API (which would make sense from a Copyright perspective I'm sure)

in other words - an iOS app can ONLY STREAM from Spotify. Is that right?

Also - is there some way of being automatically alerted of updates to the Spotify SDK, or other developer news?

**Comment by arirawr** [comment]
Hi @JonJC, offline access or downloading with the mobile SDKs is not on our roadmap at the moment.

If you want to stay up to date, [https://developer.spotify.com](https://developer.spotify.com) is the source of truth, and we post updates to Twitter as [@SpotifyPlatform](https://twitter.com/SpotifyPlatform).

**Comment by arirawr** [comment]
You can also subscribe to our newsletter here: http://eepurl.com/Z2qfn
