### ISSUE TITLE
App rejected by App Review for displaying album artwork

### ISSUE THREAD

**Issue by dlo** [spotify/ios-sdk#881]
## Description

Apple rejected our app for displaying album artwork. We mentioned to the review team that album artwork was covered in the Spotify developer terms of use, but they did not accept that as a rationale. Here is the full text from their review:

> Your app includes protected album cover artworks in app icons, screenshots or previews without the necessary authorization.
>
> Please see attached screenshots for details.
>
> Your app and its contents should not infringe upon the rights of another party. In the event your app infringes another party’s rights, you are responsible for any liability to Apple because of a claim.
>
> Next Steps
>
> To resolve this issue, please provide documentary evidence of rights to use this content. Once we have reviewed your documentation and confirmed its validity, we will proceed with the review of your app.
>
> Alternatively, please remove all protected third-party album cover artwork from your app icons, screenshots and previews.

What can we provide to Apple to prove that we have the rights to display album artwork per the terms of the Spotify developer agreement? Is there something we can point them to?

### Versions

N/A

### Severity

Major

## Steps to Reproduce
1. Use the Spotify SDK to stream songs, and display album artwork to let the user know what track is playing
2. Submit to the App Store.

### Actual behaviour

The app is rejected for displaying album artwork.

### Expected behaviour

The app passes review.

**Comment by AEDWIP** [comment]
Hi Dan

I ran into the same problem. Are they rejecting your app or just the meta
data you uploaded to iTunes. I.E. Screen shots. In my case they just
complained about unlicensed art work. So I commented out the image display
code on a test device and took new screen shots. My production version shows
the artwork

Andy

From:  Dan Loewenherz <notifications@github.com>
Reply-To:  spotify/ios-sdk
<reply+00725a2f86b6c0d294696c9834efebc7e47a6e32b1c8573992cf0000000115c6a0cd9
2a169ce0f385cfe@reply.github.com>
Date:  Tuesday, September 5, 2017 at 10:30 AM
To:  spotify/ios-sdk <ios-sdk@noreply.github.com>
Cc:  Subscribed <subscribed@noreply.github.com>
Subject:  [spotify/ios-sdk] App rejected by App Review for displaying album
artwork (#881)

**Comment by dlo** [comment]
Andy—great point! What a great idea. I'll wait to hear back from App Review and will then give this a shot and follow up. Thanks for the advice.

**Comment by hughrawlinson** [comment]
Hi @dlo - I've heard of Apple rejecting apps for displaying copyrighted content in the app store metadata & screenshots before, so I'd recommend trying @AEDWIP's approach.

**Comment by irfaan** [comment]
Hey @dlo - did you end up removing/replacing the offending screenshots or were you able to reason with Apple?
