### ISSUE TITLE
Issues receiving data from Spotify to our app. 

### ISSUE THREAD

**Issue by jesseshortt** [spotify/ios-sdk#883]
Hey guys. My app Aurafy, prior to updating to iOS 11 was working perfectly fine with Spotify and now there seems to be something wrong with the connection between the apps. Can I submit a support ticket to have this looked at? My dev team has done crashalytics and haven’t found anything and we believe it’s possibly an issue with Spotify. I’ve already looked on the developer support but couldn’t find a solution. Thanks in advance! -Jesse

**Comment by hughrawlinson** [comment]
Hi Jesse, what specifically is the issue you're seeing in iOS 11?

**Comment by jesseshortt** [comment]
Thanks Hugh,

It seems the issue has been resolved.

Thanks,

Jesse
