### ISSUE TITLE
iOS SDK - Notification / Track Control when Track is played in Spotify-App

### ISSUE THREAD

**Issue by SeniorGmd** [spotify/ios-sdk#884]
Hi,

in fact, i've searched google and github for a possible solution for this issue - without success.

The issue is:
- The iOS-Spotify-App is playing a track.
- A third-party-app (mine) it authorized via the Spotify-App. The scope SPTAuthStreamingScope and "user-read-currently-playing" is applied.
- The third-party-app (mine) does not play any track at all. 
- Still the Spotify-App is playing. 
- My App did not receive any notification when a track is changed in the Spotify App and / or the MPMusicPlayerController will be used to play, pause skip ... a track.

[[NSNotificationCenter defaultCenter] addObserver:self selector:@selector(playbackChanged) name:MPMusicPlayerControllerNowPlayingItemDidChangeNotification object:[MPMusicPlayerController systemMusicPlayer]];
[[MPMusicPlayerController systemMusicPlayer] beginGeneratingPlaybackNotifications];

Is there is a solution for that? Any kind of notification that a third-party-app can observe from the native Main-Spotify-App? 

Thanks in advance

**Comment by hughrawlinson** [comment]
Hi @SeniorGmd - at the moment, there's no way to observe the playback of devices outside of the iOS SDK instance. You could poll our [currently playing track](https://developer.spotify.com/web-api/get-the-users-currently-playing-track/) endpoint of our Web API using the same token that you use in the iOS SDK instantiation, but be careful of running into rate limits!
