### ISSUE TITLE
Android Auto Suggestions for improvement

### ISSUE THREAD

**Issue by HighPryority** [spotify/ios-sdk#885]
First of all I would like to disclose that I am in no way a programmer. I have very basic understanding of Java and CSS but from there it is all literally another language to me. However I am an ideas man and I thought what better way to get my ideas made into a reality then to talk to programmers who can speak code.

I am currently using Android Auto through my Samsung S7 and XAV-AX100 Sony Head Unit.
Spotify app version:8.4.19.792 armV7
Android Auto version:2.6.573464

I currently use Android Auto in my car and predominately use it for listening to Spotify. After using it for six months I had a couple of ideas to improve the experience. The first suggestion should be a relatively simple fix but let me explain it and I'll let you guys decide that. 

When playing from my songs section of my library it is as if Android Auto has produced a random order that it sticks to, rather then playing them in the order that they were added in or in alphabetical order. Its quite frustrating because when I just want to listen to my favorite new One direction song (I swear their songs aren't just for girls) that is the most recent song added to my library.  I have to unplug my phone, select the song, then plug it back in and jam out to the song. 

What my suggestion would be is to change the order from whatever the Android Auto system select to just the order it appears in my app, plain and simple date order. That way when I haven't gotten around to creating my latest hot-fire playlist I can just listen to my most recently saved songs and happily confess my love for Zane (no homo).

While its not necessarily a bug I would put the severity to catastrophic because I'm a little bit of a drama queen and it might get someone onto it quicker. I don't really have any logs for the issue either as its how the program is designed to behave.

Second Idea which I'd hazard a guess is a little harder to create (so if your up for a challenge) Is smarter voice commands through the google assistant. For example as I'm listening to my hot-fire playlist and a particular artist is speaking to me and I want to hear more of them I would like to be able to say something along the lines of "OK google play more of this artist" and Spotify looks at the artist and plays the most popular songs in order just as it usually would if you had searched for the artist through voice command.

This would also be beneficial for when you're listening to an artist with a hard to pronounce name or where a more popular artist with a similar name exists. For example when you say "OK google play Childish Gambino" It cant find the artist. If I am already listening to one of his songs I can say "OK google play more of this artist" and Spotify doesn't even have to stuff around with trying to understand which artist I'm looking for, its already playing them and can pull up the rest of his songs. 

Also on that if it was easy enough to add in commands such as the one I'm suggesting. You could take it one step further and add in a command such as "OK Google play the rest of this Album" Which I notice is already an option in the Spotify app with the "view artist" and "view album" links. So it wouldn't be a case of adding in the coding to get Spotify to look for that it would just be linking the already existing shortcuts to voice commands.

Please go easy on me and remember coding is not my strong point. If I sound like some mum with an iPhone asking why you cant send interdimensional nudes who has no idea how big of an ask it is please let me know :)

Thanks,
Luke

**Comment by hughrawlinson** [comment]
Hi Luke,

Thanks for the enthusiasm! You can file feature suggestions with our customer support team over on [our community site](community.spotify.com). This forum is specifically for features requests and bug reports for our Software Development Kit for iOS.

Best,

Spotify Developer Support
