### ISSUE TITLE
Offline Playback Through Third-Party Apps

### ISSUE THREAD

**Issue by bonbonio** [spotify/ios-sdk#887]
## Description
Provide an update on whether it is still in the roadmap to provide a manner of allowing a Premium Users downloaded songs to be played from the local storage rather than re-streaming it in Third-Party Apps

### Versions
Affects Android and iOS

## Steps to Reproduce
None needed.

### Actual behaviour
A Premium User downloads songs to play offline using the Official Spotify App, and when these same songs are accessed in a Third-Party App on the same device, we are only provided streaming references.

### Expected behaviour
Provide an identifier with the track details that contains a reference to the Spotify on-device storage/cache so that we can look there if its present, and if so play that - should it not be found we would be able to revert back to the streaming URL in use now. Ideally and hopefully the identifier would be the same for downloaded tracks on Android and iOS and then it could work cross-platform without adding a large volume of further data to the API response payloads.

I feel this would be a benefit to your Users (increases the utility of Spotify in Third-Party Apps) and it should also lessen the burden on streaming media from your end.

An alternative would be for Third-Party Apps to allow the User to download tracks for offline use in a cache specific to the Third-Party App. This would satisfy the need but consume more storage space on the device.

I have seen many threads (some several years old) where Spotify have said this feature is on the roadmap - is this still the case? Is there any clarity that can be provided?

## Logs
None needed.

**Comment by hughrawlinson** [comment]
Hi! We're aware that offline is an important feature for the community. It's not planned for release in at the moment, so don't expect it soon. I'll keep this issue open as a feature request (the other open issue for offline playback is specifically in the context of playlists).

**Comment by mnlgr** [comment]
Hi! Any updates about this feature? It would be awesome.
Thanks !

**Comment by mswork** [comment]
Strongly needed feature.

**Comment by mrpossoms** [comment]
I'm with everyone above. This would be huge.

**Comment by arirawr** [comment]
Hi all - I'm happy to let you know that offline playback is supported through our new App Remote SDK (available on iOS and Android), which allows you to remote control the Spotify mobile app. You can check it out for iOS [here](https://beta.developer.spotify.com/documentation/ios-app-remote/) and for Android [here](https://beta.developer.spotify.com/documentation/android-app-remote/).

There are no plans to support it through this particular SDK so I will close this issue.
