### ISSUE TITLE
audioStreamingDidLogin method does not get called in Beta 25

### ISSUE THREAD

**Issue by everythingswift** [spotify/ios-sdk#897]
*If you are filing a bug report, please include information for the topics below. Also, please make sure to only report one bug/feature request/question per issue.*

## Description
The player does not start playing as login method success callback is never received.

### Versions
iOS SDK version
Beta 25

### Severity
Major

## Steps to Reproduce
1. Integrated iOS SDK as explained on the developer portal.
2. OAuth flow is good - can get the app to launch spotify login page, and come back to the app after successful authentication.
3. I've a notification setup on the AppDelegate on successful return to the app after OAuth flow, which triggers the player's login method. 
`
 if self.player == nil {
            self.player = SPTAudioStreamingController.sharedInstance()
        }
        self.player!.delegate = self
        try! player?.start(withClientId: auth.clientID)
        self.player!.login(withAccessToken: authSession.accessToken)
`
4. View Controller does adopt to SPTAudioStreamingDelegate
//class ViewController: UIViewController, SPTAudioStreamingDelegate
Below methods never get called
`   
func audioStreamingDidLogin(_ audioStreaming: SPTAudioStreamingController!) {
        self.player.playSpotifyURI("spotify:track:58s6EuEYJdlb0kO7awm3Vp", startingWith: 0, startingWithPosition: 0) { (error) in
            if error != nil{
                print("Failed to playback")
            }
        }
    }
    
    func audioStreamingDidEncounterTemporaryConnectionError(_ audioStreaming: SPTAudioStreamingController!) {
        print("audioStreamingDidEncounterTemporaryConnectionError")
    }
    
    func audioStreaming(_ audioStreaming: SPTAudioStreamingController!, didReceiveError error: Error!) {
        print(error.localizedDescription)
    }
`

### Actual behaviour
The delegate method with succesful loginCall back is not getting called.

### Expected behaviour
 The delegate method should be called.
   func audioStreamingDidLogin(_ audioStreaming: SPTAudioStreamingController!) {

## Logs
2017-12-20 21:57:03.256993-0600 Spotify1[12184:662325] [BoringSSL] Function boringssl_session_errorlog: line 2871 [boringssl_session_read] SSL_ERROR_ZERO_RETURN(6): operation failed because the connection was cleanly shut down with a close_notify alert
2017-12-20 21:57:03.257365-0600 Spotify1[12184:662325] [BoringSSL] Function boringssl_session_errorlog: line 2871 [boringssl_session_read] SSL_ERROR_ZERO_RETURN(6): operation failed because the connection was cleanly shut down with a close_notify alert

**Comment by GokmenAkar** [comment]
Have you found any solution? I have the same kind of error.

**Comment by everythingswift** [comment]
@GokmenAkar I've not been able to find a solution in Swift. However please try the sample Objective-C project. That seems to work fine. I've left this issue open in terms of Swift implementation.

**Comment by GokmenAkar** [comment]
@everythingswift Oh, I'll try obj-c. Have you example project? I need to solve playing problem immediately

**Comment by arirawr** [comment]
Hey @everythingswift and @GokmenAkar - here is some sample code in Swift that has worked for me, let me know if this helps: https://gist.github.com/arirawr/c9220042caff1605fa8eeb929847cfc4

**Comment by kainosobata** [comment]
Hi. I'm facing same issue.

`SPTAuth.defaultInstance().handleAuthCallback` was succeeded and I can get `session` with no `error`.

Then I call  `SPTAudioStreamingController.sharedInstance().login(withAccessToken: receivedSession)`
But `SPTAudioStreamingDelegate` delegate methods are never called. (`audioStreamingDidLogin`, `audioStreamingDidLogout`, `audioStreamingDidReconnect`, `audioStreamingDidDisconnect`) 

I set delegate as below.

```swift
let player = SPTAudioStreamingController.sharedInstance()
try! player.start(withClientId: clientID)  // 先に呼ぶ必要あり
player.delegate = self
```

**Comment by kainosobata** [comment]
My issue is solved. It's my fault. 

`SPTAudioStreamingController.sharedInstance().login(withAccessToken )` is available only on **Premium Account**, but mine is not premium account. 

I was stuck in this problem in three hours XD
Thanks.

**Comment by arirawr** [comment]
Glad to hear you solved it! I'm going to go ahead and close this issue. @everythingswift feel free to reopen if that doesn't solve your error.
