### ISSUE TITLE
Initiating song with a certain URI starts playing the same song with a different URI

### ISSUE THREAD

**Issue by asklausen** [spotify/ios-sdk#899]
As the title suggests, I'm initiating one URI, and it plays another URI. Both URIs reflect the same song though.

Example:
Initiate this URI: spotify:track:0KklLSXgYW5k4m78YaBIIt
And you'll see that it starts playing this URI: spotify:track:62QlXQyslXFx0ca8GbiPWK.
Both URIs belong to a song called Something Better - Two Friends Remix

Platform:
iOS 11.0

**Comment by Next-Age-Code** [comment]
Same issue with Albums, there are two identical albums with different uri, even tho on official client there is only one album 🤔

**Comment by arirawr** [comment]
Hi @asklausen - looks like you've run into [**Track Relinking**](https://beta.developer.spotify.com/documentation/general/guides/track-relinking-guide/).

If you take a look at [this console query](https://beta.developer.spotify.com/console/get-track/?id=0KklLSXgYW5k4m78YaBIIt&market=DK) for "Get Track" for the track you mentioned, specifying a market of Denmark, you can see that it does indeed return the other URI you mentioned. Scroll down, and you'll see a field `linked_from` in the response, which contains the original track from the query.

Track relinking is a way of getting the instance of a track that is available in the user's market. In your case, the track `0KklLSXgYW5k4m78YaBIIt` is not available in Denmark, so the API finds the linked track `62QlXQyslXFx0ca8GbiPWK`.

You can read the full Track Relinking guide [here](https://beta.developer.spotify.com/documentation/general/guides/track-relinking-guide/).
