### ISSUE TITLE
Not possible to play a list of tracks

### ISSUE THREAD

**Issue by spacecar** [spotify/ios-sdk#9]
The WebAPI allows you to pass an array of URI's to the start playback endpoint, but there doesn't seem to be a corresponding function on the SPTAppRemotePlayerAPI. Is this something that will be fixed or is there some other solution?

**Comment by hughrawlinson** [comment]
Thanks for the suggestion, @spacecar. I'll bring this to the team and see if they have any thoughts.

**Comment by jackfreeman** [comment]
@spacecar does `- (void)enqueueTrackUri:(NSString*)trackUri callback:(nullable SPTAppRemoteCallback)callback;` on `SPTAppRemotePlayerAPI` solve this problem for you?

**Comment by spacecar** [comment]
@jackfreeman Most likely it would solve our problems. Is this a new method on `SPTAppRemotePlayerAPI` or where do I find it?

**Comment by jackfreeman** [comment]
@spacecar unfortunately this method is missing documentation in this release, but can found in the source of SPTAppRemotePlayerAPI [here](https://github.com/spotify/ios-sdk/blob/master/SpotifyiOS.framework/Versions/A/Headers/SPTAppRemotePlayerAPI.h#L162)

Sorry for the mistake, documentation for this method has been added for the next release:

    /**
     * Adds a track to the user's currently playing queue
     *
     * @param trackUri The track URI to add to the queue
     * @param callback On success `result` will be `YES`
     *                 On error `result` will be `nil` and error set
     */
     - (void)enqueueTrackUri:(NSString*)trackUri callback:(nullable SPTAppRemoteCallback)callback;
