### ISSUE TITLE
Reopening Issue 880 - Unable to refresh session: encryptedRefreshToken is nil

### ISSUE THREAD

**Issue by JonJC** [spotify/ios-sdk#901]
Hi - issue 880 was closed, but not resolved - nobody appears to me monitoring it - so I thought I'd raise a new issue.
Could you please look at #880 (probably best to reopen #880 so we preserve the thread)

Thanks all!

**Comment by JonJC** [comment]
aaaargh! Come on Spotify.... what's the point of having an API if you don't support it? 
Things got better for a while, but now this again....
Does anybody monitor this???

**Comment by bih** [comment]
Hey Jon! I'll go ahead and comment on your other issue, to preserve it as you mentioned. As this ticket is a duplicate, I'll close it 👍
