### ISSUE TITLE
Get authorization code through the Authorization Code Flow

### ISSUE THREAD

**Issue by Juliocbr** [spotify/ios-sdk#904]
Hi,

I was wondering if there is any way to get the authorization code through the Authorization Code Flow or can only get the user's token (Implicit Grant Flow) using the library?

**Comment by bih** [comment]
Hi @Juliocbr,

You can get the user's `access_token` from Implicit Grant Flow, as you mentioned. The only problem with that is the user needs to re-authenticate every 60 minutes.

But, with an `authorization_code`, you'll need to exchange that for an `access_token` - which you can do yourself every 60 minutes without requiring the user to re-authenticate.

For iOS, we have an example in Ruby of how to "swap" an `authorization_code` for an `access_token` (which you'd need to do on a separate server, not in your iOS app, for security reasons):
[spotify_token_swap.rb](https://github.com/spotify/ios-sdk/blob/master/Demo%20Projects/spotify_token_swap.rb)
