### ISSUE TITLE
Ruby Token Swap Issue

### ISSUE THREAD

**Issue by qridder** [spotify/ios-sdk#906]
Hi, I downloaded the ruby Spotify token swap.rb file and entered my apps information in the client_id and client secret and call back fields but am getting this error in terminal related to the encryption secret line? 

"syntax error, unexpected tIDENTIFIER, expecting end-of-input
...ykfDmPHtLKLGzViHW9aHGmyTLD8hGXC"

**Comment by khancyai** [comment]
Hi,
Please check your question marks for strings.

**Comment by bih** [comment]
Hi,

In this case, it would be that your string literals are invalid (something like `code = "hey` where you're missing the second `"`).

Though this is part of the iOS SDK bundle, it is not an iOS SDK-related issue and so I'll close the ticket. Feel free to comment with a code sample (excluding your sensitive information) and I can help you resolve that issue if you'd like 🙂
