### ISSUE TITLE
Not able to create developer account

### ISSUE THREAD

**Issue by shkar62** [spotify/ios-sdk#909]
I have been trying to create a developer account and I always get 403 forbidden error. How to fix this?

**Comment by arirawr** [comment]
Hi @shkar62, that's no good! Do you have a Spotify account already or are you trying to create a new one? Also, can you verify that you're in one of our available countries? https://support.spotify.com/us/using_spotify/the_basics/full-list-of-territories-where-spotify-is-available/

**Comment by arirawr** [comment]
Going to mark this as resolved - please re-open if you continue to see the issue.
