### ISSUE TITLE
Change the playlist cover image?

### ISSUE THREAD

**Issue by pvcary** [spotify/ios-sdk#910]
Having trouble finding information on how to change the playlist cover image to a custom image. Can someone point me in the right direction? Thanks!

**Comment by arirawr** [comment]
Hey @pvcary - this isn't supported through the iOS SDK. You can, however, call the Web API endpoint from your app: https://beta.developer.spotify.com/documentation/web-api/reference/playlists/upload-custom-playlist-cover/

**Comment by evgeniyd** [comment]
@arirawr is is _intentionally_ not supported? otherwise, there is a good candidate for feature request.
