### ISSUE TITLE
New developer portal and missing app

### ISSUE THREAD

**Issue by mennolaan** [spotify/ios-sdk#912]
All of the sudden the safari log in callback results in a exec_bad_access error in xcode. I cannot even debug the source and even went back to a commit which im certain worked while switching the login process. 

Couldn't find anything in the code and as I know Spotify SDK is beta for a reason, its sometimes changes core functionality without a headsup. So I went over to the developer dashboard and i see the webiste is updated, nice.

However I cannot find my previously registered app in here, but if I open the safari component it does show the name and information regarding that app.

SO whats the deal, do I need to register(i tried and error persist) How can I check my previously registered app and compare setting in order to debug login process?

**Comment by hughrawlinson** [comment]
Hi @mennolaan - can you send me your Spotify username and client id? If you prefer to keep them private, you can email developer dash support at spotify dot com, or DM us on twitter: @SpotifyPlatform.

**Comment by mennolaan** [comment]
So first I need to apologise. So I got a bit enraged as stuff was not working. Not Spotify's fault! It turns out I was using a depecrated func from Apple. Xcode did not bother to tell me this was not working anymore:
func application(_ application: UIApplication, open url: URL, sourceApplication: String?, annotation: Any) -> Bool

it should be changed to this:
func application(_ app: UIApplication, open url: URL, options: [UIApplicationOpenURLOptionsKey : Any] = [:]) -> Bool
I think this should be here because I assume more people will run into this and I hope my sunday tracking this issue will save some time for other spotify ios sdk users.

However my old app is nowhere to be found and that's inconvenient but as I'm still in development and not released to app store, I made a new app (old one is this working but not to be found on dashboard). To be honest I needed to create a new one as the project name changed and so should the name in Spotify dashboard.

**Comment by hughrawlinson** [comment]
Thanks for sharing that snippet @mennolaan, I'm sure it'll be useful for people! I'm happy to help you find your old client if you still want? For that, I'd need the client ID and your Spotify username, which you can send to me via the email or Twitter account I mentioned above.

**Comment by dewski** [comment]
I hit this as well and happy I headed over to the issue tracker 😄 @mennolaan thanks for figuring that out!

**Comment by mennolaan** [comment]
@dewski Glad to hear! I'm still disappointed in Xcode/Apple for not notifying me about this cridical error. NSZombies didnt help me out either.
