### ISSUE TITLE
Javascript Error in Web Authentication URL

### ISSUE THREAD

**Issue by jkmartin19** [spotify/ios-sdk#916]
## Description
Users of my iOS app are unable to authenticate via Spotify.

I get the authentication URL like this:

```
guard let spotifyUrl = SPTAuth.defaultInstance().spotifyWebAuthenticationURL() else {
    return
}
```

This results in the following URL:
https://accounts.spotify.com/authorize?nolinks=true&utm_source=spotify-sdk&nosignup=true&response_type=code&utm_medium=ios-sdk&utm_campaign=ios-sdk&redirect_uri=getphile%3A%2F%2Fspotify&show_dialog=true&client_id=e87ba5dfe28d46de99a0f9b48a854390

The app opens this URL in Safari, but there is an error on the page. The page gives me this message:

Error
Oops! Something went wrong, please try again or check out our help area

And when I look in the browser console, I see this error:

index.js:6 SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Object.Y [as fromJson] (https://d2d1dxiu3v1f2i.cloudfront.net/d3d1850/js/index.js:5:6501)
    at link (https://d2d1dxiu3v1f2i.cloudfront.net/d3d1850/js/index.js:11:23018)
    at oe (https://d2d1dxiu3v1f2i.cloudfront.net/d3d1850/js/index.js:6:9150)
    at v (https://d2d1dxiu3v1f2i.cloudfront.net/d3d1850/js/index.js:6:2459)
    at s (https://d2d1dxiu3v1f2i.cloudfront.net/d3d1850/js/index.js:5:29990)
    at s (https://d2d1dxiu3v1f2i.cloudfront.net/d3d1850/js/index.js:5:30007)
    at s (https://d2d1dxiu3v1f2i.cloudfront.net/d3d1850/js/index.js:5:30007)
    at https://d2d1dxiu3v1f2i.cloudfront.net/d3d1850/js/index.js:5:29521
    at https://d2d1dxiu3v1f2i.cloudfront.net/d3d1850/js/index.js:5:8769 <script defer="" src="https://d2d1dxiu3v1f2i.cloudfront.net/d3d1850/js/index.js" sp-bootstrap="">

Is this a bug on the Spotify website, or is this a setup issue on my app? This was working previously, so I don't think it is a problem on my end, but I'm not sure. Any help would be appreciated.

### Severity
Major

**Comment by jkmartin19** [comment]
I just opened the auth link in an incognito browser and it prompted me to login as expected. So perhaps this has something to do with the fact that I am already signed in?

**Comment by arirawr** [comment]
Hey there! This is a bug with the accounts page that we are aware of and looking into. I'll update here when it's fixed.

**Comment by jkmartin19** [comment]
Thanks!

**Comment by arirawr** [comment]
Hi @jkmartin19 - this issue should be resolved now! Please let us know if you see any other issues!
