### ISSUE TITLE
Using the scopes "SPTAuthUserFollowReadScope" and "SPTAuthUserReadTopScope"

### ISSUE THREAD

**Issue by markusvtjohansson** [spotify/ios-sdk#917]
I have been looking for a while now regarding how to fetch the artists that the user is following, and I can't seem to find anything in the documentation that could help me do that. The same goes for being able to read the users top played tracks and artists. I thought this was impossible in the iOS SDK until I found the two scopes "SPTAuthUserFollowReadScope" and "SPTAuthUserReadTopScope", which both seem to imply that the things that I'm looking for is possible. My question is therefore, if it actually is possible, what functions or methods can be used to accomplish this? If it is not possible, why are there scopes which clearly implies that it should be?

**Comment by arirawr** [comment]
Hi @markusvtjohansson! Both of those endpoints are available in the Web API. You can use the iOS SDK to authenticate with those scopes, then use the access token you receive to make a HTTP request to the Web API endpoint. Unfortunately these endpoints are not available natively in the iOS SDK.

Here's the reference for Get Followed Artists: https://beta.developer.spotify.com/documentation/web-api/reference/follow/get-followed/
and here's the one for Top Tracks/Artists: https://beta.developer.spotify.com/documentation/web-api/reference/personalization/get-users-top-artists-and-tracks/

Hope that helps!
