### ISSUE TITLE
kTokenSwapService URL objc issue

### ISSUE THREAD

**Issue by Prodigy441** [spotify/ios-sdk#919]
I am having an issue with the code, this one is confusing because it is asking for "#define kTokenSwapServiceURL "http://localhost:1234/swap" and I do not know what that means or where to find it. Please Help!

**Comment by khancyai** [comment]
Hi,

If you need run token exchange service for long lived auth session you must setup it. 

This repo you can use it. 
https://github.com/simontaen/SpotifyTokenSwap

For more information please checkout this: https://beta.developer.spotify.com/documentation/ios-sdk/guides/token-swap-and-refresh/
