### ISSUE TITLE
SPTRequest caching and cancelling

### ISSUE THREAD

**Issue by kennylovrin** [spotify/ios-sdk#92]
Is there any way to cancel a SPTRequest? I'm thinking of a typical use case like a table view with cells that needs to show information (for example a SPTTrack loaded via it's URI). If the user scrolls the list back and forth quickly there is quite a risk of flickering cells when a cell is reused and the initial request supposed to set it's data finishes while another request has been fired for the same cell. If that makes sense.. 

Also, are there any caching at all performed by the SDK? If I request the same track URI for example over and over, will it perform an actual request each time? It's fine, we can cache where we need to and where it would work, but I can't tell right now if it's on us as users of the SDK or the SDK caches requests internally.

**Comment by fishkingsin** [comment]
+1 for both Request cancellation and caching

**Comment by dtrenz** [comment]
+1 for cancellation & caching, in that order. :+1:

**Comment by possan** [comment]
Closing this, this is now supported in the latest release! finally, it took some refactoring :)
