### ISSUE TITLE
Will not allow adding valid Bundle ID

### ISSUE THREAD

**Issue by chasepuskar** [spotify/ios-sdk#920]
## Description
When trying to add a valid Bundle ID (used in App Store and in collaboration with other APIs) on the Spotify App Dashboard, it says "Not a valid Bundle ID".  The Bundle ID has no periods, all lowercase letters, and no spaces.

### Severity
Major

## Steps to Reproduce
1. Go to Spotify Developer App Dashboard
2. Select an App
3. Select "Edit Settings"
4. Enter a Bundle ID without periods
5. Attempt to save settings

### Actual behaviour
"Not a valid Bundle ID" appears below field

### Expected behaviour
Expected Bundle ID to be successfully added.

**Comment by arirawr** [comment]
Hi @chasepuskar, 

According to [Apple's documentation](https://developer.apple.com/library/content/documentation/CoreFoundation/Conceptual/CFBundles/BundleTypes/BundleTypes.html#//apple_ref/doc/uid/10000123i-CH101-SW1), bundle IDs should be in reverse-DNS format (a backwards domain name):

> The bundle identifier string identifies your application to the system.  This string must be a uniform type identifier (UTI) that contains only alphanumeric (A-Z,a-z,0-9), hyphen (-), and period (.) characters. The string should also be in reverse-DNS format. For example, if your company’s domain is Ajax.com and you create an application named Hello, you could assign the string com.Ajax.Hello as your application’s bundle identifier.  The bundle identifier is used in validating the application signature.

This helps ensure that bundle IDs are unique even if application names may be the same. I realise that Apple allows you to input non-standard bundle IDs, but I *highly* recommend you conform to the
standard naming structure. In our app settings, we verify that bundle IDs follow this structure.

If there is a particular reason or use case that causes you to be unable to conform to the reverse-DNS format, please send us an email at developer-support [at] spotify [dot] com and we can see what we can do.
