### ISSUE TITLE
is it possibe to use spotify sdk without user's login

### ISSUE THREAD

**Issue by sahabe1** [spotify/ios-sdk#926]
i want to create ios app using spotify sdk  to play song without using user's login

**Comment by arirawr** [comment]
Hi @sahabe1, all playback requires the user to login. Playback is only supported for Spotify Premium users.

**Comment by sahabe1** [comment]
is it possibe to set acces token validity?

**Comment by arirawr** [comment]
What do you mean by validity? :)

**Comment by sahabe1** [comment]
token is expiring in 1 hour.  is it  posibe to to set token validity forever?

**Comment by arirawr** [comment]
No, all access tokens last for one hour. However, you can refresh the tokens. Take a read through [this guide](https://developer.spotify.com/documentation/ios-sdk/guides/token-swap-and-refresh/) to learn about token refreshing. Hope that helps!

**Comment by arirawr** [comment]
There's also a pre-built token swap service available on GitHub here: https://github.com/bih/spotify-token-swap-service

**Comment by sahabe1** [comment]
can i use https://developer.spotify.com/documentation/general/guides/authorization-guide/#authorization-code-flow for getting acces token for long running time in ios app
