### ISSUE TITLE
How do I setup a backend API for Refresh Token and Token Swap?

### ISSUE THREAD

**Issue by sahabe1** [spotify/ios-sdk#928]

**Comment by bih** [comment]
Hi @sahabe1,

This question has been asked before in #906, #80, #197.

I'll answer it again for your convenience - there's two convenient ways to do this:
- [Remix our project on Glitch](https://glitch.com/~spotify-token-swap)
- [One-click deploy with Heroku](https://github.com/bih/spotify-token-swap-service#one-click-with-heroku)

When generated, you'll have a live URL with two endpoints - refresh token and token swap. If your credentials are entered correctly, you should have a working setup of token swap and refresh token! 👍

**Comment by bih** [comment]
As this has already been answered, I'm going to close this. Feel free to re-open if you continue to have issues 👍

**Comment by sahabe1** [comment]
where i can find code = ? parameter

**Comment by bih** [comment]
That's returned to your application once a user authorizes. If you set your redirect URL to `ios-app://` for example, we'll send your user back to `ios-app://?code=[code here]` if they choose to authorize your application.

**Comment by sahabe1** [comment]
when i am using https://accounts.spotify.com/en/authorize?client_id=d950416c32d14834********4a34bf1e37&response_type=code&redirect_uri=******

i am getting code but its not authorize  and getting error login failed unsupported url
