### ISSUE TITLE
Question regarding Monetization Policy 

### ISSUE THREAD

**Issue by Chase-Klingel** [spotify/ios-sdk#95]
The latest post I could find regarding monetizing our own apps while using Spotify's API states that if you stream content, there are no options to monetize. If you are using the API, but not streaming content, then you may monetize your app. Is this still accurate?

**Comment by kkarayannis** [comment]
There is more information about this [here](https://github.com/spotify/ios-sdk/issues/92) and [here](https://github.com/spotify/ios-sdk/issues/20).
